In [9]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline

riders2013 = pd.read_csv("2013riders_bymonth.csv")
riders2014 = pd.read_csv("2014riders_bymonth.csv")
riders2015 = pd.read_csv("2015riders_bymonth.csv")
riders2016 = pd.read_csv("2016riders_bymonth.csv")
riders2017 = pd.read_csv("2017riders_bymonth.csv")
riders2018 = pd.read_csv("2018riders_bymonth.csv")
riders2019 = pd.read_csv("2019riders_bymonth.csv")
riders2020 = pd.read_csv("2020riders_bymonth.csv")

allrides = pd.read_csv("station_month_year_riders.csv")

riders = {2013: riders2013, 2014: riders2014, 2015: riders2015, 2016: riders2016, 2017: riders2017, 2018: riders2018, 2019: riders2019}
#print(riders[2013][(riders[2013]['stationame'] == '18th')])

In [11]:
for station in riders2020['stationame']:
    for month in range(1,13):
        for year in range(2013,2020):
            ridership = riders[year][(riders[year]['stationame'] == station)][str(month)].astype(int)
            print(station, year, month, ridership)

18th 2013 1 0    45209
Name: 1, dtype: int64
18th 2014 1 0    46217
Name: 1, dtype: int64
18th 2015 1 0    47085
Name: 1, dtype: int64
18th 2016 1 0    46937
Name: 1, dtype: int64
18th 2017 1 0    43545
Name: 1, dtype: int64
18th 2018 1 0    41483
Name: 1, dtype: int64
18th 2019 1 0    37774
Name: 1, dtype: int64
18th 2013 2 0    43826
Name: 2, dtype: int64
18th 2014 2 0    48018
Name: 2, dtype: int64
18th 2015 2 0    47687
Name: 2, dtype: int64
18th 2016 2 0    48592
Name: 2, dtype: int64
18th 2017 2 0    44012
Name: 2, dtype: int64
18th 2018 2 0    39947
Name: 2, dtype: int64
18th 2019 2 0    39459
Name: 2, dtype: int64
18th 2013 3 0    46890
Name: 3, dtype: int64
18th 2014 3 0    54695
Name: 3, dtype: int64
18th 2015 3 0    55931
Name: 3, dtype: int64
18th 2016 3 0    53150
Name: 3, dtype: int64
18th 2017 3 0    49918
Name: 3, dtype: int64
18th 2018 3 0    47031
Name: 3, dtype: int64
18th 2019 3 0    44800
Name: 3, dtype: int64
18th 2013 4 0    49225
Name: 4, dtype: int64
18th 2014 4 0    54155
Name: 4, dtype: int64
18th 2015 4 0    55871
Name: 4, dtype: int64
18th 2016 4 0    49230
Name: 4, dtype: int64
18th 2017 4 0    47984
Name: 4, dtype: int64
18th 2018 4 0    45078
Name: 4, dtype: int64
18th 2019 4 0    46330
Name: 4, dtype: int64
18th 2013 5 0    49580
Name: 5, dtype: int64
18th 2014 5 0    53650
Name: 5, dtype: int64
18th 2015 5 0    56885
Name: 5, dtype: int64
18th 2016 5 0    53193
Name: 5, dtype: int64
18th 2017 5 0    51968
Name: 5, dtype: int64
18th 2018 5 0    50403
Name: 5, dtype: int64
18th 2019 5 0    50367
Name: 5, dtype: int64
18th 2013 6 0    49315
Name: 6, dtype: int64
18th 2014 6 0    51491
Name: 6, dtype: int64
18th 2015 6 0    55444
Name: 6, dtype: int64
18th 2016 6 0    55314
Name: 6, dtype: int64
18th 2017 6 0    54815
Name: 6, dtype: int64
18th 2018 6 0    52183
Name: 6, dtype: int64
18th 2019 6 0    46218
Name: 6, dtype: int64
18th 2013 7 0    52531
Name: 7, dtype: int64
18th 2014 7 0    54550
Name: 7, dtype: int64
18th 2015 7 0    57032
Name: 7, dtype: int64
18th 2016 7 0    51916
Name: 7, dtype: int64
18th 2017 7 0    49672
Name: 7, dtype: int64
18th 2018 7 0    49160
Name: 7, dtype: int64
18th 2019 7 0    48394
Name: 7, dtype: int64
18th 2013 8 0    53121
Name: 8, dtype: int64
18th 2014 8 0    52930
Name: 8, dtype: int64
18th 2015 8 0    54435
Name: 8, dtype: int64
18th 2016 8 0    51504
Name: 8, dtype: int64
18th 2017 8 0    50610
Name: 8, dtype: int64
18th 2018 8 0    0
Name: 8, dtype: int64
18th 2019 8 0    48968
Name: 8, dtype: int64
18th 2013 9 0    52430
Name: 9, dtype: int64
18th 2014 9 0    56674
Name: 9, dtype: int64
18th 2015 9 0    59917
Name: 9, dtype: int64
18th 2016 9 0    53657
Name: 9, dtype: int64
18th 2017 9 0    52100
Name: 9, dtype: int64
18th 2018 9 0    0
Name: 9, dtype: int64
18th 2019 9 0    48349
Name: 9, dtype: int64
18th 2013 10 0    59578
Name: 10, dtype: int64
18th 2014 10 0    63062
Name: 10, dtype: int64
18th 2015 10 0    62697
Name: 10, dtype: int64
18th 2016 10 0    57029
Name: 10, dtype: int64
18th 2017 10 0    54559
Name: 10, dtype: int64
18th 2018 10 0    0
Name: 10, dtype: int64
18th 2019 10 0    53567
Name: 10, dtype: int64
18th 2013 11 0    50809
Name: 11, dtype: int64
18th 2014 11 0    52543
Name: 11, dtype: int64
18th 2015 11 0    54028
Name: 11, dtype: int64
18th 2016 11 0    50206
Name: 11, dtype: int64
18th 2017 11 0    47590
Name: 11, dtype: int64
18th 2018 11 0    0
Name: 11, dtype: int64
18th 2019 11 0    45109
Name: 11, dtype: int64
18th 2013 12 0    46140
Name: 12, dtype: int64
18th 2014 12 0    48912
Name: 12, dtype: int64
18th 2015 12 0    49585
Name: 12, dtype: int64
18th 2016 12 0    42987
Name: 12, dtype: int64
18th 2017 12 0    41491
Name: 12, dtype: int64
18th 2018 12 0    0
Name: 12, dtype: int64
18th 2019 12 0    40754
Name: 12, dtype: int64
35-Bronzeville-IIT 2013 1 1    54802
Name: 1, dtype: int64
35-Bronzeville-IIT 2014 1 1    53326
Name: 1, dtype: int64
35-Bronzeville-IIT 2015 1 1    50498
Name: 1, dtype: int64
35-Bronzeville-IIT 2016 1 1    46246
Name: 1, dtype: int64
35-Bronzeville-IIT 2017 1 1    41734
Name: 1, dtype: int64
35-Bronzeville-IIT 2018 1 1    41031
Name: 1, dtype: int64
35-Bronzeville-IIT 2019 1 1    34814
Name: 1, dtype: int64
35-Bronzeville-IIT 2013 2 1    55037
Name: 2, dtype: int64
35-Bronzeville-IIT 2014 2 1    57402
Name: 2, dtype: int64
35-Bronzeville-IIT 2015 2 1    48235
Name: 2, dtype: int64
35-Bronzeville-IIT 2016 2 1    48582
Name: 2, dtype: int64
35-Bronzeville-IIT 2017 2 1    42972
Name: 2, dtype: int64
35-Bronzeville-IIT 2018 2 1    39340
Name: 2, dtype: int64
35-Bronzeville-IIT 2019 2 1    38677
Name: 2, dtype: int64
35-Bronzeville-IIT 2013 3 1    57203
Name: 3, dtype: int64
35-Bronzeville-IIT 2014 3 1    63458
Name: 3, dtype: int64
35-Bronzeville-IIT 2015 3 1    56524
Name: 3, dtype: int64
35-Bronzeville-IIT 2016 3 1    50802
Name: 3, dtype: int64
35-Bronzeville-IIT 2017 3 1    45725
Name: 3, dtype: int64
35-Bronzeville-IIT 2018 3 1    42824
Name: 3, dtype: int64
35-Bronzeville-IIT 2019 3 1    42182
Name: 3, dtype: int64
35-Bronzeville-IIT 2013 4 1    62132
Name: 4, dtype: int64
35-Bronzeville-IIT 2014 4 1    63541
Name: 4, dtype: int64
35-Bronzeville-IIT 2015 4 1    56650
Name: 4, dtype: int64
35-Bronzeville-IIT 2016 4 1    49316
Name: 4, dtype: int64
35-Bronzeville-IIT 2017 4 1    44256
Name: 4, dtype: int64
35-Bronzeville-IIT 2018 4 1    42437
Name: 4, dtype: int64
35-Bronzeville-IIT 2019 4 1    42988
Name: 4, dtype: int64
35-Bronzeville-IIT 2013 5 1    96994
Name: 5, dtype: int64
35-Bronzeville-IIT 2014 5 1    57731
Name: 5, dtype: int64
35-Bronzeville-IIT 2015 5 1    53901
Name: 5, dtype: int64
35-Bronzeville-IIT 2016 5 1    46756
Name: 5, dtype: int64
35-Bronzeville-IIT 2017 5 1    41680
Name: 5, dtype: int64
35-Bronzeville-IIT 2018 5 1    41393
Name: 5, dtype: int64
35-Bronzeville-IIT 2019 5 1    40079
Name: 5, dtype: int64
35-Bronzeville-IIT 2013 6 1    135871
Name: 6, dtype: int64
35-Bronzeville-IIT 2014 6 1    51875
Name: 6, dtype: int64
35-Bronzeville-IIT 2015 6 1    55671
Name: 6, dtype: int64
35-Bronzeville-IIT 2016 6 1    46254
Name: 6, dtype: int64
35-Bronzeville-IIT 2017 6 1    41701
Name: 6, dtype: int64
35-Bronzeville-IIT 2018 6 1    39895
Name: 6, dtype: int64
35-Bronzeville-IIT 2019 6 1    31349
Name: 6, dtype: int64
35-Bronzeville-IIT 2013 7 1    163900
Name: 7, dtype: int64
35-Bronzeville-IIT 2014 7 1    55254
Name: 7, dtype: int64
35-Bronzeville-IIT 2015 7 1    58436
Name: 7, dtype: int64
35-Bronzeville-IIT 2016 7 1    46453
Name: 7, dtype: int64
35-Bronzeville-IIT 2017 7 1    40078
Name: 7, dtype: int64
35-Bronzeville-IIT 2018 7 1    41052
Name: 7, dtype: int64
35-Bronzeville-IIT 2019 7 1    42534
Name: 7, dtype: int64
35-Bronzeville-IIT 2013 8 1    178602
Name: 8, dtype: int64
35-Bronzeville-IIT 2014 8 1    59190
Name: 8, dtype: int64
35-Bronzeville-IIT 2015 8 1    56667
Name: 8, dtype: int64
35-Bronzeville-IIT 2016 8 1    48353
Name: 8, dtype: int64
35-Bronzeville-IIT 2017 8 1    49505
Name: 8, dtype: int64
35-Bronzeville-IIT 2018 8 1    0
Name: 8, dtype: int64
35-Bronzeville-IIT 2019 8 1    46716
Name: 8, dtype: int64
35-Bronzeville-IIT 2013 9 1    174381
Name: 9, dtype: int64
35-Bronzeville-IIT 2014 9 1    67369
Name: 9, dtype: int64
35-Bronzeville-IIT 2015 9 1    63203
Name: 9, dtype: int64
35-Bronzeville-IIT 2016 9 1    55974
Name: 9, dtype: int64
35-Bronzeville-IIT 2017 9 1    54569
Name: 9, dtype: int64
35-Bronzeville-IIT 2018 9 1    0
Name: 9, dtype: int64
35-Bronzeville-IIT 2019 9 1    48386
Name: 9, dtype: int64
35-Bronzeville-IIT 2013 10 1    138550
Name: 10, dtype: int64
35-Bronzeville-IIT 2014 10 1    71437
Name: 10, dtype: int64
35-Bronzeville-IIT 2015 10 1    66603
Name: 10, dtype: int64
35-Bronzeville-IIT 2016 10 1    55499
Name: 10, dtype: int64
35-Bronzeville-IIT 2017 10 1    56328
Name: 10, dtype: int64
35-Bronzeville-IIT 2018 10 1    0
Name: 10, dtype: int64
35-Bronzeville-IIT 2019 10 1    47505
Name: 10, dtype: int64
35-Bronzeville-IIT 2013 11 1    62687
Name: 11, dtype: int64
35-Bronzeville-IIT 2014 11 1    53033
Name: 11, dtype: int64
35-Bronzeville-IIT 2015 11 1    54643
Name: 11, dtype: int64
35-Bronzeville-IIT 2016 11 1    49688
Name: 11, dtype: int64
35-Bronzeville-IIT 2017 11 1    48257
Name: 11, dtype: int64
35-Bronzeville-IIT 2018 11 1    0
Name: 11, dtype: int64
35-Bronzeville-IIT 2019 11 1    37047
Name: 11, dtype: int64
35-Bronzeville-IIT 2013 12 1    49905
Name: 12, dtype: int64
35-Bronzeville-IIT 2014 12 1    49081
Name: 12, dtype: int64
35-Bronzeville-IIT 2015 12 1    45153
Name: 12, dtype: int64
35-Bronzeville-IIT 2016 12 1    36205
Name: 12, dtype: int64
35-Bronzeville-IIT 2017 12 1    35603
Name: 12, dtype: int64
35-Bronzeville-IIT 2018 12 1    0
Name: 12, dtype: int64
35-Bronzeville-IIT 2019 12 1    28402
Name: 12, dtype: int64
35th/Archer 2013 1 2    69894
Name: 1, dtype: int64
35th/Archer 2014 1 2    67981
Name: 1, dtype: int64
35th/Archer 2015 1 2    70724
Name: 1, dtype: int64
35th/Archer 2016 1 2    72756
Name: 1, dtype: int64
35th/Archer 2017 1 2    70638
Name: 1, dtype: int64
35th/Archer 2018 1 2    69728
Name: 1, dtype: int64
35th/Archer 2019 1 2    63280
Name: 1, dtype: int64
35th/Archer 2013 2 2    66850
Name: 2, dtype: int64
35th/Archer 2014 2 2    70977
Name: 2, dtype: int64
35th/Archer 2015 2 2    68041
Name: 2, dtype: int64
35th/Archer 2016 2 2    77541
Name: 2, dtype: int64
35th/Archer 2017 2 2    73442
Name: 2, dtype: int64
35th/Archer 2018 2 2    67494
Name: 2, dtype: int64
35th/Archer 2019 2 2    65831
Name: 2, dtype: int64
35th/Archer 2013 3 2    73422
Name: 3, dtype: int64
35th/Archer 2014 3 2    81543
Name: 3, dtype: int64
35th/Archer 2015 3 2    81146
Name: 3, dtype: int64
35th/Archer 2016 3 2    85958
Name: 3, dtype: int64
35th/Archer 2017 3 2    83818
Name: 3, dtype: int64
35th/Archer 2018 3 2    76222
Name: 3, dtype: int64
35th/Archer 2019 3 2    74550
Name: 3, dtype: int64
35th/Archer 2013 4 2    77511
Name: 4, dtype: int64
35th/Archer 2014 4 2    81260
Name: 4, dtype: int64
35th/Archer 2015 4 2    80490
Name: 4, dtype: int64
35th/Archer 2016 4 2    82980
Name: 4, dtype: int64
35th/Archer 2017 4 2    76057
Name: 4, dtype: int64
35th/Archer 2018 4 2    75824
Name: 4, dtype: int64
35th/Archer 2019 4 2    74935
Name: 4, dtype: int64
35th/Archer 2013 5 2    80904
Name: 5, dtype: int64
35th/Archer 2014 5 2    78749
Name: 5, dtype: int64
35th/Archer 2015 5 2    81240
Name: 5, dtype: int64
35th/Archer 2016 5 2    84890
Name: 5, dtype: int64
35th/Archer 2017 5 2    82899
Name: 5, dtype: int64
35th/Archer 2018 5 2    81501
Name: 5, dtype: int64
35th/Archer 2019 5 2    79585
Name: 5, dtype: int64
35th/Archer 2013 6 2    77753
Name: 6, dtype: int64
35th/Archer 2014 6 2    77871
Name: 6, dtype: int64
35th/Archer 2015 6 2    84193
Name: 6, dtype: int64
35th/Archer 2016 6 2    84871
Name: 6, dtype: int64
35th/Archer 2017 6 2    81646
Name: 6, dtype: int64
35th/Archer 2018 6 2    77181
Name: 6, dtype: int64
35th/Archer 2019 6 2    74129
Name: 6, dtype: int64
35th/Archer 2013 7 2    79670
Name: 7, dtype: int64
35th/Archer 2014 7 2    78852
Name: 7, dtype: int64
35th/Archer 2015 7 2    87497
Name: 7, dtype: int64
35th/Archer 2016 7 2    80998
Name: 7, dtype: int64
35th/Archer 2017 7 2    77983
Name: 7, dtype: int64
35th/Archer 2018 7 2    0
Name: 7, dtype: int64
35th/Archer 2019 7 2    76951
Name: 7, dtype: int64
35th/Archer 2013 8 2    82437
Name: 8, dtype: int64

35th/Archer 2014 8 2    77772
Name: 8, dtype: int64
35th/Archer 2015 8 2    83949
Name: 8, dtype: int64
35th/Archer 2016 8 2    83149
Name: 8, dtype: int64
35th/Archer 2017 8 2    83948
Name: 8, dtype: int64
35th/Archer 2018 8 2    0
Name: 8, dtype: int64
35th/Archer 2019 8 2    77527
Name: 8, dtype: int64
35th/Archer 2013 9 2    85328
Name: 9, dtype: int64
35th/Archer 2014 9 2    84155
Name: 9, dtype: int64
35th/Archer 2015 9 2    90541
Name: 9, dtype: int64
35th/Archer 2016 9 2    87731
Name: 9, dtype: int64
35th/Archer 2017 9 2    86364
Name: 9, dtype: int64
35th/Archer 2018 9 2    0
Name: 9, dtype: int64
35th/Archer 2019 9 2    82115
Name: 9, dtype: int64
35th/Archer 2013 10 2    92030
Name: 10, dtype: int64
35th/Archer 2014 10 2    89597
Name: 10, dtype: int64
35th/Archer 2015 10 2    94119
Name: 10, dtype: int64
35th/Archer 2016 10 2    89009
Name: 10, dtype: int64
35th/Archer 2017 10 2    88874
Name: 10, dtype: int64
35th/Archer 2018 10 2    0
Name: 10, dtype: int64
35th/Archer 2019 10 2    86984
Name: 10, dtype: int64
35th/Archer 2013 11 2    78341
Name: 11, dtype: int64
35th/Archer 2014 11 2    73777
Name: 11, dtype: int64
35th/Archer 2015 11 2    81983
Name: 11, dtype: int64
35th/Archer 2016 11 2    83563
Name: 11, dtype: int64
35th/Archer 2017 11 2    80665
Name: 11, dtype: int64
35th/Archer 2018 11 2    0
Name: 11, dtype: int64
35th/Archer 2019 11 2    73498
Name: 11, dtype: int64
35th/Archer 2013 12 2    72051
Name: 12, dtype: int64
35th/Archer 2014 12 2    74131
Name: 12, dtype: int64
35th/Archer 2015 12 2    79175
Name: 12, dtype: int64
35th/Archer 2016 12 2    71010
Name: 12, dtype: int64
35th/Archer 2017 12 2    69860
Name: 12, dtype: int64
35th/Archer 2018 12 2    0
Name: 12, dtype: int64
35th/Archer 2019 12 2    66907
Name: 12, dtype: int64
43rd 2013 1 3    25400
Name: 1, dtype: int64
43rd 2014 1 3    26652
Name: 1, dtype: int64
43rd 2015 1 3    25034
Name: 1, dtype: int64
43rd 2016 1 3    26151
Name: 1, dtype: int64
43rd 2017 1 3    23998
Name: 1, dtype: int64
43rd 2018 1 3    23610
Name: 1, dtype: int64
43rd 2019 1 3    20798
Name: 1, dtype: int64
43rd 2013 2 3    24122
Name: 2, dtype: int64
43rd 2014 2 3    27161
Name: 2, dtype: int64
43rd 2015 2 3    23378
Name: 2, dtype: int64
43rd 2016 2 3    26168
Name: 2, dtype: int64
43rd 2017 2 3    23378
Name: 2, dtype: int64
43rd 2018 2 3    22349
Name: 2, dtype: int64
43rd 2019 2 3    21026
Name: 2, dtype: int64
43rd 2013 3 3    25631
Name: 3, dtype: int64
43rd 2014 3 3    30873
Name: 3, dtype: int64
43rd 2015 3 3    27802
Name: 3, dtype: int64
43rd 2016 3 3    28258
Name: 3, dtype: int64
43rd 2017 3 3    25852
Name: 3, dtype: int64
43rd 2018 3 3    24658
Name: 3, dtype: int64
43rd 2019 3 3    22658
Name: 3, dtype: int64
43rd 2013 4 3    28026
Name: 4, dtype: int64
43rd 2014 4 3    30499
Name: 4, dtype: int64
43rd 2015 4 3    28122
Name: 4, dtype: int64
43rd 2016 4 3    26313
Name: 4, dtype: int64
43rd 2017 4 3    24494
Name: 4, dtype: int64
43rd 2018 4 3    24843
Name: 4, dtype: int64
43rd 2019 4 3    23119
Name: 4, dtype: int64
43rd 2013 5 3    33028
Name: 5, dtype: int64
43rd 2014 5 3    31469
Name: 5, dtype: int64
43rd 2015 5 3    29182
Name: 5, dtype: int64
43rd 2016 5 3    28594
Name: 5, dtype: int64
43rd 2017 5 3    27021
Name: 5, dtype: int64
43rd 2018 5 3    27796
Name: 5, dtype: int64
43rd 2019 5 3    25185
Name: 5, dtype: int64
43rd 2013 6 3    38924
Name: 6, dtype: int64
43rd 2014 6 3    29751
Name: 6, dtype: int64
43rd 2015 6 3    30991
Name: 6, dtype: int64
43rd 2016 6 3    29016
Name: 6, dtype: int64
43rd 2017 6 3    28392
Name: 6, dtype: int64
43rd 2018 6 3    27308
Name: 6, dtype: int64
43rd 2019 6 3    24711
Name: 6, dtype: int64
43rd 2013 7 3    42997
Name: 7, dtype: int64
43rd 2014 7 3    33066
Name: 7, dtype: int64
43rd 2015 7 3    33242
Name: 7, dtype: int64
43rd 2016 7 3    28917
Name: 7, dtype: int64
43rd 2017 7 3    27975
Name: 7, dtype: int64
43rd 2018 7 3    28420
Name: 7, dtype: int64
43rd 2019 7 3    26747
Name: 7, dtype: int64
43rd 2013 8 3    45461
Name: 8, dtype: int64
43rd 2014 8 3    33108
Name: 8, dtype: int64
43rd 2015 8 3    32592
Name: 8, dtype: int64
43rd 2016 8 3    30370
Name: 8, dtype: int64
43rd 2017 8 3    29815
Name: 8, dtype: int64
43rd 2018 8 3    0
Name: 8, dtype: int64
43rd 2019 8 3    26441
Name: 8, dtype: int64
43rd 2013 9 3    44917
Name: 9, dtype: int64
43rd 2014 9 3    32200
Name: 9, dtype: int64
43rd 2015 9 3    31778
Name: 9, dtype: int64
43rd 2016 9 3    29097
Name: 9, dtype: int64
43rd 2017 9 3    28105
Name: 9, dtype: int64
43rd 2018 9 3    0
Name: 9, dtype: int64
43rd 2019 9 3    25280
Name: 9, dtype: int64
43rd 2013 10 3    44413
Name: 10, dtype: int64
43rd 2014 10 3    33249
Name: 10, dtype: int64
43rd 2015 10 3    33748
Name: 10, dtype: int64
43rd 2016 10 3    29734
Name: 10, dtype: int64
43rd 2017 10 3    29156
Name: 10, dtype: int64
43rd 2018 10 3    0
Name: 10, dtype: int64
43rd 2019 10 3    26804
Name: 10, dtype: int64
43rd 2013 11 3    30701
Name: 11, dtype: int64
43rd 2014 11 3    27083
Name: 11, dtype: int64
43rd 2015 11 3    29574
Name: 11, dtype: int64
43rd 2016 11 3    27136
Name: 11, dtype: int64
43rd 2017 11 3    25764
Name: 11, dtype: int64
43rd 2018 11 3    0
Name: 11, dtype: int64
43rd 2019 11 3    21558
Name: 11, dtype: int64
43rd 2013 12 3    28678
Name: 12, dtype: int64
43rd 2014 12 3    28172
Name: 12, dtype: int64
43rd 2015 12 3    28842
Name: 12, dtype: int64
43rd 2016 12 3    23745
Name: 12, dtype: int64
43rd 2017 12 3    24280
Name: 12, dtype: int64
43rd 2018 12 3    0
Name: 12, dtype: int64
43rd 2019 12 3    21089
Name: 12, dtype: int64
47th-Dan Ryan 2013 1 4    79341
Name: 1, dtype: int64
47th-Dan Ryan 2014 1 4    64771
Name: 1, dtype: int64
47th-Dan Ryan 2015 1 4    82257
Name: 1, dtype: int64
47th-Dan Ryan 2016 1 4    81853
Name: 1, dtype: int64
47th-Dan Ryan 2017 1 4    74650
Name: 1, dtype: int64
47th-Dan Ryan 2018 1 4    71256
Name: 1, dtype: int64
47th-Dan Ryan 2019 1 4    63395
Name: 1, dtype: int64
47th-Dan Ryan 2013 2 4    73431
Name: 2, dtype: int64
47th-Dan Ryan 2014 2 4    70644
Name: 2, dtype: int64
47th-Dan Ryan 2015 2 4    75432
Name: 2, dtype: int64
47th-Dan Ryan 2016 2 4    82189
Name: 2, dtype: int64
47th-Dan Ryan 2017 2 4    72555
Name: 2, dtype: int64
47th-Dan Ryan 2018 2 4    66707
Name: 2, dtype: int64
47th-Dan Ryan 2019 2 4    64104
Name: 2, dtype: int64
47th-Dan Ryan 2013 3 4    80169
Name: 3, dtype: int64
47th-Dan Ryan 2014 3 4    83505
Name: 3, dtype: int64
47th-Dan Ryan 2015 3 4    90736
Name: 3, dtype: int64
47th-Dan Ryan 2016 3 4    90425
Name: 3, dtype: int64
47th-Dan Ryan 2017 3 4    82190
Name: 3, dtype: int64
47th-Dan Ryan 2018 3 4    76065
Name: 3, dtype: int64
47th-Dan Ryan 2019 3 4    70660
Name: 3, dtype: int64
47th-Dan Ryan 2013 4 4    81340
Name: 4, dtype: int64
47th-Dan Ryan 2014 4 4    83779
Name: 4, dtype: int64
47th-Dan Ryan 2015 4 4    89883
Name: 4, dtype: int64
47th-Dan Ryan 2016 4 4    86137
Name: 4, dtype: int64
47th-Dan Ryan 2017 4 4    76694
Name: 4, dtype: int64
47th-Dan Ryan 2018 4 4    74971
Name: 4, dtype: int64
47th-Dan Ryan 2019 4 4    69705
Name: 4, dtype: int64
47th-Dan Ryan 2013 5 4    48346
Name: 5, dtype: int64
47th-Dan Ryan 2014 5 4    90626
Name: 5, dtype: int64
47th-Dan Ryan 2015 5 4    94329
Name: 5, dtype: int64
47th-Dan Ryan 2016 5 4    91301
Name: 5, dtype: int64
47th-Dan Ryan 2017 5 4    85109
Name: 5, dtype: int64
47th-Dan Ryan 2018 5 4    82719
Name: 5, dtype: int64
47th-Dan Ryan 2019 5 4    76269
Name: 5, dtype: int64
47th-Dan Ryan 2013 6 4    0
Name: 6, dtype: int64
47th-Dan Ryan 2014 6 4    85967
Name: 6, dtype: int64
47th-Dan Ryan 2015 6 4    93706
Name: 6, dtype: int64
47th-Dan Ryan 2016 6 4    88804
Name: 6, dtype: int64
47th-Dan Ryan 2017 6 4    85830
Name: 6, dtype: int64
47th-Dan Ryan 2018 6 4    79548
Name: 6, dtype: int64
47th-Dan Ryan 2019 6 4    73560
Name: 6, dtype: int64
47th-Dan Ryan 2013 7 4    0
Name: 7, dtype: int64
47th-Dan Ryan 2014 7 4    91203
Name: 7, dtype: int64
47th-Dan Ryan 2015 7 4    97163
Name: 7, dtype: int64
47th-Dan Ryan 2016 7 4    89895
Name: 7, dtype: int64
47th-Dan Ryan 2017 7 4    72155
Name: 7, dtype: int64
47th-Dan Ryan 2018 7 4    80330
Name: 7, dtype: int64
47th-Dan Ryan 2019 7 4    78151
Name: 7, dtype: int64
47th-Dan Ryan 2013 8 4    0
Name: 8, dtype: int64
47th-Dan Ryan 2014 8 4    89002
Name: 8, dtype: int64
47th-Dan Ryan 2015 8 4    93622
Name: 8, dtype: int64
47th-Dan Ryan 2016 8 4    88842
Name: 8, dtype: int64
47th-Dan Ryan 2017 8 4    64510
Name: 8, dtype: int64
47th-Dan Ryan 2018 8 4    0
Name: 8, dtype: int64
47th-Dan Ryan 2019 8 4    79400
Name: 8, dtype: int64
47th-Dan Ryan 2013 9 4    25643
Name: 9, dtype: int64
47th-Dan Ryan 2014 9 4    96234
Name: 9, dtype: int64
47th-Dan Ryan 2015 9 4    96044
Name: 9, dtype: int64
47th-Dan Ryan 2016 9 4    90233
Name: 9, dtype: int64
47th-Dan Ryan 2017 9 4    61712
Name: 9, dtype: int64
47th-Dan Ryan 2018 9 4    0
Name: 9, dtype: int64
47th-Dan Ryan 2019 9 4    76728
Name: 9, dtype: int64
47th-Dan Ryan 2013 10 4    68632
Name: 10, dtype: int64
47th-Dan Ryan 2014 10 4    101814
Name: 10, dtype: int64
47th-Dan Ryan 2015 10 4    101988
Name: 10, dtype: int64
47th-Dan Ryan 2016 10 4    92876
Name: 10, dtype: int64
47th-Dan Ryan 2017 10 4    83468
Name: 10, dtype: int64
47th-Dan Ryan 2018 10 4    0
Name: 10, dtype: int64
47th-Dan Ryan 2019 10 4    78389
Name: 10, dtype: int64
47th-Dan Ryan 2013 11 4    69155
Name: 11, dtype: int64
47th-Dan Ryan 2014 11 4    90034
Name: 11, dtype: int64
47th-Dan Ryan 2015 11 4    88552
Name: 11, dtype: int64
47th-Dan Ryan 2016 11 4    86238
Name: 11, dtype: int64
47th-Dan Ryan 2017 11 4    77945
Name: 11, dtype: int64
47th-Dan Ryan 2018 11 4    0
Name: 11, dtype: int64
47th-Dan Ryan 2019 11 4    70697
Name: 11, dtype: int64
47th-Dan Ryan 2013 12 4    0
Name: 12, dtype: int64
47th-Dan Ryan 2014 12 4    91062
Name: 12, dtype: int64
47th-Dan Ryan 2015 12 4    88329
Name: 12, dtype: int64
47th-Dan Ryan 2016 12 4    76412
Name: 12, dtype: int64
47th-Dan Ryan 2017 12 4    72682
Name: 12, dtype: int64
47th-Dan Ryan 2018 12 4    0
Name: 12, dtype: int64
47th-Dan Ryan 2019 12 4    68803
Name: 12, dtype: int64
47th-South Elevated 2013 1 5    33272
Name: 1, dtype: int64
47th-South Elevated 2014 1 5    32286
Name: 1, dtype: int64
47th-South Elevated 2015 1 5    30718
Name: 1, dtype: int64
47th-South Elevated 2016 1 5    32884
Name: 1, dtype: int64
47th-South Elevated 2017 1 5    28194
Name: 1, dtype: int64
47th-South Elevated 2018 1 5    27766
Name: 1, dtype: int64
47th-South Elevated 2019 1 5    23441
Name: 1, dtype: int64
47th-South Elevated 2013 2 5    32626
Name: 2, dtype: int64
47th-South Elevated 2014 2 5    34938
Name: 2, dtype: int64
47th-South Elevated 2015 2 5    30284
Name: 2, dtype: int64
47th-South Elevated 2016 2 5    32955
Name: 2, dtype: int64
47th-South Elevated 2017 2 5    28201
Name: 2, dtype: int64
47th-South Elevated 2018 2 5    26607
Name: 2, dtype: int64
47th-South Elevated 2019 2 5    23494
Name: 2, dtype: int64
47th-South Elevated 2013 3 5    33861
Name: 3, dtype: int64
47th-South Elevated 2014 3 5    39301
Name: 3, dtype: int64
47th-South Elevated 2015 3 5    35545
Name: 3, dtype: int64
47th-South Elevated 2016 3 5    35208
Name: 3, dtype: int64
47th-South Elevated 2017 3 5    31221
Name: 3, dtype: int64
47th-South Elevated 2018 3 5    29733
Name: 3, dtype: int64
47th-South Elevated 2019 3 5    25741
Name: 3, dtype: int64
47th-South Elevated 2013 4 5    34916
Name: 4, dtype: int64
47th-South Elevated 2014 4 5    38057
Name: 4, dtype: int64
47th-South Elevated 2015 4 5    35953
Name: 4, dtype: int64
47th-South Elevated 2016 4 5    32186
Name: 4, dtype: int64
47th-South Elevated 2017 4 5    29294
Name: 4, dtype: int64
47th-South Elevated 2018 4 5    28092
Name: 4, dtype: int64
47th-South Elevated 2019 4 5    26132
Name: 4, dtype: int64
47th-South Elevated 2013 5 5    45211
Name: 5, dtype: int64
47th-South Elevated 2014 5 5    39893
Name: 5, dtype: int64
47th-South Elevated 2015 5 5    36446
Name: 5, dtype: int64
47th-South Elevated 2016 5 5    33602
Name: 5, dtype: int64
47th-South Elevated 2017 5 5    31871
Name: 5, dtype: int64
47th-South Elevated 2018 5 5    30393
Name: 5, dtype: int64
47th-South Elevated 2019 5 5    27646
Name: 5, dtype: int64
47th-South Elevated 2013 6 5    57389
Name: 6, dtype: int64
47th-South Elevated 2014 6 5    39232
Name: 6, dtype: int64
47th-South Elevated 2015 6 5    37866
Name: 6, dtype: int64
47th-South Elevated 2016 6 5    33118
Name: 6, dtype: int64
47th-South Elevated 2017 6 5    33021
Name: 6, dtype: int64
47th-South Elevated 2018 6 5    28650
Name: 6, dtype: int64
47th-South Elevated 2019 6 5    27124
Name: 6, dtype: int64
47th-South Elevated 2013 7 5    63177
Name: 7, dtype: int64
47th-South Elevated 2014 7 5    42662
Name: 7, dtype: int64
47th-South Elevated 2015 7 5    41207
Name: 7, dtype: int64
47th-South Elevated 2016 7 5    33495
Name: 7, dtype: int64
47th-South Elevated 2017 7 5    32478
Name: 7, dtype: int64
47th-South Elevated 2018 7 5    30961
Name: 7, dtype: int64
47th-South Elevated 2019 7 5    30072
Name: 7, dtype: int64
47th-South Elevated 2013 8 5    66334
Name: 8, dtype: int64
47th-South Elevated 2014 8 5    43651
Name: 8, dtype: int64
47th-South Elevated 2015 8 5    40777
Name: 8, dtype: int64
47th-South Elevated 2016 8 5    34235
Name: 8, dtype: int64
47th-South Elevated 2017 8 5    34024
Name: 8, dtype: int64
47th-South Elevated 2018 8 5    0
Name: 8, dtype: int64
47th-South Elevated 2019 8 5    30131
Name: 8, dtype: int64
47th-South Elevated 2013 9 5    64135
Name: 9, dtype: int64
47th-South Elevated 2014 9 5    42126
Name: 9, dtype: int64
47th-South Elevated 2015 9 5    39712
Name: 9, dtype: int64
47th-South Elevated 2016 9 5    33130
Name: 9, dtype: int64
47th-South Elevated 2017 9 5    32697
Name: 9, dtype: int64
47th-South Elevated 2018 9 5    0
Name: 9, dtype: int64
47th-South Elevated 2019 9 5    27361
Name: 9, dtype: int64
47th-South Elevated 2013 10 5    60841
Name: 10, dtype: int64
47th-South Elevated 2014 10 5    42653
Name: 10, dtype: int64
47th-South Elevated 2015 10 5    41695
Name: 10, dtype: int64
47th-South Elevated 2016 10 5    33261
Name: 10, dtype: int64
47th-South Elevated 2017 10 5    33464
Name: 10, dtype: int64
47th-South Elevated 2018 10 5    0
Name: 10, dtype: int64
47th-South Elevated 2019 10 5    28419
Name: 10, dtype: int64
47th-South Elevated 2013 11 5    38744
Name: 11, dtype: int64
47th-South Elevated 2014 11 5    32179
Name: 11, dtype: int64
47th-South Elevated 2015 11 5    36338
Name: 11, dtype: int64
47th-South Elevated 2016 11 5    31454
Name: 11, dtype: int64
47th-South Elevated 2017 11 5    30940
Name: 11, dtype: int64
47th-South Elevated 2018 11 5    0
Name: 11, dtype: int64
47th-South Elevated 2019 11 5    23046
Name: 11, dtype: int64
47th-South Elevated 2013 12 5    35661
Name: 12, dtype: int64
47th-South Elevated 2014 12 5    32384
Name: 12, dtype: int64
47th-South Elevated 2015 12 5    36263
Name: 12, dtype: int64
47th-South Elevated 2016 12 5    28651
Name: 12, dtype: int64
47th-South Elevated 2017 12 5    28513
Name: 12, dtype: int64
47th-South Elevated 2018 12 5    0
Name: 12, dtype: int64
47th-South Elevated 2019 12 5    22370
Name: 12, dtype: int64
51st 2013 1 6    29527
Name: 1, dtype: int64
51st 2014 1 6    27757
Name: 1, dtype: int64
51st 2015 1 6    25178
Name: 1, dtype: int64
51st 2016 1 6    26069
Name: 1, dtype: int64
51st 2017 1 6    22904
Name: 1, dtype: int64
51st 2018 1 6    23280
Name: 1, dtype: int64
51st 2019 1 6    22410
Name: 1, dtype: int64
51st 2013 2 6    27240
Name: 2, dtype: int64
51st 2014 2 6    28569
Name: 2, dtype: int64
51st 2015 2 6    24282
Name: 2, dtype: int64
51st 2016 2 6    25989
Name: 2, dtype: int64
51st 2017 2 6    22720
Name: 2, dtype: int64
51st 2018 2 6    21824
Name: 2, dtype: int64
51st 2019 2 6    21508
Name: 2, dtype: int64
51st 2013 3 6    28830
Name: 3, dtype: int64
51st 2014 3 6    31834
Name: 3, dtype: int64
51st 2015 3 6    29557
Name: 3, dtype: int64
51st 2016 3 6    28700
Name: 3, dtype: int64
51st 2017 3 6    25382
Name: 3, dtype: int64
51st 2018 3 6    25350
Name: 3, dtype: int64
51st 2019 3 6    23750
Name: 3, dtype: int64
51st 2013 4 6    30665
Name: 4, dtype: int64
51st 2014 4 6    30727
Name: 4, dtype: int64
51st 2015 4 6    30313
Name: 4, dtype: int64
51st 2016 4 6    27177
Name: 4, dtype: int64
51st 2017 4 6    23231
Name: 4, dtype: int64
51st 2018 4 6    24012
Name: 4, dtype: int64
51st 2019 4 6    23503
Name: 4, dtype: int64
51st 2013 5 6    36702
Name: 5, dtype: int64
51st 2014 5 6    32363
Name: 5, dtype: int64

51st 2015 5 6    31134
Name: 5, dtype: int64
51st 2016 5 6    28292
Name: 5, dtype: int64
51st 2017 5 6    25231
Name: 5, dtype: int64
51st 2018 5 6    26047
Name: 5, dtype: int64
51st 2019 5 6    24736
Name: 5, dtype: int64
51st 2013 6 6    42981
Name: 6, dtype: int64
51st 2014 6 6    29756
Name: 6, dtype: int64
51st 2015 6 6    31940
Name: 6, dtype: int64
51st 2016 6 6    29061
Name: 6, dtype: int64
51st 2017 6 6    25721
Name: 6, dtype: int64
51st 2018 6 6    25798
Name: 6, dtype: int64
51st 2019 6 6    23750
Name: 6, dtype: int64
51st 2013 7 6    46131
Name: 7, dtype: int64
51st 2014 7 6    29950
Name: 7, dtype: int64
51st 2015 7 6    33798
Name: 7, dtype: int64
51st 2016 7 6    29238
Name: 7, dtype: int64
51st 2017 7 6    25877
Name: 7, dtype: int64
51st 2018 7 6    26980
Name: 7, dtype: int64
51st 2019 7 6    26601
Name: 7, dtype: int64
51st 2013 8 6    47999
Name: 8, dtype: int64
51st 2014 8 6    31403
Name: 8, dtype: int64
51st 2015 8 6    32482
Name: 8, dtype: int64
51st 2016 8 6    28476
Name: 8, dtype: int64
51st 2017 8 6    28586
Name: 8, dtype: int64
51st 2018 8 6    0
Name: 8, dtype: int64
51st 2019 8 6    26611
Name: 8, dtype: int64
51st 2013 9 6    48155
Name: 9, dtype: int64
51st 2014 9 6    31398
Name: 9, dtype: int64
51st 2015 9 6    32884
Name: 9, dtype: int64
51st 2016 9 6    28087
Name: 9, dtype: int64
51st 2017 9 6    27610
Name: 9, dtype: int64
51st 2018 9 6    0
Name: 9, dtype: int64
51st 2019 9 6    25086
Name: 9, dtype: int64
51st 2013 10 6    46777
Name: 10, dtype: int64
51st 2014 10 6    33630
Name: 10, dtype: int64
51st 2015 10 6    33899
Name: 10, dtype: int64
51st 2016 10 6    28739
Name: 10, dtype: int64
51st 2017 10 6    28589
Name: 10, dtype: int64
51st 2018 10 6    0
Name: 10, dtype: int64
51st 2019 10 6    25956
Name: 10, dtype: int64
51st 2013 11 6    32823
Name: 11, dtype: int64
51st 2014 11 6    27283
Name: 11, dtype: int64
51st 2015 11 6    28474
Name: 11, dtype: int64
51st 2016 11 6    25983
Name: 11, dtype: int64
51st 2017 11 6    25305
Name: 11, dtype: int64
51st 2018 11 6    0
Name: 11, dtype: int64
51st 2019 11 6    22072
Name: 11, dtype: int64
51st 2013 12 6    29619
Name: 12, dtype: int64
51st 2014 12 6    27639
Name: 12, dtype: int64
51st 2015 12 6    28848
Name: 12, dtype: int64
51st 2016 12 6    23564
Name: 12, dtype: int64
51st 2017 12 6    23203
Name: 12, dtype: int64
51st 2018 12 6    0
Name: 12, dtype: int64
51st 2019 12 6    22124
Name: 12, dtype: int64
54th/Cermak 2013 1 7    50230
Name: 1, dtype: int64
54th/Cermak 2014 1 7    47726
Name: 1, dtype: int64
54th/Cermak 2015 1 7    52284
Name: 1, dtype: int64
54th/Cermak 2016 1 7    51595
Name: 1, dtype: int64
54th/Cermak 2017 1 7    50832
Name: 1, dtype: int64
54th/Cermak 2018 1 7    48504
Name: 1, dtype: int64
54th/Cermak 2019 1 7    45524
Name: 1, dtype: int64
54th/Cermak 2013 2 7    46750
Name: 2, dtype: int64
54th/Cermak 2014 2 7    48840
Name: 2, dtype: int64
54th/Cermak 2015 2 7    49342
Name: 2, dtype: int64
54th/Cermak 2016 2 7    51860
Name: 2, dtype: int64
54th/Cermak 2017 2 7    50115
Name: 2, dtype: int64
54th/Cermak 2018 2 7    46293
Name: 2, dtype: int64
54th/Cermak 2019 2 7    46026
Name: 2, dtype: int64
54th/Cermak 2013 3 7    51684
Name: 3, dtype: int64
54th/Cermak 2014 3 7    55074
Name: 3, dtype: int64
54th/Cermak 2015 3 7    59152
Name: 3, dtype: int64
54th/Cermak 2016 3 7    55729
Name: 3, dtype: int64
54th/Cermak 2017 3 7    55896
Name: 3, dtype: int64
54th/Cermak 2018 3 7    52063
Name: 3, dtype: int64
54th/Cermak 2019 3 7    51518
Name: 3, dtype: int64
54th/Cermak 2013 4 7    56295
Name: 4, dtype: int64
54th/Cermak 2014 4 7    58036
Name: 4, dtype: int64
54th/Cermak 2015 4 7    60244
Name: 4, dtype: int64
54th/Cermak 2016 4 7    53049
Name: 4, dtype: int64
54th/Cermak 2017 4 7    53320
Name: 4, dtype: int64
54th/Cermak 2018 4 7    50799
Name: 4, dtype: int64
54th/Cermak 2019 4 7    53825
Name: 4, dtype: int64
54th/Cermak 2013 5 7    56436
Name: 5, dtype: int64
54th/Cermak 2014 5 7    57613
Name: 5, dtype: int64
54th/Cermak 2015 5 7    59908
Name: 5, dtype: int64
54th/Cermak 2016 5 7    56123
Name: 5, dtype: int64
54th/Cermak 2017 5 7    58186
Name: 5, dtype: int64
54th/Cermak 2018 5 7    57099
Name: 5, dtype: int64
54th/Cermak 2019 5 7    57002
Name: 5, dtype: int64
54th/Cermak 2013 6 7    57915
Name: 6, dtype: int64
54th/Cermak 2014 6 7    58966
Name: 6, dtype: int64
54th/Cermak 2015 6 7    64139
Name: 6, dtype: int64
54th/Cermak 2016 6 7    59727
Name: 6, dtype: int64
54th/Cermak 2017 6 7    61094
Name: 6, dtype: int64
54th/Cermak 2018 6 7    57562
Name: 6, dtype: int64
54th/Cermak 2019 6 7    56707
Name: 6, dtype: int64
54th/Cermak 2013 7 7    62100
Name: 7, dtype: int64
54th/Cermak 2014 7 7    64673
Name: 7, dtype: int64
54th/Cermak 2015 7 7    67887
Name: 7, dtype: int64
54th/Cermak 2016 7 7    59602
Name: 7, dtype: int64
54th/Cermak 2017 7 7    58762
Name: 7, dtype: int64
54th/Cermak 2018 7 7    58204
Name: 7, dtype: int64
54th/Cermak 2019 7 7    58310
Name: 7, dtype: int64
54th/Cermak 2013 8 7    59531
Name: 8, dtype: int64
54th/Cermak 2014 8 7    63227
Name: 8, dtype: int64
54th/Cermak 2015 8 7    63769
Name: 8, dtype: int64
54th/Cermak 2016 8 7    59734
Name: 8, dtype: int64
54th/Cermak 2017 8 7    62818
Name: 8, dtype: int64
54th/Cermak 2018 8 7    0
Name: 8, dtype: int64
54th/Cermak 2019 8 7    58853
Name: 8, dtype: int64
54th/Cermak 2013 9 7    57630
Name: 9, dtype: int64
54th/Cermak 2014 9 7    63368
Name: 9, dtype: int64
54th/Cermak 2015 9 7    65723
Name: 9, dtype: int64
54th/Cermak 2016 9 7    59789
Name: 9, dtype: int64
54th/Cermak 2017 9 7    59916
Name: 9, dtype: int64
54th/Cermak 2018 9 7    0
Name: 9, dtype: int64
54th/Cermak 2019 9 7    57971
Name: 9, dtype: int64
54th/Cermak 2013 10 7    61643
Name: 10, dtype: int64
54th/Cermak 2014 10 7    65575
Name: 10, dtype: int64
54th/Cermak 2015 10 7    66726
Name: 10, dtype: int64
54th/Cermak 2016 10 7    59784
Name: 10, dtype: int64
54th/Cermak 2017 10 7    60462
Name: 10, dtype: int64
54th/Cermak 2018 10 7    0
Name: 10, dtype: int64
54th/Cermak 2019 10 7    60191
Name: 10, dtype: int64
54th/Cermak 2013 11 7    53595
Name: 11, dtype: int64
54th/Cermak 2014 11 7    54277
Name: 11, dtype: int64
54th/Cermak 2015 11 7    59271
Name: 11, dtype: int64
54th/Cermak 2016 11 7    59135
Name: 11, dtype: int64
54th/Cermak 2017 11 7    55634
Name: 11, dtype: int64
54th/Cermak 2018 11 7    0
Name: 11, dtype: int64
54th/Cermak 2019 11 7    52434
Name: 11, dtype: int64
54th/Cermak 2013 12 7    50239
Name: 12, dtype: int64
54th/Cermak 2014 12 7    56526
Name: 12, dtype: int64
54th/Cermak 2015 12 7    58120
Name: 12, dtype: int64
54th/Cermak 2016 12 7    51339
Name: 12, dtype: int64
54th/Cermak 2017 12 7    50229
Name: 12, dtype: int64
54th/Cermak 2018 12 7    0
Name: 12, dtype: int64
54th/Cermak 2019 12 7    49205
Name: 12, dtype: int64
63rd-Dan Ryan 2013 1 8    85289
Name: 1, dtype: int64
63rd-Dan Ryan 2014 1 8    77812
Name: 1, dtype: int64
63rd-Dan Ryan 2015 1 8    88930
Name: 1, dtype: int64
63rd-Dan Ryan 2016 1 8    77368
Name: 1, dtype: int64
63rd-Dan Ryan 2017 1 8    77537
Name: 1, dtype: int64
63rd-Dan Ryan 2018 1 8    73332
Name: 1, dtype: int64
63rd-Dan Ryan 2019 1 8    70664
Name: 1, dtype: int64
63rd-Dan Ryan 2013 2 8    78791
Name: 2, dtype: int64
63rd-Dan Ryan 2014 2 8    82197
Name: 2, dtype: int64
63rd-Dan Ryan 2015 2 8    75786
Name: 2, dtype: int64
63rd-Dan Ryan 2016 2 8    82067
Name: 2, dtype: int64
63rd-Dan Ryan 2017 2 8    77882
Name: 2, dtype: int64
63rd-Dan Ryan 2018 2 8    70754
Name: 2, dtype: int64
63rd-Dan Ryan 2019 2 8    70601
Name: 2, dtype: int64
63rd-Dan Ryan 2013 3 8    84509
Name: 3, dtype: int64
63rd-Dan Ryan 2014 3 8    93573
Name: 3, dtype: int64
63rd-Dan Ryan 2015 3 8    88023
Name: 3, dtype: int64
63rd-Dan Ryan 2016 3 8    91102
Name: 3, dtype: int64
63rd-Dan Ryan 2017 3 8    84404
Name: 3, dtype: int64
63rd-Dan Ryan 2018 3 8    79511
Name: 3, dtype: int64
63rd-Dan Ryan 2019 3 8    77570
Name: 3, dtype: int64
63rd-Dan Ryan 2013 4 8    83472
Name: 4, dtype: int64
63rd-Dan Ryan 2014 4 8    90262
Name: 4, dtype: int64
63rd-Dan Ryan 2015 4 8    84564
Name: 4, dtype: int64
63rd-Dan Ryan 2016 4 8    85833
Name: 4, dtype: int64
63rd-Dan Ryan 2017 4 8    76543
Name: 4, dtype: int64
63rd-Dan Ryan 2018 4 8    77803
Name: 4, dtype: int64
63rd-Dan Ryan 2019 4 8    76517
Name: 4, dtype: int64
63rd-Dan Ryan 2013 5 8    50104
Name: 5, dtype: int64
63rd-Dan Ryan 2014 5 8    95897
Name: 5, dtype: int64
63rd-Dan Ryan 2015 5 8    85861
Name: 5, dtype: int64
63rd-Dan Ryan 2016 5 8    92610
Name: 5, dtype: int64
63rd-Dan Ryan 2017 5 8    85779
Name: 5, dtype: int64
63rd-Dan Ryan 2018 5 8    86265
Name: 5, dtype: int64
63rd-Dan Ryan 2019 5 8    83109
Name: 5, dtype: int64
63rd-Dan Ryan 2013 6 8    0
Name: 6, dtype: int64
63rd-Dan Ryan 2014 6 8    89512
Name: 6, dtype: int64
63rd-Dan Ryan 2015 6 8    83137
Name: 6, dtype: int64
63rd-Dan Ryan 2016 6 8    90294
Name: 6, dtype: int64
63rd-Dan Ryan 2017 6 8    83017
Name: 6, dtype: int64
63rd-Dan Ryan 2018 6 8    81407
Name: 6, dtype: int64
63rd-Dan Ryan 2019 6 8    78781
Name: 6, dtype: int64
63rd-Dan Ryan 2013 7 8    0
Name: 7, dtype: int64
63rd-Dan Ryan 2014 7 8    94195
Name: 7, dtype: int64
63rd-Dan Ryan 2015 7 8    84845
Name: 7, dtype: int64
63rd-Dan Ryan 2016 7 8    85942
Name: 7, dtype: int64
63rd-Dan Ryan 2017 7 8    79775
Name: 7, dtype: int64
63rd-Dan Ryan 2018 7 8    81686
Name: 7, dtype: int64
63rd-Dan Ryan 2019 7 8    79577
Name: 7, dtype: int64
63rd-Dan Ryan 2013 8 8    0
Name: 8, dtype: int64
63rd-Dan Ryan 2014 8 8    95246
Name: 8, dtype: int64
63rd-Dan Ryan 2015 8 8    85321
Name: 8, dtype: int64
63rd-Dan Ryan 2016 8 8    86898
Name: 8, dtype: int64
63rd-Dan Ryan 2017 8 8    83425
Name: 8, dtype: int64
63rd-Dan Ryan 2018 8 8    0
Name: 8, dtype: int64
63rd-Dan Ryan 2019 8 8    80681
Name: 8, dtype: int64
63rd-Dan Ryan 2013 9 8    31358
Name: 9, dtype: int64
63rd-Dan Ryan 2014 9 8    107126
Name: 9, dtype: int64
63rd-Dan Ryan 2015 9 8    93610
Name: 9, dtype: int64
63rd-Dan Ryan 2016 9 8    94919
Name: 9, dtype: int64
63rd-Dan Ryan 2017 9 8    87053
Name: 9, dtype: int64
63rd-Dan Ryan 2018 9 8    0
Name: 9, dtype: int64
63rd-Dan Ryan 2019 9 8    83198
Name: 9, dtype: int64
63rd-Dan Ryan 2013 10 8    82649
Name: 10, dtype: int64
63rd-Dan Ryan 2014 10 8    112922
Name: 10, dtype: int64
63rd-Dan Ryan 2015 10 8    97969
Name: 10, dtype: int64
63rd-Dan Ryan 2016 10 8    94946
Name: 10, dtype: int64
63rd-Dan Ryan 2017 10 8    87875
Name: 10, dtype: int64
63rd-Dan Ryan 2018 10 8    0
Name: 10, dtype: int64
63rd-Dan Ryan 2019 10 8    85403
Name: 10, dtype: int64
63rd-Dan Ryan 2013 11 8    80318
Name: 11, dtype: int64
63rd-Dan Ryan 2014 11 8    93411
Name: 11, dtype: int64
63rd-Dan Ryan 2015 11 8    83921
Name: 11, dtype: int64
63rd-Dan Ryan 2016 11 8    87449
Name: 11, dtype: int64
63rd-Dan Ryan 2017 11 8    80951
Name: 11, dtype: int64
63rd-Dan Ryan 2018 11 8    0
Name: 11, dtype: int64
63rd-Dan Ryan 2019 11 8    76552
Name: 11, dtype: int64
63rd-Dan Ryan 2013 12 8    0
Name: 12, dtype: int64
63rd-Dan Ryan 2014 12 8    95440
Name: 12, dtype: int64
63rd-Dan Ryan 2015 12 8    83063
Name: 12, dtype: int64
63rd-Dan Ryan 2016 12 8    78192
Name: 12, dtype: int64
63rd-Dan Ryan 2017 12 8    75113
Name: 12, dtype: int64
63rd-Dan Ryan 2018 12 8    0
Name: 12, dtype: int64
63rd-Dan Ryan 2019 12 8    75077
Name: 12, dtype: int64
69th 2013 1 9    141035
Name: 1, dtype: int64
69th 2014 1 9    120179
Name: 1, dtype: int64
69th 2015 1 9    143029
Name: 1, dtype: int64
69th 2016 1 9    142458
Name: 1, dtype: int64
69th 2017 1 9    133445
Name: 1, dtype: int64
69th 2018 1 9    122969
Name: 1, dtype: int64
69th 2019 1 9    111784
Name: 1, dtype: int64
69th 2013 2 9    129147
Name: 2, dtype: int64
69th 2014 2 9    127862
Name: 2, dtype: int64
69th 2015 2 9    130589
Name: 2, dtype: int64
69th 2016 2 9    140608
Name: 2, dtype: int64
69th 2017 2 9    130232
Name: 2, dtype: int64
69th 2018 2 9    114109
Name: 2, dtype: int64
69th 2019 2 9    109073
Name: 2, dtype: int64
69th 2013 3 9    139380
Name: 3, dtype: int64
69th 2014 3 9    145593
Name: 3, dtype: int64
69th 2015 3 9    155146
Name: 3, dtype: int64
69th 2016 3 9    151438
Name: 3, dtype: int64
69th 2017 3 9    139577
Name: 3, dtype: int64
69th 2018 3 9    128843
Name: 3, dtype: int64
69th 2019 3 9    119037
Name: 3, dtype: int64
69th 2013 4 9    139214
Name: 4, dtype: int64
69th 2014 4 9    145563
Name: 4, dtype: int64
69th 2015 4 9    151025
Name: 4, dtype: int64
69th 2016 4 9    145115
Name: 4, dtype: int64
69th 2017 4 9    128860
Name: 4, dtype: int64
69th 2018 4 9    125430
Name: 4, dtype: int64
69th 2019 4 9    116649
Name: 4, dtype: int64
69th 2013 5 9    82930
Name: 5, dtype: int64
69th 2014 5 9    154284
Name: 5, dtype: int64
69th 2015 5 9    158489
Name: 5, dtype: int64
69th 2016 5 9    152053
Name: 5, dtype: int64
69th 2017 5 9    142966
Name: 5, dtype: int64
69th 2018 5 9    138577
Name: 5, dtype: int64
69th 2019 5 9    126835
Name: 5, dtype: int64
69th 2013 6 9    0
Name: 6, dtype: int64
69th 2014 6 9    146313
Name: 6, dtype: int64
69th 2015 6 9    157767
Name: 6, dtype: int64
69th 2016 6 9    151638
Name: 6, dtype: int64
69th 2017 6 9    142850
Name: 6, dtype: int64
69th 2018 6 9    132902
Name: 6, dtype: int64
69th 2019 6 9    117486
Name: 6, dtype: int64
69th 2013 7 9    0
Name: 7, dtype: int64
69th 2014 7 9    154043
Name: 7, dtype: int64
69th 2015 7 9    165695
Name: 7, dtype: int64
69th 2016 7 9    151395
Name: 7, dtype: int64
69th 2017 7 9    140833
Name: 7, dtype: int64
69th 2018 7 9    135383
Name: 7, dtype: int64
69th 2019 7 9    127780
Name: 7, dtype: int64
69th 2013 8 9    0
Name: 8, dtype: int64
69th 2014 8 9    155716
Name: 8, dtype: int64
69th 2015 8 9    158514
Name: 8, dtype: int64
69th 2016 8 9    149865
Name: 8, dtype: int64
69th 2017 8 9    146511
Name: 8, dtype: int64
69th 2018 8 9    0
Name: 8, dtype: int64
69th 2019 8 9    125537
Name: 8, dtype: int64
69th 2013 9 9    49826
Name: 9, dtype: int64
69th 2014 9 9    166263
Name: 9, dtype: int64
69th 2015 9 9    163691
Name: 9, dtype: int64
69th 2016 9 9    151756
Name: 9, dtype: int64
69th 2017 9 9    144708
Name: 9, dtype: int64
69th 2018 9 9    0
Name: 9, dtype: int64
69th 2019 9 9    121308
Name: 9, dtype: int64
69th 2013 10 9    125473
Name: 10, dtype: int64
69th 2014 10 9    176380
Name: 10, dtype: int64
69th 2015 10 9    176152
Name: 10, dtype: int64
69th 2016 10 9    158686
Name: 10, dtype: int64
69th 2017 10 9    149748
Name: 10, dtype: int64

69th 2018 10 9    0
Name: 10, dtype: int64
69th 2019 10 9    127325
Name: 10, dtype: int64
69th 2013 11 9    125655
Name: 11, dtype: int64
69th 2014 11 9    151812
Name: 11, dtype: int64
69th 2015 11 9    156143
Name: 11, dtype: int64
69th 2016 11 9    149318
Name: 11, dtype: int64
69th 2017 11 9    136751
Name: 11, dtype: int64
69th 2018 11 9    0
Name: 11, dtype: int64
69th 2019 11 9    111346
Name: 11, dtype: int64
69th 2013 12 9    0
Name: 12, dtype: int64
69th 2014 12 9    155993
Name: 12, dtype: int64
69th 2015 12 9    154216
Name: 12, dtype: int64
69th 2016 12 9    135771
Name: 12, dtype: int64
69th 2017 12 9    128837
Name: 12, dtype: int64
69th 2018 12 9    0
Name: 12, dtype: int64
69th 2019 12 9    109765
Name: 12, dtype: int64
79th 2013 1 10    184402
Name: 1, dtype: int64
79th 2014 1 10    166945
Name: 1, dtype: int64
79th 2015 1 10    190847
Name: 1, dtype: int64
79th 2016 1 10    191070
Name: 1, dtype: int64
79th 2017 1 10    177679
Name: 1, dtype: int64
79th 2018 1 10    166892
Name: 1, dtype: int64
79th 2019 1 10    148318
Name: 1, dtype: int64
79th 2013 2 10    171824
Name: 2, dtype: int64
79th 2014 2 10    174744
Name: 2, dtype: int64
79th 2015 2 10    176634
Name: 2, dtype: int64
79th 2016 2 10    187756
Name: 2, dtype: int64
79th 2017 2 10    172020
Name: 2, dtype: int64
79th 2018 2 10    157092
Name: 2, dtype: int64
79th 2019 2 10    148030
Name: 2, dtype: int64
79th 2013 3 10    185155
Name: 3, dtype: int64
79th 2014 3 10    198550
Name: 3, dtype: int64
79th 2015 3 10    207094
Name: 3, dtype: int64
79th 2016 3 10    200891
Name: 3, dtype: int64
79th 2017 3 10    187752
Name: 3, dtype: int64
79th 2018 3 10    175061
Name: 3, dtype: int64
79th 2019 3 10    161092
Name: 3, dtype: int64
79th 2013 4 10    183400
Name: 4, dtype: int64
79th 2014 4 10    195840
Name: 4, dtype: int64
79th 2015 4 10    204192
Name: 4, dtype: int64
79th 2016 4 10    189557
Name: 4, dtype: int64
79th 2017 4 10    173731
Name: 4, dtype: int64
79th 2018 4 10    170629
Name: 4, dtype: int64
79th 2019 4 10    159341
Name: 4, dtype: int64
79th 2013 5 10    109837
Name: 5, dtype: int64
79th 2014 5 10    205361
Name: 5, dtype: int64
79th 2015 5 10    212971
Name: 5, dtype: int64
79th 2016 5 10    200772
Name: 5, dtype: int64
79th 2017 5 10    190900
Name: 5, dtype: int64
79th 2018 5 10    186548
Name: 5, dtype: int64
79th 2019 5 10    174825
Name: 5, dtype: int64
79th 2013 6 10    0
Name: 6, dtype: int64
79th 2014 6 10    197313
Name: 6, dtype: int64
79th 2015 6 10    213886
Name: 6, dtype: int64
79th 2016 6 10    201117
Name: 6, dtype: int64
79th 2017 6 10    190728
Name: 6, dtype: int64
79th 2018 6 10    180400
Name: 6, dtype: int64
79th 2019 6 10    167957
Name: 6, dtype: int64
79th 2013 7 10    0
Name: 7, dtype: int64
79th 2014 7 10    206910
Name: 7, dtype: int64
79th 2015 7 10    223282
Name: 7, dtype: int64
79th 2016 7 10    198741
Name: 7, dtype: int64
79th 2017 7 10    187542
Name: 7, dtype: int64
79th 2018 7 10    184925
Name: 7, dtype: int64
79th 2019 7 10    177018
Name: 7, dtype: int64
79th 2013 8 10    0
Name: 8, dtype: int64
79th 2014 8 10    207727
Name: 8, dtype: int64
79th 2015 8 10    215254
Name: 8, dtype: int64
79th 2016 8 10    200006
Name: 8, dtype: int64
79th 2017 8 10    191966
Name: 8, dtype: int64
79th 2018 8 10    0
Name: 8, dtype: int64
79th 2019 8 10    175973
Name: 8, dtype: int64
79th 2013 9 10    67492
Name: 9, dtype: int64
79th 2014 9 10    222370
Name: 9, dtype: int64
79th 2015 9 10    222504
Name: 9, dtype: int64
79th 2016 9 10    199811
Name: 9, dtype: int64
79th 2017 9 10    189039
Name: 9, dtype: int64
79th 2018 9 10    0
Name: 9, dtype: int64
79th 2019 9 10    170637
Name: 9, dtype: int64
79th 2013 10 10    167737
Name: 10, dtype: int64
79th 2014 10 10    234123
Name: 10, dtype: int64
79th 2015 10 10    231365
Name: 10, dtype: int64
79th 2016 10 10    209526
Name: 10, dtype: int64
79th 2017 10 10    196076
Name: 10, dtype: int64
79th 2018 10 10    0
Name: 10, dtype: int64
79th 2019 10 10    177559
Name: 10, dtype: int64
79th 2013 11 10    173690
Name: 11, dtype: int64
79th 2014 11 10    200710
Name: 11, dtype: int64
79th 2015 11 10    203493
Name: 11, dtype: int64
79th 2016 11 10    198387
Name: 11, dtype: int64
79th 2017 11 10    182331
Name: 11, dtype: int64
79th 2018 11 10    0
Name: 11, dtype: int64
79th 2019 11 10    158249
Name: 11, dtype: int64
79th 2013 12 10    0
Name: 12, dtype: int64
79th 2014 12 10    208083
Name: 12, dtype: int64
79th 2015 12 10    206349
Name: 12, dtype: int64
79th 2016 12 10    185562
Name: 12, dtype: int64
79th 2017 12 10    173351
Name: 12, dtype: int64
79th 2018 12 10    0
Name: 12, dtype: int64
79th 2019 12 10    156867
Name: 12, dtype: int64
87th 2013 1 11    114526
Name: 1, dtype: int64
87th 2014 1 11    99271
Name: 1, dtype: int64
87th 2015 1 11    116141
Name: 1, dtype: int64
87th 2016 1 11    109995
Name: 1, dtype: int64
87th 2017 1 11    105298
Name: 1, dtype: int64
87th 2018 1 11    97951
Name: 1, dtype: int64
87th 2019 1 11    89398
Name: 1, dtype: int64
87th 2013 2 11    104661
Name: 2, dtype: int64
87th 2014 2 11    105892
Name: 2, dtype: int64
87th 2015 2 11    107743
Name: 2, dtype: int64
87th 2016 2 11    110297
Name: 2, dtype: int64
87th 2017 2 11    103166
Name: 2, dtype: int64
87th 2018 2 11    94417
Name: 2, dtype: int64
87th 2019 2 11    89051
Name: 2, dtype: int64
87th 2013 3 11    113746
Name: 3, dtype: int64
87th 2014 3 11    120733
Name: 3, dtype: int64
87th 2015 3 11    127366
Name: 3, dtype: int64
87th 2016 3 11    119969
Name: 3, dtype: int64
87th 2017 3 11    111798
Name: 3, dtype: int64
87th 2018 3 11    106586
Name: 3, dtype: int64
87th 2019 3 11    98791
Name: 3, dtype: int64
87th 2013 4 11    112732
Name: 4, dtype: int64
87th 2014 4 11    121493
Name: 4, dtype: int64
87th 2015 4 11    125393
Name: 4, dtype: int64
87th 2016 4 11    113765
Name: 4, dtype: int64
87th 2017 4 11    103932
Name: 4, dtype: int64
87th 2018 4 11    102817
Name: 4, dtype: int64
87th 2019 4 11    96457
Name: 4, dtype: int64
87th 2013 5 11    67902
Name: 5, dtype: int64
87th 2014 5 11    127579
Name: 5, dtype: int64
87th 2015 5 11    132286
Name: 5, dtype: int64
87th 2016 5 11    121632
Name: 5, dtype: int64
87th 2017 5 11    112575
Name: 5, dtype: int64
87th 2018 5 11    112542
Name: 5, dtype: int64
87th 2019 5 11    106303
Name: 5, dtype: int64
87th 2013 6 11    0
Name: 6, dtype: int64
87th 2014 6 11    126499
Name: 6, dtype: int64
87th 2015 6 11    133141
Name: 6, dtype: int64
87th 2016 6 11    121486
Name: 6, dtype: int64
87th 2017 6 11    113721
Name: 6, dtype: int64
87th 2018 6 11    109018
Name: 6, dtype: int64
87th 2019 6 11    102146
Name: 6, dtype: int64
87th 2013 7 11    0
Name: 7, dtype: int64
87th 2014 7 11    134830
Name: 7, dtype: int64
87th 2015 7 11    137606
Name: 7, dtype: int64
87th 2016 7 11    119419
Name: 7, dtype: int64
87th 2017 7 11    112594
Name: 7, dtype: int64
87th 2018 7 11    112866
Name: 7, dtype: int64
87th 2019 7 11    106057
Name: 7, dtype: int64
87th 2013 8 11    0
Name: 8, dtype: int64
87th 2014 8 11    133069
Name: 8, dtype: int64
87th 2015 8 11    127315
Name: 8, dtype: int64
87th 2016 8 11    120747
Name: 8, dtype: int64
87th 2017 8 11    115280
Name: 8, dtype: int64
87th 2018 8 11    0
Name: 8, dtype: int64
87th 2019 8 11    105026
Name: 8, dtype: int64
87th 2013 9 11    42712
Name: 9, dtype: int64
87th 2014 9 11    137985
Name: 9, dtype: int64
87th 2015 9 11    129406
Name: 9, dtype: int64
87th 2016 9 11    120592
Name: 9, dtype: int64
87th 2017 9 11    113162
Name: 9, dtype: int64
87th 2018 9 11    0
Name: 9, dtype: int64
87th 2019 9 11    102698
Name: 9, dtype: int64
87th 2013 10 11    108093
Name: 10, dtype: int64
87th 2014 10 11    145941
Name: 10, dtype: int64
87th 2015 10 11    136546
Name: 10, dtype: int64
87th 2016 10 11    125049
Name: 10, dtype: int64
87th 2017 10 11    117315
Name: 10, dtype: int64
87th 2018 10 11    0
Name: 10, dtype: int64
87th 2019 10 11    104612
Name: 10, dtype: int64
87th 2013 11 11    106179
Name: 11, dtype: int64
87th 2014 11 11    124236
Name: 11, dtype: int64
87th 2015 11 11    121025
Name: 11, dtype: int64
87th 2016 11 11    116923
Name: 11, dtype: int64
87th 2017 11 11    108376
Name: 11, dtype: int64
87th 2018 11 11    0
Name: 11, dtype: int64
87th 2019 11 11    93378
Name: 11, dtype: int64
87th 2013 12 11    0
Name: 12, dtype: int64
87th 2014 12 11    128834
Name: 12, dtype: int64
87th 2015 12 11    122488
Name: 12, dtype: int64
87th 2016 12 11    108699
Name: 12, dtype: int64
87th 2017 12 11    103334
Name: 12, dtype: int64
87th 2018 12 11    0
Name: 12, dtype: int64
87th 2019 12 11    92807
Name: 12, dtype: int64
95th/Dan Ryan 2013 1 12    300463
Name: 1, dtype: int64
95th/Dan Ryan 2014 1 12    250776
Name: 1, dtype: int64
95th/Dan Ryan 2015 1 12    285467
Name: 1, dtype: int64
95th/Dan Ryan 2016 1 12    279606
Name: 1, dtype: int64
95th/Dan Ryan 2017 1 12    260145
Name: 1, dtype: int64
95th/Dan Ryan 2018 1 12    243250
Name: 1, dtype: int64
95th/Dan Ryan 2019 1 12    214357
Name: 1, dtype: int64
95th/Dan Ryan 2013 2 12    276155
Name: 2, dtype: int64
95th/Dan Ryan 2014 2 12    267784
Name: 2, dtype: int64
95th/Dan Ryan 2015 2 12    263788
Name: 2, dtype: int64
95th/Dan Ryan 2016 2 12    280838
Name: 2, dtype: int64
95th/Dan Ryan 2017 2 12    255629
Name: 2, dtype: int64
95th/Dan Ryan 2018 2 12    230482
Name: 2, dtype: int64
95th/Dan Ryan 2019 2 12    214852
Name: 2, dtype: int64
95th/Dan Ryan 2013 3 12    292019
Name: 3, dtype: int64
95th/Dan Ryan 2014 3 12    307614
Name: 3, dtype: int64
95th/Dan Ryan 2015 3 12    312576
Name: 3, dtype: int64
95th/Dan Ryan 2016 3 12    301901
Name: 3, dtype: int64
95th/Dan Ryan 2017 3 12    283880
Name: 3, dtype: int64
95th/Dan Ryan 2018 3 12    257811
Name: 3, dtype: int64
95th/Dan Ryan 2019 3 12    228961
Name: 3, dtype: int64
95th/Dan Ryan 2013 4 12    294400
Name: 4, dtype: int64
95th/Dan Ryan 2014 4 12    303200
Name: 4, dtype: int64
95th/Dan Ryan 2015 4 12    302029
Name: 4, dtype: int64
95th/Dan Ryan 2016 4 12    282275
Name: 4, dtype: int64
95th/Dan Ryan 2017 4 12    256400
Name: 4, dtype: int64
95th/Dan Ryan 2018 4 12    250476
Name: 4, dtype: int64
95th/Dan Ryan 2019 4 12    231909
Name: 4, dtype: int64
95th/Dan Ryan 2013 5 12    174716
Name: 5, dtype: int64
95th/Dan Ryan 2014 5 12    315194
Name: 5, dtype: int64
95th/Dan Ryan 2015 5 12    307920
Name: 5, dtype: int64
95th/Dan Ryan 2016 5 12    298656
Name: 5, dtype: int64
95th/Dan Ryan 2017 5 12    283694
Name: 5, dtype: int64
95th/Dan Ryan 2018 5 12    266560
Name: 5, dtype: int64
95th/Dan Ryan 2019 5 12    251527
Name: 5, dtype: int64
95th/Dan Ryan 2013 6 12    0
Name: 6, dtype: int64
95th/Dan Ryan 2014 6 12    300263
Name: 6, dtype: int64
95th/Dan Ryan 2015 6 12    311468
Name: 6, dtype: int64
95th/Dan Ryan 2016 6 12    295367
Name: 6, dtype: int64
95th/Dan Ryan 2017 6 12    279307
Name: 6, dtype: int64
95th/Dan Ryan 2018 6 12    251301
Name: 6, dtype: int64
95th/Dan Ryan 2019 6 12    237748
Name: 6, dtype: int64
95th/Dan Ryan 2013 7 12    0
Name: 7, dtype: int64
95th/Dan Ryan 2014 7 12    315011
Name: 7, dtype: int64
95th/Dan Ryan 2015 7 12    319026
Name: 7, dtype: int64
95th/Dan Ryan 2016 7 12    285277
Name: 7, dtype: int64
95th/Dan Ryan 2017 7 12    269360
Name: 7, dtype: int64
95th/Dan Ryan 2018 7 12    256652
Name: 7, dtype: int64
95th/Dan Ryan 2019 7 12    249823
Name: 7, dtype: int64
95th/Dan Ryan 2013 8 12    0
Name: 8, dtype: int64
95th/Dan Ryan 2014 8 12    310238
Name: 8, dtype: int64
95th/Dan Ryan 2015 8 12    307980
Name: 8, dtype: int64
95th/Dan Ryan 2016 8 12    292886
Name: 8, dtype: int64
95th/Dan Ryan 2017 8 12    281937
Name: 8, dtype: int64
95th/Dan Ryan 2018 8 12    0
Name: 8, dtype: int64
95th/Dan Ryan 2019 8 12    246366
Name: 8, dtype: int64
95th/Dan Ryan 2013 9 12    117770
Name: 9, dtype: int64
95th/Dan Ryan 2014 9 12    338234
Name: 9, dtype: int64
95th/Dan Ryan 2015 9 12    327414
Name: 9, dtype: int64
95th/Dan Ryan 2016 9 12    298698
Name: 9, dtype: int64
95th/Dan Ryan 2017 9 12    283708
Name: 9, dtype: int64
95th/Dan Ryan 2018 9 12    0
Name: 9, dtype: int64
95th/Dan Ryan 2019 9 12    244102
Name: 9, dtype: int64
95th/Dan Ryan 2013 10 12    276785
Name: 10, dtype: int64
95th/Dan Ryan 2014 10 12    355331
Name: 10, dtype: int64
95th/Dan Ryan 2015 10 12    340191
Name: 10, dtype: int64
95th/Dan Ryan 2016 10 12    303741
Name: 10, dtype: int64
95th/Dan Ryan 2017 10 12    292874
Name: 10, dtype: int64
95th/Dan Ryan 2018 10 12    0
Name: 10, dtype: int64
95th/Dan Ryan 2019 10 12    253132
Name: 10, dtype: int64
95th/Dan Ryan 2013 11 12    264554
Name: 11, dtype: int64
95th/Dan Ryan 2014 11 12    299442
Name: 11, dtype: int64
95th/Dan Ryan 2015 11 12    299253
Name: 11, dtype: int64
95th/Dan Ryan 2016 11 12    287314
Name: 11, dtype: int64
95th/Dan Ryan 2017 11 12    267344
Name: 11, dtype: int64
95th/Dan Ryan 2018 11 12    0
Name: 11, dtype: int64
95th/Dan Ryan 2019 11 12    224620
Name: 11, dtype: int64
95th/Dan Ryan 2013 12 12    0
Name: 12, dtype: int64
95th/Dan Ryan 2014 12 12    306512
Name: 12, dtype: int64
95th/Dan Ryan 2015 12 12    299103
Name: 12, dtype: int64
95th/Dan Ryan 2016 12 12    262169
Name: 12, dtype: int64
95th/Dan Ryan 2017 12 12    246868
Name: 12, dtype: int64
95th/Dan Ryan 2018 12 12    0
Name: 12, dtype: int64
95th/Dan Ryan 2019 12 12    221429
Name: 12, dtype: int64
Adams/Wabash 2013 1 13    168862
Name: 1, dtype: int64
Adams/Wabash 2014 1 13    150622
Name: 1, dtype: int64
Adams/Wabash 2015 1 13    156998
Name: 1, dtype: int64
Adams/Wabash 2016 1 13    201570
Name: 1, dtype: int64
Adams/Wabash 2017 1 13    209619
Name: 1, dtype: int64
Adams/Wabash 2018 1 13    174549
Name: 1, dtype: int64
Adams/Wabash 2019 1 13    145040
Name: 1, dtype: int64
Adams/Wabash 2013 2 13    176065
Name: 2, dtype: int64
Adams/Wabash 2014 2 13    161625
Name: 2, dtype: int64
Adams/Wabash 2015 2 13    158538
Name: 2, dtype: int64
Adams/Wabash 2016 2 13    217649
Name: 2, dtype: int64
Adams/Wabash 2017 2 13    208444
Name: 2, dtype: int64
Adams/Wabash 2018 2 13    166751
Name: 2, dtype: int64
Adams/Wabash 2019 2 13    160700
Name: 2, dtype: int64
Adams/Wabash 2013 3 13    160742
Name: 3, dtype: int64
Adams/Wabash 2014 3 13    181223
Name: 3, dtype: int64
Adams/Wabash 2015 3 13    214346
Name: 3, dtype: int64
Adams/Wabash 2016 3 13    242907
Name: 3, dtype: int64
Adams/Wabash 2017 3 13    224700
Name: 3, dtype: int64
Adams/Wabash 2018 3 13    190464
Name: 3, dtype: int64
Adams/Wabash 2019 3 13    172100
Name: 3, dtype: int64
Adams/Wabash 2013 4 13    184551
Name: 4, dtype: int64
Adams/Wabash 2014 4 13    187840
Name: 4, dtype: int64
Adams/Wabash 2015 4 13    249192
Name: 4, dtype: int64
Adams/Wabash 2016 4 13    243305
Name: 4, dtype: int64
Adams/Wabash 2017 4 13    225361
Name: 4, dtype: int64
Adams/Wabash 2018 4 13    185649
Name: 4, dtype: int64
Adams/Wabash 2019 4 13    180964
Name: 4, dtype: int64
Adams/Wabash 2013 5 13    180699
Name: 5, dtype: int64
Adams/Wabash 2014 5 13    180154
Name: 5, dtype: int64
Adams/Wabash 2015 5 13    240854
Name: 5, dtype: int64
Adams/Wabash 2016 5 13    241033
Name: 5, dtype: int64

Adams/Wabash 2017 5 13    237663
Name: 5, dtype: int64
Adams/Wabash 2018 5 13    196964
Name: 5, dtype: int64
Adams/Wabash 2019 5 13    185635
Name: 5, dtype: int64
Adams/Wabash 2013 6 13    190487
Name: 6, dtype: int64
Adams/Wabash 2014 6 13    183020
Name: 6, dtype: int64
Adams/Wabash 2015 6 13    256654
Name: 6, dtype: int64
Adams/Wabash 2016 6 13    228445
Name: 6, dtype: int64
Adams/Wabash 2017 6 13    230948
Name: 6, dtype: int64
Adams/Wabash 2018 6 13    179876
Name: 6, dtype: int64
Adams/Wabash 2019 6 13    171856
Name: 6, dtype: int64
Adams/Wabash 2013 7 13    207753
Name: 7, dtype: int64
Adams/Wabash 2014 7 13    197024
Name: 7, dtype: int64
Adams/Wabash 2015 7 13    287580
Name: 7, dtype: int64
Adams/Wabash 2016 7 13    275953
Name: 7, dtype: int64
Adams/Wabash 2017 7 13    242408
Name: 7, dtype: int64
Adams/Wabash 2018 7 13    0
Name: 7, dtype: int64
Adams/Wabash 2019 7 13    184412
Name: 7, dtype: int64
Adams/Wabash 2013 8 13    195705
Name: 8, dtype: int64
Adams/Wabash 2014 8 13    185285
Name: 8, dtype: int64
Adams/Wabash 2015 8 13    245891
Name: 8, dtype: int64
Adams/Wabash 2016 8 13    231972
Name: 8, dtype: int64
Adams/Wabash 2017 8 13    245973
Name: 8, dtype: int64
Adams/Wabash 2018 8 13    0
Name: 8, dtype: int64
Adams/Wabash 2019 8 13    186325
Name: 8, dtype: int64
Adams/Wabash 2013 9 13    185790
Name: 9, dtype: int64
Adams/Wabash 2014 9 13    187865
Name: 9, dtype: int64
Adams/Wabash 2015 9 13    254127
Name: 9, dtype: int64
Adams/Wabash 2016 9 13    236796
Name: 9, dtype: int64
Adams/Wabash 2017 9 13    199306
Name: 9, dtype: int64
Adams/Wabash 2018 9 13    0
Name: 9, dtype: int64
Adams/Wabash 2019 9 13    184584
Name: 9, dtype: int64
Adams/Wabash 2013 10 13    214713
Name: 10, dtype: int64
Adams/Wabash 2014 10 13    212006
Name: 10, dtype: int64
Adams/Wabash 2015 10 13    280598
Name: 10, dtype: int64
Adams/Wabash 2016 10 13    263750
Name: 10, dtype: int64
Adams/Wabash 2017 10 13    216508
Name: 10, dtype: int64
Adams/Wabash 2018 10 13    0
Name: 10, dtype: int64
Adams/Wabash 2019 10 13    218577
Name: 10, dtype: int64
Adams/Wabash 2013 11 13    171596
Name: 11, dtype: int64
Adams/Wabash 2014 11 13    161004
Name: 11, dtype: int64
Adams/Wabash 2015 11 13    233677
Name: 11, dtype: int64
Adams/Wabash 2016 11 13    235812
Name: 11, dtype: int64
Adams/Wabash 2017 11 13    186964
Name: 11, dtype: int64
Adams/Wabash 2018 11 13    0
Name: 11, dtype: int64
Adams/Wabash 2019 11 13    164022
Name: 11, dtype: int64
Adams/Wabash 2013 12 13    141310
Name: 12, dtype: int64
Adams/Wabash 2014 12 13    143773
Name: 12, dtype: int64
Adams/Wabash 2015 12 13    209799
Name: 12, dtype: int64
Adams/Wabash 2016 12 13    189188
Name: 12, dtype: int64
Adams/Wabash 2017 12 13    145385
Name: 12, dtype: int64
Adams/Wabash 2018 12 13    0
Name: 12, dtype: int64
Adams/Wabash 2019 12 13    133268
Name: 12, dtype: int64
Addison-Brown 2013 1 14    61810
Name: 1, dtype: int64
Addison-Brown 2014 1 14    61217
Name: 1, dtype: int64
Addison-Brown 2015 1 14    58640
Name: 1, dtype: int64
Addison-Brown 2016 1 14    60486
Name: 1, dtype: int64
Addison-Brown 2017 1 14    61361
Name: 1, dtype: int64
Addison-Brown 2018 1 14    59947
Name: 1, dtype: int64
Addison-Brown 2019 1 14    55483
Name: 1, dtype: int64
Addison-Brown 2013 2 14    59436
Name: 2, dtype: int64
Addison-Brown 2014 2 14    62208
Name: 2, dtype: int64
Addison-Brown 2015 2 14    57331
Name: 2, dtype: int64
Addison-Brown 2016 2 14    61114
Name: 2, dtype: int64
Addison-Brown 2017 2 14    58836
Name: 2, dtype: int64
Addison-Brown 2018 2 14    56865
Name: 2, dtype: int64
Addison-Brown 2019 2 14    56726
Name: 2, dtype: int64
Addison-Brown 2013 3 14    59620
Name: 3, dtype: int64
Addison-Brown 2014 3 14    69504
Name: 3, dtype: int64
Addison-Brown 2015 3 14    64998
Name: 3, dtype: int64
Addison-Brown 2016 3 14    69444
Name: 3, dtype: int64
Addison-Brown 2017 3 14    68107
Name: 3, dtype: int64
Addison-Brown 2018 3 14    62977
Name: 3, dtype: int64
Addison-Brown 2019 3 14    64935
Name: 3, dtype: int64
Addison-Brown 2013 4 14    63766
Name: 4, dtype: int64
Addison-Brown 2014 4 14    66009
Name: 4, dtype: int64
Addison-Brown 2015 4 14    60882
Name: 4, dtype: int64
Addison-Brown 2016 4 14    63424
Name: 4, dtype: int64
Addison-Brown 2017 4 14    59313
Name: 4, dtype: int64
Addison-Brown 2018 4 14    60551
Name: 4, dtype: int64
Addison-Brown 2019 4 14    60851
Name: 4, dtype: int64
Addison-Brown 2013 5 14    64290
Name: 5, dtype: int64
Addison-Brown 2014 5 14    67520
Name: 5, dtype: int64
Addison-Brown 2015 5 14    61765
Name: 5, dtype: int64
Addison-Brown 2016 5 14    66586
Name: 5, dtype: int64
Addison-Brown 2017 5 14    67003
Name: 5, dtype: int64
Addison-Brown 2018 5 14    65375
Name: 5, dtype: int64
Addison-Brown 2019 5 14    67114
Name: 5, dtype: int64
Addison-Brown 2013 6 14    64089
Name: 6, dtype: int64
Addison-Brown 2014 6 14    62535
Name: 6, dtype: int64
Addison-Brown 2015 6 14    63260
Name: 6, dtype: int64
Addison-Brown 2016 6 14    67459
Name: 6, dtype: int64
Addison-Brown 2017 6 14    65789
Name: 6, dtype: int64
Addison-Brown 2018 6 14    60284
Name: 6, dtype: int64
Addison-Brown 2019 6 14    61666
Name: 6, dtype: int64
Addison-Brown 2013 7 14    61851
Name: 7, dtype: int64
Addison-Brown 2014 7 14    60610
Name: 7, dtype: int64
Addison-Brown 2015 7 14    59920
Name: 7, dtype: int64
Addison-Brown 2016 7 14    59281
Name: 7, dtype: int64
Addison-Brown 2017 7 14    56292
Name: 7, dtype: int64
Addison-Brown 2018 7 14    0
Name: 7, dtype: int64
Addison-Brown 2019 7 14    57466
Name: 7, dtype: int64
Addison-Brown 2013 8 14    64725
Name: 8, dtype: int64
Addison-Brown 2014 8 14    58896
Name: 8, dtype: int64
Addison-Brown 2015 8 14    57360
Name: 8, dtype: int64
Addison-Brown 2016 8 14    61756
Name: 8, dtype: int64
Addison-Brown 2017 8 14    61252
Name: 8, dtype: int64
Addison-Brown 2018 8 14    0
Name: 8, dtype: int64
Addison-Brown 2019 8 14    59339
Name: 8, dtype: int64
Addison-Brown 2013 9 14    66461
Name: 9, dtype: int64
Addison-Brown 2014 9 14    65820
Name: 9, dtype: int64
Addison-Brown 2015 9 14    64380
Name: 9, dtype: int64
Addison-Brown 2016 9 14    68844
Name: 9, dtype: int64
Addison-Brown 2017 9 14    64063
Name: 9, dtype: int64
Addison-Brown 2018 9 14    0
Name: 9, dtype: int64
Addison-Brown 2019 9 14    64042
Name: 9, dtype: int64
Addison-Brown 2013 10 14    74436
Name: 10, dtype: int64
Addison-Brown 2014 10 14    71099
Name: 10, dtype: int64
Addison-Brown 2015 10 14    70134
Name: 10, dtype: int64
Addison-Brown 2016 10 14    71649
Name: 10, dtype: int64
Addison-Brown 2017 10 14    68060
Name: 10, dtype: int64
Addison-Brown 2018 10 14    0
Name: 10, dtype: int64
Addison-Brown 2019 10 14    66094
Name: 10, dtype: int64
Addison-Brown 2013 11 14    62058
Name: 11, dtype: int64
Addison-Brown 2014 11 14    57630
Name: 11, dtype: int64
Addison-Brown 2015 11 14    59252
Name: 11, dtype: int64
Addison-Brown 2016 11 14    64976
Name: 11, dtype: int64
Addison-Brown 2017 11 14    60096
Name: 11, dtype: int64
Addison-Brown 2018 11 14    0
Name: 11, dtype: int64
Addison-Brown 2019 11 14    57200
Name: 11, dtype: int64
Addison-Brown 2013 12 14    58205
Name: 12, dtype: int64
Addison-Brown 2014 12 14    57862
Name: 12, dtype: int64
Addison-Brown 2015 12 14    58124
Name: 12, dtype: int64
Addison-Brown 2016 12 14    56540
Name: 12, dtype: int64
Addison-Brown 2017 12 14    53156
Name: 12, dtype: int64
Addison-Brown 2018 12 14    0
Name: 12, dtype: int64
Addison-Brown 2019 12 14    53353
Name: 12, dtype: int64
Addison-North Main 2013 1 15    176866
Name: 1, dtype: int64
Addison-North Main 2014 1 15    168896
Name: 1, dtype: int64
Addison-North Main 2015 1 15    173219
Name: 1, dtype: int64
Addison-North Main 2016 1 15    172097
Name: 1, dtype: int64
Addison-North Main 2017 1 15    163552
Name: 1, dtype: int64
Addison-North Main 2018 1 15    154459
Name: 1, dtype: int64
Addison-North Main 2019 1 15    147569
Name: 1, dtype: int64
Addison-North Main 2013 2 15    165420
Name: 2, dtype: int64
Addison-North Main 2014 2 15    168679
Name: 2, dtype: int64
Addison-North Main 2015 2 15    160947
Name: 2, dtype: int64
Addison-North Main 2016 2 15    170931
Name: 2, dtype: int64
Addison-North Main 2017 2 15    157805
Name: 2, dtype: int64
Addison-North Main 2018 2 15    148924
Name: 2, dtype: int64
Addison-North Main 2019 2 15    148856
Name: 2, dtype: int64
Addison-North Main 2013 3 15    204241
Name: 3, dtype: int64
Addison-North Main 2014 3 15    206779
Name: 3, dtype: int64
Addison-North Main 2015 3 15    202241
Name: 3, dtype: int64
Addison-North Main 2016 3 15    196884
Name: 3, dtype: int64
Addison-North Main 2017 3 15    185950
Name: 3, dtype: int64
Addison-North Main 2018 3 15    180402
Name: 3, dtype: int64
Addison-North Main 2019 3 15    131835
Name: 3, dtype: int64
Addison-North Main 2013 4 15    245972
Name: 4, dtype: int64
Addison-North Main 2014 4 15    271231
Name: 4, dtype: int64
Addison-North Main 2015 4 15    252473
Name: 4, dtype: int64
Addison-North Main 2016 4 15    261882
Name: 4, dtype: int64
Addison-North Main 2017 4 15    255774
Name: 4, dtype: int64
Addison-North Main 2018 4 15    246968
Name: 4, dtype: int64
Addison-North Main 2019 4 15    225991
Name: 4, dtype: int64
Addison-North Main 2013 5 15    298175
Name: 5, dtype: int64
Addison-North Main 2014 5 15    271173
Name: 5, dtype: int64
Addison-North Main 2015 5 15    295551
Name: 5, dtype: int64
Addison-North Main 2016 5 15    318552
Name: 5, dtype: int64
Addison-North Main 2017 5 15    305940
Name: 5, dtype: int64
Addison-North Main 2018 5 15    286481
Name: 5, dtype: int64
Addison-North Main 2019 5 15    270963
Name: 5, dtype: int64
Addison-North Main 2013 6 15    305164
Name: 6, dtype: int64
Addison-North Main 2014 6 15    324005
Name: 6, dtype: int64
Addison-North Main 2015 6 15    306394
Name: 6, dtype: int64
Addison-North Main 2016 6 15    322915
Name: 6, dtype: int64
Addison-North Main 2017 6 15    335215
Name: 6, dtype: int64
Addison-North Main 2018 6 15    307384
Name: 6, dtype: int64
Addison-North Main 2019 6 15    341742
Name: 6, dtype: int64
Addison-North Main 2013 7 15    328687
Name: 7, dtype: int64
Addison-North Main 2014 7 15    318195
Name: 7, dtype: int64
Addison-North Main 2015 7 15    343711
Name: 7, dtype: int64
Addison-North Main 2016 7 15    333390
Name: 7, dtype: int64

Addison-North Main 2017 7 15    330552
Name: 7, dtype: int64
Addison-North Main 2018 7 15    345696
Name: 7, dtype: int64
Addison-North Main 2019 7 15    254675
Name: 7, dtype: int64
Addison-North Main 2013 8 15    333488
Name: 8, dtype: int64
Addison-North Main 2014 8 15    297420
Name: 8, dtype: int64
Addison-North Main 2015 8 15    333725
Name: 8, dtype: int64
Addison-North Main 2016 8 15    357599
Name: 8, dtype: int64
Addison-North Main 2017 8 15    373291
Name: 8, dtype: int64
Addison-North Main 2018 8 15    0
Name: 8, dtype: int64
Addison-North Main 2019 8 15    301403
Name: 8, dtype: int64
Addison-North Main 2013 9 15    274104
Name: 9, dtype: int64
Addison-North Main 2014 9 15    294998
Name: 9, dtype: int64
Addison-North Main 2015 9 15    343344
Name: 9, dtype: int64
Addison-North Main 2016 9 15    302838
Name: 9, dtype: int64
Addison-North Main 2017 9 15    301376
Name: 9, dtype: int64
Addison-North Main 2018 9 15    0
Name: 9, dtype: int64
Addison-North Main 2019 9 15    272297
Name: 9, dtype: int64
Addison-North Main 2013 10 15    224509
Name: 10, dtype: int64
Addison-North Main 2014 10 15    218389
Name: 10, dtype: int64
Addison-North Main 2015 10 15    278370
Name: 10, dtype: int64
Addison-North Main 2016 10 15    342111
Name: 10, dtype: int64
Addison-North Main 2017 10 15    250758
Name: 10, dtype: int64
Addison-North Main 2018 10 15    0
Name: 10, dtype: int64
Addison-North Main 2019 10 15    192956
Name: 10, dtype: int64
Addison-North Main 2013 11 15    191831
Name: 11, dtype: int64
Addison-North Main 2014 11 15    181286
Name: 11, dtype: int64
Addison-North Main 2015 11 15    183665
Name: 11, dtype: int64
Addison-North Main 2016 11 15    234270
Name: 11, dtype: int64
Addison-North Main 2017 11 15    164406
Name: 11, dtype: int64
Addison-North Main 2018 11 15    0
Name: 11, dtype: int64
Addison-North Main 2019 11 15    161187
Name: 11, dtype: int64
Addison-North Main 2013 12 15    162480
Name: 12, dtype: int64
Addison-North Main 2014 12 15    163820
Name: 12, dtype: int64
Addison-North Main 2015 12 15    161138
Name: 12, dtype: int64
Addison-North Main 2016 12 15    148648
Name: 12, dtype: int64
Addison-North Main 2017 12 15    147273
Name: 12, dtype: int64
Addison-North Main 2018 12 15    0
Name: 12, dtype: int64
Addison-North Main 2019 12 15    147897
Name: 12, dtype: int64
Addison-O'Hare 2013 1 16    66491
Name: 1, dtype: int64
Addison-O'Hare 2014 1 16    61846
Name: 1, dtype: int64
Addison-O'Hare 2015 1 16    68046
Name: 1, dtype: int64
Addison-O'Hare 2016 1 16    69468
Name: 1, dtype: int64
Addison-O'Hare 2017 1 16    66584
Name: 1, dtype: int64
Addison-O'Hare 2018 1 16    64612
Name: 1, dtype: int64
Addison-O'Hare 2019 1 16    64253
Name: 1, dtype: int64
Addison-O'Hare 2013 2 16    62229
Name: 2, dtype: int64
Addison-O'Hare 2014 2 16    63440
Name: 2, dtype: int64
Addison-O'Hare 2015 2 16    66025
Name: 2, dtype: int64
Addison-O'Hare 2016 2 16    70479
Name: 2, dtype: int64
Addison-O'Hare 2017 2 16    65029
Name: 2, dtype: int64
Addison-O'Hare 2018 2 16    62114
Name: 2, dtype: int64
Addison-O'Hare 2019 2 16    64839
Name: 2, dtype: int64
Addison-O'Hare 2013 3 16    68647
Name: 3, dtype: int64
Addison-O'Hare 2014 3 16    71323
Name: 3, dtype: int64
Addison-O'Hare 2015 3 16    78640
Name: 3, dtype: int64
Addison-O'Hare 2016 3 16    59965
Name: 3, dtype: int64
Addison-O'Hare 2017 3 16    75458
Name: 3, dtype: int64
Addison-O'Hare 2018 3 16    70982
Name: 3, dtype: int64
Addison-O'Hare 2019 3 16    73701
Name: 3, dtype: int64
Addison-O'Hare 2013 4 16    72787
Name: 4, dtype: int64
Addison-O'Hare 2014 4 16    71941
Name: 4, dtype: int64
Addison-O'Hare 2015 4 16    78100
Name: 4, dtype: int64
Addison-O'Hare 2016 4 16    52735
Name: 4, dtype: int64
Addison-O'Hare 2017 4 16    70816
Name: 4, dtype: int64
Addison-O'Hare 2018 4 16    71608
Name: 4, dtype: int64
Addison-O'Hare 2019 4 16    75038
Name: 4, dtype: int64
Addison-O'Hare 2013 5 16    77830
Name: 5, dtype: int64
Addison-O'Hare 2014 5 16    75555
Name: 5, dtype: int64
Addison-O'Hare 2015 5 16    82383
Name: 5, dtype: int64
Addison-O'Hare 2016 5 16    74388
Name: 5, dtype: int64
Addison-O'Hare 2017 5 16    79931
Name: 5, dtype: int64
Addison-O'Hare 2018 5 16    78821
Name: 5, dtype: int64
Addison-O'Hare 2019 5 16    80163
Name: 5, dtype: int64
Addison-O'Hare 2013 6 16    74839
Name: 6, dtype: int64
Addison-O'Hare 2014 6 16    73781
Name: 6, dtype: int64
Addison-O'Hare 2015 6 16    83885
Name: 6, dtype: int64
Addison-O'Hare 2016 6 16    71054
Name: 6, dtype: int64
Addison-O'Hare 2017 6 16    80100
Name: 6, dtype: int64
Addison-O'Hare 2018 6 16    75587
Name: 6, dtype: int64
Addison-O'Hare 2019 6 16    68274
Name: 6, dtype: int64
Addison-O'Hare 2013 7 16    77509
Name: 7, dtype: int64
Addison-O'Hare 2014 7 16    76065
Name: 7, dtype: int64
Addison-O'Hare 2015 7 16    85297
Name: 7, dtype: int64
Addison-O'Hare 2016 7 16    81181
Name: 7, dtype: int64
Addison-O'Hare 2017 7 16    73866
Name: 7, dtype: int64
Addison-O'Hare 2018 7 16    75707
Name: 7, dtype: int64
Addison-O'Hare 2019 7 16    75403
Name: 7, dtype: int64
Addison-O'Hare 2013 8 16    80391
Name: 8, dtype: int64
Addison-O'Hare 2014 8 16    73400
Name: 8, dtype: int64
Addison-O'Hare 2015 8 16    81410
Name: 8, dtype: int64
Addison-O'Hare 2016 8 16    78886
Name: 8, dtype: int64
Addison-O'Hare 2017 8 16    78726
Name: 8, dtype: int64
Addison-O'Hare 2018 8 16    0
Name: 8, dtype: int64
Addison-O'Hare 2019 8 16    77455
Name: 8, dtype: int64
Addison-O'Hare 2013 9 16    78121
Name: 9, dtype: int64
Addison-O'Hare 2014 9 16    81479
Name: 9, dtype: int64
Addison-O'Hare 2015 9 16    87295
Name: 9, dtype: int64
Addison-O'Hare 2016 9 16    81396
Name: 9, dtype: int64
Addison-O'Hare 2017 9 16    78794
Name: 9, dtype: int64
Addison-O'Hare 2018 9 16    0
Name: 9, dtype: int64
Addison-O'Hare 2019 9 16    78870
Name: 9, dtype: int64
Addison-O'Hare 2013 10 16    83558
Name: 10, dtype: int64
Addison-O'Hare 2014 10 16    85716
Name: 10, dtype: int64
Addison-O'Hare 2015 10 16    88658
Name: 10, dtype: int64
Addison-O'Hare 2016 10 16    83101
Name: 10, dtype: int64
Addison-O'Hare 2017 10 16    81236
Name: 10, dtype: int64
Addison-O'Hare 2018 10 16    0
Name: 10, dtype: int64
Addison-O'Hare 2019 10 16    79930
Name: 10, dtype: int64
Addison-O'Hare 2013 11 16    71119
Name: 11, dtype: int64
Addison-O'Hare 2014 11 16    70198
Name: 11, dtype: int64
Addison-O'Hare 2015 11 16    75797
Name: 11, dtype: int64
Addison-O'Hare 2016 11 16    76124
Name: 11, dtype: int64
Addison-O'Hare 2017 11 16    72846
Name: 11, dtype: int64
Addison-O'Hare 2018 11 16    0
Name: 11, dtype: int64
Addison-O'Hare 2019 11 16    68899
Name: 11, dtype: int64
Addison-O'Hare 2013 12 16    66384
Name: 12, dtype: int64
Addison-O'Hare 2014 12 16    71482
Name: 12, dtype: int64
Addison-O'Hare 2015 12 16    74220
Name: 12, dtype: int64
Addison-O'Hare 2016 12 16    65994
Name: 12, dtype: int64
Addison-O'Hare 2017 12 16    63954
Name: 12, dtype: int64
Addison-O'Hare 2018 12 16    0
Name: 12, dtype: int64
Addison-O'Hare 2019 12 16    65191
Name: 12, dtype: int64
Argyle 2013 1 17    73843
Name: 1, dtype: int64
Argyle 2014 1 17    82505
Name: 1, dtype: int64
Argyle 2015 1 17    84382
Name: 1, dtype: int64
Argyle 2016 1 17    84171
Name: 1, dtype: int64
Argyle 2017 1 17    81868
Name: 1, dtype: int64
Argyle 2018 1 17    79556
Name: 1, dtype: int64
Argyle 2019 1 17    74175
Name: 1, dtype: int64
Argyle 2013 2 17    70105
Name: 2, dtype: int64
Argyle 2014 2 17    81234
Name: 2, dtype: int64
Argyle 2015 2 17    79766
Name: 2, dtype: int64
Argyle 2016 2 17    84469
Name: 2, dtype: int64
Argyle 2017 2 17    77486
Name: 2, dtype: int64
Argyle 2018 2 17    77004
Name: 2, dtype: int64
Argyle 2019 2 17    74230
Name: 2, dtype: int64
Argyle 2013 3 17    78888
Name: 3, dtype: int64
Argyle 2014 3 17    91618
Name: 3, dtype: int64
Argyle 2015 3 17    89322
Name: 3, dtype: int64
Argyle 2016 3 17    89907
Name: 3, dtype: int64
Argyle 2017 3 17    87560
Name: 3, dtype: int64
Argyle 2018 3 17    85528
Name: 3, dtype: int64
Argyle 2019 3 17    82121
Name: 3, dtype: int64
Argyle 2013 4 17    75771
Name: 4, dtype: int64
Argyle 2014 4 17    89317
Name: 4, dtype: int64
Argyle 2015 4 17    90221
Name: 4, dtype: int64
Argyle 2016 4 17    87663
Name: 4, dtype: int64
Argyle 2017 4 17    82551
Name: 4, dtype: int64
Argyle 2018 4 17    82554
Name: 4, dtype: int64
Argyle 2019 4 17    80761
Name: 4, dtype: int64
Argyle 2013 5 17    80232

Name: 5, dtype: int64
Argyle 2014 5 17    92077
Name: 5, dtype: int64
Argyle 2015 5 17    91956
Name: 5, dtype: int64
Argyle 2016 5 17    89377
Name: 5, dtype: int64
Argyle 2017 5 17    85500
Name: 5, dtype: int64
Argyle 2018 5 17    85595
Name: 5, dtype: int64
Argyle 2019 5 17    83486
Name: 5, dtype: int64
Argyle 2013 6 17    83788
Name: 6, dtype: int64
Argyle 2014 6 17    88900
Name: 6, dtype: int64
Argyle 2015 6 17    94760
Name: 6, dtype: int64
Argyle 2016 6 17    91034
Name: 6, dtype: int64
Argyle 2017 6 17    86763
Name: 6, dtype: int64
Argyle 2018 6 17    84701
Name: 6, dtype: int64
Argyle 2019 6 17    83411
Name: 6, dtype: int64
Argyle 2013 7 17    85095
Name: 7, dtype: int64
Argyle 2014 7 17    92389
Name: 7, dtype: int64
Argyle 2015 7 17    96942
Name: 7, dtype: int64
Argyle 2016 7 17    90190
Name: 7, dtype: int64
Argyle 2017 7 17    85736
Name: 7, dtype: int64
Argyle 2018 7 17    85338
Name: 7, dtype: int64
Argyle 2019 7 17    83179
Name: 7, dtype: int64
Argyle 2013 8 17    87890
Name: 8, dtype: int64
Argyle 2014 8 17    94497
Name: 8, dtype: int64
Argyle 2015 8 17    92760
Name: 8, dtype: int64
Argyle 2016 8 17    90577
Name: 8, dtype: int64
Argyle 2017 8 17    89334
Name: 8, dtype: int64
Argyle 2018 8 17    0
Name: 8, dtype: int64
Argyle 2019 8 17    84976
Name: 8, dtype: int64
Argyle 2013 9 17    84730
Name: 9, dtype: int64
Argyle 2014 9 17    93936
Name: 9, dtype: int64
Argyle 2015 9 17    91936
Name: 9, dtype: int64
Argyle 2016 9 17    92049
Name: 9, dtype: int64
Argyle 2017 9 17    86852
Name: 9, dtype: int64
Argyle 2018 9 17    0
Name: 9, dtype: int64
Argyle 2019 9 17    83122
Name: 9, dtype: int64
Argyle 2013 10 17    92054
Name: 10, dtype: int64
Argyle 2014 10 17    99781
Name: 10, dtype: int64
Argyle 2015 10 17    97007
Name: 10, dtype: int64
Argyle 2016 10 17    93935
Name: 10, dtype: int64
Argyle 2017 10 17    90510
Name: 10, dtype: int64
Argyle 2018 10 17    0
Name: 10, dtype: int64
Argyle 2019 10 17    89759
Name: 10, dtype: int64
Argyle 2013 11 17    84025
Name: 11, dtype: int64
Argyle 2014 11 17    86893
Name: 11, dtype: int64
Argyle 2015 11 17    85550
Name: 11, dtype: int64
Argyle 2016 11 17    87267
Name: 11, dtype: int64
Argyle 2017 11 17    81583
Name: 11, dtype: int64
Argyle 2018 11 17    0
Name: 11, dtype: int64
Argyle 2019 11 17    79162
Name: 11, dtype: int64
Argyle 2013 12 17    79681
Name: 12, dtype: int64
Argyle 2014 12 17    86218
Name: 12, dtype: int64
Argyle 2015 12 17    84018
Name: 12, dtype: int64
Argyle 2016 12 17    78902
Name: 12, dtype: int64
Argyle 2017 12 17    75324
Name: 12, dtype: int64
Argyle 2018 12 17    0
Name: 12, dtype: int64
Argyle 2019 12 17    71748
Name: 12, dtype: int64
Armitage 2013 1 18    111855
Name: 1, dtype: int64
Armitage 2014 1 18    103827
Name: 1, dtype: int64
Armitage 2015 1 18    106902
Name: 1, dtype: int64
Armitage 2016 1 18    108055
Name: 1, dtype: int64
Armitage 2017 1 18    104189
Name: 1, dtype: int64
Armitage 2018 1 18    106487
Name: 1, dtype: int64
Armitage 2019 1 18    95486
Name: 1, dtype: int64
Armitage 2013 2 18    104356
Name: 2, dtype: int64
Armitage 2014 2 18    105464
Name: 2, dtype: int64
Armitage 2015 2 18    104940
Name: 2, dtype: int64
Armitage 2016 2 18    108390
Name: 2, dtype: int64
Armitage 2017 2 18    100280
Name: 2, dtype: int64
Armitage 2018 2 18    100316
Name: 2, dtype: int64
Armitage 2019 2 18    95963
Name: 2, dtype: int64
Armitage 2013 3 18    99279
Name: 3, dtype: int64
Armitage 2014 3 18    118034
Name: 3, dtype: int64
Armitage 2015 3 18    113839
Name: 3, dtype: int64
Armitage 2016 3 18    119657
Name: 3, dtype: int64
Armitage 2017 3 18    116142
Name: 3, dtype: int64
Armitage 2018 3 18    111403
Name: 3, dtype: int64
Armitage 2019 3 18    107480
Name: 3, dtype: int64
Armitage 2013 4 18    110722
Name: 4, dtype: int64
Armitage 2014 4 18    113302
Name: 4, dtype: int64
Armitage 2015 4 18    100431
Name: 4, dtype: int64
Armitage 2016 4 18    109751
Name: 4, dtype: int64
Armitage 2017 4 18    103424
Name: 4, dtype: int64
Armitage 2018 4 18    108296
Name: 4, dtype: int64
Armitage 2019 4 18    102608
Name: 4, dtype: int64
Armitage 2013 5 18    110515
Name: 5, dtype: int64
Armitage 2014 5 18    117475
Name: 5, dtype: int64
Armitage 2015 5 18    95328
Name: 5, dtype: int64
Armitage 2016 5 18    117538
Name: 5, dtype: int64
Armitage 2017 5 18    117770
Name: 5, dtype: int64
Armitage 2018 5 18    116994
Name: 5, dtype: int64
Armitage 2019 5 18    115613
Name: 5, dtype: int64
Armitage 2013 6 18    116795
Name: 6, dtype: int64
Armitage 2014 6 18    112246
Name: 6, dtype: int64
Armitage 2015 6 18    108800
Name: 6, dtype: int64
Armitage 2016 6 18    118712
Name: 6, dtype: int64
Armitage 2017 6 18    117674
Name: 6, dtype: int64
Armitage 2018 6 18    110562
Name: 6, dtype: int64
Armitage 2019 6 18    108816
Name: 6, dtype: int64
Armitage 2013 7 18    109214
Name: 7, dtype: int64
Armitage 2014 7 18    107723
Name: 7, dtype: int64
Armitage 2015 7 18    98605
Name: 7, dtype: int64
Armitage 2016 7 18    106349
Name: 7, dtype: int64
Armitage 2017 7 18    101630
Name: 7, dtype: int64
Armitage 2018 7 18    0
Name: 7, dtype: int64
Armitage 2019 7 18    100960
Name: 7, dtype: int64
Armitage 2013 8 18    113951
Name: 8, dtype: int64
Armitage 2014 8 18    104508
Name: 8, dtype: int64
Armitage 2015 8 18    89997
Name: 8, dtype: int64
Armitage 2016 8 18    107534
Name: 8, dtype: int64
Armitage 2017 8 18    110029
Name: 8, dtype: int64
Armitage 2018 8 18    0
Name: 8, dtype: int64
Armitage 2019 8 18    103266
Name: 8, dtype: int64
Armitage 2013 9 18    115727
Name: 9, dtype: int64
Armitage 2014 9 18    117511
Name: 9, dtype: int64
Armitage 2015 9 18    97766
Name: 9, dtype: int64
Armitage 2016 9 18    115110
Name: 9, dtype: int64
Armitage 2017 9 18    115647
Name: 9, dtype: int64
Armitage 2018 9 18    0
Name: 9, dtype: int64
Armitage 2019 9 18    110670
Name: 9, dtype: int64
Armitage 2013 10 18    130405
Name: 10, dtype: int64
Armitage 2014 10 18    128463
Name: 10, dtype: int64
Armitage 2015 10 18    122028
Name: 10, dtype: int64
Armitage 2016 10 18    125798
Name: 10, dtype: int64
Armitage 2017 10 18    123516
Name: 10, dtype: int64
Armitage 2018 10 18    0
Name: 10, dtype: int64
Armitage 2019 10 18    113649
Name: 10, dtype: int64
Armitage 2013 11 18    107650
Name: 11, dtype: int64
Armitage 2014 11 18    99678
Name: 11, dtype: int64
Armitage 2015 11 18    103362
Name: 11, dtype: int64
Armitage 2016 11 18    108719
Name: 11, dtype: int64
Armitage 2017 11 18    107717
Name: 11, dtype: int64
Armitage 2018 11 18    0
Name: 11, dtype: int64
Armitage 2019 11 18    98752
Name: 11, dtype: int64
Armitage 2013 12 18    98335
Name: 12, dtype: int64
Armitage 2014 12 18    101751
Name: 12, dtype: int64
Armitage 2015 12 18    100740
Name: 12, dtype: int64
Armitage 2016 12 18    97007
Name: 12, dtype: int64
Armitage 2017 12 18    95151
Name: 12, dtype: int64
Armitage 2018 12 18    0
Name: 12, dtype: int64
Armitage 2019 12 18    90388
Name: 12, dtype: int64
Ashland-Lake 2013 1 19    58430
Name: 1, dtype: int64
Ashland-Lake 2014 1 19    53321
Name: 1, dtype: int64
Ashland-Lake 2015 1 19    57499
Name: 1, dtype: int64
Ashland-Lake 2016 1 19    57351
Name: 1, dtype: int64
Ashland-Lake 2017 1 19    55439
Name: 1, dtype: int64
Ashland-Lake 2018 1 19    55948
Name: 1, dtype: int64
Ashland-Lake 2019 1 19    51938
Name: 1, dtype: int64
Ashland-Lake 2013 2 19    55885
Name: 2, dtype: int64
Ashland-Lake 2014 2 19    54238
Name: 2, dtype: int64
Ashland-Lake 2015 2 19    56322
Name: 2, dtype: int64
Ashland-Lake 2016 2 19    56947
Name: 2, dtype: int64
Ashland-Lake 2017 2 19    54353
Name: 2, dtype: int64
Ashland-Lake 2018 2 19    53526
Name: 2, dtype: int64
Ashland-Lake 2019 2 19    53390
Name: 2, dtype: int64
Ashland-Lake 2013 3 19    62623
Name: 3, dtype: int64
Ashland-Lake 2014 3 19    65070
Name: 3, dtype: int64
Ashland-Lake 2015 3 19    67588
Name: 3, dtype: int64
Ashland-Lake 2016 3 19    65914
Name: 3, dtype: int64
Ashland-Lake 2017 3 19    63131
Name: 3, dtype: int64
Ashland-Lake 2018 3 19    67944
Name: 3, dtype: int64
Ashland-Lake 2019 3 19    61830
Name: 3, dtype: int64
Ashland-Lake 2013 4 19    63094
Name: 4, dtype: int64
Ashland-Lake 2014 4 19    62579
Name: 4, dtype: int64
Ashland-Lake 2015 4 19    66158
Name: 4, dtype: int64
Ashland-Lake 2016 4 19    61087
Name: 4, dtype: int64
Ashland-Lake 2017 4 19    57932
Name: 4, dtype: int64
Ashland-Lake 2018 4 19    57891
Name: 4, dtype: int64
Ashland-Lake 2019 4 19    59842
Name: 4, dtype: int64

Ashland-Lake 2013 5 19    66314
Name: 5, dtype: int64
Ashland-Lake 2014 5 19    63973
Name: 5, dtype: int64
Ashland-Lake 2015 5 19    67593
Name: 5, dtype: int64
Ashland-Lake 2016 5 19    62123
Name: 5, dtype: int64
Ashland-Lake 2017 5 19    63179
Name: 5, dtype: int64
Ashland-Lake 2018 5 19    63217
Name: 5, dtype: int64
Ashland-Lake 2019 5 19    64216
Name: 5, dtype: int64
Ashland-Lake 2013 6 19    62219
Name: 6, dtype: int64
Ashland-Lake 2014 6 19    63460
Name: 6, dtype: int64
Ashland-Lake 2015 6 19    71027
Name: 6, dtype: int64
Ashland-Lake 2016 6 19    62969
Name: 6, dtype: int64
Ashland-Lake 2017 6 19    62281
Name: 6, dtype: int64
Ashland-Lake 2018 6 19    60952
Name: 6, dtype: int64
Ashland-Lake 2019 6 19    61339
Name: 6, dtype: int64
Ashland-Lake 2013 7 19    81403
Name: 7, dtype: int64
Ashland-Lake 2014 7 19    80655
Name: 7, dtype: int64
Ashland-Lake 2015 7 19    87105
Name: 7, dtype: int64
Ashland-Lake 2016 7 19    73473
Name: 7, dtype: int64
Ashland-Lake 2017 7 19    70346
Name: 7, dtype: int64
Ashland-Lake 2018 7 19    71066
Name: 7, dtype: int64
Ashland-Lake 2019 7 19    70240
Name: 7, dtype: int64
Ashland-Lake 2013 8 19    72324
Name: 8, dtype: int64
Ashland-Lake 2014 8 19    72405
Name: 8, dtype: int64
Ashland-Lake 2015 8 19    66327
Name: 8, dtype: int64
Ashland-Lake 2016 8 19    62564
Name: 8, dtype: int64
Ashland-Lake 2017 8 19    63150
Name: 8, dtype: int64
Ashland-Lake 2018 8 19    0
Name: 8, dtype: int64
Ashland-Lake 2019 8 19    63734
Name: 8, dtype: int64
Ashland-Lake 2013 9 19    67913
Name: 9, dtype: int64
Ashland-Lake 2014 9 19    68678
Name: 9, dtype: int64
Ashland-Lake 2015 9 19    75684
Name: 9, dtype: int64
Ashland-Lake 2016 9 19    72982
Name: 9, dtype: int64
Ashland-Lake 2017 9 19    70437
Name: 9, dtype: int64
Ashland-Lake 2018 9 19    0
Name: 9, dtype: int64
Ashland-Lake 2019 9 19    65545
Name: 9, dtype: int64
Ashland-Lake 2013 10 19    73856
Name: 10, dtype: int64
Ashland-Lake 2014 10 19    74792
Name: 10, dtype: int64
Ashland-Lake 2015 10 19    72257
Name: 10, dtype: int64
Ashland-Lake 2016 10 19    68045
Name: 10, dtype: int64
Ashland-Lake 2017 10 19    67067
Name: 10, dtype: int64
Ashland-Lake 2018 10 19    0
Name: 10, dtype: int64
Ashland-Lake 2019 10 19    73179
Name: 10, dtype: int64
Ashland-Lake 2013 11 19    60259
Name: 11, dtype: int64
Ashland-Lake 2014 11 19    61246
Name: 11, dtype: int64
Ashland-Lake 2015 11 19    63212
Name: 11, dtype: int64
Ashland-Lake 2016 11 19    61947
Name: 11, dtype: int64
Ashland-Lake 2017 11 19    59596
Name: 11, dtype: int64
Ashland-Lake 2018 11 19    0
Name: 11, dtype: int64
Ashland-Lake 2019 11 19    62846
Name: 11, dtype: int64
Ashland-Lake 2013 12 19    56399
Name: 12, dtype: int64
Ashland-Lake 2014 12 19    62086
Name: 12, dtype: int64
Ashland-Lake 2015 12 19    60225
Name: 12, dtype: int64
Ashland-Lake 2016 12 19    54045
Name: 12, dtype: int64
Ashland-Lake 2017 12 19    52876
Name: 12, dtype: int64
Ashland-Lake 2018 12 19    0
Name: 12, dtype: int64
Ashland-Lake 2019 12 19    56966
Name: 12, dtype: int64
Ashland-Orange 2013 1 20    39024
Name: 1, dtype: int64
Ashland-Orange 2014 1 20    35258
Name: 1, dtype: int64
Ashland-Orange 2015 1 20    37337
Name: 1, dtype: int64
Ashland-Orange 2016 1 20    38008
Name: 1, dtype: int64
Ashland-Orange 2017 1 20    37315
Name: 1, dtype: int64
Ashland-Orange 2018 1 20    36981
Name: 1, dtype: int64
Ashland-Orange 2019 1 20    33958
Name: 1, dtype: int64
Ashland-Orange 2013 2 20    36965
Name: 2, dtype: int64
Ashland-Orange 2014 2 20    36760
Name: 2, dtype: int64
Ashland-Orange 2015 2 20    35553
Name: 2, dtype: int64
Ashland-Orange 2016 2 20    39663
Name: 2, dtype: int64
Ashland-Orange 2017 2 20    36767
Name: 2, dtype: int64
Ashland-Orange 2018 2 20    35436
Name: 2, dtype: int64
Ashland-Orange 2019 2 20    34789
Name: 2, dtype: int64
Ashland-Orange 2013 3 20    40612
Name: 3, dtype: int64
Ashland-Orange 2014 3 20    42738
Name: 3, dtype: int64
Ashland-Orange 2015 3 20    43443
Name: 3, dtype: int64
Ashland-Orange 2016 3 20    44391
Name: 3, dtype: int64
Ashland-Orange 2017 3 20    43731
Name: 3, dtype: int64
Ashland-Orange 2018 3 20    40295
Name: 3, dtype: int64
Ashland-Orange 2019 3 20    38839
Name: 3, dtype: int64
Ashland-Orange 2013 4 20    42027
Name: 4, dtype: int64
Ashland-Orange 2014 4 20    41606
Name: 4, dtype: int64
Ashland-Orange 2015 4 20    42395
Name: 4, dtype: int64
Ashland-Orange 2016 4 20    42583
Name: 4, dtype: int64
Ashland-Orange 2017 4 20    40191
Name: 4, dtype: int64
Ashland-Orange 2018 4 20    39077
Name: 4, dtype: int64
Ashland-Orange 2019 4 20    38802
Name: 4, dtype: int64
Ashland-Orange 2013 5 20    45660
Name: 5, dtype: int64
Ashland-Orange 2014 5 20    42413
Name: 5, dtype: int64
Ashland-Orange 2015 5 20    42869
Name: 5, dtype: int64
Ashland-Orange 2016 5 20    44554
Name: 5, dtype: int64
Ashland-Orange 2017 5 20    44206
Name: 5, dtype: int64
Ashland-Orange 2018 5 20    42605
Name: 5, dtype: int64
Ashland-Orange 2019 5 20    41961
Name: 5, dtype: int64
Ashland-Orange 2013 6 20    46686
Name: 6, dtype: int64
Ashland-Orange 2014 6 20    42205
Name: 6, dtype: int64
Ashland-Orange 2015 6 20    44968
Name: 6, dtype: int64
Ashland-Orange 2016 6 20    46097
Name: 6, dtype: int64
Ashland-Orange 2017 6 20    44677
Name: 6, dtype: int64
Ashland-Orange 2018 6 20    42187
Name: 6, dtype: int64
Ashland-Orange 2019 6 20    39912
Name: 6, dtype: int64
Ashland-Orange 2013 7 20    47984
Name: 7, dtype: int64
Ashland-Orange 2014 7 20    43512
Name: 7, dtype: int64
Ashland-Orange 2015 7 20    45432
Name: 7, dtype: int64
Ashland-Orange 2016 7 20    42756
Name: 7, dtype: int64
Ashland-Orange 2017 7 20    41446
Name: 7, dtype: int64
Ashland-Orange 2018 7 20    0
Name: 7, dtype: int64
Ashland-Orange 2019 7 20    41473
Name: 7, dtype: int64
Ashland-Orange 2013 8 20    48443
Name: 8, dtype: int64
Ashland-Orange 2014 8 20    42471
Name: 8, dtype: int64
Ashland-Orange 2015 8 20    43659
Name: 8, dtype: int64
Ashland-Orange 2016 8 20    44005
Name: 8, dtype: int64
Ashland-Orange 2017 8 20    44544
Name: 8, dtype: int64
Ashland-Orange 2018 8 20    0
Name: 8, dtype: int64
Ashland-Orange 2019 8 20    41977
Name: 8, dtype: int64
Ashland-Orange 2013 9 20    49007
Name: 9, dtype: int64
Ashland-Orange 2014 9 20    44922
Name: 9, dtype: int64
Ashland-Orange 2015 9 20    48572
Name: 9, dtype: int64
Ashland-Orange 2016 9 20    45401
Name: 9, dtype: int64
Ashland-Orange 2017 9 20    43725
Name: 9, dtype: int64
Ashland-Orange 2018 9 20    0
Name: 9, dtype: int64
Ashland-Orange 2019 9 20    43404
Name: 9, dtype: int64
Ashland-Orange 2013 10 20    52845
Name: 10, dtype: int64
Ashland-Orange 2014 10 20    47987
Name: 10, dtype: int64
Ashland-Orange 2015 10 20    49222
Name: 10, dtype: int64
Ashland-Orange 2016 10 20    47055
Name: 10, dtype: int64
Ashland-Orange 2017 10 20    46730
Name: 10, dtype: int64
Ashland-Orange 2018 10 20    0
Name: 10, dtype: int64
Ashland-Orange 2019 10 20    46661
Name: 10, dtype: int64
Ashland-Orange 2013 11 20    41833
Name: 11, dtype: int64
Ashland-Orange 2014 11 20    38860
Name: 11, dtype: int64
Ashland-Orange 2015 11 20    42798
Name: 11, dtype: int64
Ashland-Orange 2016 11 20    43822
Name: 11, dtype: int64
Ashland-Orange 2017 11 20    41317
Name: 11, dtype: int64
Ashland-Orange 2018 11 20    0
Name: 11, dtype: int64
Ashland-Orange 2019 11 20    39352
Name: 11, dtype: int64
Ashland-Orange 2013 12 20    38364
Name: 12, dtype: int64
Ashland-Orange 2014 12 20    39370
Name: 12, dtype: int64
Ashland-Orange 2015 12 20    41970
Name: 12, dtype: int64
Ashland-Orange 2016 12 20    38251
Name: 12, dtype: int64
Ashland-Orange 2017 12 20    37317
Name: 12, dtype: int64
Ashland-Orange 2018 12 20    0
Name: 12, dtype: int64
Ashland-Orange 2019 12 20    37038
Name: 12, dtype: int64
Ashland/63rd 2013 1 21    39288
Name: 1, dtype: int64
Ashland/63rd 2014 1 21    34927
Name: 1, dtype: int64
Ashland/63rd 2015 1 21    33479
Name: 1, dtype: int64
Ashland/63rd 2016 1 21    31891
Name: 1, dtype: int64
Ashland/63rd 2017 1 21    27353
Name: 1, dtype: int64
Ashland/63rd 2018 1 21    27240
Name: 1, dtype: int64
Ashland/63rd 2019 1 21    23508
Name: 1, dtype: int64
Ashland/63rd 2013 2 21    36149
Name: 2, dtype: int64
Ashland/63rd 2014 2 21    34930
Name: 2, dtype: int64
Ashland/63rd 2015 2 21    30989
Name: 2, dtype: int64
Ashland/63rd 2016 2 21    30674
Name: 2, dtype: int64
Ashland/63rd 2017 2 21    27085
Name: 2, dtype: int64
Ashland/63rd 2018 2 21    25774
Name: 2, dtype: int64
Ashland/63rd 2019 2 21    22839
Name: 2, dtype: int64
Ashland/63rd 2013 3 21    34885
Name: 3, dtype: int64
Ashland/63rd 2014 3 21    39757
Name: 3, dtype: int64
Ashland/63rd 2015 3 21    37166
Name: 3, dtype: int64
Ashland/63rd 2016 3 21    32838
Name: 3, dtype: int64
Ashland/63rd 2017 3 21    29710
Name: 3, dtype: int64
Ashland/63rd 2018 3 21    28743
Name: 3, dtype: int64
Ashland/63rd 2019 3 21    24957
Name: 3, dtype: int64

Ashland/63rd 2013 4 21    33348
Name: 4, dtype: int64
Ashland/63rd 2014 4 21    38595
Name: 4, dtype: int64
Ashland/63rd 2015 4 21    36393
Name: 4, dtype: int64
Ashland/63rd 2016 4 21    30237
Name: 4, dtype: int64
Ashland/63rd 2017 4 21    28257
Name: 4, dtype: int64
Ashland/63rd 2018 4 21    28583
Name: 4, dtype: int64
Ashland/63rd 2019 4 21    25855
Name: 4, dtype: int64
Ashland/63rd 2013 5 21    58607
Name: 5, dtype: int64
Ashland/63rd 2014 5 21    40974
Name: 5, dtype: int64
Ashland/63rd 2015 5 21    37911
Name: 5, dtype: int64
Ashland/63rd 2016 5 21    32124
Name: 5, dtype: int64
Ashland/63rd 2017 5 21    31451
Name: 5, dtype: int64
Ashland/63rd 2018 5 21    30892
Name: 5, dtype: int64
Ashland/63rd 2019 5 21    27866
Name: 5, dtype: int64
Ashland/63rd 2013 6 21    86195
Name: 6, dtype: int64
Ashland/63rd 2014 6 21    40182
Name: 6, dtype: int64
Ashland/63rd 2015 6 21    38776
Name: 6, dtype: int64
Ashland/63rd 2016 6 21    32447
Name: 6, dtype: int64
Ashland/63rd 2017 6 21    31684
Name: 6, dtype: int64
Ashland/63rd 2018 6 21    29975
Name: 6, dtype: int64
Ashland/63rd 2019 6 21    25690
Name: 6, dtype: int64
Ashland/63rd 2013 7 21    92782
Name: 7, dtype: int64
Ashland/63rd 2014 7 21    41710
Name: 7, dtype: int64
Ashland/63rd 2015 7 21    40505
Name: 7, dtype: int64
Ashland/63rd 2016 7 21    32667
Name: 7, dtype: int64
Ashland/63rd 2017 7 21    31641
Name: 7, dtype: int64
Ashland/63rd 2018 7 21    0
Name: 7, dtype: int64
Ashland/63rd 2019 7 21    26815
Name: 7, dtype: int64
Ashland/63rd 2013 8 21    95501
Name: 8, dtype: int64
Ashland/63rd 2014 8 21    44396
Name: 8, dtype: int64
Ashland/63rd 2015 8 21    38297
Name: 8, dtype: int64
Ashland/63rd 2016 8 21    32362
Name: 8, dtype: int64
Ashland/63rd 2017 8 21    33238
Name: 8, dtype: int64
Ashland/63rd 2018 8 21    0
Name: 8, dtype: int64
Ashland/63rd 2019 8 21    27123
Name: 8, dtype: int64
Ashland/63rd 2013 9 21    95350
Name: 9, dtype: int64
Ashland/63rd 2014 9 21    44459
Name: 9, dtype: int64
Ashland/63rd 2015 9 21    38299
Name: 9, dtype: int64
Ashland/63rd 2016 9 21    30511
Name: 9, dtype: int64
Ashland/63rd 2017 9 21    33511
Name: 9, dtype: int64
Ashland/63rd 2018 9 21    0
Name: 9, dtype: int64
Ashland/63rd 2019 9 21    26127
Name: 9, dtype: int64
Ashland/63rd 2013 10 21    85119
Name: 10, dtype: int64
Ashland/63rd 2014 10 21    45419
Name: 10, dtype: int64
Ashland/63rd 2015 10 21    39944
Name: 10, dtype: int64
Ashland/63rd 2016 10 21    32024
Name: 10, dtype: int64
Ashland/63rd 2017 10 21    33952
Name: 10, dtype: int64
Ashland/63rd 2018 10 21    0
Name: 10, dtype: int64
Ashland/63rd 2019 10 21    26519
Name: 10, dtype: int64
Ashland/63rd 2013 11 21    43034
Name: 11, dtype: int64
Ashland/63rd 2014 11 21    36898
Name: 11, dtype: int64
Ashland/63rd 2015 11 21    35840
Name: 11, dtype: int64
Ashland/63rd 2016 11 21    31030
Name: 11, dtype: int64
Ashland/63rd 2017 11 21    31001
Name: 11, dtype: int64
Ashland/63rd 2018 11 21    0
Name: 11, dtype: int64
Ashland/63rd 2019 11 21    22454
Name: 11, dtype: int64
Ashland/63rd 2013 12 21    38415
Name: 12, dtype: int64
Ashland/63rd 2014 12 21    37090
Name: 12, dtype: int64
Ashland/63rd 2015 12 21    35192
Name: 12, dtype: int64
Ashland/63rd 2016 12 21    27891
Name: 12, dtype: int64
Ashland/63rd 2017 12 21    27948
Name: 12, dtype: int64
Ashland/63rd 2018 12 21    0
Name: 12, dtype: int64
Ashland/63rd 2019 12 21    22137
Name: 12, dtype: int64
Austin-Forest Park 2013 1 22    50433
Name: 1, dtype: int64
Austin-Forest Park 2014 1 22    45668
Name: 1, dtype: int64
Austin-Forest Park 2015 1 22    47270
Name: 1, dtype: int64
Austin-Forest Park 2016 1 22    46387
Name: 1, dtype: int64
Austin-Forest Park 2017 1 22    48063
Name: 1, dtype: int64
Austin-Forest Park 2018 1 22    44050
Name: 1, dtype: int64
Austin-Forest Park 2019 1 22    40799
Name: 1, dtype: int64
Austin-Forest Park 2013 2 22    47582
Name: 2, dtype: int64
Austin-Forest Park 2014 2 22    46834
Name: 2, dtype: int64
Austin-Forest Park 2015 2 22    45239
Name: 2, dtype: int64
Austin-Forest Park 2016 2 22    48648
Name: 2, dtype: int64
Austin-Forest Park 2017 2 22    47089
Name: 2, dtype: int64
Austin-Forest Park 2018 2 22    42282
Name: 2, dtype: int64
Austin-Forest Park 2019 2 22    42096
Name: 2, dtype: int64
Austin-Forest Park 2013 3 22    51571
Name: 3, dtype: int64
Austin-Forest Park 2014 3 22    52180
Name: 3, dtype: int64
Austin-Forest Park 2015 3 22    54124
Name: 3, dtype: int64
Austin-Forest Park 2016 3 22    52719
Name: 3, dtype: int64
Austin-Forest Park 2017 3 22    51896
Name: 3, dtype: int64
Austin-Forest Park 2018 3 22    46618
Name: 3, dtype: int64
Austin-Forest Park 2019 3 22    44146
Name: 3, dtype: int64
Austin-Forest Park 2013 4 22    54399
Name: 4, dtype: int64
Austin-Forest Park 2014 4 22    54372
Name: 4, dtype: int64
Austin-Forest Park 2015 4 22    53119
Name: 4, dtype: int64
Austin-Forest Park 2016 4 22    52467
Name: 4, dtype: int64
Austin-Forest Park 2017 4 22    48389
Name: 4, dtype: int64
Austin-Forest Park 2018 4 22    46893
Name: 4, dtype: int64
Austin-Forest Park 2019 4 22    46858
Name: 4, dtype: int64
Austin-Forest Park 2013 5 22    54771
Name: 5, dtype: int64
Austin-Forest Park 2014 5 22    55272
Name: 5, dtype: int64
Austin-Forest Park 2015 5 22    53021
Name: 5, dtype: int64
Austin-Forest Park 2016 5 22    52828
Name: 5, dtype: int64
Austin-Forest Park 2017 5 22    51013
Name: 5, dtype: int64
Austin-Forest Park 2018 5 22    48748
Name: 5, dtype: int64
Austin-Forest Park 2019 5 22    48136
Name: 5, dtype: int64
Austin-Forest Park 2013 6 22    51608
Name: 6, dtype: int64
Austin-Forest Park 2014 6 22    54000
Name: 6, dtype: int64
Austin-Forest Park 2015 6 22    54362
Name: 6, dtype: int64
Austin-Forest Park 2016 6 22    54431
Name: 6, dtype: int64
Austin-Forest Park 2017 6 22    51494
Name: 6, dtype: int64
Austin-Forest Park 2018 6 22    47426
Name: 6, dtype: int64
Austin-Forest Park 2019 6 22    45723
Name: 6, dtype: int64
Austin-Forest Park 2013 7 22    53592
Name: 7, dtype: int64
Austin-Forest Park 2014 7 22    55721
Name: 7, dtype: int64
Austin-Forest Park 2015 7 22    56216
Name: 7, dtype: int64
Austin-Forest Park 2016 7 22    52213
Name: 7, dtype: int64
Austin-Forest Park 2017 7 22    48220
Name: 7, dtype: int64
Austin-Forest Park 2018 7 22    47299
Name: 7, dtype: int64
Austin-Forest Park 2019 7 22    47627
Name: 7, dtype: int64
Austin-Forest Park 2013 8 22    54521
Name: 8, dtype: int64
Austin-Forest Park 2014 8 22    54273
Name: 8, dtype: int64
Austin-Forest Park 2015 8 22    54292
Name: 8, dtype: int64
Austin-Forest Park 2016 8 22    55533
Name: 8, dtype: int64
Austin-Forest Park 2017 8 22    53347
Name: 8, dtype: int64
Austin-Forest Park 2018 8 22    0
Name: 8, dtype: int64
Austin-Forest Park 2019 8 22    47617
Name: 8, dtype: int64
Austin-Forest Park 2013 9 22    58492
Name: 9, dtype: int64
Austin-Forest Park 2014 9 22    58686
Name: 9, dtype: int64
Austin-Forest Park 2015 9 22    57067
Name: 9, dtype: int64
Austin-Forest Park 2016 9 22    56784
Name: 9, dtype: int64
Austin-Forest Park 2017 9 22    53600
Name: 9, dtype: int64
Austin-Forest Park 2018 9 22    0
Name: 9, dtype: int64
Austin-Forest Park 2019 9 22    47986
Name: 9, dtype: int64
Austin-Forest Park 2013 10 22    61011
Name: 10, dtype: int64
Austin-Forest Park 2014 10 22    61776
Name: 10, dtype: int64
Austin-Forest Park 2015 10 22    60205
Name: 10, dtype: int64
Austin-Forest Park 2016 10 22    56583
Name: 10, dtype: int64
Austin-Forest Park 2017 10 22    54481
Name: 10, dtype: int64
Austin-Forest Park 2018 10 22    0
Name: 10, dtype: int64
Austin-Forest Park 2019 10 22    51902
Name: 10, dtype: int64
Austin-Forest Park 2013 11 22    52256
Name: 11, dtype: int64
Austin-Forest Park 2014 11 22    50099
Name: 11, dtype: int64
Austin-Forest Park 2015 11 22    51320
Name: 11, dtype: int64
Austin-Forest Park 2016 11 22    53212
Name: 11, dtype: int64
Austin-Forest Park 2017 11 22    49231
Name: 11, dtype: int64
Austin-Forest Park 2018 11 22    0
Name: 11, dtype: int64
Austin-Forest Park 2019 11 22    42042
Name: 11, dtype: int64
Austin-Forest Park 2013 12 22    47461
Name: 12, dtype: int64
Austin-Forest Park 2014 12 22    49847
Name: 12, dtype: int64
Austin-Forest Park 2015 12 22    48737
Name: 12, dtype: int64
Austin-Forest Park 2016 12 22    44788
Name: 12, dtype: int64
Austin-Forest Park 2017 12 22    42507
Name: 12, dtype: int64

Austin-Forest Park 2018 12 22    0
Name: 12, dtype: int64
Austin-Forest Park 2019 12 22    38601
Name: 12, dtype: int64
Austin-Lake 2013 1 23    48334
Name: 1, dtype: int64
Austin-Lake 2014 1 23    45404
Name: 1, dtype: int64
Austin-Lake 2015 1 23    48075
Name: 1, dtype: int64
Austin-Lake 2016 1 23    48064
Name: 1, dtype: int64
Austin-Lake 2017 1 23    45804
Name: 1, dtype: int64
Austin-Lake 2018 1 23    44090
Name: 1, dtype: int64
Austin-Lake 2019 1 23    40353
Name: 1, dtype: int64
Austin-Lake 2013 2 23    45159
Name: 2, dtype: int64
Austin-Lake 2014 2 23    46415
Name: 2, dtype: int64
Austin-Lake 2015 2 23    45845
Name: 2, dtype: int64
Austin-Lake 2016 2 23    47718
Name: 2, dtype: int64
Austin-Lake 2017 2 23    45060
Name: 2, dtype: int64
Austin-Lake 2018 2 23    41504
Name: 2, dtype: int64
Austin-Lake 2019 2 23    39555
Name: 2, dtype: int64
Austin-Lake 2013 3 23    48501
Name: 3, dtype: int64
Austin-Lake 2014 3 23    52506
Name: 3, dtype: int64
Austin-Lake 2015 3 23    53348
Name: 3, dtype: int64
Austin-Lake 2016 3 23    53575
Name: 3, dtype: int64
Austin-Lake 2017 3 23    49639
Name: 3, dtype: int64
Austin-Lake 2018 3 23    46754
Name: 3, dtype: int64
Austin-Lake 2019 3 23    43153
Name: 3, dtype: int64
Austin-Lake 2013 4 23    50161
Name: 4, dtype: int64
Austin-Lake 2014 4 23    53338
Name: 4, dtype: int64
Austin-Lake 2015 4 23    53170
Name: 4, dtype: int64
Austin-Lake 2016 4 23    42223
Name: 4, dtype: int64
Austin-Lake 2017 4 23    47644
Name: 4, dtype: int64
Austin-Lake 2018 4 23    44970
Name: 4, dtype: int64
Austin-Lake 2019 4 23    43474
Name: 4, dtype: int64
Austin-Lake 2013 5 23    53096
Name: 5, dtype: int64
Austin-Lake 2014 5 23    54907
Name: 5, dtype: int64
Austin-Lake 2015 5 23    54068
Name: 5, dtype: int64
Austin-Lake 2016 5 23    44336
Name: 5, dtype: int64
Austin-Lake 2017 5 23    51729
Name: 5, dtype: int64
Austin-Lake 2018 5 23    49273
Name: 5, dtype: int64
Austin-Lake 2019 5 23    45997
Name: 5, dtype: int64
Austin-Lake 2013 6 23    51853
Name: 6, dtype: int64
Austin-Lake 2014 6 23    55612
Name: 6, dtype: int64
Austin-Lake 2015 6 23    56242
Name: 6, dtype: int64
Austin-Lake 2016 6 23    53635
Name: 6, dtype: int64
Austin-Lake 2017 6 23    53583
Name: 6, dtype: int64
Austin-Lake 2018 6 23    48712
Name: 6, dtype: int64
Austin-Lake 2019 6 23    44998
Name: 6, dtype: int64
Austin-Lake 2013 7 23    54943
Name: 7, dtype: int64
Austin-Lake 2014 7 23    58636
Name: 7, dtype: int64
Austin-Lake 2015 7 23    58724
Name: 7, dtype: int64
Austin-Lake 2016 7 23    52393
Name: 7, dtype: int64
Austin-Lake 2017 7 23    51100
Name: 7, dtype: int64
Austin-Lake 2018 7 23    48787
Name: 7, dtype: int64
Austin-Lake 2019 7 23    47633
Name: 7, dtype: int64
Austin-Lake 2013 8 23    55523
Name: 8, dtype: int64
Austin-Lake 2014 8 23    57550
Name: 8, dtype: int64
Austin-Lake 2015 8 23    55887
Name: 8, dtype: int64
Austin-Lake 2016 8 23    53884
Name: 8, dtype: int64
Austin-Lake 2017 8 23    53766
Name: 8, dtype: int64
Austin-Lake 2018 8 23    0
Name: 8, dtype: int64
Austin-Lake 2019 8 23    48337
Name: 8, dtype: int64
Austin-Lake 2013 9 23    54055
Name: 9, dtype: int64
Austin-Lake 2014 9 23    57351
Name: 9, dtype: int64
Austin-Lake 2015 9 23    55847
Name: 9, dtype: int64
Austin-Lake 2016 9 23    52495
Name: 9, dtype: int64
Austin-Lake 2017 9 23    51087
Name: 9, dtype: int64
Austin-Lake 2018 9 23    0
Name: 9, dtype: int64
Austin-Lake 2019 9 23    45207
Name: 9, dtype: int64
Austin-Lake 2013 10 23    58029
Name: 10, dtype: int64
Austin-Lake 2014 10 23    60080
Name: 10, dtype: int64
Austin-Lake 2015 10 23    58064
Name: 10, dtype: int64
Austin-Lake 2016 10 23    54262
Name: 10, dtype: int64
Austin-Lake 2017 10 23    52457
Name: 10, dtype: int64
Austin-Lake 2018 10 23    0
Name: 10, dtype: int64
Austin-Lake 2019 10 23    48289
Name: 10, dtype: int64
Austin-Lake 2013 11 23    50723
Name: 11, dtype: int64
Austin-Lake 2014 11 23    49873
Name: 11, dtype: int64
Austin-Lake 2015 11 23    51469
Name: 11, dtype: int64
Austin-Lake 2016 11 23    50433
Name: 11, dtype: int64
Austin-Lake 2017 11 23    47447
Name: 11, dtype: int64
Austin-Lake 2018 11 23    0
Name: 11, dtype: int64
Austin-Lake 2019 11 23    41386
Name: 11, dtype: int64
Austin-Lake 2013 12 23    47879
Name: 12, dtype: int64
Austin-Lake 2014 12 23    51722
Name: 12, dtype: int64
Austin-Lake 2015 12 23    52069
Name: 12, dtype: int64
Austin-Lake 2016 12 23    45088
Name: 12, dtype: int64
Austin-Lake 2017 12 23    43702
Name: 12, dtype: int64
Austin-Lake 2018 12 23    0
Name: 12, dtype: int64
Austin-Lake 2019 12 23    39782
Name: 12, dtype: int64
Belmont-North Main 2013 1 24    345582
Name: 1, dtype: int64
Belmont-North Main 2014 1 24    329928
Name: 1, dtype: int64
Belmont-North Main 2015 1 24    333745
Name: 1, dtype: int64
Belmont-North Main 2016 1 24    335134
Name: 1, dtype: int64
Belmont-North Main 2017 1 24    316250
Name: 1, dtype: int64
Belmont-North Main 2018 1 24    304608
Name: 1, dtype: int64
Belmont-North Main 2019 1 24    280337
Name: 1, dtype: int64
Belmont-North Main 2013 2 24    325056
Name: 2, dtype: int64
Belmont-North Main 2014 2 24    329583
Name: 2, dtype: int64
Belmont-North Main 2015 2 24    316006
Name: 2, dtype: int64
Belmont-North Main 2016 2 24    331005
Name: 2, dtype: int64
Belmont-North Main 2017 2 24    301470
Name: 2, dtype: int64
Belmont-North Main 2018 2 24    287445
Name: 2, dtype: int64
Belmont-North Main 2019 2 24    277879
Name: 2, dtype: int64
Belmont-North Main 2013 3 24    366496
Name: 3, dtype: int64
Belmont-North Main 2014 3 24    381980
Name: 3, dtype: int64
Belmont-North Main 2015 3 24    368575
Name: 3, dtype: int64
Belmont-North Main 2016 3 24    363682
Name: 3, dtype: int64
Belmont-North Main 2017 3 24    342760
Name: 3, dtype: int64
Belmont-North Main 2018 3 24    333666
Name: 3, dtype: int64
Belmont-North Main 2019 3 24    326274
Name: 3, dtype: int64
Belmont-North Main 2013 4 24    366967
Name: 4, dtype: int64
Belmont-North Main 2014 4 24    376939
Name: 4, dtype: int64
Belmont-North Main 2015 4 24    359020
Name: 4, dtype: int64
Belmont-North Main 2016 4 24    356681
Name: 4, dtype: int64
Belmont-North Main 2017 4 24    328117
Name: 4, dtype: int64
Belmont-North Main 2018 4 24    315870
Name: 4, dtype: int64
Belmont-North Main 2019 4 24    314616
Name: 4, dtype: int64
Belmont-North Main 2013 5 24    376755
Name: 5, dtype: int64
Belmont-North Main 2014 5 24    380422
Name: 5, dtype: int64
Belmont-North Main 2015 5 24    372929
Name: 5, dtype: int64
Belmont-North Main 2016 5 24    369825
Name: 5, dtype: int64
Belmont-North Main 2017 5 24    348907
Name: 5, dtype: int64
Belmont-North Main 2018 5 24    338855
Name: 5, dtype: int64
Belmont-North Main 2019 5 24    332989
Name: 5, dtype: int64
Belmont-North Main 2013 6 24    394042
Name: 6, dtype: int64
Belmont-North Main 2014 6 24    393819
Name: 6, dtype: int64
Belmont-North Main 2015 6 24    401544
Name: 6, dtype: int64
Belmont-North Main 2016 6 24    389889
Name: 6, dtype: int64
Belmont-North Main 2017 6 24    374895
Name: 6, dtype: int64
Belmont-North Main 2018 6 24    351294
Name: 6, dtype: int64
Belmont-North Main 2019 6 24    342692
Name: 6, dtype: int64
Belmont-North Main 2013 7 24    375567
Name: 7, dtype: int64
Belmont-North Main 2014 7 24    378332
Name: 7, dtype: int64
Belmont-North Main 2015 7 24    379720
Name: 7, dtype: int64
Belmont-North Main 2016 7 24    364603
Name: 7, dtype: int64
Belmont-North Main 2017 7 24    338792
Name: 7, dtype: int64
Belmont-North Main 2018 7 24    318083
Name: 7, dtype: int64
Belmont-North Main 2019 7 24    314529
Name: 7, dtype: int64
Belmont-North Main 2013 8 24    375214
Name: 8, dtype: int64
Belmont-North Main 2014 8 24    381605
Name: 8, dtype: int64
Belmont-North Main 2015 8 24    376013
Name: 8, dtype: int64
Belmont-North Main 2016 8 24    362552
Name: 8, dtype: int64
Belmont-North Main 2017 8 24    359746
Name: 8, dtype: int64
Belmont-North Main 2018 8 24    0
Name: 8, dtype: int64
Belmont-North Main 2019 8 24    332575
Name: 8, dtype: int64
Belmont-North Main 2013 9 24    378282
Name: 9, dtype: int64
Belmont-North Main 2014 9 24    374350
Name: 9, dtype: int64
Belmont-North Main 2015 9 24    377039
Name: 9, dtype: int64
Belmont-North Main 2016 9 24    358375
Name: 9, dtype: int64
Belmont-North Main 2017 9 24    341277
Name: 9, dtype: int64
Belmont-North Main 2018 9 24    0
Name: 9, dtype: int64
Belmont-North Main 2019 9 24    318995
Name: 9, dtype: int64
Belmont-North Main 2013 10 24    413093
Name: 10, dtype: int64
Belmont-North Main 2014 10 24    407902
Name: 10, dtype: int64
Belmont-North Main 2015 10 24    409118
Name: 10, dtype: int64
Belmont-North Main 2016 10 24    419433
Name: 10, dtype: int64
Belmont-North Main 2017 10 24    370376
Name: 10, dtype: int64
Belmont-North Main 2018 10 24    0
Name: 10, dtype: int64
Belmont-North Main 2019 10 24    348049
Name: 10, dtype: int64
Belmont-North Main 2013 11 24    357346
Name: 11, dtype: int64
Belmont-North Main 2014 11 24    341386
Name: 11, dtype: int64
Belmont-North Main 2015 11 24    340036
Name: 11, dtype: int64
Belmont-North Main 2016 11 24    355052
Name: 11, dtype: int64
Belmont-North Main 2017 11 24    312207
Name: 11, dtype: int64
Belmont-North Main 2018 11 24    0
Name: 11, dtype: int64
Belmont-North Main 2019 11 24    292789
Name: 11, dtype: int64
Belmont-North Main 2013 12 24    313269
Name: 12, dtype: int64
Belmont-North Main 2014 12 24    321622
Name: 12, dtype: int64
Belmont-North Main 2015 12 24    319611
Name: 12, dtype: int64
Belmont-North Main 2016 12 24    288025
Name: 12, dtype: int64
Belmont-North Main 2017 12 24    275590
Name: 12, dtype: int64
Belmont-North Main 2018 12 24    0
Name: 12, dtype: int64
Belmont-North Main 2019 12 24    263441
Name: 12, dtype: int64
Belmont-O'Hare 2013 1 25    134634
Name: 1, dtype: int64
Belmont-O'Hare 2014 1 25    133477
Name: 1, dtype: int64
Belmont-O'Hare 2015 1 25    136454
Name: 1, dtype: int64
Belmont-O'Hare 2016 1 25    137108
Name: 1, dtype: int64
Belmont-O'Hare 2017 1 25    138122
Name: 1, dtype: int64
Belmont-O'Hare 2018 1 25    133570
Name: 1, dtype: int64
Belmont-O'Hare 2019 1 25    106872
Name: 1, dtype: int64
Belmont-O'Hare 2013 2 25    129690
Name: 2, dtype: int64
Belmont-O'Hare 2014 2 25    133910
Name: 2, dtype: int64
Belmont-O'Hare 2015 2 25    132679
Name: 2, dtype: int64
Belmont-O'Hare 2016 2 25    141365
Name: 2, dtype: int64
Belmont-O'Hare 2017 2 25    132607
Name: 2, dtype: int64
Belmont-O'Hare 2018 2 25    128108
Name: 2, dtype: int64
Belmont-O'Hare 2019 2 25    109375
Name: 2, dtype: int64
Belmont-O'Hare 2013 3 25    144245
Name: 3, dtype: int64
Belmont-O'Hare 2014 3 25    145098
Name: 3, dtype: int64
Belmont-O'Hare 2015 3 25    150622
Name: 3, dtype: int64
Belmont-O'Hare 2016 3 25    159850
Name: 3, dtype: int64
Belmont-O'Hare 2017 3 25    150004
Name: 3, dtype: int64
Belmont-O'Hare 2018 3 25    145408
Name: 3, dtype: int64
Belmont-O'Hare 2019 3 25    103811
Name: 3, dtype: int64
Belmont-O'Hare 2013 4 25    145257
Name: 4, dtype: int64
Belmont-O'Hare 2014 4 25    140985
Name: 4, dtype: int64
Belmont-O'Hare 2015 4 25    148741
Name: 4, dtype: int64
Belmont-O'Hare 2016 4 25    152042
Name: 4, dtype: int64
Belmont-O'Hare 2017 4 25    138778
Name: 4, dtype: int64
Belmont-O'Hare 2018 4 25    139983
Name: 4, dtype: int64
Belmont-O'Hare 2019 4 25    122790
Name: 4, dtype: int64
Belmont-O'Hare 2013 5 25    148242
Name: 5, dtype: int64
Belmont-O'Hare 2014 5 25    141363
Name: 5, dtype: int64
Belmont-O'Hare 2015 5 25    147469
Name: 5, dtype: int64
Belmont-O'Hare 2016 5 25    150149
Name: 5, dtype: int64
Belmont-O'Hare 2017 5 25    148248
Name: 5, dtype: int64
Belmont-O'Hare 2018 5 25    146490
Name: 5, dtype: int64
Belmont-O'Hare 2019 5 25    128869
Name: 5, dtype: int64
Belmont-O'Hare 2013 6 25    141042
Name: 6, dtype: int64
Belmont-O'Hare 2014 6 25    136643
Name: 6, dtype: int64
Belmont-O'Hare 2015 6 25    151848
Name: 6, dtype: int64
Belmont-O'Hare 2016 6 25    157293
Name: 6, dtype: int64
Belmont-O'Hare 2017 6 25    149534
Name: 6, dtype: int64
Belmont-O'Hare 2018 6 25    141266
Name: 6, dtype: int64
Belmont-O'Hare 2019 6 25    125162
Name: 6, dtype: int64
Belmont-O'Hare 2013 7 25    145754
Name: 7, dtype: int64
Belmont-O'Hare 2014 7 25    142956
Name: 7, dtype: int64
Belmont-O'Hare 2015 7 25    156478
Name: 7, dtype: int64
Belmont-O'Hare 2016 7 25    150303
Name: 7, dtype: int64
Belmont-O'Hare 2017 7 25    142557
Name: 7, dtype: int64
Belmont-O'Hare 2018 7 25    141369
Name: 7, dtype: int64
Belmont-O'Hare 2019 7 25    131130
Name: 7, dtype: int64
Belmont-O'Hare 2013 8 25    149364
Name: 8, dtype: int64
Belmont-O'Hare 2014 8 25    140183
Name: 8, dtype: int64
Belmont-O'Hare 2015 8 25    150049
Name: 8, dtype: int64
Belmont-O'Hare 2016 8 25    155611
Name: 8, dtype: int64
Belmont-O'Hare 2017 8 25    152680
Name: 8, dtype: int64
Belmont-O'Hare 2018 8 25    0
Name: 8, dtype: int64
Belmont-O'Hare 2019 8 25    130987
Name: 8, dtype: int64
Belmont-O'Hare 2013 9 25    144801
Name: 9, dtype: int64
Belmont-O'Hare 2014 9 25    147075
Name: 9, dtype: int64
Belmont-O'Hare 2015 9 25    154882
Name: 9, dtype: int64
Belmont-O'Hare 2016 9 25    152852
Name: 9, dtype: int64
Belmont-O'Hare 2017 9 25    147498
Name: 9, dtype: int64
Belmont-O'Hare 2018 9 25    0
Name: 9, dtype: int64
Belmont-O'Hare 2019 9 25    126610
Name: 9, dtype: int64
Belmont-O'Hare 2013 10 25    157635
Name: 10, dtype: int64
Belmont-O'Hare 2014 10 25    157299
Name: 10, dtype: int64
Belmont-O'Hare 2015 10 25    161402
Name: 10, dtype: int64
Belmont-O'Hare 2016 10 25    156900
Name: 10, dtype: int64
Belmont-O'Hare 2017 10 25    153576
Name: 10, dtype: int64
Belmont-O'Hare 2018 10 25    0
Name: 10, dtype: int64
Belmont-O'Hare 2019 10 25    137748
Name: 10, dtype: int64
Belmont-O'Hare 2013 11 25    137726
Name: 11, dtype: int64
Belmont-O'Hare 2014 11 25    135508
Name: 11, dtype: int64
Belmont-O'Hare 2015 11 25    144438
Name: 11, dtype: int64
Belmont-O'Hare 2016 11 25    148750
Name: 11, dtype: int64
Belmont-O'Hare 2017 11 25    144908
Name: 11, dtype: int64
Belmont-O'Hare 2018 11 25    0
Name: 11, dtype: int64
Belmont-O'Hare 2019 11 25    122123
Name: 11, dtype: int64
Belmont-O'Hare 2013 12 25    134272
Name: 12, dtype: int64
Belmont-O'Hare 2014 12 25    137562
Name: 12, dtype: int64
Belmont-O'Hare 2015 12 25    142501
Name: 12, dtype: int64
Belmont-O'Hare 2016 12 25    135429
Name: 12, dtype: int64
Belmont-O'Hare 2017 12 25    131331
Name: 12, dtype: int64
Belmont-O'Hare 2018 12 25    0
Name: 12, dtype: int64
Belmont-O'Hare 2019 12 25    114655
Name: 12, dtype: int64
Berwyn 2013 1 26    75593
Name: 1, dtype: int64
Berwyn 2014 1 26    89690
Name: 1, dtype: int64
Berwyn 2015 1 26    92722
Name: 1, dtype: int64
Berwyn 2016 1 26    91004
Name: 1, dtype: int64
Berwyn 2017 1 26    88796
Name: 1, dtype: int64
Berwyn 2018 1 26    84304
Name: 1, dtype: int64
Berwyn 2019 1 26    77873
Name: 1, dtype: int64
Berwyn 2013 2 26    74475
Name: 2, dtype: int64
Berwyn 2014 2 26    90311
Name: 2, dtype: int64
Berwyn 2015 2 26    88323
Name: 2, dtype: int64
Berwyn 2016 2 26    92369
Name: 2, dtype: int64
Berwyn 2017 2 26    85345
Name: 2, dtype: int64
Berwyn 2018 2 26    80688
Name: 2, dtype: int64
Berwyn 2019 2 26    78701
Name: 2, dtype: int64
Berwyn 2013 3 26    81797
Name: 3, dtype: int64
Berwyn 2014 3 26    100207
Name: 3, dtype: int64
Berwyn 2015 3 26    98145
Name: 3, dtype: int64
Berwyn 2016 3 26    96520
Name: 3, dtype: int64
Berwyn 2017 3 26    94273
Name: 3, dtype: int64
Berwyn 2018 3 26    90399
Name: 3, dtype: int64
Berwyn 2019 3 26    86430
Name: 3, dtype: int64
Berwyn 2013 4 26    82339
Name: 4, dtype: int64
Berwyn 2014 4 26    98139
Name: 4, dtype: int64
Berwyn 2015 4 26    97627
Name: 4, dtype: int64
Berwyn 2016 4 26    95844
Name: 4, dtype: int64
Berwyn 2017 4 26    87712
Name: 4, dtype: int64
Berwyn 2018 4 26    86002
Name: 4, dtype: int64
Berwyn 2019 4 26    84096
Name: 4, dtype: int64
Berwyn 2013 5 26    83440
Name: 5, dtype: int64
Berwyn 2014 5 26    98576
Name: 5, dtype: int64
Berwyn 2015 5 26    97262
Name: 5, dtype: int64
Berwyn 2016 5 26    97202
Name: 5, dtype: int64
Berwyn 2017 5 26    91764
Name: 5, dtype: int64
Berwyn 2018 5 26    90448
Name: 5, dtype: int64
Berwyn 2019 5 26    86806
Name: 5, dtype: int64
Berwyn 2013 6 26    89465
Name: 6, dtype: int64
Berwyn 2014 6 26    100527
Name: 6, dtype: int64
Berwyn 2015 6 26    102715
Name: 6, dtype: int64
Berwyn 2016 6 26    102713
Name: 6, dtype: int64
Berwyn 2017 6 26    96843
Name: 6, dtype: int64
Berwyn 2018 6 26    92256
Name: 6, dtype: int64
Berwyn 2019 6 26    87543
Name: 6, dtype: int64
Berwyn 2013 7 26    89640
Name: 7, dtype: int64
Berwyn 2014 7 26    99939
Name: 7, dtype: int64
Berwyn 2015 7 26    103555
Name: 7, dtype: int64
Berwyn 2016 7 26    97900
Name: 7, dtype: int64
Berwyn 2017 7 26    90915
Name: 7, dtype: int64
Berwyn 2018 7 26    88741
Name: 7, dtype: int64
Berwyn 2019 7 26    87095
Name: 7, dtype: int64
Berwyn 2013 8 26    92238
Name: 8, dtype: int64
Berwyn 2014 8 26    99690
Name: 8, dtype: int64
Berwyn 2015 8 26    100852
Name: 8, dtype: int64
Berwyn 2016 8 26    99041
Name: 8, dtype: int64
Berwyn 2017 8 26    95112
Name: 8, dtype: int64
Berwyn 2018 8 26    0
Name: 8, dtype: int64
Berwyn 2019 8 26    88276
Name: 8, dtype: int64
Berwyn 2013 9 26    96075
Name: 9, dtype: int64
Berwyn 2014 9 26    102749
Name: 9, dtype: int64
Berwyn 2015 9 26    102989
Name: 9, dtype: int64
Berwyn 2016 9 26    99419
Name: 9, dtype: int64
Berwyn 2017 9 26    93693
Name: 9, dtype: int64
Berwyn 2018 9 26    0
Name: 9, dtype: int64

Berwyn 2019 9 26    87467
Name: 9, dtype: int64
Berwyn 2013 10 26    99153
Name: 10, dtype: int64
Berwyn 2014 10 26    110857
Name: 10, dtype: int64
Berwyn 2015 10 26    108893
Name: 10, dtype: int64
Berwyn 2016 10 26    104250
Name: 10, dtype: int64
Berwyn 2017 10 26    99962
Name: 10, dtype: int64
Berwyn 2018 10 26    0
Name: 10, dtype: int64
Berwyn 2019 10 26    92648
Name: 10, dtype: int64
Berwyn 2013 11 26    89400
Name: 11, dtype: int64
Berwyn 2014 11 26    96877
Name: 11, dtype: int64
Berwyn 2015 11 26    92775
Name: 11, dtype: int64
Berwyn 2016 11 26    96069
Name: 11, dtype: int64
Berwyn 2017 11 26    89188
Name: 11, dtype: int64
Berwyn 2018 11 26    0
Name: 11, dtype: int64
Berwyn 2019 11 26    82263
Name: 11, dtype: int64
Berwyn 2013 12 26    85998
Name: 12, dtype: int64
Berwyn 2014 12 26    93411
Name: 12, dtype: int64
Berwyn 2015 12 26    92433
Name: 12, dtype: int64
Berwyn 2016 12 26    86930
Name: 12, dtype: int64
Berwyn 2017 12 26    80538
Name: 12, dtype: int64
Berwyn 2018 12 26    0
Name: 12, dtype: int64
Berwyn 2019 12 26    74355
Name: 12, dtype: int64
Bryn Mawr 2013 1 27    126592
Name: 1, dtype: int64
Bryn Mawr 2014 1 27    122657
Name: 1, dtype: int64
Bryn Mawr 2015 1 27    123654
Name: 1, dtype: int64
Bryn Mawr 2016 1 27    124590
Name: 1, dtype: int64
Bryn Mawr 2017 1 27    119519
Name: 1, dtype: int64
Bryn Mawr 2018 1 27    115732
Name: 1, dtype: int64
Bryn Mawr 2019 1 27    109348
Name: 1, dtype: int64
Bryn Mawr 2013 2 27    122324
Name: 2, dtype: int64
Bryn Mawr 2014 2 27    123744
Name: 2, dtype: int64
Bryn Mawr 2015 2 27    118044
Name: 2, dtype: int64
Bryn Mawr 2016 2 27    124895
Name: 2, dtype: int64
Bryn Mawr 2017 2 27    114586
Name: 2, dtype: int64
Bryn Mawr 2018 2 27    110847
Name: 2, dtype: int64
Bryn Mawr 2019 2 27    110474
Name: 2, dtype: int64
Bryn Mawr 2013 3 27    133301
Name: 3, dtype: int64
Bryn Mawr 2014 3 27    138043
Name: 3, dtype: int64
Bryn Mawr 2015 3 27    133499
Name: 3, dtype: int64
Bryn Mawr 2016 3 27    133284
Name: 3, dtype: int64
Bryn Mawr 2017 3 27    127671
Name: 3, dtype: int64
Bryn Mawr 2018 3 27    125066
Name: 3, dtype: int64
Bryn Mawr 2019 3 27    119401
Name: 3, dtype: int64
Bryn Mawr 2013 4 27    134290
Name: 4, dtype: int64
Bryn Mawr 2014 4 27    135302
Name: 4, dtype: int64
Bryn Mawr 2015 4 27    130993
Name: 4, dtype: int64
Bryn Mawr 2016 4 27    131280
Name: 4, dtype: int64
Bryn Mawr 2017 4 27    120433
Name: 4, dtype: int64
Bryn Mawr 2018 4 27    119839
Name: 4, dtype: int64
Bryn Mawr 2019 4 27    118737
Name: 4, dtype: int64
Bryn Mawr 2013 5 27    136141
Name: 5, dtype: int64
Bryn Mawr 2014 5 27    137294
Name: 5, dtype: int64
Bryn Mawr 2015 5 27    132770
Name: 5, dtype: int64
Bryn Mawr 2016 5 27    134409
Name: 5, dtype: int64
Bryn Mawr 2017 5 27    128934
Name: 5, dtype: int64
Bryn Mawr 2018 5 27    128270
Name: 5, dtype: int64
Bryn Mawr 2019 5 27    123947
Name: 5, dtype: int64
Bryn Mawr 2013 6 27    137750
Name: 6, dtype: int64
Bryn Mawr 2014 6 27    135365
Name: 6, dtype: int64
Bryn Mawr 2015 6 27    142328
Name: 6, dtype: int64
Bryn Mawr 2016 6 27    140729
Name: 6, dtype: int64
Bryn Mawr 2017 6 27    133024
Name: 6, dtype: int64
Bryn Mawr 2018 6 27    127502
Name: 6, dtype: int64
Bryn Mawr 2019 6 27    102983
Name: 6, dtype: int64
Bryn Mawr 2013 7 27    142884
Name: 7, dtype: int64
Bryn Mawr 2014 7 27    138765
Name: 7, dtype: int64
Bryn Mawr 2015 7 27    144980
Name: 7, dtype: int64
Bryn Mawr 2016 7 27    135844
Name: 7, dtype: int64
Bryn Mawr 2017 7 27    128559
Name: 7, dtype: int64
Bryn Mawr 2018 7 27    127341
Name: 7, dtype: int64
Bryn Mawr 2019 7 27    116594
Name: 7, dtype: int64
Bryn Mawr 2013 8 27    144255
Name: 8, dtype: int64
Bryn Mawr 2014 8 27    136040
Name: 8, dtype: int64
Bryn Mawr 2015 8 27    139486
Name: 8, dtype: int64
Bryn Mawr 2016 8 27    134391
Name: 8, dtype: int64
Bryn Mawr 2017 8 27    134023
Name: 8, dtype: int64
Bryn Mawr 2018 8 27    0
Name: 8, dtype: int64
Bryn Mawr 2019 8 27    121168
Name: 8, dtype: int64
Bryn Mawr 2013 9 27    138893
Name: 9, dtype: int64
Bryn Mawr 2014 9 27    138811
Name: 9, dtype: int64
Bryn Mawr 2015 9 27    138938
Name: 9, dtype: int64
Bryn Mawr 2016 9 27    132778
Name: 9, dtype: int64
Bryn Mawr 2017 9 27    133103
Name: 9, dtype: int64
Bryn Mawr 2018 9 27    0
Name: 9, dtype: int64
Bryn Mawr 2019 9 27    117764
Name: 9, dtype: int64
Bryn Mawr 2013 10 27    149792
Name: 10, dtype: int64
Bryn Mawr 2014 10 27    145314
Name: 10, dtype: int64
Bryn Mawr 2015 10 27    147248
Name: 10, dtype: int64
Bryn Mawr 2016 10 27    137980
Name: 10, dtype: int64
Bryn Mawr 2017 10 27    135208
Name: 10, dtype: int64
Bryn Mawr 2018 10 27    0
Name: 10, dtype: int64
Bryn Mawr 2019 10 27    129771
Name: 10, dtype: int64
Bryn Mawr 2013 11 27    130240
Name: 11, dtype: int64
Bryn Mawr 2014 11 27    125870
Name: 11, dtype: int64
Bryn Mawr 2015 11 27    127932
Name: 11, dtype: int64
Bryn Mawr 2016 11 27    128773
Name: 11, dtype: int64
Bryn Mawr 2017 11 27    123130
Name: 11, dtype: int64
Bryn Mawr 2018 11 27    0
Name: 11, dtype: int64
Bryn Mawr 2019 11 27    114082
Name: 11, dtype: int64
Bryn Mawr 2013 12 27    121615
Name: 12, dtype: int64
Bryn Mawr 2014 12 27    125077
Name: 12, dtype: int64
Bryn Mawr 2015 12 27    125966
Name: 12, dtype: int64
Bryn Mawr 2016 12 27    116509
Name: 12, dtype: int64
Bryn Mawr 2017 12 27    111423
Name: 12, dtype: int64
Bryn Mawr 2018 12 27    0
Name: 12, dtype: int64
Bryn Mawr 2019 12 27    105937
Name: 12, dtype: int64
California-Cermak 2013 1 28    36328
Name: 1, dtype: int64
California-Cermak 2014 1 28    32578
Name: 1, dtype: int64
California-Cermak 2015 1 28    36387
Name: 1, dtype: int64
California-Cermak 2016 1 28    37797
Name: 1, dtype: int64
California-Cermak 2017 1 28    34797
Name: 1, dtype: int64
California-Cermak 2018 1 28    31829
Name: 1, dtype: int64
California-Cermak 2019 1 28    29369
Name: 1, dtype: int64
California-Cermak 2013 2 28    33987
Name: 2, dtype: int64
California-Cermak 2014 2 28    34417
Name: 2, dtype: int64
California-Cermak 2015 2 28    34805
Name: 2, dtype: int64
California-Cermak 2016 2 28    37779
Name: 2, dtype: int64
California-Cermak 2017 2 28    33314
Name: 2, dtype: int64
California-Cermak 2018 2 28    30958
Name: 2, dtype: int64
California-Cermak 2019 2 28    29824
Name: 2, dtype: int64
California-Cermak 2013 3 28    36582
Name: 3, dtype: int64
California-Cermak 2014 3 28    39056
Name: 3, dtype: int64
California-Cermak 2015 3 28    40988
Name: 3, dtype: int64
California-Cermak 2016 3 28    41236
Name: 3, dtype: int64
California-Cermak 2017 3 28    37401
Name: 3, dtype: int64
California-Cermak 2018 3 28    35080
Name: 3, dtype: int64
California-Cermak 2019 3 28    32861
Name: 3, dtype: int64
California-Cermak 2013 4 28    38152
Name: 4, dtype: int64
California-Cermak 2014 4 28    38766
Name: 4, dtype: int64
California-Cermak 2015 4 28    40403
Name: 4, dtype: int64
California-Cermak 2016 4 28    38927
Name: 4, dtype: int64
California-Cermak 2017 4 28    34734
Name: 4, dtype: int64
California-Cermak 2018 4 28    34426
Name: 4, dtype: int64
California-Cermak 2019 4 28    33408
Name: 4, dtype: int64
California-Cermak 2013 5 28    38976
Name: 5, dtype: int64
California-Cermak 2014 5 28    40311
Name: 5, dtype: int64
California-Cermak 2015 5 28    40983
Name: 5, dtype: int64
California-Cermak 2016 5 28    40434
Name: 5, dtype: int64
California-Cermak 2017 5 28    37886
Name: 5, dtype: int64
California-Cermak 2018 5 28    37375
Name: 5, dtype: int64
California-Cermak 2019 5 28    36988
Name: 5, dtype: int64
California-Cermak 2013 6 28    37005
Name: 6, dtype: int64
California-Cermak 2014 6 28    38505
Name: 6, dtype: int64
California-Cermak 2015 6 28    42202
Name: 6, dtype: int64
California-Cermak 2016 6 28    42281
Name: 6, dtype: int64
California-Cermak 2017 6 28    37365
Name: 6, dtype: int64
California-Cermak 2018 6 28    36799
Name: 6, dtype: int64
California-Cermak 2019 6 28    37789
Name: 6, dtype: int64
California-Cermak 2013 7 28    39833
Name: 7, dtype: int64
California-Cermak 2014 7 28    40349
Name: 7, dtype: int64
California-Cermak 2015 7 28    43517
Name: 7, dtype: int64
California-Cermak 2016 7 28    41371
Name: 7, dtype: int64
California-Cermak 2017 7 28    36202
Name: 7, dtype: int64
California-Cermak 2018 7 28    36312
Name: 7, dtype: int64
California-Cermak 2019 7 28    37319
Name: 7, dtype: int64
California-Cermak 2013 8 28    40447
Name: 8, dtype: int64
California-Cermak 2014 8 28    39827
Name: 8, dtype: int64
California-Cermak 2015 8 28    43029
Name: 8, dtype: int64
California-Cermak 2016 8 28    42145
Name: 8, dtype: int64
California-Cermak 2017 8 28    38521
Name: 8, dtype: int64
California-Cermak 2018 8 28    0
Name: 8, dtype: int64
California-Cermak 2019 8 28    36982
Name: 8, dtype: int64
California-Cermak 2013 9 28    40070
Name: 9, dtype: int64
California-Cermak 2014 9 28    42346
Name: 9, dtype: int64
California-Cermak 2015 9 28    70165
Name: 9, dtype: int64
California-Cermak 2016 9 28    57620
Name: 9, dtype: int64
California-Cermak 2017 9 28    48599
Name: 9, dtype: int64
California-Cermak 2018 9 28    0
Name: 9, dtype: int64
California-Cermak 2019 9 28    50835
Name: 9, dtype: int64
California-Cermak 2013 10 28    42435
Name: 10, dtype: int64
California-Cermak 2014 10 28    45250
Name: 10, dtype: int64
California-Cermak 2015 10 28    47102
Name: 10, dtype: int64
California-Cermak 2016 10 28    42072
Name: 10, dtype: int64
California-Cermak 2017 10 28    38733
Name: 10, dtype: int64
California-Cermak 2018 10 28    0
Name: 10, dtype: int64
California-Cermak 2019 10 28    39550
Name: 10, dtype: int64
California-Cermak 2013 11 28    36886
Name: 11, dtype: int64
California-Cermak 2014 11 28    38473
Name: 11, dtype: int64
California-Cermak 2015 11 28    41073
Name: 11, dtype: int64
California-Cermak 2016 11 28    39454
Name: 11, dtype: int64
California-Cermak 2017 11 28    35053
Name: 11, dtype: int64
California-Cermak 2018 11 28    0
Name: 11, dtype: int64
California-Cermak 2019 11 28    34293
Name: 11, dtype: int64
California-Cermak 2013 12 28    34143
Name: 12, dtype: int64
California-Cermak 2014 12 28    38351
Name: 12, dtype: int64
California-Cermak 2015 12 28    39735
Name: 12, dtype: int64
California-Cermak 2016 12 28    34618
Name: 12, dtype: int64
California-Cermak 2017 12 28    31892
Name: 12, dtype: int64
California-Cermak 2018 12 28    0
Name: 12, dtype: int64
California-Cermak 2019 12 28    32078
Name: 12, dtype: int64
California-Lake 2013 1 29    26446
Name: 1, dtype: int64
California-Lake 2014 1 29    25637
Name: 1, dtype: int64
California-Lake 2015 1 29    27268
Name: 1, dtype: int64
California-Lake 2016 1 29    26653
Name: 1, dtype: int64
California-Lake 2017 1 29    24196
Name: 1, dtype: int64
California-Lake 2018 1 29    23607
Name: 1, dtype: int64
California-Lake 2019 1 29    23068
Name: 1, dtype: int64
California-Lake 2013 2 29    24760
Name: 2, dtype: int64
California-Lake 2014 2 29    26020
Name: 2, dtype: int64
California-Lake 2015 2 29    25348
Name: 2, dtype: int64
California-Lake 2016 2 29    26038
Name: 2, dtype: int64
California-Lake 2017 2 29    23759
Name: 2, dtype: int64
California-Lake 2018 2 29    22544
Name: 2, dtype: int64
California-Lake 2019 2 29    22604
Name: 2, dtype: int64
California-Lake 2013 3 29    26050
Name: 3, dtype: int64
California-Lake 2014 3 29    30416
Name: 3, dtype: int64
California-Lake 2015 3 29    29925
Name: 3, dtype: int64
California-Lake 2016 3 29    29185
Name: 3, dtype: int64
California-Lake 2017 3 29    27089
Name: 3, dtype: int64
California-Lake 2018 3 29    25162
Name: 3, dtype: int64
California-Lake 2019 3 29    25566
Name: 3, dtype: int64

California-Lake 2013 4 29    28142
Name: 4, dtype: int64
California-Lake 2014 4 29    30144
Name: 4, dtype: int64
California-Lake 2015 4 29    30834
Name: 4, dtype: int64
California-Lake 2016 4 29    27007
Name: 4, dtype: int64
California-Lake 2017 4 29    25767
Name: 4, dtype: int64
California-Lake 2018 4 29    25080
Name: 4, dtype: int64
California-Lake 2019 4 29    25979
Name: 4, dtype: int64
California-Lake 2013 5 29    29915
Name: 5, dtype: int64
California-Lake 2014 5 29    31399
Name: 5, dtype: int64
California-Lake 2015 5 29    30861
Name: 5, dtype: int64
California-Lake 2016 5 29    29318
Name: 5, dtype: int64
California-Lake 2017 5 29    27218
Name: 5, dtype: int64
California-Lake 2018 5 29    27512
Name: 5, dtype: int64
California-Lake 2019 5 29    27985
Name: 5, dtype: int64
California-Lake 2013 6 29    28531
Name: 6, dtype: int64
California-Lake 2014 6 29    30954
Name: 6, dtype: int64
California-Lake 2015 6 29    31897
Name: 6, dtype: int64
California-Lake 2016 6 29    30477
Name: 6, dtype: int64
California-Lake 2017 6 29    26572
Name: 6, dtype: int64
California-Lake 2018 6 29    27341
Name: 6, dtype: int64
California-Lake 2019 6 29    26570
Name: 6, dtype: int64
California-Lake 2013 7 29    30036
Name: 7, dtype: int64
California-Lake 2014 7 29    32713
Name: 7, dtype: int64
California-Lake 2015 7 29    34620
Name: 7, dtype: int64
California-Lake 2016 7 29    29991
Name: 7, dtype: int64
California-Lake 2017 7 29    25362
Name: 7, dtype: int64
California-Lake 2018 7 29    28095
Name: 7, dtype: int64
California-Lake 2019 7 29    27232
Name: 7, dtype: int64
California-Lake 2013 8 29    30012
Name: 8, dtype: int64
California-Lake 2014 8 29    32532
Name: 8, dtype: int64
California-Lake 2015 8 29    34882
Name: 8, dtype: int64
California-Lake 2016 8 29    30402
Name: 8, dtype: int64
California-Lake 2017 8 29    27606
Name: 8, dtype: int64
California-Lake 2018 8 29    0
Name: 8, dtype: int64
California-Lake 2019 8 29    27398
Name: 8, dtype: int64
California-Lake 2013 9 29    30925
Name: 9, dtype: int64
California-Lake 2014 9 29    33345
Name: 9, dtype: int64
California-Lake 2015 9 29    33771
Name: 9, dtype: int64
California-Lake 2016 9 29    30499
Name: 9, dtype: int64
California-Lake 2017 9 29    26865
Name: 9, dtype: int64
California-Lake 2018 9 29    0
Name: 9, dtype: int64
California-Lake 2019 9 29    26393
Name: 9, dtype: int64
California-Lake 2013 10 29    32066
Name: 10, dtype: int64
California-Lake 2014 10 29    35311
Name: 10, dtype: int64
California-Lake 2015 10 29    32660
Name: 10, dtype: int64
California-Lake 2016 10 29    30221
Name: 10, dtype: int64
California-Lake 2017 10 29    27642
Name: 10, dtype: int64
California-Lake 2018 10 29    0
Name: 10, dtype: int64
California-Lake 2019 10 29    27853
Name: 10, dtype: int64
California-Lake 2013 11 29    27644
Name: 11, dtype: int64
California-Lake 2014 11 29    28763
Name: 11, dtype: int64
California-Lake 2015 11 29    27548
Name: 11, dtype: int64
California-Lake 2016 11 29    25980
Name: 11, dtype: int64
California-Lake 2017 11 29    25948
Name: 11, dtype: int64
California-Lake 2018 11 29    0
Name: 11, dtype: int64
California-Lake 2019 11 29    23572
Name: 11, dtype: int64
California-Lake 2013 12 29    26797
Name: 12, dtype: int64
California-Lake 2014 12 29    28739
Name: 12, dtype: int64
California-Lake 2015 12 29    27742
Name: 12, dtype: int64
California-Lake 2016 12 29    24196
Name: 12, dtype: int64
California-Lake 2017 12 29    23105
Name: 12, dtype: int64
California-Lake 2018 12 29    0
Name: 12, dtype: int64
California-Lake 2019 12 29    22574
Name: 12, dtype: int64
California/Milwaukee 2013 1 30    123688
Name: 1, dtype: int64
California/Milwaukee 2014 1 30    123674
Name: 1, dtype: int64
California/Milwaukee 2015 1 30    118546
Name: 1, dtype: int64
California/Milwaukee 2016 1 30    126269
Name: 1, dtype: int64
California/Milwaukee 2017 1 30    141838
Name: 1, dtype: int64
California/Milwaukee 2018 1 30    132240
Name: 1, dtype: int64
California/Milwaukee 2019 1 30    125618
Name: 1, dtype: int64
California/Milwaukee 2013 2 30    118457
Name: 2, dtype: int64
California/Milwaukee 2014 2 30    123591
Name: 2, dtype: int64
California/Milwaukee 2015 2 30    115639
Name: 2, dtype: int64
California/Milwaukee 2016 2 30    127980
Name: 2, dtype: int64
California/Milwaukee 2017 2 30    136860
Name: 2, dtype: int64
California/Milwaukee 2018 2 30    126449
Name: 2, dtype: int64
California/Milwaukee 2019 2 30    127605
Name: 2, dtype: int64
California/Milwaukee 2013 3 30    133261
Name: 3, dtype: int64
California/Milwaukee 2014 3 30    132790
Name: 3, dtype: int64
California/Milwaukee 2015 3 30    131772
Name: 3, dtype: int64
California/Milwaukee 2016 3 30    143197
Name: 3, dtype: int64
California/Milwaukee 2017 3 30    147054
Name: 3, dtype: int64
California/Milwaukee 2018 3 30    147627
Name: 3, dtype: int64
California/Milwaukee 2019 3 30    143868
Name: 3, dtype: int64
California/Milwaukee 2013 4 30    133995
Name: 4, dtype: int64
California/Milwaukee 2014 4 30    127760
Name: 4, dtype: int64
California/Milwaukee 2015 4 30    129618
Name: 4, dtype: int64
California/Milwaukee 2016 4 30    135693
Name: 4, dtype: int64
California/Milwaukee 2017 4 30    135388
Name: 4, dtype: int64
California/Milwaukee 2018 4 30    142028
Name: 4, dtype: int64
California/Milwaukee 2019 4 30    143627
Name: 4, dtype: int64
California/Milwaukee 2013 5 30    131138
Name: 5, dtype: int64
California/Milwaukee 2014 5 30    123747
Name: 5, dtype: int64
California/Milwaukee 2015 5 30    129854
Name: 5, dtype: int64
California/Milwaukee 2016 5 30    137912
Name: 5, dtype: int64
California/Milwaukee 2017 5 30    145953
Name: 5, dtype: int64
California/Milwaukee 2018 5 30    148523
Name: 5, dtype: int64
California/Milwaukee 2019 5 30    141833
Name: 5, dtype: int64
California/Milwaukee 2013 6 30    126434
Name: 6, dtype: int64
California/Milwaukee 2014 6 30    120804
Name: 6, dtype: int64
California/Milwaukee 2015 6 30    137971
Name: 6, dtype: int64
California/Milwaukee 2016 6 30    143608
Name: 6, dtype: int64
California/Milwaukee 2017 6 30    150041
Name: 6, dtype: int64
California/Milwaukee 2018 6 30    145527
Name: 6, dtype: int64
California/Milwaukee 2019 6 30    144479
Name: 6, dtype: int64
California/Milwaukee 2013 7 30    132862
Name: 7, dtype: int64
California/Milwaukee 2014 7 30    130367
Name: 7, dtype: int64
California/Milwaukee 2015 7 30    145262
Name: 7, dtype: int64
California/Milwaukee 2016 7 30    140354
Name: 7, dtype: int64
California/Milwaukee 2017 7 30    142965
Name: 7, dtype: int64
California/Milwaukee 2018 7 30    145066
Name: 7, dtype: int64
California/Milwaukee 2019 7 30    148145
Name: 7, dtype: int64
California/Milwaukee 2013 8 30    135005
Name: 8, dtype: int64
California/Milwaukee 2014 8 30    122239
Name: 8, dtype: int64
California/Milwaukee 2015 8 30    139928
Name: 8, dtype: int64
California/Milwaukee 2016 8 30    141842
Name: 8, dtype: int64
California/Milwaukee 2017 8 30    154337
Name: 8, dtype: int64
California/Milwaukee 2018 8 30    0
Name: 8, dtype: int64
California/Milwaukee 2019 8 30    153338
Name: 8, dtype: int64
California/Milwaukee 2013 9 30    138437
Name: 9, dtype: int64
California/Milwaukee 2014 9 30    11664
Name: 9, dtype: int64
California/Milwaukee 2015 9 30    143511
Name: 9, dtype: int64
California/Milwaukee 2016 9 30    142612
Name: 9, dtype: int64
California/Milwaukee 2017 9 30    152526
Name: 9, dtype: int64
California/Milwaukee 2018 9 30    0
Name: 9, dtype: int64
California/Milwaukee 2019 9 30    148738
Name: 9, dtype: int64
California/Milwaukee 2013 10 30    147439
Name: 10, dtype: int64
California/Milwaukee 2014 10 30    63413
Name: 10, dtype: int64
California/Milwaukee 2015 10 30    150836
Name: 10, dtype: int64
California/Milwaukee 2016 10 30    148463
Name: 10, dtype: int64
California/Milwaukee 2017 10 30    153680
Name: 10, dtype: int64
California/Milwaukee 2018 10 30    0
Name: 10, dtype: int64
California/Milwaukee 2019 10 30    161477
Name: 10, dtype: int64
California/Milwaukee 2013 11 30    132193
Name: 11, dtype: int64
California/Milwaukee 2014 11 30    113194
Name: 11, dtype: int64
California/Milwaukee 2015 11 30    131596
Name: 11, dtype: int64
California/Milwaukee 2016 11 30    139381
Name: 11, dtype: int64
California/Milwaukee 2017 11 30    140407
Name: 11, dtype: int64
California/Milwaukee 2018 11 30    0
Name: 11, dtype: int64
California/Milwaukee 2019 11 30    137026
Name: 11, dtype: int64
California/Milwaukee 2013 12 30    122427
Name: 12, dtype: int64
California/Milwaukee 2014 12 30    116314
Name: 12, dtype: int64
California/Milwaukee 2015 12 30    130266
Name: 12, dtype: int64
California/Milwaukee 2016 12 30    126315
Name: 12, dtype: int64
California/Milwaukee 2017 12 30    126594
Name: 12, dtype: int64
California/Milwaukee 2018 12 30    0
Name: 12, dtype: int64
California/Milwaukee 2019 12 30    126708
Name: 12, dtype: int64
Central Park 2013 1 31    32141
Name: 1, dtype: int64
Central Park 2014 1 31    29552
Name: 1, dtype: int64
Central Park 2015 1 31    32354
Name: 1, dtype: int64
Central Park 2016 1 31    31931
Name: 1, dtype: int64
Central Park 2017 1 31    27836
Name: 1, dtype: int64
Central Park 2018 1 31    27261
Name: 1, dtype: int64
Central Park 2019 1 31    25254
Name: 1, dtype: int64
Central Park 2013 2 31    29608
Name: 2, dtype: int64
Central Park 2014 2 31    30788
Name: 2, dtype: int64
Central Park 2015 2 31    30466
Name: 2, dtype: int64
Central Park 2016 2 31    32114
Name: 2, dtype: int64
Central Park 2017 2 31    27686
Name: 2, dtype: int64
Central Park 2018 2 31    26747
Name: 2, dtype: int64
Central Park 2019 2 31    25471
Name: 2, dtype: int64
Central Park 2013 3 31    32064
Name: 3, dtype: int64
Central Park 2014 3 31    34429
Name: 3, dtype: int64
Central Park 2015 3 31    35897
Name: 3, dtype: int64
Central Park 2016 3 31    33607
Name: 3, dtype: int64
Central Park 2017 3 31    29865
Name: 3, dtype: int64
Central Park 2018 3 31    29454
Name: 3, dtype: int64
Central Park 2019 3 31    27525
Name: 3, dtype: int64
Central Park 2013 4 31    34802
Name: 4, dtype: int64
Central Park 2014 4 31    33041
Name: 4, dtype: int64
Central Park 2015 4 31    35578
Name: 4, dtype: int64
Central Park 2016 4 31    30327
Name: 4, dtype: int64
Central Park 2017 4 31    27124
Name: 4, dtype: int64
Central Park 2018 4 31    28937
Name: 4, dtype: int64
Central Park 2019 4 31    27845
Name: 4, dtype: int64
Central Park 2013 5 31    34745
Name: 5, dtype: int64
Central Park 2014 5 31    34694
Name: 5, dtype: int64
Central Park 2015 5 31    34940
Name: 5, dtype: int64
Central Park 2016 5 31    31838
Name: 5, dtype: int64
Central Park 2017 5 31    30529
Name: 5, dtype: int64
Central Park 2018 5 31    31066
Name: 5, dtype: int64
Central Park 2019 5 31    29417
Name: 5, dtype: int64
Central Park 2013 6 31    33384
Name: 6, dtype: int64
Central Park 2014 6 31    34297
Name: 6, dtype: int64
Central Park 2015 6 31    36124
Name: 6, dtype: int64
Central Park 2016 6 31    32551
Name: 6, dtype: int64
Central Park 2017 6 31    31321
Name: 6, dtype: int64
Central Park 2018 6 31    31158
Name: 6, dtype: int64
Central Park 2019 6 31    28680
Name: 6, dtype: int64
Central Park 2013 7 31    36234
Name: 7, dtype: int64
Central Park 2014 7 31    37089
Name: 7, dtype: int64
Central Park 2015 7 31    37121
Name: 7, dtype: int64
Central Park 2016 7 31    32735
Name: 7, dtype: int64
Central Park 2017 7 31    31224
Name: 7, dtype: int64
Central Park 2018 7 31    31758
Name: 7, dtype: int64
Central Park 2019 7 31    30341
Name: 7, dtype: int64
Central Park 2013 8 31    36371
Name: 8, dtype: int64
Central Park 2014 8 31    35785
Name: 8, dtype: int64
Central Park 2015 8 31    35879
Name: 8, dtype: int64
Central Park 2016 8 31    32641
Name: 8, dtype: int64
Central Park 2017 8 31    32197
Name: 8, dtype: int64
Central Park 2018 8 31    0
Name: 8, dtype: int64
Central Park 2019 8 31    30156
Name: 8, dtype: int64
Central Park 2013 9 31    36562
Name: 9, dtype: int64
Central Park 2014 9 31    38821
Name: 9, dtype: int64
Central Park 2015 9 31    38634
Name: 9, dtype: int64
Central Park 2016 9 31    33377
Name: 9, dtype: int64
Central Park 2017 9 31    32370
Name: 9, dtype: int64
Central Park 2018 9 31    0
Name: 9, dtype: int64
Central Park 2019 9 31    31159
Name: 9, dtype: int64
Central Park 2013 10 31    38708
Name: 10, dtype: int64
Central Park 2014 10 31    40903
Name: 10, dtype: int64
Central Park 2015 10 31    39824
Name: 10, dtype: int64
Central Park 2016 10 31    33596
Name: 10, dtype: int64
Central Park 2017 10 31    33149
Name: 10, dtype: int64
Central Park 2018 10 31    0
Name: 10, dtype: int64
Central Park 2019 10 31    32045
Name: 10, dtype: int64
Central Park 2013 11 31    33055
Name: 11, dtype: int64
Central Park 2014 11 31    33728
Name: 11, dtype: int64
Central Park 2015 11 31    34868
Name: 11, dtype: int64
Central Park 2016 11 31    31490
Name: 11, dtype: int64
Central Park 2017 11 31    30431
Name: 11, dtype: int64
Central Park 2018 11 31    0
Name: 11, dtype: int64
Central Park 2019 11 31    28042
Name: 11, dtype: int64
Central Park 2013 12 31    30595
Name: 12, dtype: int64
Central Park 2014 12 31    34623
Name: 12, dtype: int64
Central Park 2015 12 31    33985
Name: 12, dtype: int64
Central Park 2016 12 31    27880
Name: 12, dtype: int64
Central Park 2017 12 31    27678
Name: 12, dtype: int64
Central Park 2018 12 31    0
Name: 12, dtype: int64
Central Park 2019 12 31    27211
Name: 12, dtype: int64
Central-Evanston 2013 1 32    20973
Name: 1, dtype: int64
Central-Evanston 2014 1 32    20504
Name: 1, dtype: int64
Central-Evanston 2015 1 32    19533
Name: 1, dtype: int64
Central-Evanston 2016 1 32    18522
Name: 1, dtype: int64
Central-Evanston 2017 1 32    18969
Name: 1, dtype: int64
Central-Evanston 2018 1 32    17477
Name: 1, dtype: int64
Central-Evanston 2019 1 32    17266
Name: 1, dtype: int64
Central-Evanston 2013 2 32    19263
Name: 2, dtype: int64
Central-Evanston 2014 2 32    18563
Name: 2, dtype: int64
Central-Evanston 2015 2 32    18818
Name: 2, dtype: int64
Central-Evanston 2016 2 32    18288
Name: 2, dtype: int64
Central-Evanston 2017 2 32    17828
Name: 2, dtype: int64
Central-Evanston 2018 2 32    17011
Name: 2, dtype: int64
Central-Evanston 2019 2 32    17013
Name: 2, dtype: int64
Central-Evanston 2013 3 32    18994
Name: 3, dtype: int64
Central-Evanston 2014 3 32    19967
Name: 3, dtype: int64
Central-Evanston 2015 3 32    20219
Name: 3, dtype: int64
Central-Evanston 2016 3 32    20030
Name: 3, dtype: int64
Central-Evanston 2017 3 32    20067
Name: 3, dtype: int64
Central-Evanston 2018 3 32    18399
Name: 3, dtype: int64
Central-Evanston 2019 3 32    17867
Name: 3, dtype: int64
Central-Evanston 2013 4 32    20399
Name: 4, dtype: int64
Central-Evanston 2014 4 32    20620
Name: 4, dtype: int64
Central-Evanston 2015 4 32    19562
Name: 4, dtype: int64
Central-Evanston 2016 4 32    19386
Name: 4, dtype: int64
Central-Evanston 2017 4 32    18332
Name: 4, dtype: int64
Central-Evanston 2018 4 32    18046
Name: 4, dtype: int64
Central-Evanston 2019 4 32    18442
Name: 4, dtype: int64
Central-Evanston 2013 5 32    21170
Name: 5, dtype: int64
Central-Evanston 2014 5 32    20883
Name: 5, dtype: int64
Central-Evanston 2015 5 32    18952
Name: 5, dtype: int64
Central-Evanston 2016 5 32    20598
Name: 5, dtype: int64
Central-Evanston 2017 5 32    20061
Name: 5, dtype: int64
Central-Evanston 2018 5 32    19881
Name: 5, dtype: int64
Central-Evanston 2019 5 32    19237
Name: 5, dtype: int64
Central-Evanston 2013 6 32    21888
Name: 6, dtype: int64
Central-Evanston 2014 6 32    22233
Name: 6, dtype: int64
Central-Evanston 2015 6 32    22418
Name: 6, dtype: int64
Central-Evanston 2016 6 32    23745
Name: 6, dtype: int64
Central-Evanston 2017 6 32    22857
Name: 6, dtype: int64
Central-Evanston 2018 6 32    21035
Name: 6, dtype: int64
Central-Evanston 2019 6 32    20461
Name: 6, dtype: int64
Central-Evanston 2013 7 32    23229
Name: 7, dtype: int64
Central-Evanston 2014 7 32    23012
Name: 7, dtype: int64
Central-Evanston 2015 7 32    23472
Name: 7, dtype: int64
Central-Evanston 2016 7 32    23027
Name: 7, dtype: int64
Central-Evanston 2017 7 32    21393
Name: 7, dtype: int64
Central-Evanston 2018 7 32    21238
Name: 7, dtype: int64
Central-Evanston 2019 7 32    20920

Name: 7, dtype: int64
Central-Evanston 2013 8 32    22709
Name: 8, dtype: int64
Central-Evanston 2014 8 32    23639
Name: 8, dtype: int64
Central-Evanston 2015 8 32    22589
Name: 8, dtype: int64
Central-Evanston 2016 8 32    22919
Name: 8, dtype: int64
Central-Evanston 2017 8 32    23206
Name: 8, dtype: int64
Central-Evanston 2018 8 32    0
Name: 8, dtype: int64
Central-Evanston 2019 8 32    22151
Name: 8, dtype: int64
Central-Evanston 2013 9 32    24828
Name: 9, dtype: int64
Central-Evanston 2014 9 32    23960
Name: 9, dtype: int64
Central-Evanston 2015 9 32    25892
Name: 9, dtype: int64
Central-Evanston 2016 9 32    28491
Name: 9, dtype: int64
Central-Evanston 2017 9 32    22145
Name: 9, dtype: int64
Central-Evanston 2018 9 32    0
Name: 9, dtype: int64
Central-Evanston 2019 9 32    23020
Name: 9, dtype: int64
Central-Evanston 2013 10 32    28948
Name: 10, dtype: int64
Central-Evanston 2014 10 32    29776
Name: 10, dtype: int64
Central-Evanston 2015 10 32    27509
Name: 10, dtype: int64
Central-Evanston 2016 10 32    24755
Name: 10, dtype: int64
Central-Evanston 2017 10 32    29877
Name: 10, dtype: int64
Central-Evanston 2018 10 32    0
Name: 10, dtype: int64
Central-Evanston 2019 10 32    29524
Name: 10, dtype: int64
Central-Evanston 2013 11 32    27623
Name: 11, dtype: int64
Central-Evanston 2014 11 32    22672
Name: 11, dtype: int64
Central-Evanston 2015 11 32    22323
Name: 11, dtype: int64
Central-Evanston 2016 11 32    24383
Name: 11, dtype: int64
Central-Evanston 2017 11 32    20279
Name: 11, dtype: int64
Central-Evanston 2018 11 32    0
Name: 11, dtype: int64
Central-Evanston 2019 11 32    20604
Name: 11, dtype: int64
Central-Evanston 2013 12 32    18669
Name: 12, dtype: int64
Central-Evanston 2014 12 32    19653
Name: 12, dtype: int64
Central-Evanston 2015 12 32    19230
Name: 12, dtype: int64
Central-Evanston 2016 12 32    18289
Name: 12, dtype: int64
Central-Evanston 2017 12 32    16380
Name: 12, dtype: int64
Central-Evanston 2018 12 32    0
Name: 12, dtype: int64
Central-Evanston 2019 12 32    17059
Name: 12, dtype: int64
Central-Lake 2013 1 33    59576
Name: 1, dtype: int64
Central-Lake 2014 1 33    54043
Name: 1, dtype: int64
Central-Lake 2015 1 33    56420
Name: 1, dtype: int64
Central-Lake 2016 1 33    55626
Name: 1, dtype: int64
Central-Lake 2017 1 33    50465
Name: 1, dtype: int64
Central-Lake 2018 1 33    48463
Name: 1, dtype: int64
Central-Lake 2019 1 33    43549
Name: 1, dtype: int64
Central-Lake 2013 2 33    55229
Name: 2, dtype: int64
Central-Lake 2014 2 33    55644
Name: 2, dtype: int64
Central-Lake 2015 2 33    53096
Name: 2, dtype: int64
Central-Lake 2016 2 33    54572
Name: 2, dtype: int64
Central-Lake 2017 2 33    50286
Name: 2, dtype: int64
Central-Lake 2018 2 33    46208
Name: 2, dtype: int64
Central-Lake 2019 2 33    43185
Name: 2, dtype: int64
Central-Lake 2013 3 33    58323
Name: 3, dtype: int64
Central-Lake 2014 3 33    63655
Name: 3, dtype: int64
Central-Lake 2015 3 33    63284
Name: 3, dtype: int64
Central-Lake 2016 3 33    59169
Name: 3, dtype: int64
Central-Lake 2017 3 33    53950
Name: 3, dtype: int64
Central-Lake 2018 3 33    52853
Name: 3, dtype: int64
Central-Lake 2019 3 33    47782
Name: 3, dtype: int64
Central-Lake 2013 4 33    60740
Name: 4, dtype: int64
Central-Lake 2014 4 33    61331
Name: 4, dtype: int64
Central-Lake 2015 4 33    62667
Name: 4, dtype: int64
Central-Lake 2016 4 33    45012
Name: 4, dtype: int64
Central-Lake 2017 4 33    49542
Name: 4, dtype: int64
Central-Lake 2018 4 33    50732
Name: 4, dtype: int64
Central-Lake 2019 4 33    48804
Name: 4, dtype: int64
Central-Lake 2013 5 33    63930
Name: 5, dtype: int64
Central-Lake 2014 5 33    65042
Name: 5, dtype: int64
Central-Lake 2015 5 33    65123
Name: 5, dtype: int64
Central-Lake 2016 5 33    47189
Name: 5, dtype: int64
Central-Lake 2017 5 33    53447
Name: 5, dtype: int64
Central-Lake 2018 5 33    55896
Name: 5, dtype: int64
Central-Lake 2019 5 33    52082
Name: 5, dtype: int64
Central-Lake 2013 6 33    60655
Name: 6, dtype: int64
Central-Lake 2014 6 33    60299
Name: 6, dtype: int64
Central-Lake 2015 6 33    65739
Name: 6, dtype: int64
Central-Lake 2016 6 33    55838
Name: 6, dtype: int64
Central-Lake 2017 6 33    54141
Name: 6, dtype: int64
Central-Lake 2018 6 33    53419
Name: 6, dtype: int64
Central-Lake 2019 6 33    50174
Name: 6, dtype: int64
Central-Lake 2013 7 33    62875
Name: 7, dtype: int64
Central-Lake 2014 7 33    64082
Name: 7, dtype: int64
Central-Lake 2015 7 33    66519
Name: 7, dtype: int64
Central-Lake 2016 7 33    55424
Name: 7, dtype: int64
Central-Lake 2017 7 33    52927
Name: 7, dtype: int64
Central-Lake 2018 7 33    54468
Name: 7, dtype: int64
Central-Lake 2019 7 33    52442
Name: 7, dtype: int64
Central-Lake 2013 8 33    63491
Name: 8, dtype: int64
Central-Lake 2014 8 33    61893
Name: 8, dtype: int64
Central-Lake 2015 8 33    63196
Name: 8, dtype: int64
Central-Lake 2016 8 33    55569
Name: 8, dtype: int64
Central-Lake 2017 8 33    52848
Name: 8, dtype: int64
Central-Lake 2018 8 33    0
Name: 8, dtype: int64
Central-Lake 2019 8 33    52226
Name: 8, dtype: int64
Central-Lake 2013 9 33    61777
Name: 9, dtype: int64
Central-Lake 2014 9 33    66948
Name: 9, dtype: int64
Central-Lake 2015 9 33    65342
Name: 9, dtype: int64
Central-Lake 2016 9 33    56051
Name: 9, dtype: int64
Central-Lake 2017 9 33    51814
Name: 9, dtype: int64
Central-Lake 2018 9 33    0
Name: 9, dtype: int64
Central-Lake 2019 9 33    52309
Name: 9, dtype: int64
Central-Lake 2013 10 33    67072
Name: 10, dtype: int64
Central-Lake 2014 10 33    70401
Name: 10, dtype: int64
Central-Lake 2015 10 33    67980
Name: 10, dtype: int64
Central-Lake 2016 10 33    57862
Name: 10, dtype: int64
Central-Lake 2017 10 33    54772
Name: 10, dtype: int64
Central-Lake 2018 10 33    0
Name: 10, dtype: int64
Central-Lake 2019 10 33    54544
Name: 10, dtype: int64
Central-Lake 2013 11 33    58183
Name: 11, dtype: int64
Central-Lake 2014 11 33    59265
Name: 11, dtype: int64
Central-Lake 2015 11 33    60667
Name: 11, dtype: int64
Central-Lake 2016 11 33    54835
Name: 11, dtype: int64
Central-Lake 2017 11 33    50127
Name: 11, dtype: int64
Central-Lake 2018 11 33    0
Name: 11, dtype: int64
Central-Lake 2019 11 33    48061
Name: 11, dtype: int64
Central-Lake 2013 12 33    57961
Name: 12, dtype: int64
Central-Lake 2014 12 33    61605
Name: 12, dtype: int64
Central-Lake 2015 12 33    60911
Name: 12, dtype: int64
Central-Lake 2016 12 33    50554
Name: 12, dtype: int64
Central-Lake 2017 12 33    47927
Name: 12, dtype: int64
Central-Lake 2018 12 33    0
Name: 12, dtype: int64
Central-Lake 2019 12 33    47491
Name: 12, dtype: int64
Cermak-Chinatown 2013 1 34    112723
Name: 1, dtype: int64
Cermak-Chinatown 2014 1 34    93452
Name: 1, dtype: int64
Cermak-Chinatown 2015 1 34    109500
Name: 1, dtype: int64
Cermak-Chinatown 2016 1 34    106076
Name: 1, dtype: int64
Cermak-Chinatown 2017 1 34    104997
Name: 1, dtype: int64
Cermak-Chinatown 2018 1 34    96600
Name: 1, dtype: int64
Cermak-Chinatown 2019 1 34    88375
Name: 1, dtype: int64
Cermak-Chinatown 2013 2 34    113139
Name: 2, dtype: int64
Cermak-Chinatown 2014 2 34    103174
Name: 2, dtype: int64
Cermak-Chinatown 2015 2 34    102624
Name: 2, dtype: int64
Cermak-Chinatown 2016 2 34    116495
Name: 2, dtype: int64
Cermak-Chinatown 2017 2 34    110411
Name: 2, dtype: int64
Cermak-Chinatown 2018 2 34    100514
Name: 2, dtype: int64
Cermak-Chinatown 2019 2 34    98380
Name: 2, dtype: int64
Cermak-Chinatown 2013 3 34    135445
Name: 3, dtype: int64
Cermak-Chinatown 2014 3 34    127931
Name: 3, dtype: int64
Cermak-Chinatown 2015 3 34    127642
Name: 3, dtype: int64
Cermak-Chinatown 2016 3 34    132406
Name: 3, dtype: int64
Cermak-Chinatown 2017 3 34    123194
Name: 3, dtype: int64
Cermak-Chinatown 2018 3 34    123345
Name: 3, dtype: int64
Cermak-Chinatown 2019 3 34    117745
Name: 3, dtype: int64
Cermak-Chinatown 2013 4 34    127308
Name: 4, dtype: int64
Cermak-Chinatown 2014 4 34    127973
Name: 4, dtype: int64
Cermak-Chinatown 2015 4 34    124148
Name: 4, dtype: int64
Cermak-Chinatown 2016 4 34    124600
Name: 4, dtype: int64
Cermak-Chinatown 2017 4 34    124275
Name: 4, dtype: int64
Cermak-Chinatown 2018 4 34    113032
Name: 4, dtype: int64
Cermak-Chinatown 2019 4 34    112606
Name: 4, dtype: int64
Cermak-Chinatown 2013 5 34    80328
Name: 5, dtype: int64
Cermak-Chinatown 2014 5 34    138958
Name: 5, dtype: int64
Cermak-Chinatown 2015 5 34    134047
Name: 5, dtype: int64
Cermak-Chinatown 2016 5 34    136182
Name: 5, dtype: int64
Cermak-Chinatown 2017 5 34    130166
Name: 5, dtype: int64
Cermak-Chinatown 2018 5 34    126955
Name: 5, dtype: int64
Cermak-Chinatown 2019 5 34    130179
Name: 5, dtype: int64
Cermak-Chinatown 2013 6 34    0
Name: 6, dtype: int64
Cermak-Chinatown 2014 6 34    132297
Name: 6, dtype: int64
Cermak-Chinatown 2015 6 34    130473
Name: 6, dtype: int64
Cermak-Chinatown 2016 6 34    130511
Name: 6, dtype: int64
Cermak-Chinatown 2017 6 34    134447
Name: 6, dtype: int64
Cermak-Chinatown 2018 6 34    130680
Name: 6, dtype: int64
Cermak-Chinatown 2019 6 34    132660
Name: 6, dtype: int64
Cermak-Chinatown 2013 7 34    0
Name: 7, dtype: int64
Cermak-Chinatown 2014 7 34    140934
Name: 7, dtype: int64
Cermak-Chinatown 2015 7 34    144368
Name: 7, dtype: int64
Cermak-Chinatown 2016 7 34    142898
Name: 7, dtype: int64
Cermak-Chinatown 2017 7 34    140057
Name: 7, dtype: int64
Cermak-Chinatown 2018 7 34    136742
Name: 7, dtype: int64
Cermak-Chinatown 2019 7 34    130094
Name: 7, dtype: int64
Cermak-Chinatown 2013 8 34    0
Name: 8, dtype: int64
Cermak-Chinatown 2014 8 34    144120
Name: 8, dtype: int64
Cermak-Chinatown 2015 8 34    137822
Name: 8, dtype: int64
Cermak-Chinatown 2016 8 34    133917
Name: 8, dtype: int64
Cermak-Chinatown 2017 8 34    137975
Name: 8, dtype: int64
Cermak-Chinatown 2018 8 34    0
Name: 8, dtype: int64

Cermak-Chinatown 2019 8 34    136010
Name: 8, dtype: int64
Cermak-Chinatown 2013 9 34    41218
Name: 9, dtype: int64
Cermak-Chinatown 2014 9 34    145445
Name: 9, dtype: int64
Cermak-Chinatown 2015 9 34    140736
Name: 9, dtype: int64
Cermak-Chinatown 2016 9 34    142186
Name: 9, dtype: int64
Cermak-Chinatown 2017 9 34    140685
Name: 9, dtype: int64
Cermak-Chinatown 2018 9 34    0
Name: 9, dtype: int64
Cermak-Chinatown 2019 9 34    134786
Name: 9, dtype: int64
Cermak-Chinatown 2013 10 34    111834
Name: 10, dtype: int64
Cermak-Chinatown 2014 10 34    156724
Name: 10, dtype: int64
Cermak-Chinatown 2015 10 34    153844
Name: 10, dtype: int64
Cermak-Chinatown 2016 10 34    151622
Name: 10, dtype: int64
Cermak-Chinatown 2017 10 34    144269
Name: 10, dtype: int64
Cermak-Chinatown 2018 10 34    0
Name: 10, dtype: int64
Cermak-Chinatown 2019 10 34    149239
Name: 10, dtype: int64
Cermak-Chinatown 2013 11 34    101804
Name: 11, dtype: int64
Cermak-Chinatown 2014 11 34    133028
Name: 11, dtype: int64
Cermak-Chinatown 2015 11 34    127860
Name: 11, dtype: int64
Cermak-Chinatown 2016 11 34    129360
Name: 11, dtype: int64
Cermak-Chinatown 2017 11 34    119110
Name: 11, dtype: int64
Cermak-Chinatown 2018 11 34    0
Name: 11, dtype: int64
Cermak-Chinatown 2019 11 34    117348
Name: 11, dtype: int64
Cermak-Chinatown 2013 12 34    0
Name: 12, dtype: int64
Cermak-Chinatown 2014 12 34    123552
Name: 12, dtype: int64
Cermak-Chinatown 2015 12 34    114753
Name: 12, dtype: int64
Cermak-Chinatown 2016 12 34    102997
Name: 12, dtype: int64
Cermak-Chinatown 2017 12 34    100021
Name: 12, dtype: int64
Cermak-Chinatown 2018 12 34    0
Name: 12, dtype: int64
Cermak-Chinatown 2019 12 34    108837
Name: 12, dtype: int64
Cermak-McCormick Place 2013 1 Series([], Name: 1, dtype: int64)
Cermak-McCormick Place 2014 1 Series([], Name: 1, dtype: int64)
Cermak-McCormick Place 2015 1 35    0
Name: 1, dtype: int64
Cermak-McCormick Place 2016 1 35    27315
Name: 1, dtype: int64
Cermak-McCormick Place 2017 1 35    30873
Name: 1, dtype: int64
Cermak-McCormick Place 2018 1 35    33352
Name: 1, dtype: int64
Cermak-McCormick Place 2019 1 35    32751
Name: 1, dtype: int64
Cermak-McCormick Place 2013 2 Series([], Name: 2, dtype: int64)
Cermak-McCormick Place 2014 2 Series([], Name: 2, dtype: int64)
Cermak-McCormick Place 2015 2 35    18718
Name: 2, dtype: int64
Cermak-McCormick Place 2016 2 35    33846
Name: 2, dtype: int64
Cermak-McCormick Place 2017 2 35    34979
Name: 2, dtype: int64
Cermak-McCormick Place 2018 2 35    35033
Name: 2, dtype: int64
Cermak-McCormick Place 2019 2 35    39826
Name: 2, dtype: int64
Cermak-McCormick Place 2013 3 Series([], Name: 3, dtype: int64)
Cermak-McCormick Place 2014 3 Series([], Name: 3, dtype: int64)
Cermak-McCormick Place 2015 3 35    27922
Name: 3, dtype: int64
Cermak-McCormick Place 2016 3 35    39122
Name: 3, dtype: int64
Cermak-McCormick Place 2017 3 35    34577
Name: 3, dtype: int64
Cermak-McCormick Place 2018 3 35    41248
Name: 3, dtype: int64
Cermak-McCormick Place 2019 3 35    48040
Name: 3, dtype: int64
Cermak-McCormick Place 2013 4 Series([], Name: 4, dtype: int64)
Cermak-McCormick Place 2014 4 Series([], Name: 4, dtype: int64)
Cermak-McCormick Place 2015 4 35    31403
Name: 4, dtype: int64
Cermak-McCormick Place 2016 4 35    36811
Name: 4, dtype: int64
Cermak-McCormick Place 2017 4 35    40963
Name: 4, dtype: int64
Cermak-McCormick Place 2018 4 35    39646
Name: 4, dtype: int64
Cermak-McCormick Place 2019 4 35    55087
Name: 4, dtype: int64
Cermak-McCormick Place 2013 5 Series([], Name: 5, dtype: int64)
Cermak-McCormick Place 2014 5 Series([], Name: 5, dtype: int64)
Cermak-McCormick Place 2015 5 35    36808
Name: 5, dtype: int64
Cermak-McCormick Place 2016 5 35    37837
Name: 5, dtype: int64
Cermak-McCormick Place 2017 5 35    38932
Name: 5, dtype: int64
Cermak-McCormick Place 2018 5 35    45292
Name: 5, dtype: int64
Cermak-McCormick Place 2019 5 35    51350
Name: 5, dtype: int64
Cermak-McCormick Place 2013 6 Series([], Name: 6, dtype: int64)
Cermak-McCormick Place 2014 6 Series([], Name: 6, dtype: int64)
Cermak-McCormick Place 2015 6 35    36502
Name: 6, dtype: int64
Cermak-McCormick Place 2016 6 35    39568
Name: 6, dtype: int64
Cermak-McCormick Place 2017 6 35    44372
Name: 6, dtype: int64
Cermak-McCormick Place 2018 6 35    49832
Name: 6, dtype: int64
Cermak-McCormick Place 2019 6 35    50077
Name: 6, dtype: int64
Cermak-McCormick Place 2013 7 Series([], Name: 7, dtype: int64)
Cermak-McCormick Place 2014 7 Series([], Name: 7, dtype: int64)
Cermak-McCormick Place 2015 7 35    43932
Name: 7, dtype: int64
Cermak-McCormick Place 2016 7 35    41356
Name: 7, dtype: int64
Cermak-McCormick Place 2017 7 35    39590
Name: 7, dtype: int64
Cermak-McCormick Place 2018 7 35    48129
Name: 7, dtype: int64
Cermak-McCormick Place 2019 7 35    51529
Name: 7, dtype: int64
Cermak-McCormick Place 2013 8 Series([], Name: 8, dtype: int64)
Cermak-McCormick Place 2014 8 Series([], Name: 8, dtype: int64)
Cermak-McCormick Place 2015 8 35    36912
Name: 8, dtype: int64
Cermak-McCormick Place 2016 8 35    37642
Name: 8, dtype: int64
Cermak-McCormick Place 2017 8 35    39946
Name: 8, dtype: int64
Cermak-McCormick Place 2018 8 35    0
Name: 8, dtype: int64
Cermak-McCormick Place 2019 8 35    52014
Name: 8, dtype: int64
Cermak-McCormick Place 2013 9 Series([], Name: 9, dtype: int64)
Cermak-McCormick Place 2014 9 Series([], Name: 9, dtype: int64)
Cermak-McCormick Place 2015 9 35    39633
Name: 9, dtype: int64
Cermak-McCormick Place 2016 9 35    41394
Name: 9, dtype: int64
Cermak-McCormick Place 2017 9 35    43782
Name: 9, dtype: int64
Cermak-McCormick Place 2018 9 35    0
Name: 9, dtype: int64
Cermak-McCormick Place 2019 9 35    50538
Name: 9, dtype: int64
Cermak-McCormick Place 2013 10 Series([], Name: 10, dtype: int64)
Cermak-McCormick Place 2014 10 Series([], Name: 10, dtype: int64)
Cermak-McCormick Place 2015 10 35    50854
Name: 10, dtype: int64
Cermak-McCormick Place 2016 10 35    48777
Name: 10, dtype: int64
Cermak-McCormick Place 2017 10 35    55850
Name: 10, dtype: int64
Cermak-McCormick Place 2018 10 35    0
Name: 10, dtype: int64
Cermak-McCormick Place 2019 10 35    60933
Name: 10, dtype: int64
Cermak-McCormick Place 2013 11 Series([], Name: 11, dtype: int64)
Cermak-McCormick Place 2014 11 Series([], Name: 11, dtype: int64)
Cermak-McCormick Place 2015 11 35    37078
Name: 11, dtype: int64
Cermak-McCormick Place 2016 11 35    40328
Name: 11, dtype: int64
Cermak-McCormick Place 2017 11 35    41508
Name: 11, dtype: int64
Cermak-McCormick Place 2018 11 35    0
Name: 11, dtype: int64
Cermak-McCormick Place 2019 11 35    37107
Name: 11, dtype: int64
Cermak-McCormick Place 2013 12 Series([], Name: 12, dtype: int64)
Cermak-McCormick Place 2014 12 Series([], Name: 12, dtype: int64)
Cermak-McCormick Place 2015 12 35    31027
Name: 12, dtype: int64
Cermak-McCormick Place 2016 12 35    28027
Name: 12, dtype: int64
Cermak-McCormick Place 2017 12 35    31015
Name: 12, dtype: int64
Cermak-McCormick Place 2018 12 35    0
Name: 12, dtype: int64
Cermak-McCormick Place 2019 12 35    35472
Name: 12, dtype: int64
Chicago/Franklin 2013 1 35    165824
Name: 1, dtype: int64
Chicago/Franklin 2014 1 35    165004
Name: 1, dtype: int64
Chicago/Franklin 2015 1 36    171699
Name: 1, dtype: int64
Chicago/Franklin 2016 1 36    161396
Name: 1, dtype: int64
Chicago/Franklin 2017 1 36    155841
Name: 1, dtype: int64
Chicago/Franklin 2018 1 36    163188
Name: 1, dtype: int64
Chicago/Franklin 2019 1 36    153837
Name: 1, dtype: int64
Chicago/Franklin 2013 2 35    165248
Name: 2, dtype: int64
Chicago/Franklin 2014 2 35    164829
Name: 2, dtype: int64
Chicago/Franklin 2015 2 36    171830
Name: 2, dtype: int64
Chicago/Franklin 2016 2 36    160826
Name: 2, dtype: int64
Chicago/Franklin 2017 2 36    147093
Name: 2, dtype: int64
Chicago/Franklin 2018 2 36    155559
Name: 2, dtype: int64
Chicago/Franklin 2019 2 36    154666
Name: 2, dtype: int64
Chicago/Franklin 2013 3 35    151797
Name: 3, dtype: int64
Chicago/Franklin 2014 3 35    180625
Name: 3, dtype: int64
Chicago/Franklin 2015 3 36    178813
Name: 3, dtype: int64
Chicago/Franklin 2016 3 36    173052
Name: 3, dtype: int64
Chicago/Franklin 2017 3 36    168743
Name: 3, dtype: int64
Chicago/Franklin 2018 3 36    176073
Name: 3, dtype: int64
Chicago/Franklin 2019 3 36    165744
Name: 3, dtype: int64
Chicago/Franklin 2013 4 35    167626
Name: 4, dtype: int64
Chicago/Franklin 2014 4 35    182378
Name: 4, dtype: int64
Chicago/Franklin 2015 4 36    165242
Name: 4, dtype: int64
Chicago/Franklin 2016 4 36    164237
Name: 4, dtype: int64
Chicago/Franklin 2017 4 36    157523
Name: 4, dtype: int64
Chicago/Franklin 2018 4 36    169844
Name: 4, dtype: int64
Chicago/Franklin 2019 4 36    167448
Name: 4, dtype: int64
Chicago/Franklin 2013 5 35    160080
Name: 5, dtype: int64
Chicago/Franklin 2014 5 35    176266
Name: 5, dtype: int64
Chicago/Franklin 2015 5 36    144451
Name: 5, dtype: int64
Chicago/Franklin 2016 5 36    163605
Name: 5, dtype: int64
Chicago/Franklin 2017 5 36    165961
Name: 5, dtype: int64
Chicago/Franklin 2018 5 36    177280
Name: 5, dtype: int64
Chicago/Franklin 2019 5 36    173048
Name: 5, dtype: int64
Chicago/Franklin 2013 6 35    163336
Name: 6, dtype: int64
Chicago/Franklin 2014 6 35    170524
Name: 6, dtype: int64
Chicago/Franklin 2015 6 36    170092
Name: 6, dtype: int64
Chicago/Franklin 2016 6 36    171308
Name: 6, dtype: int64
Chicago/Franklin 2017 6 36    173476
Name: 6, dtype: int64
Chicago/Franklin 2018 6 36    177013
Name: 6, dtype: int64
Chicago/Franklin 2019 6 36    166244
Name: 6, dtype: int64
Chicago/Franklin 2013 7 35    175888
Name: 7, dtype: int64
Chicago/Franklin 2014 7 35    178526
Name: 7, dtype: int64
Chicago/Franklin 2015 7 36    169761
Name: 7, dtype: int64
Chicago/Franklin 2016 7 36    162834
Name: 7, dtype: int64
Chicago/Franklin 2017 7 36    163756
Name: 7, dtype: int64
Chicago/Franklin 2018 7 36    0
Name: 7, dtype: int64
Chicago/Franklin 2019 7 36    173760
Name: 7, dtype: int64
Chicago/Franklin 2013 8 35    175073
Name: 8, dtype: int64
Chicago/Franklin 2014 8 35    169384
Name: 8, dtype: int64
Chicago/Franklin 2015 8 36    155536
Name: 8, dtype: int64
Chicago/Franklin 2016 8 36    174275
Name: 8, dtype: int64
Chicago/Franklin 2017 8 36    181887
Name: 8, dtype: int64
Chicago/Franklin 2018 8 36    0
Name: 8, dtype: int64
Chicago/Franklin 2019 8 36    178419
Name: 8, dtype: int64
Chicago/Franklin 2013 9 35    168080
Name: 9, dtype: int64
Chicago/Franklin 2014 9 35    176199
Name: 9, dtype: int64
Chicago/Franklin 2015 9 36    158579
Name: 9, dtype: int64
Chicago/Franklin 2016 9 36    169377

Name: 9, dtype: int64
Chicago/Franklin 2017 9 36    168869
Name: 9, dtype: int64
Chicago/Franklin 2018 9 36    0
Name: 9, dtype: int64
Chicago/Franklin 2019 9 36    173769
Name: 9, dtype: int64
Chicago/Franklin 2013 10 35    195185
Name: 10, dtype: int64
Chicago/Franklin 2014 10 35    197779
Name: 10, dtype: int64
Chicago/Franklin 2015 10 36    187840
Name: 10, dtype: int64
Chicago/Franklin 2016 10 36    179444
Name: 10, dtype: int64
Chicago/Franklin 2017 10 36    186242
Name: 10, dtype: int64
Chicago/Franklin 2018 10 36    0
Name: 10, dtype: int64
Chicago/Franklin 2019 10 36    190004
Name: 10, dtype: int64
Chicago/Franklin 2013 11 35    163587
Name: 11, dtype: int64
Chicago/Franklin 2014 11 35    159847
Name: 11, dtype: int64
Chicago/Franklin 2015 11 36    162688
Name: 11, dtype: int64
Chicago/Franklin 2016 11 36    160641
Name: 11, dtype: int64
Chicago/Franklin 2017 11 36    167980
Name: 11, dtype: int64
Chicago/Franklin 2018 11 36    0
Name: 11, dtype: int64
Chicago/Franklin 2019 11 36    157346
Name: 11, dtype: int64
Chicago/Franklin 2013 12 35    150333
Name: 12, dtype: int64
Chicago/Franklin 2014 12 35    161407
Name: 12, dtype: int64
Chicago/Franklin 2015 12 36    156501
Name: 12, dtype: int64
Chicago/Franklin 2016 12 36    140441
Name: 12, dtype: int64
Chicago/Franklin 2017 12 36    143375
Name: 12, dtype: int64
Chicago/Franklin 2018 12 36    0
Name: 12, dtype: int64
Chicago/Franklin 2019 12 36    139090
Name: 12, dtype: int64
Chicago/Milwaukee 2013 1 36    105993
Name: 1, dtype: int64
Chicago/Milwaukee 2014 1 36    105674
Name: 1, dtype: int64
Chicago/Milwaukee 2015 1 37    105537
Name: 1, dtype: int64
Chicago/Milwaukee 2016 1 37    105188
Name: 1, dtype: int64
Chicago/Milwaukee 2017 1 37    100397
Name: 1, dtype: int64
Chicago/Milwaukee 2018 1 37    100291
Name: 1, dtype: int64
Chicago/Milwaukee 2019 1 37    83338
Name: 1, dtype: int64
Chicago/Milwaukee 2013 2 36    103905
Name: 2, dtype: int64
Chicago/Milwaukee 2014 2 36    107002
Name: 2, dtype: int64
Chicago/Milwaukee 2015 2 37    103964
Name: 2, dtype: int64
Chicago/Milwaukee 2016 2 37    107512
Name: 2, dtype: int64
Chicago/Milwaukee 2017 2 37    95417
Name: 2, dtype: int64
Chicago/Milwaukee 2018 2 37    95332
Name: 2, dtype: int64
Chicago/Milwaukee 2019 2 37    87772
Name: 2, dtype: int64
Chicago/Milwaukee 2013 3 36    114690
Name: 3, dtype: int64
Chicago/Milwaukee 2014 3 36    115889
Name: 3, dtype: int64
Chicago/Milwaukee 2015 3 37    116297
Name: 3, dtype: int64
Chicago/Milwaukee 2016 3 37    117366
Name: 3, dtype: int64
Chicago/Milwaukee 2017 3 37    112170
Name: 3, dtype: int64
Chicago/Milwaukee 2018 3 37    108581
Name: 3, dtype: int64
Chicago/Milwaukee 2019 3 37    100424
Name: 3, dtype: int64
Chicago/Milwaukee 2013 4 36    112494
Name: 4, dtype: int64
Chicago/Milwaukee 2014 4 36    109849
Name: 4, dtype: int64
Chicago/Milwaukee 2015 4 37    112845
Name: 4, dtype: int64
Chicago/Milwaukee 2016 4 37    108333
Name: 4, dtype: int64
Chicago/Milwaukee 2017 4 37    100462
Name: 4, dtype: int64
Chicago/Milwaukee 2018 4 37    104392
Name: 4, dtype: int64
Chicago/Milwaukee 2019 4 37    98441
Name: 4, dtype: int64
Chicago/Milwaukee 2013 5 36    115563
Name: 5, dtype: int64
Chicago/Milwaukee 2014 5 36    113228
Name: 5, dtype: int64
Chicago/Milwaukee 2015 5 37    114888
Name: 5, dtype: int64
Chicago/Milwaukee 2016 5 37    111631
Name: 5, dtype: int64
Chicago/Milwaukee 2017 5 37    111983
Name: 5, dtype: int64
Chicago/Milwaukee 2018 5 37    111226
Name: 5, dtype: int64
Chicago/Milwaukee 2019 5 37    104833
Name: 5, dtype: int64
Chicago/Milwaukee 2013 6 36    110170
Name: 6, dtype: int64
Chicago/Milwaukee 2014 6 36    107089
Name: 6, dtype: int64
Chicago/Milwaukee 2015 6 37    117824
Name: 6, dtype: int64
Chicago/Milwaukee 2016 6 37    111930
Name: 6, dtype: int64
Chicago/Milwaukee 2017 6 37    113730
Name: 6, dtype: int64
Chicago/Milwaukee 2018 6 37    107381
Name: 6, dtype: int64
Chicago/Milwaukee 2019 6 37    98609
Name: 6, dtype: int64
Chicago/Milwaukee 2013 7 36    113251
Name: 7, dtype: int64
Chicago/Milwaukee 2014 7 36    108388
Name: 7, dtype: int64
Chicago/Milwaukee 2015 7 37    117748
Name: 7, dtype: int64
Chicago/Milwaukee 2016 7 37    106295
Name: 7, dtype: int64
Chicago/Milwaukee 2017 7 37    102820
Name: 7, dtype: int64
Chicago/Milwaukee 2018 7 37    104031
Name: 7, dtype: int64
Chicago/Milwaukee 2019 7 37    99862
Name: 7, dtype: int64
Chicago/Milwaukee 2013 8 36    114624
Name: 8, dtype: int64
Chicago/Milwaukee 2014 8 36    105583
Name: 8, dtype: int64
Chicago/Milwaukee 2015 8 37    111696
Name: 8, dtype: int64
Chicago/Milwaukee 2016 8 37    108082
Name: 8, dtype: int64
Chicago/Milwaukee 2017 8 37    111614
Name: 8, dtype: int64
Chicago/Milwaukee 2018 8 37    0
Name: 8, dtype: int64
Chicago/Milwaukee 2019 8 37    99822
Name: 8, dtype: int64
Chicago/Milwaukee 2013 9 36    114102
Name: 9, dtype: int64
Chicago/Milwaukee 2014 9 36    110453
Name: 9, dtype: int64
Chicago/Milwaukee 2015 9 37    117312
Name: 9, dtype: int64
Chicago/Milwaukee 2016 9 37    108918
Name: 9, dtype: int64
Chicago/Milwaukee 2017 9 37    108854
Name: 9, dtype: int64
Chicago/Milwaukee 2018 9 37    0
Name: 9, dtype: int64
Chicago/Milwaukee 2019 9 37    101072
Name: 9, dtype: int64
Chicago/Milwaukee 2013 10 36    126581
Name: 10, dtype: int64
Chicago/Milwaukee 2014 10 36    121696
Name: 10, dtype: int64
Chicago/Milwaukee 2015 10 37    124518
Name: 10, dtype: int64
Chicago/Milwaukee 2016 10 37    113447
Name: 10, dtype: int64
Chicago/Milwaukee 2017 10 37    113886
Name: 10, dtype: int64
Chicago/Milwaukee 2018 10 37    0
Name: 10, dtype: int64
Chicago/Milwaukee 2019 10 37    121315
Name: 10, dtype: int64
Chicago/Milwaukee 2013 11 36    110662
Name: 11, dtype: int64
Chicago/Milwaukee 2014 11 36    101851
Name: 11, dtype: int64
Chicago/Milwaukee 2015 11 37    106741
Name: 11, dtype: int64
Chicago/Milwaukee 2016 11 37    103963
Name: 11, dtype: int64
Chicago/Milwaukee 2017 11 37    104031
Name: 11, dtype: int64
Chicago/Milwaukee 2018 11 37    0
Name: 11, dtype: int64
Chicago/Milwaukee 2019 11 37    104615
Name: 11, dtype: int64
Chicago/Milwaukee 2013 12 36    104547
Name: 12, dtype: int64
Chicago/Milwaukee 2014 12 36    102734
Name: 12, dtype: int64
Chicago/Milwaukee 2015 12 37    105294
Name: 12, dtype: int64
Chicago/Milwaukee 2016 12 37    95052
Name: 12, dtype: int64
Chicago/Milwaukee 2017 12 37    92410
Name: 12, dtype: int64
Chicago/Milwaukee 2018 12 37    0
Name: 12, dtype: int64
Chicago/Milwaukee 2019 12 37    82365
Name: 12, dtype: int64
Chicago/State 2013 1 37    382920
Name: 1, dtype: int64
Chicago/State 2014 1 37    367089
Name: 1, dtype: int64
Chicago/State 2015 1 38    363295
Name: 1, dtype: int64
Chicago/State 2016 1 38    381507
Name: 1, dtype: int64
Chicago/State 2017 1 38    369906
Name: 1, dtype: int64
Chicago/State 2018 1 38    346394
Name: 1, dtype: int64
Chicago/State 2019 1 38    321309
Name: 1, dtype: int64
Chicago/State 2013 2 37    348148
Name: 2, dtype: int64
Chicago/State 2014 2 37    368334
Name: 2, dtype: int64
Chicago/State 2015 2 38    335286
Name: 2, dtype: int64
Chicago/State 2016 2 38    391570
Name: 2, dtype: int64
Chicago/State 2017 2 38    358820
Name: 2, dtype: int64
Chicago/State 2018 2 38    332641
Name: 2, dtype: int64
Chicago/State 2019 2 38    323862
Name: 2, dtype: int64
Chicago/State 2013 3 37    429705
Name: 3, dtype: int64
Chicago/State 2014 3 37    426621
Name: 3, dtype: int64
Chicago/State 2015 3 38    418226
Name: 3, dtype: int64
Chicago/State 2016 3 38    429989
Name: 3, dtype: int64
Chicago/State 2017 3 38    406769
Name: 3, dtype: int64
Chicago/State 2018 3 38    387107
Name: 3, dtype: int64
Chicago/State 2019 3 38    359656
Name: 3, dtype: int64
Chicago/State 2013 4 37    422870
Name: 4, dtype: int64
Chicago/State 2014 4 37    436605
Name: 4, dtype: int64
Chicago/State 2015 4 38    423372
Name: 4, dtype: int64
Chicago/State 2016 4 38    430493
Name: 4, dtype: int64
Chicago/State 2017 4 38    395486
Name: 4, dtype: int64
Chicago/State 2018 4 38    368343
Name: 4, dtype: int64
Chicago/State 2019 4 38    364182
Name: 4, dtype: int64
Chicago/State 2013 5 37    419720
Name: 5, dtype: int64
Chicago/State 2014 5 37    433560
Name: 5, dtype: int64
Chicago/State 2015 5 38    433176
Name: 5, dtype: int64

Chicago/State 2016 5 38    433624
Name: 5, dtype: int64
Chicago/State 2017 5 38    405370
Name: 5, dtype: int64
Chicago/State 2018 5 38    385787
Name: 5, dtype: int64
Chicago/State 2019 5 38    372901
Name: 5, dtype: int64
Chicago/State 2013 6 37    421738
Name: 6, dtype: int64
Chicago/State 2014 6 37    445645
Name: 6, dtype: int64
Chicago/State 2015 6 38    453442
Name: 6, dtype: int64
Chicago/State 2016 6 38    460749
Name: 6, dtype: int64
Chicago/State 2017 6 38    441035
Name: 6, dtype: int64
Chicago/State 2018 6 38    397451
Name: 6, dtype: int64
Chicago/State 2019 6 38    391799
Name: 6, dtype: int64
Chicago/State 2013 7 37    467299
Name: 7, dtype: int64
Chicago/State 2014 7 37    483678
Name: 7, dtype: int64
Chicago/State 2015 7 38    502911
Name: 7, dtype: int64
Chicago/State 2016 7 38    477189
Name: 7, dtype: int64
Chicago/State 2017 7 38    438641
Name: 7, dtype: int64
Chicago/State 2018 7 38    410972
Name: 7, dtype: int64
Chicago/State 2019 7 38    401842
Name: 7, dtype: int64
Chicago/State 2013 8 37    462668
Name: 8, dtype: int64
Chicago/State 2014 8 37    478982
Name: 8, dtype: int64
Chicago/State 2015 8 38    488020
Name: 8, dtype: int64
Chicago/State 2016 8 38    470122
Name: 8, dtype: int64
Chicago/State 2017 8 38    454621
Name: 8, dtype: int64
Chicago/State 2018 8 38    0
Name: 8, dtype: int64
Chicago/State 2019 8 38    408951
Name: 8, dtype: int64
Chicago/State 2013 9 37    434851
Name: 9, dtype: int64
Chicago/State 2014 9 37    461281
Name: 9, dtype: int64
Chicago/State 2015 9 38    474999
Name: 9, dtype: int64
Chicago/State 2016 9 38    455240
Name: 9, dtype: int64
Chicago/State 2017 9 38    430248
Name: 9, dtype: int64
Chicago/State 2018 9 38    0
Name: 9, dtype: int64
Chicago/State 2019 9 38    394635
Name: 9, dtype: int64
Chicago/State 2013 10 37    474041
Name: 10, dtype: int64
Chicago/State 2014 10 37    486925
Name: 10, dtype: int64
Chicago/State 2015 10 38    499461
Name: 10, dtype: int64
Chicago/State 2016 10 38    478243
Name: 10, dtype: int64
Chicago/State 2017 10 38    440613
Name: 10, dtype: int64
Chicago/State 2018 10 38    0
Name: 10, dtype: int64
Chicago/State 2019 10 38    427628
Name: 10, dtype: int64
Chicago/State 2013 11 37    445199
Name: 11, dtype: int64
Chicago/State 2014 11 37    440336
Name: 11, dtype: int64
Chicago/State 2015 11 38    442441
Name: 11, dtype: int64
Chicago/State 2016 11 38    451957
Name: 11, dtype: int64
Chicago/State 2017 11 38    397979
Name: 11, dtype: int64
Chicago/State 2018 11 38    0
Name: 11, dtype: int64
Chicago/State 2019 11 38    383961
Name: 11, dtype: int64
Chicago/State 2013 12 37    410508
Name: 12, dtype: int64
Chicago/State 2014 12 37    430936
Name: 12, dtype: int64
Chicago/State 2015 12 38    427909
Name: 12, dtype: int64
Chicago/State 2016 12 38    402091
Name: 12, dtype: int64
Chicago/State 2017 12 38    362607
Name: 12, dtype: int64
Chicago/State 2018 12 38    0
Name: 12, dtype: int64
Chicago/State 2019 12 38    351125
Name: 12, dtype: int64
Cicero-Cermak 2013 1 38    32604
Name: 1, dtype: int64
Cicero-Cermak 2014 1 38    31093
Name: 1, dtype: int64
Cicero-Cermak 2015 1 39    33260
Name: 1, dtype: int64
Cicero-Cermak 2016 1 39    32531
Name: 1, dtype: int64
Cicero-Cermak 2017 1 39    30492
Name: 1, dtype: int64
Cicero-Cermak 2018 1 39    28436
Name: 1, dtype: int64
Cicero-Cermak 2019 1 39    26476
Name: 1, dtype: int64
Cicero-Cermak 2013 2 38    30515
Name: 2, dtype: int64
Cicero-Cermak 2014 2 38    31864
Name: 2, dtype: int64
Cicero-Cermak 2015 2 39    31501
Name: 2, dtype: int64
Cicero-Cermak 2016 2 39    32991
Name: 2, dtype: int64
Cicero-Cermak 2017 2 39    30583
Name: 2, dtype: int64
Cicero-Cermak 2018 2 39    27739
Name: 2, dtype: int64
Cicero-Cermak 2019 2 39    26571
Name: 2, dtype: int64
Cicero-Cermak 2013 3 38    33822
Name: 3, dtype: int64
Cicero-Cermak 2014 3 38    36531
Name: 3, dtype: int64
Cicero-Cermak 2015 3 39    36032
Name: 3, dtype: int64
Cicero-Cermak 2016 3 39    35147
Name: 3, dtype: int64
Cicero-Cermak 2017 3 39    33324
Name: 3, dtype: int64
Cicero-Cermak 2018 3 39    31798
Name: 3, dtype: int64
Cicero-Cermak 2019 3 39    29811
Name: 3, dtype: int64
Cicero-Cermak 2013 4 38    35168
Name: 4, dtype: int64
Cicero-Cermak 2014 4 38    37534
Name: 4, dtype: int64
Cicero-Cermak 2015 4 39    36889
Name: 4, dtype: int64
Cicero-Cermak 2016 4 39    33314
Name: 4, dtype: int64
Cicero-Cermak 2017 4 39    31716
Name: 4, dtype: int64
Cicero-Cermak 2018 4 39    30367
Name: 4, dtype: int64
Cicero-Cermak 2019 4 39    31202
Name: 4, dtype: int64
Cicero-Cermak 2013 5 38    36457
Name: 5, dtype: int64
Cicero-Cermak 2014 5 38    38622
Name: 5, dtype: int64
Cicero-Cermak 2015 5 39    37981
Name: 5, dtype: int64
Cicero-Cermak 2016 5 39    36296
Name: 5, dtype: int64
Cicero-Cermak 2017 5 39    34120
Name: 5, dtype: int64
Cicero-Cermak 2018 5 39    33959
Name: 5, dtype: int64
Cicero-Cermak 2019 5 39    33094
Name: 5, dtype: int64
Cicero-Cermak 2013 6 38    36938
Name: 6, dtype: int64
Cicero-Cermak 2014 6 38    38686
Name: 6, dtype: int64
Cicero-Cermak 2015 6 39    40138
Name: 6, dtype: int64
Cicero-Cermak 2016 6 39    38031
Name: 6, dtype: int64
Cicero-Cermak 2017 6 39    35709
Name: 6, dtype: int64
Cicero-Cermak 2018 6 39    33468
Name: 6, dtype: int64
Cicero-Cermak 2019 6 39    32315
Name: 6, dtype: int64
Cicero-Cermak 2013 7 38    40026
Name: 7, dtype: int64
Cicero-Cermak 2014 7 38    41072
Name: 7, dtype: int64
Cicero-Cermak 2015 7 39    42228
Name: 7, dtype: int64
Cicero-Cermak 2016 7 39    37889
Name: 7, dtype: int64
Cicero-Cermak 2017 7 39    35425
Name: 7, dtype: int64
Cicero-Cermak 2018 7 39    34271
Name: 7, dtype: int64
Cicero-Cermak 2019 7 39    33562
Name: 7, dtype: int64
Cicero-Cermak 2013 8 38    39722
Name: 8, dtype: int64
Cicero-Cermak 2014 8 38    39807
Name: 8, dtype: int64
Cicero-Cermak 2015 8 39    40282
Name: 8, dtype: int64
Cicero-Cermak 2016 8 39    37569
Name: 8, dtype: int64
Cicero-Cermak 2017 8 39    36082
Name: 8, dtype: int64
Cicero-Cermak 2018 8 39    0
Name: 8, dtype: int64
Cicero-Cermak 2019 8 39    33575
Name: 8, dtype: int64
Cicero-Cermak 2013 9 38    36343
Name: 9, dtype: int64
Cicero-Cermak 2014 9 38    39180
Name: 9, dtype: int64
Cicero-Cermak 2015 9 39    40132
Name: 9, dtype: int64
Cicero-Cermak 2016 9 39    36654
Name: 9, dtype: int64
Cicero-Cermak 2017 9 39    35290
Name: 9, dtype: int64
Cicero-Cermak 2018 9 39    0
Name: 9, dtype: int64
Cicero-Cermak 2019 9 39    31643
Name: 9, dtype: int64
Cicero-Cermak 2013 10 38    39123
Name: 10, dtype: int64
Cicero-Cermak 2014 10 38    42115
Name: 10, dtype: int64
Cicero-Cermak 2015 10 39    42006
Name: 10, dtype: int64
Cicero-Cermak 2016 10 39    37687
Name: 10, dtype: int64
Cicero-Cermak 2017 10 39    35417
Name: 10, dtype: int64
Cicero-Cermak 2018 10 39    0
Name: 10, dtype: int64
Cicero-Cermak 2019 10 39    32459
Name: 10, dtype: int64
Cicero-Cermak 2013 11 38    35687
Name: 11, dtype: int64
Cicero-Cermak 2014 11 38    35758
Name: 11, dtype: int64
Cicero-Cermak 2015 11 39    36772
Name: 11, dtype: int64
Cicero-Cermak 2016 11 39    36063
Name: 11, dtype: int64
Cicero-Cermak 2017 11 39    32620
Name: 11, dtype: int64
Cicero-Cermak 2018 11 39    0
Name: 11, dtype: int64
Cicero-Cermak 2019 11 39    28900
Name: 11, dtype: int64
Cicero-Cermak 2013 12 38    33596
Name: 12, dtype: int64
Cicero-Cermak 2014 12 38    36415
Name: 12, dtype: int64
Cicero-Cermak 2015 12 39    37848
Name: 12, dtype: int64
Cicero-Cermak 2016 12 39    31783
Name: 12, dtype: int64
Cicero-Cermak 2017 12 39    29844
Name: 12, dtype: int64
Cicero-Cermak 2018 12 39    0
Name: 12, dtype: int64
Cicero-Cermak 2019 12 39    28453
Name: 12, dtype: int64
Cicero-Forest Park 2013 1 39    36253
Name: 1, dtype: int64
Cicero-Forest Park 2014 1 39    33396
Name: 1, dtype: int64
Cicero-Forest Park 2015 1 40    36628
Name: 1, dtype: int64
Cicero-Forest Park 2016 1 40    36276
Name: 1, dtype: int64
Cicero-Forest Park 2017 1 40    39840
Name: 1, dtype: int64
Cicero-Forest Park 2018 1 40    31232
Name: 1, dtype: int64
Cicero-Forest Park 2019 1 40    30747
Name: 1, dtype: int64
Cicero-Forest Park 2013 2 39    33211
Name: 2, dtype: int64
Cicero-Forest Park 2014 2 39    34243
Name: 2, dtype: int64
Cicero-Forest Park 2015 2 40    33395
Name: 2, dtype: int64
Cicero-Forest Park 2016 2 40    36490
Name: 2, dtype: int64
Cicero-Forest Park 2017 2 40    34612
Name: 2, dtype: int64
Cicero-Forest Park 2018 2 40    29288
Name: 2, dtype: int64
Cicero-Forest Park 2019 2 40    30339
Name: 2, dtype: int64
Cicero-Forest Park 2013 3 39    36360
Name: 3, dtype: int64
Cicero-Forest Park 2014 3 39    39257
Name: 3, dtype: int64
Cicero-Forest Park 2015 3 40    38857
Name: 3, dtype: int64
Cicero-Forest Park 2016 3 40    39772
Name: 3, dtype: int64
Cicero-Forest Park 2017 3 40    36334
Name: 3, dtype: int64
Cicero-Forest Park 2018 3 40    33268
Name: 3, dtype: int64
Cicero-Forest Park 2019 3 40    33130
Name: 3, dtype: int64
Cicero-Forest Park 2013 4 39    36620
Name: 4, dtype: int64
Cicero-Forest Park 2014 4 39    38856
Name: 4, dtype: int64
Cicero-Forest Park 2015 4 40    39627
Name: 4, dtype: int64
Cicero-Forest Park 2016 4 40    37707
Name: 4, dtype: int64
Cicero-Forest Park 2017 4 40    34950
Name: 4, dtype: int64
Cicero-Forest Park 2018 4 40    32862
Name: 4, dtype: int64
Cicero-Forest Park 2019 4 40    33392
Name: 4, dtype: int64
Cicero-Forest Park 2013 5 39    38460
Name: 5, dtype: int64
Cicero-Forest Park 2014 5 39    41297
Name: 5, dtype: int64
Cicero-Forest Park 2015 5 40    40464
Name: 5, dtype: int64
Cicero-Forest Park 2016 5 40    39667
Name: 5, dtype: int64
Cicero-Forest Park 2017 5 40    39649
Name: 5, dtype: int64
Cicero-Forest Park 2018 5 40    36739
Name: 5, dtype: int64
Cicero-Forest Park 2019 5 40    35321
Name: 5, dtype: int64

Cicero-Forest Park 2013 6 39    35805
Name: 6, dtype: int64
Cicero-Forest Park 2014 6 39    40287
Name: 6, dtype: int64
Cicero-Forest Park 2015 6 40    41036
Name: 6, dtype: int64
Cicero-Forest Park 2016 6 40    39661
Name: 6, dtype: int64
Cicero-Forest Park 2017 6 40    39676
Name: 6, dtype: int64
Cicero-Forest Park 2018 6 40    35991
Name: 6, dtype: int64
Cicero-Forest Park 2019 6 40    34783
Name: 6, dtype: int64
Cicero-Forest Park 2013 7 39    37434
Name: 7, dtype: int64
Cicero-Forest Park 2014 7 39    41071
Name: 7, dtype: int64
Cicero-Forest Park 2015 7 40    41574
Name: 7, dtype: int64
Cicero-Forest Park 2016 7 40    38509
Name: 7, dtype: int64
Cicero-Forest Park 2017 7 40    36569
Name: 7, dtype: int64
Cicero-Forest Park 2018 7 40    35385
Name: 7, dtype: int64
Cicero-Forest Park 2019 7 40    35505
Name: 7, dtype: int64
Cicero-Forest Park 2013 8 39    39081
Name: 8, dtype: int64
Cicero-Forest Park 2014 8 39    41194
Name: 8, dtype: int64
Cicero-Forest Park 2015 8 40    40987
Name: 8, dtype: int64
Cicero-Forest Park 2016 8 40    40545
Name: 8, dtype: int64
Cicero-Forest Park 2017 8 40    38115
Name: 8, dtype: int64
Cicero-Forest Park 2018 8 40    0
Name: 8, dtype: int64
Cicero-Forest Park 2019 8 40    37193
Name: 8, dtype: int64
Cicero-Forest Park 2013 9 39    39471
Name: 9, dtype: int64
Cicero-Forest Park 2014 9 39    44957
Name: 9, dtype: int64
Cicero-Forest Park 2015 9 40    44054
Name: 9, dtype: int64
Cicero-Forest Park 2016 9 40    40702
Name: 9, dtype: int64
Cicero-Forest Park 2017 9 40    37115
Name: 9, dtype: int64
Cicero-Forest Park 2018 9 40    0
Name: 9, dtype: int64
Cicero-Forest Park 2019 9 40    36118
Name: 9, dtype: int64
Cicero-Forest Park 2013 10 39    42587
Name: 10, dtype: int64
Cicero-Forest Park 2014 10 39    47136
Name: 10, dtype: int64
Cicero-Forest Park 2015 10 40    46176
Name: 10, dtype: int64
Cicero-Forest Park 2016 10 40    43126
Name: 10, dtype: int64
Cicero-Forest Park 2017 10 40    37312
Name: 10, dtype: int64
Cicero-Forest Park 2018 10 40    0
Name: 10, dtype: int64
Cicero-Forest Park 2019 10 40    37445
Name: 10, dtype: int64
Cicero-Forest Park 2013 11 39    38453
Name: 11, dtype: int64
Cicero-Forest Park 2014 11 39    39159
Name: 11, dtype: int64
Cicero-Forest Park 2015 11 40    40261
Name: 11, dtype: int64
Cicero-Forest Park 2016 11 40    43971
Name: 11, dtype: int64
Cicero-Forest Park 2017 11 40    35280
Name: 11, dtype: int64
Cicero-Forest Park 2018 11 40    0
Name: 11, dtype: int64
Cicero-Forest Park 2019 11 40    33157
Name: 11, dtype: int64
Cicero-Forest Park 2013 12 39    36207
Name: 12, dtype: int64
Cicero-Forest Park 2014 12 39    39832
Name: 12, dtype: int64
Cicero-Forest Park 2015 12 40    39881
Name: 12, dtype: int64
Cicero-Forest Park 2016 12 40    42292
Name: 12, dtype: int64
Cicero-Forest Park 2017 12 40    32661
Name: 12, dtype: int64
Cicero-Forest Park 2018 12 40    0
Name: 12, dtype: int64
Cicero-Forest Park 2019 12 40    31409
Name: 12, dtype: int64
Cicero-Lake 2013 1 40    35637
Name: 1, dtype: int64
Cicero-Lake 2014 1 40    35070
Name: 1, dtype: int64
Cicero-Lake 2015 1 41    40513
Name: 1, dtype: int64
Cicero-Lake 2016 1 41    36055
Name: 1, dtype: int64
Cicero-Lake 2017 1 41    32051
Name: 1, dtype: int64
Cicero-Lake 2018 1 41    30837
Name: 1, dtype: int64
Cicero-Lake 2019 1 41    27546
Name: 1, dtype: int64
Cicero-Lake 2013 2 40    33752
Name: 2, dtype: int64
Cicero-Lake 2014 2 40    36136
Name: 2, dtype: int64
Cicero-Lake 2015 2 41    37209
Name: 2, dtype: int64
Cicero-Lake 2016 2 41    35842
Name: 2, dtype: int64
Cicero-Lake 2017 2 41    31992
Name: 2, dtype: int64
Cicero-Lake 2018 2 41    28953
Name: 2, dtype: int64
Cicero-Lake 2019 2 41    27381
Name: 2, dtype: int64
Cicero-Lake 2013 3 40    34938
Name: 3, dtype: int64
Cicero-Lake 2014 3 40    41326
Name: 3, dtype: int64
Cicero-Lake 2015 3 41    41947
Name: 3, dtype: int64
Cicero-Lake 2016 3 41    39088
Name: 3, dtype: int64
Cicero-Lake 2017 3 41    34255
Name: 3, dtype: int64
Cicero-Lake 2018 3 41    32405
Name: 3, dtype: int64
Cicero-Lake 2019 3 41    30028
Name: 3, dtype: int64
Cicero-Lake 2013 4 40    36594
Name: 4, dtype: int64
Cicero-Lake 2014 4 40    41189
Name: 4, dtype: int64
Cicero-Lake 2015 4 41    41754
Name: 4, dtype: int64
Cicero-Lake 2016 4 41    35410
Name: 4, dtype: int64
Cicero-Lake 2017 4 41    32571
Name: 4, dtype: int64
Cicero-Lake 2018 4 41    31849
Name: 4, dtype: int64
Cicero-Lake 2019 4 41    30053
Name: 4, dtype: int64
Cicero-Lake 2013 5 40    38570
Name: 5, dtype: int64
Cicero-Lake 2014 5 40    43012
Name: 5, dtype: int64
Cicero-Lake 2015 5 41    42538
Name: 5, dtype: int64
Cicero-Lake 2016 5 41    37755
Name: 5, dtype: int64
Cicero-Lake 2017 5 41    36608
Name: 5, dtype: int64
Cicero-Lake 2018 5 41    35316
Name: 5, dtype: int64
Cicero-Lake 2019 5 41    33658
Name: 5, dtype: int64
Cicero-Lake 2013 6 40    36207
Name: 6, dtype: int64
Cicero-Lake 2014 6 40    42680
Name: 6, dtype: int64
Cicero-Lake 2015 6 41    42933
Name: 6, dtype: int64
Cicero-Lake 2016 6 41    38087
Name: 6, dtype: int64
Cicero-Lake 2017 6 41    36172
Name: 6, dtype: int64
Cicero-Lake 2018 6 41    33291
Name: 6, dtype: int64
Cicero-Lake 2019 6 41    32241
Name: 6, dtype: int64
Cicero-Lake 2013 7 40    39381
Name: 7, dtype: int64
Cicero-Lake 2014 7 40    43904
Name: 7, dtype: int64
Cicero-Lake 2015 7 41    43514
Name: 7, dtype: int64
Cicero-Lake 2016 7 41    36314
Name: 7, dtype: int64
Cicero-Lake 2017 7 41    34225
Name: 7, dtype: int64
Cicero-Lake 2018 7 41    33096
Name: 7, dtype: int64
Cicero-Lake 2019 7 41    32802
Name: 7, dtype: int64
Cicero-Lake 2013 8 40    41496
Name: 8, dtype: int64
Cicero-Lake 2014 8 40    44186
Name: 8, dtype: int64
Cicero-Lake 2015 8 41    41110
Name: 8, dtype: int64
Cicero-Lake 2016 8 41    36351
Name: 8, dtype: int64
Cicero-Lake 2017 8 41    35836
Name: 8, dtype: int64
Cicero-Lake 2018 8 41    0
Name: 8, dtype: int64
Cicero-Lake 2019 8 41    32633
Name: 8, dtype: int64
Cicero-Lake 2013 9 40    40716
Name: 9, dtype: int64
Cicero-Lake 2014 9 40    49182
Name: 9, dtype: int64
Cicero-Lake 2015 9 41    42226
Name: 9, dtype: int64
Cicero-Lake 2016 9 41    37065
Name: 9, dtype: int64
Cicero-Lake 2017 9 41    35433
Name: 9, dtype: int64
Cicero-Lake 2018 9 41    0
Name: 9, dtype: int64
Cicero-Lake 2019 9 41    32022
Name: 9, dtype: int64
Cicero-Lake 2013 10 40    43555
Name: 10, dtype: int64
Cicero-Lake 2014 10 40    50822
Name: 10, dtype: int64
Cicero-Lake 2015 10 41    44105
Name: 10, dtype: int64
Cicero-Lake 2016 10 41    37890
Name: 10, dtype: int64
Cicero-Lake 2017 10 41    36307
Name: 10, dtype: int64
Cicero-Lake 2018 10 41    0
Name: 10, dtype: int64
Cicero-Lake 2019 10 41    33152
Name: 10, dtype: int64
Cicero-Lake 2013 11 40    38160
Name: 11, dtype: int64
Cicero-Lake 2014 11 40    42365
Name: 11, dtype: int64
Cicero-Lake 2015 11 41    39305
Name: 11, dtype: int64
Cicero-Lake 2016 11 41    35261
Name: 11, dtype: int64
Cicero-Lake 2017 11 41    33742
Name: 11, dtype: int64
Cicero-Lake 2018 11 41    0
Name: 11, dtype: int64
Cicero-Lake 2019 11 41    29580
Name: 11, dtype: int64
Cicero-Lake 2013 12 40    37016
Name: 12, dtype: int64
Cicero-Lake 2014 12 40    43709
Name: 12, dtype: int64
Cicero-Lake 2015 12 41    39400
Name: 12, dtype: int64
Cicero-Lake 2016 12 41    32915
Name: 12, dtype: int64
Cicero-Lake 2017 12 41    31310
Name: 12, dtype: int64
Cicero-Lake 2018 12 41    0
Name: 12, dtype: int64
Cicero-Lake 2019 12 41    29224
Name: 12, dtype: int64
Clark/Division 2013 1 41    202337
Name: 1, dtype: int64
Clark/Division 2014 1 41    197625
Name: 1, dtype: int64
Clark/Division 2015 1 42    179784
Name: 1, dtype: int64
Clark/Division 2016 1 42    211492
Name: 1, dtype: int64
Clark/Division 2017 1 42    204603
Name: 1, dtype: int64
Clark/Division 2018 1 42    199676
Name: 1, dtype: int64
Clark/Division 2019 1 42    183502
Name: 1, dtype: int64
Clark/Division 2013 2 41    181522
Name: 2, dtype: int64
Clark/Division 2014 2 41    198121
Name: 2, dtype: int64
Clark/Division 2015 2 42    168211
Name: 2, dtype: int64
Clark/Division 2016 2 42    211847
Name: 2, dtype: int64
Clark/Division 2017 2 42    194942
Name: 2, dtype: int64
Clark/Division 2018 2 42    189468
Name: 2, dtype: int64
Clark/Division 2019 2 42    182866
Name: 2, dtype: int64
Clark/Division 2013 3 41    213148
Name: 3, dtype: int64
Clark/Division 2014 3 41    225937
Name: 3, dtype: int64
Clark/Division 2015 3 42    205728
Name: 3, dtype: int64
Clark/Division 2016 3 42    231791
Name: 3, dtype: int64
Clark/Division 2017 3 42    223492
Name: 3, dtype: int64
Clark/Division 2018 3 42    215569
Name: 3, dtype: int64
Clark/Division 2019 3 42    201232
Name: 3, dtype: int64
Clark/Division 2013 4 41    214387
Name: 4, dtype: int64
Clark/Division 2014 4 41    219703
Name: 4, dtype: int64
Clark/Division 2015 4 42    203059
Name: 4, dtype: int64
Clark/Division 2016 4 42    225570
Name: 4, dtype: int64
Clark/Division 2017 4 42    209152
Name: 4, dtype: int64
Clark/Division 2018 4 42    206290
Name: 4, dtype: int64
Clark/Division 2019 4 42    197081
Name: 4, dtype: int64
Clark/Division 2013 5 41    219070
Name: 5, dtype: int64
Clark/Division 2014 5 41    225069
Name: 5, dtype: int64
Clark/Division 2015 5 42    218769
Name: 5, dtype: int64
Clark/Division 2016 5 42    238029
Name: 5, dtype: int64
Clark/Division 2017 5 42    225999
Name: 5, dtype: int64
Clark/Division 2018 5 42    228269
Name: 5, dtype: int64
Clark/Division 2019 5 42    216161
Name: 5, dtype: int64
Clark/Division 2013 6 41    222371
Name: 6, dtype: int64

Clark/Division 2014 6 41    230870
Name: 6, dtype: int64
Clark/Division 2015 6 42    227613
Name: 6, dtype: int64
Clark/Division 2016 6 42    248106
Name: 6, dtype: int64
Clark/Division 2017 6 42    237004
Name: 6, dtype: int64
Clark/Division 2018 6 42    230406
Name: 6, dtype: int64
Clark/Division 2019 6 42    217901
Name: 6, dtype: int64
Clark/Division 2013 7 41    194862
Name: 7, dtype: int64
Clark/Division 2014 7 41    222329
Name: 7, dtype: int64
Clark/Division 2015 7 42    237079
Name: 7, dtype: int64
Clark/Division 2016 7 42    237716
Name: 7, dtype: int64
Clark/Division 2017 7 42    223180
Name: 7, dtype: int64
Clark/Division 2018 7 42    224276
Name: 7, dtype: int64
Clark/Division 2019 7 42    216360
Name: 7, dtype: int64
Clark/Division 2013 8 41    233204
Name: 8, dtype: int64
Clark/Division 2014 8 41    225645
Name: 8, dtype: int64
Clark/Division 2015 8 42    232987
Name: 8, dtype: int64
Clark/Division 2016 8 42    235759
Name: 8, dtype: int64
Clark/Division 2017 8 42    237642
Name: 8, dtype: int64
Clark/Division 2018 8 42    0
Name: 8, dtype: int64
Clark/Division 2019 8 42    220421
Name: 8, dtype: int64
Clark/Division 2013 9 41    221955
Name: 9, dtype: int64
Clark/Division 2014 9 41    219879
Name: 9, dtype: int64
Clark/Division 2015 9 42    228601
Name: 9, dtype: int64
Clark/Division 2016 9 42    233332
Name: 9, dtype: int64
Clark/Division 2017 9 42    231088
Name: 9, dtype: int64
Clark/Division 2018 9 42    0
Name: 9, dtype: int64
Clark/Division 2019 9 42    214279
Name: 9, dtype: int64
Clark/Division 2013 10 41    241502
Name: 10, dtype: int64
Clark/Division 2014 10 41    230808
Name: 10, dtype: int64
Clark/Division 2015 10 42    232012
Name: 10, dtype: int64
Clark/Division 2016 10 42    254072
Name: 10, dtype: int64
Clark/Division 2017 10 42    242126
Name: 10, dtype: int64
Clark/Division 2018 10 42    0
Name: 10, dtype: int64
Clark/Division 2019 10 42    226043
Name: 10, dtype: int64
Clark/Division 2013 11 41    214549
Name: 11, dtype: int64
Clark/Division 2014 11 41    198315
Name: 11, dtype: int64
Clark/Division 2015 11 42    220990
Name: 11, dtype: int64
Clark/Division 2016 11 42    221607
Name: 11, dtype: int64
Clark/Division 2017 11 42    207594
Name: 11, dtype: int64
Clark/Division 2018 11 42    0
Name: 11, dtype: int64
Clark/Division 2019 11 42    196192
Name: 11, dtype: int64
Clark/Division 2013 12 41    195648
Name: 12, dtype: int64
Clark/Division 2014 12 41    189510
Name: 12, dtype: int64
Clark/Division 2015 12 42    212125
Name: 12, dtype: int64
Clark/Division 2016 12 42    198272
Name: 12, dtype: int64
Clark/Division 2017 12 42    193472
Name: 12, dtype: int64
Clark/Division 2018 12 42    0
Name: 12, dtype: int64
Clark/Division 2019 12 42    180943
Name: 12, dtype: int64
Clark/Lake 2013 1 42    434766
Name: 1, dtype: int64
Clark/Lake 2014 1 42    434627
Name: 1, dtype: int64
Clark/Lake 2015 1 43    430675
Name: 1, dtype: int64
Clark/Lake 2016 1 43    441731
Name: 1, dtype: int64
Clark/Lake 2017 1 43    462841
Name: 1, dtype: int64
Clark/Lake 2018 1 43    466023
Name: 1, dtype: int64
Clark/Lake 2019 1 43    436287
Name: 1, dtype: int64
Clark/Lake 2013 2 42    410167
Name: 2, dtype: int64
Clark/Lake 2014 2 42    405985
Name: 2, dtype: int64
Clark/Lake 2015 2 43    409229
Name: 2, dtype: int64
Clark/Lake 2016 2 43    457593
Name: 2, dtype: int64
Clark/Lake 2017 2 43    440612
Name: 2, dtype: int64
Clark/Lake 2018 2 43    428829
Name: 2, dtype: int64
Clark/Lake 2019 2 43    433898
Name: 2, dtype: int64
Clark/Lake 2013 3 42    448344
Name: 3, dtype: int64
Clark/Lake 2014 3 42    462520
Name: 3, dtype: int64
Clark/Lake 2015 3 43    499245
Name: 3, dtype: int64
Clark/Lake 2016 3 43    527312
Name: 3, dtype: int64
Clark/Lake 2017 3 43    521817
Name: 3, dtype: int64
Clark/Lake 2018 3 43    515477
Name: 3, dtype: int64
Clark/Lake 2019 3 43    488910
Name: 3, dtype: int64
Clark/Lake 2013 4 42    471036
Name: 4, dtype: int64
Clark/Lake 2014 4 42    464463
Name: 4, dtype: int64
Clark/Lake 2015 4 43    497437
Name: 4, dtype: int64
Clark/Lake 2016 4 43    489155
Name: 4, dtype: int64
Clark/Lake 2017 4 43    474517
Name: 4, dtype: int64
Clark/Lake 2018 4 43    485967
Name: 4, dtype: int64
Clark/Lake 2019 4 43    491023
Name: 4, dtype: int64
Clark/Lake 2013 5 42    473512
Name: 5, dtype: int64
Clark/Lake 2014 5 42    469761
Name: 5, dtype: int64
Clark/Lake 2015 5 43    494058
Name: 5, dtype: int64
Clark/Lake 2016 5 43    505303
Name: 5, dtype: int64
Clark/Lake 2017 5 43    524337
Name: 5, dtype: int64
Clark/Lake 2018 5 43    527149
Name: 5, dtype: int64
Clark/Lake 2019 5 43    515785
Name: 5, dtype: int64
Clark/Lake 2013 6 42    476922
Name: 6, dtype: int64
Clark/Lake 2014 6 42    479304
Name: 6, dtype: int64
Clark/Lake 2015 6 43    542188
Name: 6, dtype: int64
Clark/Lake 2016 6 43    536293
Name: 6, dtype: int64
Clark/Lake 2017 6 43    551787
Name: 6, dtype: int64
Clark/Lake 2018 6 43    533778
Name: 6, dtype: int64
Clark/Lake 2019 6 43    504296
Name: 6, dtype: int64
Clark/Lake 2013 7 42    510409
Name: 7, dtype: int64
Clark/Lake 2014 7 42    502403
Name: 7, dtype: int64
Clark/Lake 2015 7 43    561606
Name: 7, dtype: int64
Clark/Lake 2016 7 43    510492
Name: 7, dtype: int64
Clark/Lake 2017 7 43    510470
Name: 7, dtype: int64
Clark/Lake 2018 7 43    0
Name: 7, dtype: int64
Clark/Lake 2019 7 43    525120
Name: 7, dtype: int64
Clark/Lake 2013 8 42    507768
Name: 8, dtype: int64
Clark/Lake 2014 8 42    480388
Name: 8, dtype: int64
Clark/Lake 2015 8 43    533193
Name: 8, dtype: int64
Clark/Lake 2016 8 43    538887
Name: 8, dtype: int64
Clark/Lake 2017 8 43    564474
Name: 8, dtype: int64
Clark/Lake 2018 8 43    0
Name: 8, dtype: int64
Clark/Lake 2019 8 43    529193
Name: 8, dtype: int64
Clark/Lake 2013 9 42    466915
Name: 9, dtype: int64
Clark/Lake 2014 9 42    482564
Name: 9, dtype: int64
Clark/Lake 2015 9 43    529439
Name: 9, dtype: int64
Clark/Lake 2016 9 43    508022
Name: 9, dtype: int64
Clark/Lake 2017 9 43    507451
Name: 9, dtype: int64
Clark/Lake 2018 9 43    0
Name: 9, dtype: int64
Clark/Lake 2019 9 43    492305
Name: 9, dtype: int64
Clark/Lake 2013 10 42    520504
Name: 10, dtype: int64
Clark/Lake 2014 10 42    527351
Name: 10, dtype: int64
Clark/Lake 2015 10 43    560017
Name: 10, dtype: int64
Clark/Lake 2016 10 43    526287
Name: 10, dtype: int64
Clark/Lake 2017 10 43    548682
Name: 10, dtype: int64
Clark/Lake 2018 10 43    0
Name: 10, dtype: int64
Clark/Lake 2019 10 43    554822
Name: 10, dtype: int64
Clark/Lake 2013 11 42    425283
Name: 11, dtype: int64
Clark/Lake 2014 11 42    427013
Name: 11, dtype: int64
Clark/Lake 2015 11 43    474828
Name: 11, dtype: int64
Clark/Lake 2016 11 43    498800
Name: 11, dtype: int64
Clark/Lake 2017 11 43    489570
Name: 11, dtype: int64
Clark/Lake 2018 11 43    0
Name: 11, dtype: int64
Clark/Lake 2019 11 43    441955
Name: 11, dtype: int64
Clark/Lake 2013 12 42    397932
Name: 12, dtype: int64
Clark/Lake 2014 12 42    436856
Name: 12, dtype: int64
Clark/Lake 2015 12 43    465154
Name: 12, dtype: int64
Clark/Lake 2016 12 43    432791
Name: 12, dtype: int64
Clark/Lake 2017 12 43    425975
Name: 12, dtype: int64
Clark/Lake 2018 12 43    0
Name: 12, dtype: int64
Clark/Lake 2019 12 43    417173
Name: 12, dtype: int64
Clinton-Forest Park 2013 1 43    87832
Name: 1, dtype: int64
Clinton-Forest Park 2014 1 43    85501
Name: 1, dtype: int64
Clinton-Forest Park 2015 1 44    88666
Name: 1, dtype: int64
Clinton-Forest Park 2016 1 44    93212
Name: 1, dtype: int64
Clinton-Forest Park 2017 1 44    91950
Name: 1, dtype: int64
Clinton-Forest Park 2018 1 44    85833
Name: 1, dtype: int64
Clinton-Forest Park 2019 1 44    74115
Name: 1, dtype: int64
Clinton-Forest Park 2013 2 43    82938
Name: 2, dtype: int64
Clinton-Forest Park 2014 2 43    84228
Name: 2, dtype: int64
Clinton-Forest Park 2015 2 44    86739
Name: 2, dtype: int64
Clinton-Forest Park 2016 2 44    96261
Name: 2, dtype: int64
Clinton-Forest Park 2017 2 44    85086
Name: 2, dtype: int64
Clinton-Forest Park 2018 2 44    80488
Name: 2, dtype: int64
Clinton-Forest Park 2019 2 44    74472
Name: 2, dtype: int64
Clinton-Forest Park 2013 3 43    94009
Name: 3, dtype: int64
Clinton-Forest Park 2014 3 43    95249
Name: 3, dtype: int64
Clinton-Forest Park 2015 3 44    99982
Name: 3, dtype: int64
Clinton-Forest Park 2016 3 44    107858
Name: 3, dtype: int64
Clinton-Forest Park 2017 3 44    100028
Name: 3, dtype: int64
Clinton-Forest Park 2018 3 44    91536
Name: 3, dtype: int64
Clinton-Forest Park 2019 3 44    79517
Name: 3, dtype: int64
Clinton-Forest Park 2013 4 43    90160
Name: 4, dtype: int64
Clinton-Forest Park 2014 4 43    93212
Name: 4, dtype: int64
Clinton-Forest Park 2015 4 44    95617
Name: 4, dtype: int64
Clinton-Forest Park 2016 4 44    99542
Name: 4, dtype: int64
Clinton-Forest Park 2017 4 44    89844
Name: 4, dtype: int64
Clinton-Forest Park 2018 4 44    86514
Name: 4, dtype: int64
Clinton-Forest Park 2019 4 44    79942
Name: 4, dtype: int64
Clinton-Forest Park 2013 5 43    89162
Name: 5, dtype: int64
Clinton-Forest Park 2014 5 43    94154
Name: 5, dtype: int64

Clinton-Forest Park 2015 5 44    94815
Name: 5, dtype: int64
Clinton-Forest Park 2016 5 44    99531
Name: 5, dtype: int64
Clinton-Forest Park 2017 5 44    96619
Name: 5, dtype: int64
Clinton-Forest Park 2018 5 44    90750
Name: 5, dtype: int64
Clinton-Forest Park 2019 5 44    80994
Name: 5, dtype: int64
Clinton-Forest Park 2013 6 43    84934
Name: 6, dtype: int64
Clinton-Forest Park 2014 6 43    93792
Name: 6, dtype: int64
Clinton-Forest Park 2015 6 44    100465
Name: 6, dtype: int64
Clinton-Forest Park 2016 6 44    101430
Name: 6, dtype: int64
Clinton-Forest Park 2017 6 44    95587
Name: 6, dtype: int64
Clinton-Forest Park 2018 6 44    88858
Name: 6, dtype: int64
Clinton-Forest Park 2019 6 44    76151
Name: 6, dtype: int64
Clinton-Forest Park 2013 7 43    89896
Name: 7, dtype: int64
Clinton-Forest Park 2014 7 43    97616
Name: 7, dtype: int64
Clinton-Forest Park 2015 7 44    103860
Name: 7, dtype: int64
Clinton-Forest Park 2016 7 44    97342
Name: 7, dtype: int64
Clinton-Forest Park 2017 7 44    89179
Name: 7, dtype: int64
Clinton-Forest Park 2018 7 44    86660
Name: 7, dtype: int64
Clinton-Forest Park 2019 7 44    82713
Name: 7, dtype: int64
Clinton-Forest Park 2013 8 43    89949
Name: 8, dtype: int64
Clinton-Forest Park 2014 8 43    96033
Name: 8, dtype: int64
Clinton-Forest Park 2015 8 44    100911
Name: 8, dtype: int64
Clinton-Forest Park 2016 8 44    102567
Name: 8, dtype: int64
Clinton-Forest Park 2017 8 44    99651
Name: 8, dtype: int64
Clinton-Forest Park 2018 8 44    0
Name: 8, dtype: int64
Clinton-Forest Park 2019 8 44    87482
Name: 8, dtype: int64
Clinton-Forest Park 2013 9 43    84649
Name: 9, dtype: int64
Clinton-Forest Park 2014 9 43    95521
Name: 9, dtype: int64
Clinton-Forest Park 2015 9 44    102428
Name: 9, dtype: int64
Clinton-Forest Park 2016 9 44    100025
Name: 9, dtype: int64
Clinton-Forest Park 2017 9 44    92516
Name: 9, dtype: int64
Clinton-Forest Park 2018 9 44    0
Name: 9, dtype: int64
Clinton-Forest Park 2019 9 44    84738
Name: 9, dtype: int64
Clinton-Forest Park 2013 10 43    96867
Name: 10, dtype: int64
Clinton-Forest Park 2014 10 43    103175
Name: 10, dtype: int64
Clinton-Forest Park 2015 10 44    109702
Name: 10, dtype: int64
Clinton-Forest Park 2016 10 44    104341
Name: 10, dtype: int64
Clinton-Forest Park 2017 10 44    100291
Name: 10, dtype: int64
Clinton-Forest Park 2018 10 44    0
Name: 10, dtype: int64
Clinton-Forest Park 2019 10 44    95434
Name: 10, dtype: int64
Clinton-Forest Park 2013 11 43    86065
Name: 11, dtype: int64
Clinton-Forest Park 2014 11 43    88300
Name: 11, dtype: int64
Clinton-Forest Park 2015 11 44    96066
Name: 11, dtype: int64
Clinton-Forest Park 2016 11 44    99828
Name: 11, dtype: int64
Clinton-Forest Park 2017 11 44    92125
Name: 11, dtype: int64
Clinton-Forest Park 2018 11 44    0
Name: 11, dtype: int64
Clinton-Forest Park 2019 11 44    83985
Name: 11, dtype: int64
Clinton-Forest Park 2013 12 43    84981
Name: 12, dtype: int64
Clinton-Forest Park 2014 12 43    89858
Name: 12, dtype: int64
Clinton-Forest Park 2015 12 44    94770
Name: 12, dtype: int64
Clinton-Forest Park 2016 12 44    89292
Name: 12, dtype: int64
Clinton-Forest Park 2017 12 44    80084
Name: 12, dtype: int64
Clinton-Forest Park 2018 12 44    0
Name: 12, dtype: int64
Clinton-Forest Park 2019 12 44    80937
Name: 12, dtype: int64
Clinton-Lake 2013 1 44    102034
Name: 1, dtype: int64
Clinton-Lake 2014 1 44    92523
Name: 1, dtype: int64
Clinton-Lake 2015 1 45    90661
Name: 1, dtype: int64
Clinton-Lake 2016 1 45    95595
Name: 1, dtype: int64
Clinton-Lake 2017 1 45    94283
Name: 1, dtype: int64
Clinton-Lake 2018 1 45    99492
Name: 1, dtype: int64
Clinton-Lake 2019 1 45    93711
Name: 1, dtype: int64
Clinton-Lake 2013 2 44    98381
Name: 2, dtype: int64
Clinton-Lake 2014 2 44    93608
Name: 2, dtype: int64
Clinton-Lake 2015 2 45    88366
Name: 2, dtype: int64
Clinton-Lake 2016 2 45    97086
Name: 2, dtype: int64
Clinton-Lake 2017 2 45    90049
Name: 2, dtype: int64
Clinton-Lake 2018 2 45    94801
Name: 2, dtype: int64
Clinton-Lake 2019 2 45    96993
Name: 2, dtype: int64
Clinton-Lake 2013 3 44    109163
Name: 3, dtype: int64
Clinton-Lake 2014 3 44    101540
Name: 3, dtype: int64
Clinton-Lake 2015 3 45    99143
Name: 3, dtype: int64
Clinton-Lake 2016 3 45    106125
Name: 3, dtype: int64
Clinton-Lake 2017 3 45    103277
Name: 3, dtype: int64
Clinton-Lake 2018 3 45    103821
Name: 3, dtype: int64
Clinton-Lake 2019 3 45    103402
Name: 3, dtype: int64
Clinton-Lake 2013 4 44    110699
Name: 4, dtype: int64
Clinton-Lake 2014 4 44    102559
Name: 4, dtype: int64
Clinton-Lake 2015 4 45    100933
Name: 4, dtype: int64
Clinton-Lake 2016 4 45    99945
Name: 4, dtype: int64
Clinton-Lake 2017 4 45    94267
Name: 4, dtype: int64
Clinton-Lake 2018 4 45    100747
Name: 4, dtype: int64
Clinton-Lake 2019 4 45    107481
Name: 4, dtype: int64
Clinton-Lake 2013 5 44    109535
Name: 5, dtype: int64
Clinton-Lake 2014 5 44    100355
Name: 5, dtype: int64
Clinton-Lake 2015 5 45    99184
Name: 5, dtype: int64
Clinton-Lake 2016 5 45    100303
Name: 5, dtype: int64
Clinton-Lake 2017 5 45    100353
Name: 5, dtype: int64
Clinton-Lake 2018 5 45    103563
Name: 5, dtype: int64
Clinton-Lake 2019 5 45    109926
Name: 5, dtype: int64
Clinton-Lake 2013 6 44    103463
Name: 6, dtype: int64
Clinton-Lake 2014 6 44    100402
Name: 6, dtype: int64
Clinton-Lake 2015 6 45    109641
Name: 6, dtype: int64
Clinton-Lake 2016 6 45    106770
Name: 6, dtype: int64
Clinton-Lake 2017 6 45    104186
Name: 6, dtype: int64
Clinton-Lake 2018 6 45    106541
Name: 6, dtype: int64
Clinton-Lake 2019 6 45    113158
Name: 6, dtype: int64
Clinton-Lake 2013 7 44    109368
Name: 7, dtype: int64
Clinton-Lake 2014 7 44    104410
Name: 7, dtype: int64
Clinton-Lake 2015 7 45    110373
Name: 7, dtype: int64
Clinton-Lake 2016 7 45    100932
Name: 7, dtype: int64
Clinton-Lake 2017 7 45    97976
Name: 7, dtype: int64
Clinton-Lake 2018 7 45    105921
Name: 7, dtype: int64
Clinton-Lake 2019 7 45    114176
Name: 7, dtype: int64
Clinton-Lake 2013 8 44    109625
Name: 8, dtype: int64
Clinton-Lake 2014 8 44    99090
Name: 8, dtype: int64
Clinton-Lake 2015 8 45    105285
Name: 8, dtype: int64
Clinton-Lake 2016 8 45    106609
Name: 8, dtype: int64
Clinton-Lake 2017 8 45    109528
Name: 8, dtype: int64
Clinton-Lake 2018 8 45    0
Name: 8, dtype: int64
Clinton-Lake 2019 8 45    110711
Name: 8, dtype: int64
Clinton-Lake 2013 9 44    103640
Name: 9, dtype: int64
Clinton-Lake 2014 9 44    99592
Name: 9, dtype: int64
Clinton-Lake 2015 9 45    106957
Name: 9, dtype: int64
Clinton-Lake 2016 9 45    103338
Name: 9, dtype: int64
Clinton-Lake 2017 9 45    101633
Name: 9, dtype: int64
Clinton-Lake 2018 9 45    0
Name: 9, dtype: int64
Clinton-Lake 2019 9 45    106572
Name: 9, dtype: int64
Clinton-Lake 2013 10 44    115902
Name: 10, dtype: int64
Clinton-Lake 2014 10 44    108412
Name: 10, dtype: int64
Clinton-Lake 2015 10 45    113451
Name: 10, dtype: int64
Clinton-Lake 2016 10 45    106823
Name: 10, dtype: int64
Clinton-Lake 2017 10 45    112548
Name: 10, dtype: int64
Clinton-Lake 2018 10 45    0
Name: 10, dtype: int64
Clinton-Lake 2019 10 45    120799
Name: 10, dtype: int64
Clinton-Lake 2013 11 44    97640
Name: 11, dtype: int64
Clinton-Lake 2014 11 44    88836
Name: 11, dtype: int64
Clinton-Lake 2015 11 45    97536
Name: 11, dtype: int64
Clinton-Lake 2016 11 45    98907
Name: 11, dtype: int64
Clinton-Lake 2017 11 45    100919
Name: 11, dtype: int64
Clinton-Lake 2018 11 45    0
Name: 11, dtype: int64
Clinton-Lake 2019 11 45    103779
Name: 11, dtype: int64
Clinton-Lake 2013 12 44    87676
Name: 12, dtype: int64
Clinton-Lake 2014 12 44    89336
Name: 12, dtype: int64
Clinton-Lake 2015 12 45    93740
Name: 12, dtype: int64
Clinton-Lake 2016 12 45    86648
Name: 12, dtype: int64
Clinton-Lake 2017 12 45    86792
Name: 12, dtype: int64
Clinton-Lake 2018 12 45    0
Name: 12, dtype: int64
Clinton-Lake 2019 12 45    91157
Name: 12, dtype: int64
Conservatory 2013 1 45    21625
Name: 1, dtype: int64
Conservatory 2014 1 45    20367
Name: 1, dtype: int64
Conservatory 2015 1 46    23110
Name: 1, dtype: int64
Conservatory 2016 1 46    24127
Name: 1, dtype: int64
Conservatory 2017 1 46    21299
Name: 1, dtype: int64
Conservatory 2018 1 46    20586
Name: 1, dtype: int64
Conservatory 2019 1 46    19800
Name: 1, dtype: int64
Conservatory 2013 2 45    19711
Name: 2, dtype: int64
Conservatory 2014 2 45    21380
Name: 2, dtype: int64
Conservatory 2015 2 46    21140
Name: 2, dtype: int64
Conservatory 2016 2 46    23805
Name: 2, dtype: int64
Conservatory 2017 2 46    21818
Name: 2, dtype: int64
Conservatory 2018 2 46    20485
Name: 2, dtype: int64
Conservatory 2019 2 46    19195
Name: 2, dtype: int64
Conservatory 2013 3 45    21672
Name: 3, dtype: int64
Conservatory 2014 3 45    25560
Name: 3, dtype: int64
Conservatory 2015 3 46    26494
Name: 3, dtype: int64
Conservatory 2016 3 46    26753
Name: 3, dtype: int64
Conservatory 2017 3 46    24755
Name: 3, dtype: int64
Conservatory 2018 3 46    24633
Name: 3, dtype: int64
Conservatory 2019 3 46    23720
Name: 3, dtype: int64
Conservatory 2013 4 45    23987
Name: 4, dtype: int64
Conservatory 2014 4 45    25220
Name: 4, dtype: int64
Conservatory 2015 4 46    27205
Name: 4, dtype: int64
Conservatory 2016 4 46    24719
Name: 4, dtype: int64
Conservatory 2017 4 46    22768
Name: 4, dtype: int64
Conservatory 2018 4 46    25031
Name: 4, dtype: int64
Conservatory 2019 4 46    22425
Name: 4, dtype: int64
Conservatory 2013 5 45    26360
Name: 5, dtype: int64
Conservatory 2014 5 45    28847
Name: 5, dtype: int64
Conservatory 2015 5 46    29819
Name: 5, dtype: int64
Conservatory 2016 5 46    28115
Name: 5, dtype: int64
Conservatory 2017 5 46    25764
Name: 5, dtype: int64
Conservatory 2018 5 46    27794
Name: 5, dtype: int64
Conservatory 2019 5 46    25028
Name: 5, dtype: int64
Conservatory 2013 6 45    23587
Name: 6, dtype: int64

Conservatory 2014 6 45    27617
Name: 6, dtype: int64
Conservatory 2015 6 46    28391
Name: 6, dtype: int64
Conservatory 2016 6 46    25508
Name: 6, dtype: int64
Conservatory 2017 6 46    24181
Name: 6, dtype: int64
Conservatory 2018 6 46    25207
Name: 6, dtype: int64
Conservatory 2019 6 46    23165
Name: 6, dtype: int64
Conservatory 2013 7 45    25911
Name: 7, dtype: int64
Conservatory 2014 7 45    28366
Name: 7, dtype: int64
Conservatory 2015 7 46    30751
Name: 7, dtype: int64
Conservatory 2016 7 46    25946
Name: 7, dtype: int64
Conservatory 2017 7 46    24398
Name: 7, dtype: int64
Conservatory 2018 7 46    26635
Name: 7, dtype: int64
Conservatory 2019 7 46    25484
Name: 7, dtype: int64
Conservatory 2013 8 45    25200
Name: 8, dtype: int64
Conservatory 2014 8 45    26104
Name: 8, dtype: int64
Conservatory 2015 8 46    28538
Name: 8, dtype: int64
Conservatory 2016 8 46    25238
Name: 8, dtype: int64
Conservatory 2017 8 46    25147
Name: 8, dtype: int64
Conservatory 2018 8 46    0
Name: 8, dtype: int64
Conservatory 2019 8 46    24108
Name: 8, dtype: int64
Conservatory 2013 9 45    25704
Name: 9, dtype: int64
Conservatory 2014 9 45    28611
Name: 9, dtype: int64
Conservatory 2015 9 46    29835
Name: 9, dtype: int64
Conservatory 2016 9 46    27270
Name: 9, dtype: int64
Conservatory 2017 9 46    25527
Name: 9, dtype: int64
Conservatory 2018 9 46    0
Name: 9, dtype: int64
Conservatory 2019 9 46    24023
Name: 9, dtype: int64
Conservatory 2013 10 45    27470
Name: 10, dtype: int64
Conservatory 2014 10 45    29104
Name: 10, dtype: int64
Conservatory 2015 10 46    31356
Name: 10, dtype: int64
Conservatory 2016 10 46    26778
Name: 10, dtype: int64
Conservatory 2017 10 46    25399
Name: 10, dtype: int64
Conservatory 2018 10 46    0
Name: 10, dtype: int64
Conservatory 2019 10 46    25628
Name: 10, dtype: int64
Conservatory 2013 11 45    23645
Name: 11, dtype: int64
Conservatory 2014 11 45    23809
Name: 11, dtype: int64
Conservatory 2015 11 46    25773
Name: 11, dtype: int64
Conservatory 2016 11 46    24532
Name: 11, dtype: int64
Conservatory 2017 11 46    22523
Name: 11, dtype: int64
Conservatory 2018 11 46    0
Name: 11, dtype: int64
Conservatory 2019 11 46    23380
Name: 11, dtype: int64
Conservatory 2013 12 45    22459
Name: 12, dtype: int64
Conservatory 2014 12 45    24608
Name: 12, dtype: int64
Conservatory 2015 12 46    25428
Name: 12, dtype: int64
Conservatory 2016 12 46    21665
Name: 12, dtype: int64
Conservatory 2017 12 46    20515
Name: 12, dtype: int64
Conservatory 2018 12 46    0
Name: 12, dtype: int64
Conservatory 2019 12 46    22770
Name: 12, dtype: int64
Cumberland 2013 1 46    104424
Name: 1, dtype: int64
Cumberland 2014 1 46    97062
Name: 1, dtype: int64
Cumberland 2015 1 47    98502
Name: 1, dtype: int64
Cumberland 2016 1 47    101470
Name: 1, dtype: int64
Cumberland 2017 1 47    102667
Name: 1, dtype: int64
Cumberland 2018 1 47    100943
Name: 1, dtype: int64
Cumberland 2019 1 47    90585
Name: 1, dtype: int64
Cumberland 2013 2 46    99399
Name: 2, dtype: int64
Cumberland 2014 2 46    99145
Name: 2, dtype: int64
Cumberland 2015 2 47    94487
Name: 2, dtype: int64
Cumberland 2016 2 47    104031
Name: 2, dtype: int64
Cumberland 2017 2 47    98550
Name: 2, dtype: int64
Cumberland 2018 2 47    95097
Name: 2, dtype: int64
Cumberland 2019 2 47    91247
Name: 2, dtype: int64
Cumberland 2013 3 46    112663
Name: 3, dtype: int64
Cumberland 2014 3 46    114683
Name: 3, dtype: int64
Cumberland 2015 3 47    113911
Name: 3, dtype: int64
Cumberland 2016 3 47    118568
Name: 3, dtype: int64
Cumberland 2017 3 47    115811
Name: 3, dtype: int64
Cumberland 2018 3 47    111844
Name: 3, dtype: int64
Cumberland 2019 3 47    101509
Name: 3, dtype: int64
Cumberland 2013 4 46    119107
Name: 4, dtype: int64
Cumberland 2014 4 46    115211
Name: 4, dtype: int64
Cumberland 2015 4 47    116437
Name: 4, dtype: int64
Cumberland 2016 4 47    114541
Name: 4, dtype: int64
Cumberland 2017 4 47    110300
Name: 4, dtype: int64
Cumberland 2018 4 47    107446
Name: 4, dtype: int64
Cumberland 2019 4 47    104053
Name: 4, dtype: int64
Cumberland 2013 5 46    123665
Name: 5, dtype: int64
Cumberland 2014 5 46    117981
Name: 5, dtype: int64
Cumberland 2015 5 47    123447
Name: 5, dtype: int64
Cumberland 2016 5 47    120377
Name: 5, dtype: int64
Cumberland 2017 5 47    122378
Name: 5, dtype: int64
Cumberland 2018 5 47    115927
Name: 5, dtype: int64
Cumberland 2019 5 47    109012
Name: 5, dtype: int64
Cumberland 2013 6 46    130035
Name: 6, dtype: int64
Cumberland 2014 6 46    122600
Name: 6, dtype: int64
Cumberland 2015 6 47    134821
Name: 6, dtype: int64
Cumberland 2016 6 47    131029
Name: 6, dtype: int64
Cumberland 2017 6 47    132755
Name: 6, dtype: int64
Cumberland 2018 6 47    119441
Name: 6, dtype: int64
Cumberland 2019 6 47    110000
Name: 6, dtype: int64
Cumberland 2013 7 46    138582
Name: 7, dtype: int64
Cumberland 2014 7 46    128937
Name: 7, dtype: int64
Cumberland 2015 7 47    145242
Name: 7, dtype: int64
Cumberland 2016 7 47    131166
Name: 7, dtype: int64
Cumberland 2017 7 47    124907
Name: 7, dtype: int64
Cumberland 2018 7 47    117406
Name: 7, dtype: int64
Cumberland 2019 7 47    110494
Name: 7, dtype: int64
Cumberland 2013 8 46    138045
Name: 8, dtype: int64
Cumberland 2014 8 46    126804
Name: 8, dtype: int64
Cumberland 2015 8 47    132644
Name: 8, dtype: int64
Cumberland 2016 8 47    130222
Name: 8, dtype: int64
Cumberland 2017 8 47    137160
Name: 8, dtype: int64
Cumberland 2018 8 47    0
Name: 8, dtype: int64
Cumberland 2019 8 47    113519
Name: 8, dtype: int64
Cumberland 2013 9 46    125189
Name: 9, dtype: int64
Cumberland 2014 9 46    122432
Name: 9, dtype: int64
Cumberland 2015 9 47    132615
Name: 9, dtype: int64
Cumberland 2016 9 47    130198
Name: 9, dtype: int64
Cumberland 2017 9 47    122517
Name: 9, dtype: int64
Cumberland 2018 9 47    0
Name: 9, dtype: int64
Cumberland 2019 9 47    108167
Name: 9, dtype: int64
Cumberland 2013 10 46    132339
Name: 10, dtype: int64
Cumberland 2014 10 46    128357
Name: 10, dtype: int64
Cumberland 2015 10 47    134913
Name: 10, dtype: int64
Cumberland 2016 10 47    127153
Name: 10, dtype: int64
Cumberland 2017 10 47    127757
Name: 10, dtype: int64
Cumberland 2018 10 47    0
Name: 10, dtype: int64
Cumberland 2019 10 47    113967
Name: 10, dtype: int64
Cumberland 2013 11 46    111191
Name: 11, dtype: int64
Cumberland 2014 11 46    105696
Name: 11, dtype: int64
Cumberland 2015 11 47    113149
Name: 11, dtype: int64
Cumberland 2016 11 47    107295
Name: 11, dtype: int64
Cumberland 2017 11 47    112498
Name: 11, dtype: int64
Cumberland 2018 11 47    0
Name: 11, dtype: int64
Cumberland 2019 11 47    96143
Name: 11, dtype: int64
Cumberland 2013 12 46    103930
Name: 12, dtype: int64
Cumberland 2014 12 46    107213
Name: 12, dtype: int64
Cumberland 2015 12 47    111247
Name: 12, dtype: int64
Cumberland 2016 12 47    99261
Name: 12, dtype: int64
Cumberland 2017 12 47    98604
Name: 12, dtype: int64
Cumberland 2018 12 47    0
Name: 12, dtype: int64
Cumberland 2019 12 47    91114
Name: 12, dtype: int64
Damen-Brown 2013 1 47    65563
Name: 1, dtype: int64
Damen-Brown 2014 1 47    63832
Name: 1, dtype: int64
Damen-Brown 2015 1 48    63372
Name: 1, dtype: int64
Damen-Brown 2016 1 48    69649
Name: 1, dtype: int64
Damen-Brown 2017 1 48    72885
Name: 1, dtype: int64
Damen-Brown 2018 1 48    70134
Name: 1, dtype: int64
Damen-Brown 2019 1 48    64567
Name: 1, dtype: int64
Damen-Brown 2013 2 47    62647
Name: 2, dtype: int64
Damen-Brown 2014 2 47    65172
Name: 2, dtype: int64
Damen-Brown 2015 2 48    62642
Name: 2, dtype: int64
Damen-Brown 2016 2 48    70755
Name: 2, dtype: int64
Damen-Brown 2017 2 48    67392
Name: 2, dtype: int64
Damen-Brown 2018 2 48    65939
Name: 2, dtype: int64
Damen-Brown 2019 2 48    65340
Name: 2, dtype: int64
Damen-Brown 2013 3 47    63784
Name: 3, dtype: int64
Damen-Brown 2014 3 47    71109
Name: 3, dtype: int64
Damen-Brown 2015 3 48    70736
Name: 3, dtype: int64
Damen-Brown 2016 3 48    78956
Name: 3, dtype: int64
Damen-Brown 2017 3 48    78107
Name: 3, dtype: int64
Damen-Brown 2018 3 48    75147
Name: 3, dtype: int64
Damen-Brown 2019 3 48    72642
Name: 3, dtype: int64
Damen-Brown 2013 4 47    66542
Name: 4, dtype: int64
Damen-Brown 2014 4 47    69637
Name: 4, dtype: int64
Damen-Brown 2015 4 48    68019
Name: 4, dtype: int64
Damen-Brown 2016 4 48    72565
Name: 4, dtype: int64
Damen-Brown 2017 4 48    69710
Name: 4, dtype: int64
Damen-Brown 2018 4 48    69842
Name: 4, dtype: int64
Damen-Brown 2019 4 48    70533
Name: 4, dtype: int64
Damen-Brown 2013 5 47    65313
Name: 5, dtype: int64
Damen-Brown 2014 5 47    70245
Name: 5, dtype: int64
Damen-Brown 2015 5 48    68193
Name: 5, dtype: int64
Damen-Brown 2016 5 48    76739
Name: 5, dtype: int64
Damen-Brown 2017 5 48    76356
Name: 5, dtype: int64
Damen-Brown 2018 5 48    75582
Name: 5, dtype: int64
Damen-Brown 2019 5 48    75260
Name: 5, dtype: int64
Damen-Brown 2013 6 47    66415
Name: 6, dtype: int64
Damen-Brown 2014 6 47    67869
Name: 6, dtype: int64
Damen-Brown 2015 6 48    71182
Name: 6, dtype: int64
Damen-Brown 2016 6 48    78647
Name: 6, dtype: int64
Damen-Brown 2017 6 48    76756
Name: 6, dtype: int64
Damen-Brown 2018 6 48    71889
Name: 6, dtype: int64
Damen-Brown 2019 6 48    70633
Name: 6, dtype: int64
Damen-Brown 2013 7 47    66927
Name: 7, dtype: int64
Damen-Brown 2014 7 47    67618
Name: 7, dtype: int64
Damen-Brown 2015 7 48    71594
Name: 7, dtype: int64
Damen-Brown 2016 7 48    72381
Name: 7, dtype: int64
Damen-Brown 2017 7 48    69614
Name: 7, dtype: int64
Damen-Brown 2018 7 48    0
Name: 7, dtype: int64
Damen-Brown 2019 7 48    68941
Name: 7, dtype: int64
Damen-Brown 2013 8 47    67955
Name: 8, dtype: int64
Damen-Brown 2014 8 47    66134
Name: 8, dtype: int64
Damen-Brown 2015 8 48    68291
Name: 8, dtype: int64
Damen-Brown 2016 8 48    75329
Name: 8, dtype: int64
Damen-Brown 2017 8 48    74055
Name: 8, dtype: int64
Damen-Brown 2018 8 48    0
Name: 8, dtype: int64
Damen-Brown 2019 8 48    70620
Name: 8, dtype: int64
Damen-Brown 2013 9 47    67844
Name: 9, dtype: int64
Damen-Brown 2014 9 47    69768
Name: 9, dtype: int64
Damen-Brown 2015 9 48    73452
Name: 9, dtype: int64
Damen-Brown 2016 9 48    78123
Name: 9, dtype: int64
Damen-Brown 2017 9 48    74929
Name: 9, dtype: int64
Damen-Brown 2018 9 48    0
Name: 9, dtype: int64
Damen-Brown 2019 9 48    72015
Name: 9, dtype: int64
Damen-Brown 2013 10 47    74283
Name: 10, dtype: int64
Damen-Brown 2014 10 47    74473
Name: 10, dtype: int64
Damen-Brown 2015 10 48    79225
Name: 10, dtype: int64
Damen-Brown 2016 10 48    81367
Name: 10, dtype: int64
Damen-Brown 2017 10 48    78864
Name: 10, dtype: int64
Damen-Brown 2018 10 48    0
Name: 10, dtype: int64
Damen-Brown 2019 10 48    77668
Name: 10, dtype: int64
Damen-Brown 2013 11 47    65082
Name: 11, dtype: int64
Damen-Brown 2014 11 47    62418
Name: 11, dtype: int64
Damen-Brown 2015 11 48    69822
Name: 11, dtype: int64
Damen-Brown 2016 11 48    74955
Name: 11, dtype: int64
Damen-Brown 2017 11 48    70663
Name: 11, dtype: int64
Damen-Brown 2018 11 48    0
Name: 11, dtype: int64
Damen-Brown 2019 11 48    66678
Name: 11, dtype: int64
Damen-Brown 2013 12 47    62084
Name: 12, dtype: int64
Damen-Brown 2014 12 47    63806
Name: 12, dtype: int64
Damen-Brown 2015 12 48    69251
Name: 12, dtype: int64
Damen-Brown 2016 12 48    67783
Name: 12, dtype: int64
Damen-Brown 2017 12 48    64294
Name: 12, dtype: int64
Damen-Brown 2018 12 48    0
Name: 12, dtype: int64
Damen-Brown 2019 12 48    63376
Name: 12, dtype: int64
Damen-Cermak 2013 1 48    35122
Name: 1, dtype: int64
Damen-Cermak 2014 1 48    35148
Name: 1, dtype: int64
Damen-Cermak 2015 1 49    37067
Name: 1, dtype: int64
Damen-Cermak 2016 1 49    36401
Name: 1, dtype: int64
Damen-Cermak 2017 1 49    36567
Name: 1, dtype: int64
Damen-Cermak 2018 1 49    34772
Name: 1, dtype: int64
Damen-Cermak 2019 1 49    33289
Name: 1, dtype: int64
Damen-Cermak 2013 2 48    34558
Name: 2, dtype: int64
Damen-Cermak 2014 2 48    36314
Name: 2, dtype: int64
Damen-Cermak 2015 2 49    37035
Name: 2, dtype: int64
Damen-Cermak 2016 2 49    37969
Name: 2, dtype: int64
Damen-Cermak 2017 2 49    37081
Name: 2, dtype: int64
Damen-Cermak 2018 2 49    33525
Name: 2, dtype: int64
Damen-Cermak 2019 2 49    34137
Name: 2, dtype: int64
Damen-Cermak 2013 3 48    35950
Name: 3, dtype: int64
Damen-Cermak 2014 3 48    40894
Name: 3, dtype: int64
Damen-Cermak 2015 3 49    42905
Name: 3, dtype: int64
Damen-Cermak 2016 3 49    41031
Name: 3, dtype: int64
Damen-Cermak 2017 3 49    42294
Name: 3, dtype: int64
Damen-Cermak 2018 3 49    39209
Name: 3, dtype: int64
Damen-Cermak 2019 3 49    37988
Name: 3, dtype: int64
Damen-Cermak 2013 4 48    38847
Name: 4, dtype: int64
Damen-Cermak 2014 4 48    40236
Name: 4, dtype: int64
Damen-Cermak 2015 4 49    41602
Name: 4, dtype: int64
Damen-Cermak 2016 4 49    38939
Name: 4, dtype: int64
Damen-Cermak 2017 4 49    39007
Name: 4, dtype: int64
Damen-Cermak 2018 4 49    37316
Name: 4, dtype: int64
Damen-Cermak 2019 4 49    38143
Name: 4, dtype: int64
Damen-Cermak 2013 5 48    38676
Name: 5, dtype: int64
Damen-Cermak 2014 5 48    39142
Name: 5, dtype: int64
Damen-Cermak 2015 5 49    41053
Name: 5, dtype: int64
Damen-Cermak 2016 5 49    40897
Name: 5, dtype: int64
Damen-Cermak 2017 5 49    42231
Name: 5, dtype: int64
Damen-Cermak 2018 5 49    40294
Name: 5, dtype: int64
Damen-Cermak 2019 5 49    41150
Name: 5, dtype: int64
Damen-Cermak 2013 6 48    36735
Name: 6, dtype: int64
Damen-Cermak 2014 6 48    39684
Name: 6, dtype: int64
Damen-Cermak 2015 6 49    40587
Name: 6, dtype: int64
Damen-Cermak 2016 6 49    40060
Name: 6, dtype: int64
Damen-Cermak 2017 6 49    39485
Name: 6, dtype: int64
Damen-Cermak 2018 6 49    38618
Name: 6, dtype: int64
Damen-Cermak 2019 6 49    38425
Name: 6, dtype: int64
Damen-Cermak 2013 7 48    38850
Name: 7, dtype: int64
Damen-Cermak 2014 7 48    40946
Name: 7, dtype: int64
Damen-Cermak 2015 7 49    41987
Name: 7, dtype: int64
Damen-Cermak 2016 7 49    40035
Name: 7, dtype: int64
Damen-Cermak 2017 7 49    38044
Name: 7, dtype: int64
Damen-Cermak 2018 7 49    39028
Name: 7, dtype: int64
Damen-Cermak 2019 7 49    40037
Name: 7, dtype: int64
Damen-Cermak 2013 8 48    39834
Name: 8, dtype: int64
Damen-Cermak 2014 8 48    41418
Name: 8, dtype: int64
Damen-Cermak 2015 8 49    41091
Name: 8, dtype: int64
Damen-Cermak 2016 8 49    40566
Name: 8, dtype: int64
Damen-Cermak 2017 8 49    40251
Name: 8, dtype: int64
Damen-Cermak 2018 8 49    0
Name: 8, dtype: int64
Damen-Cermak 2019 8 49    40449
Name: 8, dtype: int64
Damen-Cermak 2013 9 48    40238
Name: 9, dtype: int64
Damen-Cermak 2014 9 48    44660
Name: 9, dtype: int64
Damen-Cermak 2015 9 49    46576
Name: 9, dtype: int64
Damen-Cermak 2016 9 49    44064
Name: 9, dtype: int64
Damen-Cermak 2017 9 49    41769
Name: 9, dtype: int64
Damen-Cermak 2018 9 49    0
Name: 9, dtype: int64
Damen-Cermak 2019 9 49    41266
Name: 9, dtype: int64
Damen-Cermak 2013 10 48    43395
Name: 10, dtype: int64
Damen-Cermak 2014 10 48    48912
Name: 10, dtype: int64
Damen-Cermak 2015 10 49    47105
Name: 10, dtype: int64
Damen-Cermak 2016 10 49    45218
Name: 10, dtype: int64
Damen-Cermak 2017 10 49    43561
Name: 10, dtype: int64
Damen-Cermak 2018 10 49    0
Name: 10, dtype: int64

Damen-Cermak 2019 10 49    44940
Name: 10, dtype: int64
Damen-Cermak 2013 11 48    38849
Name: 11, dtype: int64
Damen-Cermak 2014 11 48    40773
Name: 11, dtype: int64
Damen-Cermak 2015 11 49    41108
Name: 11, dtype: int64
Damen-Cermak 2016 11 49    42374
Name: 11, dtype: int64
Damen-Cermak 2017 11 49    39418
Name: 11, dtype: int64
Damen-Cermak 2018 11 49    0
Name: 11, dtype: int64
Damen-Cermak 2019 11 49    38522
Name: 11, dtype: int64
Damen-Cermak 2013 12 48    35462
Name: 12, dtype: int64
Damen-Cermak 2014 12 48    39083
Name: 12, dtype: int64
Damen-Cermak 2015 12 49    39018
Name: 12, dtype: int64
Damen-Cermak 2016 12 49    37192
Name: 12, dtype: int64
Damen-Cermak 2017 12 49    34850
Name: 12, dtype: int64
Damen-Cermak 2018 12 49    0
Name: 12, dtype: int64
Damen-Cermak 2019 12 49    34931
Name: 12, dtype: int64
Damen/Milwaukee 2013 1 49    161804
Name: 1, dtype: int64
Damen/Milwaukee 2014 1 49    159647
Name: 1, dtype: int64
Damen/Milwaukee 2015 1 50    148672
Name: 1, dtype: int64
Damen/Milwaukee 2016 1 50    171503
Name: 1, dtype: int64
Damen/Milwaukee 2017 1 50    165831
Name: 1, dtype: int64
Damen/Milwaukee 2018 1 50    155944
Name: 1, dtype: int64
Damen/Milwaukee 2019 1 50    144877
Name: 1, dtype: int64
Damen/Milwaukee 2013 2 49    154249
Name: 2, dtype: int64
Damen/Milwaukee 2014 2 49    161673
Name: 2, dtype: int64
Damen/Milwaukee 2015 2 50    146707
Name: 2, dtype: int64
Damen/Milwaukee 2016 2 50    171628
Name: 2, dtype: int64
Damen/Milwaukee 2017 2 50    159497
Name: 2, dtype: int64
Damen/Milwaukee 2018 2 50    146958
Name: 2, dtype: int64
Damen/Milwaukee 2019 2 50    145736
Name: 2, dtype: int64
Damen/Milwaukee 2013 3 49    181902
Name: 3, dtype: int64
Damen/Milwaukee 2014 3 49    188167
Name: 3, dtype: int64
Damen/Milwaukee 2015 3 50    179928
Name: 3, dtype: int64
Damen/Milwaukee 2016 3 50    196383
Name: 3, dtype: int64
Damen/Milwaukee 2017 3 50    186652
Name: 3, dtype: int64
Damen/Milwaukee 2018 3 50    178852
Name: 3, dtype: int64
Damen/Milwaukee 2019 3 50    168303
Name: 3, dtype: int64
Damen/Milwaukee 2013 4 49    180082
Name: 4, dtype: int64
Damen/Milwaukee 2014 4 49    241759
Name: 4, dtype: int64
Damen/Milwaukee 2015 4 50    178751
Name: 4, dtype: int64
Damen/Milwaukee 2016 4 50    183506
Name: 4, dtype: int64
Damen/Milwaukee 2017 4 50    175066
Name: 4, dtype: int64
Damen/Milwaukee 2018 4 50    164826
Name: 4, dtype: int64
Damen/Milwaukee 2019 4 50    165443
Name: 4, dtype: int64
Damen/Milwaukee 2013 5 49    186296
Name: 5, dtype: int64
Damen/Milwaukee 2014 5 49    188346
Name: 5, dtype: int64
Damen/Milwaukee 2015 5 50    185755
Name: 5, dtype: int64
Damen/Milwaukee 2016 5 50    190470
Name: 5, dtype: int64
Damen/Milwaukee 2017 5 50    188327
Name: 5, dtype: int64
Damen/Milwaukee 2018 5 50    179077
Name: 5, dtype: int64
Damen/Milwaukee 2019 5 50    168996
Name: 5, dtype: int64
Damen/Milwaukee 2013 6 49    188738
Name: 6, dtype: int64
Damen/Milwaukee 2014 6 49    186117
Name: 6, dtype: int64
Damen/Milwaukee 2015 6 50    200548
Name: 6, dtype: int64
Damen/Milwaukee 2016 6 50    201031
Name: 6, dtype: int64
Damen/Milwaukee 2017 6 50    197609
Name: 6, dtype: int64
Damen/Milwaukee 2018 6 50    181765
Name: 6, dtype: int64
Damen/Milwaukee 2019 6 50    175584
Name: 6, dtype: int64
Damen/Milwaukee 2013 7 49    203529
Name: 7, dtype: int64
Damen/Milwaukee 2014 7 49    200204
Name: 7, dtype: int64
Damen/Milwaukee 2015 7 50    219039
Name: 7, dtype: int64
Damen/Milwaukee 2016 7 50    203022
Name: 7, dtype: int64
Damen/Milwaukee 2017 7 50    190529
Name: 7, dtype: int64
Damen/Milwaukee 2018 7 50    185034
Name: 7, dtype: int64
Damen/Milwaukee 2019 7 50    182878
Name: 7, dtype: int64
Damen/Milwaukee 2013 8 49    198878
Name: 8, dtype: int64
Damen/Milwaukee 2014 8 49    183209
Name: 8, dtype: int64
Damen/Milwaukee 2015 8 50    204132
Name: 8, dtype: int64
Damen/Milwaukee 2016 8 50    192661
Name: 8, dtype: int64
Damen/Milwaukee 2017 8 50    196199
Name: 8, dtype: int64
Damen/Milwaukee 2018 8 50    0
Name: 8, dtype: int64
Damen/Milwaukee 2019 8 50    181335
Name: 8, dtype: int64
Damen/Milwaukee 2013 9 49    188214
Name: 9, dtype: int64
Damen/Milwaukee 2014 9 49    190603
Name: 9, dtype: int64
Damen/Milwaukee 2015 9 50    201108
Name: 9, dtype: int64
Damen/Milwaukee 2016 9 50    186026
Name: 9, dtype: int64
Damen/Milwaukee 2017 9 50    186512
Name: 9, dtype: int64
Damen/Milwaukee 2018 9 50    0
Name: 9, dtype: int64
Damen/Milwaukee 2019 9 50    175307
Name: 9, dtype: int64
Damen/Milwaukee 2013 10 49    199911
Name: 10, dtype: int64
Damen/Milwaukee 2014 10 49    120276
Name: 10, dtype: int64
Damen/Milwaukee 2015 10 50    211327
Name: 10, dtype: int64
Damen/Milwaukee 2016 10 50    195984
Name: 10, dtype: int64
Damen/Milwaukee 2017 10 50    190887
Name: 10, dtype: int64
Damen/Milwaukee 2018 10 50    0
Name: 10, dtype: int64
Damen/Milwaukee 2019 10 50    204424
Name: 10, dtype: int64
Damen/Milwaukee 2013 11 49    174015
Name: 11, dtype: int64
Damen/Milwaukee 2014 11 49    0
Name: 11, dtype: int64
Damen/Milwaukee 2015 11 50    180468
Name: 11, dtype: int64
Damen/Milwaukee 2016 11 50    175803
Name: 11, dtype: int64
Damen/Milwaukee 2017 11 50    169020
Name: 11, dtype: int64
Damen/Milwaukee 2018 11 50    0
Name: 11, dtype: int64
Damen/Milwaukee 2019 11 50    163696
Name: 11, dtype: int64
Damen/Milwaukee 2013 12 49    159078
Name: 12, dtype: int64
Damen/Milwaukee 2014 12 49    36880
Name: 12, dtype: int64
Damen/Milwaukee 2015 12 50    176630
Name: 12, dtype: int64
Damen/Milwaukee 2016 12 50    158361
Name: 12, dtype: int64
Damen/Milwaukee 2017 12 50    149556
Name: 12, dtype: int64
Damen/Milwaukee 2018 12 50    0
Name: 12, dtype: int64
Damen/Milwaukee 2019 12 50    146571
Name: 12, dtype: int64
Davis 2013 1 50    99979
Name: 1, dtype: int64
Davis 2014 1 50    95959
Name: 1, dtype: int64
Davis 2015 1 51    97771
Name: 1, dtype: int64
Davis 2016 1 51    93948
Name: 1, dtype: int64
Davis 2017 1 51    93262
Name: 1, dtype: int64
Davis 2018 1 51    89673
Name: 1, dtype: int64
Davis 2019 1 51    82929
Name: 1, dtype: int64
Davis 2013 2 50    95674
Name: 2, dtype: int64
Davis 2014 2 50    96075
Name: 2, dtype: int64
Davis 2015 2 51    92830
Name: 2, dtype: int64
Davis 2016 2 51    95040
Name: 2, dtype: int64
Davis 2017 2 51    88168
Name: 2, dtype: int64
Davis 2018 2 51    88892
Name: 2, dtype: int64
Davis 2019 2 51    82477
Name: 2, dtype: int64
Davis 2013 3 50    99038
Name: 3, dtype: int64
Davis 2014 3 50    103367
Name: 3, dtype: int64
Davis 2015 3 51    103247
Name: 3, dtype: int64
Davis 2016 3 51    100942
Name: 3, dtype: int64
Davis 2017 3 51    98002
Name: 3, dtype: int64
Davis 2018 3 51    98435
Name: 3, dtype: int64
Davis 2019 3 51    89128
Name: 3, dtype: int64
Davis 2013 4 50    105171
Name: 4, dtype: int64
Davis 2014 4 50    107297
Name: 4, dtype: int64
Davis 2015 4 51    104626
Name: 4, dtype: int64
Davis 2016 4 51    100220
Name: 4, dtype: int64
Davis 2017 4 51    95944
Name: 4, dtype: int64
Davis 2018 4 51    97293
Name: 4, dtype: int64
Davis 2019 4 51    93012
Name: 4, dtype: int64
Davis 2013 5 50    108285
Name: 5, dtype: int64
Davis 2014 5 50    109638
Name: 5, dtype: int64
Davis 2015 5 51    106446
Name: 5, dtype: int64
Davis 2016 5 51    103241
Name: 5, dtype: int64
Davis 2017 5 51    101565
Name: 5, dtype: int64
Davis 2018 5 51    102257
Name: 5, dtype: int64
Davis 2019 5 51    97840
Name: 5, dtype: int64
Davis 2013 6 50    106918
Name: 6, dtype: int64
Davis 2014 6 50    107700
Name: 6, dtype: int64
Davis 2015 6 51    110917
Name: 6, dtype: int64
Davis 2016 6 51    105891
Name: 6, dtype: int64
Davis 2017 6 51    104835
Name: 6, dtype: int64
Davis 2018 6 51    102435
Name: 6, dtype: int64
Davis 2019 6 51    95275
Name: 6, dtype: int64
Davis 2013 7 50    109420
Name: 7, dtype: int64
Davis 2014 7 50    111648
Name: 7, dtype: int64
Davis 2015 7 51    114944
Name: 7, dtype: int64
Davis 2016 7 51    105243
Name: 7, dtype: int64
Davis 2017 7 51    101357
Name: 7, dtype: int64
Davis 2018 7 51    103452
Name: 7, dtype: int64
Davis 2019 7 51    96608
Name: 7, dtype: int64
Davis 2013 8 50    105270
Name: 8, dtype: int64
Davis 2014 8 50    107612
Name: 8, dtype: int64
Davis 2015 8 51    106930
Name: 8, dtype: int64
Davis 2016 8 51    103679
Name: 8, dtype: int64
Davis 2017 8 51    103343
Name: 8, dtype: int64
Davis 2018 8 51    0
Name: 8, dtype: int64
Davis 2019 8 51    95207
Name: 8, dtype: int64
Davis 2013 9 50    99774
Name: 9, dtype: int64
Davis 2014 9 50    106953
Name: 9, dtype: int64
Davis 2015 9 51    106599
Name: 9, dtype: int64
Davis 2016 9 51    102546
Name: 9, dtype: int64
Davis 2017 9 51    98172
Name: 9, dtype: int64
Davis 2018 9 51    0
Name: 9, dtype: int64
Davis 2019 9 51    91014
Name: 9, dtype: int64
Davis 2013 10 50    113949
Name: 10, dtype: int64
Davis 2014 10 50    118334
Name: 10, dtype: int64
Davis 2015 10 51    114307
Name: 10, dtype: int64
Davis 2016 10 51    108464
Name: 10, dtype: int64
Davis 2017 10 51    104928
Name: 10, dtype: int64
Davis 2018 10 51    0
Name: 10, dtype: int64
Davis 2019 10 51    101914
Name: 10, dtype: int64
Davis 2013 11 50    102624
Name: 11, dtype: int64
Davis 2014 11 50    99703
Name: 11, dtype: int64
Davis 2015 11 51    96856
Name: 11, dtype: int64
Davis 2016 11 51    100565
Name: 11, dtype: int64
Davis 2017 11 51    93531
Name: 11, dtype: int64
Davis 2018 11 51    0
Name: 11, dtype: int64
Davis 2019 11 51    88214
Name: 11, dtype: int64

Davis 2013 12 50    90086
Name: 12, dtype: int64
Davis 2014 12 50    93913
Name: 12, dtype: int64
Davis 2015 12 51    91688
Name: 12, dtype: int64
Davis 2016 12 51    82791
Name: 12, dtype: int64
Davis 2017 12 51    81359
Name: 12, dtype: int64
Davis 2018 12 51    0
Name: 12, dtype: int64
Davis 2019 12 51    77822
Name: 12, dtype: int64
Dempster 2013 1 51    21284
Name: 1, dtype: int64
Dempster 2014 1 51    23846
Name: 1, dtype: int64
Dempster 2015 1 52    23041
Name: 1, dtype: int64
Dempster 2016 1 52    22325
Name: 1, dtype: int64
Dempster 2017 1 52    22382
Name: 1, dtype: int64
Dempster 2018 1 52    21254
Name: 1, dtype: int64
Dempster 2019 1 52    19350
Name: 1, dtype: int64
Dempster 2013 2 51    20583
Name: 2, dtype: int64
Dempster 2014 2 51    22995
Name: 2, dtype: int64
Dempster 2015 2 52    21924
Name: 2, dtype: int64
Dempster 2016 2 52    22016
Name: 2, dtype: int64
Dempster 2017 2 52    20738
Name: 2, dtype: int64
Dempster 2018 2 52    20374
Name: 2, dtype: int64
Dempster 2019 2 52    19219
Name: 2, dtype: int64
Dempster 2013 3 51    22175
Name: 3, dtype: int64
Dempster 2014 3 51    25751
Name: 3, dtype: int64
Dempster 2015 3 52    24436
Name: 3, dtype: int64
Dempster 2016 3 52    23332
Name: 3, dtype: int64
Dempster 2017 3 52    22945
Name: 3, dtype: int64
Dempster 2018 3 52    22803
Name: 3, dtype: int64
Dempster 2019 3 52    21417
Name: 3, dtype: int64
Dempster 2013 4 51    23244
Name: 4, dtype: int64
Dempster 2014 4 51    25100
Name: 4, dtype: int64
Dempster 2015 4 52    24126
Name: 4, dtype: int64
Dempster 2016 4 52    22954
Name: 4, dtype: int64
Dempster 2017 4 52    22712
Name: 4, dtype: int64
Dempster 2018 4 52    22208
Name: 4, dtype: int64
Dempster 2019 4 52    21783
Name: 4, dtype: int64
Dempster 2013 5 51    24072
Name: 5, dtype: int64
Dempster 2014 5 51    26960
Name: 5, dtype: int64
Dempster 2015 5 52    25597
Name: 5, dtype: int64
Dempster 2016 5 52    23703
Name: 5, dtype: int64
Dempster 2017 5 52    23635
Name: 5, dtype: int64
Dempster 2018 5 52    23314
Name: 5, dtype: int64
Dempster 2019 5 52    22958
Name: 5, dtype: int64
Dempster 2013 6 51    24353
Name: 6, dtype: int64
Dempster 2014 6 51    26887
Name: 6, dtype: int64
Dempster 2015 6 52    26847
Name: 6, dtype: int64
Dempster 2016 6 52    25224
Name: 6, dtype: int64
Dempster 2017 6 52    25802
Name: 6, dtype: int64
Dempster 2018 6 52    24868
Name: 6, dtype: int64
Dempster 2019 6 52    23357
Name: 6, dtype: int64
Dempster 2013 7 51    25215
Name: 7, dtype: int64
Dempster 2014 7 51    27295
Name: 7, dtype: int64
Dempster 2015 7 52    27861
Name: 7, dtype: int64
Dempster 2016 7 52    25735
Name: 7, dtype: int64
Dempster 2017 7 52    25120
Name: 7, dtype: int64
Dempster 2018 7 52    24694
Name: 7, dtype: int64
Dempster 2019 7 52    23496
Name: 7, dtype: int64
Dempster 2013 8 51    24678
Name: 8, dtype: int64
Dempster 2014 8 51    25632
Name: 8, dtype: int64
Dempster 2015 8 52    26257
Name: 8, dtype: int64
Dempster 2016 8 52    24457
Name: 8, dtype: int64
Dempster 2017 8 52    25608
Name: 8, dtype: int64
Dempster 2018 8 52    0
Name: 8, dtype: int64
Dempster 2019 8 52    23690
Name: 8, dtype: int64
Dempster 2013 9 51    24242
Name: 9, dtype: int64
Dempster 2014 9 51    26085
Name: 9, dtype: int64
Dempster 2015 9 52    26404
Name: 9, dtype: int64
Dempster 2016 9 52    24719
Name: 9, dtype: int64
Dempster 2017 9 52    23494
Name: 9, dtype: int64
Dempster 2018 9 52    0
Name: 9, dtype: int64
Dempster 2019 9 52    21118
Name: 9, dtype: int64
Dempster 2013 10 51    26987
Name: 10, dtype: int64
Dempster 2014 10 51    26847
Name: 10, dtype: int64
Dempster 2015 10 52    27215
Name: 10, dtype: int64
Dempster 2016 10 52    26177
Name: 10, dtype: int64
Dempster 2017 10 52    24744
Name: 10, dtype: int64
Dempster 2018 10 52    0
Name: 10, dtype: int64
Dempster 2019 10 52    23150
Name: 10, dtype: int64
Dempster 2013 11 51    24637
Name: 11, dtype: int64
Dempster 2014 11 51    23593
Name: 11, dtype: int64
Dempster 2015 11 52    23786
Name: 11, dtype: int64
Dempster 2016 11 52    23840
Name: 11, dtype: int64
Dempster 2017 11 52    22490
Name: 11, dtype: int64
Dempster 2018 11 52    0
Name: 11, dtype: int64
Dempster 2019 11 52    20837
Name: 11, dtype: int64
Dempster 2013 12 51    22908
Name: 12, dtype: int64
Dempster 2014 12 51    22808
Name: 12, dtype: int64
Dempster 2015 12 52    21923
Name: 12, dtype: int64
Dempster 2016 12 52    20744
Name: 12, dtype: int64
Dempster 2017 12 52    19938
Name: 12, dtype: int64
Dempster 2018 12 52    0
Name: 12, dtype: int64
Dempster 2019 12 52    18559
Name: 12, dtype: int64
Dempster-Skokie 2013 1 52    51846
Name: 1, dtype: int64
Dempster-Skokie 2014 1 52    46093
Name: 1, dtype: int64
Dempster-Skokie 2015 1 53    48481
Name: 1, dtype: int64
Dempster-Skokie 2016 1 53    39312
Name: 1, dtype: int64
Dempster-Skokie 2017 1 53    42625
Name: 1, dtype: int64
Dempster-Skokie 2018 1 53    41562
Name: 1, dtype: int64
Dempster-Skokie 2019 1 53    38310
Name: 1, dtype: int64
Dempster-Skokie 2013 2 52    49118
Name: 2, dtype: int64
Dempster-Skokie 2014 2 52    46449
Name: 2, dtype: int64
Dempster-Skokie 2015 2 53    45380
Name: 2, dtype: int64
Dempster-Skokie 2016 2 53    40747
Name: 2, dtype: int64
Dempster-Skokie 2017 2 53    41703
Name: 2, dtype: int64
Dempster-Skokie 2018 2 53    39611
Name: 2, dtype: int64
Dempster-Skokie 2019 2 53    39370
Name: 2, dtype: int64
Dempster-Skokie 2013 3 52    52506
Name: 3, dtype: int64
Dempster-Skokie 2014 3 52    52929
Name: 3, dtype: int64
Dempster-Skokie 2015 3 53    53240
Name: 3, dtype: int64
Dempster-Skokie 2016 3 53    45637
Name: 3, dtype: int64
Dempster-Skokie 2017 3 53    46894
Name: 3, dtype: int64
Dempster-Skokie 2018 3 53    45292
Name: 3, dtype: int64
Dempster-Skokie 2019 3 53    42065
Name: 3, dtype: int64
Dempster-Skokie 2013 4 52    58240
Name: 4, dtype: int64
Dempster-Skokie 2014 4 52    58811
Name: 4, dtype: int64
Dempster-Skokie 2015 4 53    56273
Name: 4, dtype: int64
Dempster-Skokie 2016 4 53    46901
Name: 4, dtype: int64
Dempster-Skokie 2017 4 53    49392
Name: 4, dtype: int64
Dempster-Skokie 2018 4 53    48777
Name: 4, dtype: int64
Dempster-Skokie 2019 4 53    47632
Name: 4, dtype: int64
Dempster-Skokie 2013 5 52    61802
Name: 5, dtype: int64
Dempster-Skokie 2014 5 52    58101
Name: 5, dtype: int64
Dempster-Skokie 2015 5 53    32406
Name: 5, dtype: int64
Dempster-Skokie 2016 5 53    52542
Name: 5, dtype: int64
Dempster-Skokie 2017 5 53    54362
Name: 5, dtype: int64
Dempster-Skokie 2018 5 53    52884
Name: 5, dtype: int64
Dempster-Skokie 2019 5 53    51158
Name: 5, dtype: int64
Dempster-Skokie 2013 6 52    62841
Name: 6, dtype: int64
Dempster-Skokie 2014 6 52    63912
Name: 6, dtype: int64
Dempster-Skokie 2015 6 53    549
Name: 6, dtype: int64
Dempster-Skokie 2016 6 53    55804
Name: 6, dtype: int64
Dempster-Skokie 2017 6 53    59617
Name: 6, dtype: int64
Dempster-Skokie 2018 6 53    53455
Name: 6, dtype: int64
Dempster-Skokie 2019 6 53    54937
Name: 6, dtype: int64
Dempster-Skokie 2013 7 52    66663
Name: 7, dtype: int64
Dempster-Skokie 2014 7 52    67115
Name: 7, dtype: int64
Dempster-Skokie 2015 7 53    0
Name: 7, dtype: int64
Dempster-Skokie 2016 7 53    57959
Name: 7, dtype: int64
Dempster-Skokie 2017 7 53    58460
Name: 7, dtype: int64
Dempster-Skokie 2018 7 53    59156
Name: 7, dtype: int64
Dempster-Skokie 2019 7 53    50750
Name: 7, dtype: int64
Dempster-Skokie 2013 8 52    66549
Name: 8, dtype: int64
Dempster-Skokie 2014 8 52    63092
Name: 8, dtype: int64
Dempster-Skokie 2015 8 53    0
Name: 8, dtype: int64
Dempster-Skokie 2016 8 53    59658
Name: 8, dtype: int64
Dempster-Skokie 2017 8 53    62113
Name: 8, dtype: int64
Dempster-Skokie 2018 8 53    0
Name: 8, dtype: int64
Dempster-Skokie 2019 8 53    54826
Name: 8, dtype: int64
Dempster-Skokie 2013 9 52    61493
Name: 9, dtype: int64
Dempster-Skokie 2014 9 52    63289
Name: 9, dtype: int64
Dempster-Skokie 2015 9 53    0
Name: 9, dtype: int64
Dempster-Skokie 2016 9 53    57138
Name: 9, dtype: int64
Dempster-Skokie 2017 9 53    56955
Name: 9, dtype: int64
Dempster-Skokie 2018 9 53    0
Name: 9, dtype: int64
Dempster-Skokie 2019 9 53    49998
Name: 9, dtype: int64
Dempster-Skokie 2013 10 52    63240
Name: 10, dtype: int64
Dempster-Skokie 2014 10 52    62309
Name: 10, dtype: int64
Dempster-Skokie 2015 10 53    2085
Name: 10, dtype: int64
Dempster-Skokie 2016 10 53    59028
Name: 10, dtype: int64
Dempster-Skokie 2017 10 53    56515
Name: 10, dtype: int64
Dempster-Skokie 2018 10 53    0
Name: 10, dtype: int64
Dempster-Skokie 2019 10 53    48926
Name: 10, dtype: int64
Dempster-Skokie 2013 11 52    54029
Name: 11, dtype: int64
Dempster-Skokie 2014 11 52    51423
Name: 11, dtype: int64
Dempster-Skokie 2015 11 53    42242
Name: 11, dtype: int64
Dempster-Skokie 2016 11 53    51653
Name: 11, dtype: int64
Dempster-Skokie 2017 11 53    47075
Name: 11, dtype: int64
Dempster-Skokie 2018 11 53    0
Name: 11, dtype: int64
Dempster-Skokie 2019 11 53    40822
Name: 11, dtype: int64
Dempster-Skokie 2013 12 52    49115
Name: 12, dtype: int64
Dempster-Skokie 2014 12 52    51836
Name: 12, dtype: int64
Dempster-Skokie 2015 12 53    42863
Name: 12, dtype: int64
Dempster-Skokie 2016 12 53    41881
Name: 12, dtype: int64
Dempster-Skokie 2017 12 53    41684
Name: 12, dtype: int64
Dempster-Skokie 2018 12 53    0
Name: 12, dtype: int64
Dempster-Skokie 2019 12 53    38539
Name: 12, dtype: int64
Diversey 2013 1 53    146764
Name: 1, dtype: int64
Diversey 2014 1 53    145331
Name: 1, dtype: int64
Diversey 2015 1 54    137380
Name: 1, dtype: int64
Diversey 2016 1 54    138374
Name: 1, dtype: int64
Diversey 2017 1 54    136050
Name: 1, dtype: int64
Diversey 2018 1 54    137586
Name: 1, dtype: int64
Diversey 2019 1 54    127759
Name: 1, dtype: int64
Diversey 2013 2 53    138799
Name: 2, dtype: int64
Diversey 2014 2 53    142360
Name: 2, dtype: int64
Diversey 2015 2 54    130029
Name: 2, dtype: int64
Diversey 2016 2 54    138919
Name: 2, dtype: int64
Diversey 2017 2 54    127454
Name: 2, dtype: int64
Diversey 2018 2 54    126940
Name: 2, dtype: int64
Diversey 2019 2 54    126916
Name: 2, dtype: int64
Diversey 2013 3 53    142933
Name: 3, dtype: int64
Diversey 2014 3 53    159270
Name: 3, dtype: int64
Diversey 2015 3 54    145945
Name: 3, dtype: int64
Diversey 2016 3 54    151611
Name: 3, dtype: int64
Diversey 2017 3 54    145730
Name: 3, dtype: int64
Diversey 2018 3 54    145931
Name: 3, dtype: int64
Diversey 2019 3 54    138903
Name: 3, dtype: int64
Diversey 2013 4 53    149327
Name: 4, dtype: int64
Diversey 2014 4 53    155494
Name: 4, dtype: int64
Diversey 2015 4 54    141401
Name: 4, dtype: int64
Diversey 2016 4 54    147670
Name: 4, dtype: int64
Diversey 2017 4 54    134354
Name: 4, dtype: int64
Diversey 2018 4 54    136982
Name: 4, dtype: int64
Diversey 2019 4 54    135260
Name: 4, dtype: int64
Diversey 2013 5 53    146727
Name: 5, dtype: int64
Diversey 2014 5 53    155527
Name: 5, dtype: int64
Diversey 2015 5 54    140256
Name: 5, dtype: int64
Diversey 2016 5 54    149263
Name: 5, dtype: int64
Diversey 2017 5 54    144995
Name: 5, dtype: int64
Diversey 2018 5 54    145747
Name: 5, dtype: int64
Diversey 2019 5 54    143185
Name: 5, dtype: int64
Diversey 2013 6 53    159875
Name: 6, dtype: int64
Diversey 2014 6 53    157500
Name: 6, dtype: int64
Diversey 2015 6 54    156913
Name: 6, dtype: int64
Diversey 2016 6 54    158879
Name: 6, dtype: int64

Diversey 2017 6 54    153871
Name: 6, dtype: int64
Diversey 2018 6 54    150095
Name: 6, dtype: int64
Diversey 2019 6 54    143644
Name: 6, dtype: int64
Diversey 2013 7 53    158339
Name: 7, dtype: int64
Diversey 2014 7 53    150624
Name: 7, dtype: int64
Diversey 2015 7 54    151287
Name: 7, dtype: int64
Diversey 2016 7 54    147898
Name: 7, dtype: int64
Diversey 2017 7 54    137542
Name: 7, dtype: int64
Diversey 2018 7 54    0
Name: 7, dtype: int64
Diversey 2019 7 54    139615
Name: 7, dtype: int64
Diversey 2013 8 53    161647
Name: 8, dtype: int64
Diversey 2014 8 53    144393
Name: 8, dtype: int64
Diversey 2015 8 54    145287
Name: 8, dtype: int64
Diversey 2016 8 54    153000
Name: 8, dtype: int64
Diversey 2017 8 54    148835
Name: 8, dtype: int64
Diversey 2018 8 54    0
Name: 8, dtype: int64
Diversey 2019 8 54    144573
Name: 8, dtype: int64
Diversey 2013 9 53    153766
Name: 9, dtype: int64
Diversey 2014 9 53    151249
Name: 9, dtype: int64
Diversey 2015 9 54    145060
Name: 9, dtype: int64
Diversey 2016 9 54    149414
Name: 9, dtype: int64
Diversey 2017 9 54    144472
Name: 9, dtype: int64
Diversey 2018 9 54    0
Name: 9, dtype: int64
Diversey 2019 9 54    141270
Name: 9, dtype: int64
Diversey 2013 10 53    171979
Name: 10, dtype: int64
Diversey 2014 10 53    163464
Name: 10, dtype: int64
Diversey 2015 10 54    161577
Name: 10, dtype: int64
Diversey 2016 10 54    158714
Name: 10, dtype: int64
Diversey 2017 10 54    154785
Name: 10, dtype: int64
Diversey 2018 10 54    0
Name: 10, dtype: int64
Diversey 2019 10 54    159783
Name: 10, dtype: int64
Diversey 2013 11 53    147579
Name: 11, dtype: int64
Diversey 2014 11 53    132790
Name: 11, dtype: int64
Diversey 2015 11 54    137644
Name: 11, dtype: int64
Diversey 2016 11 54    141403
Name: 11, dtype: int64
Diversey 2017 11 54    134846
Name: 11, dtype: int64
Diversey 2018 11 54    0
Name: 11, dtype: int64
Diversey 2019 11 54    131373
Name: 11, dtype: int64
Diversey 2013 12 53    132185
Name: 12, dtype: int64
Diversey 2014 12 53    131096
Name: 12, dtype: int64
Diversey 2015 12 54    132416
Name: 12, dtype: int64
Diversey 2016 12 54    121715
Name: 12, dtype: int64
Diversey 2017 12 54    118390
Name: 12, dtype: int64
Diversey 2018 12 54    0
Name: 12, dtype: int64
Diversey 2019 12 54    118726
Name: 12, dtype: int64
Division/Milwaukee 2013 1 54    153520
Name: 1, dtype: int64
Division/Milwaukee 2014 1 54    155158
Name: 1, dtype: int64
Division/Milwaukee 2015 1 55    156904
Name: 1, dtype: int64
Division/Milwaukee 2016 1 55    153835
Name: 1, dtype: int64
Division/Milwaukee 2017 1 55    149777
Name: 1, dtype: int64
Division/Milwaukee 2018 1 55    146967
Name: 1, dtype: int64
Division/Milwaukee 2019 1 55    141985
Name: 1, dtype: int64
Division/Milwaukee 2013 2 54    146255
Name: 2, dtype: int64
Division/Milwaukee 2014 2 54    157236
Name: 2, dtype: int64
Division/Milwaukee 2015 2 55    152981
Name: 2, dtype: int64
Division/Milwaukee 2016 2 55    156232
Name: 2, dtype: int64
Division/Milwaukee 2017 2 55    143929
Name: 2, dtype: int64
Division/Milwaukee 2018 2 55    140879
Name: 2, dtype: int64
Division/Milwaukee 2019 2 55    142358
Name: 2, dtype: int64
Division/Milwaukee 2013 3 54    161933
Name: 3, dtype: int64
Division/Milwaukee 2014 3 54    171819
Name: 3, dtype: int64
Division/Milwaukee 2015 3 55    174637
Name: 3, dtype: int64
Division/Milwaukee 2016 3 55    171860
Name: 3, dtype: int64
Division/Milwaukee 2017 3 55    165352
Name: 3, dtype: int64
Division/Milwaukee 2018 3 55    161206
Name: 3, dtype: int64
Division/Milwaukee 2019 3 55    158897
Name: 3, dtype: int64
Division/Milwaukee 2013 4 54    161046
Name: 4, dtype: int64
Division/Milwaukee 2014 4 54    161191
Name: 4, dtype: int64
Division/Milwaukee 2015 4 55    166024
Name: 4, dtype: int64
Division/Milwaukee 2016 4 55    160086
Name: 4, dtype: int64
Division/Milwaukee 2017 4 55    150277
Name: 4, dtype: int64
Division/Milwaukee 2018 4 55    154027
Name: 4, dtype: int64
Division/Milwaukee 2019 4 55    156532
Name: 4, dtype: int64
Division/Milwaukee 2013 5 54    160649
Name: 5, dtype: int64
Division/Milwaukee 2014 5 54    166043
Name: 5, dtype: int64
Division/Milwaukee 2015 5 55    166667
Name: 5, dtype: int64
Division/Milwaukee 2016 5 55    163331
Name: 5, dtype: int64
Division/Milwaukee 2017 5 55    162660
Name: 5, dtype: int64
Division/Milwaukee 2018 5 55    163225
Name: 5, dtype: int64
Division/Milwaukee 2019 5 55    166418
Name: 5, dtype: int64
Division/Milwaukee 2013 6 54    154028
Name: 6, dtype: int64
Division/Milwaukee 2014 6 54    158681
Name: 6, dtype: int64
Division/Milwaukee 2015 6 55    169928
Name: 6, dtype: int64
Division/Milwaukee 2016 6 55    165528
Name: 6, dtype: int64
Division/Milwaukee 2017 6 55    163023
Name: 6, dtype: int64
Division/Milwaukee 2018 6 55    159507
Name: 6, dtype: int64
Division/Milwaukee 2019 6 55    158942
Name: 6, dtype: int64
Division/Milwaukee 2013 7 54    158993
Name: 7, dtype: int64
Division/Milwaukee 2014 7 54    162399
Name: 7, dtype: int64
Division/Milwaukee 2015 7 55    172863
Name: 7, dtype: int64
Division/Milwaukee 2016 7 55    160040
Name: 7, dtype: int64
Division/Milwaukee 2017 7 55    150480
Name: 7, dtype: int64
Division/Milwaukee 2018 7 55    154495
Name: 7, dtype: int64
Division/Milwaukee 2019 7 55    162056
Name: 7, dtype: int64
Division/Milwaukee 2013 8 54    161724
Name: 8, dtype: int64
Division/Milwaukee 2014 8 54    159772
Name: 8, dtype: int64
Division/Milwaukee 2015 8 55    165094
Name: 8, dtype: int64
Division/Milwaukee 2016 8 55    161212
Name: 8, dtype: int64
Division/Milwaukee 2017 8 55    164161
Name: 8, dtype: int64
Division/Milwaukee 2018 8 55    0
Name: 8, dtype: int64
Division/Milwaukee 2019 8 55    162411
Name: 8, dtype: int64
Division/Milwaukee 2013 9 54    167100
Name: 9, dtype: int64
Division/Milwaukee 2014 9 54    168725
Name: 9, dtype: int64
Division/Milwaukee 2015 9 55    173085
Name: 9, dtype: int64
Division/Milwaukee 2016 9 55    165314
Name: 9, dtype: int64
Division/Milwaukee 2017 9 55    162307
Name: 9, dtype: int64
Division/Milwaukee 2018 9 55    0
Name: 9, dtype: int64
Division/Milwaukee 2019 9 55    145067
Name: 9, dtype: int64
Division/Milwaukee 2013 10 54    178227
Name: 10, dtype: int64
Division/Milwaukee 2014 10 54    203489
Name: 10, dtype: int64
Division/Milwaukee 2015 10 55    182159
Name: 10, dtype: int64
Division/Milwaukee 2016 10 55    172226
Name: 10, dtype: int64
Division/Milwaukee 2017 10 55    169012
Name: 10, dtype: int64
Division/Milwaukee 2018 10 55    0
Name: 10, dtype: int64
Division/Milwaukee 2019 10 55    104031
Name: 10, dtype: int64
Division/Milwaukee 2013 11 54    158637
Name: 11, dtype: int64
Division/Milwaukee 2014 11 54    204619
Name: 11, dtype: int64
Division/Milwaukee 2015 11 55    156645
Name: 11, dtype: int64
Division/Milwaukee 2016 11 55    157266
Name: 11, dtype: int64
Division/Milwaukee 2017 11 55    153397
Name: 11, dtype: int64
Division/Milwaukee 2018 11 55    0
Name: 11, dtype: int64
Division/Milwaukee 2019 11 55    112400
Name: 11, dtype: int64
Division/Milwaukee 2013 12 54    151061
Name: 12, dtype: int64
Division/Milwaukee 2014 12 54    191177
Name: 12, dtype: int64
Division/Milwaukee 2015 12 55    154512
Name: 12, dtype: int64
Division/Milwaukee 2016 12 55    142400
Name: 12, dtype: int64
Division/Milwaukee 2017 12 55    137006
Name: 12, dtype: int64
Division/Milwaukee 2018 12 55    0
Name: 12, dtype: int64
Division/Milwaukee 2019 12 55    124746
Name: 12, dtype: int64
East 63rd-Cottage Grove 2013 1 55    33786
Name: 1, dtype: int64
East 63rd-Cottage Grove 2014 1 55    33745
Name: 1, dtype: int64
East 63rd-Cottage Grove 2015 1 56    30006
Name: 1, dtype: int64
East 63rd-Cottage Grove 2016 1 56    30337
Name: 1, dtype: int64
East 63rd-Cottage Grove 2017 1 56    28021
Name: 1, dtype: int64
East 63rd-Cottage Grove 2018 1 56    26343
Name: 1, dtype: int64
East 63rd-Cottage Grove 2019 1 56    21897
Name: 1, dtype: int64
East 63rd-Cottage Grove 2013 2 55    31804
Name: 2, dtype: int64
East 63rd-Cottage Grove 2014 2 55    34134
Name: 2, dtype: int64
East 63rd-Cottage Grove 2015 2 56    28732
Name: 2, dtype: int64
East 63rd-Cottage Grove 2016 2 56    29959
Name: 2, dtype: int64
East 63rd-Cottage Grove 2017 2 56    27748
Name: 2, dtype: int64
East 63rd-Cottage Grove 2018 2 56    24816
Name: 2, dtype: int64
East 63rd-Cottage Grove 2019 2 56    22250
Name: 2, dtype: int64
East 63rd-Cottage Grove 2013 3 55    34466
Name: 3, dtype: int64
East 63rd-Cottage Grove 2014 3 55    37805
Name: 3, dtype: int64
East 63rd-Cottage Grove 2015 3 56    33359
Name: 3, dtype: int64
East 63rd-Cottage Grove 2016 3 56    31535
Name: 3, dtype: int64
East 63rd-Cottage Grove 2017 3 56    30263
Name: 3, dtype: int64
East 63rd-Cottage Grove 2018 3 56    28748
Name: 3, dtype: int64
East 63rd-Cottage Grove 2019 3 56    24118
Name: 3, dtype: int64
East 63rd-Cottage Grove 2013 4 55    36373
Name: 4, dtype: int64
East 63rd-Cottage Grove 2014 4 55    37357
Name: 4, dtype: int64
East 63rd-Cottage Grove 2015 4 56    34754
Name: 4, dtype: int64
East 63rd-Cottage Grove 2016 4 56    29974
Name: 4, dtype: int64
East 63rd-Cottage Grove 2017 4 56    27942
Name: 4, dtype: int64
East 63rd-Cottage Grove 2018 4 56    26392
Name: 4, dtype: int64
East 63rd-Cottage Grove 2019 4 56    24243
Name: 4, dtype: int64
East 63rd-Cottage Grove 2013 5 55    48481
Name: 5, dtype: int64
East 63rd-Cottage Grove 2014 5 55    38231
Name: 5, dtype: int64
East 63rd-Cottage Grove 2015 5 56    35376
Name: 5, dtype: int64
East 63rd-Cottage Grove 2016 5 56    31626
Name: 5, dtype: int64
East 63rd-Cottage Grove 2017 5 56    30490
Name: 5, dtype: int64
East 63rd-Cottage Grove 2018 5 56    28252
Name: 5, dtype: int64
East 63rd-Cottage Grove 2019 5 56    26995
Name: 5, dtype: int64
East 63rd-Cottage Grove 2013 6 55    59009
Name: 6, dtype: int64
East 63rd-Cottage Grove 2014 6 55    36295
Name: 6, dtype: int64
East 63rd-Cottage Grove 2015 6 56    36634
Name: 6, dtype: int64
East 63rd-Cottage Grove 2016 6 56    32029
Name: 6, dtype: int64
East 63rd-Cottage Grove 2017 6 56    31220
Name: 6, dtype: int64
East 63rd-Cottage Grove 2018 6 56    28699
Name: 6, dtype: int64
East 63rd-Cottage Grove 2019 6 56    26218
Name: 6, dtype: int64
East 63rd-Cottage Grove 2013 7 55    63452
Name: 7, dtype: int64
East 63rd-Cottage Grove 2014 7 55    39253
Name: 7, dtype: int64
East 63rd-Cottage Grove 2015 7 56    39480
Name: 7, dtype: int64
East 63rd-Cottage Grove 2016 7 56    32082
Name: 7, dtype: int64
East 63rd-Cottage Grove 2017 7 56    31003
Name: 7, dtype: int64
East 63rd-Cottage Grove 2018 7 56    0
Name: 7, dtype: int64
East 63rd-Cottage Grove 2019 7 56    28799
Name: 7, dtype: int64
East 63rd-Cottage Grove 2013 8 55    64914
Name: 8, dtype: int64
East 63rd-Cottage Grove 2014 8 55    40226
Name: 8, dtype: int64
East 63rd-Cottage Grove 2015 8 56    36756
Name: 8, dtype: int64
East 63rd-Cottage Grove 2016 8 56    31634
Name: 8, dtype: int64
East 63rd-Cottage Grove 2017 8 56    32127
Name: 8, dtype: int64
East 63rd-Cottage Grove 2018 8 56    0
Name: 8, dtype: int64
East 63rd-Cottage Grove 2019 8 56    28573
Name: 8, dtype: int64
East 63rd-Cottage Grove 2013 9 55    62998
Name: 9, dtype: int64
East 63rd-Cottage Grove 2014 9 55    38665
Name: 9, dtype: int64
East 63rd-Cottage Grove 2015 9 56    36398
Name: 9, dtype: int64
East 63rd-Cottage Grove 2016 9 56    32258
Name: 9, dtype: int64
East 63rd-Cottage Grove 2017 9 56    30207
Name: 9, dtype: int64
East 63rd-Cottage Grove 2018 9 56    0
Name: 9, dtype: int64
East 63rd-Cottage Grove 2019 9 56    27410
Name: 9, dtype: int64
East 63rd-Cottage Grove 2013 10 55    61506
Name: 10, dtype: int64
East 63rd-Cottage Grove 2014 10 55    38879
Name: 10, dtype: int64
East 63rd-Cottage Grove 2015 10 56    37099
Name: 10, dtype: int64
East 63rd-Cottage Grove 2016 10 56    32801
Name: 10, dtype: int64
East 63rd-Cottage Grove 2017 10 56    31992
Name: 10, dtype: int64
East 63rd-Cottage Grove 2018 10 56    0
Name: 10, dtype: int64
East 63rd-Cottage Grove 2019 10 56    27925
Name: 10, dtype: int64
East 63rd-Cottage Grove 2013 11 55    41102
Name: 11, dtype: int64
East 63rd-Cottage Grove 2014 11 55    32420
Name: 11, dtype: int64
East 63rd-Cottage Grove 2015 11 56    33697
Name: 11, dtype: int64
East 63rd-Cottage Grove 2016 11 56    30658
Name: 11, dtype: int64
East 63rd-Cottage Grove 2017 11 56    29516
Name: 11, dtype: int64
East 63rd-Cottage Grove 2018 11 56    0
Name: 11, dtype: int64
East 63rd-Cottage Grove 2019 11 56    22746
Name: 11, dtype: int64
East 63rd-Cottage Grove 2013 12 55    36403
Name: 12, dtype: int64
East 63rd-Cottage Grove 2014 12 55    31911
Name: 12, dtype: int64
East 63rd-Cottage Grove 2015 12 56    33052
Name: 12, dtype: int64
East 63rd-Cottage Grove 2016 12 56    27594
Name: 12, dtype: int64
East 63rd-Cottage Grove 2017 12 56    26317
Name: 12, dtype: int64
East 63rd-Cottage Grove 2018 12 56    0
Name: 12, dtype: int64
East 63rd-Cottage Grove 2019 12 56    21695
Name: 12, dtype: int64
Forest Park 2013 1 56    92042
Name: 1, dtype: int64
Forest Park 2014 1 56    82079
Name: 1, dtype: int64
Forest Park 2015 1 57    83992
Name: 1, dtype: int64
Forest Park 2016 1 57    81621
Name: 1, dtype: int64
Forest Park 2017 1 57    80672
Name: 1, dtype: int64
Forest Park 2018 1 57    76388
Name: 1, dtype: int64
Forest Park 2019 1 57    70357
Name: 1, dtype: int64
Forest Park 2013 2 56    86307
Name: 2, dtype: int64
Forest Park 2014 2 56    83685
Name: 2, dtype: int64
Forest Park 2015 2 57    78033
Name: 2, dtype: int64
Forest Park 2016 2 57    83259
Name: 2, dtype: int64
Forest Park 2017 2 57    78322
Name: 2, dtype: int64
Forest Park 2018 2 57    71885
Name: 2, dtype: int64
Forest Park 2019 2 57    70832
Name: 2, dtype: int64
Forest Park 2013 3 56    93634
Name: 3, dtype: int64
Forest Park 2014 3 56    94142
Name: 3, dtype: int64
Forest Park 2015 3 57    94813
Name: 3, dtype: int64
Forest Park 2016 3 57    92594
Name: 3, dtype: int64
Forest Park 2017 3 57    87917
Name: 3, dtype: int64
Forest Park 2018 3 57    83405
Name: 3, dtype: int64
Forest Park 2019 3 57    76396
Name: 3, dtype: int64
Forest Park 2013 4 56    96996
Name: 4, dtype: int64
Forest Park 2014 4 56    98806
Name: 4, dtype: int64
Forest Park 2015 4 57    96013
Name: 4, dtype: int64
Forest Park 2016 4 57    91418
Name: 4, dtype: int64
Forest Park 2017 4 57    84317
Name: 4, dtype: int64
Forest Park 2018 4 57    82073
Name: 4, dtype: int64
Forest Park 2019 4 57    79111
Name: 4, dtype: int64
Forest Park 2013 5 56    101183
Name: 5, dtype: int64
Forest Park 2014 5 56    99080
Name: 5, dtype: int64
Forest Park 2015 5 57    95074
Name: 5, dtype: int64
Forest Park 2016 5 57    93271
Name: 5, dtype: int64
Forest Park 2017 5 57    90211
Name: 5, dtype: int64
Forest Park 2018 5 57    87237
Name: 5, dtype: int64
Forest Park 2019 5 57    80644
Name: 5, dtype: int64
Forest Park 2013 6 56    98565
Name: 6, dtype: int64
Forest Park 2014 6 56    99882
Name: 6, dtype: int64
Forest Park 2015 6 57    100236
Name: 6, dtype: int64
Forest Park 2016 6 57    97361
Name: 6, dtype: int64
Forest Park 2017 6 57    94755
Name: 6, dtype: int64
Forest Park 2018 6 57    87394
Name: 6, dtype: int64
Forest Park 2019 6 57    78739
Name: 6, dtype: int64
Forest Park 2013 7 56    105131
Name: 7, dtype: int64
Forest Park 2014 7 56    106843
Name: 7, dtype: int64
Forest Park 2015 7 57    105562
Name: 7, dtype: int64
Forest Park 2016 7 57    93790
Name: 7, dtype: int64
Forest Park 2017 7 57    89017
Name: 7, dtype: int64
Forest Park 2018 7 57    87500
Name: 7, dtype: int64
Forest Park 2019 7 57    81616
Name: 7, dtype: int64
Forest Park 2013 8 56    103896
Name: 8, dtype: int64
Forest Park 2014 8 56    101710
Name: 8, dtype: int64
Forest Park 2015 8 57    99298
Name: 8, dtype: int64
Forest Park 2016 8 57    98282
Name: 8, dtype: int64
Forest Park 2017 8 57    96025
Name: 8, dtype: int64
Forest Park 2018 8 57    0
Name: 8, dtype: int64
Forest Park 2019 8 57    82430
Name: 8, dtype: int64
Forest Park 2013 9 56    97956
Name: 9, dtype: int64
Forest Park 2014 9 56    104187
Name: 9, dtype: int64
Forest Park 2015 9 57    101129
Name: 9, dtype: int64
Forest Park 2016 9 57    97699
Name: 9, dtype: int64
Forest Park 2017 9 57    90790
Name: 9, dtype: int64
Forest Park 2018 9 57    0
Name: 9, dtype: int64
Forest Park 2019 9 57    79469
Name: 9, dtype: int64
Forest Park 2013 10 56    104090
Name: 10, dtype: int64
Forest Park 2014 10 56    108522
Name: 10, dtype: int64
Forest Park 2015 10 57    103973
Name: 10, dtype: int64
Forest Park 2016 10 57    99445
Name: 10, dtype: int64
Forest Park 2017 10 57    93894
Name: 10, dtype: int64
Forest Park 2018 10 57    0
Name: 10, dtype: int64
Forest Park 2019 10 57    85590
Name: 10, dtype: int64
Forest Park 2013 11 56    90249
Name: 11, dtype: int64
Forest Park 2014 11 56    87864
Name: 11, dtype: int64
Forest Park 2015 11 57    89209
Name: 11, dtype: int64
Forest Park 2016 11 57    93206
Name: 11, dtype: int64
Forest Park 2017 11 57    85197
Name: 11, dtype: int64
Forest Park 2018 11 57    0
Name: 11, dtype: int64
Forest Park 2019 11 57    71072
Name: 11, dtype: int64
Forest Park 2013 12 56    85755

Name: 12, dtype: int64
Forest Park 2014 12 56    90240
Name: 12, dtype: int64
Forest Park 2015 12 57    88020
Name: 12, dtype: int64
Forest Park 2016 12 57    79521
Name: 12, dtype: int64
Forest Park 2017 12 57    75621
Name: 12, dtype: int64
Forest Park 2018 12 57    0
Name: 12, dtype: int64
Forest Park 2019 12 57    67983
Name: 12, dtype: int64
Foster 2013 1 57    21080
Name: 1, dtype: int64
Foster 2014 1 57    21095
Name: 1, dtype: int64
Foster 2015 1 58    21155
Name: 1, dtype: int64
Foster 2016 1 58    22486
Name: 1, dtype: int64
Foster 2017 1 58    22502
Name: 1, dtype: int64
Foster 2018 1 58    20394
Name: 1, dtype: int64
Foster 2019 1 58    18050
Name: 1, dtype: int64
Foster 2013 2 57    21068
Name: 2, dtype: int64
Foster 2014 2 57    21623
Name: 2, dtype: int64
Foster 2015 2 58    20798
Name: 2, dtype: int64
Foster 2016 2 58    23772
Name: 2, dtype: int64
Foster 2017 2 58    22010
Name: 2, dtype: int64
Foster 2018 2 58    20437
Name: 2, dtype: int64
Foster 2019 2 58    19557
Name: 2, dtype: int64
Foster 2013 3 57    19946
Name: 3, dtype: int64
Foster 2014 3 57    21387
Name: 3, dtype: int64
Foster 2015 3 58    21678
Name: 3, dtype: int64
Foster 2016 3 58    23095
Name: 3, dtype: int64
Foster 2017 3 58    22298
Name: 3, dtype: int64
Foster 2018 3 58    20811
Name: 3, dtype: int64
Foster 2019 3 58    19570
Name: 3, dtype: int64
Foster 2013 4 57    23450
Name: 4, dtype: int64
Foster 2014 4 57    25017
Name: 4, dtype: int64
Foster 2015 4 58    24209
Name: 4, dtype: int64
Foster 2016 4 58    25514
Name: 4, dtype: int64
Foster 2017 4 58    22960
Name: 4, dtype: int64
Foster 2018 4 58    22123
Name: 4, dtype: int64
Foster 2019 4 58    21920
Name: 4, dtype: int64
Foster 2013 5 57    24986
Name: 5, dtype: int64
Foster 2014 5 57    24541
Name: 5, dtype: int64
Foster 2015 5 58    24635
Name: 5, dtype: int64
Foster 2016 5 58    26352
Name: 5, dtype: int64
Foster 2017 5 58    24749
Name: 5, dtype: int64
Foster 2018 5 58    23913
Name: 5, dtype: int64
Foster 2019 5 58    23456
Name: 5, dtype: int64
Foster 2013 6 57    23559
Name: 6, dtype: int64
Foster 2014 6 57    23848
Name: 6, dtype: int64
Foster 2015 6 58    25184
Name: 6, dtype: int64
Foster 2016 6 58    26539
Name: 6, dtype: int64
Foster 2017 6 58    25133
Name: 6, dtype: int64
Foster 2018 6 58    23010
Name: 6, dtype: int64
Foster 2019 6 58    22719
Name: 6, dtype: int64
Foster 2013 7 57    23546
Name: 7, dtype: int64
Foster 2014 7 57    23868
Name: 7, dtype: int64
Foster 2015 7 58    27018
Name: 7, dtype: int64
Foster 2016 7 58    25236
Name: 7, dtype: int64
Foster 2017 7 58    24550
Name: 7, dtype: int64
Foster 2018 7 58    23837
Name: 7, dtype: int64
Foster 2019 7 58    24558
Name: 7, dtype: int64
Foster 2013 8 57    21435
Name: 8, dtype: int64
Foster 2014 8 57    22001
Name: 8, dtype: int64
Foster 2015 8 58    23340
Name: 8, dtype: int64
Foster 2016 8 58    23860
Name: 8, dtype: int64
Foster 2017 8 58    25502
Name: 8, dtype: int64
Foster 2018 8 58    0
Name: 8, dtype: int64
Foster 2019 8 58    21813
Name: 8, dtype: int64
Foster 2013 9 57    20745
Name: 9, dtype: int64
Foster 2014 9 57    22422
Name: 9, dtype: int64
Foster 2015 9 58    24022
Name: 9, dtype: int64
Foster 2016 9 58    24242
Name: 9, dtype: int64
Foster 2017 9 58    22428
Name: 9, dtype: int64
Foster 2018 9 58    0
Name: 9, dtype: int64
Foster 2019 9 58    20277
Name: 9, dtype: int64
Foster 2013 10 57    26803
Name: 10, dtype: int64
Foster 2014 10 57    27444
Name: 10, dtype: int64
Foster 2015 10 58    28896
Name: 10, dtype: int64
Foster 2016 10 58    28443
Name: 10, dtype: int64
Foster 2017 10 58    26284
Name: 10, dtype: int64
Foster 2018 10 58    0
Name: 10, dtype: int64
Foster 2019 10 58    24978
Name: 10, dtype: int64
Foster 2013 11 57    22881
Name: 11, dtype: int64
Foster 2014 11 57    22546
Name: 11, dtype: int64
Foster 2015 11 58    23962
Name: 11, dtype: int64
Foster 2016 11 58    25355
Name: 11, dtype: int64
Foster 2017 11 58    23022
Name: 11, dtype: int64
Foster 2018 11 58    0
Name: 11, dtype: int64
Foster 2019 11 58    21005
Name: 11, dtype: int64
Foster 2013 12 57    17099
Name: 12, dtype: int64
Foster 2014 12 57    17064
Name: 12, dtype: int64
Foster 2015 12 58    17898
Name: 12, dtype: int64
Foster 2016 12 58    15750
Name: 12, dtype: int64
Foster 2017 12 58    15208
Name: 12, dtype: int64
Foster 2018 12 58    0
Name: 12, dtype: int64
Foster 2019 12 58    14839
Name: 12, dtype: int64
Francisco 2013 1 58    37834
Name: 1, dtype: int64
Francisco 2014 1 58    36489
Name: 1, dtype: int64
Francisco 2015 1 59    36997
Name: 1, dtype: int64
Francisco 2016 1 59    37590
Name: 1, dtype: int64
Francisco 2017 1 59    40164
Name: 1, dtype: int64
Francisco 2018 1 59    39484
Name: 1, dtype: int64
Francisco 2019 1 59    36916
Name: 1, dtype: int64
Francisco 2013 2 58    35178
Name: 2, dtype: int64
Francisco 2014 2 58    36568
Name: 2, dtype: int64
Francisco 2015 2 59    35166
Name: 2, dtype: int64
Francisco 2016 2 59    37717
Name: 2, dtype: int64
Francisco 2017 2 59    38077
Name: 2, dtype: int64
Francisco 2018 2 59    36795
Name: 2, dtype: int64
Francisco 2019 2 59    37374
Name: 2, dtype: int64
Francisco 2013 3 58    37868
Name: 3, dtype: int64
Francisco 2014 3 58    40597
Name: 3, dtype: int64
Francisco 2015 3 59    40543
Name: 3, dtype: int64
Francisco 2016 3 59    41978
Name: 3, dtype: int64
Francisco 2017 3 59    44287
Name: 3, dtype: int64
Francisco 2018 3 59    41712
Name: 3, dtype: int64
Francisco 2019 3 59    41751
Name: 3, dtype: int64
Francisco 2013 4 58    39067
Name: 4, dtype: int64
Francisco 2014 4 58    40340
Name: 4, dtype: int64
Francisco 2015 4 59    39583
Name: 4, dtype: int64
Francisco 2016 4 59    39966
Name: 4, dtype: int64
Francisco 2017 4 59    40522
Name: 4, dtype: int64
Francisco 2018 4 59    39970
Name: 4, dtype: int64
Francisco 2019 4 59    41566
Name: 4, dtype: int64
Francisco 2013 5 58    40164
Name: 5, dtype: int64
Francisco 2014 5 58    39369
Name: 5, dtype: int64
Francisco 2015 5 59    40598
Name: 5, dtype: int64
Francisco 2016 5 59    42774
Name: 5, dtype: int64
Francisco 2017 5 59    44741
Name: 5, dtype: int64
Francisco 2018 5 59    43994
Name: 5, dtype: int64
Francisco 2019 5 59    44785
Name: 5, dtype: int64
Francisco 2013 6 58    39843
Name: 6, dtype: int64
Francisco 2014 6 58    40323
Name: 6, dtype: int64
Francisco 2015 6 59    42157
Name: 6, dtype: int64
Francisco 2016 6 59    44249
Name: 6, dtype: int64
Francisco 2017 6 59    45797
Name: 6, dtype: int64
Francisco 2018 6 59    43214
Name: 6, dtype: int64
Francisco 2019 6 59    43447
Name: 6, dtype: int64
Francisco 2013 7 58    42772
Name: 7, dtype: int64
Francisco 2014 7 58    41689
Name: 7, dtype: int64
Francisco 2015 7 59    42816
Name: 7, dtype: int64
Francisco 2016 7 59    42532
Name: 7, dtype: int64
Francisco 2017 7 59    40521
Name: 7, dtype: int64
Francisco 2018 7 59    0
Name: 7, dtype: int64
Francisco 2019 7 59    43974
Name: 7, dtype: int64
Francisco 2013 8 58    42988
Name: 8, dtype: int64
Francisco 2014 8 58    38856
Name: 8, dtype: int64
Francisco 2015 8 59    40912
Name: 8, dtype: int64
Francisco 2016 8 59    44343
Name: 8, dtype: int64
Francisco 2017 8 59    45458
Name: 8, dtype: int64
Francisco 2018 8 59    0
Name: 8, dtype: int64
Francisco 2019 8 59    44270
Name: 8, dtype: int64
Francisco 2013 9 58    41308
Name: 9, dtype: int64
Francisco 2014 9 58    41674
Name: 9, dtype: int64
Francisco 2015 9 59    41939
Name: 9, dtype: int64
Francisco 2016 9 59    44265
Name: 9, dtype: int64
Francisco 2017 9 59    44109
Name: 9, dtype: int64
Francisco 2018 9 59    0
Name: 9, dtype: int64
Francisco 2019 9 59    42678
Name: 9, dtype: int64
Francisco 2013 10 58    44963
Name: 10, dtype: int64
Francisco 2014 10 58    44007
Name: 10, dtype: int64
Francisco 2015 10 59    41730
Name: 10, dtype: int64
Francisco 2016 10 59    45570
Name: 10, dtype: int64
Francisco 2017 10 59    45968
Name: 10, dtype: int64
Francisco 2018 10 59    0
Name: 10, dtype: int64
Francisco 2019 10 59    44466
Name: 10, dtype: int64
Francisco 2013 11 58    39211
Name: 11, dtype: int64
Francisco 2014 11 58    36699
Name: 11, dtype: int64
Francisco 2015 11 59    37544
Name: 11, dtype: int64
Francisco 2016 11 59    42575
Name: 11, dtype: int64
Francisco 2017 11 59    40674
Name: 11, dtype: int64
Francisco 2018 11 59    0
Name: 11, dtype: int64
Francisco 2019 11 59    30817
Name: 11, dtype: int64
Francisco 2013 12 58    37617
Name: 12, dtype: int64
Francisco 2014 12 58    38421
Name: 12, dtype: int64
Francisco 2015 12 59    38297
Name: 12, dtype: int64
Francisco 2016 12 59    38293
Name: 12, dtype: int64
Francisco 2017 12 59    37262
Name: 12, dtype: int64
Francisco 2018 12 59    0
Name: 12, dtype: int64
Francisco 2019 12 59    36956
Name: 12, dtype: int64
Fullerton 2013 1 59    380225
Name: 1, dtype: int64
Fullerton 2014 1 59    337627
Name: 1, dtype: int64
Fullerton 2015 1 60    350796
Name: 1, dtype: int64
Fullerton 2016 1 60    358674
Name: 1, dtype: int64
Fullerton 2017 1 60    346203
Name: 1, dtype: int64
Fullerton 2018 1 60    324892
Name: 1, dtype: int64
Fullerton 2019 1 60    293352
Name: 1, dtype: int64
Fullerton 2013 2 59    361183
Name: 2, dtype: int64
Fullerton 2014 2 59    340896
Name: 2, dtype: int64
Fullerton 2015 2 60    327889
Name: 2, dtype: int64
Fullerton 2016 2 60    361113
Name: 2, dtype: int64
Fullerton 2017 2 60    328758
Name: 2, dtype: int64
Fullerton 2018 2 60    304184
Name: 2, dtype: int64
Fullerton 2019 2 60    307525
Name: 2, dtype: int64
Fullerton 2013 3 59    356765
Name: 3, dtype: int64
Fullerton 2014 3 59    353425
Name: 3, dtype: int64
Fullerton 2015 3 60    357222
Name: 3, dtype: int64
Fullerton 2016 3 60    361740
Name: 3, dtype: int64
Fullerton 2017 3 60    334275
Name: 3, dtype: int64
Fullerton 2018 3 60    315819
Name: 3, dtype: int64
Fullerton 2019 3 60    303485
Name: 3, dtype: int64
Fullerton 2013 4 59    398746
Name: 4, dtype: int64
Fullerton 2014 4 59    386913
Name: 4, dtype: int64
Fullerton 2015 4 60    388558
Name: 4, dtype: int64
Fullerton 2016 4 60    379206
Name: 4, dtype: int64
Fullerton 2017 4 60    342676
Name: 4, dtype: int64
Fullerton 2018 4 60    329143
Name: 4, dtype: int64
Fullerton 2019 4 60    336833
Name: 4, dtype: int64
Fullerton 2013 5 59    399427
Name: 5, dtype: int64
Fullerton 2014 5 59    388329
Name: 5, dtype: int64
Fullerton 2015 5 60    396722
Name: 5, dtype: int64
Fullerton 2016 5 60    386031
Name: 5, dtype: int64
Fullerton 2017 5 60    367121
Name: 5, dtype: int64
Fullerton 2018 5 60    349119
Name: 5, dtype: int64
Fullerton 2019 5 60    352432
Name: 5, dtype: int64
Fullerton 2013 6 59    346974
Name: 6, dtype: int64
Fullerton 2014 6 59    330328
Name: 6, dtype: int64
Fullerton 2015 6 60    344503
Name: 6, dtype: int64
Fullerton 2016 6 60    321316
Name: 6, dtype: int64
Fullerton 2017 6 60    300921
Name: 6, dtype: int64
Fullerton 2018 6 60    278889
Name: 6, dtype: int64
Fullerton 2019 6 60    296985
Name: 6, dtype: int64
Fullerton 2013 7 59    310732
Name: 7, dtype: int64
Fullerton 2014 7 59    304735
Name: 7, dtype: int64
Fullerton 2015 7 60    317706
Name: 7, dtype: int64
Fullerton 2016 7 60    287056
Name: 7, dtype: int64
Fullerton 2017 7 60    259568
Name: 7, dtype: int64
Fullerton 2018 7 60    260836
Name: 7, dtype: int64
Fullerton 2019 7 60    262843
Name: 7, dtype: int64
Fullerton 2013 8 59    300120
Name: 8, dtype: int64
Fullerton 2014 8 59    285802
Name: 8, dtype: int64
Fullerton 2015 8 60    297652
Name: 8, dtype: int64
Fullerton 2016 8 60    279919
Name: 8, dtype: int64
Fullerton 2017 8 60    273382
Name: 8, dtype: int64
Fullerton 2018 8 60    0
Name: 8, dtype: int64
Fullerton 2019 8 60    264402
Name: 8, dtype: int64
Fullerton 2013 9 59    398068
Name: 9, dtype: int64
Fullerton 2014 9 59    400807
Name: 9, dtype: int64
Fullerton 2015 9 60    415022
Name: 9, dtype: int64
Fullerton 2016 9 60    390934
Name: 9, dtype: int64
Fullerton 2017 9 60    375681
Name: 9, dtype: int64
Fullerton 2018 9 60    0
Name: 9, dtype: int64
Fullerton 2019 9 60    360219
Name: 9, dtype: int64
Fullerton 2013 10 59    460415
Name: 10, dtype: int64
Fullerton 2014 10 59    447768
Name: 10, dtype: int64
Fullerton 2015 10 60    448957
Name: 10, dtype: int64
Fullerton 2016 10 60    426137
Name: 10, dtype: int64
Fullerton 2017 10 60    399453
Name: 10, dtype: int64
Fullerton 2018 10 60    0
Name: 10, dtype: int64
Fullerton 2019 10 60    414009
Name: 10, dtype: int64
Fullerton 2013 11 59    367942
Name: 11, dtype: int64
Fullerton 2014 11 59    345022
Name: 11, dtype: int64
Fullerton 2015 11 60    351055
Name: 11, dtype: int64
Fullerton 2016 11 60    338130
Name: 11, dtype: int64
Fullerton 2017 11 60    303440
Name: 11, dtype: int64
Fullerton 2018 11 60    0
Name: 11, dtype: int64
Fullerton 2019 11 60    318540
Name: 11, dtype: int64
Fullerton 2013 12 59    233525
Name: 12, dtype: int64
Fullerton 2014 12 59    233257
Name: 12, dtype: int64
Fullerton 2015 12 60    237648
Name: 12, dtype: int64
Fullerton 2016 12 60    208503
Name: 12, dtype: int64
Fullerton 2017 12 60    198751
Name: 12, dtype: int64
Fullerton 2018 12 60    0
Name: 12, dtype: int64
Fullerton 2019 12 60    208919
Name: 12, dtype: int64
Garfield-Dan Ryan 2013 1 60    92515
Name: 1, dtype: int64
Garfield-Dan Ryan 2014 1 60    82455
Name: 1, dtype: int64
Garfield-Dan Ryan 2015 1 61    93449
Name: 1, dtype: int64
Garfield-Dan Ryan 2016 1 61    94228
Name: 1, dtype: int64
Garfield-Dan Ryan 2017 1 61    87547
Name: 1, dtype: int64
Garfield-Dan Ryan 2018 1 61    78440
Name: 1, dtype: int64
Garfield-Dan Ryan 2019 1 61    70241
Name: 1, dtype: int64
Garfield-Dan Ryan 2013 2 60    85425
Name: 2, dtype: int64
Garfield-Dan Ryan 2014 2 60    87815
Name: 2, dtype: int64
Garfield-Dan Ryan 2015 2 61    85388
Name: 2, dtype: int64
Garfield-Dan Ryan 2016 2 61    93768
Name: 2, dtype: int64
Garfield-Dan Ryan 2017 2 61    85461
Name: 2, dtype: int64
Garfield-Dan Ryan 2018 2 61    74602
Name: 2, dtype: int64
Garfield-Dan Ryan 2019 2 61    69272
Name: 2, dtype: int64
Garfield-Dan Ryan 2013 3 60    94560
Name: 3, dtype: int64
Garfield-Dan Ryan 2014 3 60    98975
Name: 3, dtype: int64
Garfield-Dan Ryan 2015 3 61    101231
Name: 3, dtype: int64
Garfield-Dan Ryan 2016 3 61    101180
Name: 3, dtype: int64
Garfield-Dan Ryan 2017 3 61    92414
Name: 3, dtype: int64
Garfield-Dan Ryan 2018 3 61    83729
Name: 3, dtype: int64
Garfield-Dan Ryan 2019 3 61    75382
Name: 3, dtype: int64
Garfield-Dan Ryan 2013 4 60    94775
Name: 4, dtype: int64
Garfield-Dan Ryan 2014 4 60    99335
Name: 4, dtype: int64
Garfield-Dan Ryan 2015 4 61    102763
Name: 4, dtype: int64
Garfield-Dan Ryan 2016 4 61    98464
Name: 4, dtype: int64
Garfield-Dan Ryan 2017 4 61    88842
Name: 4, dtype: int64
Garfield-Dan Ryan 2018 4 61    82679
Name: 4, dtype: int64
Garfield-Dan Ryan 2019 4 61    75808
Name: 4, dtype: int64
Garfield-Dan Ryan 2013 5 60    57269
Name: 5, dtype: int64
Garfield-Dan Ryan 2014 5 60    106664
Name: 5, dtype: int64
Garfield-Dan Ryan 2015 5 61    107352
Name: 5, dtype: int64
Garfield-Dan Ryan 2016 5 61    103501
Name: 5, dtype: int64
Garfield-Dan Ryan 2017 5 61    97440
Name: 5, dtype: int64
Garfield-Dan Ryan 2018 5 61    91913
Name: 5, dtype: int64
Garfield-Dan Ryan 2019 5 61    84608
Name: 5, dtype: int64
Garfield-Dan Ryan 2013 6 60    0
Name: 6, dtype: int64
Garfield-Dan Ryan 2014 6 60    100748
Name: 6, dtype: int64
Garfield-Dan Ryan 2015 6 61    108741
Name: 6, dtype: int64
Garfield-Dan Ryan 2016 6 61    102011
Name: 6, dtype: int64
Garfield-Dan Ryan 2017 6 61    95934
Name: 6, dtype: int64
Garfield-Dan Ryan 2018 6 61    87582
Name: 6, dtype: int64
Garfield-Dan Ryan 2019 6 61    82443
Name: 6, dtype: int64
Garfield-Dan Ryan 2013 7 60    0
Name: 7, dtype: int64
Garfield-Dan Ryan 2014 7 60    106300
Name: 7, dtype: int64
Garfield-Dan Ryan 2015 7 61    114102
Name: 7, dtype: int64
Garfield-Dan Ryan 2016 7 61    100736
Name: 7, dtype: int64
Garfield-Dan Ryan 2017 7 61    92056
Name: 7, dtype: int64
Garfield-Dan Ryan 2018 7 61    90659
Name: 7, dtype: int64
Garfield-Dan Ryan 2019 7 61    84194
Name: 7, dtype: int64
Garfield-Dan Ryan 2013 8 60    0
Name: 8, dtype: int64
Garfield-Dan Ryan 2014 8 60    103086
Name: 8, dtype: int64
Garfield-Dan Ryan 2015 8 61    107570
Name: 8, dtype: int64
Garfield-Dan Ryan 2016 8 61    98555
Name: 8, dtype: int64
Garfield-Dan Ryan 2017 8 61    93883
Name: 8, dtype: int64
Garfield-Dan Ryan 2018 8 61    0
Name: 8, dtype: int64
Garfield-Dan Ryan 2019 8 61    82295
Name: 8, dtype: int64
Garfield-Dan Ryan 2013 9 60    36047
Name: 9, dtype: int64
Garfield-Dan Ryan 2014 9 60    109417
Name: 9, dtype: int64
Garfield-Dan Ryan 2015 9 61    110732
Name: 9, dtype: int64
Garfield-Dan Ryan 2016 9 61    102423
Name: 9, dtype: int64
Garfield-Dan Ryan 2017 9 61    95115
Name: 9, dtype: int64
Garfield-Dan Ryan 2018 9 61    0
Name: 9, dtype: int64
Garfield-Dan Ryan 2019 9 61    81999
Name: 9, dtype: int64
Garfield-Dan Ryan 2013 10 60    90991
Name: 10, dtype: int64
Garfield-Dan Ryan 2014 10 60    118313
Name: 10, dtype: int64
Garfield-Dan Ryan 2015 10 61    118485
Name: 10, dtype: int64
Garfield-Dan Ryan 2016 10 61    105366
Name: 10, dtype: int64
Garfield-Dan Ryan 2017 10 61    97325
Name: 10, dtype: int64
Garfield-Dan Ryan 2018 10 61    0
Name: 10, dtype: int64

Garfield-Dan Ryan 2019 10 61    86550
Name: 10, dtype: int64
Garfield-Dan Ryan 2013 11 60    84484
Name: 11, dtype: int64
Garfield-Dan Ryan 2014 11 60    101268
Name: 11, dtype: int64
Garfield-Dan Ryan 2015 11 61    103495
Name: 11, dtype: int64
Garfield-Dan Ryan 2016 11 61    99166
Name: 11, dtype: int64
Garfield-Dan Ryan 2017 11 61    88244
Name: 11, dtype: int64
Garfield-Dan Ryan 2018 11 61    0
Name: 11, dtype: int64
Garfield-Dan Ryan 2019 11 61    77082
Name: 11, dtype: int64
Garfield-Dan Ryan 2013 12 60    0
Name: 12, dtype: int64
Garfield-Dan Ryan 2014 12 60    100719
Name: 12, dtype: int64
Garfield-Dan Ryan 2015 12 61    99505
Name: 12, dtype: int64
Garfield-Dan Ryan 2016 12 61    86760
Name: 12, dtype: int64
Garfield-Dan Ryan 2017 12 61    78340
Name: 12, dtype: int64
Garfield-Dan Ryan 2018 12 61    0
Name: 12, dtype: int64
Garfield-Dan Ryan 2019 12 61    70852
Name: 12, dtype: int64
Garfield-South Elevated 2013 1 61    33538
Name: 1, dtype: int64
Garfield-South Elevated 2014 1 61    36941
Name: 1, dtype: int64
Garfield-South Elevated 2015 1 62    32174
Name: 1, dtype: int64
Garfield-South Elevated 2016 1 62    34162
Name: 1, dtype: int64
Garfield-South Elevated 2017 1 62    31147
Name: 1, dtype: int64
Garfield-South Elevated 2018 1 62    30285
Name: 1, dtype: int64
Garfield-South Elevated 2019 1 62    18672
Name: 1, dtype: int64
Garfield-South Elevated 2013 2 61    32110
Name: 2, dtype: int64
Garfield-South Elevated 2014 2 61    37309
Name: 2, dtype: int64
Garfield-South Elevated 2015 2 62    30656
Name: 2, dtype: int64
Garfield-South Elevated 2016 2 62    33830
Name: 2, dtype: int64
Garfield-South Elevated 2017 2 62    30593
Name: 2, dtype: int64
Garfield-South Elevated 2018 2 62    29038
Name: 2, dtype: int64
Garfield-South Elevated 2019 2 62    22024
Name: 2, dtype: int64
Garfield-South Elevated 2013 3 61    37514
Name: 3, dtype: int64
Garfield-South Elevated 2014 3 61    41566
Name: 3, dtype: int64
Garfield-South Elevated 2015 3 62    37234
Name: 3, dtype: int64
Garfield-South Elevated 2016 3 62    36777
Name: 3, dtype: int64
Garfield-South Elevated 2017 3 62    34388
Name: 3, dtype: int64
Garfield-South Elevated 2018 3 62    32901
Name: 3, dtype: int64
Garfield-South Elevated 2019 3 62    25381
Name: 3, dtype: int64
Garfield-South Elevated 2013 4 61    39947
Name: 4, dtype: int64
Garfield-South Elevated 2014 4 61    41220
Name: 4, dtype: int64
Garfield-South Elevated 2015 4 62    37938
Name: 4, dtype: int64
Garfield-South Elevated 2016 4 62    34664
Name: 4, dtype: int64
Garfield-South Elevated 2017 4 62    33022
Name: 4, dtype: int64
Garfield-South Elevated 2018 4 62    32004
Name: 4, dtype: int64
Garfield-South Elevated 2019 4 62    26674
Name: 4, dtype: int64
Garfield-South Elevated 2013 5 61    154290
Name: 5, dtype: int64
Garfield-South Elevated 2014 5 61    41888
Name: 5, dtype: int64
Garfield-South Elevated 2015 5 62    39816
Name: 5, dtype: int64
Garfield-South Elevated 2016 5 62    37320
Name: 5, dtype: int64
Garfield-South Elevated 2017 5 62    36400
Name: 5, dtype: int64
Garfield-South Elevated 2018 5 62    35388
Name: 5, dtype: int64
Garfield-South Elevated 2019 5 62    28940
Name: 5, dtype: int64
Garfield-South Elevated 2013 6 61    351924
Name: 6, dtype: int64
Garfield-South Elevated 2014 6 61    42129
Name: 6, dtype: int64
Garfield-South Elevated 2015 6 62    41437
Name: 6, dtype: int64
Garfield-South Elevated 2016 6 62    38073
Name: 6, dtype: int64
Garfield-South Elevated 2017 6 62    37890
Name: 6, dtype: int64
Garfield-South Elevated 2018 6 62    33885
Name: 6, dtype: int64
Garfield-South Elevated 2019 6 62    28877
Name: 6, dtype: int64
Garfield-South Elevated 2013 7 61    402719
Name: 7, dtype: int64
Garfield-South Elevated 2014 7 61    45199
Name: 7, dtype: int64
Garfield-South Elevated 2015 7 62    46763
Name: 7, dtype: int64
Garfield-South Elevated 2016 7 62    39328
Name: 7, dtype: int64
Garfield-South Elevated 2017 7 62    39016
Name: 7, dtype: int64
Garfield-South Elevated 2018 7 62    37012
Name: 7, dtype: int64
Garfield-South Elevated 2019 7 62    33333
Name: 7, dtype: int64
Garfield-South Elevated 2013 8 61    435799
Name: 8, dtype: int64
Garfield-South Elevated 2014 8 61    43845
Name: 8, dtype: int64
Garfield-South Elevated 2015 8 62    44535
Name: 8, dtype: int64
Garfield-South Elevated 2016 8 62    37764
Name: 8, dtype: int64
Garfield-South Elevated 2017 8 62    40235
Name: 8, dtype: int64
Garfield-South Elevated 2018 8 62    0
Name: 8, dtype: int64
Garfield-South Elevated 2019 8 62    32952
Name: 8, dtype: int64
Garfield-South Elevated 2013 9 61    413846
Name: 9, dtype: int64
Garfield-South Elevated 2014 9 61    41784
Name: 9, dtype: int64
Garfield-South Elevated 2015 9 62    43279
Name: 9, dtype: int64
Garfield-South Elevated 2016 9 62    36261
Name: 9, dtype: int64
Garfield-South Elevated 2017 9 62    36993
Name: 9, dtype: int64
Garfield-South Elevated 2018 9 62    0
Name: 9, dtype: int64
Garfield-South Elevated 2019 9 62    29984
Name: 9, dtype: int64
Garfield-South Elevated 2013 10 61    271854
Name: 10, dtype: int64
Garfield-South Elevated 2014 10 61    43028
Name: 10, dtype: int64
Garfield-South Elevated 2015 10 62    45025
Name: 10, dtype: int64
Garfield-South Elevated 2016 10 62    38591
Name: 10, dtype: int64
Garfield-South Elevated 2017 10 62    38594
Name: 10, dtype: int64
Garfield-South Elevated 2018 10 62    0
Name: 10, dtype: int64
Garfield-South Elevated 2019 10 62    30818
Name: 10, dtype: int64
Garfield-South Elevated 2013 11 61    46544
Name: 11, dtype: int64
Garfield-South Elevated 2014 11 61    34501
Name: 11, dtype: int64
Garfield-South Elevated 2015 11 62    38308
Name: 11, dtype: int64
Garfield-South Elevated 2016 11 62    35325
Name: 11, dtype: int64
Garfield-South Elevated 2017 11 62    34281
Name: 11, dtype: int64
Garfield-South Elevated 2018 11 62    0
Name: 11, dtype: int64
Garfield-South Elevated 2019 11 62    24704
Name: 11, dtype: int64
Garfield-South Elevated 2013 12 61    39513
Name: 12, dtype: int64
Garfield-South Elevated 2014 12 61    34558
Name: 12, dtype: int64
Garfield-South Elevated 2015 12 62    36455
Name: 12, dtype: int64
Garfield-South Elevated 2016 12 62    30469
Name: 12, dtype: int64
Garfield-South Elevated 2017 12 62    29122
Name: 12, dtype: int64
Garfield-South Elevated 2018 12 62    0
Name: 12, dtype: int64
Garfield-South Elevated 2019 12 62    20838
Name: 12, dtype: int64
Grand/Milwaukee 2013 1 62    58593
Name: 1, dtype: int64
Grand/Milwaukee 2014 1 62    61808
Name: 1, dtype: int64
Grand/Milwaukee 2015 1 63    63994
Name: 1, dtype: int64
Grand/Milwaukee 2016 1 63    67250
Name: 1, dtype: int64
Grand/Milwaukee 2017 1 63    62634
Name: 1, dtype: int64
Grand/Milwaukee 2018 1 63    63304
Name: 1, dtype: int64
Grand/Milwaukee 2019 1 63    65795
Name: 1, dtype: int64
Grand/Milwaukee 2013 2 62    55802
Name: 2, dtype: int64
Grand/Milwaukee 2014 2 62    60777
Name: 2, dtype: int64
Grand/Milwaukee 2015 2 63    61474
Name: 2, dtype: int64
Grand/Milwaukee 2016 2 63    68492
Name: 2, dtype: int64
Grand/Milwaukee 2017 2 63    59999
Name: 2, dtype: int64
Grand/Milwaukee 2018 2 63    61672
Name: 2, dtype: int64
Grand/Milwaukee 2019 2 63    64298
Name: 2, dtype: int64
Grand/Milwaukee 2013 3 62    63192
Name: 3, dtype: int64
Grand/Milwaukee 2014 3 62    66400
Name: 3, dtype: int64
Grand/Milwaukee 2015 3 63    70862
Name: 3, dtype: int64
Grand/Milwaukee 2016 3 63    74903
Name: 3, dtype: int64
Grand/Milwaukee 2017 3 63    68906
Name: 3, dtype: int64
Grand/Milwaukee 2018 3 63    71916
Name: 3, dtype: int64
Grand/Milwaukee 2019 3 63    71626
Name: 3, dtype: int64
Grand/Milwaukee 2013 4 62    63871
Name: 4, dtype: int64
Grand/Milwaukee 2014 4 62    65806
Name: 4, dtype: int64
Grand/Milwaukee 2015 4 63    70983
Name: 4, dtype: int64
Grand/Milwaukee 2016 4 63    70843
Name: 4, dtype: int64
Grand/Milwaukee 2017 4 63    64888
Name: 4, dtype: int64
Grand/Milwaukee 2018 4 63    68657
Name: 4, dtype: int64
Grand/Milwaukee 2019 4 63    72413
Name: 4, dtype: int64
Grand/Milwaukee 2013 5 62    66114
Name: 5, dtype: int64
Grand/Milwaukee 2014 5 62    69856
Name: 5, dtype: int64
Grand/Milwaukee 2015 5 63    74159
Name: 5, dtype: int64
Grand/Milwaukee 2016 5 63    74051
Name: 5, dtype: int64
Grand/Milwaukee 2017 5 63    73613
Name: 5, dtype: int64
Grand/Milwaukee 2018 5 63    78328
Name: 5, dtype: int64
Grand/Milwaukee 2019 5 63    79820
Name: 5, dtype: int64
Grand/Milwaukee 2013 6 62    67118
Name: 6, dtype: int64
Grand/Milwaukee 2014 6 62    70081
Name: 6, dtype: int64
Grand/Milwaukee 2015 6 63    78589
Name: 6, dtype: int64
Grand/Milwaukee 2016 6 63    80557
Name: 6, dtype: int64
Grand/Milwaukee 2017 6 63    78090
Name: 6, dtype: int64
Grand/Milwaukee 2018 6 63    80642
Name: 6, dtype: int64
Grand/Milwaukee 2019 6 63    80254
Name: 6, dtype: int64
Grand/Milwaukee 2013 7 62    70597
Name: 7, dtype: int64
Grand/Milwaukee 2014 7 62    75569
Name: 7, dtype: int64
Grand/Milwaukee 2015 7 63    86381
Name: 7, dtype: int64
Grand/Milwaukee 2016 7 63    78750
Name: 7, dtype: int64
Grand/Milwaukee 2017 7 63    75163
Name: 7, dtype: int64

Grand/Milwaukee 2018 7 63    80878
Name: 7, dtype: int64
Grand/Milwaukee 2019 7 63    81325
Name: 7, dtype: int64
Grand/Milwaukee 2013 8 62    72364
Name: 8, dtype: int64
Grand/Milwaukee 2014 8 62    71750
Name: 8, dtype: int64
Grand/Milwaukee 2015 8 63    80584
Name: 8, dtype: int64
Grand/Milwaukee 2016 8 63    76851
Name: 8, dtype: int64
Grand/Milwaukee 2017 8 63    78412
Name: 8, dtype: int64
Grand/Milwaukee 2018 8 63    0
Name: 8, dtype: int64
Grand/Milwaukee 2019 8 63    81378
Name: 8, dtype: int64
Grand/Milwaukee 2013 9 62    63788
Name: 9, dtype: int64
Grand/Milwaukee 2014 9 62    68119
Name: 9, dtype: int64
Grand/Milwaukee 2015 9 63    76846
Name: 9, dtype: int64
Grand/Milwaukee 2016 9 63    71648
Name: 9, dtype: int64
Grand/Milwaukee 2017 9 63    70915
Name: 9, dtype: int64
Grand/Milwaukee 2018 9 63    0
Name: 9, dtype: int64
Grand/Milwaukee 2019 9 63    73366
Name: 9, dtype: int64
Grand/Milwaukee 2013 10 62    71706
Name: 10, dtype: int64
Grand/Milwaukee 2014 10 62    74554
Name: 10, dtype: int64
Grand/Milwaukee 2015 10 63    81245
Name: 10, dtype: int64
Grand/Milwaukee 2016 10 63    75242
Name: 10, dtype: int64
Grand/Milwaukee 2017 10 63    75606
Name: 10, dtype: int64
Grand/Milwaukee 2018 10 63    0
Name: 10, dtype: int64
Grand/Milwaukee 2019 10 63    79258
Name: 10, dtype: int64
Grand/Milwaukee 2013 11 62    64514
Name: 11, dtype: int64
Grand/Milwaukee 2014 11 62    62253
Name: 11, dtype: int64
Grand/Milwaukee 2015 11 63    70100
Name: 11, dtype: int64
Grand/Milwaukee 2016 11 63    67630
Name: 11, dtype: int64
Grand/Milwaukee 2017 11 63    68271
Name: 11, dtype: int64
Grand/Milwaukee 2018 11 63    0
Name: 11, dtype: int64
Grand/Milwaukee 2019 11 63    54475
Name: 11, dtype: int64
Grand/Milwaukee 2013 12 62    60338
Name: 12, dtype: int64
Grand/Milwaukee 2014 12 62    62558
Name: 12, dtype: int64
Grand/Milwaukee 2015 12 63    68614
Name: 12, dtype: int64
Grand/Milwaukee 2016 12 63    60648
Name: 12, dtype: int64
Grand/Milwaukee 2017 12 63    60255
Name: 12, dtype: int64
Grand/Milwaukee 2018 12 63    0
Name: 12, dtype: int64
Grand/Milwaukee 2019 12 63    61710
Name: 12, dtype: int64
Grand/State 2013 1 63    268036
Name: 1, dtype: int64
Grand/State 2014 1 63    297886
Name: 1, dtype: int64
Grand/State 2015 1 64    292102
Name: 1, dtype: int64
Grand/State 2016 1 64    309809
Name: 1, dtype: int64
Grand/State 2017 1 64    297826
Name: 1, dtype: int64
Grand/State 2018 1 64    277930
Name: 1, dtype: int64
Grand/State 2019 1 64    265020
Name: 1, dtype: int64
Grand/State 2013 2 63    228261
Name: 2, dtype: int64
Grand/State 2014 2 63    279276
Name: 2, dtype: int64
Grand/State 2015 2 64    259376
Name: 2, dtype: int64
Grand/State 2016 2 64    301034
Name: 2, dtype: int64
Grand/State 2017 2 64    274449
Name: 2, dtype: int64
Grand/State 2018 2 64    260059
Name: 2, dtype: int64
Grand/State 2019 2 64    256391
Name: 2, dtype: int64
Grand/State 2013 3 63    310994
Name: 3, dtype: int64
Grand/State 2014 3 63    343489
Name: 3, dtype: int64
Grand/State 2015 3 64    338432
Name: 3, dtype: int64
Grand/State 2016 3 64    349255
Name: 3, dtype: int64
Grand/State 2017 3 64    336925
Name: 3, dtype: int64
Grand/State 2018 3 64    323493
Name: 3, dtype: int64
Grand/State 2019 3 64    307157
Name: 3, dtype: int64
Grand/State 2013 4 63    301793
Name: 4, dtype: int64
Grand/State 2014 4 63    340454
Name: 4, dtype: int64
Grand/State 2015 4 64    343168
Name: 4, dtype: int64
Grand/State 2016 4 64    342842
Name: 4, dtype: int64
Grand/State 2017 4 64    325604
Name: 4, dtype: int64
Grand/State 2018 4 64    303189
Name: 4, dtype: int64
Grand/State 2019 4 64    300617
Name: 4, dtype: int64
Grand/State 2013 5 63    327873
Name: 5, dtype: int64
Grand/State 2014 5 63    359153
Name: 5, dtype: int64
Grand/State 2015 5 64    379797
Name: 5, dtype: int64
Grand/State 2016 5 64    369455
Name: 5, dtype: int64
Grand/State 2017 5 64    352718
Name: 5, dtype: int64
Grand/State 2018 5 64    333505
Name: 5, dtype: int64
Grand/State 2019 5 64    333445
Name: 5, dtype: int64
Grand/State 2013 6 63    328293
Name: 6, dtype: int64
Grand/State 2014 6 63    369118
Name: 6, dtype: int64
Grand/State 2015 6 64    399831
Name: 6, dtype: int64
Grand/State 2016 6 64    393664
Name: 6, dtype: int64
Grand/State 2017 6 64    380707
Name: 6, dtype: int64
Grand/State 2018 6 64    355094
Name: 6, dtype: int64
Grand/State 2019 6 64    356310
Name: 6, dtype: int64
Grand/State 2013 7 63    383874
Name: 7, dtype: int64
Grand/State 2014 7 63    412344
Name: 7, dtype: int64
Grand/State 2015 7 64    458589
Name: 7, dtype: int64
Grand/State 2016 7 64    433165
Name: 7, dtype: int64
Grand/State 2017 7 64    395963
Name: 7, dtype: int64
Grand/State 2018 7 64    381190
Name: 7, dtype: int64
Grand/State 2019 7 64    363545
Name: 7, dtype: int64
Grand/State 2013 8 63    375607
Name: 8, dtype: int64
Grand/State 2014 8 63    400525
Name: 8, dtype: int64
Grand/State 2015 8 64    431714
Name: 8, dtype: int64
Grand/State 2016 8 64    406011
Name: 8, dtype: int64
Grand/State 2017 8 64    399651
Name: 8, dtype: int64
Grand/State 2018 8 64    0
Name: 8, dtype: int64
Grand/State 2019 8 64    361751
Name: 8, dtype: int64
Grand/State 2013 9 63    329018
Name: 9, dtype: int64
Grand/State 2014 9 63    349329
Name: 9, dtype: int64
Grand/State 2015 9 64    390410
Name: 9, dtype: int64
Grand/State 2016 9 64    356503
Name: 9, dtype: int64
Grand/State 2017 9 64    343852
Name: 9, dtype: int64
Grand/State 2018 9 64    0
Name: 9, dtype: int64
Grand/State 2019 9 64    315937
Name: 9, dtype: int64
Grand/State 2013 10 63    340106
Name: 10, dtype: int64
Grand/State 2014 10 63    370013
Name: 10, dtype: int64
Grand/State 2015 10 64    397535
Name: 10, dtype: int64
Grand/State 2016 10 64    387165
Name: 10, dtype: int64
Grand/State 2017 10 64    355056
Name: 10, dtype: int64
Grand/State 2018 10 64    0
Name: 10, dtype: int64
Grand/State 2019 10 64    341882
Name: 10, dtype: int64
Grand/State 2013 11 63    320647
Name: 11, dtype: int64
Grand/State 2014 11 63    334999
Name: 11, dtype: int64
Grand/State 2015 11 64    335547
Name: 11, dtype: int64
Grand/State 2016 11 64    345379
Name: 11, dtype: int64
Grand/State 2017 11 64    307188
Name: 11, dtype: int64
Grand/State 2018 11 64    0
Name: 11, dtype: int64
Grand/State 2019 11 64    295181
Name: 11, dtype: int64
Grand/State 2013 12 63    315195
Name: 12, dtype: int64
Grand/State 2014 12 63    328258
Name: 12, dtype: int64
Grand/State 2015 12 64    323129
Name: 12, dtype: int64
Grand/State 2016 12 64    308404
Name: 12, dtype: int64
Grand/State 2017 12 64    287543
Name: 12, dtype: int64
Grand/State 2018 12 64    0
Name: 12, dtype: int64
Grand/State 2019 12 64    282795
Name: 12, dtype: int64
Granville 2013 1 64    102108
Name: 1, dtype: int64
Granville 2014 1 64    109294
Name: 1, dtype: int64
Granville 2015 1 65    110781
Name: 1, dtype: int64
Granville 2016 1 65    107457
Name: 1, dtype: int64
Granville 2017 1 65    102979
Name: 1, dtype: int64
Granville 2018 1 65    99525
Name: 1, dtype: int64
Granville 2019 1 65    92385
Name: 1, dtype: int64
Granville 2013 2 64    102808
Name: 2, dtype: int64
Granville 2014 2 64    114207
Name: 2, dtype: int64
Granville 2015 2 65    109467
Name: 2, dtype: int64
Granville 2016 2 65    115314
Name: 2, dtype: int64
Granville 2017 2 65    106039
Name: 2, dtype: int64
Granville 2018 2 65    101761
Name: 2, dtype: int64
Granville 2019 2 65    98788
Name: 2, dtype: int64
Granville 2013 3 64    111163
Name: 3, dtype: int64
Granville 2014 3 64    126578
Name: 3, dtype: int64
Granville 2015 3 65    121272
Name: 3, dtype: int64
Granville 2016 3 65    117337
Name: 3, dtype: int64
Granville 2017 3 65    116549
Name: 3, dtype: int64
Granville 2018 3 65    110409
Name: 3, dtype: int64
Granville 2019 3 65    106681
Name: 3, dtype: int64
Granville 2013 4 64    111197
Name: 4, dtype: int64
Granville 2014 4 64    123434
Name: 4, dtype: int64
Granville 2015 4 65    121393
Name: 4, dtype: int64
Granville 2016 4 65    118373
Name: 4, dtype: int64
Granville 2017 4 65    109725
Name: 4, dtype: int64
Granville 2018 4 65    108004
Name: 4, dtype: int64
Granville 2019 4 65    104179
Name: 4, dtype: int64
Granville 2013 5 64    103849
Name: 5, dtype: int64
Granville 2014 5 64    115092
Name: 5, dtype: int64
Granville 2015 5 65    108905
Name: 5, dtype: int64
Granville 2016 5 65    108374
Name: 5, dtype: int64
Granville 2017 5 65    106701
Name: 5, dtype: int64
Granville 2018 5 65    102673
Name: 5, dtype: int64
Granville 2019 5 65    97463
Name: 5, dtype: int64
Granville 2013 6 64    101568
Name: 6, dtype: int64
Granville 2014 6 64    111753
Name: 6, dtype: int64
Granville 2015 6 65    110488
Name: 6, dtype: int64
Granville 2016 6 65    109181
Name: 6, dtype: int64
Granville 2017 6 65    106268
Name: 6, dtype: int64
Granville 2018 6 65    99185
Name: 6, dtype: int64
Granville 2019 6 65    93171
Name: 6, dtype: int64
Granville 2013 7 64    105648
Name: 7, dtype: int64
Granville 2014 7 64    114227
Name: 7, dtype: int64
Granville 2015 7 65    116785
Name: 7, dtype: int64
Granville 2016 7 65    111187
Name: 7, dtype: int64
Granville 2017 7 65    102501
Name: 7, dtype: int64
Granville 2018 7 65    100506
Name: 7, dtype: int64
Granville 2019 7 65    94258
Name: 7, dtype: int64
Granville 2013 8 64    112118
Name: 8, dtype: int64
Granville 2014 8 64    116909
Name: 8, dtype: int64
Granville 2015 8 65    116338

Name: 8, dtype: int64
Granville 2016 8 65    108986
Name: 8, dtype: int64
Granville 2017 8 65    108338
Name: 8, dtype: int64
Granville 2018 8 65    0
Name: 8, dtype: int64
Granville 2019 8 65    97599
Name: 8, dtype: int64
Granville 2013 9 64    124073
Name: 9, dtype: int64
Granville 2014 9 64    130209
Name: 9, dtype: int64
Granville 2015 9 65    129516
Name: 9, dtype: int64
Granville 2016 9 65    121888
Name: 9, dtype: int64
Granville 2017 9 65    120272
Name: 9, dtype: int64
Granville 2018 9 65    0
Name: 9, dtype: int64
Granville 2019 9 65    109550
Name: 9, dtype: int64
Granville 2013 10 64    135312
Name: 10, dtype: int64
Granville 2014 10 64    137946
Name: 10, dtype: int64
Granville 2015 10 65    139588
Name: 10, dtype: int64
Granville 2016 10 65    131912
Name: 10, dtype: int64
Granville 2017 10 65    120925
Name: 10, dtype: int64
Granville 2018 10 65    0
Name: 10, dtype: int64
Granville 2019 10 65    116982
Name: 10, dtype: int64
Granville 2013 11 64    121180
Name: 11, dtype: int64
Granville 2014 11 64    119950
Name: 11, dtype: int64
Granville 2015 11 65    116167
Name: 11, dtype: int64
Granville 2016 11 65    119043
Name: 11, dtype: int64
Granville 2017 11 65    110824
Name: 11, dtype: int64
Granville 2018 11 65    0
Name: 11, dtype: int64
Granville 2019 11 65    105454
Name: 11, dtype: int64
Granville 2013 12 64    102696
Name: 12, dtype: int64
Granville 2014 12 64    100169
Name: 12, dtype: int64
Granville 2015 12 65    104676
Name: 12, dtype: int64
Granville 2016 12 65    99951
Name: 12, dtype: int64
Granville 2017 12 65    95975
Name: 12, dtype: int64
Granville 2018 12 65    0
Name: 12, dtype: int64
Granville 2019 12 65    85294
Name: 12, dtype: int64
Halsted-Orange 2013 1 65    65291
Name: 1, dtype: int64
Halsted-Orange 2014 1 65    63913
Name: 1, dtype: int64
Halsted-Orange 2015 1 66    64390
Name: 1, dtype: int64
Halsted-Orange 2016 1 66    65263
Name: 1, dtype: int64
Halsted-Orange 2017 1 66    62963
Name: 1, dtype: int64
Halsted-Orange 2018 1 66    58131
Name: 1, dtype: int64
Halsted-Orange 2019 1 66    54202
Name: 1, dtype: int64
Halsted-Orange 2013 2 65    64314
Name: 2, dtype: int64
Halsted-Orange 2014 2 65    68323
Name: 2, dtype: int64
Halsted-Orange 2015 2 66    65617
Name: 2, dtype: int64
Halsted-Orange 2016 2 66    70527
Name: 2, dtype: int64
Halsted-Orange 2017 2 66    64428
Name: 2, dtype: int64
Halsted-Orange 2018 2 66    58824
Name: 2, dtype: int64
Halsted-Orange 2019 2 66    60682
Name: 2, dtype: int64
Halsted-Orange 2013 3 65    67328
Name: 3, dtype: int64
Halsted-Orange 2014 3 65    75680
Name: 3, dtype: int64
Halsted-Orange 2015 3 66    76154
Name: 3, dtype: int64
Halsted-Orange 2016 3 66    76659
Name: 3, dtype: int64
Halsted-Orange 2017 3 66    72078
Name: 3, dtype: int64
Halsted-Orange 2018 3 66    66475
Name: 3, dtype: int64
Halsted-Orange 2019 3 66    64173
Name: 3, dtype: int64
Halsted-Orange 2013 4 65    71140
Name: 4, dtype: int64
Halsted-Orange 2014 4 65    86893
Name: 4, dtype: int64
Halsted-Orange 2015 4 66    75748
Name: 4, dtype: int64
Halsted-Orange 2016 4 66    73541
Name: 4, dtype: int64
Halsted-Orange 2017 4 66    66995
Name: 4, dtype: int64
Halsted-Orange 2018 4 66    65601
Name: 4, dtype: int64
Halsted-Orange 2019 4 66    67369
Name: 4, dtype: int64
Halsted-Orange 2013 5 65    73729
Name: 5, dtype: int64
Halsted-Orange 2014 5 65    89774
Name: 5, dtype: int64
Halsted-Orange 2015 5 66    68423
Name: 5, dtype: int64
Halsted-Orange 2016 5 66    68776
Name: 5, dtype: int64
Halsted-Orange 2017 5 66    65952
Name: 5, dtype: int64
Halsted-Orange 2018 5 66    63766
Name: 5, dtype: int64
Halsted-Orange 2019 5 66    63011
Name: 5, dtype: int64
Halsted-Orange 2013 6 65    76172
Name: 6, dtype: int64
Halsted-Orange 2014 6 65    68677
Name: 6, dtype: int64
Halsted-Orange 2015 6 66    69889
Name: 6, dtype: int64
Halsted-Orange 2016 6 66    69519
Name: 6, dtype: int64
Halsted-Orange 2017 6 66    65338
Name: 6, dtype: int64
Halsted-Orange 2018 6 66    60100
Name: 6, dtype: int64
Halsted-Orange 2019 6 66    58566
Name: 6, dtype: int64
Halsted-Orange 2013 7 65    77280
Name: 7, dtype: int64
Halsted-Orange 2014 7 65    70168
Name: 7, dtype: int64
Halsted-Orange 2015 7 66    71053
Name: 7, dtype: int64
Halsted-Orange 2016 7 66    67043
Name: 7, dtype: int64
Halsted-Orange 2017 7 66    61020
Name: 7, dtype: int64
Halsted-Orange 2018 7 66    0
Name: 7, dtype: int64
Halsted-Orange 2019 7 66    60123
Name: 7, dtype: int64
Halsted-Orange 2013 8 65    80030
Name: 8, dtype: int64
Halsted-Orange 2014 8 65    69569
Name: 8, dtype: int64
Halsted-Orange 2015 8 66    69389
Name: 8, dtype: int64
Halsted-Orange 2016 8 66    71070
Name: 8, dtype: int64
Halsted-Orange 2017 8 66    66882
Name: 8, dtype: int64
Halsted-Orange 2018 8 66    0
Name: 8, dtype: int64
Halsted-Orange 2019 8 66    62999
Name: 8, dtype: int64
Halsted-Orange 2013 9 65    87404
Name: 9, dtype: int64
Halsted-Orange 2014 9 65    81974
Name: 9, dtype: int64
Halsted-Orange 2015 9 66    79843
Name: 9, dtype: int64
Halsted-Orange 2016 9 66    77700
Name: 9, dtype: int64
Halsted-Orange 2017 9 66    74686
Name: 9, dtype: int64
Halsted-Orange 2018 9 66    0
Name: 9, dtype: int64
Halsted-Orange 2019 9 66    73013
Name: 9, dtype: int64
Halsted-Orange 2013 10 65    97318
Name: 10, dtype: int64
Halsted-Orange 2014 10 65    90499
Name: 10, dtype: int64
Halsted-Orange 2015 10 66    86838
Name: 10, dtype: int64
Halsted-Orange 2016 10 66    81159
Name: 10, dtype: int64
Halsted-Orange 2017 10 66    81379
Name: 10, dtype: int64
Halsted-Orange 2018 10 66    0
Name: 10, dtype: int64
Halsted-Orange 2019 10 66    79949
Name: 10, dtype: int64
Halsted-Orange 2013 11 65    74603
Name: 11, dtype: int64
Halsted-Orange 2014 11 65    70449
Name: 11, dtype: int64
Halsted-Orange 2015 11 66    74161
Name: 11, dtype: int64
Halsted-Orange 2016 11 66    72734
Name: 11, dtype: int64
Halsted-Orange 2017 11 66    68975
Name: 11, dtype: int64
Halsted-Orange 2018 11 66    0
Name: 11, dtype: int64
Halsted-Orange 2019 11 66    65968
Name: 11, dtype: int64
Halsted-Orange 2013 12 65    64960
Name: 12, dtype: int64
Halsted-Orange 2014 12 65    65177
Name: 12, dtype: int64
Halsted-Orange 2015 12 66    66985
Name: 12, dtype: int64
Halsted-Orange 2016 12 66    58183
Name: 12, dtype: int64
Halsted-Orange 2017 12 66    56139
Name: 12, dtype: int64
Halsted-Orange 2018 12 66    0
Name: 12, dtype: int64
Halsted-Orange 2019 12 66    56141
Name: 12, dtype: int64
Halsted/63rd 2013 1 66    23156
Name: 1, dtype: int64
Halsted/63rd 2014 1 66    22160
Name: 1, dtype: int64
Halsted/63rd 2015 1 67    19236
Name: 1, dtype: int64
Halsted/63rd 2016 1 67    17942
Name: 1, dtype: int64
Halsted/63rd 2017 1 67    14835
Name: 1, dtype: int64
Halsted/63rd 2018 1 67    14530
Name: 1, dtype: int64
Halsted/63rd 2019 1 67    11870
Name: 1, dtype: int64
Halsted/63rd 2013 2 66    21726
Name: 2, dtype: int64
Halsted/63rd 2014 2 66    22476
Name: 2, dtype: int64
Halsted/63rd 2015 2 67    17607
Name: 2, dtype: int64
Halsted/63rd 2016 2 67    18518
Name: 2, dtype: int64
Halsted/63rd 2017 2 67    15702
Name: 2, dtype: int64
Halsted/63rd 2018 2 67    14407
Name: 2, dtype: int64
Halsted/63rd 2019 2 67    12651
Name: 2, dtype: int64
Halsted/63rd 2013 3 66    20715
Name: 3, dtype: int64
Halsted/63rd 2014 3 66    24321
Name: 3, dtype: int64
Halsted/63rd 2015 3 67    20202
Name: 3, dtype: int64
Halsted/63rd 2016 3 67    18791
Name: 3, dtype: int64
Halsted/63rd 2017 3 67    16380
Name: 3, dtype: int64
Halsted/63rd 2018 3 67    15472
Name: 3, dtype: int64
Halsted/63rd 2019 3 67    14042
Name: 3, dtype: int64
Halsted/63rd 2013 4 66    20938
Name: 4, dtype: int64
Halsted/63rd 2014 4 66    22249
Name: 4, dtype: int64
Halsted/63rd 2015 4 67    20035
Name: 4, dtype: int64
Halsted/63rd 2016 4 67    17532
Name: 4, dtype: int64
Halsted/63rd 2017 4 67    15625
Name: 4, dtype: int64
Halsted/63rd 2018 4 67    15617
Name: 4, dtype: int64
Halsted/63rd 2019 4 67    13925
Name: 4, dtype: int64
Halsted/63rd 2013 5 66    35730
Name: 5, dtype: int64
Halsted/63rd 2014 5 66    22521
Name: 5, dtype: int64
Halsted/63rd 2015 5 67    19478
Name: 5, dtype: int64
Halsted/63rd 2016 5 67    17320
Name: 5, dtype: int64
Halsted/63rd 2017 5 67    16945
Name: 5, dtype: int64
Halsted/63rd 2018 5 67    16683
Name: 5, dtype: int64
Halsted/63rd 2019 5 67    14038
Name: 5, dtype: int64
Halsted/63rd 2013 6 66    56378
Name: 6, dtype: int64
Halsted/63rd 2014 6 66    21336
Name: 6, dtype: int64
Halsted/63rd 2015 6 67    20022
Name: 6, dtype: int64
Halsted/63rd 2016 6 67    17327
Name: 6, dtype: int64
Halsted/63rd 2017 6 67    16562
Name: 6, dtype: int64
Halsted/63rd 2018 6 67    15923
Name: 6, dtype: int64
Halsted/63rd 2019 6 67    13067
Name: 6, dtype: int64
Halsted/63rd 2013 7 66    59050
Name: 7, dtype: int64
Halsted/63rd 2014 7 66    21693
Name: 7, dtype: int64
Halsted/63rd 2015 7 67    21628
Name: 7, dtype: int64
Halsted/63rd 2016 7 67    16758
Name: 7, dtype: int64
Halsted/63rd 2017 7 67    16090
Name: 7, dtype: int64
Halsted/63rd 2018 7 67    0
Name: 7, dtype: int64
Halsted/63rd 2019 7 67    13570
Name: 7, dtype: int64
Halsted/63rd 2013 8 66    62503
Name: 8, dtype: int64
Halsted/63rd 2014 8 66    23220
Name: 8, dtype: int64
Halsted/63rd 2015 8 67    21254
Name: 8, dtype: int64
Halsted/63rd 2016 8 67    16764
Name: 8, dtype: int64
Halsted/63rd 2017 8 67    16815
Name: 8, dtype: int64
Halsted/63rd 2018 8 67    0
Name: 8, dtype: int64

Halsted/63rd 2019 8 67    13659
Name: 8, dtype: int64
Halsted/63rd 2013 9 66    67533
Name: 9, dtype: int64
Halsted/63rd 2014 9 66    25002
Name: 9, dtype: int64
Halsted/63rd 2015 9 67    23831
Name: 9, dtype: int64
Halsted/63rd 2016 9 67    20036
Name: 9, dtype: int64
Halsted/63rd 2017 9 67    19091
Name: 9, dtype: int64
Halsted/63rd 2018 9 67    0
Name: 9, dtype: int64
Halsted/63rd 2019 9 67    14712
Name: 9, dtype: int64
Halsted/63rd 2013 10 66    57902
Name: 10, dtype: int64
Halsted/63rd 2014 10 66    25484
Name: 10, dtype: int64
Halsted/63rd 2015 10 67    25158
Name: 10, dtype: int64
Halsted/63rd 2016 10 67    19002
Name: 10, dtype: int64
Halsted/63rd 2017 10 67    19931
Name: 10, dtype: int64
Halsted/63rd 2018 10 67    0
Name: 10, dtype: int64
Halsted/63rd 2019 10 67    14884
Name: 10, dtype: int64
Halsted/63rd 2013 11 66    25951
Name: 11, dtype: int64
Halsted/63rd 2014 11 66    20090
Name: 11, dtype: int64
Halsted/63rd 2015 11 67    20723
Name: 11, dtype: int64
Halsted/63rd 2016 11 67    16950
Name: 11, dtype: int64
Halsted/63rd 2017 11 67    17278
Name: 11, dtype: int64
Halsted/63rd 2018 11 67    0
Name: 11, dtype: int64
Halsted/63rd 2019 11 67    12119
Name: 11, dtype: int64
Halsted/63rd 2013 12 66    22470
Name: 12, dtype: int64
Halsted/63rd 2014 12 66    19468
Name: 12, dtype: int64
Halsted/63rd 2015 12 67    18939
Name: 12, dtype: int64
Halsted/63rd 2016 12 67    14221
Name: 12, dtype: int64
Halsted/63rd 2017 12 67    14521
Name: 12, dtype: int64
Halsted/63rd 2018 12 67    0
Name: 12, dtype: int64
Halsted/63rd 2019 12 67    10677
Name: 12, dtype: int64
Harlem-Forest Park 2013 1 67    26207
Name: 1, dtype: int64
Harlem-Forest Park 2014 1 67    25968
Name: 1, dtype: int64
Harlem-Forest Park 2015 1 68    28069
Name: 1, dtype: int64
Harlem-Forest Park 2016 1 68    27749
Name: 1, dtype: int64
Harlem-Forest Park 2017 1 68    29867
Name: 1, dtype: int64
Harlem-Forest Park 2018 1 68    27791
Name: 1, dtype: int64
Harlem-Forest Park 2019 1 68    27331
Name: 1, dtype: int64
Harlem-Forest Park 2013 2 67    24313
Name: 2, dtype: int64
Harlem-Forest Park 2014 2 67    25877
Name: 2, dtype: int64
Harlem-Forest Park 2015 2 68    26430
Name: 2, dtype: int64
Harlem-Forest Park 2016 2 68    28576
Name: 2, dtype: int64
Harlem-Forest Park 2017 2 68    27843
Name: 2, dtype: int64
Harlem-Forest Park 2018 2 68    25935
Name: 2, dtype: int64
Harlem-Forest Park 2019 2 68    27039
Name: 2, dtype: int64
Harlem-Forest Park 2013 3 67    27643
Name: 3, dtype: int64
Harlem-Forest Park 2014 3 67    29896
Name: 3, dtype: int64
Harlem-Forest Park 2015 3 68    32178
Name: 3, dtype: int64
Harlem-Forest Park 2016 3 68    30975
Name: 3, dtype: int64
Harlem-Forest Park 2017 3 68    31010
Name: 3, dtype: int64
Harlem-Forest Park 2018 3 68    30238
Name: 3, dtype: int64
Harlem-Forest Park 2019 3 68    28903
Name: 3, dtype: int64
Harlem-Forest Park 2013 4 67    27520
Name: 4, dtype: int64
Harlem-Forest Park 2014 4 67    30310
Name: 4, dtype: int64
Harlem-Forest Park 2015 4 68    31670
Name: 4, dtype: int64
Harlem-Forest Park 2016 4 68    30714
Name: 4, dtype: int64
Harlem-Forest Park 2017 4 68    29431
Name: 4, dtype: int64
Harlem-Forest Park 2018 4 68    30473
Name: 4, dtype: int64
Harlem-Forest Park 2019 4 68    29557
Name: 4, dtype: int64
Harlem-Forest Park 2013 5 67    28691
Name: 5, dtype: int64
Harlem-Forest Park 2014 5 67    30978
Name: 5, dtype: int64
Harlem-Forest Park 2015 5 68    33170
Name: 5, dtype: int64
Harlem-Forest Park 2016 5 68    31730
Name: 5, dtype: int64
Harlem-Forest Park 2017 5 68    31381
Name: 5, dtype: int64
Harlem-Forest Park 2018 5 68    32772
Name: 5, dtype: int64
Harlem-Forest Park 2019 5 68    29804
Name: 5, dtype: int64
Harlem-Forest Park 2013 6 67    28696
Name: 6, dtype: int64
Harlem-Forest Park 2014 6 67    30437
Name: 6, dtype: int64
Harlem-Forest Park 2015 6 68    34437
Name: 6, dtype: int64
Harlem-Forest Park 2016 6 68    33037
Name: 6, dtype: int64
Harlem-Forest Park 2017 6 68    32744
Name: 6, dtype: int64
Harlem-Forest Park 2018 6 68    31253
Name: 6, dtype: int64
Harlem-Forest Park 2019 6 68    29370
Name: 6, dtype: int64
Harlem-Forest Park 2013 7 67    31290
Name: 7, dtype: int64
Harlem-Forest Park 2014 7 67    31754
Name: 7, dtype: int64
Harlem-Forest Park 2015 7 68    35756
Name: 7, dtype: int64
Harlem-Forest Park 2016 7 68    32087
Name: 7, dtype: int64
Harlem-Forest Park 2017 7 68    31563
Name: 7, dtype: int64
Harlem-Forest Park 2018 7 68    31609
Name: 7, dtype: int64
Harlem-Forest Park 2019 7 68    29845
Name: 7, dtype: int64
Harlem-Forest Park 2013 8 67    32256
Name: 8, dtype: int64
Harlem-Forest Park 2014 8 67    32641
Name: 8, dtype: int64
Harlem-Forest Park 2015 8 68    34748
Name: 8, dtype: int64
Harlem-Forest Park 2016 8 68    34249
Name: 8, dtype: int64
Harlem-Forest Park 2017 8 68    34894
Name: 8, dtype: int64
Harlem-Forest Park 2018 8 68    0
Name: 8, dtype: int64
Harlem-Forest Park 2019 8 68    30251
Name: 8, dtype: int64
Harlem-Forest Park 2013 9 67    30116
Name: 9, dtype: int64
Harlem-Forest Park 2014 9 67    33451
Name: 9, dtype: int64
Harlem-Forest Park 2015 9 68    34016
Name: 9, dtype: int64
Harlem-Forest Park 2016 9 68    33980
Name: 9, dtype: int64
Harlem-Forest Park 2017 9 68    33443
Name: 9, dtype: int64
Harlem-Forest Park 2018 9 68    0
Name: 9, dtype: int64
Harlem-Forest Park 2019 9 68    29088
Name: 9, dtype: int64
Harlem-Forest Park 2013 10 67    31580
Name: 10, dtype: int64
Harlem-Forest Park 2014 10 67    35232
Name: 10, dtype: int64
Harlem-Forest Park 2015 10 68    34724
Name: 10, dtype: int64
Harlem-Forest Park 2016 10 68    35290
Name: 10, dtype: int64
Harlem-Forest Park 2017 10 68    35153
Name: 10, dtype: int64
Harlem-Forest Park 2018 10 68    0
Name: 10, dtype: int64
Harlem-Forest Park 2019 10 68    31299
Name: 10, dtype: int64
Harlem-Forest Park 2013 11 67    29441
Name: 11, dtype: int64
Harlem-Forest Park 2014 11 67    30109
Name: 11, dtype: int64
Harlem-Forest Park 2015 11 68    30233
Name: 11, dtype: int64
Harlem-Forest Park 2016 11 68    33025
Name: 11, dtype: int64
Harlem-Forest Park 2017 11 68    31506
Name: 11, dtype: int64
Harlem-Forest Park 2018 11 68    0
Name: 11, dtype: int64
Harlem-Forest Park 2019 11 68    26346
Name: 11, dtype: int64
Harlem-Forest Park 2013 12 67    27116
Name: 12, dtype: int64
Harlem-Forest Park 2014 12 67    30698
Name: 12, dtype: int64
Harlem-Forest Park 2015 12 68    30950
Name: 12, dtype: int64
Harlem-Forest Park 2016 12 68    29357
Name: 12, dtype: int64
Harlem-Forest Park 2017 12 68    27219
Name: 12, dtype: int64
Harlem-Forest Park 2018 12 68    0
Name: 12, dtype: int64
Harlem-Forest Park 2019 12 68    25263
Name: 12, dtype: int64
Harlem-Lake 2013 1 68    92506
Name: 1, dtype: int64
Harlem-Lake 2014 1 68    91357
Name: 1, dtype: int64
Harlem-Lake 2015 1 69    92361
Name: 1, dtype: int64
Harlem-Lake 2016 1 69    92659
Name: 1, dtype: int64
Harlem-Lake 2017 1 69    90092
Name: 1, dtype: int64
Harlem-Lake 2018 1 69    87743
Name: 1, dtype: int64
Harlem-Lake 2019 1 69    82086
Name: 1, dtype: int64
Harlem-Lake 2013 2 68    87396
Name: 2, dtype: int64
Harlem-Lake 2014 2 68    92617
Name: 2, dtype: int64
Harlem-Lake 2015 2 69    88544
Name: 2, dtype: int64
Harlem-Lake 2016 2 69    94084
Name: 2, dtype: int64
Harlem-Lake 2017 2 69    89496
Name: 2, dtype: int64
Harlem-Lake 2018 2 69    82998
Name: 2, dtype: int64
Harlem-Lake 2019 2 69    80855
Name: 2, dtype: int64
Harlem-Lake 2013 3 68    94303
Name: 3, dtype: int64
Harlem-Lake 2014 3 68    105541
Name: 3, dtype: int64
Harlem-Lake 2015 3 69    105107
Name: 3, dtype: int64
Harlem-Lake 2016 3 69    102558
Name: 3, dtype: int64
Harlem-Lake 2017 3 69    98327
Name: 3, dtype: int64
Harlem-Lake 2018 3 69    97050
Name: 3, dtype: int64
Harlem-Lake 2019 3 69    90355
Name: 3, dtype: int64
Harlem-Lake 2013 4 68    97172
Name: 4, dtype: int64
Harlem-Lake 2014 4 68    108755
Name: 4, dtype: int64
Harlem-Lake 2015 4 69    104885
Name: 4, dtype: int64
Harlem-Lake 2016 4 69    83769
Name: 4, dtype: int64
Harlem-Lake 2017 4 69    94007
Name: 4, dtype: int64
Harlem-Lake 2018 4 69    93044
Name: 4, dtype: int64
Harlem-Lake 2019 4 69    92332
Name: 4, dtype: int64
Harlem-Lake 2013 5 68    103650
Name: 5, dtype: int64
Harlem-Lake 2014 5 68    110462
Name: 5, dtype: int64
Harlem-Lake 2015 5 69    105606
Name: 5, dtype: int64
Harlem-Lake 2016 5 69    85803
Name: 5, dtype: int64
Harlem-Lake 2017 5 69    100012
Name: 5, dtype: int64
Harlem-Lake 2018 5 69    100828
Name: 5, dtype: int64
Harlem-Lake 2019 5 69    96208
Name: 5, dtype: int64
Harlem-Lake 2013 6 68    105089
Name: 6, dtype: int64
Harlem-Lake 2014 6 68    111219
Name: 6, dtype: int64
Harlem-Lake 2015 6 69    111560
Name: 6, dtype: int64

Harlem-Lake 2016 6 69    103548
Name: 6, dtype: int64
Harlem-Lake 2017 6 69    105068
Name: 6, dtype: int64
Harlem-Lake 2018 6 69    102085
Name: 6, dtype: int64
Harlem-Lake 2019 6 69    95657
Name: 6, dtype: int64
Harlem-Lake 2013 7 68    111499
Name: 7, dtype: int64
Harlem-Lake 2014 7 68    115291
Name: 7, dtype: int64
Harlem-Lake 2015 7 69    117721
Name: 7, dtype: int64
Harlem-Lake 2016 7 69    103921
Name: 7, dtype: int64
Harlem-Lake 2017 7 69    102147
Name: 7, dtype: int64
Harlem-Lake 2018 7 69    103872
Name: 7, dtype: int64
Harlem-Lake 2019 7 69    98639
Name: 7, dtype: int64
Harlem-Lake 2013 8 68    116108
Name: 8, dtype: int64
Harlem-Lake 2014 8 68    114763
Name: 8, dtype: int64
Harlem-Lake 2015 8 69    113260
Name: 8, dtype: int64
Harlem-Lake 2016 8 69    106419
Name: 8, dtype: int64
Harlem-Lake 2017 8 69    107538
Name: 8, dtype: int64
Harlem-Lake 2018 8 69    0
Name: 8, dtype: int64
Harlem-Lake 2019 8 69    100649
Name: 8, dtype: int64
Harlem-Lake 2013 9 68    108309
Name: 9, dtype: int64
Harlem-Lake 2014 9 68    111463
Name: 9, dtype: int64
Harlem-Lake 2015 9 69    111219
Name: 9, dtype: int64
Harlem-Lake 2016 9 69    103925
Name: 9, dtype: int64
Harlem-Lake 2017 9 69    100995
Name: 9, dtype: int64
Harlem-Lake 2018 9 69    0
Name: 9, dtype: int64
Harlem-Lake 2019 9 69    94794
Name: 9, dtype: int64
Harlem-Lake 2013 10 68    115275
Name: 10, dtype: int64
Harlem-Lake 2014 10 68    118099
Name: 10, dtype: int64
Harlem-Lake 2015 10 69    114583
Name: 10, dtype: int64
Harlem-Lake 2016 10 69    105175
Name: 10, dtype: int64
Harlem-Lake 2017 10 69    104208
Name: 10, dtype: int64
Harlem-Lake 2018 10 69    0
Name: 10, dtype: int64
Harlem-Lake 2019 10 69    101011
Name: 10, dtype: int64
Harlem-Lake 2013 11 68    101880
Name: 11, dtype: int64
Harlem-Lake 2014 11 68    99051
Name: 11, dtype: int64
Harlem-Lake 2015 11 69    101265
Name: 11, dtype: int64
Harlem-Lake 2016 11 69    100779
Name: 11, dtype: int64
Harlem-Lake 2017 11 69    94191
Name: 11, dtype: int64
Harlem-Lake 2018 11 69    0
Name: 11, dtype: int64
Harlem-Lake 2019 11 69    86392
Name: 11, dtype: int64
Harlem-Lake 2013 12 68    95030
Name: 12, dtype: int64
Harlem-Lake 2014 12 68    99963
Name: 12, dtype: int64
Harlem-Lake 2015 12 69    100250
Name: 12, dtype: int64
Harlem-Lake 2016 12 69    86922
Name: 12, dtype: int64
Harlem-Lake 2017 12 69    85538
Name: 12, dtype: int64
Harlem-Lake 2018 12 69    0
Name: 12, dtype: int64
Harlem-Lake 2019 12 69    82835
Name: 12, dtype: int64
Harlem-O'Hare 2013 1 69    70188
Name: 1, dtype: int64
Harlem-O'Hare 2014 1 69    65698
Name: 1, dtype: int64
Harlem-O'Hare 2015 1 70    69895
Name: 1, dtype: int64
Harlem-O'Hare 2016 1 70    70863
Name: 1, dtype: int64
Harlem-O'Hare 2017 1 70    68930
Name: 1, dtype: int64
Harlem-O'Hare 2018 1 70    67432
Name: 1, dtype: int64
Harlem-O'Hare 2019 1 70    63955
Name: 1, dtype: int64
Harlem-O'Hare 2013 2 69    65996
Name: 2, dtype: int64
Harlem-O'Hare 2014 2 69    67560
Name: 2, dtype: int64
Harlem-O'Hare 2015 2 70    66584
Name: 2, dtype: int64
Harlem-O'Hare 2016 2 70    72711
Name: 2, dtype: int64
Harlem-O'Hare 2017 2 70    67192
Name: 2, dtype: int64
Harlem-O'Hare 2018 2 70    64011
Name: 2, dtype: int64
Harlem-O'Hare 2019 2 70    64677
Name: 2, dtype: int64
Harlem-O'Hare 2013 3 69    72523
Name: 3, dtype: int64
Harlem-O'Hare 2014 3 69    77180
Name: 3, dtype: int64
Harlem-O'Hare 2015 3 70    80764
Name: 3, dtype: int64
Harlem-O'Hare 2016 3 70    81735
Name: 3, dtype: int64
Harlem-O'Hare 2017 3 70    77045
Name: 3, dtype: int64
Harlem-O'Hare 2018 3 70    73982
Name: 3, dtype: int64
Harlem-O'Hare 2019 3 70    72490
Name: 3, dtype: int64
Harlem-O'Hare 2013 4 69    76150
Name: 4, dtype: int64
Harlem-O'Hare 2014 4 69    76957
Name: 4, dtype: int64
Harlem-O'Hare 2015 4 70    78264
Name: 4, dtype: int64
Harlem-O'Hare 2016 4 70    75818
Name: 4, dtype: int64
Harlem-O'Hare 2017 4 70    69599
Name: 4, dtype: int64
Harlem-O'Hare 2018 4 70    70860
Name: 4, dtype: int64
Harlem-O'Hare 2019 4 70    73632
Name: 4, dtype: int64
Harlem-O'Hare 2013 5 69    78629
Name: 5, dtype: int64
Harlem-O'Hare 2014 5 69    80444
Name: 5, dtype: int64
Harlem-O'Hare 2015 5 70    79872
Name: 5, dtype: int64
Harlem-O'Hare 2016 5 70    78110
Name: 5, dtype: int64
Harlem-O'Hare 2017 5 70    77340
Name: 5, dtype: int64
Harlem-O'Hare 2018 5 70    75940
Name: 5, dtype: int64
Harlem-O'Hare 2019 5 70    74990
Name: 5, dtype: int64
Harlem-O'Hare 2013 6 69    78201
Name: 6, dtype: int64
Harlem-O'Hare 2014 6 69    79183
Name: 6, dtype: int64
Harlem-O'Hare 2015 6 70    84935
Name: 6, dtype: int64
Harlem-O'Hare 2016 6 70    79872
Name: 6, dtype: int64
Harlem-O'Hare 2017 6 70    79720
Name: 6, dtype: int64
Harlem-O'Hare 2018 6 70    73450
Name: 6, dtype: int64
Harlem-O'Hare 2019 6 70    70582
Name: 6, dtype: int64
Harlem-O'Hare 2013 7 69    79395
Name: 7, dtype: int64
Harlem-O'Hare 2014 7 69    80118
Name: 7, dtype: int64
Harlem-O'Hare 2015 7 70    83352
Name: 7, dtype: int64
Harlem-O'Hare 2016 7 70    76658
Name: 7, dtype: int64
Harlem-O'Hare 2017 7 70    72720
Name: 7, dtype: int64
Harlem-O'Hare 2018 7 70    72478
Name: 7, dtype: int64
Harlem-O'Hare 2019 7 70    71830
Name: 7, dtype: int64
Harlem-O'Hare 2013 8 69    81954
Name: 8, dtype: int64
Harlem-O'Hare 2014 8 69    79915
Name: 8, dtype: int64
Harlem-O'Hare 2015 8 70    80674
Name: 8, dtype: int64
Harlem-O'Hare 2016 8 70    78560
Name: 8, dtype: int64
Harlem-O'Hare 2017 8 70    80147
Name: 8, dtype: int64
Harlem-O'Hare 2018 8 70    0
Name: 8, dtype: int64
Harlem-O'Hare 2019 8 70    69909
Name: 8, dtype: int64
Harlem-O'Hare 2013 9 69    79557
Name: 9, dtype: int64
Harlem-O'Hare 2014 9 69    84391
Name: 9, dtype: int64
Harlem-O'Hare 2015 9 70    84720
Name: 9, dtype: int64
Harlem-O'Hare 2016 9 70    68479
Name: 9, dtype: int64
Harlem-O'Hare 2017 9 70    76956
Name: 9, dtype: int64
Harlem-O'Hare 2018 9 70    0
Name: 9, dtype: int64
Harlem-O'Hare 2019 9 70    73075
Name: 9, dtype: int64
Harlem-O'Hare 2013 10 69    87695
Name: 10, dtype: int64
Harlem-O'Hare 2014 10 69    90471
Name: 10, dtype: int64
Harlem-O'Hare 2015 10 70    89013
Name: 10, dtype: int64
Harlem-O'Hare 2016 10 70    76323
Name: 10, dtype: int64
Harlem-O'Hare 2017 10 70    80332
Name: 10, dtype: int64
Harlem-O'Hare 2018 10 70    0
Name: 10, dtype: int64
Harlem-O'Hare 2019 10 70    79443
Name: 10, dtype: int64
Harlem-O'Hare 2013 11 69    75543
Name: 11, dtype: int64
Harlem-O'Hare 2014 11 69    74513
Name: 11, dtype: int64
Harlem-O'Hare 2015 11 70    77428
Name: 11, dtype: int64
Harlem-O'Hare 2016 11 70    80257
Name: 11, dtype: int64
Harlem-O'Hare 2017 11 70    73079
Name: 11, dtype: int64
Harlem-O'Hare 2018 11 70    0
Name: 11, dtype: int64
Harlem-O'Hare 2019 11 70    66816
Name: 11, dtype: int64
Harlem-O'Hare 2013 12 69    69588
Name: 12, dtype: int64
Harlem-O'Hare 2014 12 69    76482
Name: 12, dtype: int64
Harlem-O'Hare 2015 12 70    75790
Name: 12, dtype: int64
Harlem-O'Hare 2016 12 70    67173
Name: 12, dtype: int64
Harlem-O'Hare 2017 12 70    65516
Name: 12, dtype: int64
Harlem-O'Hare 2018 12 70    0
Name: 12, dtype: int64
Harlem-O'Hare 2019 12 70    63477
Name: 12, dtype: int64
Harrison 2013 1 70    94999
Name: 1, dtype: int64
Harrison 2014 1 70    94271
Name: 1, dtype: int64
Harrison 2015 1 71    97456
Name: 1, dtype: int64
Harrison 2016 1 71    104244
Name: 1, dtype: int64
Harrison 2017 1 71    98355
Name: 1, dtype: int64
Harrison 2018 1 71    96426
Name: 1, dtype: int64
Harrison 2019 1 71    82861
Name: 1, dtype: int64
Harrison 2013 2 70    111370
Name: 2, dtype: int64
Harrison 2014 2 70    121775
Name: 2, dtype: int64
Harrison 2015 2 71    107766
Name: 2, dtype: int64
Harrison 2016 2 71    124044
Name: 2, dtype: int64
Harrison 2017 2 71    109263
Name: 2, dtype: int64
Harrison 2018 2 71    104052
Name: 2, dtype: int64
Harrison 2019 2 71    96085
Name: 2, dtype: int64
Harrison 2013 3 70    123052
Name: 3, dtype: int64
Harrison 2014 3 70    128825
Name: 3, dtype: int64
Harrison 2015 3 71    125284
Name: 3, dtype: int64
Harrison 2016 3 71    127140
Name: 3, dtype: int64
Harrison 2017 3 71    122743
Name: 3, dtype: int64
Harrison 2018 3 71    111783
Name: 3, dtype: int64
Harrison 2019 3 71    101875
Name: 3, dtype: int64
Harrison 2013 4 70    128963
Name: 4, dtype: int64
Harrison 2014 4 70    125336
Name: 4, dtype: int64
Harrison 2015 4 71    132600
Name: 4, dtype: int64
Harrison 2016 4 71    131943
Name: 4, dtype: int64
Harrison 2017 4 71    117797
Name: 4, dtype: int64
Harrison 2018 4 71    114403
Name: 4, dtype: int64
Harrison 2019 4 71    102118
Name: 4, dtype: int64
Harrison 2013 5 70    117828
Name: 5, dtype: int64
Harrison 2014 5 70    87680
Name: 5, dtype: int64
Harrison 2015 5 71    129904
Name: 5, dtype: int64
Harrison 2016 5 71    123946
Name: 5, dtype: int64
Harrison 2017 5 71    116716
Name: 5, dtype: int64
Harrison 2018 5 71    111482
Name: 5, dtype: int64
Harrison 2019 5 71    103040
Name: 5, dtype: int64
Harrison 2013 6 70    100217
Name: 6, dtype: int64
Harrison 2014 6 70    81988
Name: 6, dtype: int64
Harrison 2015 6 71    117561
Name: 6, dtype: int64
Harrison 2016 6 71    114102
Name: 6, dtype: int64
Harrison 2017 6 71    106161
Name: 6, dtype: int64
Harrison 2018 6 71    103265
Name: 6, dtype: int64
Harrison 2019 6 71    98777
Name: 6, dtype: int64
Harrison 2013 7 70    105941
Name: 7, dtype: int64
Harrison 2014 7 70    86725
Name: 7, dtype: int64
Harrison 2015 7 71    133036
Name: 7, dtype: int64
Harrison 2016 7 71    125913
Name: 7, dtype: int64
Harrison 2017 7 71    102834
Name: 7, dtype: int64
Harrison 2018 7 71    101398
Name: 7, dtype: int64
Harrison 2019 7 71    94834
Name: 7, dtype: int64
Harrison 2013 8 70    104870
Name: 8, dtype: int64
Harrison 2014 8 70    100054
Name: 8, dtype: int64
Harrison 2015 8 71    111334
Name: 8, dtype: int64
Harrison 2016 8 71    101581
Name: 8, dtype: int64
Harrison 2017 8 71    113343
Name: 8, dtype: int64
Harrison 2018 8 71    0
Name: 8, dtype: int64
Harrison 2019 8 71    101487
Name: 8, dtype: int64
Harrison 2013 9 70    128416
Name: 9, dtype: int64
Harrison 2014 9 70    137286
Name: 9, dtype: int64
Harrison 2015 9 71    144293
Name: 9, dtype: int64
Harrison 2016 9 71    135264
Name: 9, dtype: int64
Harrison 2017 9 71    126502
Name: 9, dtype: int64
Harrison 2018 9 71    0
Name: 9, dtype: int64
Harrison 2019 9 71    114775
Name: 9, dtype: int64
Harrison 2013 10 70    147833
Name: 10, dtype: int64
Harrison 2014 10 70    152929
Name: 10, dtype: int64
Harrison 2015 10 71    159615
Name: 10, dtype: int64
Harrison 2016 10 71    152987
Name: 10, dtype: int64
Harrison 2017 10 71    140537
Name: 10, dtype: int64
Harrison 2018 10 71    0
Name: 10, dtype: int64
Harrison 2019 10 71    127892
Name: 10, dtype: int64
Harrison 2013 11 70    129216
Name: 11, dtype: int64
Harrison 2014 11 70    128439
Name: 11, dtype: int64
Harrison 2015 11 71    129163
Name: 11, dtype: int64
Harrison 2016 11 71    132304
Name: 11, dtype: int64
Harrison 2017 11 71    113213
Name: 11, dtype: int64
Harrison 2018 11 71    0
Name: 11, dtype: int64
Harrison 2019 11 71    106123
Name: 11, dtype: int64
Harrison 2013 12 70    98995
Name: 12, dtype: int64
Harrison 2014 12 70    103499
Name: 12, dtype: int64
Harrison 2015 12 71    109350
Name: 12, dtype: int64
Harrison 2016 12 71    100923
Name: 12, dtype: int64
Harrison 2017 12 71    91420
Name: 12, dtype: int64
Harrison 2018 12 71    0
Name: 12, dtype: int64
Harrison 2019 12 71    82647
Name: 12, dtype: int64
Howard 2013 1 71    166602
Name: 1, dtype: int64
Howard 2014 1 71    156378
Name: 1, dtype: int64
Howard 2015 1 72    157524
Name: 1, dtype: int64
Howard 2016 1 72    148439
Name: 1, dtype: int64
Howard 2017 1 72    144040
Name: 1, dtype: int64
Howard 2018 1 72    138102
Name: 1, dtype: int64
Howard 2019 1 72    126361
Name: 1, dtype: int64
Howard 2013 2 71    157737
Name: 2, dtype: int64
Howard 2014 2 71    156254
Name: 2, dtype: int64
Howard 2015 2 72    147405
Name: 2, dtype: int64
Howard 2016 2 72    149915
Name: 2, dtype: int64
Howard 2017 2 72    141316
Name: 2, dtype: int64
Howard 2018 2 72    128957
Name: 2, dtype: int64
Howard 2019 2 72    125736
Name: 2, dtype: int64
Howard 2013 3 71    171065
Name: 3, dtype: int64
Howard 2014 3 71    173393
Name: 3, dtype: int64
Howard 2015 3 72    169775
Name: 3, dtype: int64
Howard 2016 3 72    163758
Name: 3, dtype: int64
Howard 2017 3 72    159127
Name: 3, dtype: int64
Howard 2018 3 72    146006
Name: 3, dtype: int64
Howard 2019 3 72    138325
Name: 3, dtype: int64
Howard 2013 4 71    174487
Name: 4, dtype: int64
Howard 2014 4 71    170351
Name: 4, dtype: int64
Howard 2015 4 72    166882
Name: 4, dtype: int64
Howard 2016 4 72    158290
Name: 4, dtype: int64
Howard 2017 4 72    151280
Name: 4, dtype: int64
Howard 2018 4 72    143050
Name: 4, dtype: int64
Howard 2019 4 72    139365
Name: 4, dtype: int64
Howard 2013 5 71    177874
Name: 5, dtype: int64
Howard 2014 5 71    172836
Name: 5, dtype: int64
Howard 2015 5 72    184809
Name: 5, dtype: int64
Howard 2016 5 72    160931
Name: 5, dtype: int64
Howard 2017 5 72    161223
Name: 5, dtype: int64
Howard 2018 5 72    152838
Name: 5, dtype: int64
Howard 2019 5 72    146330
Name: 5, dtype: int64
Howard 2013 6 71    176163
Name: 6, dtype: int64
Howard 2014 6 71    169363
Name: 6, dtype: int64
Howard 2015 6 72    211828
Name: 6, dtype: int64
Howard 2016 6 72    162428
Name: 6, dtype: int64
Howard 2017 6 72    162589
Name: 6, dtype: int64
Howard 2018 6 72    149549
Name: 6, dtype: int64
Howard 2019 6 72    142680
Name: 6, dtype: int64
Howard 2013 7 71    177865
Name: 7, dtype: int64
Howard 2014 7 71    176348
Name: 7, dtype: int64
Howard 2015 7 72    216337
Name: 7, dtype: int64
Howard 2016 7 72    160606
Name: 7, dtype: int64
Howard 2017 7 72    157459
Name: 7, dtype: int64
Howard 2018 7 72    151008
Name: 7, dtype: int64
Howard 2019 7 72    143380
Name: 7, dtype: int64
Howard 2013 8 71    177354
Name: 8, dtype: int64
Howard 2014 8 71    173738
Name: 8, dtype: int64
Howard 2015 8 72    208851
Name: 8, dtype: int64
Howard 2016 8 72    164015
Name: 8, dtype: int64
Howard 2017 8 72    163960
Name: 8, dtype: int64
Howard 2018 8 72    0
Name: 8, dtype: int64
Howard 2019 8 72    143241
Name: 8, dtype: int64
Howard 2013 9 71    174991
Name: 9, dtype: int64
Howard 2014 9 71    178856
Name: 9, dtype: int64
Howard 2015 9 72    210504
Name: 9, dtype: int64
Howard 2016 9 72    163645
Name: 9, dtype: int64
Howard 2017 9 72    156121
Name: 9, dtype: int64
Howard 2018 9 72    0
Name: 9, dtype: int64
Howard 2019 9 72    138869
Name: 9, dtype: int64
Howard 2013 10 71    186262
Name: 10, dtype: int64
Howard 2014 10 71    188981
Name: 10, dtype: int64
Howard 2015 10 72    216262
Name: 10, dtype: int64
Howard 2016 10 72    171234
Name: 10, dtype: int64
Howard 2017 10 72    162931
Name: 10, dtype: int64
Howard 2018 10 72    0
Name: 10, dtype: int64
Howard 2019 10 72    147909
Name: 10, dtype: int64
Howard 2013 11 71    167002
Name: 11, dtype: int64

Howard 2014 11 71    163130
Name: 11, dtype: int64
Howard 2015 11 72    161435
Name: 11, dtype: int64
Howard 2016 11 72    157129
Name: 11, dtype: int64
Howard 2017 11 72    146809
Name: 11, dtype: int64
Howard 2018 11 72    0
Name: 11, dtype: int64
Howard 2019 11 72    132134
Name: 11, dtype: int64
Howard 2013 12 71    159052
Name: 12, dtype: int64
Howard 2014 12 71    164086
Name: 12, dtype: int64
Howard 2015 12 72    157698
Name: 12, dtype: int64
Howard 2016 12 72    144717
Name: 12, dtype: int64
Howard 2017 12 72    138017
Name: 12, dtype: int64
Howard 2018 12 72    0
Name: 12, dtype: int64
Howard 2019 12 72    126479
Name: 12, dtype: int64
Indiana 2013 1 72    23309
Name: 1, dtype: int64
Indiana 2014 1 72    23739
Name: 1, dtype: int64
Indiana 2015 1 73    21525
Name: 1, dtype: int64
Indiana 2016 1 73    21933
Name: 1, dtype: int64
Indiana 2017 1 73    19981
Name: 1, dtype: int64
Indiana 2018 1 73    19332
Name: 1, dtype: int64
Indiana 2019 1 73    17447
Name: 1, dtype: int64
Indiana 2013 2 72    22302
Name: 2, dtype: int64
Indiana 2014 2 72    25010
Name: 2, dtype: int64
Indiana 2015 2 73    20180
Name: 2, dtype: int64
Indiana 2016 2 73    22001
Name: 2, dtype: int64
Indiana 2017 2 73    19982
Name: 2, dtype: int64
Indiana 2018 2 73    18257
Name: 2, dtype: int64
Indiana 2019 2 73    17345
Name: 2, dtype: int64
Indiana 2013 3 72    23771
Name: 3, dtype: int64
Indiana 2014 3 72    27706
Name: 3, dtype: int64
Indiana 2015 3 73    23446
Name: 3, dtype: int64
Indiana 2016 3 73    23314
Name: 3, dtype: int64
Indiana 2017 3 73    22634
Name: 3, dtype: int64
Indiana 2018 3 73    20647
Name: 3, dtype: int64
Indiana 2019 3 73    19561
Name: 3, dtype: int64
Indiana 2013 4 72    25354
Name: 4, dtype: int64
Indiana 2014 4 72    24825
Name: 4, dtype: int64
Indiana 2015 4 73    23563
Name: 4, dtype: int64
Indiana 2016 4 73    21320
Name: 4, dtype: int64
Indiana 2017 4 73    21018
Name: 4, dtype: int64
Indiana 2018 4 73    20107
Name: 4, dtype: int64
Indiana 2019 4 73    19437
Name: 4, dtype: int64
Indiana 2013 5 72    29611
Name: 5, dtype: int64
Indiana 2014 5 72    26848
Name: 5, dtype: int64
Indiana 2015 5 73    25532
Name: 5, dtype: int64
Indiana 2016 5 73    22857
Name: 5, dtype: int64
Indiana 2017 5 73    22954
Name: 5, dtype: int64
Indiana 2018 5 73    22124
Name: 5, dtype: int64
Indiana 2019 5 73    21063
Name: 5, dtype: int64
Indiana 2013 6 72    33747
Name: 6, dtype: int64
Indiana 2014 6 72    26362
Name: 6, dtype: int64
Indiana 2015 6 73    25734
Name: 6, dtype: int64
Indiana 2016 6 73    23043
Name: 6, dtype: int64
Indiana 2017 6 73    23288
Name: 6, dtype: int64
Indiana 2018 6 73    21296
Name: 6, dtype: int64
Indiana 2019 6 73    19730
Name: 6, dtype: int64
Indiana 2013 7 72    37628
Name: 7, dtype: int64
Indiana 2014 7 72    28557
Name: 7, dtype: int64
Indiana 2015 7 73    27981
Name: 7, dtype: int64
Indiana 2016 7 73    23564
Name: 7, dtype: int64
Indiana 2017 7 73    22420
Name: 7, dtype: int64
Indiana 2018 7 73    22236
Name: 7, dtype: int64
Indiana 2019 7 73    21094
Name: 7, dtype: int64
Indiana 2013 8 72    39181
Name: 8, dtype: int64
Indiana 2014 8 72    27364
Name: 8, dtype: int64
Indiana 2015 8 73    26404
Name: 8, dtype: int64
Indiana 2016 8 73    22570
Name: 8, dtype: int64
Indiana 2017 8 73    23669
Name: 8, dtype: int64
Indiana 2018 8 73    0
Name: 8, dtype: int64
Indiana 2019 8 73    20554
Name: 8, dtype: int64
Indiana 2013 9 72    42324
Name: 9, dtype: int64
Indiana 2014 9 72    28575
Name: 9, dtype: int64
Indiana 2015 9 73    26624
Name: 9, dtype: int64
Indiana 2016 9 73    23851
Name: 9, dtype: int64
Indiana 2017 9 73    23422
Name: 9, dtype: int64
Indiana 2018 9 73    0
Name: 9, dtype: int64
Indiana 2019 9 73    20652
Name: 9, dtype: int64
Indiana 2013 10 72    40638
Name: 10, dtype: int64
Indiana 2014 10 72    29515
Name: 10, dtype: int64
Indiana 2015 10 73    28582
Name: 10, dtype: int64
Indiana 2016 10 73    24537
Name: 10, dtype: int64
Indiana 2017 10 73    25269
Name: 10, dtype: int64
Indiana 2018 10 73    0
Name: 10, dtype: int64
Indiana 2019 10 73    21396
Name: 10, dtype: int64
Indiana 2013 11 72    27416
Name: 11, dtype: int64
Indiana 2014 11 72    23050
Name: 11, dtype: int64
Indiana 2015 11 73    24273
Name: 11, dtype: int64
Indiana 2016 11 73    22834
Name: 11, dtype: int64
Indiana 2017 11 73    22226
Name: 11, dtype: int64
Indiana 2018 11 73    0
Name: 11, dtype: int64
Indiana 2019 11 73    17549
Name: 11, dtype: int64
Indiana 2013 12 72    25861
Name: 12, dtype: int64
Indiana 2014 12 72    22947
Name: 12, dtype: int64
Indiana 2015 12 73    23290
Name: 12, dtype: int64
Indiana 2016 12 73    20063
Name: 12, dtype: int64
Indiana 2017 12 73    19986
Name: 12, dtype: int64
Indiana 2018 12 73    0
Name: 12, dtype: int64
Indiana 2019 12 73    16135
Name: 12, dtype: int64
Irving Park-Brown 2013 1 73    79984
Name: 1, dtype: int64
Irving Park-Brown 2014 1 73    78434
Name: 1, dtype: int64
Irving Park-Brown 2015 1 74    75956
Name: 1, dtype: int64
Irving Park-Brown 2016 1 74    76495
Name: 1, dtype: int64
Irving Park-Brown 2017 1 74    77199
Name: 1, dtype: int64
Irving Park-Brown 2018 1 74    79317
Name: 1, dtype: int64
Irving Park-Brown 2019 1 74    73619
Name: 1, dtype: int64
Irving Park-Brown 2013 2 73    74934
Name: 2, dtype: int64
Irving Park-Brown 2014 2 73    78585
Name: 2, dtype: int64
Irving Park-Brown 2015 2 74    74192
Name: 2, dtype: int64
Irving Park-Brown 2016 2 74    76541
Name: 2, dtype: int64
Irving Park-Brown 2017 2 74    73467
Name: 2, dtype: int64
Irving Park-Brown 2018 2 74    74419
Name: 2, dtype: int64
Irving Park-Brown 2019 2 74    74172
Name: 2, dtype: int64
Irving Park-Brown 2013 3 73    77431
Name: 3, dtype: int64
Irving Park-Brown 2014 3 73    86941
Name: 3, dtype: int64
Irving Park-Brown 2015 3 74    83303
Name: 3, dtype: int64
Irving Park-Brown 2016 3 74    85526
Name: 3, dtype: int64
Irving Park-Brown 2017 3 74    84513
Name: 3, dtype: int64
Irving Park-Brown 2018 3 74    83916
Name: 3, dtype: int64
Irving Park-Brown 2019 3 74    81058
Name: 3, dtype: int64
Irving Park-Brown 2013 4 73    79470
Name: 4, dtype: int64
Irving Park-Brown 2014 4 73    84510
Name: 4, dtype: int64
Irving Park-Brown 2015 4 74    78670
Name: 4, dtype: int64
Irving Park-Brown 2016 4 74    81013
Name: 4, dtype: int64
Irving Park-Brown 2017 4 74    76556
Name: 4, dtype: int64
Irving Park-Brown 2018 4 74    80028
Name: 4, dtype: int64
Irving Park-Brown 2019 4 74    79526
Name: 4, dtype: int64
Irving Park-Brown 2013 5 73    80622
Name: 5, dtype: int64
Irving Park-Brown 2014 5 73    84404
Name: 5, dtype: int64
Irving Park-Brown 2015 5 74    79987
Name: 5, dtype: int64
Irving Park-Brown 2016 5 74    83223
Name: 5, dtype: int64
Irving Park-Brown 2017 5 74    85274
Name: 5, dtype: int64
Irving Park-Brown 2018 5 74    86882
Name: 5, dtype: int64
Irving Park-Brown 2019 5 74    84663
Name: 5, dtype: int64
Irving Park-Brown 2013 6 73    87929
Name: 6, dtype: int64
Irving Park-Brown 2014 6 73    92659
Name: 6, dtype: int64
Irving Park-Brown 2015 6 74    87843
Name: 6, dtype: int64
Irving Park-Brown 2016 6 74    92771
Name: 6, dtype: int64
Irving Park-Brown 2017 6 74    92554
Name: 6, dtype: int64
Irving Park-Brown 2018 6 74    87291
Name: 6, dtype: int64
Irving Park-Brown 2019 6 74    83877
Name: 6, dtype: int64
Irving Park-Brown 2013 7 73    79976
Name: 7, dtype: int64
Irving Park-Brown 2014 7 73    83834
Name: 7, dtype: int64
Irving Park-Brown 2015 7 74    83165
Name: 7, dtype: int64
Irving Park-Brown 2016 7 74    80617
Name: 7, dtype: int64
Irving Park-Brown 2017 7 74    80830
Name: 7, dtype: int64
Irving Park-Brown 2018 7 74    0
Name: 7, dtype: int64
Irving Park-Brown 2019 7 74    79987
Name: 7, dtype: int64
Irving Park-Brown 2013 8 73    82436
Name: 8, dtype: int64
Irving Park-Brown 2014 8 73    81600
Name: 8, dtype: int64
Irving Park-Brown 2015 8 74    79181
Name: 8, dtype: int64
Irving Park-Brown 2016 8 74    82823
Name: 8, dtype: int64
Irving Park-Brown 2017 8 74    87350
Name: 8, dtype: int64
Irving Park-Brown 2018 8 74    0
Name: 8, dtype: int64
Irving Park-Brown 2019 8 74    80646
Name: 8, dtype: int64
Irving Park-Brown 2013 9 73    81607
Name: 9, dtype: int64
Irving Park-Brown 2014 9 73    83247
Name: 9, dtype: int64
Irving Park-Brown 2015 9 74    81105
Name: 9, dtype: int64
Irving Park-Brown 2016 9 74    82649
Name: 9, dtype: int64
Irving Park-Brown 2017 9 74    85644
Name: 9, dtype: int64
Irving Park-Brown 2018 9 74    0
Name: 9, dtype: int64
Irving Park-Brown 2019 9 74    81072
Name: 9, dtype: int64
Irving Park-Brown 2013 10 73    90422
Name: 10, dtype: int64
Irving Park-Brown 2014 10 73    90056
Name: 10, dtype: int64
Irving Park-Brown 2015 10 74    86415
Name: 10, dtype: int64
Irving Park-Brown 2016 10 74    86708
Name: 10, dtype: int64
Irving Park-Brown 2017 10 74    89089
Name: 10, dtype: int64
Irving Park-Brown 2018 10 74    0
Name: 10, dtype: int64
Irving Park-Brown 2019 10 74    87000
Name: 10, dtype: int64
Irving Park-Brown 2013 11 73    79176
Name: 11, dtype: int64
Irving Park-Brown 2014 11 73    75453
Name: 11, dtype: int64
Irving Park-Brown 2015 11 74    77137
Name: 11, dtype: int64
Irving Park-Brown 2016 11 74    80366
Name: 11, dtype: int64
Irving Park-Brown 2017 11 74    79858
Name: 11, dtype: int64
Irving Park-Brown 2018 11 74    0
Name: 11, dtype: int64
Irving Park-Brown 2019 11 74    73464
Name: 11, dtype: int64
Irving Park-Brown 2013 12 73    74454
Name: 12, dtype: int64
Irving Park-Brown 2014 12 73    75561
Name: 12, dtype: int64
Irving Park-Brown 2015 12 74    75685
Name: 12, dtype: int64
Irving Park-Brown 2016 12 74    71944
Name: 12, dtype: int64
Irving Park-Brown 2017 12 74    71514
Name: 12, dtype: int64
Irving Park-Brown 2018 12 74    0
Name: 12, dtype: int64
Irving Park-Brown 2019 12 74    68254
Name: 12, dtype: int64
Irving Park-O'Hare 2013 1 74    109918
Name: 1, dtype: int64
Irving Park-O'Hare 2014 1 74    103929
Name: 1, dtype: int64
Irving Park-O'Hare 2015 1 75    107934
Name: 1, dtype: int64
Irving Park-O'Hare 2016 1 75    108824
Name: 1, dtype: int64
Irving Park-O'Hare 2017 1 75    102786
Name: 1, dtype: int64
Irving Park-O'Hare 2018 1 75    104014
Name: 1, dtype: int64
Irving Park-O'Hare 2019 1 75    96138
Name: 1, dtype: int64
Irving Park-O'Hare 2013 2 74    102456
Name: 2, dtype: int64
Irving Park-O'Hare 2014 2 74    105970
Name: 2, dtype: int64
Irving Park-O'Hare 2015 2 75    103183
Name: 2, dtype: int64
Irving Park-O'Hare 2016 2 75    109482
Name: 2, dtype: int64
Irving Park-O'Hare 2017 2 75    96741
Name: 2, dtype: int64
Irving Park-O'Hare 2018 2 75    98524
Name: 2, dtype: int64
Irving Park-O'Hare 2019 2 75    95823
Name: 2, dtype: int64
Irving Park-O'Hare 2013 3 74    113443
Name: 3, dtype: int64
Irving Park-O'Hare 2014 3 74    116509
Name: 3, dtype: int64
Irving Park-O'Hare 2015 3 75    121038
Name: 3, dtype: int64
Irving Park-O'Hare 2016 3 75    128773
Name: 3, dtype: int64
Irving Park-O'Hare 2017 3 75    112869
Name: 3, dtype: int64
Irving Park-O'Hare 2018 3 75    112961
Name: 3, dtype: int64
Irving Park-O'Hare 2019 3 75    107032
Name: 3, dtype: int64
Irving Park-O'Hare 2013 4 74    114274
Name: 4, dtype: int64
Irving Park-O'Hare 2014 4 74    115472
Name: 4, dtype: int64
Irving Park-O'Hare 2015 4 75    118861
Name: 4, dtype: int64
Irving Park-O'Hare 2016 4 75    123179
Name: 4, dtype: int64
Irving Park-O'Hare 2017 4 75    105642
Name: 4, dtype: int64
Irving Park-O'Hare 2018 4 75    108460
Name: 4, dtype: int64
Irving Park-O'Hare 2019 4 75    106092
Name: 4, dtype: int64
Irving Park-O'Hare 2013 5 74    119473
Name: 5, dtype: int64
Irving Park-O'Hare 2014 5 74    118228
Name: 5, dtype: int64
Irving Park-O'Hare 2015 5 75    119677
Name: 5, dtype: int64
Irving Park-O'Hare 2016 5 75    129340
Name: 5, dtype: int64
Irving Park-O'Hare 2017 5 75    115560
Name: 5, dtype: int64
Irving Park-O'Hare 2018 5 75    116472
Name: 5, dtype: int64
Irving Park-O'Hare 2019 5 75    113610
Name: 5, dtype: int64
Irving Park-O'Hare 2013 6 74    118540
Name: 6, dtype: int64
Irving Park-O'Hare 2014 6 74    115688
Name: 6, dtype: int64
Irving Park-O'Hare 2015 6 75    125534
Name: 6, dtype: int64
Irving Park-O'Hare 2016 6 75    128704
Name: 6, dtype: int64
Irving Park-O'Hare 2017 6 75    119005
Name: 6, dtype: int64
Irving Park-O'Hare 2018 6 75    114666
Name: 6, dtype: int64
Irving Park-O'Hare 2019 6 75    110445
Name: 6, dtype: int64
Irving Park-O'Hare 2013 7 74    120304
Name: 7, dtype: int64
Irving Park-O'Hare 2014 7 74    119713
Name: 7, dtype: int64
Irving Park-O'Hare 2015 7 75    128297
Name: 7, dtype: int64
Irving Park-O'Hare 2016 7 75    90853
Name: 7, dtype: int64
Irving Park-O'Hare 2017 7 75    113113
Name: 7, dtype: int64
Irving Park-O'Hare 2018 7 75    112037
Name: 7, dtype: int64
Irving Park-O'Hare 2019 7 75    113997
Name: 7, dtype: int64
Irving Park-O'Hare 2013 8 74    122885
Name: 8, dtype: int64
Irving Park-O'Hare 2014 8 74    117540
Name: 8, dtype: int64
Irving Park-O'Hare 2015 8 75    125470
Name: 8, dtype: int64
Irving Park-O'Hare 2016 8 75    102388
Name: 8, dtype: int64
Irving Park-O'Hare 2017 8 75    121966
Name: 8, dtype: int64
Irving Park-O'Hare 2018 8 75    0
Name: 8, dtype: int64
Irving Park-O'Hare 2019 8 75    113175
Name: 8, dtype: int64
Irving Park-O'Hare 2013 9 74    120678
Name: 9, dtype: int64
Irving Park-O'Hare 2014 9 74    121658
Name: 9, dtype: int64
Irving Park-O'Hare 2015 9 75    125904
Name: 9, dtype: int64
Irving Park-O'Hare 2016 9 75    112571
Name: 9, dtype: int64
Irving Park-O'Hare 2017 9 75    116219
Name: 9, dtype: int64
Irving Park-O'Hare 2018 9 75    0
Name: 9, dtype: int64
Irving Park-O'Hare 2019 9 75    109098
Name: 9, dtype: int64
Irving Park-O'Hare 2013 10 74    130437
Name: 10, dtype: int64
Irving Park-O'Hare 2014 10 74    130003
Name: 10, dtype: int64
Irving Park-O'Hare 2015 10 75    130680
Name: 10, dtype: int64
Irving Park-O'Hare 2016 10 75    114151
Name: 10, dtype: int64
Irving Park-O'Hare 2017 10 75    120846
Name: 10, dtype: int64
Irving Park-O'Hare 2018 10 75    0
Name: 10, dtype: int64
Irving Park-O'Hare 2019 10 75    117404
Name: 10, dtype: int64
Irving Park-O'Hare 2013 11 74    115795
Name: 11, dtype: int64
Irving Park-O'Hare 2014 11 74    110575
Name: 11, dtype: int64
Irving Park-O'Hare 2015 11 75    115765
Name: 11, dtype: int64
Irving Park-O'Hare 2016 11 75    110633
Name: 11, dtype: int64
Irving Park-O'Hare 2017 11 75    110740
Name: 11, dtype: int64
Irving Park-O'Hare 2018 11 75    0
Name: 11, dtype: int64
Irving Park-O'Hare 2019 11 75    102906
Name: 11, dtype: int64
Irving Park-O'Hare 2013 12 74    108705
Name: 12, dtype: int64
Irving Park-O'Hare 2014 12 74    113062
Name: 12, dtype: int64
Irving Park-O'Hare 2015 12 75    116226
Name: 12, dtype: int64
Irving Park-O'Hare 2016 12 75    101010
Name: 12, dtype: int64
Irving Park-O'Hare 2017 12 75    101746
Name: 12, dtype: int64
Irving Park-O'Hare 2018 12 75    0
Name: 12, dtype: int64
Irving Park-O'Hare 2019 12 75    98087
Name: 12, dtype: int64
Jackson/Dearborn 2013 1 75    190941
Name: 1, dtype: int64
Jackson/Dearborn 2014 1 75    172017
Name: 1, dtype: int64
Jackson/Dearborn 2015 1 76    178176
Name: 1, dtype: int64
Jackson/Dearborn 2016 1 76    174018
Name: 1, dtype: int64
Jackson/Dearborn 2017 1 76    177999
Name: 1, dtype: int64
Jackson/Dearborn 2018 1 76    163095
Name: 1, dtype: int64
Jackson/Dearborn 2019 1 76    145263
Name: 1, dtype: int64
Jackson/Dearborn 2013 2 75    186888
Name: 2, dtype: int64
Jackson/Dearborn 2014 2 75    180342
Name: 2, dtype: int64
Jackson/Dearborn 2015 2 76    174652

Name: 2, dtype: int64
Jackson/Dearborn 2016 2 76    187164
Name: 2, dtype: int64
Jackson/Dearborn 2017 2 76    169692
Name: 2, dtype: int64
Jackson/Dearborn 2018 2 76    155711
Name: 2, dtype: int64
Jackson/Dearborn 2019 2 76    158517
Name: 2, dtype: int64
Jackson/Dearborn 2013 3 75    199500
Name: 3, dtype: int64
Jackson/Dearborn 2014 3 75    199230
Name: 3, dtype: int64
Jackson/Dearborn 2015 3 76    204129
Name: 3, dtype: int64
Jackson/Dearborn 2016 3 76    205493
Name: 3, dtype: int64
Jackson/Dearborn 2017 3 76    193063
Name: 3, dtype: int64
Jackson/Dearborn 2018 3 76    179592
Name: 3, dtype: int64
Jackson/Dearborn 2019 3 76    168616
Name: 3, dtype: int64
Jackson/Dearborn 2013 4 75    212025
Name: 4, dtype: int64
Jackson/Dearborn 2014 4 75    201496
Name: 4, dtype: int64
Jackson/Dearborn 2015 4 76    206182
Name: 4, dtype: int64
Jackson/Dearborn 2016 4 76    198723
Name: 4, dtype: int64
Jackson/Dearborn 2017 4 76    180027
Name: 4, dtype: int64
Jackson/Dearborn 2018 4 76    177306
Name: 4, dtype: int64
Jackson/Dearborn 2019 4 76    173389
Name: 4, dtype: int64
Jackson/Dearborn 2013 5 75    210450
Name: 5, dtype: int64
Jackson/Dearborn 2014 5 75    198633
Name: 5, dtype: int64
Jackson/Dearborn 2015 5 76    199813
Name: 5, dtype: int64
Jackson/Dearborn 2016 5 76    193131
Name: 5, dtype: int64
Jackson/Dearborn 2017 5 76    188624
Name: 5, dtype: int64
Jackson/Dearborn 2018 5 76    180617
Name: 5, dtype: int64
Jackson/Dearborn 2019 5 76    174352
Name: 5, dtype: int64
Jackson/Dearborn 2013 6 75    206075
Name: 6, dtype: int64
Jackson/Dearborn 2014 6 75    196137
Name: 6, dtype: int64
Jackson/Dearborn 2015 6 76    205549
Name: 6, dtype: int64
Jackson/Dearborn 2016 6 76    202388
Name: 6, dtype: int64
Jackson/Dearborn 2017 6 76    188145
Name: 6, dtype: int64
Jackson/Dearborn 2018 6 76    167310
Name: 6, dtype: int64
Jackson/Dearborn 2019 6 76    163041
Name: 6, dtype: int64
Jackson/Dearborn 2013 7 75    219046
Name: 7, dtype: int64
Jackson/Dearborn 2014 7 75    207999
Name: 7, dtype: int64
Jackson/Dearborn 2015 7 76    220079
Name: 7, dtype: int64
Jackson/Dearborn 2016 7 76    203076
Name: 7, dtype: int64
Jackson/Dearborn 2017 7 76    169403
Name: 7, dtype: int64
Jackson/Dearborn 2018 7 76    169083
Name: 7, dtype: int64
Jackson/Dearborn 2019 7 76    170661
Name: 7, dtype: int64
Jackson/Dearborn 2013 8 75    220646
Name: 8, dtype: int64
Jackson/Dearborn 2014 8 75    203665
Name: 8, dtype: int64
Jackson/Dearborn 2015 8 76    202701
Name: 8, dtype: int64
Jackson/Dearborn 2016 8 76    192424
Name: 8, dtype: int64
Jackson/Dearborn 2017 8 76    193599
Name: 8, dtype: int64
Jackson/Dearborn 2018 8 76    0
Name: 8, dtype: int64
Jackson/Dearborn 2019 8 76    182244
Name: 8, dtype: int64
Jackson/Dearborn 2013 9 75    213717
Name: 9, dtype: int64
Jackson/Dearborn 2014 9 75    211559
Name: 9, dtype: int64
Jackson/Dearborn 2015 9 76    214158
Name: 9, dtype: int64
Jackson/Dearborn 2016 9 76    201489
Name: 9, dtype: int64
Jackson/Dearborn 2017 9 76    184367
Name: 9, dtype: int64
Jackson/Dearborn 2018 9 76    0
Name: 9, dtype: int64
Jackson/Dearborn 2019 9 76    183231
Name: 9, dtype: int64
Jackson/Dearborn 2013 10 75    241020
Name: 10, dtype: int64
Jackson/Dearborn 2014 10 75    235695
Name: 10, dtype: int64
Jackson/Dearborn 2015 10 76    233401
Name: 10, dtype: int64
Jackson/Dearborn 2016 10 76    213433
Name: 10, dtype: int64
Jackson/Dearborn 2017 10 76    205370
Name: 10, dtype: int64
Jackson/Dearborn 2018 10 76    0
Name: 10, dtype: int64
Jackson/Dearborn 2019 10 76    210043
Name: 10, dtype: int64
Jackson/Dearborn 2013 11 75    196193
Name: 11, dtype: int64
Jackson/Dearborn 2014 11 75    184007
Name: 11, dtype: int64
Jackson/Dearborn 2015 11 76    193179
Name: 11, dtype: int64
Jackson/Dearborn 2016 11 76    196874
Name: 11, dtype: int64
Jackson/Dearborn 2017 11 76    172409
Name: 11, dtype: int64
Jackson/Dearborn 2018 11 76    0
Name: 11, dtype: int64
Jackson/Dearborn 2019 11 76    164672
Name: 11, dtype: int64
Jackson/Dearborn 2013 12 75    162972
Name: 12, dtype: int64
Jackson/Dearborn 2014 12 75    166772
Name: 12, dtype: int64
Jackson/Dearborn 2015 12 76    169742
Name: 12, dtype: int64
Jackson/Dearborn 2016 12 76    151256
Name: 12, dtype: int64
Jackson/Dearborn 2017 12 76    136881
Name: 12, dtype: int64
Jackson/Dearborn 2018 12 76    0
Name: 12, dtype: int64
Jackson/Dearborn 2019 12 76    137300
Name: 12, dtype: int64
Jackson/State 2013 1 76    278342
Name: 1, dtype: int64
Jackson/State 2014 1 76    250993
Name: 1, dtype: int64
Jackson/State 2015 1 77    265009
Name: 1, dtype: int64
Jackson/State 2016 1 77    263237
Name: 1, dtype: int64
Jackson/State 2017 1 77    267646
Name: 1, dtype: int64
Jackson/State 2018 1 77    235052
Name: 1, dtype: int64
Jackson/State 2019 1 77    200023
Name: 1, dtype: int64
Jackson/State 2013 2 76    255176
Name: 2, dtype: int64
Jackson/State 2014 2 76    262283
Name: 2, dtype: int64
Jackson/State 2015 2 77    249912
Name: 2, dtype: int64
Jackson/State 2016 2 77    286263
Name: 2, dtype: int64
Jackson/State 2017 2 77    251331
Name: 2, dtype: int64
Jackson/State 2018 2 77    219579
Name: 2, dtype: int64
Jackson/State 2019 2 77    220823
Name: 2, dtype: int64
Jackson/State 2013 3 76    296256
Name: 3, dtype: int64
Jackson/State 2014 3 76    275403
Name: 3, dtype: int64
Jackson/State 2015 3 77    284886
Name: 3, dtype: int64
Jackson/State 2016 3 77    290335
Name: 3, dtype: int64
Jackson/State 2017 3 77    274194
Name: 3, dtype: int64
Jackson/State 2018 3 77    237996
Name: 3, dtype: int64
Jackson/State 2019 3 77    216428
Name: 3, dtype: int64
Jackson/State 2013 4 76    314802
Name: 4, dtype: int64
Jackson/State 2014 4 76    299050
Name: 4, dtype: int64
Jackson/State 2015 4 77    306544
Name: 4, dtype: int64
Jackson/State 2016 4 77    301496
Name: 4, dtype: int64
Jackson/State 2017 4 77    263892
Name: 4, dtype: int64
Jackson/State 2018 4 77    245818
Name: 4, dtype: int64
Jackson/State 2019 4 77    236655
Name: 4, dtype: int64
Jackson/State 2013 5 76    293658
Name: 5, dtype: int64
Jackson/State 2014 5 76    293131
Name: 5, dtype: int64
Jackson/State 2015 5 77    297184
Name: 5, dtype: int64
Jackson/State 2016 5 77    289137
Name: 5, dtype: int64
Jackson/State 2017 5 77    277923
Name: 5, dtype: int64
Jackson/State 2018 5 77    240849
Name: 5, dtype: int64
Jackson/State 2019 5 77    232253
Name: 5, dtype: int64
Jackson/State 2013 6 76    242682
Name: 6, dtype: int64
Jackson/State 2014 6 76    279948
Name: 6, dtype: int64
Jackson/State 2015 6 77    281020
Name: 6, dtype: int64
Jackson/State 2016 6 77    272869
Name: 6, dtype: int64
Jackson/State 2017 6 77    246685
Name: 6, dtype: int64
Jackson/State 2018 6 77    204018
Name: 6, dtype: int64
Jackson/State 2019 6 77    195757
Name: 6, dtype: int64
Jackson/State 2013 7 76    249419
Name: 7, dtype: int64
Jackson/State 2014 7 76    285931
Name: 7, dtype: int64
Jackson/State 2015 7 77    293000
Name: 7, dtype: int64
Jackson/State 2016 7 77    266585
Name: 7, dtype: int64
Jackson/State 2017 7 77    221508
Name: 7, dtype: int64
Jackson/State 2018 7 77    205844
Name: 7, dtype: int64
Jackson/State 2019 7 77    203052
Name: 7, dtype: int64
Jackson/State 2013 8 76    250777
Name: 8, dtype: int64
Jackson/State 2014 8 76    264623
Name: 8, dtype: int64
Jackson/State 2015 8 77    268742
Name: 8, dtype: int64
Jackson/State 2016 8 77    252144
Name: 8, dtype: int64
Jackson/State 2017 8 77    243226
Name: 8, dtype: int64
Jackson/State 2018 8 77    0
Name: 8, dtype: int64
Jackson/State 2019 8 77    208505
Name: 8, dtype: int64
Jackson/State 2013 9 76    275827
Name: 9, dtype: int64
Jackson/State 2014 9 76    308996
Name: 9, dtype: int64
Jackson/State 2015 9 77    320656
Name: 9, dtype: int64
Jackson/State 2016 9 77    295896
Name: 9, dtype: int64
Jackson/State 2017 9 77    265303
Name: 9, dtype: int64
Jackson/State 2018 9 77    0
Name: 9, dtype: int64
Jackson/State 2019 9 77    234496
Name: 9, dtype: int64
Jackson/State 2013 10 76    325767
Name: 10, dtype: int64
Jackson/State 2014 10 76    350435
Name: 10, dtype: int64
Jackson/State 2015 10 77    342859
Name: 10, dtype: int64
Jackson/State 2016 10 77    314932
Name: 10, dtype: int64
Jackson/State 2017 10 77    295324
Name: 10, dtype: int64
Jackson/State 2018 10 77    0
Name: 10, dtype: int64
Jackson/State 2019 10 77    279576
Name: 10, dtype: int64
Jackson/State 2013 11 76    264428
Name: 11, dtype: int64
Jackson/State 2014 11 76    273195
Name: 11, dtype: int64
Jackson/State 2015 11 77    269751
Name: 11, dtype: int64
Jackson/State 2016 11 77    271701
Name: 11, dtype: int64
Jackson/State 2017 11 77    224645
Name: 11, dtype: int64
Jackson/State 2018 11 77    0
Name: 11, dtype: int64
Jackson/State 2019 11 77    215406
Name: 11, dtype: int64
Jackson/State 2013 12 76    199251
Name: 12, dtype: int64
Jackson/State 2014 12 76    217332
Name: 12, dtype: int64
Jackson/State 2015 12 77    210407
Name: 12, dtype: int64
Jackson/State 2016 12 77    191852
Name: 12, dtype: int64
Jackson/State 2017 12 77    163111
Name: 12, dtype: int64
Jackson/State 2018 12 77    0
Name: 12, dtype: int64
Jackson/State 2019 12 77    158613
Name: 12, dtype: int64
Jarvis 2013 1 77    36690
Name: 1, dtype: int64
Jarvis 2014 1 77    43795
Name: 1, dtype: int64
Jarvis 2015 1 78    44977
Name: 1, dtype: int64
Jarvis 2016 1 78    45039
Name: 1, dtype: int64
Jarvis 2017 1 78    43454
Name: 1, dtype: int64
Jarvis 2018 1 78    39882
Name: 1, dtype: int64
Jarvis 2019 1 78    36453
Name: 1, dtype: int64
Jarvis 2013 2 77    36304
Name: 2, dtype: int64
Jarvis 2014 2 77    43025
Name: 2, dtype: int64
Jarvis 2015 2 78    42601
Name: 2, dtype: int64
Jarvis 2016 2 78    45282
Name: 2, dtype: int64
Jarvis 2017 2 78    41513
Name: 2, dtype: int64
Jarvis 2018 2 78    38225
Name: 2, dtype: int64
Jarvis 2019 2 78    36710
Name: 2, dtype: int64
Jarvis 2013 3 77    41930
Name: 3, dtype: int64
Jarvis 2014 3 77    47452
Name: 3, dtype: int64
Jarvis 2015 3 78    47849
Name: 3, dtype: int64
Jarvis 2016 3 78    49519
Name: 3, dtype: int64
Jarvis 2017 3 78    45891
Name: 3, dtype: int64
Jarvis 2018 3 78    42716
Name: 3, dtype: int64
Jarvis 2019 3 78    40430
Name: 3, dtype: int64
Jarvis 2013 4 77    41927
Name: 4, dtype: int64
Jarvis 2014 4 77    46612
Name: 4, dtype: int64
Jarvis 2015 4 78    48276
Name: 4, dtype: int64
Jarvis 2016 4 78    47623
Name: 4, dtype: int64
Jarvis 2017 4 78    43552
Name: 4, dtype: int64
Jarvis 2018 4 78    41023
Name: 4, dtype: int64
Jarvis 2019 4 78    39651
Name: 4, dtype: int64
Jarvis 2013 5 77    43231
Name: 5, dtype: int64
Jarvis 2014 5 77    48888
Name: 5, dtype: int64
Jarvis 2015 5 78    48927
Name: 5, dtype: int64
Jarvis 2016 5 78    48488
Name: 5, dtype: int64
Jarvis 2017 5 78    45397
Name: 5, dtype: int64
Jarvis 2018 5 78    43355
Name: 5, dtype: int64
Jarvis 2019 5 78    41696
Name: 5, dtype: int64
Jarvis 2013 6 77    44774
Name: 6, dtype: int64
Jarvis 2014 6 77    48950
Name: 6, dtype: int64
Jarvis 2015 6 78    50374
Name: 6, dtype: int64
Jarvis 2016 6 78    49137
Name: 6, dtype: int64
Jarvis 2017 6 78    47877
Name: 6, dtype: int64
Jarvis 2018 6 78    42641
Name: 6, dtype: int64
Jarvis 2019 6 78    42046
Name: 6, dtype: int64

Jarvis 2013 7 77    47070
Name: 7, dtype: int64
Jarvis 2014 7 77    49363
Name: 7, dtype: int64
Jarvis 2015 7 78    51204
Name: 7, dtype: int64
Jarvis 2016 7 78    47672
Name: 7, dtype: int64
Jarvis 2017 7 78    46311
Name: 7, dtype: int64
Jarvis 2018 7 78    43658
Name: 7, dtype: int64
Jarvis 2019 7 78    41542
Name: 7, dtype: int64
Jarvis 2013 8 77    48252
Name: 8, dtype: int64
Jarvis 2014 8 77    50106
Name: 8, dtype: int64
Jarvis 2015 8 78    49944
Name: 8, dtype: int64
Jarvis 2016 8 78    48465
Name: 8, dtype: int64
Jarvis 2017 8 78    47829
Name: 8, dtype: int64
Jarvis 2018 8 78    0
Name: 8, dtype: int64
Jarvis 2019 8 78    42277
Name: 8, dtype: int64
Jarvis 2013 9 77    48167
Name: 9, dtype: int64
Jarvis 2014 9 77    50106
Name: 9, dtype: int64
Jarvis 2015 9 78    52027
Name: 9, dtype: int64
Jarvis 2016 9 78    49477
Name: 9, dtype: int64
Jarvis 2017 9 78    46733
Name: 9, dtype: int64
Jarvis 2018 9 78    0
Name: 9, dtype: int64
Jarvis 2019 9 78    40989
Name: 9, dtype: int64
Jarvis 2013 10 77    51321
Name: 10, dtype: int64
Jarvis 2014 10 77    52335
Name: 10, dtype: int64
Jarvis 2015 10 78    52907
Name: 10, dtype: int64
Jarvis 2016 10 78    48719
Name: 10, dtype: int64
Jarvis 2017 10 78    46556
Name: 10, dtype: int64
Jarvis 2018 10 78    0
Name: 10, dtype: int64
Jarvis 2019 10 78    42962
Name: 10, dtype: int64
Jarvis 2013 11 77    45621
Name: 11, dtype: int64
Jarvis 2014 11 77    45947
Name: 11, dtype: int64
Jarvis 2015 11 78    45983
Name: 11, dtype: int64
Jarvis 2016 11 78    47003
Name: 11, dtype: int64
Jarvis 2017 11 78    42640
Name: 11, dtype: int64
Jarvis 2018 11 78    0
Name: 11, dtype: int64
Jarvis 2019 11 78    38171
Name: 11, dtype: int64
Jarvis 2013 12 77    42745
Name: 12, dtype: int64
Jarvis 2014 12 77    45038
Name: 12, dtype: int64
Jarvis 2015 12 78    46376
Name: 12, dtype: int64
Jarvis 2016 12 78    42966
Name: 12, dtype: int64
Jarvis 2017 12 78    39589
Name: 12, dtype: int64
Jarvis 2018 12 78    0
Name: 12, dtype: int64
Jarvis 2019 12 78    36535
Name: 12, dtype: int64
Jefferson Park 2013 1 78    162543
Name: 1, dtype: int64
Jefferson Park 2014 1 78    159462
Name: 1, dtype: int64
Jefferson Park 2015 1 79    163242
Name: 1, dtype: int64
Jefferson Park 2016 1 79    165621
Name: 1, dtype: int64
Jefferson Park 2017 1 79    167329
Name: 1, dtype: int64
Jefferson Park 2018 1 79    161711
Name: 1, dtype: int64
Jefferson Park 2019 1 79    139394
Name: 1, dtype: int64
Jefferson Park 2013 2 78    152599
Name: 2, dtype: int64
Jefferson Park 2014 2 78    158924
Name: 2, dtype: int64
Jefferson Park 2015 2 79    153511
Name: 2, dtype: int64
Jefferson Park 2016 2 79    167946
Name: 2, dtype: int64
Jefferson Park 2017 2 79    159040
Name: 2, dtype: int64
Jefferson Park 2018 2 79    152239
Name: 2, dtype: int64
Jefferson Park 2019 2 79    139322
Name: 2, dtype: int64
Jefferson Park 2013 3 78    169760
Name: 3, dtype: int64
Jefferson Park 2014 3 78    177768
Name: 3, dtype: int64
Jefferson Park 2015 3 79    180625
Name: 3, dtype: int64
Jefferson Park 2016 3 79    185833
Name: 3, dtype: int64
Jefferson Park 2017 3 79    180243
Name: 3, dtype: int64
Jefferson Park 2018 3 79    173603
Name: 3, dtype: int64
Jefferson Park 2019 3 79    156216
Name: 3, dtype: int64
Jefferson Park 2013 4 78    176344
Name: 4, dtype: int64
Jefferson Park 2014 4 78    177193
Name: 4, dtype: int64
Jefferson Park 2015 4 79    178902
Name: 4, dtype: int64
Jefferson Park 2016 4 79    178752
Name: 4, dtype: int64
Jefferson Park 2017 4 79    166832
Name: 4, dtype: int64
Jefferson Park 2018 4 79    167226
Name: 4, dtype: int64
Jefferson Park 2019 4 79    157455
Name: 4, dtype: int64
Jefferson Park 2013 5 78    181396
Name: 5, dtype: int64
Jefferson Park 2014 5 78    182394
Name: 5, dtype: int64
Jefferson Park 2015 5 79    179346
Name: 5, dtype: int64
Jefferson Park 2016 5 79    188226
Name: 5, dtype: int64
Jefferson Park 2017 5 79    181283
Name: 5, dtype: int64
Jefferson Park 2018 5 79    178553
Name: 5, dtype: int64
Jefferson Park 2019 5 79    164524
Name: 5, dtype: int64
Jefferson Park 2013 6 78    176669
Name: 6, dtype: int64
Jefferson Park 2014 6 78    180098
Name: 6, dtype: int64
Jefferson Park 2015 6 79    189871
Name: 6, dtype: int64
Jefferson Park 2016 6 79    189405
Name: 6, dtype: int64
Jefferson Park 2017 6 79    182252
Name: 6, dtype: int64
Jefferson Park 2018 6 79    173020
Name: 6, dtype: int64
Jefferson Park 2019 6 79    159458
Name: 6, dtype: int64
Jefferson Park 2013 7 78    183517
Name: 7, dtype: int64
Jefferson Park 2014 7 78    187789
Name: 7, dtype: int64
Jefferson Park 2015 7 79    195886
Name: 7, dtype: int64
Jefferson Park 2016 7 79    184893
Name: 7, dtype: int64
Jefferson Park 2017 7 79    172959
Name: 7, dtype: int64
Jefferson Park 2018 7 79    173477
Name: 7, dtype: int64
Jefferson Park 2019 7 79    165973
Name: 7, dtype: int64
Jefferson Park 2013 8 78    188661
Name: 8, dtype: int64
Jefferson Park 2014 8 78    186229
Name: 8, dtype: int64
Jefferson Park 2015 8 79    189570
Name: 8, dtype: int64
Jefferson Park 2016 8 79    190767
Name: 8, dtype: int64
Jefferson Park 2017 8 79    186600
Name: 8, dtype: int64
Jefferson Park 2018 8 79    0
Name: 8, dtype: int64
Jefferson Park 2019 8 79    161350
Name: 8, dtype: int64
Jefferson Park 2013 9 78    183545
Name: 9, dtype: int64
Jefferson Park 2014 9 78    187665
Name: 9, dtype: int64
Jefferson Park 2015 9 79    192448
Name: 9, dtype: int64
Jefferson Park 2016 9 79    192319
Name: 9, dtype: int64
Jefferson Park 2017 9 79    181799
Name: 9, dtype: int64
Jefferson Park 2018 9 79    0
Name: 9, dtype: int64
Jefferson Park 2019 9 79    166902
Name: 9, dtype: int64
Jefferson Park 2013 10 78    196120
Name: 10, dtype: int64
Jefferson Park 2014 10 78    198643
Name: 10, dtype: int64
Jefferson Park 2015 10 79    197344
Name: 10, dtype: int64
Jefferson Park 2016 10 79    192268
Name: 10, dtype: int64
Jefferson Park 2017 10 79    187471
Name: 10, dtype: int64
Jefferson Park 2018 10 79    0
Name: 10, dtype: int64
Jefferson Park 2019 10 79    177549
Name: 10, dtype: int64
Jefferson Park 2013 11 78    172500
Name: 11, dtype: int64
Jefferson Park 2014 11 78    167959
Name: 11, dtype: int64
Jefferson Park 2015 11 79    176413
Name: 11, dtype: int64
Jefferson Park 2016 11 79    183103
Name: 11, dtype: int64
Jefferson Park 2017 11 79    173985
Name: 11, dtype: int64
Jefferson Park 2018 11 79    0
Name: 11, dtype: int64
Jefferson Park 2019 11 79    156009
Name: 11, dtype: int64
Jefferson Park 2013 12 78    163128
Name: 12, dtype: int64
Jefferson Park 2014 12 78    171895
Name: 12, dtype: int64
Jefferson Park 2015 12 79    176010
Name: 12, dtype: int64
Jefferson Park 2016 12 79    163597
Name: 12, dtype: int64
Jefferson Park 2017 12 79    159825
Name: 12, dtype: int64
Jefferson Park 2018 12 79    0
Name: 12, dtype: int64
Jefferson Park 2019 12 79    152250
Name: 12, dtype: int64
Kedzie-Brown 2013 1 79    50689
Name: 1, dtype: int64
Kedzie-Brown 2014 1 79    53100
Name: 1, dtype: int64
Kedzie-Brown 2015 1 80    51045
Name: 1, dtype: int64
Kedzie-Brown 2016 1 80    50345
Name: 1, dtype: int64
Kedzie-Brown 2017 1 80    49420
Name: 1, dtype: int64
Kedzie-Brown 2018 1 80    49120
Name: 1, dtype: int64
Kedzie-Brown 2019 1 80    47313
Name: 1, dtype: int64
Kedzie-Brown 2013 2 79    47778
Name: 2, dtype: int64
Kedzie-Brown 2014 2 79    52695
Name: 2, dtype: int64
Kedzie-Brown 2015 2 80    49339
Name: 2, dtype: int64
Kedzie-Brown 2016 2 80    50958
Name: 2, dtype: int64
Kedzie-Brown 2017 2 80    48188
Name: 2, dtype: int64
Kedzie-Brown 2018 2 80    47255
Name: 2, dtype: int64
Kedzie-Brown 2019 2 80    47194
Name: 2, dtype: int64
Kedzie-Brown 2013 3 79    52243
Name: 3, dtype: int64
Kedzie-Brown 2014 3 79    59586
Name: 3, dtype: int64
Kedzie-Brown 2015 3 80    55843
Name: 3, dtype: int64
Kedzie-Brown 2016 3 80    56272
Name: 3, dtype: int64
Kedzie-Brown 2017 3 80    55063
Name: 3, dtype: int64
Kedzie-Brown 2018 3 80    53702
Name: 3, dtype: int64
Kedzie-Brown 2019 3 80    53522
Name: 3, dtype: int64
Kedzie-Brown 2013 4 79    52937
Name: 4, dtype: int64
Kedzie-Brown 2014 4 79    58601
Name: 4, dtype: int64
Kedzie-Brown 2015 4 80    53679
Name: 4, dtype: int64
Kedzie-Brown 2016 4 80    54010
Name: 4, dtype: int64
Kedzie-Brown 2017 4 80    51995
Name: 4, dtype: int64
Kedzie-Brown 2018 4 80    52513
Name: 4, dtype: int64
Kedzie-Brown 2019 4 80    52735
Name: 4, dtype: int64
Kedzie-Brown 2013 5 79    53810
Name: 5, dtype: int64
Kedzie-Brown 2014 5 79    59348
Name: 5, dtype: int64
Kedzie-Brown 2015 5 80    54466
Name: 5, dtype: int64
Kedzie-Brown 2016 5 80    55882
Name: 5, dtype: int64
Kedzie-Brown 2017 5 80    55554
Name: 5, dtype: int64
Kedzie-Brown 2018 5 80    55778
Name: 5, dtype: int64
Kedzie-Brown 2019 5 80    56077
Name: 5, dtype: int64
Kedzie-Brown 2013 6 79    54342
Name: 6, dtype: int64
Kedzie-Brown 2014 6 79    56567
Name: 6, dtype: int64
Kedzie-Brown 2015 6 80    54947
Name: 6, dtype: int64
Kedzie-Brown 2016 6 80    56082
Name: 6, dtype: int64
Kedzie-Brown 2017 6 80    55620
Name: 6, dtype: int64
Kedzie-Brown 2018 6 80    53975
Name: 6, dtype: int64
Kedzie-Brown 2019 6 80    54315
Name: 6, dtype: int64
Kedzie-Brown 2013 7 79    82430
Name: 7, dtype: int64
Kedzie-Brown 2014 7 79    56459
Name: 7, dtype: int64
Kedzie-Brown 2015 7 80    55306
Name: 7, dtype: int64
Kedzie-Brown 2016 7 80    54861
Name: 7, dtype: int64
Kedzie-Brown 2017 7 80    49508
Name: 7, dtype: int64
Kedzie-Brown 2018 7 80    0
Name: 7, dtype: int64
Kedzie-Brown 2019 7 80    55078
Name: 7, dtype: int64
Kedzie-Brown 2013 8 79    60101
Name: 8, dtype: int64
Kedzie-Brown 2014 8 79    52837
Name: 8, dtype: int64
Kedzie-Brown 2015 8 80    53598
Name: 8, dtype: int64
Kedzie-Brown 2016 8 80    55331
Name: 8, dtype: int64
Kedzie-Brown 2017 8 80    55026
Name: 8, dtype: int64
Kedzie-Brown 2018 8 80    0
Name: 8, dtype: int64
Kedzie-Brown 2019 8 80    55823
Name: 8, dtype: int64
Kedzie-Brown 2013 9 79    60292
Name: 9, dtype: int64
Kedzie-Brown 2014 9 79    57901
Name: 9, dtype: int64
Kedzie-Brown 2015 9 80    56345
Name: 9, dtype: int64
Kedzie-Brown 2016 9 80    57195
Name: 9, dtype: int64
Kedzie-Brown 2017 9 80    55896
Name: 9, dtype: int64
Kedzie-Brown 2018 9 80    0
Name: 9, dtype: int64
Kedzie-Brown 2019 9 80    54666
Name: 9, dtype: int64
Kedzie-Brown 2013 10 79    63628
Name: 10, dtype: int64
Kedzie-Brown 2014 10 79    61058
Name: 10, dtype: int64
Kedzie-Brown 2015 10 80    56545
Name: 10, dtype: int64
Kedzie-Brown 2016 10 80    59128
Name: 10, dtype: int64
Kedzie-Brown 2017 10 80    57440
Name: 10, dtype: int64
Kedzie-Brown 2018 10 80    0
Name: 10, dtype: int64
Kedzie-Brown 2019 10 80    55145
Name: 10, dtype: int64
Kedzie-Brown 2013 11 79    55744
Name: 11, dtype: int64
Kedzie-Brown 2014 11 79    52493
Name: 11, dtype: int64
Kedzie-Brown 2015 11 80    52137
Name: 11, dtype: int64
Kedzie-Brown 2016 11 80    55388
Name: 11, dtype: int64
Kedzie-Brown 2017 11 80    52741
Name: 11, dtype: int64
Kedzie-Brown 2018 11 80    0
Name: 11, dtype: int64
Kedzie-Brown 2019 11 80    38552
Name: 11, dtype: int64
Kedzie-Brown 2013 12 79    53582
Name: 12, dtype: int64
Kedzie-Brown 2014 12 79    52916
Name: 12, dtype: int64
Kedzie-Brown 2015 12 80    52321
Name: 12, dtype: int64
Kedzie-Brown 2016 12 80    49788
Name: 12, dtype: int64
Kedzie-Brown 2017 12 80    48414
Name: 12, dtype: int64
Kedzie-Brown 2018 12 80    0
Name: 12, dtype: int64
Kedzie-Brown 2019 12 80    47547
Name: 12, dtype: int64
Kedzie-Cermak 2013 1 80    26336
Name: 1, dtype: int64
Kedzie-Cermak 2014 1 80    25790
Name: 1, dtype: int64
Kedzie-Cermak 2015 1 81    27597
Name: 1, dtype: int64
Kedzie-Cermak 2016 1 81    27392
Name: 1, dtype: int64
Kedzie-Cermak 2017 1 81    25411
Name: 1, dtype: int64
Kedzie-Cermak 2018 1 81    24628
Name: 1, dtype: int64
Kedzie-Cermak 2019 1 81    22275
Name: 1, dtype: int64
Kedzie-Cermak 2013 2 80    24925
Name: 2, dtype: int64
Kedzie-Cermak 2014 2 80    26568
Name: 2, dtype: int64
Kedzie-Cermak 2015 2 81    26062
Name: 2, dtype: int64
Kedzie-Cermak 2016 2 81    27979
Name: 2, dtype: int64
Kedzie-Cermak 2017 2 81    25354
Name: 2, dtype: int64
Kedzie-Cermak 2018 2 81    23489
Name: 2, dtype: int64
Kedzie-Cermak 2019 2 81    22973
Name: 2, dtype: int64
Kedzie-Cermak 2013 3 80    26988
Name: 3, dtype: int64
Kedzie-Cermak 2014 3 80    30988
Name: 3, dtype: int64
Kedzie-Cermak 2015 3 81    30524
Name: 3, dtype: int64
Kedzie-Cermak 2016 3 81    29675
Name: 3, dtype: int64
Kedzie-Cermak 2017 3 81    27997
Name: 3, dtype: int64
Kedzie-Cermak 2018 3 81    27119
Name: 3, dtype: int64
Kedzie-Cermak 2019 3 81    25157
Name: 3, dtype: int64
Kedzie-Cermak 2013 4 80    28603
Name: 4, dtype: int64
Kedzie-Cermak 2014 4 80    30943
Name: 4, dtype: int64
Kedzie-Cermak 2015 4 81    31360
Name: 4, dtype: int64
Kedzie-Cermak 2016 4 81    27599
Name: 4, dtype: int64
Kedzie-Cermak 2017 4 81    26799
Name: 4, dtype: int64
Kedzie-Cermak 2018 4 81    25840
Name: 4, dtype: int64
Kedzie-Cermak 2019 4 81    25811
Name: 4, dtype: int64
Kedzie-Cermak 2013 5 80    29151
Name: 5, dtype: int64
Kedzie-Cermak 2014 5 80    31804
Name: 5, dtype: int64
Kedzie-Cermak 2015 5 81    32200
Name: 5, dtype: int64
Kedzie-Cermak 2016 5 81    29377
Name: 5, dtype: int64
Kedzie-Cermak 2017 5 81    28670
Name: 5, dtype: int64
Kedzie-Cermak 2018 5 81    28485
Name: 5, dtype: int64
Kedzie-Cermak 2019 5 81    28085
Name: 5, dtype: int64
Kedzie-Cermak 2013 6 80    28610
Name: 6, dtype: int64
Kedzie-Cermak 2014 6 80    29741
Name: 6, dtype: int64
Kedzie-Cermak 2015 6 81    32574
Name: 6, dtype: int64
Kedzie-Cermak 2016 6 81    29801
Name: 6, dtype: int64
Kedzie-Cermak 2017 6 81    28713
Name: 6, dtype: int64
Kedzie-Cermak 2018 6 81    27633
Name: 6, dtype: int64
Kedzie-Cermak 2019 6 81    27235
Name: 6, dtype: int64
Kedzie-Cermak 2013 7 80    30522
Name: 7, dtype: int64
Kedzie-Cermak 2014 7 80    30408
Name: 7, dtype: int64
Kedzie-Cermak 2015 7 81    33570
Name: 7, dtype: int64
Kedzie-Cermak 2016 7 81    29458
Name: 7, dtype: int64
Kedzie-Cermak 2017 7 81    28543
Name: 7, dtype: int64
Kedzie-Cermak 2018 7 81    27596
Name: 7, dtype: int64
Kedzie-Cermak 2019 7 81    28571
Name: 7, dtype: int64
Kedzie-Cermak 2013 8 80    30942
Name: 8, dtype: int64
Kedzie-Cermak 2014 8 80    29874
Name: 8, dtype: int64
Kedzie-Cermak 2015 8 81    32532
Name: 8, dtype: int64
Kedzie-Cermak 2016 8 81    30101
Name: 8, dtype: int64
Kedzie-Cermak 2017 8 81    30015
Name: 8, dtype: int64
Kedzie-Cermak 2018 8 81    0
Name: 8, dtype: int64
Kedzie-Cermak 2019 8 81    28245
Name: 8, dtype: int64
Kedzie-Cermak 2013 9 80    31098
Name: 9, dtype: int64
Kedzie-Cermak 2014 9 80    31653
Name: 9, dtype: int64
Kedzie-Cermak 2015 9 81    37652
Name: 9, dtype: int64
Kedzie-Cermak 2016 9 81    38139
Name: 9, dtype: int64
Kedzie-Cermak 2017 9 81    40216
Name: 9, dtype: int64
Kedzie-Cermak 2018 9 81    0
Name: 9, dtype: int64
Kedzie-Cermak 2019 9 81    39332
Name: 9, dtype: int64
Kedzie-Cermak 2013 10 80    32518
Name: 10, dtype: int64
Kedzie-Cermak 2014 10 80    34353
Name: 10, dtype: int64
Kedzie-Cermak 2015 10 81    35071
Name: 10, dtype: int64
Kedzie-Cermak 2016 10 81    30622
Name: 10, dtype: int64
Kedzie-Cermak 2017 10 81    30396
Name: 10, dtype: int64
Kedzie-Cermak 2018 10 81    0
Name: 10, dtype: int64
Kedzie-Cermak 2019 10 81    28725
Name: 10, dtype: int64
Kedzie-Cermak 2013 11 80    28015
Name: 11, dtype: int64
Kedzie-Cermak 2014 11 80    29227
Name: 11, dtype: int64
Kedzie-Cermak 2015 11 81    30209
Name: 11, dtype: int64
Kedzie-Cermak 2016 11 81    28864
Name: 11, dtype: int64
Kedzie-Cermak 2017 11 81    27460
Name: 11, dtype: int64
Kedzie-Cermak 2018 11 81    0
Name: 11, dtype: int64
Kedzie-Cermak 2019 11 81    25003
Name: 11, dtype: int64
Kedzie-Cermak 2013 12 80    26380
Name: 12, dtype: int64
Kedzie-Cermak 2014 12 80    29843
Name: 12, dtype: int64
Kedzie-Cermak 2015 12 81    29777
Name: 12, dtype: int64
Kedzie-Cermak 2016 12 81    25387
Name: 12, dtype: int64
Kedzie-Cermak 2017 12 81    25420
Name: 12, dtype: int64
Kedzie-Cermak 2018 12 81    0
Name: 12, dtype: int64
Kedzie-Cermak 2019 12 81    23677
Name: 12, dtype: int64
Kedzie-Homan-Forest Park 2013 1 81    56409
Name: 1, dtype: int64
Kedzie-Homan-Forest Park 2014 1 81    52507
Name: 1, dtype: int64

Kedzie-Homan-Forest Park 2015 1 82    60185
Name: 1, dtype: int64
Kedzie-Homan-Forest Park 2016 1 82    58096
Name: 1, dtype: int64
Kedzie-Homan-Forest Park 2017 1 82    49868
Name: 1, dtype: int64
Kedzie-Homan-Forest Park 2018 1 82    50411
Name: 1, dtype: int64
Kedzie-Homan-Forest Park 2019 1 82    42640
Name: 1, dtype: int64
Kedzie-Homan-Forest Park 2013 2 81    54224
Name: 2, dtype: int64
Kedzie-Homan-Forest Park 2014 2 81    54163
Name: 2, dtype: int64
Kedzie-Homan-Forest Park 2015 2 82    55811
Name: 2, dtype: int64
Kedzie-Homan-Forest Park 2016 2 82    55432
Name: 2, dtype: int64
Kedzie-Homan-Forest Park 2017 2 82    49686
Name: 2, dtype: int64
Kedzie-Homan-Forest Park 2018 2 82    47338
Name: 2, dtype: int64
Kedzie-Homan-Forest Park 2019 2 82    41818
Name: 2, dtype: int64
Kedzie-Homan-Forest Park 2013 3 81    59309
Name: 3, dtype: int64
Kedzie-Homan-Forest Park 2014 3 81    61541
Name: 3, dtype: int64
Kedzie-Homan-Forest Park 2015 3 82    67183
Name: 3, dtype: int64
Kedzie-Homan-Forest Park 2016 3 82    59511
Name: 3, dtype: int64
Kedzie-Homan-Forest Park 2017 3 82    52820
Name: 3, dtype: int64
Kedzie-Homan-Forest Park 2018 3 82    53108
Name: 3, dtype: int64
Kedzie-Homan-Forest Park 2019 3 82    45744
Name: 3, dtype: int64
Kedzie-Homan-Forest Park 2013 4 81    60483
Name: 4, dtype: int64
Kedzie-Homan-Forest Park 2014 4 81    60272
Name: 4, dtype: int64
Kedzie-Homan-Forest Park 2015 4 82    66358
Name: 4, dtype: int64
Kedzie-Homan-Forest Park 2016 4 82    58231
Name: 4, dtype: int64
Kedzie-Homan-Forest Park 2017 4 82    48709
Name: 4, dtype: int64
Kedzie-Homan-Forest Park 2018 4 82    51595
Name: 4, dtype: int64
Kedzie-Homan-Forest Park 2019 4 82    45011
Name: 4, dtype: int64
Kedzie-Homan-Forest Park 2013 5 81    61813
Name: 5, dtype: int64
Kedzie-Homan-Forest Park 2014 5 81    64294
Name: 5, dtype: int64
Kedzie-Homan-Forest Park 2015 5 82    69502
Name: 5, dtype: int64
Kedzie-Homan-Forest Park 2016 5 82    63823
Name: 5, dtype: int64
Kedzie-Homan-Forest Park 2017 5 82    53692
Name: 5, dtype: int64
Kedzie-Homan-Forest Park 2018 5 82    58066
Name: 5, dtype: int64
Kedzie-Homan-Forest Park 2019 5 82    48868
Name: 5, dtype: int64
Kedzie-Homan-Forest Park 2013 6 81    58452
Name: 6, dtype: int64
Kedzie-Homan-Forest Park 2014 6 81    61324
Name: 6, dtype: int64
Kedzie-Homan-Forest Park 2015 6 82    69891
Name: 6, dtype: int64
Kedzie-Homan-Forest Park 2016 6 82    64209
Name: 6, dtype: int64
Kedzie-Homan-Forest Park 2017 6 82    52293
Name: 6, dtype: int64
Kedzie-Homan-Forest Park 2018 6 82    53647
Name: 6, dtype: int64
Kedzie-Homan-Forest Park 2019 6 82    48492
Name: 6, dtype: int64
Kedzie-Homan-Forest Park 2013 7 81    60666
Name: 7, dtype: int64
Kedzie-Homan-Forest Park 2014 7 81    64910
Name: 7, dtype: int64
Kedzie-Homan-Forest Park 2015 7 82    71067
Name: 7, dtype: int64
Kedzie-Homan-Forest Park 2016 7 82    60660
Name: 7, dtype: int64
Kedzie-Homan-Forest Park 2017 7 82    50786
Name: 7, dtype: int64
Kedzie-Homan-Forest Park 2018 7 82    52903
Name: 7, dtype: int64
Kedzie-Homan-Forest Park 2019 7 82    52688
Name: 7, dtype: int64
Kedzie-Homan-Forest Park 2013 8 81    62263
Name: 8, dtype: int64
Kedzie-Homan-Forest Park 2014 8 81    63776
Name: 8, dtype: int64
Kedzie-Homan-Forest Park 2015 8 82    67451
Name: 8, dtype: int64
Kedzie-Homan-Forest Park 2016 8 82    61932
Name: 8, dtype: int64
Kedzie-Homan-Forest Park 2017 8 82    52404
Name: 8, dtype: int64
Kedzie-Homan-Forest Park 2018 8 82    0
Name: 8, dtype: int64
Kedzie-Homan-Forest Park 2019 8 82    55424
Name: 8, dtype: int64
Kedzie-Homan-Forest Park 2013 9 81    63707
Name: 9, dtype: int64
Kedzie-Homan-Forest Park 2014 9 81    70086
Name: 9, dtype: int64
Kedzie-Homan-Forest Park 2015 9 82    70113
Name: 9, dtype: int64
Kedzie-Homan-Forest Park 2016 9 82    66506
Name: 9, dtype: int64
Kedzie-Homan-Forest Park 2017 9 82    54808
Name: 9, dtype: int64
Kedzie-Homan-Forest Park 2018 9 82    0
Name: 9, dtype: int64
Kedzie-Homan-Forest Park 2019 9 82    52840
Name: 9, dtype: int64
Kedzie-Homan-Forest Park 2013 10 81    67495
Name: 10, dtype: int64
Kedzie-Homan-Forest Park 2014 10 81    73879
Name: 10, dtype: int64
Kedzie-Homan-Forest Park 2015 10 82    69066
Name: 10, dtype: int64
Kedzie-Homan-Forest Park 2016 10 82    64056
Name: 10, dtype: int64
Kedzie-Homan-Forest Park 2017 10 82    56154
Name: 10, dtype: int64
Kedzie-Homan-Forest Park 2018 10 82    0
Name: 10, dtype: int64
Kedzie-Homan-Forest Park 2019 10 82    53428
Name: 10, dtype: int64
Kedzie-Homan-Forest Park 2013 11 81    59406
Name: 11, dtype: int64
Kedzie-Homan-Forest Park 2014 11 81    61245
Name: 11, dtype: int64
Kedzie-Homan-Forest Park 2015 11 82    58953
Name: 11, dtype: int64
Kedzie-Homan-Forest Park 2016 11 82    57651
Name: 11, dtype: int64
Kedzie-Homan-Forest Park 2017 11 82    55037
Name: 11, dtype: int64
Kedzie-Homan-Forest Park 2018 11 82    0
Name: 11, dtype: int64
Kedzie-Homan-Forest Park 2019 11 82    47460
Name: 11, dtype: int64
Kedzie-Homan-Forest Park 2013 12 81    55297
Name: 12, dtype: int64
Kedzie-Homan-Forest Park 2014 12 81    64309
Name: 12, dtype: int64
Kedzie-Homan-Forest Park 2015 12 82    61668
Name: 12, dtype: int64
Kedzie-Homan-Forest Park 2016 12 82    51055
Name: 12, dtype: int64
Kedzie-Homan-Forest Park 2017 12 82    53395
Name: 12, dtype: int64
Kedzie-Homan-Forest Park 2018 12 82    0
Name: 12, dtype: int64
Kedzie-Homan-Forest Park 2019 12 82    47413
Name: 12, dtype: int64
Kedzie-Lake 2013 1 82    36112
Name: 1, dtype: int64
Kedzie-Lake 2014 1 82    37192
Name: 1, dtype: int64
Kedzie-Lake 2015 1 83    39202
Name: 1, dtype: int64
Kedzie-Lake 2016 1 83    41416
Name: 1, dtype: int64
Kedzie-Lake 2017 1 83    32158
Name: 1, dtype: int64
Kedzie-Lake 2018 1 83    38490
Name: 1, dtype: int64
Kedzie-Lake 2019 1 83    31537
Name: 1, dtype: int64
Kedzie-Lake 2013 2 82    34215
Name: 2, dtype: int64
Kedzie-Lake 2014 2 82    40472
Name: 2, dtype: int64
Kedzie-Lake 2015 2 83    36597
Name: 2, dtype: int64
Kedzie-Lake 2016 2 83    39641
Name: 2, dtype: int64
Kedzie-Lake 2017 2 83    33746
Name: 2, dtype: int64
Kedzie-Lake 2018 2 83    35513
Name: 2, dtype: int64
Kedzie-Lake 2019 2 83    32275
Name: 2, dtype: int64
Kedzie-Lake 2013 3 82    34917
Name: 3, dtype: int64
Kedzie-Lake 2014 3 82    44565
Name: 3, dtype: int64
Kedzie-Lake 2015 3 83    43884
Name: 3, dtype: int64
Kedzie-Lake 2016 3 83    45621
Name: 3, dtype: int64
Kedzie-Lake 2017 3 83    36579
Name: 3, dtype: int64
Kedzie-Lake 2018 3 83    39243
Name: 3, dtype: int64
Kedzie-Lake 2019 3 83    35379
Name: 3, dtype: int64
Kedzie-Lake 2013 4 82    37013
Name: 4, dtype: int64
Kedzie-Lake 2014 4 82    43105
Name: 4, dtype: int64
Kedzie-Lake 2015 4 83    42520
Name: 4, dtype: int64
Kedzie-Lake 2016 4 83    42531
Name: 4, dtype: int64
Kedzie-Lake 2017 4 83    31705
Name: 4, dtype: int64
Kedzie-Lake 2018 4 83    39023
Name: 4, dtype: int64
Kedzie-Lake 2019 4 83    34052
Name: 4, dtype: int64
Kedzie-Lake 2013 5 82    39976
Name: 5, dtype: int64
Kedzie-Lake 2014 5 82    45595
Name: 5, dtype: int64
Kedzie-Lake 2015 5 83    45132
Name: 5, dtype: int64
Kedzie-Lake 2016 5 83    48299
Name: 5, dtype: int64
Kedzie-Lake 2017 5 83    39909
Name: 5, dtype: int64
Kedzie-Lake 2018 5 83    44603
Name: 5, dtype: int64
Kedzie-Lake 2019 5 83    38399
Name: 5, dtype: int64
Kedzie-Lake 2013 6 82    42843
Name: 6, dtype: int64
Kedzie-Lake 2014 6 82    40865
Name: 6, dtype: int64
Kedzie-Lake 2015 6 83    43438
Name: 6, dtype: int64
Kedzie-Lake 2016 6 83    45779
Name: 6, dtype: int64
Kedzie-Lake 2017 6 83    37518
Name: 6, dtype: int64
Kedzie-Lake 2018 6 83    40456
Name: 6, dtype: int64
Kedzie-Lake 2019 6 83    34687
Name: 6, dtype: int64
Kedzie-Lake 2013 7 82    46198
Name: 7, dtype: int64
Kedzie-Lake 2014 7 82    40498
Name: 7, dtype: int64
Kedzie-Lake 2015 7 83    40320
Name: 7, dtype: int64
Kedzie-Lake 2016 7 83    38873
Name: 7, dtype: int64
Kedzie-Lake 2017 7 83    34815
Name: 7, dtype: int64
Kedzie-Lake 2018 7 83    38041
Name: 7, dtype: int64
Kedzie-Lake 2019 7 83    33791
Name: 7, dtype: int64
Kedzie-Lake 2013 8 82    46546
Name: 8, dtype: int64
Kedzie-Lake 2014 8 82    40329
Name: 8, dtype: int64
Kedzie-Lake 2015 8 83    40154
Name: 8, dtype: int64
Kedzie-Lake 2016 8 83    39323
Name: 8, dtype: int64
Kedzie-Lake 2017 8 83    37357
Name: 8, dtype: int64
Kedzie-Lake 2018 8 83    0
Name: 8, dtype: int64
Kedzie-Lake 2019 8 83    34861
Name: 8, dtype: int64
Kedzie-Lake 2013 9 82    53313
Name: 9, dtype: int64
Kedzie-Lake 2014 9 82    49278
Name: 9, dtype: int64
Kedzie-Lake 2015 9 83    47144
Name: 9, dtype: int64
Kedzie-Lake 2016 9 83    43211
Name: 9, dtype: int64
Kedzie-Lake 2017 9 83    41308
Name: 9, dtype: int64
Kedzie-Lake 2018 9 83    0
Name: 9, dtype: int64
Kedzie-Lake 2019 9 83    37981
Name: 9, dtype: int64
Kedzie-Lake 2013 10 82    54461
Name: 10, dtype: int64
Kedzie-Lake 2014 10 82    51032
Name: 10, dtype: int64
Kedzie-Lake 2015 10 83    52736
Name: 10, dtype: int64
Kedzie-Lake 2016 10 83    42168
Name: 10, dtype: int64
Kedzie-Lake 2017 10 83    42420
Name: 10, dtype: int64
Kedzie-Lake 2018 10 83    0
Name: 10, dtype: int64
Kedzie-Lake 2019 10 83    37573
Name: 10, dtype: int64
Kedzie-Lake 2013 11 82    44392
Name: 11, dtype: int64

Kedzie-Lake 2014 11 82    40530
Name: 11, dtype: int64
Kedzie-Lake 2015 11 83    45229
Name: 11, dtype: int64
Kedzie-Lake 2016 11 83    39371
Name: 11, dtype: int64
Kedzie-Lake 2017 11 83    40260
Name: 11, dtype: int64
Kedzie-Lake 2018 11 83    0
Name: 11, dtype: int64
Kedzie-Lake 2019 11 83    33867
Name: 11, dtype: int64
Kedzie-Lake 2013 12 82    39605
Name: 12, dtype: int64
Kedzie-Lake 2014 12 82    41660
Name: 12, dtype: int64
Kedzie-Lake 2015 12 83    44096
Name: 12, dtype: int64
Kedzie-Lake 2016 12 83    31200
Name: 12, dtype: int64
Kedzie-Lake 2017 12 83    39890
Name: 12, dtype: int64
Kedzie-Lake 2018 12 83    0
Name: 12, dtype: int64
Kedzie-Lake 2019 12 83    32034
Name: 12, dtype: int64
Kedzie-Midway 2013 1 83    79428
Name: 1, dtype: int64
Kedzie-Midway 2014 1 83    74160
Name: 1, dtype: int64
Kedzie-Midway 2015 1 84    77595
Name: 1, dtype: int64
Kedzie-Midway 2016 1 84    77610
Name: 1, dtype: int64
Kedzie-Midway 2017 1 84    79128
Name: 1, dtype: int64
Kedzie-Midway 2018 1 84    79167
Name: 1, dtype: int64
Kedzie-Midway 2019 1 84    73259
Name: 1, dtype: int64
Kedzie-Midway 2013 2 83    75315
Name: 2, dtype: int64
Kedzie-Midway 2014 2 83    79667
Name: 2, dtype: int64
Kedzie-Midway 2015 2 84    74318
Name: 2, dtype: int64
Kedzie-Midway 2016 2 84    82972
Name: 2, dtype: int64
Kedzie-Midway 2017 2 84    79892
Name: 2, dtype: int64
Kedzie-Midway 2018 2 84    75997
Name: 2, dtype: int64
Kedzie-Midway 2019 2 84    75233
Name: 2, dtype: int64
Kedzie-Midway 2013 3 83    81764
Name: 3, dtype: int64
Kedzie-Midway 2014 3 83    90546
Name: 3, dtype: int64
Kedzie-Midway 2015 3 84    88728
Name: 3, dtype: int64
Kedzie-Midway 2016 3 84    89789
Name: 3, dtype: int64
Kedzie-Midway 2017 3 84    91705
Name: 3, dtype: int64
Kedzie-Midway 2018 3 84    86435
Name: 3, dtype: int64
Kedzie-Midway 2019 3 84    84660
Name: 3, dtype: int64
Kedzie-Midway 2013 4 83    86460
Name: 4, dtype: int64
Kedzie-Midway 2014 4 83    90256
Name: 4, dtype: int64
Kedzie-Midway 2015 4 84    88681
Name: 4, dtype: int64
Kedzie-Midway 2016 4 84    87368
Name: 4, dtype: int64
Kedzie-Midway 2017 4 84    83650
Name: 4, dtype: int64
Kedzie-Midway 2018 4 84    83960
Name: 4, dtype: int64
Kedzie-Midway 2019 4 84    84631
Name: 4, dtype: int64
Kedzie-Midway 2013 5 83    89932
Name: 5, dtype: int64
Kedzie-Midway 2014 5 83    89196
Name: 5, dtype: int64
Kedzie-Midway 2015 5 84    81522
Name: 5, dtype: int64
Kedzie-Midway 2016 5 84    89259
Name: 5, dtype: int64
Kedzie-Midway 2017 5 84    91498
Name: 5, dtype: int64
Kedzie-Midway 2018 5 84    89884
Name: 5, dtype: int64
Kedzie-Midway 2019 5 84    88844
Name: 5, dtype: int64
Kedzie-Midway 2013 6 83    88391
Name: 6, dtype: int64
Kedzie-Midway 2014 6 83    86964
Name: 6, dtype: int64
Kedzie-Midway 2015 6 84    73910
Name: 6, dtype: int64
Kedzie-Midway 2016 6 84    92373
Name: 6, dtype: int64
Kedzie-Midway 2017 6 84    91734
Name: 6, dtype: int64
Kedzie-Midway 2018 6 84    86544
Name: 6, dtype: int64
Kedzie-Midway 2019 6 84    83125
Name: 6, dtype: int64
Kedzie-Midway 2013 7 83    91159
Name: 7, dtype: int64
Kedzie-Midway 2014 7 83    70830
Name: 7, dtype: int64
Kedzie-Midway 2015 7 84    74896
Name: 7, dtype: int64
Kedzie-Midway 2016 7 84    88960
Name: 7, dtype: int64
Kedzie-Midway 2017 7 84    86686
Name: 7, dtype: int64
Kedzie-Midway 2018 7 84    0
Name: 7, dtype: int64
Kedzie-Midway 2019 7 84    85307
Name: 7, dtype: int64
Kedzie-Midway 2013 8 83    92704
Name: 8, dtype: int64
Kedzie-Midway 2014 8 83    66740
Name: 8, dtype: int64
Kedzie-Midway 2015 8 84    72213
Name: 8, dtype: int64
Kedzie-Midway 2016 8 84    92336
Name: 8, dtype: int64
Kedzie-Midway 2017 8 84    93670
Name: 8, dtype: int64
Kedzie-Midway 2018 8 84    0
Name: 8, dtype: int64
Kedzie-Midway 2019 8 84    86474
Name: 8, dtype: int64
Kedzie-Midway 2013 9 83    93326
Name: 9, dtype: int64
Kedzie-Midway 2014 9 83    75258
Name: 9, dtype: int64
Kedzie-Midway 2015 9 84    77101
Name: 9, dtype: int64
Kedzie-Midway 2016 9 84    97193
Name: 9, dtype: int64
Kedzie-Midway 2017 9 84    95448
Name: 9, dtype: int64
Kedzie-Midway 2018 9 84    0
Name: 9, dtype: int64
Kedzie-Midway 2019 9 84    91679
Name: 9, dtype: int64
Kedzie-Midway 2013 10 83    101379
Name: 10, dtype: int64
Kedzie-Midway 2014 10 83    78980
Name: 10, dtype: int64
Kedzie-Midway 2015 10 84    80413
Name: 10, dtype: int64
Kedzie-Midway 2016 10 84    98870
Name: 10, dtype: int64
Kedzie-Midway 2017 10 84    99047
Name: 10, dtype: int64
Kedzie-Midway 2018 10 84    0
Name: 10, dtype: int64
Kedzie-Midway 2019 10 84    96865
Name: 10, dtype: int64
Kedzie-Midway 2013 11 83    86365
Name: 11, dtype: int64
Kedzie-Midway 2014 11 83    65600
Name: 11, dtype: int64
Kedzie-Midway 2015 11 84    71307
Name: 11, dtype: int64
Kedzie-Midway 2016 11 84    92789
Name: 11, dtype: int64
Kedzie-Midway 2017 11 84    90343
Name: 11, dtype: int64
Kedzie-Midway 2018 11 84    0
Name: 11, dtype: int64
Kedzie-Midway 2019 11 84    82951
Name: 11, dtype: int64
Kedzie-Midway 2013 12 83    78204
Name: 12, dtype: int64
Kedzie-Midway 2014 12 83    67309
Name: 12, dtype: int64
Kedzie-Midway 2015 12 84    73064
Name: 12, dtype: int64
Kedzie-Midway 2016 12 84    81008
Name: 12, dtype: int64
Kedzie-Midway 2017 12 84    80230
Name: 12, dtype: int64
Kedzie-Midway 2018 12 84    0
Name: 12, dtype: int64
Kedzie-Midway 2019 12 84    76561
Name: 12, dtype: int64
Kimball 2013 1 84    107839
Name: 1, dtype: int64
Kimball 2014 1 84    103348
Name: 1, dtype: int64
Kimball 2015 1 85    103528
Name: 1, dtype: int64
Kimball 2016 1 85    101563
Name: 1, dtype: int64
Kimball 2017 1 85    101871
Name: 1, dtype: int64
Kimball 2018 1 85    96656
Name: 1, dtype: int64
Kimball 2019 1 85    93870
Name: 1, dtype: int64
Kimball 2013 2 84    101446
Name: 2, dtype: int64
Kimball 2014 2 84    104699
Name: 2, dtype: int64
Kimball 2015 2 85    99930
Name: 2, dtype: int64
Kimball 2016 2 85    103294
Name: 2, dtype: int64
Kimball 2017 2 85    98704
Name: 2, dtype: int64
Kimball 2018 2 85    92203
Name: 2, dtype: int64
Kimball 2019 2 85    94695
Name: 2, dtype: int64
Kimball 2013 3 84    104215
Name: 3, dtype: int64
Kimball 2014 3 84    116411
Name: 3, dtype: int64
Kimball 2015 3 85    112615
Name: 3, dtype: int64
Kimball 2016 3 85    112532
Name: 3, dtype: int64
Kimball 2017 3 85    111329
Name: 3, dtype: int64
Kimball 2018 3 85    103731
Name: 3, dtype: int64
Kimball 2019 3 85    104408
Name: 3, dtype: int64
Kimball 2013 4 84    110426
Name: 4, dtype: int64
Kimball 2014 4 84    116670
Name: 4, dtype: int64
Kimball 2015 4 85    109864
Name: 4, dtype: int64
Kimball 2016 4 85    108442
Name: 4, dtype: int64
Kimball 2017 4 85    102636
Name: 4, dtype: int64
Kimball 2018 4 85    101396
Name: 4, dtype: int64
Kimball 2019 4 85    102762
Name: 4, dtype: int64
Kimball 2013 5 84    108700
Name: 5, dtype: int64
Kimball 2014 5 84    114678
Name: 5, dtype: int64
Kimball 2015 5 85    107763
Name: 5, dtype: int64
Kimball 2016 5 85    108781
Name: 5, dtype: int64
Kimball 2017 5 85    109519
Name: 5, dtype: int64
Kimball 2018 5 85    105268
Name: 5, dtype: int64
Kimball 2019 5 85    107317
Name: 5, dtype: int64
Kimball 2013 6 84    108307
Name: 6, dtype: int64
Kimball 2014 6 84    109566
Name: 6, dtype: int64
Kimball 2015 6 85    109344
Name: 6, dtype: int64
Kimball 2016 6 85    111375
Name: 6, dtype: int64
Kimball 2017 6 85    107674
Name: 6, dtype: int64
Kimball 2018 6 85    101954
Name: 6, dtype: int64
Kimball 2019 6 85    102861
Name: 6, dtype: int64
Kimball 2013 7 84    76834
Name: 7, dtype: int64
Kimball 2014 7 84    109867
Name: 7, dtype: int64
Kimball 2015 7 85    109446
Name: 7, dtype: int64
Kimball 2016 7 85    106877
Name: 7, dtype: int64
Kimball 2017 7 85    97440
Name: 7, dtype: int64
Kimball 2018 7 85    0
Name: 7, dtype: int64
Kimball 2019 7 85    104802
Name: 7, dtype: int64
Kimball 2013 8 84    110691
Name: 8, dtype: int64
Kimball 2014 8 84    103318
Name: 8, dtype: int64
Kimball 2015 8 85    107590
Name: 8, dtype: int64
Kimball 2016 8 85    110196
Name: 8, dtype: int64
Kimball 2017 8 85    106170
Name: 8, dtype: int64
Kimball 2018 8 85    0
Name: 8, dtype: int64
Kimball 2019 8 85    105751
Name: 8, dtype: int64
Kimball 2013 9 84    115190
Name: 9, dtype: int64
Kimball 2014 9 84    119657
Name: 9, dtype: int64
Kimball 2015 9 85    115902
Name: 9, dtype: int64
Kimball 2016 9 85    116084
Name: 9, dtype: int64
Kimball 2017 9 85    109826
Name: 9, dtype: int64
Kimball 2018 9 85    0
Name: 9, dtype: int64
Kimball 2019 9 85    108052
Name: 9, dtype: int64
Kimball 2013 10 84    123280
Name: 10, dtype: int64
Kimball 2014 10 84    124528
Name: 10, dtype: int64
Kimball 2015 10 85    118356
Name: 10, dtype: int64
Kimball 2016 10 85    119632
Name: 10, dtype: int64
Kimball 2017 10 85    112954
Name: 10, dtype: int64
Kimball 2018 10 85    0
Name: 10, dtype: int64
Kimball 2019 10 85    108203
Name: 10, dtype: int64
Kimball 2013 11 84    108606
Name: 11, dtype: int64
Kimball 2014 11 84    103724
Name: 11, dtype: int64
Kimball 2015 11 85    105630
Name: 11, dtype: int64
Kimball 2016 11 85    112257
Name: 11, dtype: int64
Kimball 2017 11 85    103522
Name: 11, dtype: int64
Kimball 2018 11 85    0
Name: 11, dtype: int64
Kimball 2019 11 85    78728
Name: 11, dtype: int64
Kimball 2013 12 84    102432
Name: 12, dtype: int64
Kimball 2014 12 84    105228
Name: 12, dtype: int64
Kimball 2015 12 85    104837
Name: 12, dtype: int64
Kimball 2016 12 85    101819
Name: 12, dtype: int64
Kimball 2017 12 85    94766
Name: 12, dtype: int64
Kimball 2018 12 85    0
Name: 12, dtype: int64
Kimball 2019 12 85    93645
Name: 12, dtype: int64
King Drive 2013 1 85    16342
Name: 1, dtype: int64
King Drive 2014 1 85    15795
Name: 1, dtype: int64
King Drive 2015 1 86    14693
Name: 1, dtype: int64
King Drive 2016 1 86    14835
Name: 1, dtype: int64
King Drive 2017 1 86    14100
Name: 1, dtype: int64
King Drive 2018 1 86    12815
Name: 1, dtype: int64
King Drive 2019 1 86    11114
Name: 1, dtype: int64
King Drive 2013 2 85    15579
Name: 2, dtype: int64
King Drive 2014 2 85    15855
Name: 2, dtype: int64
King Drive 2015 2 86    14001
Name: 2, dtype: int64
King Drive 2016 2 86    15288
Name: 2, dtype: int64
King Drive 2017 2 86    13770
Name: 2, dtype: int64
King Drive 2018 2 86    12300
Name: 2, dtype: int64
King Drive 2019 2 86    10628
Name: 2, dtype: int64
King Drive 2013 3 85    17001
Name: 3, dtype: int64
King Drive 2014 3 85    18288
Name: 3, dtype: int64
King Drive 2015 3 86    16555
Name: 3, dtype: int64
King Drive 2016 3 86    16914
Name: 3, dtype: int64
King Drive 2017 3 86    14772
Name: 3, dtype: int64
King Drive 2018 3 86    13093
Name: 3, dtype: int64
King Drive 2019 3 86    11493
Name: 3, dtype: int64
King Drive 2013 4 85    18932
Name: 4, dtype: int64
King Drive 2014 4 85    17479
Name: 4, dtype: int64
King Drive 2015 4 86    16600
Name: 4, dtype: int64
King Drive 2016 4 86    15636
Name: 4, dtype: int64
King Drive 2017 4 86    13722
Name: 4, dtype: int64
King Drive 2018 4 86    13001
Name: 4, dtype: int64
King Drive 2019 4 86    10943
Name: 4, dtype: int64
King Drive 2013 5 85    25107
Name: 5, dtype: int64
King Drive 2014 5 85    18633
Name: 5, dtype: int64
King Drive 2015 5 86    17747
Name: 5, dtype: int64
King Drive 2016 5 86    16769
Name: 5, dtype: int64
King Drive 2017 5 86    14842
Name: 5, dtype: int64
King Drive 2018 5 86    15487
Name: 5, dtype: int64
King Drive 2019 5 86    12570
Name: 5, dtype: int64
King Drive 2013 6 85    30126
Name: 6, dtype: int64
King Drive 2014 6 85    18114
Name: 6, dtype: int64
King Drive 2015 6 86    18646
Name: 6, dtype: int64
King Drive 2016 6 86    17311
Name: 6, dtype: int64
King Drive 2017 6 86    15573
Name: 6, dtype: int64
King Drive 2018 6 86    15081
Name: 6, dtype: int64
King Drive 2019 6 86    11968
Name: 6, dtype: int64
King Drive 2013 7 85    30414
Name: 7, dtype: int64
King Drive 2014 7 85    19107
Name: 7, dtype: int64
King Drive 2015 7 86    20024
Name: 7, dtype: int64
King Drive 2016 7 86    16941
Name: 7, dtype: int64
King Drive 2017 7 86    14986
Name: 7, dtype: int64
King Drive 2018 7 86    14303
Name: 7, dtype: int64
King Drive 2019 7 86    12997
Name: 7, dtype: int64
King Drive 2013 8 85    31541
Name: 8, dtype: int64
King Drive 2014 8 85    19152
Name: 8, dtype: int64
King Drive 2015 8 86    19232
Name: 8, dtype: int64
King Drive 2016 8 86    16510
Name: 8, dtype: int64
King Drive 2017 8 86    15490
Name: 8, dtype: int64
King Drive 2018 8 86    0
Name: 8, dtype: int64
King Drive 2019 8 86    13176
Name: 8, dtype: int64
King Drive 2013 9 85    30281
Name: 9, dtype: int64
King Drive 2014 9 85    18954
Name: 9, dtype: int64
King Drive 2015 9 86    19459
Name: 9, dtype: int64
King Drive 2016 9 86    16630
Name: 9, dtype: int64
King Drive 2017 9 86    15649
Name: 9, dtype: int64
King Drive 2018 9 86    0
Name: 9, dtype: int64
King Drive 2019 9 86    12459
Name: 9, dtype: int64
King Drive 2013 10 85    28975
Name: 10, dtype: int64
King Drive 2014 10 85    19499
Name: 10, dtype: int64
King Drive 2015 10 86    19468
Name: 10, dtype: int64
King Drive 2016 10 86    16382
Name: 10, dtype: int64
King Drive 2017 10 86    15876
Name: 10, dtype: int64
King Drive 2018 10 86    0
Name: 10, dtype: int64
King Drive 2019 10 86    11834
Name: 10, dtype: int64
King Drive 2013 11 85    19717
Name: 11, dtype: int64
King Drive 2014 11 85    16333
Name: 11, dtype: int64
King Drive 2015 11 86    17592
Name: 11, dtype: int64
King Drive 2016 11 86    16375
Name: 11, dtype: int64
King Drive 2017 11 86    14355
Name: 11, dtype: int64
King Drive 2018 11 86    0
Name: 11, dtype: int64
King Drive 2019 11 86    10083
Name: 11, dtype: int64
King Drive 2013 12 85    18115
Name: 12, dtype: int64
King Drive 2014 12 85    16533
Name: 12, dtype: int64
King Drive 2015 12 86    17167
Name: 12, dtype: int64
King Drive 2016 12 86    15167
Name: 12, dtype: int64
King Drive 2017 12 86    13384
Name: 12, dtype: int64
King Drive 2018 12 86    0
Name: 12, dtype: int64
King Drive 2019 12 86    9866
Name: 12, dtype: int64
Kostner 2013 1 86    11211
Name: 1, dtype: int64
Kostner 2014 1 86    12282
Name: 1, dtype: int64
Kostner 2015 1 87    12848
Name: 1, dtype: int64

Kostner 2016 1 87    12547
Name: 1, dtype: int64
Kostner 2017 1 87    12149
Name: 1, dtype: int64
Kostner 2018 1 87    11620
Name: 1, dtype: int64
Kostner 2019 1 87    11200
Name: 1, dtype: int64
Kostner 2013 2 86    10395
Name: 2, dtype: int64
Kostner 2014 2 86    13509
Name: 2, dtype: int64
Kostner 2015 2 87    12400
Name: 2, dtype: int64
Kostner 2016 2 87    13120
Name: 2, dtype: int64
Kostner 2017 2 87    11744
Name: 2, dtype: int64
Kostner 2018 2 87    10650
Name: 2, dtype: int64
Kostner 2019 2 87    11156
Name: 2, dtype: int64
Kostner 2013 3 86    12161
Name: 3, dtype: int64
Kostner 2014 3 86    15405
Name: 3, dtype: int64
Kostner 2015 3 87    15132
Name: 3, dtype: int64
Kostner 2016 3 87    14089
Name: 3, dtype: int64
Kostner 2017 3 87    13351
Name: 3, dtype: int64
Kostner 2018 3 87    11958
Name: 3, dtype: int64
Kostner 2019 3 87    12145
Name: 3, dtype: int64
Kostner 2013 4 86    13566
Name: 4, dtype: int64
Kostner 2014 4 86    14447
Name: 4, dtype: int64
Kostner 2015 4 87    14899
Name: 4, dtype: int64
Kostner 2016 4 87    12734
Name: 4, dtype: int64
Kostner 2017 4 87    12519
Name: 4, dtype: int64
Kostner 2018 4 87    11810
Name: 4, dtype: int64
Kostner 2019 4 87    12054
Name: 4, dtype: int64
Kostner 2013 5 86    13730
Name: 5, dtype: int64
Kostner 2014 5 86    15076
Name: 5, dtype: int64
Kostner 2015 5 87    14914
Name: 5, dtype: int64
Kostner 2016 5 87    14187
Name: 5, dtype: int64
Kostner 2017 5 87    13967
Name: 5, dtype: int64
Kostner 2018 5 87    13251
Name: 5, dtype: int64
Kostner 2019 5 87    12961
Name: 5, dtype: int64
Kostner 2013 6 86    12695
Name: 6, dtype: int64
Kostner 2014 6 86    13659
Name: 6, dtype: int64
Kostner 2015 6 87    15086
Name: 6, dtype: int64
Kostner 2016 6 87    14122
Name: 6, dtype: int64
Kostner 2017 6 87    13677
Name: 6, dtype: int64
Kostner 2018 6 87    12906
Name: 6, dtype: int64
Kostner 2019 6 87    12326
Name: 6, dtype: int64
Kostner 2013 7 86    12813
Name: 7, dtype: int64
Kostner 2014 7 86    14571
Name: 7, dtype: int64
Kostner 2015 7 87    15158
Name: 7, dtype: int64
Kostner 2016 7 87    13949
Name: 7, dtype: int64
Kostner 2017 7 87    12936
Name: 7, dtype: int64
Kostner 2018 7 87    13235
Name: 7, dtype: int64
Kostner 2019 7 87    12468
Name: 7, dtype: int64
Kostner 2013 8 86    13112
Name: 8, dtype: int64
Kostner 2014 8 86    14136
Name: 8, dtype: int64
Kostner 2015 8 87    14651
Name: 8, dtype: int64
Kostner 2016 8 87    13976
Name: 8, dtype: int64
Kostner 2017 8 87    13256
Name: 8, dtype: int64
Kostner 2018 8 87    0
Name: 8, dtype: int64
Kostner 2019 8 87    12162
Name: 8, dtype: int64
Kostner 2013 9 86    13827
Name: 9, dtype: int64
Kostner 2014 9 86    15906
Name: 9, dtype: int64
Kostner 2015 9 87    15644
Name: 9, dtype: int64
Kostner 2016 9 87    14353
Name: 9, dtype: int64
Kostner 2017 9 87    13941
Name: 9, dtype: int64
Kostner 2018 9 87    0
Name: 9, dtype: int64
Kostner 2019 9 87    12391
Name: 9, dtype: int64
Kostner 2013 10 86    15116
Name: 10, dtype: int64
Kostner 2014 10 86    16924
Name: 10, dtype: int64
Kostner 2015 10 87    16039
Name: 10, dtype: int64
Kostner 2016 10 87    14288
Name: 10, dtype: int64
Kostner 2017 10 87    14648
Name: 10, dtype: int64
Kostner 2018 10 87    0
Name: 10, dtype: int64
Kostner 2019 10 87    13053
Name: 10, dtype: int64
Kostner 2013 11 86    13616
Name: 11, dtype: int64
Kostner 2014 11 86    13933
Name: 11, dtype: int64
Kostner 2015 11 87    13880
Name: 11, dtype: int64
Kostner 2016 11 87    13598
Name: 11, dtype: int64
Kostner 2017 11 87    13229
Name: 11, dtype: int64
Kostner 2018 11 87    0
Name: 11, dtype: int64
Kostner 2019 11 87    11329
Name: 11, dtype: int64
Kostner 2013 12 86    13169
Name: 12, dtype: int64
Kostner 2014 12 86    13911
Name: 12, dtype: int64
Kostner 2015 12 87    13669
Name: 12, dtype: int64
Kostner 2016 12 87    12374
Name: 12, dtype: int64
Kostner 2017 12 87    12087
Name: 12, dtype: int64
Kostner 2018 12 87    0
Name: 12, dtype: int64
Kostner 2019 12 87    10789
Name: 12, dtype: int64
Lake/State 2013 1 87    430367
Name: 1, dtype: int64
Lake/State 2014 1 87    463449
Name: 1, dtype: int64
Lake/State 2015 1 88    489045
Name: 1, dtype: int64
Lake/State 2016 1 88    514199
Name: 1, dtype: int64
Lake/State 2017 1 88    510399
Name: 1, dtype: int64
Lake/State 2018 1 88    489912
Name: 1, dtype: int64
Lake/State 2019 1 88    480049
Name: 1, dtype: int64
Lake/State 2013 2 87    392392
Name: 2, dtype: int64
Lake/State 2014 2 87    468164
Name: 2, dtype: int64
Lake/State 2015 2 88    446250
Name: 2, dtype: int64
Lake/State 2016 2 88    532100
Name: 2, dtype: int64
Lake/State 2017 2 88    482414
Name: 2, dtype: int64
Lake/State 2018 2 88    462991
Name: 2, dtype: int64
Lake/State 2019 2 88    481530
Name: 2, dtype: int64
Lake/State 2013 3 87    507760
Name: 3, dtype: int64
Lake/State 2014 3 87    536364
Name: 3, dtype: int64
Lake/State 2015 3 88    556705
Name: 3, dtype: int64
Lake/State 2016 3 88    585413
Name: 3, dtype: int64
Lake/State 2017 3 88    566728
Name: 3, dtype: int64
Lake/State 2018 3 88    539570
Name: 3, dtype: int64
Lake/State 2019 3 88    530400
Name: 3, dtype: int64
Lake/State 2013 4 87    496532
Name: 4, dtype: int64
Lake/State 2014 4 87    535918
Name: 4, dtype: int64
Lake/State 2015 4 88    572031
Name: 4, dtype: int64
Lake/State 2016 4 88    569004
Name: 4, dtype: int64
Lake/State 2017 4 88    528215
Name: 4, dtype: int64
Lake/State 2018 4 88    518687
Name: 4, dtype: int64
Lake/State 2019 4 88    528643
Name: 4, dtype: int64
Lake/State 2013 5 87    487341
Name: 5, dtype: int64
Lake/State 2014 5 87    535223
Name: 5, dtype: int64
Lake/State 2015 5 88    589426
Name: 5, dtype: int64
Lake/State 2016 5 88    585593
Name: 5, dtype: int64
Lake/State 2017 5 88    566736
Name: 5, dtype: int64
Lake/State 2018 5 88    548748
Name: 5, dtype: int64
Lake/State 2019 5 88    551602
Name: 5, dtype: int64
Lake/State 2013 6 87    463189
Name: 6, dtype: int64
Lake/State 2014 6 87    561807
Name: 6, dtype: int64
Lake/State 2015 6 88    626407
Name: 6, dtype: int64
Lake/State 2016 6 88    622054
Name: 6, dtype: int64
Lake/State 2017 6 88    604959
Name: 6, dtype: int64
Lake/State 2018 6 88    573521
Name: 6, dtype: int64
Lake/State 2019 6 88    557473
Name: 6, dtype: int64
Lake/State 2013 7 87    503012
Name: 7, dtype: int64
Lake/State 2014 7 87    591670
Name: 7, dtype: int64
Lake/State 2015 7 88    670496
Name: 7, dtype: int64
Lake/State 2016 7 88    615773
Name: 7, dtype: int64
Lake/State 2017 7 88    583308
Name: 7, dtype: int64
Lake/State 2018 7 88    583522
Name: 7, dtype: int64
Lake/State 2019 7 88    570382
Name: 7, dtype: int64
Lake/State 2013 8 87    498837
Name: 8, dtype: int64
Lake/State 2014 8 87    577359
Name: 8, dtype: int64
Lake/State 2015 8 88    633465
Name: 8, dtype: int64
Lake/State 2016 8 88    620554
Name: 8, dtype: int64
Lake/State 2017 8 88    613575
Name: 8, dtype: int64
Lake/State 2018 8 88    0
Name: 8, dtype: int64
Lake/State 2019 8 88    572898
Name: 8, dtype: int64
Lake/State 2013 9 87    469739
Name: 9, dtype: int64
Lake/State 2014 9 87    571476
Name: 9, dtype: int64
Lake/State 2015 9 88    648879
Name: 9, dtype: int64
Lake/State 2016 9 88    602868
Name: 9, dtype: int64
Lake/State 2017 9 88    567880
Name: 9, dtype: int64
Lake/State 2018 9 88    0
Name: 9, dtype: int64
Lake/State 2019 9 88    548715
Name: 9, dtype: int64
Lake/State 2013 10 87    531878
Name: 10, dtype: int64
Lake/State 2014 10 87    610648
Name: 10, dtype: int64
Lake/State 2015 10 88    646403
Name: 10, dtype: int64
Lake/State 2016 10 88    628332
Name: 10, dtype: int64
Lake/State 2017 10 88    597484
Name: 10, dtype: int64
Lake/State 2018 10 88    0
Name: 10, dtype: int64
Lake/State 2019 10 88    594404
Name: 10, dtype: int64
Lake/State 2013 11 87    508017
Name: 11, dtype: int64
Lake/State 2014 11 87    535861
Name: 11, dtype: int64
Lake/State 2015 11 88    562288
Name: 11, dtype: int64
Lake/State 2016 11 88    595317
Name: 11, dtype: int64
Lake/State 2017 11 88    531893
Name: 11, dtype: int64
Lake/State 2018 11 88    0
Name: 11, dtype: int64
Lake/State 2019 11 88    532140
Name: 11, dtype: int64
Lake/State 2013 12 87    503669
Name: 12, dtype: int64
Lake/State 2014 12 87    548983
Name: 12, dtype: int64
Lake/State 2015 12 88    569977
Name: 12, dtype: int64
Lake/State 2016 12 88    542698
Name: 12, dtype: int64
Lake/State 2017 12 88    496810
Name: 12, dtype: int64
Lake/State 2018 12 88    0
Name: 12, dtype: int64
Lake/State 2019 12 88    502603
Name: 12, dtype: int64
Laramie 2013 1 88    34929
Name: 1, dtype: int64
Laramie 2014 1 88    32818
Name: 1, dtype: int64
Laramie 2015 1 89    35206
Name: 1, dtype: int64
Laramie 2016 1 89    33434
Name: 1, dtype: int64
Laramie 2017 1 89    29238
Name: 1, dtype: int64
Laramie 2018 1 89    27721
Name: 1, dtype: int64
Laramie 2019 1 89    25346
Name: 1, dtype: int64
Laramie 2013 2 88    32716
Name: 2, dtype: int64
Laramie 2014 2 88    33384
Name: 2, dtype: int64
Laramie 2015 2 89    32787
Name: 2, dtype: int64
Laramie 2016 2 89    32726
Name: 2, dtype: int64
Laramie 2017 2 89    29403
Name: 2, dtype: int64
Laramie 2018 2 89    26779
Name: 2, dtype: int64
Laramie 2019 2 89    25788
Name: 2, dtype: int64
Laramie 2013 3 88    34745
Name: 3, dtype: int64
Laramie 2014 3 88    38261
Name: 3, dtype: int64
Laramie 2015 3 89    38695
Name: 3, dtype: int64
Laramie 2016 3 89    35073
Name: 3, dtype: int64
Laramie 2017 3 89    31180
Name: 3, dtype: int64
Laramie 2018 3 89    29185
Name: 3, dtype: int64
Laramie 2019 3 89    28957
Name: 3, dtype: int64
Laramie 2013 4 88    35729
Name: 4, dtype: int64
Laramie 2014 4 88    38308
Name: 4, dtype: int64
Laramie 2015 4 89    37632
Name: 4, dtype: int64
Laramie 2016 4 89    50639
Name: 4, dtype: int64
Laramie 2017 4 89    28790
Name: 4, dtype: int64
Laramie 2018 4 89    28813
Name: 4, dtype: int64
Laramie 2019 4 89    28895
Name: 4, dtype: int64
Laramie 2013 5 88    38937
Name: 5, dtype: int64
Laramie 2014 5 88    40919
Name: 5, dtype: int64
Laramie 2015 5 89    38939
Name: 5, dtype: int64
Laramie 2016 5 89    51932
Name: 5, dtype: int64
Laramie 2017 5 89    32252
Name: 5, dtype: int64
Laramie 2018 5 89    32020
Name: 5, dtype: int64
Laramie 2019 5 89    31363
Name: 5, dtype: int64
Laramie 2013 6 88    37721
Name: 6, dtype: int64
Laramie 2014 6 88    39075
Name: 6, dtype: int64
Laramie 2015 6 89    39187
Name: 6, dtype: int64
Laramie 2016 6 89    34086
Name: 6, dtype: int64
Laramie 2017 6 89    32542
Name: 6, dtype: int64
Laramie 2018 6 89    31043
Name: 6, dtype: int64
Laramie 2019 6 89    29140
Name: 6, dtype: int64
Laramie 2013 7 88    38642
Name: 7, dtype: int64
Laramie 2014 7 88    40526
Name: 7, dtype: int64
Laramie 2015 7 89    40053
Name: 7, dtype: int64
Laramie 2016 7 89    32635
Name: 7, dtype: int64
Laramie 2017 7 89    30906
Name: 7, dtype: int64
Laramie 2018 7 89    30940
Name: 7, dtype: int64
Laramie 2019 7 89    29026
Name: 7, dtype: int64
Laramie 2013 8 88    41050
Name: 8, dtype: int64
Laramie 2014 8 88    40388
Name: 8, dtype: int64
Laramie 2015 8 89    38696
Name: 8, dtype: int64
Laramie 2016 8 89    32895
Name: 8, dtype: int64
Laramie 2017 8 89    32471
Name: 8, dtype: int64
Laramie 2018 8 89    0
Name: 8, dtype: int64
Laramie 2019 8 89    29142
Name: 8, dtype: int64
Laramie 2013 9 88    41096
Name: 9, dtype: int64
Laramie 2014 9 88    43082
Name: 9, dtype: int64
Laramie 2015 9 89    40389
Name: 9, dtype: int64
Laramie 2016 9 89    34351
Name: 9, dtype: int64
Laramie 2017 9 89    32907
Name: 9, dtype: int64
Laramie 2018 9 89    0
Name: 9, dtype: int64
Laramie 2019 9 89    28621
Name: 9, dtype: int64
Laramie 2013 10 88    43337
Name: 10, dtype: int64
Laramie 2014 10 88    44718
Name: 10, dtype: int64
Laramie 2015 10 89    41777
Name: 10, dtype: int64
Laramie 2016 10 89    35840
Name: 10, dtype: int64
Laramie 2017 10 89    34183
Name: 10, dtype: int64
Laramie 2018 10 89    0
Name: 10, dtype: int64
Laramie 2019 10 89    29738
Name: 10, dtype: int64
Laramie 2013 11 88    37077
Name: 11, dtype: int64
Laramie 2014 11 88    36195
Name: 11, dtype: int64
Laramie 2015 11 89    36346
Name: 11, dtype: int64
Laramie 2016 11 89    33006
Name: 11, dtype: int64
Laramie 2017 11 89    30584
Name: 11, dtype: int64
Laramie 2018 11 89    0
Name: 11, dtype: int64
Laramie 2019 11 89    25876
Name: 11, dtype: int64
Laramie 2013 12 88    34893
Name: 12, dtype: int64
Laramie 2014 12 88    37850
Name: 12, dtype: int64
Laramie 2015 12 89    36337
Name: 12, dtype: int64
Laramie 2016 12 89    29486
Name: 12, dtype: int64
Laramie 2017 12 89    28211
Name: 12, dtype: int64
Laramie 2018 12 89    0
Name: 12, dtype: int64
Laramie 2019 12 89    25229
Name: 12, dtype: int64
LaSalle 2013 1 89    64929
Name: 1, dtype: int64
LaSalle 2014 1 89    65420
Name: 1, dtype: int64
LaSalle 2015 1 90    67232
Name: 1, dtype: int64
LaSalle 2016 1 90    69432
Name: 1, dtype: int64
LaSalle 2017 1 90    72705
Name: 1, dtype: int64
LaSalle 2018 1 90    67539
Name: 1, dtype: int64
LaSalle 2019 1 90    61621
Name: 1, dtype: int64
LaSalle 2013 2 89    71788
Name: 2, dtype: int64
LaSalle 2014 2 89    74349
Name: 2, dtype: int64
LaSalle 2015 2 90    72984
Name: 2, dtype: int64
LaSalle 2016 2 90    79925
Name: 2, dtype: int64
LaSalle 2017 2 90    73562
Name: 2, dtype: int64
LaSalle 2018 2 90    69488
Name: 2, dtype: int64
LaSalle 2019 2 90    68420
Name: 2, dtype: int64
LaSalle 2013 3 89    75927
Name: 3, dtype: int64
LaSalle 2014 3 89    79980
Name: 3, dtype: int64
LaSalle 2015 3 90    81211
Name: 3, dtype: int64
LaSalle 2016 3 90    87758
Name: 3, dtype: int64
LaSalle 2017 3 90    84013
Name: 3, dtype: int64
LaSalle 2018 3 90    78315
Name: 3, dtype: int64
LaSalle 2019 3 90    73265
Name: 3, dtype: int64
LaSalle 2013 4 89    81672
Name: 4, dtype: int64
LaSalle 2014 4 89    81389
Name: 4, dtype: int64
LaSalle 2015 4 90    81739
Name: 4, dtype: int64
LaSalle 2016 4 90    85352
Name: 4, dtype: int64
LaSalle 2017 4 90    78360
Name: 4, dtype: int64
LaSalle 2018 4 90    76781
Name: 4, dtype: int64
LaSalle 2019 4 90    74858
Name: 4, dtype: int64
LaSalle 2013 5 89    75001
Name: 5, dtype: int64
LaSalle 2014 5 89    75993
Name: 5, dtype: int64
LaSalle 2015 5 90    75470
Name: 5, dtype: int64
LaSalle 2016 5 90    79183
Name: 5, dtype: int64
LaSalle 2017 5 90    77790
Name: 5, dtype: int64
LaSalle 2018 5 90    75991
Name: 5, dtype: int64
LaSalle 2019 5 90    73333
Name: 5, dtype: int64
LaSalle 2013 6 89    68804
Name: 6, dtype: int64
LaSalle 2014 6 89    69052
Name: 6, dtype: int64
LaSalle 2015 6 90    75187
Name: 6, dtype: int64
LaSalle 2016 6 90    78993
Name: 6, dtype: int64
LaSalle 2017 6 90    75051
Name: 6, dtype: int64
LaSalle 2018 6 90    71782
Name: 6, dtype: int64
LaSalle 2019 6 90    69332
Name: 6, dtype: int64
LaSalle 2013 7 89    71487
Name: 7, dtype: int64
LaSalle 2014 7 89    71194
Name: 7, dtype: int64
LaSalle 2015 7 90    79513
Name: 7, dtype: int64
LaSalle 2016 7 90    84404
Name: 7, dtype: int64
LaSalle 2017 7 90    69486
Name: 7, dtype: int64
LaSalle 2018 7 90    70219
Name: 7, dtype: int64
LaSalle 2019 7 90    70634
Name: 7, dtype: int64
LaSalle 2013 8 89    74315
Name: 8, dtype: int64
LaSalle 2014 8 89    69341
Name: 8, dtype: int64
LaSalle 2015 8 90    73627
Name: 8, dtype: int64
LaSalle 2016 8 90    77528
Name: 8, dtype: int64
LaSalle 2017 8 90    81740
Name: 8, dtype: int64
LaSalle 2018 8 90    0
Name: 8, dtype: int64
LaSalle 2019 8 90    75824
Name: 8, dtype: int64
LaSalle 2013 9 89    85956
Name: 9, dtype: int64
LaSalle 2014 9 89    86756
Name: 9, dtype: int64
LaSalle 2015 9 90    85455
Name: 9, dtype: int64
LaSalle 2016 9 90    88812
Name: 9, dtype: int64
LaSalle 2017 9 90    82392
Name: 9, dtype: int64
LaSalle 2018 9 90    0
Name: 9, dtype: int64
LaSalle 2019 9 90    81986
Name: 9, dtype: int64
LaSalle 2013 10 89    96471
Name: 10, dtype: int64
LaSalle 2014 10 89    94361
Name: 10, dtype: int64
LaSalle 2015 10 90    94426
Name: 10, dtype: int64
LaSalle 2016 10 90    95822
Name: 10, dtype: int64
LaSalle 2017 10 90    91358

Name: 10, dtype: int64
LaSalle 2018 10 90    0
Name: 10, dtype: int64
LaSalle 2019 10 90    89747
Name: 10, dtype: int64
LaSalle 2013 11 89    81495
Name: 11, dtype: int64
LaSalle 2014 11 89    73921
Name: 11, dtype: int64
LaSalle 2015 11 90    79575
Name: 11, dtype: int64
LaSalle 2016 11 90    87143
Name: 11, dtype: int64
LaSalle 2017 11 90    78256
Name: 11, dtype: int64
LaSalle 2018 11 90    0
Name: 11, dtype: int64
LaSalle 2019 11 90    72995
Name: 11, dtype: int64
LaSalle 2013 12 89    65592
Name: 12, dtype: int64
LaSalle 2014 12 89    66033
Name: 12, dtype: int64
LaSalle 2015 12 90    71363
Name: 12, dtype: int64
LaSalle 2016 12 90    67154
Name: 12, dtype: int64
LaSalle 2017 12 90    62941
Name: 12, dtype: int64
LaSalle 2018 12 90    0
Name: 12, dtype: int64
LaSalle 2019 12 90    61325
Name: 12, dtype: int64
LaSalle/Van Buren 2013 1 90    71727
Name: 1, dtype: int64
LaSalle/Van Buren 2014 1 90    69650
Name: 1, dtype: int64
LaSalle/Van Buren 2015 1 91    63736
Name: 1, dtype: int64
LaSalle/Van Buren 2016 1 91    64004
Name: 1, dtype: int64
LaSalle/Van Buren 2017 1 91    65950
Name: 1, dtype: int64
LaSalle/Van Buren 2018 1 91    71096
Name: 1, dtype: int64
LaSalle/Van Buren 2019 1 91    64815
Name: 1, dtype: int64
LaSalle/Van Buren 2013 2 90    65571
Name: 2, dtype: int64
LaSalle/Van Buren 2014 2 90    69362
Name: 2, dtype: int64
LaSalle/Van Buren 2015 2 91    62124
Name: 2, dtype: int64
LaSalle/Van Buren 2016 2 91    65947
Name: 2, dtype: int64
LaSalle/Van Buren 2017 2 91    60834
Name: 2, dtype: int64
LaSalle/Van Buren 2018 2 91    65738
Name: 2, dtype: int64
LaSalle/Van Buren 2019 2 91    65944
Name: 2, dtype: int64
LaSalle/Van Buren 2013 3 90    54672
Name: 3, dtype: int64
LaSalle/Van Buren 2014 3 90    73384
Name: 3, dtype: int64
LaSalle/Van Buren 2015 3 91    68336
Name: 3, dtype: int64
LaSalle/Van Buren 2016 3 91    71679
Name: 3, dtype: int64
LaSalle/Van Buren 2017 3 91    73361
Name: 3, dtype: int64
LaSalle/Van Buren 2018 3 91    72857
Name: 3, dtype: int64
LaSalle/Van Buren 2019 3 91    69621
Name: 3, dtype: int64
LaSalle/Van Buren 2013 4 90    65376
Name: 4, dtype: int64
LaSalle/Van Buren 2014 4 90    72782
Name: 4, dtype: int64
LaSalle/Van Buren 2015 4 91    64357
Name: 4, dtype: int64
LaSalle/Van Buren 2016 4 91    65760
Name: 4, dtype: int64
LaSalle/Van Buren 2017 4 91    64008
Name: 4, dtype: int64
LaSalle/Van Buren 2018 4 91    68563
Name: 4, dtype: int64
LaSalle/Van Buren 2019 4 91    70532
Name: 4, dtype: int64
LaSalle/Van Buren 2013 5 90    61933
Name: 5, dtype: int64
LaSalle/Van Buren 2014 5 90    70066
Name: 5, dtype: int64
LaSalle/Van Buren 2015 5 91    58954
Name: 5, dtype: int64
LaSalle/Van Buren 2016 5 91    66460
Name: 5, dtype: int64
LaSalle/Van Buren 2017 5 91    70490
Name: 5, dtype: int64
LaSalle/Van Buren 2018 5 91    71254
Name: 5, dtype: int64
LaSalle/Van Buren 2019 5 91    72463
Name: 5, dtype: int64
LaSalle/Van Buren 2013 6 90    65792
Name: 6, dtype: int64
LaSalle/Van Buren 2014 6 90    69744
Name: 6, dtype: int64
LaSalle/Van Buren 2015 6 91    69088
Name: 6, dtype: int64
LaSalle/Van Buren 2016 6 91    71766
Name: 6, dtype: int64
LaSalle/Van Buren 2017 6 91    71404
Name: 6, dtype: int64
LaSalle/Van Buren 2018 6 91    71112
Name: 6, dtype: int64
LaSalle/Van Buren 2019 6 91    67917
Name: 6, dtype: int64
LaSalle/Van Buren 2013 7 90    70374
Name: 7, dtype: int64
LaSalle/Van Buren 2014 7 90    70457
Name: 7, dtype: int64
LaSalle/Van Buren 2015 7 91    68003
Name: 7, dtype: int64
LaSalle/Van Buren 2016 7 91    66342
Name: 7, dtype: int64
LaSalle/Van Buren 2017 7 91    64163
Name: 7, dtype: int64
LaSalle/Van Buren 2018 7 91    0
Name: 7, dtype: int64
LaSalle/Van Buren 2019 7 91    72550
Name: 7, dtype: int64
LaSalle/Van Buren 2013 8 90    69839
Name: 8, dtype: int64
LaSalle/Van Buren 2014 8 90    66230
Name: 8, dtype: int64
LaSalle/Van Buren 2015 8 91    62278
Name: 8, dtype: int64
LaSalle/Van Buren 2016 8 91    71151
Name: 8, dtype: int64
LaSalle/Van Buren 2017 8 91    73432
Name: 8, dtype: int64
LaSalle/Van Buren 2018 8 91    0
Name: 8, dtype: int64
LaSalle/Van Buren 2019 8 91    71674
Name: 8, dtype: int64
LaSalle/Van Buren 2013 9 90    66940
Name: 9, dtype: int64
LaSalle/Van Buren 2014 9 90    67056
Name: 9, dtype: int64
LaSalle/Van Buren 2015 9 91    64608
Name: 9, dtype: int64
LaSalle/Van Buren 2016 9 91    68159
Name: 9, dtype: int64
LaSalle/Van Buren 2017 9 91    65934
Name: 9, dtype: int64
LaSalle/Van Buren 2018 9 91    0
Name: 9, dtype: int64
LaSalle/Van Buren 2019 9 91    68671
Name: 9, dtype: int64
LaSalle/Van Buren 2013 10 90    76934
Name: 10, dtype: int64
LaSalle/Van Buren 2014 10 90    72743
Name: 10, dtype: int64
LaSalle/Van Buren 2015 10 91    69249
Name: 10, dtype: int64
LaSalle/Van Buren 2016 10 91    69490
Name: 10, dtype: int64
LaSalle/Van Buren 2017 10 91    74307
Name: 10, dtype: int64
LaSalle/Van Buren 2018 10 91    0
Name: 10, dtype: int64
LaSalle/Van Buren 2019 10 91    78510
Name: 10, dtype: int64
LaSalle/Van Buren 2013 11 90    66259
Name: 11, dtype: int64
LaSalle/Van Buren 2014 11 90    59126
Name: 11, dtype: int64
LaSalle/Van Buren 2015 11 91    61676
Name: 11, dtype: int64
LaSalle/Van Buren 2016 11 91    66155
Name: 11, dtype: int64
LaSalle/Van Buren 2017 11 91    69023
Name: 11, dtype: int64
LaSalle/Van Buren 2018 11 91    0
Name: 11, dtype: int64
LaSalle/Van Buren 2019 11 91    66109
Name: 11, dtype: int64
LaSalle/Van Buren 2013 12 90    62451
Name: 12, dtype: int64
LaSalle/Van Buren 2014 12 90    60387
Name: 12, dtype: int64
LaSalle/Van Buren 2015 12 91    61946
Name: 12, dtype: int64
LaSalle/Van Buren 2016 12 91    59938
Name: 12, dtype: int64
LaSalle/Van Buren 2017 12 91    59214
Name: 12, dtype: int64
LaSalle/Van Buren 2018 12 91    0
Name: 12, dtype: int64
LaSalle/Van Buren 2019 12 91    61257
Name: 12, dtype: int64
Lawrence 2013 1 91    81649
Name: 1, dtype: int64
Lawrence 2014 1 91    57689
Name: 1, dtype: int64
Lawrence 2015 1 92    89349
Name: 1, dtype: int64
Lawrence 2016 1 92    88681
Name: 1, dtype: int64
Lawrence 2017 1 92    92114
Name: 1, dtype: int64
Lawrence 2018 1 92    83400
Name: 1, dtype: int64
Lawrence 2019 1 92    74932
Name: 1, dtype: int64
Lawrence 2013 2 91    77385
Name: 2, dtype: int64
Lawrence 2014 2 91    87767
Name: 2, dtype: int64
Lawrence 2015 2 92    84959
Name: 2, dtype: int64
Lawrence 2016 2 92    89425
Name: 2, dtype: int64
Lawrence 2017 2 92    86977
Name: 2, dtype: int64
Lawrence 2018 2 92    80904
Name: 2, dtype: int64
Lawrence 2019 2 92    75169
Name: 2, dtype: int64
Lawrence 2013 3 91    85875
Name: 3, dtype: int64
Lawrence 2014 3 91    99264
Name: 3, dtype: int64
Lawrence 2015 3 92    94285
Name: 3, dtype: int64
Lawrence 2016 3 92    96081
Name: 3, dtype: int64
Lawrence 2017 3 92    101586
Name: 3, dtype: int64
Lawrence 2018 3 92    88894
Name: 3, dtype: int64
Lawrence 2019 3 92    82722
Name: 3, dtype: int64
Lawrence 2013 4 91    86545
Name: 4, dtype: int64
Lawrence 2014 4 91    100755
Name: 4, dtype: int64
Lawrence 2015 4 92    94559
Name: 4, dtype: int64
Lawrence 2016 4 92    93817
Name: 4, dtype: int64
Lawrence 2017 4 92    92920
Name: 4, dtype: int64
Lawrence 2018 4 92    83761
Name: 4, dtype: int64
Lawrence 2019 4 92    79644
Name: 4, dtype: int64
Lawrence 2013 5 91    92335
Name: 5, dtype: int64
Lawrence 2014 5 91    102508
Name: 5, dtype: int64
Lawrence 2015 5 92    96983
Name: 5, dtype: int64
Lawrence 2016 5 92    95171
Name: 5, dtype: int64
Lawrence 2017 5 92    98970
Name: 5, dtype: int64
Lawrence 2018 5 92    87146
Name: 5, dtype: int64
Lawrence 2019 5 92    87041
Name: 5, dtype: int64
Lawrence 2013 6 91    88854
Name: 6, dtype: int64
Lawrence 2014 6 91    94358
Name: 6, dtype: int64
Lawrence 2015 6 92    95306
Name: 6, dtype: int64
Lawrence 2016 6 92    95147
Name: 6, dtype: int64
Lawrence 2017 6 92    101171
Name: 6, dtype: int64
Lawrence 2018 6 92    84331
Name: 6, dtype: int64
Lawrence 2019 6 92    81655
Name: 6, dtype: int64
Lawrence 2013 7 91    94369
Name: 7, dtype: int64
Lawrence 2014 7 91    101559
Name: 7, dtype: int64
Lawrence 2015 7 92    103605
Name: 7, dtype: int64
Lawrence 2016 7 92    96978
Name: 7, dtype: int64
Lawrence 2017 7 92    97211
Name: 7, dtype: int64
Lawrence 2018 7 92    85909
Name: 7, dtype: int64
Lawrence 2019 7 92    82039
Name: 7, dtype: int64
Lawrence 2013 8 91    91338
Name: 8, dtype: int64
Lawrence 2014 8 91    98848
Name: 8, dtype: int64
Lawrence 2015 8 92    93880
Name: 8, dtype: int64
Lawrence 2016 8 92    93864
Name: 8, dtype: int64
Lawrence 2017 8 92    100267
Name: 8, dtype: int64
Lawrence 2018 8 92    0
Name: 8, dtype: int64
Lawrence 2019 8 92    83456
Name: 8, dtype: int64
Lawrence 2013 9 91    93595
Name: 9, dtype: int64
Lawrence 2014 9 91    101634
Name: 9, dtype: int64
Lawrence 2015 9 92    98682
Name: 9, dtype: int64
Lawrence 2016 9 92    96160
Name: 9, dtype: int64
Lawrence 2017 9 92    98446
Name: 9, dtype: int64
Lawrence 2018 9 92    0
Name: 9, dtype: int64
Lawrence 2019 9 92    87009
Name: 9, dtype: int64
Lawrence 2013 10 91    104747
Name: 10, dtype: int64
Lawrence 2014 10 91    111845
Name: 10, dtype: int64
Lawrence 2015 10 92    106165
Name: 10, dtype: int64
Lawrence 2016 10 92    111030
Name: 10, dtype: int64
Lawrence 2017 10 92    103595
Name: 10, dtype: int64
Lawrence 2018 10 92    0
Name: 10, dtype: int64
Lawrence 2019 10 92    87860
Name: 10, dtype: int64
Lawrence 2013 11 91    99372
Name: 11, dtype: int64
Lawrence 2014 11 91    97806
Name: 11, dtype: int64
Lawrence 2015 11 92    92990

Name: 11, dtype: int64
Lawrence 2016 11 92    102186
Name: 11, dtype: int64
Lawrence 2017 11 92    94819
Name: 11, dtype: int64
Lawrence 2018 11 92    0
Name: 11, dtype: int64
Lawrence 2019 11 92    81357
Name: 11, dtype: int64
Lawrence 2013 12 91    86667
Name: 12, dtype: int64
Lawrence 2014 12 91    92989
Name: 12, dtype: int64
Lawrence 2015 12 92    89001
Name: 12, dtype: int64
Lawrence 2016 12 92    89610
Name: 12, dtype: int64
Lawrence 2017 12 92    81782
Name: 12, dtype: int64
Lawrence 2018 12 92    0
Name: 12, dtype: int64
Lawrence 2019 12 92    72512
Name: 12, dtype: int64
Library 2013 1 92    102535
Name: 1, dtype: int64
Library 2014 1 92    85794
Name: 1, dtype: int64
Library 2015 1 93    89324
Name: 1, dtype: int64
Library 2016 1 93    85493
Name: 1, dtype: int64
Library 2017 1 93    87704
Name: 1, dtype: int64
Library 2018 1 93    83716
Name: 1, dtype: int64
Library 2019 1 93    73427
Name: 1, dtype: int64
Library 2013 2 92    105338
Name: 2, dtype: int64
Library 2014 2 92    96255
Name: 2, dtype: int64
Library 2015 2 93    93882
Name: 2, dtype: int64
Library 2016 2 93    94533
Name: 2, dtype: int64
Library 2017 2 93    86243
Name: 2, dtype: int64
Library 2018 2 93    82473
Name: 2, dtype: int64
Library 2019 2 93    83540
Name: 2, dtype: int64
Library 2013 3 92    94458
Name: 3, dtype: int64
Library 2014 3 92    106138
Name: 3, dtype: int64
Library 2015 3 93    104459
Name: 3, dtype: int64
Library 2016 3 93    99187
Name: 3, dtype: int64
Library 2017 3 93    101272
Name: 3, dtype: int64
Library 2018 3 93    92423
Name: 3, dtype: int64
Library 2019 3 93    89608
Name: 3, dtype: int64
Library 2013 4 92    111301
Name: 4, dtype: int64
Library 2014 4 92    111077
Name: 4, dtype: int64
Library 2015 4 93    105934
Name: 4, dtype: int64
Library 2016 4 93    96137
Name: 4, dtype: int64
Library 2017 4 93    93006
Name: 4, dtype: int64
Library 2018 4 93    90207
Name: 4, dtype: int64
Library 2019 4 93    92735
Name: 4, dtype: int64
Library 2013 5 92    101010
Name: 5, dtype: int64
Library 2014 5 92    104169
Name: 5, dtype: int64
Library 2015 5 93    99374
Name: 5, dtype: int64
Library 2016 5 93    96104
Name: 5, dtype: int64
Library 2017 5 93    96535
Name: 5, dtype: int64
Library 2018 5 93    93924
Name: 5, dtype: int64
Library 2019 5 93    93746
Name: 5, dtype: int64
Library 2013 6 92    98532
Name: 6, dtype: int64
Library 2014 6 92    102635
Name: 6, dtype: int64
Library 2015 6 93    103849
Name: 6, dtype: int64
Library 2016 6 93    116154
Name: 6, dtype: int64
Library 2017 6 93    100762
Name: 6, dtype: int64
Library 2018 6 93    89765
Name: 6, dtype: int64
Library 2019 6 93    80329
Name: 6, dtype: int64
Library 2013 7 92    108073
Name: 7, dtype: int64
Library 2014 7 92    107282
Name: 7, dtype: int64
Library 2015 7 93    109120
Name: 7, dtype: int64
Library 2016 7 93    105887
Name: 7, dtype: int64
Library 2017 7 93    93431
Name: 7, dtype: int64
Library 2018 7 93    0
Name: 7, dtype: int64
Library 2019 7 93    89823
Name: 7, dtype: int64
Library 2013 8 92    109429
Name: 8, dtype: int64
Library 2014 8 92    102015
Name: 8, dtype: int64
Library 2015 8 93    99001
Name: 8, dtype: int64
Library 2016 8 93    102427
Name: 8, dtype: int64
Library 2017 8 93    107814
Name: 8, dtype: int64
Library 2018 8 93    0
Name: 8, dtype: int64
Library 2019 8 93    93843
Name: 8, dtype: int64
Library 2013 9 92    113654
Name: 9, dtype: int64
Library 2014 9 92    114427
Name: 9, dtype: int64
Library 2015 9 93    112082
Name: 9, dtype: int64
Library 2016 9 93    111967
Name: 9, dtype: int64
Library 2017 9 93    104341
Name: 9, dtype: int64
Library 2018 9 93    0
Name: 9, dtype: int64
Library 2019 9 93    104696
Name: 9, dtype: int64
Library 2013 10 92    128977
Name: 10, dtype: int64
Library 2014 10 92    125785
Name: 10, dtype: int64
Library 2015 10 93    119908
Name: 10, dtype: int64
Library 2016 10 93    112050
Name: 10, dtype: int64
Library 2017 10 93    115462
Name: 10, dtype: int64
Library 2018 10 93    0
Name: 10, dtype: int64
Library 2019 10 93    115646
Name: 10, dtype: int64
Library 2013 11 92    103407
Name: 11, dtype: int64
Library 2014 11 92    98401
Name: 11, dtype: int64
Library 2015 11 93    99191
Name: 11, dtype: int64
Library 2016 11 93    103597
Name: 11, dtype: int64
Library 2017 11 93    94286
Name: 11, dtype: int64
Library 2018 11 93    0
Name: 11, dtype: int64
Library 2019 11 93    89060
Name: 11, dtype: int64
Library 2013 12 92    82486
Name: 12, dtype: int64
Library 2014 12 92    86125
Name: 12, dtype: int64
Library 2015 12 93    83124
Name: 12, dtype: int64
Library 2016 12 93    74624
Name: 12, dtype: int64
Library 2017 12 93    72925
Name: 12, dtype: int64
Library 2018 12 93    0
Name: 12, dtype: int64
Library 2019 12 93    70556
Name: 12, dtype: int64
Linden 2013 1 93    20586
Name: 1, dtype: int64
Linden 2014 1 93    18733
Name: 1, dtype: int64
Linden 2015 1 94    19403
Name: 1, dtype: int64
Linden 2016 1 94    19899
Name: 1, dtype: int64
Linden 2017 1 94    20082
Name: 1, dtype: int64
Linden 2018 1 94    19808
Name: 1, dtype: int64
Linden 2019 1 94    18559
Name: 1, dtype: int64
Linden 2013 2 93    18867
Name: 2, dtype: int64
Linden 2014 2 93    18812
Name: 2, dtype: int64
Linden 2015 2 94    17719
Name: 2, dtype: int64
Linden 2016 2 94    19842
Name: 2, dtype: int64
Linden 2017 2 94    18817
Name: 2, dtype: int64
Linden 2018 2 94    18919
Name: 2, dtype: int64
Linden 2019 2 94    18765
Name: 2, dtype: int64
Linden 2013 3 93    19421
Name: 3, dtype: int64
Linden 2014 3 93    21459
Name: 3, dtype: int64
Linden 2015 3 94    21198
Name: 3, dtype: int64
Linden 2016 3 94    21885
Name: 3, dtype: int64
Linden 2017 3 94    20870
Name: 3, dtype: int64
Linden 2018 3 94    21765
Name: 3, dtype: int64
Linden 2019 3 94    20690
Name: 3, dtype: int64
Linden 2013 4 93    22158
Name: 4, dtype: int64
Linden 2014 4 93    24071
Name: 4, dtype: int64
Linden 2015 4 94    22214
Name: 4, dtype: int64
Linden 2016 4 94    24094
Name: 4, dtype: int64
Linden 2017 4 94    22828
Name: 4, dtype: int64
Linden 2018 4 94    22271
Name: 4, dtype: int64
Linden 2019 4 94    23488
Name: 4, dtype: int64
Linden 2013 5 93    26578
Name: 5, dtype: int64
Linden 2014 5 93    26064
Name: 5, dtype: int64
Linden 2015 5 94    28954
Name: 5, dtype: int64
Linden 2016 5 94    29626
Name: 5, dtype: int64
Linden 2017 5 94    29051
Name: 5, dtype: int64
Linden 2018 5 94    28490
Name: 5, dtype: int64
Linden 2019 5 94    28941
Name: 5, dtype: int64
Linden 2013 6 93    28503
Name: 6, dtype: int64
Linden 2014 6 93    29206
Name: 6, dtype: int64
Linden 2015 6 94    32045
Name: 6, dtype: int64
Linden 2016 6 94    32456
Name: 6, dtype: int64
Linden 2017 6 94    33542
Name: 6, dtype: int64
Linden 2018 6 94    29807
Name: 6, dtype: int64
Linden 2019 6 94    31010
Name: 6, dtype: int64
Linden 2013 7 93    30767
Name: 7, dtype: int64
Linden 2014 7 93    31293
Name: 7, dtype: int64
Linden 2015 7 94    38176
Name: 7, dtype: int64
Linden 2016 7 94    33557
Name: 7, dtype: int64
Linden 2017 7 94    32951
Name: 7, dtype: int64
Linden 2018 7 94    33597
Name: 7, dtype: int64
Linden 2019 7 94    29534
Name: 7, dtype: int64
Linden 2013 8 93    29892
Name: 8, dtype: int64
Linden 2014 8 93    29037
Name: 8, dtype: int64
Linden 2015 8 94    35771
Name: 8, dtype: int64
Linden 2016 8 94    33168
Name: 8, dtype: int64
Linden 2017 8 94    35046
Name: 8, dtype: int64
Linden 2018 8 94    0
Name: 8, dtype: int64
Linden 2019 8 94    31872
Name: 8, dtype: int64
Linden 2013 9 93    24645
Name: 9, dtype: int64
Linden 2014 9 93    26467
Name: 9, dtype: int64
Linden 2015 9 94    31860
Name: 9, dtype: int64
Linden 2016 9 94    28344
Name: 9, dtype: int64
Linden 2017 9 94    27771
Name: 9, dtype: int64
Linden 2018 9 94    0
Name: 9, dtype: int64
Linden 2019 9 94    26602
Name: 9, dtype: int64
Linden 2013 10 93    25049
Name: 10, dtype: int64
Linden 2014 10 93    24411
Name: 10, dtype: int64
Linden 2015 10 94    29876
Name: 10, dtype: int64
Linden 2016 10 94    32814
Name: 10, dtype: int64
Linden 2017 10 94    27985
Name: 10, dtype: int64
Linden 2018 10 94    0
Name: 10, dtype: int64
Linden 2019 10 94    25291
Name: 10, dtype: int64
Linden 2013 11 93    21768
Name: 11, dtype: int64
Linden 2014 11 93    20778
Name: 11, dtype: int64
Linden 2015 11 94    22484
Name: 11, dtype: int64
Linden 2016 11 94    25116
Name: 11, dtype: int64
Linden 2017 11 94    21709
Name: 11, dtype: int64
Linden 2018 11 94    0
Name: 11, dtype: int64
Linden 2019 11 94    21131
Name: 11, dtype: int64
Linden 2013 12 93    20767
Name: 12, dtype: int64
Linden 2014 12 93    21582
Name: 12, dtype: int64
Linden 2015 12 94    21598
Name: 12, dtype: int64
Linden 2016 12 94    20093
Name: 12, dtype: int64
Linden 2017 12 94    20590
Name: 12, dtype: int64
Linden 2018 12 94    0
Name: 12, dtype: int64
Linden 2019 12 94    20438
Name: 12, dtype: int64
Logan Square 2013 1 94    173663
Name: 1, dtype: int64
Logan Square 2014 1 94    175500
Name: 1, dtype: int64
Logan Square 2015 1 95    179723
Name: 1, dtype: int64
Logan Square 2016 1 95    178605
Name: 1, dtype: int64
Logan Square 2017 1 95    178676
Name: 1, dtype: int64
Logan Square 2018 1 95    178391
Name: 1, dtype: int64
Logan Square 2019 1 95    172105
Name: 1, dtype: int64
Logan Square 2013 2 94    167860
Name: 2, dtype: int64
Logan Square 2014 2 94    176097
Name: 2, dtype: int64
Logan Square 2015 2 95    176199
Name: 2, dtype: int64
Logan Square 2016 2 95    183378
Name: 2, dtype: int64
Logan Square 2017 2 95    170402
Name: 2, dtype: int64
Logan Square 2018 2 95    168737
Name: 2, dtype: int64
Logan Square 2019 2 95    174103
Name: 2, dtype: int64
Logan Square 2013 3 94    185105
Name: 3, dtype: int64
Logan Square 2014 3 94    195820
Name: 3, dtype: int64
Logan Square 2015 3 95    197300
Name: 3, dtype: int64
Logan Square 2016 3 95    201998
Name: 3, dtype: int64
Logan Square 2017 3 95    195250
Name: 3, dtype: int64
Logan Square 2018 3 95    193843
Name: 3, dtype: int64
Logan Square 2019 3 95    202442
Name: 3, dtype: int64
Logan Square 2013 4 94    186432
Name: 4, dtype: int64
Logan Square 2014 4 94    181739
Name: 4, dtype: int64
Logan Square 2015 4 95    193825
Name: 4, dtype: int64
Logan Square 2016 4 95    190780
Name: 4, dtype: int64
Logan Square 2017 4 95    181271
Name: 4, dtype: int64
Logan Square 2018 4 95    183443
Name: 4, dtype: int64
Logan Square 2019 4 95    191942
Name: 4, dtype: int64
Logan Square 2013 5 94    184578
Name: 5, dtype: int64
Logan Square 2014 5 94    189467
Name: 5, dtype: int64
Logan Square 2015 5 95    191504
Name: 5, dtype: int64
Logan Square 2016 5 95    192563
Name: 5, dtype: int64
Logan Square 2017 5 95    193297
Name: 5, dtype: int64
Logan Square 2018 5 95    189983
Name: 5, dtype: int64
Logan Square 2019 5 95    196887
Name: 5, dtype: int64
Logan Square 2013 6 94    179401
Name: 6, dtype: int64
Logan Square 2014 6 94    188404
Name: 6, dtype: int64
Logan Square 2015 6 95    197445
Name: 6, dtype: int64
Logan Square 2016 6 95    199408
Name: 6, dtype: int64
Logan Square 2017 6 95    200133
Name: 6, dtype: int64
Logan Square 2018 6 95    190274
Name: 6, dtype: int64
Logan Square 2019 6 95    190180
Name: 6, dtype: int64
Logan Square 2013 7 94    188793
Name: 7, dtype: int64
Logan Square 2014 7 94    185491
Name: 7, dtype: int64
Logan Square 2015 7 95    205877
Name: 7, dtype: int64
Logan Square 2016 7 95    193482
Name: 7, dtype: int64
Logan Square 2017 7 95    188125
Name: 7, dtype: int64
Logan Square 2018 7 95    189361
Name: 7, dtype: int64
Logan Square 2019 7 95    195114
Name: 7, dtype: int64
Logan Square 2013 8 94    191724
Name: 8, dtype: int64
Logan Square 2014 8 94    202895
Name: 8, dtype: int64
Logan Square 2015 8 95    194574
Name: 8, dtype: int64
Logan Square 2016 8 95    197341
Name: 8, dtype: int64
Logan Square 2017 8 95    202104
Name: 8, dtype: int64
Logan Square 2018 8 95    0
Name: 8, dtype: int64
Logan Square 2019 8 95    199211
Name: 8, dtype: int64
Logan Square 2013 9 94    185260
Name: 9, dtype: int64
Logan Square 2014 9 94    216239
Name: 9, dtype: int64
Logan Square 2015 9 95    198958
Name: 9, dtype: int64
Logan Square 2016 9 95    195550
Name: 9, dtype: int64
Logan Square 2017 9 95    194578
Name: 9, dtype: int64
Logan Square 2018 9 95    0
Name: 9, dtype: int64
Logan Square 2019 9 95    188953
Name: 9, dtype: int64
Logan Square 2013 10 94    202384
Name: 10, dtype: int64
Logan Square 2014 10 94    224118
Name: 10, dtype: int64
Logan Square 2015 10 95    210208
Name: 10, dtype: int64
Logan Square 2016 10 95    202487
Name: 10, dtype: int64
Logan Square 2017 10 95    202870
Name: 10, dtype: int64
Logan Square 2018 10 95    0
Name: 10, dtype: int64
Logan Square 2019 10 95    207496
Name: 10, dtype: int64
Logan Square 2013 11 94    180594
Name: 11, dtype: int64
Logan Square 2014 11 94    174364
Name: 11, dtype: int64
Logan Square 2015 11 95    185758
Name: 11, dtype: int64
Logan Square 2016 11 95    190554
Name: 11, dtype: int64
Logan Square 2017 11 95    185390
Name: 11, dtype: int64
Logan Square 2018 11 95    0
Name: 11, dtype: int64
Logan Square 2019 11 95    178638
Name: 11, dtype: int64
Logan Square 2013 12 94    173641
Name: 12, dtype: int64
Logan Square 2014 12 94    175519
Name: 12, dtype: int64
Logan Square 2015 12 95    183848
Name: 12, dtype: int64
Logan Square 2016 12 95    175004
Name: 12, dtype: int64
Logan Square 2017 12 95    168975
Name: 12, dtype: int64
Logan Square 2018 12 95    0
Name: 12, dtype: int64
Logan Square 2019 12 95    164643
Name: 12, dtype: int64
Loyola 2013 1 95    129021
Name: 1, dtype: int64
Loyola 2014 1 95    163251
Name: 1, dtype: int64
Loyola 2015 1 96    142727
Name: 1, dtype: int64
Loyola 2016 1 96    133630
Name: 1, dtype: int64
Loyola 2017 1 96    132993
Name: 1, dtype: int64
Loyola 2018 1 96    125685
Name: 1, dtype: int64
Loyola 2019 1 96    119971
Name: 1, dtype: int64
Loyola 2013 2 95    132290
Name: 2, dtype: int64
Loyola 2014 2 95    146955
Name: 2, dtype: int64
Loyola 2015 2 96    142672
Name: 2, dtype: int64
Loyola 2016 2 96    152559
Name: 2, dtype: int64
Loyola 2017 2 96    140507
Name: 2, dtype: int64
Loyola 2018 2 96    135383
Name: 2, dtype: int64
Loyola 2019 2 96    135528
Name: 2, dtype: int64
Loyola 2013 3 95    138458
Name: 3, dtype: int64
Loyola 2014 3 95    152896
Name: 3, dtype: int64
Loyola 2015 3 96    158598
Name: 3, dtype: int64
Loyola 2016 3 96    152621
Name: 3, dtype: int64
Loyola 2017 3 96    150320
Name: 3, dtype: int64
Loyola 2018 3 96    145987
Name: 3, dtype: int64
Loyola 2019 3 96    144235
Name: 3, dtype: int64
Loyola 2013 4 95    147673
Name: 4, dtype: int64
Loyola 2014 4 95    152430
Name: 4, dtype: int64
Loyola 2015 4 96    155652
Name: 4, dtype: int64
Loyola 2016 4 96    154678
Name: 4, dtype: int64
Loyola 2017 4 96    142113
Name: 4, dtype: int64
Loyola 2018 4 96    141764
Name: 4, dtype: int64
Loyola 2019 4 96    143120
Name: 4, dtype: int64
Loyola 2013 5 95    129685
Name: 5, dtype: int64
Loyola 2014 5 95    138885
Name: 5, dtype: int64
Loyola 2015 5 96    137138
Name: 5, dtype: int64
Loyola 2016 5 96    136712
Name: 5, dtype: int64
Loyola 2017 5 96    129226
Name: 5, dtype: int64
Loyola 2018 5 96    127464
Name: 5, dtype: int64
Loyola 2019 5 96    124690
Name: 5, dtype: int64
Loyola 2013 6 95    129407
Name: 6, dtype: int64
Loyola 2014 6 95    135408
Name: 6, dtype: int64
Loyola 2015 6 96    140719
Name: 6, dtype: int64

Loyola 2016 6 96    142893
Name: 6, dtype: int64
Loyola 2017 6 96    135524
Name: 6, dtype: int64
Loyola 2018 6 96    126227
Name: 6, dtype: int64
Loyola 2019 6 96    123697
Name: 6, dtype: int64
Loyola 2013 7 95    136609
Name: 7, dtype: int64
Loyola 2014 7 95    140579
Name: 7, dtype: int64
Loyola 2015 7 96    146422
Name: 7, dtype: int64
Loyola 2016 7 96    141119
Name: 7, dtype: int64
Loyola 2017 7 96    132596
Name: 7, dtype: int64
Loyola 2018 7 96    127876
Name: 7, dtype: int64
Loyola 2019 7 96    128641
Name: 7, dtype: int64
Loyola 2013 8 95    145414
Name: 8, dtype: int64
Loyola 2014 8 95    150223
Name: 8, dtype: int64
Loyola 2015 8 96    152393
Name: 8, dtype: int64
Loyola 2016 8 96    141678
Name: 8, dtype: int64
Loyola 2017 8 96    140297
Name: 8, dtype: int64
Loyola 2018 8 96    0
Name: 8, dtype: int64
Loyola 2019 8 96    141006
Name: 8, dtype: int64
Loyola 2013 9 95    183950
Name: 9, dtype: int64
Loyola 2014 9 95    178655
Name: 9, dtype: int64
Loyola 2015 9 96    179386
Name: 9, dtype: int64
Loyola 2016 9 96    173690
Name: 9, dtype: int64
Loyola 2017 9 96    168319
Name: 9, dtype: int64
Loyola 2018 9 96    0
Name: 9, dtype: int64
Loyola 2019 9 96    169275
Name: 9, dtype: int64
Loyola 2013 10 95    201957
Name: 10, dtype: int64
Loyola 2014 10 95    182310
Name: 10, dtype: int64
Loyola 2015 10 96    182581
Name: 10, dtype: int64
Loyola 2016 10 96    168980
Name: 10, dtype: int64
Loyola 2017 10 96    165292
Name: 10, dtype: int64
Loyola 2018 10 96    0
Name: 10, dtype: int64
Loyola 2019 10 96    172382
Name: 10, dtype: int64
Loyola 2013 11 95    185702
Name: 11, dtype: int64
Loyola 2014 11 95    155164
Name: 11, dtype: int64
Loyola 2015 11 96    153950
Name: 11, dtype: int64
Loyola 2016 11 96    160281
Name: 11, dtype: int64
Loyola 2017 11 96    146556
Name: 11, dtype: int64
Loyola 2018 11 96    0
Name: 11, dtype: int64
Loyola 2019 11 96    147665
Name: 11, dtype: int64
Loyola 2013 12 95    155002
Name: 12, dtype: int64
Loyola 2014 12 95    130930
Name: 12, dtype: int64
Loyola 2015 12 96    129141
Name: 12, dtype: int64
Loyola 2016 12 96    124949
Name: 12, dtype: int64
Loyola 2017 12 96    118065
Name: 12, dtype: int64
Loyola 2018 12 96    0
Name: 12, dtype: int64
Loyola 2019 12 96    113194
Name: 12, dtype: int64
Main 2013 1 97    29771
Name: 1, dtype: int64
Main 2014 1 97    31455
Name: 1, dtype: int64
Main 2015 1 98    31590
Name: 1, dtype: int64
Main 2016 1 98    29284
Name: 1, dtype: int64
Main 2017 1 98    31708
Name: 1, dtype: int64
Main 2018 1 98    29399
Name: 1, dtype: int64
Main 2019 1 97    26673
Name: 1, dtype: int64
Main 2013 2 97    28983
Name: 2, dtype: int64
Main 2014 2 97    31005
Name: 2, dtype: int64
Main 2015 2 98    29938
Name: 2, dtype: int64
Main 2016 2 98    29845
Name: 2, dtype: int64
Main 2017 2 98    29233
Name: 2, dtype: int64
Main 2018 2 98    28381
Name: 2, dtype: int64
Main 2019 2 97    27374
Name: 2, dtype: int64
Main 2013 3 97    29690
Name: 3, dtype: int64
Main 2014 3 97    34040
Name: 3, dtype: int64
Main 2015 3 98    34083
Name: 3, dtype: int64
Main 2016 3 98    31957
Name: 3, dtype: int64
Main 2017 3 98    32455
Name: 3, dtype: int64
Main 2018 3 98    31380
Name: 3, dtype: int64
Main 2019 3 97    29292
Name: 3, dtype: int64
Main 2013 4 97    32171
Name: 4, dtype: int64
Main 2014 4 97    34104
Name: 4, dtype: int64
Main 2015 4 98    33052
Name: 4, dtype: int64
Main 2016 4 98    31608
Name: 4, dtype: int64
Main 2017 4 98    30787
Name: 4, dtype: int64
Main 2018 4 98    29885
Name: 4, dtype: int64
Main 2019 4 97    30581
Name: 4, dtype: int64
Main 2013 5 97    32441
Name: 5, dtype: int64
Main 2014 5 97    34430
Name: 5, dtype: int64
Main 2015 5 98    32843
Name: 5, dtype: int64
Main 2016 5 98    32564
Name: 5, dtype: int64
Main 2017 5 98    32898
Name: 5, dtype: int64
Main 2018 5 98    31270
Name: 5, dtype: int64
Main 2019 5 97    31307
Name: 5, dtype: int64
Main 2013 6 97    33233
Name: 6, dtype: int64
Main 2014 6 97    35705
Name: 6, dtype: int64
Main 2015 6 98    35400
Name: 6, dtype: int64
Main 2016 6 98    34578
Name: 6, dtype: int64
Main 2017 6 98    34824
Name: 6, dtype: int64
Main 2018 6 98    32922
Name: 6, dtype: int64
Main 2019 6 97    31381
Name: 6, dtype: int64
Main 2013 7 97    32853
Name: 7, dtype: int64
Main 2014 7 97    35451
Name: 7, dtype: int64
Main 2015 7 98    36097
Name: 7, dtype: int64
Main 2016 7 98    33531
Name: 7, dtype: int64
Main 2017 7 98    33379
Name: 7, dtype: int64
Main 2018 7 98    31808
Name: 7, dtype: int64
Main 2019 7 97    31660
Name: 7, dtype: int64
Main 2013 8 97    32713
Name: 8, dtype: int64
Main 2014 8 97    34220
Name: 8, dtype: int64
Main 2015 8 98    33637
Name: 8, dtype: int64
Main 2016 8 98    34408
Name: 8, dtype: int64
Main 2017 8 98    33921
Name: 8, dtype: int64
Main 2018 8 98    0
Name: 8, dtype: int64
Main 2019 8 97    31517
Name: 8, dtype: int64
Main 2013 9 97    32331
Name: 9, dtype: int64
Main 2014 9 97    34384
Name: 9, dtype: int64
Main 2015 9 98    34545
Name: 9, dtype: int64
Main 2016 9 98    35071
Name: 9, dtype: int64
Main 2017 9 98    33015
Name: 9, dtype: int64
Main 2018 9 98    0
Name: 9, dtype: int64
Main 2019 9 97    30013
Name: 9, dtype: int64
Main 2013 10 97    35136
Name: 10, dtype: int64
Main 2014 10 97    36293
Name: 10, dtype: int64
Main 2015 10 98    36693
Name: 10, dtype: int64
Main 2016 10 98    36270
Name: 10, dtype: int64
Main 2017 10 98    34413
Name: 10, dtype: int64
Main 2018 10 98    0
Name: 10, dtype: int64
Main 2019 10 97    33138
Name: 10, dtype: int64
Main 2013 11 97    32373
Name: 11, dtype: int64
Main 2014 11 97    31364
Name: 11, dtype: int64
Main 2015 11 98    31002
Name: 11, dtype: int64
Main 2016 11 98    33499
Name: 11, dtype: int64
Main 2017 11 98    30998
Name: 11, dtype: int64
Main 2018 11 98    0
Name: 11, dtype: int64
Main 2019 11 97    28591
Name: 11, dtype: int64
Main 2013 12 97    30345
Name: 12, dtype: int64
Main 2014 12 97    30990
Name: 12, dtype: int64
Main 2015 12 98    30047
Name: 12, dtype: int64
Main 2016 12 98    28916
Name: 12, dtype: int64
Main 2017 12 98    27433
Name: 12, dtype: int64
Main 2018 12 98    0
Name: 12, dtype: int64
Main 2019 12 97    26695
Name: 12, dtype: int64
Medical Center 2013 1 98    87823
Name: 1, dtype: int64
Medical Center 2014 1 98    81454
Name: 1, dtype: int64
Medical Center 2015 1 99    81011
Name: 1, dtype: int64
Medical Center 2016 1 99    74801
Name: 1, dtype: int64
Medical Center 2017 1 99    69965
Name: 1, dtype: int64
Medical Center 2018 1 99    49296
Name: 1, dtype: int64
Medical Center 2019 1 98    60540
Name: 1, dtype: int64
Medical Center 2013 2 98    85906
Name: 2, dtype: int64
Medical Center 2014 2 98    86781
Name: 2, dtype: int64
Medical Center 2015 2 99    78195
Name: 2, dtype: int64
Medical Center 2016 2 99    79156
Name: 2, dtype: int64
Medical Center 2017 2 99    62803
Name: 2, dtype: int64
Medical Center 2018 2 99    47635
Name: 2, dtype: int64
Medical Center 2019 2 98    64676
Name: 2, dtype: int64
Medical Center 2013 3 98    92887
Name: 3, dtype: int64
Medical Center 2014 3 98    95959
Name: 3, dtype: int64
Medical Center 2015 3 99    92108
Name: 3, dtype: int64
Medical Center 2016 3 99    88569
Name: 3, dtype: int64
Medical Center 2017 3 99    72403
Name: 3, dtype: int64
Medical Center 2018 3 99    52675
Name: 3, dtype: int64
Medical Center 2019 3 98    71043
Name: 3, dtype: int64
Medical Center 2013 4 98    94279
Name: 4, dtype: int64
Medical Center 2014 4 98    91134
Name: 4, dtype: int64
Medical Center 2015 4 99    87288
Name: 4, dtype: int64
Medical Center 2016 4 99    80759
Name: 4, dtype: int64
Medical Center 2017 4 99    65760
Name: 4, dtype: int64
Medical Center 2018 4 99    50313
Name: 4, dtype: int64
Medical Center 2019 4 98    65932
Name: 4, dtype: int64
Medical Center 2013 5 98    85733
Name: 5, dtype: int64
Medical Center 2014 5 98    83231
Name: 5, dtype: int64
Medical Center 2015 5 99    79246
Name: 5, dtype: int64
Medical Center 2016 5 99    74455
Name: 5, dtype: int64
Medical Center 2017 5 99    65779
Name: 5, dtype: int64
Medical Center 2018 5 99    49007
Name: 5, dtype: int64
Medical Center 2019 5 98    63394
Name: 5, dtype: int64
Medical Center 2013 6 98    76907
Name: 6, dtype: int64
Medical Center 2014 6 98    79284
Name: 6, dtype: int64
Medical Center 2015 6 99    83853
Name: 6, dtype: int64
Medical Center 2016 6 99    75794
Name: 6, dtype: int64
Medical Center 2017 6 99    61772
Name: 6, dtype: int64
Medical Center 2018 6 99    45658
Name: 6, dtype: int64
Medical Center 2019 6 98    59112
Name: 6, dtype: int64
Medical Center 2013 7 98    81603
Name: 7, dtype: int64
Medical Center 2014 7 98    81602
Name: 7, dtype: int64
Medical Center 2015 7 99    80730
Name: 7, dtype: int64
Medical Center 2016 7 99    68640
Name: 7, dtype: int64
Medical Center 2017 7 99    56105
Name: 7, dtype: int64
Medical Center 2018 7 99    44390
Name: 7, dtype: int64
Medical Center 2019 7 98    61886
Name: 7, dtype: int64
Medical Center 2013 8 98    84860
Name: 8, dtype: int64
Medical Center 2014 8 98    83867
Name: 8, dtype: int64
Medical Center 2015 8 99    80512
Name: 8, dtype: int64
Medical Center 2016 8 99    72594
Name: 8, dtype: int64
Medical Center 2017 8 99    48901
Name: 8, dtype: int64
Medical Center 2018 8 99    0
Name: 8, dtype: int64
Medical Center 2019 8 98    62892
Name: 8, dtype: int64
Medical Center 2013 9 98    97052
Name: 9, dtype: int64
Medical Center 2014 9 98    101406
Name: 9, dtype: int64
Medical Center 2015 9 99    97369
Name: 9, dtype: int64
Medical Center 2016 9 99    85346
Name: 9, dtype: int64
Medical Center 2017 9 99    55653
Name: 9, dtype: int64
Medical Center 2018 9 99    0
Name: 9, dtype: int64
Medical Center 2019 9 98    74375
Name: 9, dtype: int64
Medical Center 2013 10 98    108886
Name: 10, dtype: int64
Medical Center 2014 10 98    109451
Name: 10, dtype: int64
Medical Center 2015 10 99    101511
Name: 10, dtype: int64
Medical Center 2016 10 99    91637
Name: 10, dtype: int64
Medical Center 2017 10 99    63135
Name: 10, dtype: int64
Medical Center 2018 10 99    0
Name: 10, dtype: int64
Medical Center 2019 10 98    80772
Name: 10, dtype: int64
Medical Center 2013 11 98    91264
Name: 11, dtype: int64
Medical Center 2014 11 98    84282
Name: 11, dtype: int64
Medical Center 2015 11 99    86903
Name: 11, dtype: int64
Medical Center 2016 11 99    81692
Name: 11, dtype: int64
Medical Center 2017 11 99    54338
Name: 11, dtype: int64
Medical Center 2018 11 99    0
Name: 11, dtype: int64
Medical Center 2019 11 98    67275
Name: 11, dtype: int64
Medical Center 2013 12 98    79320
Name: 12, dtype: int64
Medical Center 2014 12 98    79480
Name: 12, dtype: int64
Medical Center 2015 12 99    77880
Name: 12, dtype: int64
Medical Center 2016 12 99    66828
Name: 12, dtype: int64
Medical Center 2017 12 99    44478
Name: 12, dtype: int64
Medical Center 2018 12 99    0
Name: 12, dtype: int64
Medical Center 2019 12 98    57312
Name: 12, dtype: int64
Merchandise Mart 2013 1 99    163104
Name: 1, dtype: int64
Merchandise Mart 2014 1 99    165114
Name: 1, dtype: int64
Merchandise Mart 2015 1 100    169987
Name: 1, dtype: int64
Merchandise Mart 2016 1 100    171926
Name: 1, dtype: int64
Merchandise Mart 2017 1 100    180420
Name: 1, dtype: int64
Merchandise Mart 2018 1 100    192856
Name: 1, dtype: int64
Merchandise Mart 2019 1 99    172847
Name: 1, dtype: int64
Merchandise Mart 2013 2 99    154358
Name: 2, dtype: int64
Merchandise Mart 2014 2 99    167221
Name: 2, dtype: int64
Merchandise Mart 2015 2 100    172123
Name: 2, dtype: int64
Merchandise Mart 2016 2 100    175491
Name: 2, dtype: int64
Merchandise Mart 2017 2 100    167867
Name: 2, dtype: int64
Merchandise Mart 2018 2 100    177737
Name: 2, dtype: int64
Merchandise Mart 2019 2 99    170559
Name: 2, dtype: int64
Merchandise Mart 2013 3 99    145508
Name: 3, dtype: int64
Merchandise Mart 2014 3 99    186444
Name: 3, dtype: int64
Merchandise Mart 2015 3 100    189282
Name: 3, dtype: int64
Merchandise Mart 2016 3 100    193704
Name: 3, dtype: int64
Merchandise Mart 2017 3 100    201121
Name: 3, dtype: int64
Merchandise Mart 2018 3 100    203847
Name: 3, dtype: int64
Merchandise Mart 2019 3 99    190673
Name: 3, dtype: int64
Merchandise Mart 2013 4 99    162661
Name: 4, dtype: int64
Merchandise Mart 2014 4 99    183437
Name: 4, dtype: int64
Merchandise Mart 2015 4 100    171689
Name: 4, dtype: int64
Merchandise Mart 2016 4 100    181713
Name: 4, dtype: int64
Merchandise Mart 2017 4 100    179097
Name: 4, dtype: int64
Merchandise Mart 2018 4 100    193919
Name: 4, dtype: int64
Merchandise Mart 2019 4 99    194647
Name: 4, dtype: int64
Merchandise Mart 2013 5 99    151656
Name: 5, dtype: int64
Merchandise Mart 2014 5 99    175191
Name: 5, dtype: int64
Merchandise Mart 2015 5 100    154050
Name: 5, dtype: int64
Merchandise Mart 2016 5 100    182555
Name: 5, dtype: int64
Merchandise Mart 2017 5 100    193690
Name: 5, dtype: int64
Merchandise Mart 2018 5 100    199299
Name: 5, dtype: int64
Merchandise Mart 2019 5 99    198050
Name: 5, dtype: int64
Merchandise Mart 2013 6 99    162966
Name: 6, dtype: int64
Merchandise Mart 2014 6 99    183137
Name: 6, dtype: int64
Merchandise Mart 2015 6 100    189131
Name: 6, dtype: int64
Merchandise Mart 2016 6 100    203974
Name: 6, dtype: int64
Merchandise Mart 2017 6 100    205104
Name: 6, dtype: int64
Merchandise Mart 2018 6 100    202133
Name: 6, dtype: int64
Merchandise Mart 2019 6 99    196175
Name: 6, dtype: int64
Merchandise Mart 2013 7 99    171533
Name: 7, dtype: int64
Merchandise Mart 2014 7 99    177986
Name: 7, dtype: int64
Merchandise Mart 2015 7 100    177291
Name: 7, dtype: int64
Merchandise Mart 2016 7 100    183924
Name: 7, dtype: int64
Merchandise Mart 2017 7 100    180465
Name: 7, dtype: int64
Merchandise Mart 2018 7 100    0
Name: 7, dtype: int64
Merchandise Mart 2019 7 99    197526
Name: 7, dtype: int64
Merchandise Mart 2013 8 99    167547
Name: 8, dtype: int64
Merchandise Mart 2014 8 99    169080
Name: 8, dtype: int64
Merchandise Mart 2015 8 100    165689
Name: 8, dtype: int64
Merchandise Mart 2016 8 100    205694
Name: 8, dtype: int64
Merchandise Mart 2017 8 100    210288
Name: 8, dtype: int64
Merchandise Mart 2018 8 100    0
Name: 8, dtype: int64
Merchandise Mart 2019 8 99    198979
Name: 8, dtype: int64
Merchandise Mart 2013 9 99    154433
Name: 9, dtype: int64
Merchandise Mart 2014 9 99    175285
Name: 9, dtype: int64
Merchandise Mart 2015 9 100    169245
Name: 9, dtype: int64
Merchandise Mart 2016 9 100    187854
Name: 9, dtype: int64
Merchandise Mart 2017 9 100    184794
Name: 9, dtype: int64
Merchandise Mart 2018 9 100    0
Name: 9, dtype: int64
Merchandise Mart 2019 9 99    185121
Name: 9, dtype: int64
Merchandise Mart 2013 10 99    190893
Name: 10, dtype: int64
Merchandise Mart 2014 10 99    198185
Name: 10, dtype: int64
Merchandise Mart 2015 10 100    197917
Name: 10, dtype: int64
Merchandise Mart 2016 10 100    196527
Name: 10, dtype: int64
Merchandise Mart 2017 10 100    208519
Name: 10, dtype: int64
Merchandise Mart 2018 10 100    0
Name: 10, dtype: int64
Merchandise Mart 2019 10 99    210190
Name: 10, dtype: int64
Merchandise Mart 2013 11 99    159359

Name: 11, dtype: int64
Merchandise Mart 2014 11 99    158633
Name: 11, dtype: int64
Merchandise Mart 2015 11 100    169589
Name: 11, dtype: int64
Merchandise Mart 2016 11 100    179475
Name: 11, dtype: int64
Merchandise Mart 2017 11 100    182179
Name: 11, dtype: int64
Merchandise Mart 2018 11 100    0
Name: 11, dtype: int64
Merchandise Mart 2019 11 99    167799
Name: 11, dtype: int64
Merchandise Mart 2013 12 99    143911
Name: 12, dtype: int64
Merchandise Mart 2014 12 99    160550
Name: 12, dtype: int64
Merchandise Mart 2015 12 100    165458
Name: 12, dtype: int64
Merchandise Mart 2016 12 100    156382
Name: 12, dtype: int64
Merchandise Mart 2017 12 100    155485
Name: 12, dtype: int64
Merchandise Mart 2018 12 100    0
Name: 12, dtype: int64
Merchandise Mart 2019 12 99    155251
Name: 12, dtype: int64
Midway Airport 2013 1 100    203508
Name: 1, dtype: int64
Midway Airport 2014 1 100    190539
Name: 1, dtype: int64
Midway Airport 2015 1 101    194676
Name: 1, dtype: int64
Midway Airport 2016 1 101    196304
Name: 1, dtype: int64
Midway Airport 2017 1 101    195452
Name: 1, dtype: int64
Midway Airport 2018 1 101    193992
Name: 1, dtype: int64
Midway Airport 2019 1 100    170967
Name: 1, dtype: int64
Midway Airport 2013 2 100    190662
Name: 2, dtype: int64
Midway Airport 2014 2 100    191969
Name: 2, dtype: int64
Midway Airport 2015 2 101    182626
Name: 2, dtype: int64
Midway Airport 2016 2 101    199952
Name: 2, dtype: int64
Midway Airport 2017 2 101    190018
Name: 2, dtype: int64
Midway Airport 2018 2 101    182193
Name: 2, dtype: int64
Midway Airport 2019 2 100    173636
Name: 2, dtype: int64
Midway Airport 2013 3 100    219432
Name: 3, dtype: int64
Midway Airport 2014 3 100    229326
Name: 3, dtype: int64
Midway Airport 2015 3 101    229458
Name: 3, dtype: int64
Midway Airport 2016 3 101    233026
Name: 3, dtype: int64
Midway Airport 2017 3 101    225658
Name: 3, dtype: int64
Midway Airport 2018 3 101    217887
Name: 3, dtype: int64
Midway Airport 2019 3 100    199973
Name: 3, dtype: int64
Midway Airport 2013 4 100    230815
Name: 4, dtype: int64
Midway Airport 2014 4 100    235964
Name: 4, dtype: int64
Midway Airport 2015 4 101    232541
Name: 4, dtype: int64
Midway Airport 2016 4 101    226078
Name: 4, dtype: int64
Midway Airport 2017 4 101    216012
Name: 4, dtype: int64
Midway Airport 2018 4 101    213120
Name: 4, dtype: int64
Midway Airport 2019 4 100    208482
Name: 4, dtype: int64
Midway Airport 2013 5 100    245521
Name: 5, dtype: int64
Midway Airport 2014 5 100    242085
Name: 5, dtype: int64
Midway Airport 2015 5 101    238449
Name: 5, dtype: int64
Midway Airport 2016 5 101    242868
Name: 5, dtype: int64
Midway Airport 2017 5 101    238621
Name: 5, dtype: int64
Midway Airport 2018 5 101    233610
Name: 5, dtype: int64
Midway Airport 2019 5 100    221777
Name: 5, dtype: int64
Midway Airport 2013 6 100    245579
Name: 6, dtype: int64
Midway Airport 2014 6 100    246329
Name: 6, dtype: int64
Midway Airport 2015 6 101    256606
Name: 6, dtype: int64
Midway Airport 2016 6 101    248901
Name: 6, dtype: int64
Midway Airport 2017 6 101    250675
Name: 6, dtype: int64
Midway Airport 2018 6 101    229660
Name: 6, dtype: int64
Midway Airport 2019 6 100    215893
Name: 6, dtype: int64
Midway Airport 2013 7 100    243316
Name: 7, dtype: int64
Midway Airport 2014 7 100    256072
Name: 7, dtype: int64
Midway Airport 2015 7 101    271339
Name: 7, dtype: int64
Midway Airport 2016 7 101    251745
Name: 7, dtype: int64
Midway Airport 2017 7 101    237364
Name: 7, dtype: int64
Midway Airport 2018 7 101    0
Name: 7, dtype: int64
Midway Airport 2019 7 100    219685
Name: 7, dtype: int64
Midway Airport 2013 8 100    256277
Name: 8, dtype: int64
Midway Airport 2014 8 100    253302
Name: 8, dtype: int64
Midway Airport 2015 8 101    254130
Name: 8, dtype: int64
Midway Airport 2016 8 101    251735
Name: 8, dtype: int64
Midway Airport 2017 8 101    256863
Name: 8, dtype: int64
Midway Airport 2018 8 101    0
Name: 8, dtype: int64
Midway Airport 2019 8 100    225306
Name: 8, dtype: int64
Midway Airport 2013 9 100    245475
Name: 9, dtype: int64
Midway Airport 2014 9 100    253640
Name: 9, dtype: int64
Midway Airport 2015 9 101    266708
Name: 9, dtype: int64
Midway Airport 2016 9 101    255154
Name: 9, dtype: int64
Midway Airport 2017 9 101    246329
Name: 9, dtype: int64
Midway Airport 2018 9 101    0
Name: 9, dtype: int64
Midway Airport 2019 9 100    223456
Name: 9, dtype: int64
Midway Airport 2013 10 100    262310
Name: 10, dtype: int64
Midway Airport 2014 10 100    265542
Name: 10, dtype: int64
Midway Airport 2015 10 101    269914
Name: 10, dtype: int64
Midway Airport 2016 10 101    262775
Name: 10, dtype: int64
Midway Airport 2017 10 101    254662
Name: 10, dtype: int64
Midway Airport 2018 10 101    0
Name: 10, dtype: int64
Midway Airport 2019 10 100    237265
Name: 10, dtype: int64
Midway Airport 2013 11 100    223372
Name: 11, dtype: int64
Midway Airport 2014 11 100    217360
Name: 11, dtype: int64
Midway Airport 2015 11 101    228873
Name: 11, dtype: int64
Midway Airport 2016 11 101    239111
Name: 11, dtype: int64
Midway Airport 2017 11 101    228651
Name: 11, dtype: int64
Midway Airport 2018 11 101    0
Name: 11, dtype: int64
Midway Airport 2019 11 100    193304
Name: 11, dtype: int64
Midway Airport 2013 12 100    217378
Name: 12, dtype: int64
Midway Airport 2014 12 100    222845
Name: 12, dtype: int64
Midway Airport 2015 12 101    220537
Name: 12, dtype: int64
Midway Airport 2016 12 101    203996
Name: 12, dtype: int64
Midway Airport 2017 12 101    201538
Name: 12, dtype: int64
Midway Airport 2018 12 101    0
Name: 12, dtype: int64
Midway Airport 2019 12 100    187596
Name: 12, dtype: int64
Monroe/Dearborn 2013 1 101    162490
Name: 1, dtype: int64
Monroe/Dearborn 2014 1 101    159261
Name: 1, dtype: int64
Monroe/Dearborn 2015 1 102    163471
Name: 1, dtype: int64
Monroe/Dearborn 2016 1 102    168605
Name: 1, dtype: int64
Monroe/Dearborn 2017 1 102    187173
Name: 1, dtype: int64
Monroe/Dearborn 2018 1 102    189619
Name: 1, dtype: int64
Monroe/Dearborn 2019 1 101    170658
Name: 1, dtype: int64
Monroe/Dearborn 2013 2 101    158675
Name: 2, dtype: int64
Monroe/Dearborn 2014 2 101    163110
Name: 2, dtype: int64
Monroe/Dearborn 2015 2 102    161191
Name: 2, dtype: int64
Monroe/Dearborn 2016 2 102    183047
Name: 2, dtype: int64
Monroe/Dearborn 2017 2 102    181601
Name: 2, dtype: int64
Monroe/Dearborn 2018 2 102    177547
Name: 2, dtype: int64
Monroe/Dearborn 2019 2 101    175389
Name: 2, dtype: int64
Monroe/Dearborn 2013 3 101    177437
Name: 3, dtype: int64
Monroe/Dearborn 2014 3 101    179613
Name: 3, dtype: int64
Monroe/Dearborn 2015 3 102    189915
Name: 3, dtype: int64
Monroe/Dearborn 2016 3 102    203428
Name: 3, dtype: int64
Monroe/Dearborn 2017 3 102    211059
Name: 3, dtype: int64
Monroe/Dearborn 2018 3 102    202780
Name: 3, dtype: int64
Monroe/Dearborn 2019 3 101    189444
Name: 3, dtype: int64
Monroe/Dearborn 2013 4 101    182375
Name: 4, dtype: int64
Monroe/Dearborn 2014 4 101    184008
Name: 4, dtype: int64
Monroe/Dearborn 2015 4 102    188847
Name: 4, dtype: int64
Monroe/Dearborn 2016 4 102    193310
Name: 4, dtype: int64
Monroe/Dearborn 2017 4 102    191287
Name: 4, dtype: int64
Monroe/Dearborn 2018 4 102    195510
Name: 4, dtype: int64
Monroe/Dearborn 2019 4 101    195986
Name: 4, dtype: int64
Monroe/Dearborn 2013 5 101    178590
Name: 5, dtype: int64
Monroe/Dearborn 2014 5 101    178518
Name: 5, dtype: int64
Monroe/Dearborn 2015 5 102    181741
Name: 5, dtype: int64
Monroe/Dearborn 2016 5 102    190347
Name: 5, dtype: int64
Monroe/Dearborn 2017 5 102    203937
Name: 5, dtype: int64
Monroe/Dearborn 2018 5 102    204191
Name: 5, dtype: int64
Monroe/Dearborn 2019 5 101    201110
Name: 5, dtype: int64
Monroe/Dearborn 2013 6 101    171430
Name: 6, dtype: int64
Monroe/Dearborn 2014 6 101    177213
Name: 6, dtype: int64
Monroe/Dearborn 2015 6 102    200281
Name: 6, dtype: int64
Monroe/Dearborn 2016 6 102    200137
Name: 6, dtype: int64
Monroe/Dearborn 2017 6 102    207546
Name: 6, dtype: int64
Monroe/Dearborn 2018 6 102    199120
Name: 6, dtype: int64
Monroe/Dearborn 2019 6 101    191460
Name: 6, dtype: int64
Monroe/Dearborn 2013 7 101    185696
Name: 7, dtype: int64
Monroe/Dearborn 2014 7 101    187086
Name: 7, dtype: int64
Monroe/Dearborn 2015 7 102    206289
Name: 7, dtype: int64
Monroe/Dearborn 2016 7 102    200242
Name: 7, dtype: int64
Monroe/Dearborn 2017 7 102    193441
Name: 7, dtype: int64
Monroe/Dearborn 2018 7 102    197925
Name: 7, dtype: int64
Monroe/Dearborn 2019 7 101    199085
Name: 7, dtype: int64
Monroe/Dearborn 2013 8 101    186987
Name: 8, dtype: int64
Monroe/Dearborn 2014 8 101    180669
Name: 8, dtype: int64
Monroe/Dearborn 2015 8 102    190009
Name: 8, dtype: int64
Monroe/Dearborn 2016 8 102    206547
Name: 8, dtype: int64
Monroe/Dearborn 2017 8 102    216542
Name: 8, dtype: int64
Monroe/Dearborn 2018 8 102    0
Name: 8, dtype: int64
Monroe/Dearborn 2019 8 101    201436
Name: 8, dtype: int64
Monroe/Dearborn 2013 9 101    176793
Name: 9, dtype: int64
Monroe/Dearborn 2014 9 101    183353
Name: 9, dtype: int64
Monroe/Dearborn 2015 9 102    194337
Name: 9, dtype: int64
Monroe/Dearborn 2016 9 102    199473
Name: 9, dtype: int64
Monroe/Dearborn 2017 9 102    195190
Name: 9, dtype: int64
Monroe/Dearborn 2018 9 102    0
Name: 9, dtype: int64
Monroe/Dearborn 2019 9 101    188636
Name: 9, dtype: int64
Monroe/Dearborn 2013 10 101    197305
Name: 10, dtype: int64
Monroe/Dearborn 2014 10 101    201188
Name: 10, dtype: int64
Monroe/Dearborn 2015 10 102    209927
Name: 10, dtype: int64
Monroe/Dearborn 2016 10 102    209895
Name: 10, dtype: int64
Monroe/Dearborn 2017 10 102    213975
Name: 10, dtype: int64
Monroe/Dearborn 2018 10 102    0
Name: 10, dtype: int64
Monroe/Dearborn 2019 10 101    215248
Name: 10, dtype: int64
Monroe/Dearborn 2013 11 101    167518
Name: 11, dtype: int64
Monroe/Dearborn 2014 11 101    160744
Name: 11, dtype: int64
Monroe/Dearborn 2015 11 102    179799
Name: 11, dtype: int64
Monroe/Dearborn 2016 11 102    196549
Name: 11, dtype: int64
Monroe/Dearborn 2017 11 102    192135
Name: 11, dtype: int64
Monroe/Dearborn 2018 11 102    0
Name: 11, dtype: int64
Monroe/Dearborn 2019 11 101    178380
Name: 11, dtype: int64
Monroe/Dearborn 2013 12 101    153198
Name: 12, dtype: int64
Monroe/Dearborn 2014 12 101    159376
Name: 12, dtype: int64
Monroe/Dearborn 2015 12 102    174991
Name: 12, dtype: int64
Monroe/Dearborn 2016 12 102    172660
Name: 12, dtype: int64
Monroe/Dearborn 2017 12 102    166479
Name: 12, dtype: int64
Monroe/Dearborn 2018 12 102    0
Name: 12, dtype: int64
Monroe/Dearborn 2019 12 101    161362
Name: 12, dtype: int64
Monroe/State 2013 1 102    237403
Name: 1, dtype: int64
Monroe/State 2014 1 102    229007
Name: 1, dtype: int64
Monroe/State 2015 1 103    243091
Name: 1, dtype: int64
Monroe/State 2016 1 103    259915
Name: 1, dtype: int64
Monroe/State 2017 1 103    260583
Name: 1, dtype: int64
Monroe/State 2018 1 103    246478
Name: 1, dtype: int64
Monroe/State 2019 1 102    220882
Name: 1, dtype: int64
Monroe/State 2013 2 102    219927
Name: 2, dtype: int64
Monroe/State 2014 2 102    237500
Name: 2, dtype: int64
Monroe/State 2015 2 103    233152
Name: 2, dtype: int64
Monroe/State 2016 2 103    275305
Name: 2, dtype: int64
Monroe/State 2017 2 103    250518
Name: 2, dtype: int64
Monroe/State 2018 2 103    232557
Name: 2, dtype: int64
Monroe/State 2019 2 102    226032
Name: 2, dtype: int64
Monroe/State 2013 3 102    284954
Name: 3, dtype: int64
Monroe/State 2014 3 102    261271
Name: 3, dtype: int64
Monroe/State 2015 3 103    289234
Name: 3, dtype: int64
Monroe/State 2016 3 103    296960
Name: 3, dtype: int64
Monroe/State 2017 3 103    294347
Name: 3, dtype: int64

Monroe/State 2018 3 103    264214
Name: 3, dtype: int64
Monroe/State 2019 3 102    239953
Name: 3, dtype: int64
Monroe/State 2013 4 102    272569
Name: 4, dtype: int64
Monroe/State 2014 4 102    267885
Name: 4, dtype: int64
Monroe/State 2015 4 103    294396
Name: 4, dtype: int64
Monroe/State 2016 4 103    289121
Name: 4, dtype: int64
Monroe/State 2017 4 103    265848
Name: 4, dtype: int64
Monroe/State 2018 4 103    254607
Name: 4, dtype: int64
Monroe/State 2019 4 102    244130
Name: 4, dtype: int64
Monroe/State 2013 5 102    264319
Name: 5, dtype: int64
Monroe/State 2014 5 102    261680
Name: 5, dtype: int64
Monroe/State 2015 5 103    288473
Name: 5, dtype: int64
Monroe/State 2016 5 103    286983
Name: 5, dtype: int64
Monroe/State 2017 5 103    283498
Name: 5, dtype: int64
Monroe/State 2018 5 103    267361
Name: 5, dtype: int64
Monroe/State 2019 5 102    254048
Name: 5, dtype: int64
Monroe/State 2013 6 102    237113
Name: 6, dtype: int64
Monroe/State 2014 6 102    274281
Name: 6, dtype: int64
Monroe/State 2015 6 103    311289
Name: 6, dtype: int64
Monroe/State 2016 6 103    302003
Name: 6, dtype: int64
Monroe/State 2017 6 103    292733
Name: 6, dtype: int64
Monroe/State 2018 6 103    268512
Name: 6, dtype: int64
Monroe/State 2019 6 102    245475
Name: 6, dtype: int64
Monroe/State 2013 7 102    258869
Name: 7, dtype: int64
Monroe/State 2014 7 102    289662
Name: 7, dtype: int64
Monroe/State 2015 7 103    329285
Name: 7, dtype: int64
Monroe/State 2016 7 103    303799
Name: 7, dtype: int64
Monroe/State 2017 7 103    276985
Name: 7, dtype: int64
Monroe/State 2018 7 103    270857
Name: 7, dtype: int64
Monroe/State 2019 7 102    255865
Name: 7, dtype: int64
Monroe/State 2013 8 102    260123
Name: 8, dtype: int64
Monroe/State 2014 8 102    282629
Name: 8, dtype: int64
Monroe/State 2015 8 103    306555
Name: 8, dtype: int64
Monroe/State 2016 8 103    304595
Name: 8, dtype: int64
Monroe/State 2017 8 103    307834
Name: 8, dtype: int64
Monroe/State 2018 8 103    0
Name: 8, dtype: int64
Monroe/State 2019 8 102    262103
Name: 8, dtype: int64
Monroe/State 2013 9 102    259428
Name: 9, dtype: int64
Monroe/State 2014 9 102    284941
Name: 9, dtype: int64
Monroe/State 2015 9 103    310909
Name: 9, dtype: int64
Monroe/State 2016 9 103    290597
Name: 9, dtype: int64
Monroe/State 2017 9 103    272181
Name: 9, dtype: int64
Monroe/State 2018 9 103    0
Name: 9, dtype: int64
Monroe/State 2019 9 102    241735
Name: 9, dtype: int64
Monroe/State 2013 10 102    274177
Name: 10, dtype: int64
Monroe/State 2014 10 102    308198
Name: 10, dtype: int64
Monroe/State 2015 10 103    329217
Name: 10, dtype: int64
Monroe/State 2016 10 103    306393
Name: 10, dtype: int64
Monroe/State 2017 10 103    293767
Name: 10, dtype: int64
Monroe/State 2018 10 103    0
Name: 10, dtype: int64
Monroe/State 2019 10 102    272119
Name: 10, dtype: int64
Monroe/State 2013 11 102    245852
Name: 11, dtype: int64
Monroe/State 2014 11 102    261625
Name: 11, dtype: int64
Monroe/State 2015 11 103    276482
Name: 11, dtype: int64
Monroe/State 2016 11 103    283060
Name: 11, dtype: int64
Monroe/State 2017 11 103    252211
Name: 11, dtype: int64
Monroe/State 2018 11 103    0
Name: 11, dtype: int64
Monroe/State 2019 11 102    227989
Name: 11, dtype: int64
Monroe/State 2013 12 102    231863
Name: 12, dtype: int64
Monroe/State 2014 12 102    259456
Name: 12, dtype: int64
Monroe/State 2015 12 103    275201
Name: 12, dtype: int64
Monroe/State 2016 12 103    254775
Name: 12, dtype: int64
Monroe/State 2017 12 103    228864
Name: 12, dtype: int64
Monroe/State 2018 12 103    0
Name: 12, dtype: int64
Monroe/State 2019 12 102    210478
Name: 12, dtype: int64
Montrose-Brown 2013 1 103    70957
Name: 1, dtype: int64
Montrose-Brown 2014 1 103    71272
Name: 1, dtype: int64
Montrose-Brown 2015 1 104    67718
Name: 1, dtype: int64
Montrose-Brown 2016 1 104    69129
Name: 1, dtype: int64
Montrose-Brown 2017 1 104    70333
Name: 1, dtype: int64
Montrose-Brown 2018 1 104    69286
Name: 1, dtype: int64
Montrose-Brown 2019 1 103    60177
Name: 1, dtype: int64
Montrose-Brown 2013 2 103    67279
Name: 2, dtype: int64
Montrose-Brown 2014 2 103    71324
Name: 2, dtype: int64
Montrose-Brown 2015 2 104    66967
Name: 2, dtype: int64
Montrose-Brown 2016 2 104    70155
Name: 2, dtype: int64
Montrose-Brown 2017 2 104    66632
Name: 2, dtype: int64
Montrose-Brown 2018 2 104    65042
Name: 2, dtype: int64
Montrose-Brown 2019 2 103    60587
Name: 2, dtype: int64
Montrose-Brown 2013 3 103    70030
Name: 3, dtype: int64
Montrose-Brown 2014 3 103    77868
Name: 3, dtype: int64
Montrose-Brown 2015 3 104    74125
Name: 3, dtype: int64
Montrose-Brown 2016 3 104    76267
Name: 3, dtype: int64
Montrose-Brown 2017 3 104    77223
Name: 3, dtype: int64
Montrose-Brown 2018 3 104    73029
Name: 3, dtype: int64
Montrose-Brown 2019 3 103    66295
Name: 3, dtype: int64
Montrose-Brown 2013 4 103    73156
Name: 4, dtype: int64
Montrose-Brown 2014 4 103    76438
Name: 4, dtype: int64
Montrose-Brown 2015 4 104    70966
Name: 4, dtype: int64
Montrose-Brown 2016 4 104    72721
Name: 4, dtype: int64
Montrose-Brown 2017 4 104    71153
Name: 4, dtype: int64
Montrose-Brown 2018 4 104    69353
Name: 4, dtype: int64
Montrose-Brown 2019 4 103    65268
Name: 4, dtype: int64
Montrose-Brown 2013 5 103    72902
Name: 5, dtype: int64
Montrose-Brown 2014 5 103    76253
Name: 5, dtype: int64
Montrose-Brown 2015 5 104    71224
Name: 5, dtype: int64
Montrose-Brown 2016 5 104    74693
Name: 5, dtype: int64
Montrose-Brown 2017 5 104    76658
Name: 5, dtype: int64
Montrose-Brown 2018 5 104    72919
Name: 5, dtype: int64
Montrose-Brown 2019 5 103    69149
Name: 5, dtype: int64
Montrose-Brown 2013 6 103    74541
Name: 6, dtype: int64
Montrose-Brown 2014 6 103    74676
Name: 6, dtype: int64
Montrose-Brown 2015 6 104    73684
Name: 6, dtype: int64
Montrose-Brown 2016 6 104    76680
Name: 6, dtype: int64
Montrose-Brown 2017 6 104    77544
Name: 6, dtype: int64
Montrose-Brown 2018 6 104    71531
Name: 6, dtype: int64
Montrose-Brown 2019 6 103    67631
Name: 6, dtype: int64
Montrose-Brown 2013 7 103    77377
Name: 7, dtype: int64
Montrose-Brown 2014 7 103    74535
Name: 7, dtype: int64
Montrose-Brown 2015 7 104    74569
Name: 7, dtype: int64
Montrose-Brown 2016 7 104    72484
Name: 7, dtype: int64
Montrose-Brown 2017 7 104    72282
Name: 7, dtype: int64
Montrose-Brown 2018 7 104    0
Name: 7, dtype: int64
Montrose-Brown 2019 7 103    68393
Name: 7, dtype: int64
Montrose-Brown 2013 8 103    77851
Name: 8, dtype: int64
Montrose-Brown 2014 8 103    73186
Name: 8, dtype: int64
Montrose-Brown 2015 8 104    70994
Name: 8, dtype: int64
Montrose-Brown 2016 8 104    75622
Name: 8, dtype: int64
Montrose-Brown 2017 8 104    76764
Name: 8, dtype: int64
Montrose-Brown 2018 8 104    0
Name: 8, dtype: int64
Montrose-Brown 2019 8 103    70148
Name: 8, dtype: int64
Montrose-Brown 2013 9 103    75252
Name: 9, dtype: int64
Montrose-Brown 2014 9 103    73681
Name: 9, dtype: int64
Montrose-Brown 2015 9 104    73629
Name: 9, dtype: int64
Montrose-Brown 2016 9 104    74964
Name: 9, dtype: int64
Montrose-Brown 2017 9 104    73090
Name: 9, dtype: int64
Montrose-Brown 2018 9 104    0
Name: 9, dtype: int64
Montrose-Brown 2019 9 103    67951
Name: 9, dtype: int64
Montrose-Brown 2013 10 103    83118
Name: 10, dtype: int64
Montrose-Brown 2014 10 103    79119
Name: 10, dtype: int64
Montrose-Brown 2015 10 104    79695
Name: 10, dtype: int64
Montrose-Brown 2016 10 104    78892
Name: 10, dtype: int64
Montrose-Brown 2017 10 104    77740
Name: 10, dtype: int64
Montrose-Brown 2018 10 104    0
Name: 10, dtype: int64
Montrose-Brown 2019 10 103    74451
Name: 10, dtype: int64
Montrose-Brown 2013 11 103    73278
Name: 11, dtype: int64
Montrose-Brown 2014 11 103    65537
Name: 11, dtype: int64
Montrose-Brown 2015 11 104    69838
Name: 11, dtype: int64
Montrose-Brown 2016 11 104    72805
Name: 11, dtype: int64
Montrose-Brown 2017 11 104    69997
Name: 11, dtype: int64
Montrose-Brown 2018 11 104    0
Name: 11, dtype: int64
Montrose-Brown 2019 11 103    64549
Name: 11, dtype: int64
Montrose-Brown 2013 12 103    68615
Name: 12, dtype: int64
Montrose-Brown 2014 12 103    66973
Name: 12, dtype: int64
Montrose-Brown 2015 12 104    68887
Name: 12, dtype: int64

Montrose-Brown 2016 12 104    65681
Name: 12, dtype: int64
Montrose-Brown 2017 12 104    62737
Name: 12, dtype: int64
Montrose-Brown 2018 12 104    0
Name: 12, dtype: int64
Montrose-Brown 2019 12 103    58967
Name: 12, dtype: int64
Montrose-O'Hare 2013 1 104    57317
Name: 1, dtype: int64
Montrose-O'Hare 2014 1 104    56259
Name: 1, dtype: int64
Montrose-O'Hare 2015 1 105    59229
Name: 1, dtype: int64
Montrose-O'Hare 2016 1 105    56167
Name: 1, dtype: int64
Montrose-O'Hare 2017 1 105    60903
Name: 1, dtype: int64
Montrose-O'Hare 2018 1 105    62586
Name: 1, dtype: int64
Montrose-O'Hare 2019 1 104    59385
Name: 1, dtype: int64
Montrose-O'Hare 2013 2 104    54083
Name: 2, dtype: int64
Montrose-O'Hare 2014 2 104    57643
Name: 2, dtype: int64
Montrose-O'Hare 2015 2 105    56201
Name: 2, dtype: int64
Montrose-O'Hare 2016 2 105    58381
Name: 2, dtype: int64
Montrose-O'Hare 2017 2 105    58953
Name: 2, dtype: int64
Montrose-O'Hare 2018 2 105    59060
Name: 2, dtype: int64
Montrose-O'Hare 2019 2 104    59808
Name: 2, dtype: int64
Montrose-O'Hare 2013 3 104    59642
Name: 3, dtype: int64
Montrose-O'Hare 2014 3 104    64195
Name: 3, dtype: int64
Montrose-O'Hare 2015 3 105    66708
Name: 3, dtype: int64
Montrose-O'Hare 2016 3 105    65127
Name: 3, dtype: int64
Montrose-O'Hare 2017 3 105    67573
Name: 3, dtype: int64
Montrose-O'Hare 2018 3 105    67242
Name: 3, dtype: int64
Montrose-O'Hare 2019 3 104    65950
Name: 3, dtype: int64
Montrose-O'Hare 2013 4 104    62087
Name: 4, dtype: int64
Montrose-O'Hare 2014 4 104    64640
Name: 4, dtype: int64
Montrose-O'Hare 2015 4 105    66233
Name: 4, dtype: int64
Montrose-O'Hare 2016 4 105    59189
Name: 4, dtype: int64
Montrose-O'Hare 2017 4 105    61200
Name: 4, dtype: int64
Montrose-O'Hare 2018 4 105    64799
Name: 4, dtype: int64
Montrose-O'Hare 2019 4 104    66046
Name: 4, dtype: int64
Montrose-O'Hare 2013 5 104    60957
Name: 5, dtype: int64
Montrose-O'Hare 2014 5 104    64137
Name: 5, dtype: int64
Montrose-O'Hare 2015 5 105    63828
Name: 5, dtype: int64
Montrose-O'Hare 2016 5 105    41599
Name: 5, dtype: int64
Montrose-O'Hare 2017 5 105    66728
Name: 5, dtype: int64
Montrose-O'Hare 2018 5 105    67880
Name: 5, dtype: int64
Montrose-O'Hare 2019 5 104    67040
Name: 5, dtype: int64
Montrose-O'Hare 2013 6 104    57675
Name: 6, dtype: int64
Montrose-O'Hare 2014 6 104    63710
Name: 6, dtype: int64
Montrose-O'Hare 2015 6 105    68437
Name: 6, dtype: int64
Montrose-O'Hare 2016 6 105    53347
Name: 6, dtype: int64
Montrose-O'Hare 2017 6 105    68144
Name: 6, dtype: int64
Montrose-O'Hare 2018 6 105    66036
Name: 6, dtype: int64
Montrose-O'Hare 2019 6 104    59261
Name: 6, dtype: int64
Montrose-O'Hare 2013 7 104    64806
Name: 7, dtype: int64
Montrose-O'Hare 2014 7 104    66120
Name: 7, dtype: int64
Montrose-O'Hare 2015 7 105    69260
Name: 7, dtype: int64
Montrose-O'Hare 2016 7 105    69315
Name: 7, dtype: int64
Montrose-O'Hare 2017 7 105    65312
Name: 7, dtype: int64
Montrose-O'Hare 2018 7 105    66121
Name: 7, dtype: int64
Montrose-O'Hare 2019 7 104    65601
Name: 7, dtype: int64
Montrose-O'Hare 2013 8 104    65945
Name: 8, dtype: int64
Montrose-O'Hare 2014 8 104    65246
Name: 8, dtype: int64
Montrose-O'Hare 2015 8 105    65327
Name: 8, dtype: int64
Montrose-O'Hare 2016 8 105    70716
Name: 8, dtype: int64
Montrose-O'Hare 2017 8 105    71154
Name: 8, dtype: int64
Montrose-O'Hare 2018 8 105    0
Name: 8, dtype: int64
Montrose-O'Hare 2019 8 104    67812
Name: 8, dtype: int64
Montrose-O'Hare 2013 9 104    65866
Name: 9, dtype: int64
Montrose-O'Hare 2014 9 104    69713
Name: 9, dtype: int64
Montrose-O'Hare 2015 9 105    71145
Name: 9, dtype: int64
Montrose-O'Hare 2016 9 105    70508
Name: 9, dtype: int64
Montrose-O'Hare 2017 9 105    70373
Name: 9, dtype: int64
Montrose-O'Hare 2018 9 105    0
Name: 9, dtype: int64
Montrose-O'Hare 2019 9 104    66864
Name: 9, dtype: int64
Montrose-O'Hare 2013 10 104    72841
Name: 10, dtype: int64
Montrose-O'Hare 2014 10 104    75122
Name: 10, dtype: int64
Montrose-O'Hare 2015 10 105    74016
Name: 10, dtype: int64
Montrose-O'Hare 2016 10 105    72572
Name: 10, dtype: int64
Montrose-O'Hare 2017 10 105    74485
Name: 10, dtype: int64
Montrose-O'Hare 2018 10 105    0
Name: 10, dtype: int64
Montrose-O'Hare 2019 10 104    71299
Name: 10, dtype: int64
Montrose-O'Hare 2013 11 104    62709
Name: 11, dtype: int64
Montrose-O'Hare 2014 11 104    60960
Name: 11, dtype: int64
Montrose-O'Hare 2015 11 105    63292
Name: 11, dtype: int64
Montrose-O'Hare 2016 11 105    68924
Name: 11, dtype: int64
Montrose-O'Hare 2017 11 105    67785
Name: 11, dtype: int64
Montrose-O'Hare 2018 11 105    0
Name: 11, dtype: int64
Montrose-O'Hare 2019 11 104    60788
Name: 11, dtype: int64
Montrose-O'Hare 2013 12 104    57485
Name: 12, dtype: int64
Montrose-O'Hare 2014 12 104    61135
Name: 12, dtype: int64
Montrose-O'Hare 2015 12 105    60971
Name: 12, dtype: int64
Montrose-O'Hare 2016 12 105    59307
Name: 12, dtype: int64
Montrose-O'Hare 2017 12 105    60414
Name: 12, dtype: int64
Montrose-O'Hare 2018 12 105    0
Name: 12, dtype: int64
Montrose-O'Hare 2019 12 104    57735
Name: 12, dtype: int64
Morgan-Lake 2013 1 105    43341
Name: 1, dtype: int64
Morgan-Lake 2014 1 105    51495
Name: 1, dtype: int64
Morgan-Lake 2015 1 106    54063
Name: 1, dtype: int64
Morgan-Lake 2016 1 106    65720
Name: 1, dtype: int64
Morgan-Lake 2017 1 106    66258
Name: 1, dtype: int64
Morgan-Lake 2018 1 106    71061
Name: 1, dtype: int64
Morgan-Lake 2019 1 105    77366
Name: 1, dtype: int64
Morgan-Lake 2013 2 105    42141
Name: 2, dtype: int64
Morgan-Lake 2014 2 105    51528
Name: 2, dtype: int64
Morgan-Lake 2015 2 106    54453
Name: 2, dtype: int64
Morgan-Lake 2016 2 106    63956
Name: 2, dtype: int64
Morgan-Lake 2017 2 106    64440
Name: 2, dtype: int64
Morgan-Lake 2018 2 106    69546
Name: 2, dtype: int64
Morgan-Lake 2019 2 105    77852
Name: 2, dtype: int64
Morgan-Lake 2013 3 105    44834
Name: 3, dtype: int64
Morgan-Lake 2014 3 105    58155
Name: 3, dtype: int64
Morgan-Lake 2015 3 106    62994
Name: 3, dtype: int64
Morgan-Lake 2016 3 106    71329
Name: 3, dtype: int64
Morgan-Lake 2017 3 106    73705
Name: 3, dtype: int64
Morgan-Lake 2018 3 106    85753
Name: 3, dtype: int64
Morgan-Lake 2019 3 105    89943
Name: 3, dtype: int64
Morgan-Lake 2013 4 105    47133
Name: 4, dtype: int64
Morgan-Lake 2014 4 105    57868
Name: 4, dtype: int64
Morgan-Lake 2015 4 106    62123
Name: 4, dtype: int64
Morgan-Lake 2016 4 106    69786
Name: 4, dtype: int64
Morgan-Lake 2017 4 106    70154
Name: 4, dtype: int64
Morgan-Lake 2018 4 106    78784
Name: 4, dtype: int64
Morgan-Lake 2019 4 105    91967
Name: 4, dtype: int64
Morgan-Lake 2013 5 105    49153
Name: 5, dtype: int64
Morgan-Lake 2014 5 105    56987
Name: 5, dtype: int64
Morgan-Lake 2015 5 106    65516
Name: 5, dtype: int64
Morgan-Lake 2016 5 106    73204
Name: 5, dtype: int64
Morgan-Lake 2017 5 106    78308
Name: 5, dtype: int64
Morgan-Lake 2018 5 106    88642
Name: 5, dtype: int64
Morgan-Lake 2019 5 105    100278
Name: 5, dtype: int64
Morgan-Lake 2013 6 105    54997
Name: 6, dtype: int64
Morgan-Lake 2014 6 105    61760
Name: 6, dtype: int64
Morgan-Lake 2015 6 106    74847
Name: 6, dtype: int64
Morgan-Lake 2016 6 106    83656
Name: 6, dtype: int64
Morgan-Lake 2017 6 106    85759
Name: 6, dtype: int64
Morgan-Lake 2018 6 106    97461
Name: 6, dtype: int64
Morgan-Lake 2019 6 105    100057
Name: 6, dtype: int64
Morgan-Lake 2013 7 105    56731
Name: 7, dtype: int64
Morgan-Lake 2014 7 105    62594
Name: 7, dtype: int64
Morgan-Lake 2015 7 106    76616
Name: 7, dtype: int64
Morgan-Lake 2016 7 106    77954
Name: 7, dtype: int64
Morgan-Lake 2017 7 106    81489
Name: 7, dtype: int64
Morgan-Lake 2018 7 106    95160
Name: 7, dtype: int64
Morgan-Lake 2019 7 105    97293
Name: 7, dtype: int64
Morgan-Lake 2013 8 105    55226
Name: 8, dtype: int64
Morgan-Lake 2014 8 105    63234
Name: 8, dtype: int64
Morgan-Lake 2015 8 106    72742
Name: 8, dtype: int64
Morgan-Lake 2016 8 106    78348
Name: 8, dtype: int64
Morgan-Lake 2017 8 106    84890
Name: 8, dtype: int64
Morgan-Lake 2018 8 106    0
Name: 8, dtype: int64
Morgan-Lake 2019 8 105    102137
Name: 8, dtype: int64
Morgan-Lake 2013 9 105    51952
Name: 9, dtype: int64
Morgan-Lake 2014 9 105    63146
Name: 9, dtype: int64
Morgan-Lake 2015 9 106    72271
Name: 9, dtype: int64
Morgan-Lake 2016 9 106    74454
Name: 9, dtype: int64
Morgan-Lake 2017 9 106    79799
Name: 9, dtype: int64
Morgan-Lake 2018 9 106    0
Name: 9, dtype: int64
Morgan-Lake 2019 9 105    91489
Name: 9, dtype: int64
Morgan-Lake 2013 10 105    57363
Name: 10, dtype: int64
Morgan-Lake 2014 10 105    68175
Name: 10, dtype: int64
Morgan-Lake 2015 10 106    76097
Name: 10, dtype: int64
Morgan-Lake 2016 10 106    76919
Name: 10, dtype: int64
Morgan-Lake 2017 10 106    82837
Name: 10, dtype: int64
Morgan-Lake 2018 10 106    0
Name: 10, dtype: int64
Morgan-Lake 2019 10 105    102392
Name: 10, dtype: int64
Morgan-Lake 2013 11 105    50240
Name: 11, dtype: int64
Morgan-Lake 2014 11 105    55606
Name: 11, dtype: int64
Morgan-Lake 2015 11 106    67812
Name: 11, dtype: int64
Morgan-Lake 2016 11 106    70491
Name: 11, dtype: int64
Morgan-Lake 2017 11 106    74277
Name: 11, dtype: int64
Morgan-Lake 2018 11 106    0
Name: 11, dtype: int64
Morgan-Lake 2019 11 105    91667
Name: 11, dtype: int64
Morgan-Lake 2013 12 105    48065
Name: 12, dtype: int64
Morgan-Lake 2014 12 105    54819
Name: 12, dtype: int64
Morgan-Lake 2015 12 106    66577
Name: 12, dtype: int64
Morgan-Lake 2016 12 106    63211
Name: 12, dtype: int64
Morgan-Lake 2017 12 106    66956
Name: 12, dtype: int64
Morgan-Lake 2018 12 106    0
Name: 12, dtype: int64
Morgan-Lake 2019 12 105    82649
Name: 12, dtype: int64
Morse 2013 1 106    123329
Name: 1, dtype: int64
Morse 2014 1 106    104404
Name: 1, dtype: int64
Morse 2015 1 107    129116
Name: 1, dtype: int64
Morse 2016 1 107    126984
Name: 1, dtype: int64
Morse 2017 1 107    122137
Name: 1, dtype: int64
Morse 2018 1 107    116644
Name: 1, dtype: int64
Morse 2019 1 106    106407
Name: 1, dtype: int64
Morse 2013 2 106    120124
Name: 2, dtype: int64
Morse 2014 2 106    132121
Name: 2, dtype: int64
Morse 2015 2 107    124130
Name: 2, dtype: int64
Morse 2016 2 107    128759
Name: 2, dtype: int64
Morse 2017 2 107    116938
Name: 2, dtype: int64
Morse 2018 2 107    112558
Name: 2, dtype: int64
Morse 2019 2 106    108343
Name: 2, dtype: int64
Morse 2013 3 106    131189
Name: 3, dtype: int64
Morse 2014 3 106    144314
Name: 3, dtype: int64
Morse 2015 3 107    139566
Name: 3, dtype: int64
Morse 2016 3 107    137448
Name: 3, dtype: int64
Morse 2017 3 107    131013
Name: 3, dtype: int64
Morse 2018 3 107    125190
Name: 3, dtype: int64
Morse 2019 3 106    117250
Name: 3, dtype: int64
Morse 2013 4 106    132894
Name: 4, dtype: int64
Morse 2014 4 106    141310
Name: 4, dtype: int64
Morse 2015 4 107    136211
Name: 4, dtype: int64
Morse 2016 4 107    133590
Name: 4, dtype: int64
Morse 2017 4 107    121934
Name: 4, dtype: int64
Morse 2018 4 107    118824
Name: 4, dtype: int64
Morse 2019 4 106    115807
Name: 4, dtype: int64
Morse 2013 5 106    133080
Name: 5, dtype: int64
Morse 2014 5 106    143050
Name: 5, dtype: int64
Morse 2015 5 107    136874
Name: 5, dtype: int64
Morse 2016 5 107    134824
Name: 5, dtype: int64
Morse 2017 5 107    127729
Name: 5, dtype: int64
Morse 2018 5 107    126071
Name: 5, dtype: int64
Morse 2019 5 106    119216
Name: 5, dtype: int64
Morse 2013 6 106    135462
Name: 6, dtype: int64
Morse 2014 6 106    143086
Name: 6, dtype: int64
Morse 2015 6 107    139550
Name: 6, dtype: int64
Morse 2016 6 107    138304
Name: 6, dtype: int64
Morse 2017 6 107    133660
Name: 6, dtype: int64
Morse 2018 6 107    127316
Name: 6, dtype: int64
Morse 2019 6 106    118266
Name: 6, dtype: int64
Morse 2013 7 106    138857
Name: 7, dtype: int64
Morse 2014 7 106    144928
Name: 7, dtype: int64
Morse 2015 7 107    142419
Name: 7, dtype: int64
Morse 2016 7 107    132864
Name: 7, dtype: int64
Morse 2017 7 107    129101
Name: 7, dtype: int64
Morse 2018 7 107    124194
Name: 7, dtype: int64
Morse 2019 7 106    118800
Name: 7, dtype: int64
Morse 2013 8 106    140534
Name: 8, dtype: int64
Morse 2014 8 106    143831
Name: 8, dtype: int64
Morse 2015 8 107    140252
Name: 8, dtype: int64
Morse 2016 8 107    135346
Name: 8, dtype: int64
Morse 2017 8 107    132821
Name: 8, dtype: int64
Morse 2018 8 107    0
Name: 8, dtype: int64
Morse 2019 8 106    119433
Name: 8, dtype: int64
Morse 2013 9 106    132888
Name: 9, dtype: int64
Morse 2014 9 106    144998
Name: 9, dtype: int64
Morse 2015 9 107    144193
Name: 9, dtype: int64
Morse 2016 9 107    137775
Name: 9, dtype: int64
Morse 2017 9 107    130384
Name: 9, dtype: int64
Morse 2018 9 107    0
Name: 9, dtype: int64
Morse 2019 9 106    119843
Name: 9, dtype: int64
Morse 2013 10 106    130178
Name: 10, dtype: int64
Morse 2014 10 106    151401
Name: 10, dtype: int64
Morse 2015 10 107    148116
Name: 10, dtype: int64
Morse 2016 10 107    139176
Name: 10, dtype: int64

Morse 2017 10 107    134183
Name: 10, dtype: int64
Morse 2018 10 107    0
Name: 10, dtype: int64
Morse 2019 10 106    127549
Name: 10, dtype: int64
Morse 2013 11 106    107882
Name: 11, dtype: int64
Morse 2014 11 106    132419
Name: 11, dtype: int64
Morse 2015 11 107    129336
Name: 11, dtype: int64
Morse 2016 11 107    131946
Name: 11, dtype: int64
Morse 2017 11 107    122361
Name: 11, dtype: int64
Morse 2018 11 107    0
Name: 11, dtype: int64
Morse 2019 11 106    113227
Name: 11, dtype: int64
Morse 2013 12 106    96925
Name: 12, dtype: int64
Morse 2014 12 106    129705
Name: 12, dtype: int64
Morse 2015 12 107    126475
Name: 12, dtype: int64
Morse 2016 12 107    119262
Name: 12, dtype: int64
Morse 2017 12 107    111086
Name: 12, dtype: int64
Morse 2018 12 107    0
Name: 12, dtype: int64
Morse 2019 12 106    103737
Name: 12, dtype: int64
North/Clybourn 2013 1 107    151153
Name: 1, dtype: int64
North/Clybourn 2014 1 107    155063
Name: 1, dtype: int64
North/Clybourn 2015 1 108    155928
Name: 1, dtype: int64
North/Clybourn 2016 1 108    173304
Name: 1, dtype: int64
North/Clybourn 2017 1 108    159160
Name: 1, dtype: int64
North/Clybourn 2018 1 108    150118
Name: 1, dtype: int64
North/Clybourn 2019 1 107    137861
Name: 1, dtype: int64
North/Clybourn 2013 2 107    133697
Name: 2, dtype: int64
North/Clybourn 2014 2 107    150934
Name: 2, dtype: int64
North/Clybourn 2015 2 108    141162
Name: 2, dtype: int64
North/Clybourn 2016 2 108    167662
Name: 2, dtype: int64
North/Clybourn 2017 2 108    150864
Name: 2, dtype: int64
North/Clybourn 2018 2 108    142386
Name: 2, dtype: int64
North/Clybourn 2019 2 107    134089
Name: 2, dtype: int64
North/Clybourn 2013 3 107    162090
Name: 3, dtype: int64
North/Clybourn 2014 3 107    169138
Name: 3, dtype: int64
North/Clybourn 2015 3 108    174147
Name: 3, dtype: int64
North/Clybourn 2016 3 108    181942
Name: 3, dtype: int64
North/Clybourn 2017 3 108    169866
Name: 3, dtype: int64
North/Clybourn 2018 3 108    159258
Name: 3, dtype: int64
North/Clybourn 2019 3 107    147270
Name: 3, dtype: int64
North/Clybourn 2013 4 107    161721
Name: 4, dtype: int64
North/Clybourn 2014 4 107    166227
Name: 4, dtype: int64
North/Clybourn 2015 4 108    176596
Name: 4, dtype: int64
North/Clybourn 2016 4 108    179473
Name: 4, dtype: int64
North/Clybourn 2017 4 108    156288
Name: 4, dtype: int64
North/Clybourn 2018 4 108    152868
Name: 4, dtype: int64
North/Clybourn 2019 4 107    144303
Name: 4, dtype: int64
North/Clybourn 2013 5 107    164930
Name: 5, dtype: int64
North/Clybourn 2014 5 107    173409
Name: 5, dtype: int64
North/Clybourn 2015 5 108    185136
Name: 5, dtype: int64
North/Clybourn 2016 5 108    185888
Name: 5, dtype: int64
North/Clybourn 2017 5 108    171623
Name: 5, dtype: int64
North/Clybourn 2018 5 108    164203
Name: 5, dtype: int64
North/Clybourn 2019 5 107    155315
Name: 5, dtype: int64
North/Clybourn 2013 6 107    160163
Name: 6, dtype: int64
North/Clybourn 2014 6 107    169192
Name: 6, dtype: int64
North/Clybourn 2015 6 108    182396
Name: 6, dtype: int64
North/Clybourn 2016 6 108    187410
Name: 6, dtype: int64
North/Clybourn 2017 6 108    173657
Name: 6, dtype: int64
North/Clybourn 2018 6 108    159983
Name: 6, dtype: int64
North/Clybourn 2019 6 107    144363
Name: 6, dtype: int64
North/Clybourn 2013 7 107    161733
Name: 7, dtype: int64
North/Clybourn 2014 7 107    172166
Name: 7, dtype: int64
North/Clybourn 2015 7 108    187821
Name: 7, dtype: int64
North/Clybourn 2016 7 108    178315
Name: 7, dtype: int64
North/Clybourn 2017 7 108    163093
Name: 7, dtype: int64
North/Clybourn 2018 7 108    157669
Name: 7, dtype: int64
North/Clybourn 2019 7 107    151804
Name: 7, dtype: int64
North/Clybourn 2013 8 107    165233
Name: 8, dtype: int64
North/Clybourn 2014 8 107    176461
Name: 8, dtype: int64
North/Clybourn 2015 8 108    187522
Name: 8, dtype: int64
North/Clybourn 2016 8 108    178442
Name: 8, dtype: int64
North/Clybourn 2017 8 108    172114
Name: 8, dtype: int64
North/Clybourn 2018 8 108    0
Name: 8, dtype: int64
North/Clybourn 2019 8 107    155440
Name: 8, dtype: int64
North/Clybourn 2013 9 107    163461
Name: 9, dtype: int64
North/Clybourn 2014 9 107    182424
Name: 9, dtype: int64
North/Clybourn 2015 9 108    194473
Name: 9, dtype: int64
North/Clybourn 2016 9 108    178307
Name: 9, dtype: int64
North/Clybourn 2017 9 108    165592
Name: 9, dtype: int64
North/Clybourn 2018 9 108    0
Name: 9, dtype: int64
North/Clybourn 2019 9 107    156133
Name: 9, dtype: int64
North/Clybourn 2013 10 107    178507
Name: 10, dtype: int64
North/Clybourn 2014 10 107    193100
Name: 10, dtype: int64
North/Clybourn 2015 10 108    205745
Name: 10, dtype: int64
North/Clybourn 2016 10 108    187663
Name: 10, dtype: int64
North/Clybourn 2017 10 108    170885
Name: 10, dtype: int64
North/Clybourn 2018 10 108    0
Name: 10, dtype: int64
North/Clybourn 2019 10 107    167526
Name: 10, dtype: int64
North/Clybourn 2013 11 107    162105
Name: 11, dtype: int64
North/Clybourn 2014 11 107    174926
Name: 11, dtype: int64
North/Clybourn 2015 11 108    181521
Name: 11, dtype: int64
North/Clybourn 2016 11 108    171473
Name: 11, dtype: int64
North/Clybourn 2017 11 108    150752
Name: 11, dtype: int64
North/Clybourn 2018 11 108    0
Name: 11, dtype: int64
North/Clybourn 2019 11 107    147426
Name: 11, dtype: int64
North/Clybourn 2013 12 107    154934
Name: 12, dtype: int64
North/Clybourn 2014 12 107    167436
Name: 12, dtype: int64
North/Clybourn 2015 12 108    173904
Name: 12, dtype: int64
North/Clybourn 2016 12 108    158393
Name: 12, dtype: int64
North/Clybourn 2017 12 108    146508
Name: 12, dtype: int64
North/Clybourn 2018 12 108    0
Name: 12, dtype: int64
North/Clybourn 2019 12 107    139086
Name: 12, dtype: int64
Noyes 2013 1 108    19604
Name: 1, dtype: int64
Noyes 2014 1 108    20640
Name: 1, dtype: int64
Noyes 2015 1 109    21063
Name: 1, dtype: int64
Noyes 2016 1 109    21994
Name: 1, dtype: int64
Noyes 2017 1 109    23392
Name: 1, dtype: int64
Noyes 2018 1 109    23984
Name: 1, dtype: int64
Noyes 2019 1 108    21513
Name: 1, dtype: int64
Noyes 2013 2 108    19849
Name: 2, dtype: int64
Noyes 2014 2 108    20895
Name: 2, dtype: int64
Noyes 2015 2 109    20709
Name: 2, dtype: int64
Noyes 2016 2 109    22739
Name: 2, dtype: int64
Noyes 2017 2 109    22337
Name: 2, dtype: int64
Noyes 2018 2 109    23581
Name: 2, dtype: int64
Noyes 2019 2 108    22370
Name: 2, dtype: int64
Noyes 2013 3 108    18823
Name: 3, dtype: int64
Noyes 2014 3 108    21202
Name: 3, dtype: int64
Noyes 2015 3 109    21107
Name: 3, dtype: int64
Noyes 2016 3 109    22480
Name: 3, dtype: int64
Noyes 2017 3 109    23186
Name: 3, dtype: int64
Noyes 2018 3 109    24131
Name: 3, dtype: int64
Noyes 2019 3 108    22089
Name: 3, dtype: int64
Noyes 2013 4 108    21242
Name: 4, dtype: int64
Noyes 2014 4 108    23139
Name: 4, dtype: int64
Noyes 2015 4 109    22332
Name: 4, dtype: int64
Noyes 2016 4 109    23769
Name: 4, dtype: int64
Noyes 2017 4 109    23303
Name: 4, dtype: int64
Noyes 2018 4 109    24754
Name: 4, dtype: int64
Noyes 2019 4 108    24033
Name: 4, dtype: int64
Noyes 2013 5 108    22036
Name: 5, dtype: int64
Noyes 2014 5 108    22439
Name: 5, dtype: int64
Noyes 2015 5 109    22268
Name: 5, dtype: int64
Noyes 2016 5 109    24226
Name: 5, dtype: int64
Noyes 2017 5 109    25292
Name: 5, dtype: int64
Noyes 2018 5 109    25262
Name: 5, dtype: int64
Noyes 2019 5 108    25387
Name: 5, dtype: int64
Noyes 2013 6 108    20586
Name: 6, dtype: int64
Noyes 2014 6 108    22014
Name: 6, dtype: int64
Noyes 2015 6 109    21774
Name: 6, dtype: int64
Noyes 2016 6 109    23046
Name: 6, dtype: int64
Noyes 2017 6 109    24552
Name: 6, dtype: int64
Noyes 2018 6 109    23986
Name: 6, dtype: int64
Noyes 2019 6 108    23766
Name: 6, dtype: int64
Noyes 2013 7 108    22715
Name: 7, dtype: int64
Noyes 2014 7 108    22987
Name: 7, dtype: int64
Noyes 2015 7 109    21898
Name: 7, dtype: int64
Noyes 2016 7 109    23981
Name: 7, dtype: int64
Noyes 2017 7 109    25146
Name: 7, dtype: int64
Noyes 2018 7 109    23458
Name: 7, dtype: int64
Noyes 2019 7 108    25041
Name: 7, dtype: int64
Noyes 2013 8 108    20049
Name: 8, dtype: int64
Noyes 2014 8 108    19400
Name: 8, dtype: int64
Noyes 2015 8 109    18847
Name: 8, dtype: int64
Noyes 2016 8 109    21461
Name: 8, dtype: int64
Noyes 2017 8 109    20263
Name: 8, dtype: int64
Noyes 2018 8 109    0
Name: 8, dtype: int64
Noyes 2019 8 108    22038
Name: 8, dtype: int64
Noyes 2013 9 108    18610
Name: 9, dtype: int64
Noyes 2014 9 108    20622
Name: 9, dtype: int64
Noyes 2015 9 109    20996
Name: 9, dtype: int64
Noyes 2016 9 109    23525
Name: 9, dtype: int64
Noyes 2017 9 109    23337
Name: 9, dtype: int64
Noyes 2018 9 109    0
Name: 9, dtype: int64
Noyes 2019 9 108    21059
Name: 9, dtype: int64
Noyes 2013 10 108    24967
Name: 10, dtype: int64
Noyes 2014 10 108    25367
Name: 10, dtype: int64
Noyes 2015 10 109    26275
Name: 10, dtype: int64
Noyes 2016 10 109    27706
Name: 10, dtype: int64
Noyes 2017 10 109    29098
Name: 10, dtype: int64
Noyes 2018 10 109    0
Name: 10, dtype: int64
Noyes 2019 10 108    28338
Name: 10, dtype: int64
Noyes 2013 11 108    21526
Name: 11, dtype: int64
Noyes 2014 11 108    20833
Name: 11, dtype: int64
Noyes 2015 11 109    22809
Name: 11, dtype: int64
Noyes 2016 11 109    25512
Name: 11, dtype: int64
Noyes 2017 11 109    25167
Name: 11, dtype: int64
Noyes 2018 11 109    0
Name: 11, dtype: int64
Noyes 2019 11 108    23718
Name: 11, dtype: int64
Noyes 2013 12 108    15796
Name: 12, dtype: int64
Noyes 2014 12 108    16580
Name: 12, dtype: int64
Noyes 2015 12 109    17257
Name: 12, dtype: int64
Noyes 2016 12 109    17003
Name: 12, dtype: int64
Noyes 2017 12 109    17388
Name: 12, dtype: int64
Noyes 2018 12 109    0
Name: 12, dtype: int64
Noyes 2019 12 108    16685
Name: 12, dtype: int64
O'Hare Airport 2013 1 109    248326
Name: 1, dtype: int64
O'Hare Airport 2014 1 109    248462
Name: 1, dtype: int64
O'Hare Airport 2015 1 110    259969
Name: 1, dtype: int64
O'Hare Airport 2016 1 110    277901
Name: 1, dtype: int64
O'Hare Airport 2017 1 110    278965
Name: 1, dtype: int64
O'Hare Airport 2018 1 110    252115
Name: 1, dtype: int64
O'Hare Airport 2019 1 109    269656
Name: 1, dtype: int64
O'Hare Airport 2013 2 109    221179
Name: 2, dtype: int64
O'Hare Airport 2014 2 109    229228
Name: 2, dtype: int64
O'Hare Airport 2015 2 110    238142
Name: 2, dtype: int64
O'Hare Airport 2016 2 110    259924
Name: 2, dtype: int64
O'Hare Airport 2017 2 110    249596
Name: 2, dtype: int64
O'Hare Airport 2018 2 110    254362
Name: 2, dtype: int64
O'Hare Airport 2019 2 109    252631
Name: 2, dtype: int64
O'Hare Airport 2013 3 109    273789
Name: 3, dtype: int64
O'Hare Airport 2014 3 109    219763
Name: 3, dtype: int64
O'Hare Airport 2015 3 110    300834
Name: 3, dtype: int64
O'Hare Airport 2016 3 110    313081
Name: 3, dtype: int64
O'Hare Airport 2017 3 110    306591
Name: 3, dtype: int64
O'Hare Airport 2018 3 110    311397
Name: 3, dtype: int64
O'Hare Airport 2019 3 109    304827
Name: 3, dtype: int64
O'Hare Airport 2013 4 109    276102
Name: 4, dtype: int64
O'Hare Airport 2014 4 109    275372
Name: 4, dtype: int64
O'Hare Airport 2015 4 110    314500
Name: 4, dtype: int64
O'Hare Airport 2016 4 110    318382
Name: 4, dtype: int64
O'Hare Airport 2017 4 110    308260
Name: 4, dtype: int64
O'Hare Airport 2018 4 110    314187
Name: 4, dtype: int64
O'Hare Airport 2019 4 109    322534
Name: 4, dtype: int64
O'Hare Airport 2013 5 109    319036
Name: 5, dtype: int64
O'Hare Airport 2014 5 109    325223
Name: 5, dtype: int64
O'Hare Airport 2015 5 110    359968
Name: 5, dtype: int64
O'Hare Airport 2016 5 110    365908
Name: 5, dtype: int64
O'Hare Airport 2017 5 110    350344
Name: 5, dtype: int64
O'Hare Airport 2018 5 110    361608
Name: 5, dtype: int64
O'Hare Airport 2019 5 109    369485
Name: 5, dtype: int64
O'Hare Airport 2013 6 109    313840
Name: 6, dtype: int64
O'Hare Airport 2014 6 109    312493
Name: 6, dtype: int64
O'Hare Airport 2015 6 110    357099
Name: 6, dtype: int64
O'Hare Airport 2016 6 110    364934
Name: 6, dtype: int64
O'Hare Airport 2017 6 110    359663
Name: 6, dtype: int64
O'Hare Airport 2018 6 110    359529
Name: 6, dtype: int64
O'Hare Airport 2019 6 109    314970
Name: 6, dtype: int64
O'Hare Airport 2013 7 109    319185
Name: 7, dtype: int64
O'Hare Airport 2014 7 109    337021
Name: 7, dtype: int64
O'Hare Airport 2015 7 110    394245
Name: 7, dtype: int64
O'Hare Airport 2016 7 110    375624
Name: 7, dtype: int64
O'Hare Airport 2017 7 110    364100
Name: 7, dtype: int64
O'Hare Airport 2018 7 110    377178
Name: 7, dtype: int64
O'Hare Airport 2019 7 109    371500
Name: 7, dtype: int64
O'Hare Airport 2013 8 109    332940
Name: 8, dtype: int64
O'Hare Airport 2014 8 109    336105
Name: 8, dtype: int64
O'Hare Airport 2015 8 110    386795
Name: 8, dtype: int64
O'Hare Airport 2016 8 110    368114
Name: 8, dtype: int64
O'Hare Airport 2017 8 110    372330
Name: 8, dtype: int64
O'Hare Airport 2018 8 110    0
Name: 8, dtype: int64
O'Hare Airport 2019 8 109    373091
Name: 8, dtype: int64
O'Hare Airport 2013 9 109    301440
Name: 9, dtype: int64
O'Hare Airport 2014 9 109    314861
Name: 9, dtype: int64
O'Hare Airport 2015 9 110    381154
Name: 9, dtype: int64
O'Hare Airport 2016 9 110    355144
Name: 9, dtype: int64
O'Hare Airport 2017 9 110    353032
Name: 9, dtype: int64
O'Hare Airport 2018 9 110    0
Name: 9, dtype: int64
O'Hare Airport 2019 9 109    313233
Name: 9, dtype: int64
O'Hare Airport 2013 10 109    315997
Name: 10, dtype: int64
O'Hare Airport 2014 10 109    333763
Name: 10, dtype: int64
O'Hare Airport 2015 10 110    398159
Name: 10, dtype: int64
O'Hare Airport 2016 10 110    373614
Name: 10, dtype: int64
O'Hare Airport 2017 10 110    364858
Name: 10, dtype: int64
O'Hare Airport 2018 10 110    0
Name: 10, dtype: int64
O'Hare Airport 2019 10 109    298318
Name: 10, dtype: int64
O'Hare Airport 2013 11 109    281980
Name: 11, dtype: int64
O'Hare Airport 2014 11 109    294413
Name: 11, dtype: int64
O'Hare Airport 2015 11 110    346148
Name: 11, dtype: int64
O'Hare Airport 2016 11 110    332466
Name: 11, dtype: int64
O'Hare Airport 2017 11 110    328319
Name: 11, dtype: int64
O'Hare Airport 2018 11 110    0
Name: 11, dtype: int64
O'Hare Airport 2019 11 109    308633
Name: 11, dtype: int64
O'Hare Airport 2013 12 109    279312
Name: 12, dtype: int64
O'Hare Airport 2014 12 109    289792
Name: 12, dtype: int64
O'Hare Airport 2015 12 110    316691
Name: 12, dtype: int64
O'Hare Airport 2016 12 110    292943
Name: 12, dtype: int64
O'Hare Airport 2017 12 110    298363
Name: 12, dtype: int64
O'Hare Airport 2018 12 110    0
Name: 12, dtype: int64
O'Hare Airport 2019 12 109    312289
Name: 12, dtype: int64
Oak Park-Forest Park 2013 1 110    41817
Name: 1, dtype: int64
Oak Park-Forest Park 2014 1 110    39679
Name: 1, dtype: int64
Oak Park-Forest Park 2015 1 111    41562
Name: 1, dtype: int64
Oak Park-Forest Park 2016 1 111    40804
Name: 1, dtype: int64
Oak Park-Forest Park 2017 1 111    43403
Name: 1, dtype: int64
Oak Park-Forest Park 2018 1 111    41148
Name: 1, dtype: int64
Oak Park-Forest Park 2019 1 110    37706

Name: 1, dtype: int64
Oak Park-Forest Park 2013 2 110    39870
Name: 2, dtype: int64
Oak Park-Forest Park 2014 2 110    40532
Name: 2, dtype: int64
Oak Park-Forest Park 2015 2 111    39439
Name: 2, dtype: int64
Oak Park-Forest Park 2016 2 111    42463
Name: 2, dtype: int64
Oak Park-Forest Park 2017 2 111    40948
Name: 2, dtype: int64
Oak Park-Forest Park 2018 2 111    38361
Name: 2, dtype: int64
Oak Park-Forest Park 2019 2 110    39604
Name: 2, dtype: int64
Oak Park-Forest Park 2013 3 110    43372
Name: 3, dtype: int64
Oak Park-Forest Park 2014 3 110    44804
Name: 3, dtype: int64
Oak Park-Forest Park 2015 3 111    46937
Name: 3, dtype: int64
Oak Park-Forest Park 2016 3 111    46453
Name: 3, dtype: int64
Oak Park-Forest Park 2017 3 111    45528
Name: 3, dtype: int64
Oak Park-Forest Park 2018 3 111    43483
Name: 3, dtype: int64
Oak Park-Forest Park 2019 3 110    41746
Name: 3, dtype: int64
Oak Park-Forest Park 2013 4 110    45934
Name: 4, dtype: int64
Oak Park-Forest Park 2014 4 110    48527
Name: 4, dtype: int64
Oak Park-Forest Park 2015 4 111    46532
Name: 4, dtype: int64
Oak Park-Forest Park 2016 4 111    46818
Name: 4, dtype: int64
Oak Park-Forest Park 2017 4 111    43809
Name: 4, dtype: int64
Oak Park-Forest Park 2018 4 111    43531
Name: 4, dtype: int64
Oak Park-Forest Park 2019 4 110    44503
Name: 4, dtype: int64
Oak Park-Forest Park 2013 5 110    46131
Name: 5, dtype: int64
Oak Park-Forest Park 2014 5 110    47679
Name: 5, dtype: int64
Oak Park-Forest Park 2015 5 111    44595
Name: 5, dtype: int64
Oak Park-Forest Park 2016 5 111    46791
Name: 5, dtype: int64
Oak Park-Forest Park 2017 5 111    46093
Name: 5, dtype: int64
Oak Park-Forest Park 2018 5 111    45950
Name: 5, dtype: int64
Oak Park-Forest Park 2019 5 110    44099
Name: 5, dtype: int64
Oak Park-Forest Park 2013 6 110    45816
Name: 6, dtype: int64
Oak Park-Forest Park 2014 6 110    47354
Name: 6, dtype: int64
Oak Park-Forest Park 2015 6 111    49559
Name: 6, dtype: int64
Oak Park-Forest Park 2016 6 111    49042
Name: 6, dtype: int64
Oak Park-Forest Park 2017 6 111    47735
Name: 6, dtype: int64
Oak Park-Forest Park 2018 6 111    44828
Name: 6, dtype: int64
Oak Park-Forest Park 2019 6 110    42133
Name: 6, dtype: int64
Oak Park-Forest Park 2013 7 110    47980
Name: 7, dtype: int64
Oak Park-Forest Park 2014 7 110    49574
Name: 7, dtype: int64
Oak Park-Forest Park 2015 7 111    50399
Name: 7, dtype: int64
Oak Park-Forest Park 2016 7 111    46841
Name: 7, dtype: int64
Oak Park-Forest Park 2017 7 111    43816
Name: 7, dtype: int64
Oak Park-Forest Park 2018 7 111    45173
Name: 7, dtype: int64
Oak Park-Forest Park 2019 7 110    43868
Name: 7, dtype: int64
Oak Park-Forest Park 2013 8 110    49071
Name: 8, dtype: int64
Oak Park-Forest Park 2014 8 110    49148
Name: 8, dtype: int64
Oak Park-Forest Park 2015 8 111    48424
Name: 8, dtype: int64
Oak Park-Forest Park 2016 8 111    49210
Name: 8, dtype: int64
Oak Park-Forest Park 2017 8 111    48995
Name: 8, dtype: int64
Oak Park-Forest Park 2018 8 111    0
Name: 8, dtype: int64
Oak Park-Forest Park 2019 8 110    44385
Name: 8, dtype: int64
Oak Park-Forest Park 2013 9 110    47435
Name: 9, dtype: int64
Oak Park-Forest Park 2014 9 110    49503
Name: 9, dtype: int64
Oak Park-Forest Park 2015 9 111    49650
Name: 9, dtype: int64
Oak Park-Forest Park 2016 9 111    48723
Name: 9, dtype: int64
Oak Park-Forest Park 2017 9 111    46164
Name: 9, dtype: int64
Oak Park-Forest Park 2018 9 111    0
Name: 9, dtype: int64
Oak Park-Forest Park 2019 9 110    43802
Name: 9, dtype: int64
Oak Park-Forest Park 2013 10 110    52165
Name: 10, dtype: int64
Oak Park-Forest Park 2014 10 110    53302
Name: 10, dtype: int64
Oak Park-Forest Park 2015 10 111    50355
Name: 10, dtype: int64
Oak Park-Forest Park 2016 10 111    49632
Name: 10, dtype: int64
Oak Park-Forest Park 2017 10 111    48483
Name: 10, dtype: int64
Oak Park-Forest Park 2018 10 111    0
Name: 10, dtype: int64
Oak Park-Forest Park 2019 10 110    47799
Name: 10, dtype: int64
Oak Park-Forest Park 2013 11 110    44422
Name: 11, dtype: int64
Oak Park-Forest Park 2014 11 110    42887
Name: 11, dtype: int64
Oak Park-Forest Park 2015 11 111    43602
Name: 11, dtype: int64
Oak Park-Forest Park 2016 11 111    47200
Name: 11, dtype: int64
Oak Park-Forest Park 2017 11 111    43551
Name: 11, dtype: int64
Oak Park-Forest Park 2018 11 111    0
Name: 11, dtype: int64
Oak Park-Forest Park 2019 11 110    38836
Name: 11, dtype: int64
Oak Park-Forest Park 2013 12 110    41562
Name: 12, dtype: int64
Oak Park-Forest Park 2014 12 110    43364
Name: 12, dtype: int64
Oak Park-Forest Park 2015 12 111    42470
Name: 12, dtype: int64
Oak Park-Forest Park 2016 12 111    39447
Name: 12, dtype: int64
Oak Park-Forest Park 2017 12 111    38429
Name: 12, dtype: int64
Oak Park-Forest Park 2018 12 111    0
Name: 12, dtype: int64
Oak Park-Forest Park 2019 12 110    35957
Name: 12, dtype: int64
Oak Park-Lake 2013 1 111    35847
Name: 1, dtype: int64
Oak Park-Lake 2014 1 111    35094
Name: 1, dtype: int64
Oak Park-Lake 2015 1 112    36312
Name: 1, dtype: int64
Oak Park-Lake 2016 1 112    35547
Name: 1, dtype: int64
Oak Park-Lake 2017 1 112    36484
Name: 1, dtype: int64
Oak Park-Lake 2018 1 112    36403
Name: 1, dtype: int64
Oak Park-Lake 2019 1 111    32972
Name: 1, dtype: int64
Oak Park-Lake 2013 2 111    34187
Name: 2, dtype: int64
Oak Park-Lake 2014 2 111    35845
Name: 2, dtype: int64
Oak Park-Lake 2015 2 112    34593
Name: 2, dtype: int64
Oak Park-Lake 2016 2 112    36498
Name: 2, dtype: int64
Oak Park-Lake 2017 2 112    35107
Name: 2, dtype: int64
Oak Park-Lake 2018 2 112    33568
Name: 2, dtype: int64
Oak Park-Lake 2019 2 111    32938
Name: 2, dtype: int64
Oak Park-Lake 2013 3 111    38244
Name: 3, dtype: int64
Oak Park-Lake 2014 3 111    41727
Name: 3, dtype: int64
Oak Park-Lake 2015 3 112    41566
Name: 3, dtype: int64
Oak Park-Lake 2016 3 112    40820
Name: 3, dtype: int64
Oak Park-Lake 2017 3 112    40243
Name: 3, dtype: int64
Oak Park-Lake 2018 3 112    39856
Name: 3, dtype: int64
Oak Park-Lake 2019 3 111    37324
Name: 3, dtype: int64
Oak Park-Lake 2013 4 111    40314
Name: 4, dtype: int64
Oak Park-Lake 2014 4 111    43304
Name: 4, dtype: int64
Oak Park-Lake 2015 4 112    42200
Name: 4, dtype: int64
Oak Park-Lake 2016 4 112    33962
Name: 4, dtype: int64
Oak Park-Lake 2017 4 112    38842
Name: 4, dtype: int64
Oak Park-Lake 2018 4 112    38480
Name: 4, dtype: int64
Oak Park-Lake 2019 4 111    39220
Name: 4, dtype: int64
Oak Park-Lake 2013 5 111    42500
Name: 5, dtype: int64
Oak Park-Lake 2014 5 111    44944
Name: 5, dtype: int64
Oak Park-Lake 2015 5 112    43041
Name: 5, dtype: int64
Oak Park-Lake 2016 5 112    35920
Name: 5, dtype: int64
Oak Park-Lake 2017 5 112    41224
Name: 5, dtype: int64
Oak Park-Lake 2018 5 112    41613
Name: 5, dtype: int64
Oak Park-Lake 2019 5 111    42629
Name: 5, dtype: int64
Oak Park-Lake 2013 6 111    43028
Name: 6, dtype: int64
Oak Park-Lake 2014 6 111    46203
Name: 6, dtype: int64
Oak Park-Lake 2015 6 112    45979
Name: 6, dtype: int64
Oak Park-Lake 2016 6 112    44527
Name: 6, dtype: int64
Oak Park-Lake 2017 6 112    44448
Name: 6, dtype: int64
Oak Park-Lake 2018 6 112    41863
Name: 6, dtype: int64
Oak Park-Lake 2019 6 111    41136
Name: 6, dtype: int64
Oak Park-Lake 2013 7 111    45259
Name: 7, dtype: int64
Oak Park-Lake 2014 7 111    48048
Name: 7, dtype: int64
Oak Park-Lake 2015 7 112    48580
Name: 7, dtype: int64
Oak Park-Lake 2016 7 112    43371
Name: 7, dtype: int64
Oak Park-Lake 2017 7 112    42060
Name: 7, dtype: int64
Oak Park-Lake 2018 7 112    41896
Name: 7, dtype: int64
Oak Park-Lake 2019 7 111    41767
Name: 7, dtype: int64
Oak Park-Lake 2013 8 111    45568
Name: 8, dtype: int64
Oak Park-Lake 2014 8 111    46702
Name: 8, dtype: int64
Oak Park-Lake 2015 8 112    45640
Name: 8, dtype: int64
Oak Park-Lake 2016 8 112    43474
Name: 8, dtype: int64
Oak Park-Lake 2017 8 112    45183
Name: 8, dtype: int64
Oak Park-Lake 2018 8 112    0
Name: 8, dtype: int64
Oak Park-Lake 2019 8 111    43525
Name: 8, dtype: int64
Oak Park-Lake 2013 9 111    43138
Name: 9, dtype: int64
Oak Park-Lake 2014 9 111    45444
Name: 9, dtype: int64
Oak Park-Lake 2015 9 112    43876
Name: 9, dtype: int64
Oak Park-Lake 2016 9 112    41504
Name: 9, dtype: int64
Oak Park-Lake 2017 9 112    40606
Name: 9, dtype: int64
Oak Park-Lake 2018 9 112    0
Name: 9, dtype: int64
Oak Park-Lake 2019 9 111    39626
Name: 9, dtype: int64
Oak Park-Lake 2013 10 111    45767
Name: 10, dtype: int64
Oak Park-Lake 2014 10 111    47308
Name: 10, dtype: int64
Oak Park-Lake 2015 10 112    45663
Name: 10, dtype: int64
Oak Park-Lake 2016 10 112    42329
Name: 10, dtype: int64
Oak Park-Lake 2017 10 112    42713
Name: 10, dtype: int64
Oak Park-Lake 2018 10 112    0
Name: 10, dtype: int64
Oak Park-Lake 2019 10 111    43389
Name: 10, dtype: int64
Oak Park-Lake 2013 11 111    38245
Name: 11, dtype: int64
Oak Park-Lake 2014 11 111    38012
Name: 11, dtype: int64
Oak Park-Lake 2015 11 112    38972
Name: 11, dtype: int64
Oak Park-Lake 2016 11 112    39333
Name: 11, dtype: int64
Oak Park-Lake 2017 11 112    38040
Name: 11, dtype: int64

Oak Park-Lake 2018 11 112    0
Name: 11, dtype: int64
Oak Park-Lake 2019 11 111    35185
Name: 11, dtype: int64
Oak Park-Lake 2013 12 111    36254
Name: 12, dtype: int64
Oak Park-Lake 2014 12 111    38094
Name: 12, dtype: int64
Oak Park-Lake 2015 12 112    38430
Name: 12, dtype: int64
Oak Park-Lake 2016 12 112    34858
Name: 12, dtype: int64
Oak Park-Lake 2017 12 112    34255
Name: 12, dtype: int64
Oak Park-Lake 2018 12 112    0
Name: 12, dtype: int64
Oak Park-Lake 2019 12 111    33668
Name: 12, dtype: int64
Oakton-Skokie 2013 1 112    20284
Name: 1, dtype: int64
Oakton-Skokie 2014 1 112    20267
Name: 1, dtype: int64
Oakton-Skokie 2015 1 113    22837
Name: 1, dtype: int64
Oakton-Skokie 2016 1 113    18163
Name: 1, dtype: int64
Oakton-Skokie 2017 1 113    21881
Name: 1, dtype: int64
Oakton-Skokie 2018 1 113    22012
Name: 1, dtype: int64
Oakton-Skokie 2019 1 112    19954
Name: 1, dtype: int64
Oakton-Skokie 2013 2 112    19795
Name: 2, dtype: int64
Oakton-Skokie 2014 2 112    20711
Name: 2, dtype: int64
Oakton-Skokie 2015 2 113    21967
Name: 2, dtype: int64
Oakton-Skokie 2016 2 113    19798
Name: 2, dtype: int64
Oakton-Skokie 2017 2 113    22168
Name: 2, dtype: int64
Oakton-Skokie 2018 2 113    21907
Name: 2, dtype: int64
Oakton-Skokie 2019 2 112    20249
Name: 2, dtype: int64
Oakton-Skokie 2013 3 112    20446
Name: 3, dtype: int64
Oakton-Skokie 2014 3 112    23596
Name: 3, dtype: int64
Oakton-Skokie 2015 3 113    25281
Name: 3, dtype: int64
Oakton-Skokie 2016 3 113    22130
Name: 3, dtype: int64
Oakton-Skokie 2017 3 113    25055
Name: 3, dtype: int64
Oakton-Skokie 2018 3 113    24419
Name: 3, dtype: int64
Oakton-Skokie 2019 3 112    21888
Name: 3, dtype: int64
Oakton-Skokie 2013 4 112    22969
Name: 4, dtype: int64
Oakton-Skokie 2014 4 112    25441
Name: 4, dtype: int64
Oakton-Skokie 2015 4 113    25906
Name: 4, dtype: int64
Oakton-Skokie 2016 4 113    21476
Name: 4, dtype: int64
Oakton-Skokie 2017 4 113    23587
Name: 4, dtype: int64
Oakton-Skokie 2018 4 113    23789
Name: 4, dtype: int64
Oakton-Skokie 2019 4 112    23399
Name: 4, dtype: int64
Oakton-Skokie 2013 5 112    23628
Name: 5, dtype: int64
Oakton-Skokie 2014 5 112    24854
Name: 5, dtype: int64
Oakton-Skokie 2015 5 113    14481
Name: 5, dtype: int64
Oakton-Skokie 2016 5 113    21773
Name: 5, dtype: int64
Oakton-Skokie 2017 5 113    25107
Name: 5, dtype: int64
Oakton-Skokie 2018 5 113    24048
Name: 5, dtype: int64
Oakton-Skokie 2019 5 112    23559
Name: 5, dtype: int64
Oakton-Skokie 2013 6 112    24049
Name: 6, dtype: int64
Oakton-Skokie 2014 6 112    25237
Name: 6, dtype: int64
Oakton-Skokie 2015 6 113    1038
Name: 6, dtype: int64
Oakton-Skokie 2016 6 113    23982
Name: 6, dtype: int64
Oakton-Skokie 2017 6 113    26420
Name: 6, dtype: int64
Oakton-Skokie 2018 6 113    23386
Name: 6, dtype: int64
Oakton-Skokie 2019 6 112    23424
Name: 6, dtype: int64
Oakton-Skokie 2013 7 112    26472
Name: 7, dtype: int64
Oakton-Skokie 2014 7 112    28200
Name: 7, dtype: int64
Oakton-Skokie 2015 7 113    0
Name: 7, dtype: int64
Oakton-Skokie 2016 7 113    24344
Name: 7, dtype: int64
Oakton-Skokie 2017 7 113    25453
Name: 7, dtype: int64
Oakton-Skokie 2018 7 113    24901
Name: 7, dtype: int64
Oakton-Skokie 2019 7 112    24097
Name: 7, dtype: int64
Oakton-Skokie 2013 8 112    26573
Name: 8, dtype: int64
Oakton-Skokie 2014 8 112    27433
Name: 8, dtype: int64
Oakton-Skokie 2015 8 113    0
Name: 8, dtype: int64
Oakton-Skokie 2016 8 113    25297
Name: 8, dtype: int64
Oakton-Skokie 2017 8 113    26931
Name: 8, dtype: int64
Oakton-Skokie 2018 8 113    0
Name: 8, dtype: int64
Oakton-Skokie 2019 8 112    24904
Name: 8, dtype: int64
Oakton-Skokie 2013 9 112    26341
Name: 9, dtype: int64
Oakton-Skokie 2014 9 112    28640
Name: 9, dtype: int64
Oakton-Skokie 2015 9 113    0
Name: 9, dtype: int64
Oakton-Skokie 2016 9 113    26493
Name: 9, dtype: int64
Oakton-Skokie 2017 9 113    26589
Name: 9, dtype: int64
Oakton-Skokie 2018 9 113    0
Name: 9, dtype: int64
Oakton-Skokie 2019 9 112    25128
Name: 9, dtype: int64
Oakton-Skokie 2013 10 112    28755
Name: 10, dtype: int64
Oakton-Skokie 2014 10 112    29734
Name: 10, dtype: int64
Oakton-Skokie 2015 10 113    992
Name: 10, dtype: int64
Oakton-Skokie 2016 10 113    27090
Name: 10, dtype: int64
Oakton-Skokie 2017 10 113    27306
Name: 10, dtype: int64
Oakton-Skokie 2018 10 113    0
Name: 10, dtype: int64
Oakton-Skokie 2019 10 112    27224
Name: 10, dtype: int64
Oakton-Skokie 2013 11 112    23217
Name: 11, dtype: int64
Oakton-Skokie 2014 11 112    23956
Name: 11, dtype: int64
Oakton-Skokie 2015 11 113    18778
Name: 11, dtype: int64
Oakton-Skokie 2016 11 113    25616
Name: 11, dtype: int64
Oakton-Skokie 2017 11 113    24067
Name: 11, dtype: int64
Oakton-Skokie 2018 11 113    0
Name: 11, dtype: int64
Oakton-Skokie 2019 11 112    22099
Name: 11, dtype: int64
Oakton-Skokie 2013 12 112    20793
Name: 12, dtype: int64
Oakton-Skokie 2014 12 112    23056
Name: 12, dtype: int64
Oakton-Skokie 2015 12 113    18603
Name: 12, dtype: int64
Oakton-Skokie 2016 12 113    20338
Name: 12, dtype: int64
Oakton-Skokie 2017 12 113    20524
Name: 12, dtype: int64
Oakton-Skokie 2018 12 113    0
Name: 12, dtype: int64
Oakton-Skokie 2019 12 112    19035
Name: 12, dtype: int64
Paulina 2013 1 113    70475
Name: 1, dtype: int64
Paulina 2014 1 113    69175
Name: 1, dtype: int64
Paulina 2015 1 114    67569
Name: 1, dtype: int64
Paulina 2016 1 114    68279
Name: 1, dtype: int64
Paulina 2017 1 114    67795
Name: 1, dtype: int64
Paulina 2018 1 114    68316
Name: 1, dtype: int64
Paulina 2019 1 113    64394
Name: 1, dtype: int64
Paulina 2013 2 113    66291
Name: 2, dtype: int64
Paulina 2014 2 113    69411
Name: 2, dtype: int64
Paulina 2015 2 114    65410
Name: 2, dtype: int64
Paulina 2016 2 114    68401
Name: 2, dtype: int64
Paulina 2017 2 114    64811
Name: 2, dtype: int64
Paulina 2018 2 114    64551
Name: 2, dtype: int64
Paulina 2019 2 113    64386
Name: 2, dtype: int64
Paulina 2013 3 113    69011
Name: 3, dtype: int64
Paulina 2014 3 113    77504
Name: 3, dtype: int64
Paulina 2015 3 114    73551
Name: 3, dtype: int64
Paulina 2016 3 114    76310
Name: 3, dtype: int64
Paulina 2017 3 114    73905
Name: 3, dtype: int64
Paulina 2018 3 114    72999
Name: 3, dtype: int64
Paulina 2019 3 113    71592
Name: 3, dtype: int64
Paulina 2013 4 113    71428
Name: 4, dtype: int64
Paulina 2014 4 113    74521
Name: 4, dtype: int64
Paulina 2015 4 114    70246
Name: 4, dtype: int64
Paulina 2016 4 114    71625
Name: 4, dtype: int64
Paulina 2017 4 114    67286
Name: 4, dtype: int64
Paulina 2018 4 114    68709
Name: 4, dtype: int64
Paulina 2019 4 113    69550
Name: 4, dtype: int64
Paulina 2013 5 113    71944
Name: 5, dtype: int64
Paulina 2014 5 113    74748
Name: 5, dtype: int64
Paulina 2015 5 114    71503
Name: 5, dtype: int64
Paulina 2016 5 114    73289
Name: 5, dtype: int64
Paulina 2017 5 114    72877
Name: 5, dtype: int64
Paulina 2018 5 114    73791
Name: 5, dtype: int64
Paulina 2019 5 113    74490
Name: 5, dtype: int64
Paulina 2013 6 113    74758
Name: 6, dtype: int64
Paulina 2014 6 113    75202
Name: 6, dtype: int64
Paulina 2015 6 114    76212
Name: 6, dtype: int64
Paulina 2016 6 114    77043
Name: 6, dtype: int64
Paulina 2017 6 114    77368
Name: 6, dtype: int64
Paulina 2018 6 114    74491
Name: 6, dtype: int64
Paulina 2019 6 113    73408
Name: 6, dtype: int64
Paulina 2013 7 113    80029
Name: 7, dtype: int64
Paulina 2014 7 113    76428
Name: 7, dtype: int64
Paulina 2015 7 114    78034
Name: 7, dtype: int64
Paulina 2016 7 114    72141
Name: 7, dtype: int64
Paulina 2017 7 114    71872
Name: 7, dtype: int64
Paulina 2018 7 114    0
Name: 7, dtype: int64
Paulina 2019 7 113    74025
Name: 7, dtype: int64
Paulina 2013 8 113    78990
Name: 8, dtype: int64
Paulina 2014 8 113    73816
Name: 8, dtype: int64
Paulina 2015 8 114    73723
Name: 8, dtype: int64
Paulina 2016 8 114    74715
Name: 8, dtype: int64
Paulina 2017 8 114    76947
Name: 8, dtype: int64
Paulina 2018 8 114    0
Name: 8, dtype: int64
Paulina 2019 8 113    76074
Name: 8, dtype: int64
Paulina 2013 9 113    74527
Name: 9, dtype: int64
Paulina 2014 9 113    73542
Name: 9, dtype: int64
Paulina 2015 9 114    73263
Name: 9, dtype: int64
Paulina 2016 9 114    72584
Name: 9, dtype: int64
Paulina 2017 9 114    73376
Name: 9, dtype: int64
Paulina 2018 9 114    0
Name: 9, dtype: int64
Paulina 2019 9 113    73308
Name: 9, dtype: int64
Paulina 2013 10 113    82478
Name: 10, dtype: int64
Paulina 2014 10 113    78012
Name: 10, dtype: int64
Paulina 2015 10 114    78358
Name: 10, dtype: int64
Paulina 2016 10 114    77207
Name: 10, dtype: int64
Paulina 2017 10 114    77172
Name: 10, dtype: int64
Paulina 2018 10 114    0
Name: 10, dtype: int64
Paulina 2019 10 113    79160
Name: 10, dtype: int64

Paulina 2013 11 113    70854
Name: 11, dtype: int64
Paulina 2014 11 113    65999
Name: 11, dtype: int64
Paulina 2015 11 114    67814
Name: 11, dtype: int64
Paulina 2016 11 114    70439
Name: 11, dtype: int64
Paulina 2017 11 114    68302
Name: 11, dtype: int64
Paulina 2018 11 114    0
Name: 11, dtype: int64
Paulina 2019 11 113    67254
Name: 11, dtype: int64
Paulina 2013 12 113    66063
Name: 12, dtype: int64
Paulina 2014 12 113    66605
Name: 12, dtype: int64
Paulina 2015 12 114    66384
Name: 12, dtype: int64
Paulina 2016 12 114    63504
Name: 12, dtype: int64
Paulina 2017 12 114    61426
Name: 12, dtype: int64
Paulina 2018 12 114    0
Name: 12, dtype: int64
Paulina 2019 12 113    62026
Name: 12, dtype: int64
Polk 2013 1 114    76610
Name: 1, dtype: int64
Polk 2014 1 114    73075
Name: 1, dtype: int64
Polk 2015 1 115    74639
Name: 1, dtype: int64
Polk 2016 1 115    76281
Name: 1, dtype: int64
Polk 2017 1 115    70971
Name: 1, dtype: int64
Polk 2018 1 115    71342
Name: 1, dtype: int64
Polk 2019 1 114    65254
Name: 1, dtype: int64
Polk 2013 2 114    75912
Name: 2, dtype: int64
Polk 2014 2 114    76887
Name: 2, dtype: int64
Polk 2015 2 115    76300
Name: 2, dtype: int64
Polk 2016 2 115    78654
Name: 2, dtype: int64
Polk 2017 2 115    70044
Name: 2, dtype: int64
Polk 2018 2 115    70987
Name: 2, dtype: int64
Polk 2019 2 114    68641
Name: 2, dtype: int64
Polk 2013 3 114    76234
Name: 3, dtype: int64
Polk 2014 3 114    82139
Name: 3, dtype: int64
Polk 2015 3 115    83745
Name: 3, dtype: int64
Polk 2016 3 115    81491
Name: 3, dtype: int64
Polk 2017 3 115    78216
Name: 3, dtype: int64
Polk 2018 3 115    76830
Name: 3, dtype: int64
Polk 2019 3 114    71052
Name: 3, dtype: int64
Polk 2013 4 114    81710
Name: 4, dtype: int64
Polk 2014 4 114    84092
Name: 4, dtype: int64
Polk 2015 4 115    84272
Name: 4, dtype: int64
Polk 2016 4 115    74600
Name: 4, dtype: int64
Polk 2017 4 115    70879
Name: 4, dtype: int64
Polk 2018 4 115    74386
Name: 4, dtype: int64
Polk 2019 4 114    74398
Name: 4, dtype: int64
Polk 2013 5 114    75967
Name: 5, dtype: int64
Polk 2014 5 114    78405
Name: 5, dtype: int64
Polk 2015 5 115    76997
Name: 5, dtype: int64
Polk 2016 5 115    73850
Name: 5, dtype: int64
Polk 2017 5 115    71355
Name: 5, dtype: int64
Polk 2018 5 115    74871
Name: 5, dtype: int64
Polk 2019 5 114    72384
Name: 5, dtype: int64
Polk 2013 6 114    73257
Name: 6, dtype: int64
Polk 2014 6 114    77719
Name: 6, dtype: int64
Polk 2015 6 115    84198
Name: 6, dtype: int64
Polk 2016 6 115    80692
Name: 6, dtype: int64
Polk 2017 6 115    74873
Name: 6, dtype: int64
Polk 2018 6 115    75348
Name: 6, dtype: int64
Polk 2019 6 114    67996
Name: 6, dtype: int64
Polk 2013 7 114    81123
Name: 7, dtype: int64
Polk 2014 7 114    81766
Name: 7, dtype: int64
Polk 2015 7 115    87694
Name: 7, dtype: int64
Polk 2016 7 115    75477
Name: 7, dtype: int64
Polk 2017 7 115    68986
Name: 7, dtype: int64
Polk 2018 7 115    75665
Name: 7, dtype: int64
Polk 2019 7 114    73865
Name: 7, dtype: int64
Polk 2013 8 114    82217
Name: 8, dtype: int64
Polk 2014 8 114    79686
Name: 8, dtype: int64
Polk 2015 8 115    83914
Name: 8, dtype: int64
Polk 2016 8 115    83540
Name: 8, dtype: int64
Polk 2017 8 115    80854
Name: 8, dtype: int64
Polk 2018 8 115    0
Name: 8, dtype: int64
Polk 2019 8 114    75061
Name: 8, dtype: int64
Polk 2013 9 114    83209
Name: 9, dtype: int64
Polk 2014 9 114    86552
Name: 9, dtype: int64
Polk 2015 9 115    91662
Name: 9, dtype: int64
Polk 2016 9 115    83528
Name: 9, dtype: int64
Polk 2017 9 115    81589
Name: 9, dtype: int64
Polk 2018 9 115    0
Name: 9, dtype: int64
Polk 2019 9 114    80020
Name: 9, dtype: int64
Polk 2013 10 114    92279
Name: 10, dtype: int64
Polk 2014 10 114    93061
Name: 10, dtype: int64
Polk 2015 10 115    95357
Name: 10, dtype: int64
Polk 2016 10 115    83534
Name: 10, dtype: int64
Polk 2017 10 115    86710
Name: 10, dtype: int64
Polk 2018 10 115    0
Name: 10, dtype: int64
Polk 2019 10 114    86939
Name: 10, dtype: int64
Polk 2013 11 114    77197
Name: 11, dtype: int64
Polk 2014 11 114    74187
Name: 11, dtype: int64
Polk 2015 11 115    81726
Name: 11, dtype: int64
Polk 2016 11 115    77475
Name: 11, dtype: int64
Polk 2017 11 115    76991
Name: 11, dtype: int64
Polk 2018 11 115    0
Name: 11, dtype: int64
Polk 2019 11 114    72398
Name: 11, dtype: int64
Polk 2013 12 114    66788
Name: 12, dtype: int64
Polk 2014 12 114    70167
Name: 12, dtype: int64
Polk 2015 12 115    73468
Name: 12, dtype: int64
Polk 2016 12 115    59439
Name: 12, dtype: int64
Polk 2017 12 115    61866
Name: 12, dtype: int64
Polk 2018 12 115    0
Name: 12, dtype: int64
Polk 2019 12 114    61183
Name: 12, dtype: int64
Pulaski-Cermak 2013 1 115    30945
Name: 1, dtype: int64
Pulaski-Cermak 2014 1 115    30100
Name: 1, dtype: int64
Pulaski-Cermak 2015 1 116    31503
Name: 1, dtype: int64
Pulaski-Cermak 2016 1 116    30190
Name: 1, dtype: int64
Pulaski-Cermak 2017 1 116    27367
Name: 1, dtype: int64
Pulaski-Cermak 2018 1 116    25350
Name: 1, dtype: int64
Pulaski-Cermak 2019 1 115    23635
Name: 1, dtype: int64
Pulaski-Cermak 2013 2 115    28914
Name: 2, dtype: int64
Pulaski-Cermak 2014 2 115    30885
Name: 2, dtype: int64
Pulaski-Cermak 2015 2 116    30077
Name: 2, dtype: int64
Pulaski-Cermak 2016 2 116    30591
Name: 2, dtype: int64
Pulaski-Cermak 2017 2 116    27144
Name: 2, dtype: int64
Pulaski-Cermak 2018 2 116    24222
Name: 2, dtype: int64
Pulaski-Cermak 2019 2 115    24083
Name: 2, dtype: int64
Pulaski-Cermak 2013 3 115    29936
Name: 3, dtype: int64
Pulaski-Cermak 2014 3 115    34758
Name: 3, dtype: int64
Pulaski-Cermak 2015 3 116    34884
Name: 3, dtype: int64
Pulaski-Cermak 2016 3 116    31601
Name: 3, dtype: int64
Pulaski-Cermak 2017 3 116    28860
Name: 3, dtype: int64
Pulaski-Cermak 2018 3 116    26846
Name: 3, dtype: int64
Pulaski-Cermak 2019 3 115    25895
Name: 3, dtype: int64
Pulaski-Cermak 2013 4 115    31918
Name: 4, dtype: int64
Pulaski-Cermak 2014 4 115    34836
Name: 4, dtype: int64
Pulaski-Cermak 2015 4 116    34417
Name: 4, dtype: int64
Pulaski-Cermak 2016 4 116    29338
Name: 4, dtype: int64
Pulaski-Cermak 2017 4 116    26436
Name: 4, dtype: int64
Pulaski-Cermak 2018 4 116    26334
Name: 4, dtype: int64
Pulaski-Cermak 2019 4 115    26461
Name: 4, dtype: int64
Pulaski-Cermak 2013 5 115    32505
Name: 5, dtype: int64
Pulaski-Cermak 2014 5 115    35927
Name: 5, dtype: int64
Pulaski-Cermak 2015 5 116    34190
Name: 5, dtype: int64
Pulaski-Cermak 2016 5 116    31087
Name: 5, dtype: int64
Pulaski-Cermak 2017 5 116    29068
Name: 5, dtype: int64
Pulaski-Cermak 2018 5 116    29004
Name: 5, dtype: int64
Pulaski-Cermak 2019 5 115    29233
Name: 5, dtype: int64
Pulaski-Cermak 2013 6 115    32090
Name: 6, dtype: int64
Pulaski-Cermak 2014 6 115    34796
Name: 6, dtype: int64
Pulaski-Cermak 2015 6 116    34647
Name: 6, dtype: int64
Pulaski-Cermak 2016 6 116    31312
Name: 6, dtype: int64
Pulaski-Cermak 2017 6 116    29001
Name: 6, dtype: int64
Pulaski-Cermak 2018 6 116    27700
Name: 6, dtype: int64
Pulaski-Cermak 2019 6 115    27871
Name: 6, dtype: int64
Pulaski-Cermak 2013 7 115    34145
Name: 7, dtype: int64
Pulaski-Cermak 2014 7 115    35517
Name: 7, dtype: int64
Pulaski-Cermak 2015 7 116    35994
Name: 7, dtype: int64
Pulaski-Cermak 2016 7 116    31012
Name: 7, dtype: int64
Pulaski-Cermak 2017 7 116    27943
Name: 7, dtype: int64
Pulaski-Cermak 2018 7 116    28864
Name: 7, dtype: int64
Pulaski-Cermak 2019 7 115    29305
Name: 7, dtype: int64
Pulaski-Cermak 2013 8 115    34409
Name: 8, dtype: int64
Pulaski-Cermak 2014 8 115    34874
Name: 8, dtype: int64
Pulaski-Cermak 2015 8 116    35288
Name: 8, dtype: int64
Pulaski-Cermak 2016 8 116    31081
Name: 8, dtype: int64
Pulaski-Cermak 2017 8 116    29569
Name: 8, dtype: int64
Pulaski-Cermak 2018 8 116    0
Name: 8, dtype: int64
Pulaski-Cermak 2019 8 115    29220
Name: 8, dtype: int64
Pulaski-Cermak 2013 9 115    33675
Name: 9, dtype: int64
Pulaski-Cermak 2014 9 115    36539
Name: 9, dtype: int64
Pulaski-Cermak 2015 9 116    36075
Name: 9, dtype: int64
Pulaski-Cermak 2016 9 116    32038
Name: 9, dtype: int64
Pulaski-Cermak 2017 9 116    29594
Name: 9, dtype: int64
Pulaski-Cermak 2018 9 116    0
Name: 9, dtype: int64
Pulaski-Cermak 2019 9 115    29690
Name: 9, dtype: int64
Pulaski-Cermak 2013 10 115    35808
Name: 10, dtype: int64
Pulaski-Cermak 2014 10 115    38692
Name: 10, dtype: int64
Pulaski-Cermak 2015 10 116    37618
Name: 10, dtype: int64
Pulaski-Cermak 2016 10 116    32243
Name: 10, dtype: int64
Pulaski-Cermak 2017 10 116    30922
Name: 10, dtype: int64
Pulaski-Cermak 2018 10 116    0
Name: 10, dtype: int64
Pulaski-Cermak 2019 10 115    30514
Name: 10, dtype: int64
Pulaski-Cermak 2013 11 115    32945
Name: 11, dtype: int64
Pulaski-Cermak 2014 11 115    32791
Name: 11, dtype: int64
Pulaski-Cermak 2015 11 116    33315
Name: 11, dtype: int64
Pulaski-Cermak 2016 11 116    30651
Name: 11, dtype: int64
Pulaski-Cermak 2017 11 116    28503
Name: 11, dtype: int64
Pulaski-Cermak 2018 11 116    0
Name: 11, dtype: int64
Pulaski-Cermak 2019 11 115    26620
Name: 11, dtype: int64
Pulaski-Cermak 2013 12 115    31504
Name: 12, dtype: int64
Pulaski-Cermak 2014 12 115    34267
Name: 12, dtype: int64
Pulaski-Cermak 2015 12 116    33578
Name: 12, dtype: int64
Pulaski-Cermak 2016 12 116    27870
Name: 12, dtype: int64
Pulaski-Cermak 2017 12 116    26479
Name: 12, dtype: int64
Pulaski-Cermak 2018 12 116    0
Name: 12, dtype: int64
Pulaski-Cermak 2019 12 115    25895
Name: 12, dtype: int64
Pulaski-Forest Park 2013 1 116    51714
Name: 1, dtype: int64
Pulaski-Forest Park 2014 1 116    47455
Name: 1, dtype: int64
Pulaski-Forest Park 2015 1 117    47172
Name: 1, dtype: int64
Pulaski-Forest Park 2016 1 117    50458
Name: 1, dtype: int64
Pulaski-Forest Park 2017 1 117    44153
Name: 1, dtype: int64
Pulaski-Forest Park 2018 1 117    42093
Name: 1, dtype: int64
Pulaski-Forest Park 2019 1 116    44885
Name: 1, dtype: int64
Pulaski-Forest Park 2013 2 116    46362
Name: 2, dtype: int64
Pulaski-Forest Park 2014 2 116    47772
Name: 2, dtype: int64
Pulaski-Forest Park 2015 2 117    42835
Name: 2, dtype: int64
Pulaski-Forest Park 2016 2 117    51441
Name: 2, dtype: int64
Pulaski-Forest Park 2017 2 117    44273
Name: 2, dtype: int64
Pulaski-Forest Park 2018 2 117    40941
Name: 2, dtype: int64
Pulaski-Forest Park 2019 2 116    44023
Name: 2, dtype: int64
Pulaski-Forest Park 2013 3 116    50060
Name: 3, dtype: int64
Pulaski-Forest Park 2014 3 116    53139
Name: 3, dtype: int64
Pulaski-Forest Park 2015 3 117    50127
Name: 3, dtype: int64
Pulaski-Forest Park 2016 3 117    56301
Name: 3, dtype: int64
Pulaski-Forest Park 2017 3 117    47777
Name: 3, dtype: int64
Pulaski-Forest Park 2018 3 117    46833
Name: 3, dtype: int64
Pulaski-Forest Park 2019 3 116    47462
Name: 3, dtype: int64
Pulaski-Forest Park 2013 4 116    50351
Name: 4, dtype: int64
Pulaski-Forest Park 2014 4 116    50765
Name: 4, dtype: int64
Pulaski-Forest Park 2015 4 117    50266
Name: 4, dtype: int64
Pulaski-Forest Park 2016 4 117    51351
Name: 4, dtype: int64
Pulaski-Forest Park 2017 4 117    45423
Name: 4, dtype: int64
Pulaski-Forest Park 2018 4 117    42823
Name: 4, dtype: int64
Pulaski-Forest Park 2019 4 116    47197
Name: 4, dtype: int64
Pulaski-Forest Park 2013 5 116    52354
Name: 5, dtype: int64
Pulaski-Forest Park 2014 5 116    53946
Name: 5, dtype: int64
Pulaski-Forest Park 2015 5 117    52882
Name: 5, dtype: int64
Pulaski-Forest Park 2016 5 117    50416
Name: 5, dtype: int64
Pulaski-Forest Park 2017 5 117    50038
Name: 5, dtype: int64
Pulaski-Forest Park 2018 5 117    47198
Name: 5, dtype: int64
Pulaski-Forest Park 2019 5 116    50430
Name: 5, dtype: int64
Pulaski-Forest Park 2013 6 116    49977
Name: 6, dtype: int64
Pulaski-Forest Park 2014 6 116    53690
Name: 6, dtype: int64
Pulaski-Forest Park 2015 6 117    54756
Name: 6, dtype: int64
Pulaski-Forest Park 2016 6 117    52263
Name: 6, dtype: int64
Pulaski-Forest Park 2017 6 117    48887
Name: 6, dtype: int64
Pulaski-Forest Park 2018 6 117    45860
Name: 6, dtype: int64
Pulaski-Forest Park 2019 6 116    49006
Name: 6, dtype: int64
Pulaski-Forest Park 2013 7 116    53599
Name: 7, dtype: int64
Pulaski-Forest Park 2014 7 116    57140
Name: 7, dtype: int64
Pulaski-Forest Park 2015 7 117    56973
Name: 7, dtype: int64
Pulaski-Forest Park 2016 7 117    53043
Name: 7, dtype: int64
Pulaski-Forest Park 2017 7 117    50901
Name: 7, dtype: int64
Pulaski-Forest Park 2018 7 117    46129
Name: 7, dtype: int64
Pulaski-Forest Park 2019 7 116    48052
Name: 7, dtype: int64
Pulaski-Forest Park 2013 8 116    54638
Name: 8, dtype: int64
Pulaski-Forest Park 2014 8 116    57918
Name: 8, dtype: int64
Pulaski-Forest Park 2015 8 117    53449
Name: 8, dtype: int64
Pulaski-Forest Park 2016 8 117    55046
Name: 8, dtype: int64
Pulaski-Forest Park 2017 8 117    50508
Name: 8, dtype: int64
Pulaski-Forest Park 2018 8 117    0
Name: 8, dtype: int64
Pulaski-Forest Park 2019 8 116    48021
Name: 8, dtype: int64
Pulaski-Forest Park 2013 9 116    52905
Name: 9, dtype: int64
Pulaski-Forest Park 2014 9 116    59894
Name: 9, dtype: int64
Pulaski-Forest Park 2015 9 117    54858
Name: 9, dtype: int64
Pulaski-Forest Park 2016 9 117    53992
Name: 9, dtype: int64
Pulaski-Forest Park 2017 9 117    48302
Name: 9, dtype: int64
Pulaski-Forest Park 2018 9 117    0
Name: 9, dtype: int64
Pulaski-Forest Park 2019 9 116    46978
Name: 9, dtype: int64
Pulaski-Forest Park 2013 10 116    57430
Name: 10, dtype: int64
Pulaski-Forest Park 2014 10 116    61563
Name: 10, dtype: int64
Pulaski-Forest Park 2015 10 117    59919
Name: 10, dtype: int64
Pulaski-Forest Park 2016 10 117    53295
Name: 10, dtype: int64
Pulaski-Forest Park 2017 10 117    50295
Name: 10, dtype: int64
Pulaski-Forest Park 2018 10 117    0
Name: 10, dtype: int64
Pulaski-Forest Park 2019 10 116    50899
Name: 10, dtype: int64
Pulaski-Forest Park 2013 11 116    52778
Name: 11, dtype: int64
Pulaski-Forest Park 2014 11 116    51601
Name: 11, dtype: int64
Pulaski-Forest Park 2015 11 117    55963
Name: 11, dtype: int64
Pulaski-Forest Park 2016 11 117    49657
Name: 11, dtype: int64
Pulaski-Forest Park 2017 11 117    46078
Name: 11, dtype: int64
Pulaski-Forest Park 2018 11 117    0
Name: 11, dtype: int64
Pulaski-Forest Park 2019 11 116    46104
Name: 11, dtype: int64
Pulaski-Forest Park 2013 12 116    52056
Name: 12, dtype: int64
Pulaski-Forest Park 2014 12 116    52789
Name: 12, dtype: int64
Pulaski-Forest Park 2015 12 117    55517
Name: 12, dtype: int64
Pulaski-Forest Park 2016 12 117    45946
Name: 12, dtype: int64
Pulaski-Forest Park 2017 12 117    42519
Name: 12, dtype: int64
Pulaski-Forest Park 2018 12 117    0
Name: 12, dtype: int64
Pulaski-Forest Park 2019 12 116    47840
Name: 12, dtype: int64
Pulaski-Lake 2013 1 117    52230
Name: 1, dtype: int64
Pulaski-Lake 2014 1 117    41234
Name: 1, dtype: int64
Pulaski-Lake 2015 1 118    44444
Name: 1, dtype: int64
Pulaski-Lake 2016 1 118    39408
Name: 1, dtype: int64
Pulaski-Lake 2017 1 118    36205
Name: 1, dtype: int64
Pulaski-Lake 2018 1 118    32537
Name: 1, dtype: int64
Pulaski-Lake 2019 1 117    35314
Name: 1, dtype: int64
Pulaski-Lake 2013 2 117    47708
Name: 2, dtype: int64
Pulaski-Lake 2014 2 117    42356
Name: 2, dtype: int64
Pulaski-Lake 2015 2 118    39893
Name: 2, dtype: int64
Pulaski-Lake 2016 2 118    38213
Name: 2, dtype: int64
Pulaski-Lake 2017 2 118    36549
Name: 2, dtype: int64
Pulaski-Lake 2018 2 118    31237
Name: 2, dtype: int64
Pulaski-Lake 2019 2 117    33310
Name: 2, dtype: int64
Pulaski-Lake 2013 3 117    50914
Name: 3, dtype: int64
Pulaski-Lake 2014 3 117    48906
Name: 3, dtype: int64
Pulaski-Lake 2015 3 118    47254
Name: 3, dtype: int64
Pulaski-Lake 2016 3 118    41842
Name: 3, dtype: int64
Pulaski-Lake 2017 3 118    39492
Name: 3, dtype: int64
Pulaski-Lake 2018 3 118    35516
Name: 3, dtype: int64
Pulaski-Lake 2019 3 117    38550
Name: 3, dtype: int64
Pulaski-Lake 2013 4 117    54508
Name: 4, dtype: int64
Pulaski-Lake 2014 4 117    49646
Name: 4, dtype: int64
Pulaski-Lake 2015 4 118    47131
Name: 4, dtype: int64
Pulaski-Lake 2016 4 118    38825
Name: 4, dtype: int64
Pulaski-Lake 2017 4 118    36830
Name: 4, dtype: int64
Pulaski-Lake 2018 4 118    35442
Name: 4, dtype: int64
Pulaski-Lake 2019 4 117    39467
Name: 4, dtype: int64
Pulaski-Lake 2013 5 117    55165
Name: 5, dtype: int64
Pulaski-Lake 2014 5 117    53215
Name: 5, dtype: int64
Pulaski-Lake 2015 5 118    48768
Name: 5, dtype: int64
Pulaski-Lake 2016 5 118    41368
Name: 5, dtype: int64
Pulaski-Lake 2017 5 118    40336
Name: 5, dtype: int64
Pulaski-Lake 2018 5 118    39261
Name: 5, dtype: int64
Pulaski-Lake 2019 5 117    44120
Name: 5, dtype: int64
Pulaski-Lake 2013 6 117    50297
Name: 6, dtype: int64
Pulaski-Lake 2014 6 117    50588
Name: 6, dtype: int64
Pulaski-Lake 2015 6 118    49622
Name: 6, dtype: int64
Pulaski-Lake 2016 6 118    41185
Name: 6, dtype: int64
Pulaski-Lake 2017 6 118    39922
Name: 6, dtype: int64
Pulaski-Lake 2018 6 118    37908
Name: 6, dtype: int64
Pulaski-Lake 2019 6 117    42019
Name: 6, dtype: int64
Pulaski-Lake 2013 7 117    52124
Name: 7, dtype: int64
Pulaski-Lake 2014 7 117    53557
Name: 7, dtype: int64
Pulaski-Lake 2015 7 118    50323
Name: 7, dtype: int64
Pulaski-Lake 2016 7 118    39402
Name: 7, dtype: int64
Pulaski-Lake 2017 7 118    38277
Name: 7, dtype: int64
Pulaski-Lake 2018 7 118    38226
Name: 7, dtype: int64
Pulaski-Lake 2019 7 117    41530
Name: 7, dtype: int64
Pulaski-Lake 2013 8 117    53611
Name: 8, dtype: int64
Pulaski-Lake 2014 8 117    53810
Name: 8, dtype: int64
Pulaski-Lake 2015 8 118    48543
Name: 8, dtype: int64
Pulaski-Lake 2016 8 118    39278
Name: 8, dtype: int64
Pulaski-Lake 2017 8 118    36505
Name: 8, dtype: int64
Pulaski-Lake 2018 8 118    0
Name: 8, dtype: int64
Pulaski-Lake 2019 8 117    38346
Name: 8, dtype: int64
Pulaski-Lake 2013 9 117    49634

Name: 9, dtype: int64
Pulaski-Lake 2014 9 117    55827
Name: 9, dtype: int64
Pulaski-Lake 2015 9 118    50265
Name: 9, dtype: int64
Pulaski-Lake 2016 9 118    39879
Name: 9, dtype: int64
Pulaski-Lake 2017 9 118    38928
Name: 9, dtype: int64
Pulaski-Lake 2018 9 118    0
Name: 9, dtype: int64
Pulaski-Lake 2019 9 117    36818
Name: 9, dtype: int64
Pulaski-Lake 2013 10 117    53991
Name: 10, dtype: int64
Pulaski-Lake 2014 10 117    58685
Name: 10, dtype: int64
Pulaski-Lake 2015 10 118    51234
Name: 10, dtype: int64
Pulaski-Lake 2016 10 118    41863
Name: 10, dtype: int64
Pulaski-Lake 2017 10 118    39883
Name: 10, dtype: int64
Pulaski-Lake 2018 10 118    0
Name: 10, dtype: int64
Pulaski-Lake 2019 10 117    37660
Name: 10, dtype: int64
Pulaski-Lake 2013 11 117    47970
Name: 11, dtype: int64
Pulaski-Lake 2014 11 117    48844
Name: 11, dtype: int64
Pulaski-Lake 2015 11 118    44670
Name: 11, dtype: int64
Pulaski-Lake 2016 11 118    41070
Name: 11, dtype: int64
Pulaski-Lake 2017 11 118    35410
Name: 11, dtype: int64
Pulaski-Lake 2018 11 118    0
Name: 11, dtype: int64
Pulaski-Lake 2019 11 117    34717
Name: 11, dtype: int64
Pulaski-Lake 2013 12 117    45433
Name: 12, dtype: int64
Pulaski-Lake 2014 12 117    49655
Name: 12, dtype: int64
Pulaski-Lake 2015 12 118    43872
Name: 12, dtype: int64
Pulaski-Lake 2016 12 118    38002
Name: 12, dtype: int64
Pulaski-Lake 2017 12 118    33107
Name: 12, dtype: int64
Pulaski-Lake 2018 12 118    0
Name: 12, dtype: int64
Pulaski-Lake 2019 12 117    33645
Name: 12, dtype: int64
Pulaski-Orange 2013 1 118    122293
Name: 1, dtype: int64
Pulaski-Orange 2014 1 118    106300
Name: 1, dtype: int64
Pulaski-Orange 2015 1 119    116012
Name: 1, dtype: int64
Pulaski-Orange 2016 1 119    117035
Name: 1, dtype: int64
Pulaski-Orange 2017 1 119    115823
Name: 1, dtype: int64
Pulaski-Orange 2018 1 119    113812
Name: 1, dtype: int64
Pulaski-Orange 2019 1 118    103259
Name: 1, dtype: int64
Pulaski-Orange 2013 2 118    115665
Name: 2, dtype: int64
Pulaski-Orange 2014 2 118    116662
Name: 2, dtype: int64
Pulaski-Orange 2015 2 119    112610
Name: 2, dtype: int64
Pulaski-Orange 2016 2 119    123608
Name: 2, dtype: int64
Pulaski-Orange 2017 2 119    118472
Name: 2, dtype: int64
Pulaski-Orange 2018 2 119    110715
Name: 2, dtype: int64
Pulaski-Orange 2019 2 118    109202
Name: 2, dtype: int64
Pulaski-Orange 2013 3 118    122289
Name: 3, dtype: int64
Pulaski-Orange 2014 3 118    131650
Name: 3, dtype: int64
Pulaski-Orange 2015 3 119    135673
Name: 3, dtype: int64
Pulaski-Orange 2016 3 119    137514
Name: 3, dtype: int64
Pulaski-Orange 2017 3 119    136932
Name: 3, dtype: int64
Pulaski-Orange 2018 3 119    126375
Name: 3, dtype: int64
Pulaski-Orange 2019 3 118    121882
Name: 3, dtype: int64
Pulaski-Orange 2013 4 118    131359
Name: 4, dtype: int64
Pulaski-Orange 2014 4 118    129970
Name: 4, dtype: int64
Pulaski-Orange 2015 4 119    130966
Name: 4, dtype: int64
Pulaski-Orange 2016 4 119    128466
Name: 4, dtype: int64
Pulaski-Orange 2017 4 119    121467
Name: 4, dtype: int64
Pulaski-Orange 2018 4 119    123095
Name: 4, dtype: int64
Pulaski-Orange 2019 4 118    121051
Name: 4, dtype: int64
Pulaski-Orange 2013 5 118    133451
Name: 5, dtype: int64
Pulaski-Orange 2014 5 118    130293
Name: 5, dtype: int64
Pulaski-Orange 2015 5 119    131092
Name: 5, dtype: int64
Pulaski-Orange 2016 5 119    134902
Name: 5, dtype: int64
Pulaski-Orange 2017 5 119    135458
Name: 5, dtype: int64
Pulaski-Orange 2018 5 119    134913
Name: 5, dtype: int64
Pulaski-Orange 2019 5 118    129145
Name: 5, dtype: int64
Pulaski-Orange 2013 6 118    128427
Name: 6, dtype: int64
Pulaski-Orange 2014 6 118    128424
Name: 6, dtype: int64
Pulaski-Orange 2015 6 119    137635
Name: 6, dtype: int64
Pulaski-Orange 2016 6 119    137218
Name: 6, dtype: int64
Pulaski-Orange 2017 6 119    134385
Name: 6, dtype: int64
Pulaski-Orange 2018 6 119    126006
Name: 6, dtype: int64
Pulaski-Orange 2019 6 118    121694
Name: 6, dtype: int64
Pulaski-Orange 2013 7 118    130213
Name: 7, dtype: int64
Pulaski-Orange 2014 7 118    125284
Name: 7, dtype: int64
Pulaski-Orange 2015 7 119    140339
Name: 7, dtype: int64
Pulaski-Orange 2016 7 119    130681
Name: 7, dtype: int64
Pulaski-Orange 2017 7 119    123030
Name: 7, dtype: int64
Pulaski-Orange 2018 7 119    0
Name: 7, dtype: int64
Pulaski-Orange 2019 7 118    124326
Name: 7, dtype: int64
Pulaski-Orange 2013 8 118    130220
Name: 8, dtype: int64
Pulaski-Orange 2014 8 118    126723
Name: 8, dtype: int64
Pulaski-Orange 2015 8 119    131527
Name: 8, dtype: int64
Pulaski-Orange 2016 8 119    131443
Name: 8, dtype: int64
Pulaski-Orange 2017 8 119    131615
Name: 8, dtype: int64
Pulaski-Orange 2018 8 119    0
Name: 8, dtype: int64
Pulaski-Orange 2019 8 118    124432
Name: 8, dtype: int64
Pulaski-Orange 2013 9 118    135984
Name: 9, dtype: int64
Pulaski-Orange 2014 9 118    145557
Name: 9, dtype: int64
Pulaski-Orange 2015 9 119    147428
Name: 9, dtype: int64
Pulaski-Orange 2016 9 119    144068
Name: 9, dtype: int64
Pulaski-Orange 2017 9 119    139419
Name: 9, dtype: int64
Pulaski-Orange 2018 9 119    0
Name: 9, dtype: int64
Pulaski-Orange 2019 9 118    136945
Name: 9, dtype: int64
Pulaski-Orange 2013 10 118    147526
Name: 10, dtype: int64
Pulaski-Orange 2014 10 118    155075
Name: 10, dtype: int64
Pulaski-Orange 2015 10 119    153246
Name: 10, dtype: int64
Pulaski-Orange 2016 10 119    143885
Name: 10, dtype: int64
Pulaski-Orange 2017 10 119    144393
Name: 10, dtype: int64
Pulaski-Orange 2018 10 119    0
Name: 10, dtype: int64
Pulaski-Orange 2019 10 118    140626
Name: 10, dtype: int64
Pulaski-Orange 2013 11 118    123452
Name: 11, dtype: int64
Pulaski-Orange 2014 11 118    122597
Name: 11, dtype: int64
Pulaski-Orange 2015 11 119    130694
Name: 11, dtype: int64
Pulaski-Orange 2016 11 119    135490
Name: 11, dtype: int64
Pulaski-Orange 2017 11 119    130423
Name: 11, dtype: int64
Pulaski-Orange 2018 11 119    0
Name: 11, dtype: int64
Pulaski-Orange 2019 11 118    121730
Name: 11, dtype: int64
Pulaski-Orange 2013 12 118    112348
Name: 12, dtype: int64
Pulaski-Orange 2014 12 118    122098
Name: 12, dtype: int64
Pulaski-Orange 2015 12 119    125592
Name: 12, dtype: int64
Pulaski-Orange 2016 12 119    114796
Name: 12, dtype: int64
Pulaski-Orange 2017 12 119    114444
Name: 12, dtype: int64
Pulaski-Orange 2018 12 119    0
Name: 12, dtype: int64
Pulaski-Orange 2019 12 118    111302
Name: 12, dtype: int64
Quincy/Wells 2013 1 119    189402
Name: 1, dtype: int64
Quincy/Wells 2014 1 119    185383
Name: 1, dtype: int64
Quincy/Wells 2015 1 120    174705
Name: 1, dtype: int64
Quincy/Wells 2016 1 120    175198
Name: 1, dtype: int64
Quincy/Wells 2017 1 120    180009
Name: 1, dtype: int64
Quincy/Wells 2018 1 120    180738
Name: 1, dtype: int64
Quincy/Wells 2019 1 119    167280
Name: 1, dtype: int64
Quincy/Wells 2013 2 119    173290
Name: 2, dtype: int64
Quincy/Wells 2014 2 119    179857
Name: 2, dtype: int64
Quincy/Wells 2015 2 120    167757
Name: 2, dtype: int64
Quincy/Wells 2016 2 120    177656
Name: 2, dtype: int64
Quincy/Wells 2017 2 120    165308
Name: 2, dtype: int64
Quincy/Wells 2018 2 120    161890
Name: 2, dtype: int64
Quincy/Wells 2019 2 119    167415
Name: 2, dtype: int64
Quincy/Wells 2013 3 119    152630
Name: 3, dtype: int64
Quincy/Wells 2014 3 119    199322
Name: 3, dtype: int64
Quincy/Wells 2015 3 120    191530
Name: 3, dtype: int64
Quincy/Wells 2016 3 120    198976
Name: 3, dtype: int64
Quincy/Wells 2017 3 120    199831
Name: 3, dtype: int64
Quincy/Wells 2018 3 120    186353
Name: 3, dtype: int64
Quincy/Wells 2019 3 119    181851
Name: 3, dtype: int64
Quincy/Wells 2013 4 119    179139
Name: 4, dtype: int64
Quincy/Wells 2014 4 119    201403
Name: 4, dtype: int64
Quincy/Wells 2015 4 120    183205
Name: 4, dtype: int64
Quincy/Wells 2016 4 120    184956
Name: 4, dtype: int64
Quincy/Wells 2017 4 120    176936
Name: 4, dtype: int64
Quincy/Wells 2018 4 120    179467
Name: 4, dtype: int64
Quincy/Wells 2019 4 119    188680
Name: 4, dtype: int64
Quincy/Wells 2013 5 119    175930
Name: 5, dtype: int64
Quincy/Wells 2014 5 119    193393
Name: 5, dtype: int64
Quincy/Wells 2015 5 120    172388
Name: 5, dtype: int64
Quincy/Wells 2016 5 120    189067
Name: 5, dtype: int64
Quincy/Wells 2017 5 120    196987
Name: 5, dtype: int64
Quincy/Wells 2018 5 120    190410
Name: 5, dtype: int64
Quincy/Wells 2019 5 119    193320
Name: 5, dtype: int64
Quincy/Wells 2013 6 119    185891
Name: 6, dtype: int64
Quincy/Wells 2014 6 119    195003
Name: 6, dtype: int64
Quincy/Wells 2015 6 120    196798
Name: 6, dtype: int64
Quincy/Wells 2016 6 120    201272
Name: 6, dtype: int64
Quincy/Wells 2017 6 120    202473
Name: 6, dtype: int64
Quincy/Wells 2018 6 120    186307
Name: 6, dtype: int64
Quincy/Wells 2019 6 119    182445
Name: 6, dtype: int64
Quincy/Wells 2013 7 119    206769
Name: 7, dtype: int64

Quincy/Wells 2014 7 119    205556
Name: 7, dtype: int64
Quincy/Wells 2015 7 120    197418
Name: 7, dtype: int64
Quincy/Wells 2016 7 120    190152
Name: 7, dtype: int64
Quincy/Wells 2017 7 120    184680
Name: 7, dtype: int64
Quincy/Wells 2018 7 120    0
Name: 7, dtype: int64
Quincy/Wells 2019 7 119    196562
Name: 7, dtype: int64
Quincy/Wells 2013 8 119    202995
Name: 8, dtype: int64
Quincy/Wells 2014 8 119    193308
Name: 8, dtype: int64
Quincy/Wells 2015 8 120    185173
Name: 8, dtype: int64
Quincy/Wells 2016 8 120    207230
Name: 8, dtype: int64
Quincy/Wells 2017 8 120    205522
Name: 8, dtype: int64
Quincy/Wells 2018 8 120    0
Name: 8, dtype: int64
Quincy/Wells 2019 8 119    192950
Name: 8, dtype: int64
Quincy/Wells 2013 9 119    188072
Name: 9, dtype: int64
Quincy/Wells 2014 9 119    191405
Name: 9, dtype: int64
Quincy/Wells 2015 9 120    185776
Name: 9, dtype: int64
Quincy/Wells 2016 9 120    187694
Name: 9, dtype: int64
Quincy/Wells 2017 9 120    180511
Name: 9, dtype: int64
Quincy/Wells 2018 9 120    0
Name: 9, dtype: int64
Quincy/Wells 2019 9 119    181805
Name: 9, dtype: int64
Quincy/Wells 2013 10 119    218345
Name: 10, dtype: int64
Quincy/Wells 2014 10 119    210197
Name: 10, dtype: int64
Quincy/Wells 2015 10 120    201063
Name: 10, dtype: int64
Quincy/Wells 2016 10 120    191821
Name: 10, dtype: int64
Quincy/Wells 2017 10 120    200334
Name: 10, dtype: int64
Quincy/Wells 2018 10 120    0
Name: 10, dtype: int64
Quincy/Wells 2019 10 119    211988
Name: 10, dtype: int64
Quincy/Wells 2013 11 119    179855
Name: 11, dtype: int64
Quincy/Wells 2014 11 119    166251
Name: 11, dtype: int64
Quincy/Wells 2015 11 120    172264
Name: 11, dtype: int64
Quincy/Wells 2016 11 120    176946
Name: 11, dtype: int64
Quincy/Wells 2017 11 120    177569
Name: 11, dtype: int64
Quincy/Wells 2018 11 120    0
Name: 11, dtype: int64
Quincy/Wells 2019 11 119    169583
Name: 11, dtype: int64
Quincy/Wells 2013 12 119    168215
Name: 12, dtype: int64
Quincy/Wells 2014 12 119    167275
Name: 12, dtype: int64
Quincy/Wells 2015 12 120    165020
Name: 12, dtype: int64
Quincy/Wells 2016 12 120    157105
Name: 12, dtype: int64
Quincy/Wells 2017 12 120    152293
Name: 12, dtype: int64
Quincy/Wells 2018 12 120    0
Name: 12, dtype: int64
Quincy/Wells 2019 12 119    154475
Name: 12, dtype: int64
Racine 2013 1 120    63153
Name: 1, dtype: int64
Racine 2014 1 120    56260
Name: 1, dtype: int64
Racine 2015 1 121    59079
Name: 1, dtype: int64
Racine 2016 1 121    56898
Name: 1, dtype: int64
Racine 2017 1 121    50103
Name: 1, dtype: int64
Racine 2018 1 121    54443
Name: 1, dtype: int64
Racine 2019 1 120    48335
Name: 1, dtype: int64
Racine 2013 2 120    59344
Name: 2, dtype: int64
Racine 2014 2 120    60918
Name: 2, dtype: int64
Racine 2015 2 121    57431
Name: 2, dtype: int64
Racine 2016 2 121    57656
Name: 2, dtype: int64
Racine 2017 2 121    49563
Name: 2, dtype: int64
Racine 2018 2 121    53839
Name: 2, dtype: int64
Racine 2019 2 120    50905
Name: 2, dtype: int64
Racine 2013 3 120    60482
Name: 3, dtype: int64
Racine 2014 3 120    68889
Name: 3, dtype: int64
Racine 2015 3 121    67712
Name: 3, dtype: int64
Racine 2016 3 121    67380
Name: 3, dtype: int64
Racine 2017 3 121    57244
Name: 3, dtype: int64
Racine 2018 3 121    58425
Name: 3, dtype: int64
Racine 2019 3 120    55219
Name: 3, dtype: int64
Racine 2013 4 120    65287
Name: 4, dtype: int64
Racine 2014 4 120    63213
Name: 4, dtype: int64
Racine 2015 4 121    61011
Name: 4, dtype: int64
Racine 2016 4 121    54609
Name: 4, dtype: int64
Racine 2017 4 121    46355
Name: 4, dtype: int64
Racine 2018 4 121    58403
Name: 4, dtype: int64
Racine 2019 4 120    49378
Name: 4, dtype: int64
Racine 2013 5 120    65964
Name: 5, dtype: int64
Racine 2014 5 120    70351
Name: 5, dtype: int64
Racine 2015 5 121    66647
Name: 5, dtype: int64
Racine 2016 5 121    60591
Name: 5, dtype: int64
Racine 2017 5 121    56819
Name: 5, dtype: int64
Racine 2018 5 121    64633
Name: 5, dtype: int64
Racine 2019 5 120    59411
Name: 5, dtype: int64
Racine 2013 6 120    60852
Name: 6, dtype: int64
Racine 2014 6 120    59149
Name: 6, dtype: int64
Racine 2015 6 121    61683
Name: 6, dtype: int64
Racine 2016 6 121    59595
Name: 6, dtype: int64
Racine 2017 6 121    54727
Name: 6, dtype: int64
Racine 2018 6 121    59872
Name: 6, dtype: int64
Racine 2019 6 120    51950
Name: 6, dtype: int64
Racine 2013 7 120    52885
Name: 7, dtype: int64
Racine 2014 7 120    53571
Name: 7, dtype: int64
Racine 2015 7 121    54091
Name: 7, dtype: int64
Racine 2016 7 121    44261
Name: 7, dtype: int64
Racine 2017 7 121    41805
Name: 7, dtype: int64
Racine 2018 7 121    47970
Name: 7, dtype: int64
Racine 2019 7 120    46272
Name: 7, dtype: int64
Racine 2013 8 120    59476
Name: 8, dtype: int64
Racine 2014 8 120    56494
Name: 8, dtype: int64
Racine 2015 8 121    54422
Name: 8, dtype: int64
Racine 2016 8 121    49155
Name: 8, dtype: int64
Racine 2017 8 121    54872
Name: 8, dtype: int64
Racine 2018 8 121    0
Name: 8, dtype: int64
Racine 2019 8 120    46080
Name: 8, dtype: int64
Racine 2013 9 120    68015
Name: 9, dtype: int64
Racine 2014 9 120    73371
Name: 9, dtype: int64
Racine 2015 9 121    66840
Name: 9, dtype: int64
Racine 2016 9 121    58709
Name: 9, dtype: int64
Racine 2017 9 121    61782
Name: 9, dtype: int64
Racine 2018 9 121    0
Name: 9, dtype: int64
Racine 2019 9 120    60055
Name: 9, dtype: int64
Racine 2013 10 120    76448
Name: 10, dtype: int64
Racine 2014 10 120    77491
Name: 10, dtype: int64
Racine 2015 10 121    72759
Name: 10, dtype: int64
Racine 2016 10 121    61883
Name: 10, dtype: int64
Racine 2017 10 121    69624
Name: 10, dtype: int64
Racine 2018 10 121    0
Name: 10, dtype: int64
Racine 2019 10 120    57628
Name: 10, dtype: int64
Racine 2013 11 120    63992
Name: 11, dtype: int64
Racine 2014 11 120    59959
Name: 11, dtype: int64
Racine 2015 11 121    58218
Name: 11, dtype: int64
Racine 2016 11 121    55297
Name: 11, dtype: int64
Racine 2017 11 121    59721
Name: 11, dtype: int64
Racine 2018 11 121    0
Name: 11, dtype: int64
Racine 2019 11 120    51845
Name: 11, dtype: int64
Racine 2013 12 120    55822
Name: 12, dtype: int64
Racine 2014 12 120    58065
Name: 12, dtype: int64
Racine 2015 12 121    53727
Name: 12, dtype: int64
Racine 2016 12 121    48120
Name: 12, dtype: int64
Racine 2017 12 121    52942
Name: 12, dtype: int64
Racine 2018 12 121    0
Name: 12, dtype: int64
Racine 2019 12 120    45612
Name: 12, dtype: int64
Ridgeland 2013 1 122    31237
Name: 1, dtype: int64
Ridgeland 2014 1 122    27838
Name: 1, dtype: int64
Ridgeland 2015 1 123    29345
Name: 1, dtype: int64
Ridgeland 2016 1 123    29457
Name: 1, dtype: int64
Ridgeland 2017 1 123    31335
Name: 1, dtype: int64
Ridgeland 2018 1 123    31763
Name: 1, dtype: int64
Ridgeland 2019 1 122    28235
Name: 1, dtype: int64
Ridgeland 2013 2 122    29490
Name: 2, dtype: int64
Ridgeland 2014 2 122    28593
Name: 2, dtype: int64
Ridgeland 2015 2 123    28310
Name: 2, dtype: int64
Ridgeland 2016 2 123    30210
Name: 2, dtype: int64
Ridgeland 2017 2 123    29894
Name: 2, dtype: int64
Ridgeland 2018 2 123    29510
Name: 2, dtype: int64
Ridgeland 2019 2 122    28273
Name: 2, dtype: int64
Ridgeland 2013 3 122    30771
Name: 3, dtype: int64
Ridgeland 2014 3 122    31636
Name: 3, dtype: int64
Ridgeland 2015 3 123    33168
Name: 3, dtype: int64
Ridgeland 2016 3 123    33321
Name: 3, dtype: int64
Ridgeland 2017 3 123    34071
Name: 3, dtype: int64
Ridgeland 2018 3 123    33895
Name: 3, dtype: int64
Ridgeland 2019 3 122    31150
Name: 3, dtype: int64
Ridgeland 2013 4 122    32825
Name: 4, dtype: int64
Ridgeland 2014 4 122    33187
Name: 4, dtype: int64
Ridgeland 2015 4 123    32567
Name: 4, dtype: int64
Ridgeland 2016 4 123    29374
Name: 4, dtype: int64
Ridgeland 2017 4 123    31643
Name: 4, dtype: int64
Ridgeland 2018 4 123    32611
Name: 4, dtype: int64
Ridgeland 2019 4 122    32748
Name: 4, dtype: int64
Ridgeland 2013 5 122    34715
Name: 5, dtype: int64
Ridgeland 2014 5 122    33202
Name: 5, dtype: int64
Ridgeland 2015 5 123    31934
Name: 5, dtype: int64
Ridgeland 2016 5 123    30352
Name: 5, dtype: int64
Ridgeland 2017 5 123    35164
Name: 5, dtype: int64
Ridgeland 2018 5 123    35597
Name: 5, dtype: int64
Ridgeland 2019 5 122    34874
Name: 5, dtype: int64
Ridgeland 2013 6 122    33886
Name: 6, dtype: int64
Ridgeland 2014 6 122    34633
Name: 6, dtype: int64
Ridgeland 2015 6 123    34128
Name: 6, dtype: int64
Ridgeland 2016 6 123    35296
Name: 6, dtype: int64
Ridgeland 2017 6 123    37989
Name: 6, dtype: int64
Ridgeland 2018 6 123    35782
Name: 6, dtype: int64
Ridgeland 2019 6 122    33804
Name: 6, dtype: int64
Ridgeland 2013 7 122    36177
Name: 7, dtype: int64
Ridgeland 2014 7 122    35794
Name: 7, dtype: int64
Ridgeland 2015 7 123    36140
Name: 7, dtype: int64
Ridgeland 2016 7 123    34860
Name: 7, dtype: int64
Ridgeland 2017 7 123    35947
Name: 7, dtype: int64
Ridgeland 2018 7 123    35477
Name: 7, dtype: int64
Ridgeland 2019 7 122    34878
Name: 7, dtype: int64
Ridgeland 2013 8 122    36467
Name: 8, dtype: int64
Ridgeland 2014 8 122    34457
Name: 8, dtype: int64
Ridgeland 2015 8 123    33951
Name: 8, dtype: int64
Ridgeland 2016 8 123    34858
Name: 8, dtype: int64
Ridgeland 2017 8 123    39426
Name: 8, dtype: int64
Ridgeland 2018 8 123    0
Name: 8, dtype: int64
Ridgeland 2019 8 122    34748
Name: 8, dtype: int64
Ridgeland 2013 9 122    34683
Name: 9, dtype: int64
Ridgeland 2014 9 122    34699
Name: 9, dtype: int64
Ridgeland 2015 9 123    35549
Name: 9, dtype: int64
Ridgeland 2016 9 123    34162
Name: 9, dtype: int64
Ridgeland 2017 9 123    35381
Name: 9, dtype: int64
Ridgeland 2018 9 123    0
Name: 9, dtype: int64
Ridgeland 2019 9 122    33040
Name: 9, dtype: int64
Ridgeland 2013 10 122    36858
Name: 10, dtype: int64
Ridgeland 2014 10 122    37069
Name: 10, dtype: int64
Ridgeland 2015 10 123    36627
Name: 10, dtype: int64
Ridgeland 2016 10 123    35170
Name: 10, dtype: int64
Ridgeland 2017 10 123    37296
Name: 10, dtype: int64
Ridgeland 2018 10 123    0
Name: 10, dtype: int64
Ridgeland 2019 10 122    35953
Name: 10, dtype: int64
Ridgeland 2013 11 122    31085
Name: 11, dtype: int64
Ridgeland 2014 11 122    29647
Name: 11, dtype: int64
Ridgeland 2015 11 123    31533
Name: 11, dtype: int64
Ridgeland 2016 11 123    33639
Name: 11, dtype: int64
Ridgeland 2017 11 123    33629
Name: 11, dtype: int64
Ridgeland 2018 11 123    0
Name: 11, dtype: int64
Ridgeland 2019 11 122    30101
Name: 11, dtype: int64
Ridgeland 2013 12 122    28754
Name: 12, dtype: int64
Ridgeland 2014 12 122    30544
Name: 12, dtype: int64
Ridgeland 2015 12 123    30147
Name: 12, dtype: int64
Ridgeland 2016 12 123    29245
Name: 12, dtype: int64
Ridgeland 2017 12 123    29395
Name: 12, dtype: int64
Ridgeland 2018 12 123    0
Name: 12, dtype: int64
Ridgeland 2019 12 122    28988
Name: 12, dtype: int64
Rockwell 2013 1 123    45810
Name: 1, dtype: int64
Rockwell 2014 1 123    47450
Name: 1, dtype: int64
Rockwell 2015 1 124    44269
Name: 1, dtype: int64
Rockwell 2016 1 124    44824
Name: 1, dtype: int64
Rockwell 2017 1 124    46232
Name: 1, dtype: int64
Rockwell 2018 1 124    45514
Name: 1, dtype: int64
Rockwell 2019 1 123    41923
Name: 1, dtype: int64
Rockwell 2013 2 123    43242
Name: 2, dtype: int64
Rockwell 2014 2 123    47108
Name: 2, dtype: int64
Rockwell 2015 2 124    43132
Name: 2, dtype: int64
Rockwell 2016 2 124    45432
Name: 2, dtype: int64
Rockwell 2017 2 124    43666
Name: 2, dtype: int64
Rockwell 2018 2 124    42702
Name: 2, dtype: int64
Rockwell 2019 2 123    41519
Name: 2, dtype: int64
Rockwell 2013 3 123    45801
Name: 3, dtype: int64
Rockwell 2014 3 123    51310
Name: 3, dtype: int64
Rockwell 2015 3 124    48776
Name: 3, dtype: int64
Rockwell 2016 3 124    50681
Name: 3, dtype: int64
Rockwell 2017 3 124    50071
Name: 3, dtype: int64
Rockwell 2018 3 124    47219
Name: 3, dtype: int64
Rockwell 2019 3 123    45718
Name: 3, dtype: int64
Rockwell 2013 4 123    47058
Name: 4, dtype: int64
Rockwell 2014 4 123    50186
Name: 4, dtype: int64
Rockwell 2015 4 124    47203
Name: 4, dtype: int64
Rockwell 2016 4 124    47500
Name: 4, dtype: int64
Rockwell 2017 4 124    45607
Name: 4, dtype: int64
Rockwell 2018 4 124    45472
Name: 4, dtype: int64
Rockwell 2019 4 123    44877
Name: 4, dtype: int64
Rockwell 2013 5 123    47137
Name: 5, dtype: int64
Rockwell 2014 5 123    49830
Name: 5, dtype: int64
Rockwell 2015 5 124    46405
Name: 5, dtype: int64
Rockwell 2016 5 124    49047
Name: 5, dtype: int64
Rockwell 2017 5 124    48922
Name: 5, dtype: int64
Rockwell 2018 5 124    48857
Name: 5, dtype: int64
Rockwell 2019 5 123    47950
Name: 5, dtype: int64
Rockwell 2013 6 123    47129
Name: 6, dtype: int64
Rockwell 2014 6 123    48956
Name: 6, dtype: int64
Rockwell 2015 6 124    48869
Name: 6, dtype: int64
Rockwell 2016 6 124    51059
Name: 6, dtype: int64
Rockwell 2017 6 124    49779
Name: 6, dtype: int64
Rockwell 2018 6 124    48009
Name: 6, dtype: int64
Rockwell 2019 6 123    45997
Name: 6, dtype: int64
Rockwell 2013 7 123    49023
Name: 7, dtype: int64
Rockwell 2014 7 123    49512
Name: 7, dtype: int64
Rockwell 2015 7 124    49485
Name: 7, dtype: int64
Rockwell 2016 7 124    48156
Name: 7, dtype: int64
Rockwell 2017 7 124    43529
Name: 7, dtype: int64
Rockwell 2018 7 124    0
Name: 7, dtype: int64
Rockwell 2019 7 123    46183
Name: 7, dtype: int64
Rockwell 2013 8 123    49388
Name: 8, dtype: int64
Rockwell 2014 8 123    45534
Name: 8, dtype: int64
Rockwell 2015 8 124    48044
Name: 8, dtype: int64
Rockwell 2016 8 124    50751
Name: 8, dtype: int64
Rockwell 2017 8 124    49297
Name: 8, dtype: int64
Rockwell 2018 8 124    0
Name: 8, dtype: int64
Rockwell 2019 8 123    47385
Name: 8, dtype: int64
Rockwell 2013 9 123    47946
Name: 9, dtype: int64
Rockwell 2014 9 123    48161
Name: 9, dtype: int64
Rockwell 2015 9 124    48462
Name: 9, dtype: int64
Rockwell 2016 9 124    49197
Name: 9, dtype: int64
Rockwell 2017 9 124    47118
Name: 9, dtype: int64
Rockwell 2018 9 124    0
Name: 9, dtype: int64
Rockwell 2019 9 123    46460
Name: 9, dtype: int64
Rockwell 2013 10 123    53613
Name: 10, dtype: int64
Rockwell 2014 10 123    50696
Name: 10, dtype: int64
Rockwell 2015 10 124    49996
Name: 10, dtype: int64
Rockwell 2016 10 124    51514
Name: 10, dtype: int64
Rockwell 2017 10 124    50062
Name: 10, dtype: int64
Rockwell 2018 10 124    0
Name: 10, dtype: int64
Rockwell 2019 10 123    49430
Name: 10, dtype: int64
Rockwell 2013 11 123    46787
Name: 11, dtype: int64
Rockwell 2014 11 123    42565
Name: 11, dtype: int64
Rockwell 2015 11 124    44378
Name: 11, dtype: int64
Rockwell 2016 11 124    47476
Name: 11, dtype: int64
Rockwell 2017 11 124    45654
Name: 11, dtype: int64
Rockwell 2018 11 124    0
Name: 11, dtype: int64
Rockwell 2019 11 123    35019
Name: 11, dtype: int64
Rockwell 2013 12 123    45628
Name: 12, dtype: int64
Rockwell 2014 12 123    44441
Name: 12, dtype: int64
Rockwell 2015 12 124    45530
Name: 12, dtype: int64
Rockwell 2016 12 124    43002
Name: 12, dtype: int64
Rockwell 2017 12 124    41753
Name: 12, dtype: int64
Rockwell 2018 12 124    0
Name: 12, dtype: int64
Rockwell 2019 12 123    40210
Name: 12, dtype: int64
Roosevelt 2013 1 124    266231
Name: 1, dtype: int64
Roosevelt 2014 1 124    264324
Name: 1, dtype: int64
Roosevelt 2015 1 125    272865
Name: 1, dtype: int64
Roosevelt 2016 1 125    271732
Name: 1, dtype: int64
Roosevelt 2017 1 125    269049
Name: 1, dtype: int64
Roosevelt 2018 1 125    258148
Name: 1, dtype: int64
Roosevelt 2019 1 124    236071
Name: 1, dtype: int64
Roosevelt 2013 2 124    266758
Name: 2, dtype: int64
Roosevelt 2014 2 124    281324
Name: 2, dtype: int64
Roosevelt 2015 2 125    263400
Name: 2, dtype: int64
Roosevelt 2016 2 125    284436
Name: 2, dtype: int64
Roosevelt 2017 2 125    272678
Name: 2, dtype: int64
Roosevelt 2018 2 125    253276
Name: 2, dtype: int64
Roosevelt 2019 2 124    245335
Name: 2, dtype: int64
Roosevelt 2013 3 124    300681
Name: 3, dtype: int64
Roosevelt 2014 3 124    331374
Name: 3, dtype: int64
Roosevelt 2015 3 125    300694
Name: 3, dtype: int64
Roosevelt 2016 3 125    309990
Name: 3, dtype: int64
Roosevelt 2017 3 125    299771
Name: 3, dtype: int64
Roosevelt 2018 3 125    292374
Name: 3, dtype: int64
Roosevelt 2019 3 124    271607
Name: 3, dtype: int64
Roosevelt 2013 4 124    303597
Name: 4, dtype: int64
Roosevelt 2014 4 124    330491
Name: 4, dtype: int64
Roosevelt 2015 4 125    303628
Name: 4, dtype: int64
Roosevelt 2016 4 125    308949
Name: 4, dtype: int64
Roosevelt 2017 4 125    294749
Name: 4, dtype: int64
Roosevelt 2018 4 125    279769
Name: 4, dtype: int64
Roosevelt 2019 4 124    275859
Name: 4, dtype: int64
Roosevelt 2013 5 124    326360
Name: 5, dtype: int64
Roosevelt 2014 5 124    363020
Name: 5, dtype: int64
Roosevelt 2015 5 125    312505
Name: 5, dtype: int64
Roosevelt 2016 5 125    318319
Name: 5, dtype: int64
Roosevelt 2017 5 125    304299
Name: 5, dtype: int64
Roosevelt 2018 5 125    300007
Name: 5, dtype: int64
Roosevelt 2019 5 124    297662
Name: 5, dtype: int64
Roosevelt 2013 6 124    358141
Name: 6, dtype: int64
Roosevelt 2014 6 124    336474
Name: 6, dtype: int64
Roosevelt 2015 6 125    345471
Name: 6, dtype: int64
Roosevelt 2016 6 125    341175
Name: 6, dtype: int64
Roosevelt 2017 6 125    337642
Name: 6, dtype: int64
Roosevelt 2018 6 125    312468
Name: 6, dtype: int64
Roosevelt 2019 6 124    309482
Name: 6, dtype: int64
Roosevelt 2013 7 124    400958
Name: 7, dtype: int64
Roosevelt 2014 7 124    356811
Name: 7, dtype: int64
Roosevelt 2015 7 125    396284
Name: 7, dtype: int64
Roosevelt 2016 7 125    361811
Name: 7, dtype: int64
Roosevelt 2017 7 125    333563
Name: 7, dtype: int64
Roosevelt 2018 7 125    318333
Name: 7, dtype: int64
Roosevelt 2019 7 124    315298
Name: 7, dtype: int64
Roosevelt 2013 8 124    380869
Name: 8, dtype: int64
Roosevelt 2014 8 124    348317
Name: 8, dtype: int64
Roosevelt 2015 8 125    329627
Name: 8, dtype: int64
Roosevelt 2016 8 125    333534
Name: 8, dtype: int64
Roosevelt 2017 8 125    374152
Name: 8, dtype: int64
Roosevelt 2018 8 125    0
Name: 8, dtype: int64
Roosevelt 2019 8 124    318945
Name: 8, dtype: int64
Roosevelt 2013 9 124    395352
Name: 9, dtype: int64
Roosevelt 2014 9 124    339735
Name: 9, dtype: int64
Roosevelt 2015 9 125    342650
Name: 9, dtype: int64
Roosevelt 2016 9 125    325355
Name: 9, dtype: int64
Roosevelt 2017 9 125    348596
Name: 9, dtype: int64
Roosevelt 2018 9 125    0
Name: 9, dtype: int64
Roosevelt 2019 9 124    307886
Name: 9, dtype: int64
Roosevelt 2013 10 124    382097
Name: 10, dtype: int64
Roosevelt 2014 10 124    363052
Name: 10, dtype: int64
Roosevelt 2015 10 125    350964
Name: 10, dtype: int64
Roosevelt 2016 10 125    352099
Name: 10, dtype: int64
Roosevelt 2017 10 125    342487
Name: 10, dtype: int64
Roosevelt 2018 10 125    0
Name: 10, dtype: int64
Roosevelt 2019 10 124    342321
Name: 10, dtype: int64
Roosevelt 2013 11 124    323457
Name: 11, dtype: int64
Roosevelt 2014 11 124    320786
Name: 11, dtype: int64

Roosevelt 2015 11 125    304700
Name: 11, dtype: int64
Roosevelt 2016 11 125    320064
Name: 11, dtype: int64
Roosevelt 2017 11 125    294385
Name: 11, dtype: int64
Roosevelt 2018 11 125    0
Name: 11, dtype: int64
Roosevelt 2019 11 124    284729
Name: 11, dtype: int64
Roosevelt 2013 12 124    287584
Name: 12, dtype: int64
Roosevelt 2014 12 124    306073
Name: 12, dtype: int64
Roosevelt 2015 12 125    293229
Name: 12, dtype: int64
Roosevelt 2016 12 125    278883
Name: 12, dtype: int64
Roosevelt 2017 12 125    264451
Name: 12, dtype: int64
Roosevelt 2018 12 125    0
Name: 12, dtype: int64
Roosevelt 2019 12 124    261715
Name: 12, dtype: int64
Rosemont 2013 1 125    124126
Name: 1, dtype: int64
Rosemont 2014 1 125    131311
Name: 1, dtype: int64
Rosemont 2015 1 126    140496
Name: 1, dtype: int64
Rosemont 2016 1 126    141914
Name: 1, dtype: int64
Rosemont 2017 1 126    144930
Name: 1, dtype: int64
Rosemont 2018 1 126    143404
Name: 1, dtype: int64
Rosemont 2019 1 125    132545
Name: 1, dtype: int64
Rosemont 2013 2 125    118419
Name: 2, dtype: int64
Rosemont 2014 2 125    131341
Name: 2, dtype: int64
Rosemont 2015 2 126    133584
Name: 2, dtype: int64
Rosemont 2016 2 126    144184
Name: 2, dtype: int64
Rosemont 2017 2 126    137525
Name: 2, dtype: int64
Rosemont 2018 2 126    138756
Name: 2, dtype: int64
Rosemont 2019 2 125    133447
Name: 2, dtype: int64
Rosemont 2013 3 125    136826
Name: 3, dtype: int64
Rosemont 2014 3 125    199598
Name: 3, dtype: int64
Rosemont 2015 3 126    162063
Name: 3, dtype: int64
Rosemont 2016 3 126    164911
Name: 3, dtype: int64
Rosemont 2017 3 126    160195
Name: 3, dtype: int64
Rosemont 2018 3 126    166657
Name: 3, dtype: int64
Rosemont 2019 3 125    152995
Name: 3, dtype: int64
Rosemont 2013 4 125    142313
Name: 4, dtype: int64
Rosemont 2014 4 125    160233
Name: 4, dtype: int64
Rosemont 2015 4 126    167128
Name: 4, dtype: int64
Rosemont 2016 4 126    162891
Name: 4, dtype: int64
Rosemont 2017 4 126    155539
Name: 4, dtype: int64
Rosemont 2018 4 126    163152
Name: 4, dtype: int64
Rosemont 2019 4 125    157036
Name: 4, dtype: int64
Rosemont 2013 5 125    158376
Name: 5, dtype: int64
Rosemont 2014 5 125    178322
Name: 5, dtype: int64
Rosemont 2015 5 126    183629
Name: 5, dtype: int64
Rosemont 2016 5 126    179602
Name: 5, dtype: int64
Rosemont 2017 5 126    178532
Name: 5, dtype: int64
Rosemont 2018 5 126    181002
Name: 5, dtype: int64
Rosemont 2019 5 125    168484
Name: 5, dtype: int64
Rosemont 2013 6 125    168330
Name: 6, dtype: int64
Rosemont 2014 6 125    184479
Name: 6, dtype: int64
Rosemont 2015 6 126    193841
Name: 6, dtype: int64
Rosemont 2016 6 126    191826
Name: 6, dtype: int64
Rosemont 2017 6 126    191899
Name: 6, dtype: int64
Rosemont 2018 6 126    185819
Name: 6, dtype: int64
Rosemont 2019 6 125    171350
Name: 6, dtype: int64
Rosemont 2013 7 125    181790
Name: 7, dtype: int64
Rosemont 2014 7 125    202214
Name: 7, dtype: int64
Rosemont 2015 7 126    214792
Name: 7, dtype: int64
Rosemont 2016 7 126    193083
Name: 7, dtype: int64
Rosemont 2017 7 126    185910
Name: 7, dtype: int64
Rosemont 2018 7 126    191128
Name: 7, dtype: int64
Rosemont 2019 7 125    172121
Name: 7, dtype: int64
Rosemont 2013 8 125    199041
Name: 8, dtype: int64
Rosemont 2014 8 125    197799
Name: 8, dtype: int64
Rosemont 2015 8 126    201538
Name: 8, dtype: int64
Rosemont 2016 8 126    187455
Name: 8, dtype: int64
Rosemont 2017 8 126    195976
Name: 8, dtype: int64
Rosemont 2018 8 126    0
Name: 8, dtype: int64
Rosemont 2019 8 125    177599
Name: 8, dtype: int64
Rosemont 2013 9 125    175083
Name: 9, dtype: int64
Rosemont 2014 9 125    189267
Name: 9, dtype: int64
Rosemont 2015 9 126    190605
Name: 9, dtype: int64
Rosemont 2016 9 126    181386
Name: 9, dtype: int64
Rosemont 2017 9 126    180436
Name: 9, dtype: int64
Rosemont 2018 9 126    0
Name: 9, dtype: int64
Rosemont 2019 9 125    188010
Name: 9, dtype: int64
Rosemont 2013 10 125    187843
Name: 10, dtype: int64
Rosemont 2014 10 125    195711
Name: 10, dtype: int64
Rosemont 2015 10 126    194602
Name: 10, dtype: int64
Rosemont 2016 10 126    191148
Name: 10, dtype: int64
Rosemont 2017 10 126    185541
Name: 10, dtype: int64
Rosemont 2018 10 126    0
Name: 10, dtype: int64
Rosemont 2019 10 125    225778
Name: 10, dtype: int64
Rosemont 2013 11 125    158351
Name: 11, dtype: int64
Rosemont 2014 11 125    160296
Name: 11, dtype: int64
Rosemont 2015 11 126    163488
Name: 11, dtype: int64
Rosemont 2016 11 126    176347
Name: 11, dtype: int64
Rosemont 2017 11 126    167120
Name: 11, dtype: int64
Rosemont 2018 11 126    0
Name: 11, dtype: int64
Rosemont 2019 11 125    147731
Name: 11, dtype: int64
Rosemont 2013 12 125    143225
Name: 12, dtype: int64
Rosemont 2014 12 125    160406
Name: 12, dtype: int64
Rosemont 2015 12 126    160887
Name: 12, dtype: int64
Rosemont 2016 12 126    147955
Name: 12, dtype: int64
Rosemont 2017 12 126    147815
Name: 12, dtype: int64
Rosemont 2018 12 126    0
Name: 12, dtype: int64
Rosemont 2019 12 125    141177
Name: 12, dtype: int64
Sedgwick 2013 1 126    100858
Name: 1, dtype: int64
Sedgwick 2014 1 126    91711
Name: 1, dtype: int64
Sedgwick 2015 1 127    94448
Name: 1, dtype: int64
Sedgwick 2016 1 127    93361
Name: 1, dtype: int64
Sedgwick 2017 1 127    93236
Name: 1, dtype: int64
Sedgwick 2018 1 127    89715
Name: 1, dtype: int64
Sedgwick 2019 1 126    82559
Name: 1, dtype: int64
Sedgwick 2013 2 126    97270
Name: 2, dtype: int64
Sedgwick 2014 2 126    91140
Name: 2, dtype: int64
Sedgwick 2015 2 127    91619
Name: 2, dtype: int64
Sedgwick 2016 2 127    93341
Name: 2, dtype: int64
Sedgwick 2017 2 127    88862
Name: 2, dtype: int64
Sedgwick 2018 2 127    83948
Name: 2, dtype: int64
Sedgwick 2019 2 126    82356
Name: 2, dtype: int64
Sedgwick 2013 3 126    86886
Name: 3, dtype: int64
Sedgwick 2014 3 126    104738
Name: 3, dtype: int64
Sedgwick 2015 3 127    100602
Name: 3, dtype: int64
Sedgwick 2016 3 127    104612
Name: 3, dtype: int64
Sedgwick 2017 3 127    100297
Name: 3, dtype: int64
Sedgwick 2018 3 127    97719
Name: 3, dtype: int64
Sedgwick 2019 3 126    92119
Name: 3, dtype: int64
Sedgwick 2013 4 126    99370
Name: 4, dtype: int64
Sedgwick 2014 4 126    101797
Name: 4, dtype: int64
Sedgwick 2015 4 127    89129
Name: 4, dtype: int64
Sedgwick 2016 4 127    100187
Name: 4, dtype: int64
Sedgwick 2017 4 127    93790
Name: 4, dtype: int64
Sedgwick 2018 4 127    92340
Name: 4, dtype: int64
Sedgwick 2019 4 126    92025
Name: 4, dtype: int64
Sedgwick 2013 5 126    98548
Name: 5, dtype: int64
Sedgwick 2014 5 126    108260
Name: 5, dtype: int64
Sedgwick 2015 5 127    82768
Name: 5, dtype: int64
Sedgwick 2016 5 127    108577
Name: 5, dtype: int64
Sedgwick 2017 5 127    104520
Name: 5, dtype: int64
Sedgwick 2018 5 127    103689
Name: 5, dtype: int64
Sedgwick 2019 5 126    102201
Name: 5, dtype: int64
Sedgwick 2013 6 126    121305
Name: 6, dtype: int64
Sedgwick 2014 6 126    118277
Name: 6, dtype: int64
Sedgwick 2015 6 127    109286
Name: 6, dtype: int64
Sedgwick 2016 6 127    122643
Name: 6, dtype: int64
Sedgwick 2017 6 127    119214
Name: 6, dtype: int64
Sedgwick 2018 6 127    107546
Name: 6, dtype: int64
Sedgwick 2019 6 126    107464
Name: 6, dtype: int64
Sedgwick 2013 7 126    120060
Name: 7, dtype: int64
Sedgwick 2014 7 126    114182
Name: 7, dtype: int64
Sedgwick 2015 7 127    104926
Name: 7, dtype: int64
Sedgwick 2016 7 127    112818
Name: 7, dtype: int64
Sedgwick 2017 7 127    107031
Name: 7, dtype: int64
Sedgwick 2018 7 127    0
Name: 7, dtype: int64
Sedgwick 2019 7 126    106249
Name: 7, dtype: int64
Sedgwick 2013 8 126    119878
Name: 8, dtype: int64
Sedgwick 2014 8 126    111722
Name: 8, dtype: int64
Sedgwick 2015 8 127    94853
Name: 8, dtype: int64
Sedgwick 2016 8 127    115977
Name: 8, dtype: int64
Sedgwick 2017 8 127    114468
Name: 8, dtype: int64
Sedgwick 2018 8 127    0
Name: 8, dtype: int64
Sedgwick 2019 8 126    110434
Name: 8, dtype: int64
Sedgwick 2013 9 126    111567
Name: 9, dtype: int64
Sedgwick 2014 9 126    106816
Name: 9, dtype: int64
Sedgwick 2015 9 127    85984
Name: 9, dtype: int64
Sedgwick 2016 9 127    106216
Name: 9, dtype: int64
Sedgwick 2017 9 127    103582
Name: 9, dtype: int64
Sedgwick 2018 9 127    0
Name: 9, dtype: int64
Sedgwick 2019 9 126    103153
Name: 9, dtype: int64
Sedgwick 2013 10 126    119933
Name: 10, dtype: int64
Sedgwick 2014 10 126    115604
Name: 10, dtype: int64
Sedgwick 2015 10 127    112161
Name: 10, dtype: int64
Sedgwick 2016 10 127    115003
Name: 10, dtype: int64
Sedgwick 2017 10 127    110377
Name: 10, dtype: int64
Sedgwick 2018 10 127    0
Name: 10, dtype: int64
Sedgwick 2019 10 126    111915
Name: 10, dtype: int64
Sedgwick 2013 11 126    98979
Name: 11, dtype: int64
Sedgwick 2014 11 126    90460
Name: 11, dtype: int64
Sedgwick 2015 11 127    93821
Name: 11, dtype: int64
Sedgwick 2016 11 127    97256
Name: 11, dtype: int64
Sedgwick 2017 11 127    95047
Name: 11, dtype: int64
Sedgwick 2018 11 127    0
Name: 11, dtype: int64
Sedgwick 2019 11 126    87776
Name: 11, dtype: int64
Sedgwick 2013 12 126    89226
Name: 12, dtype: int64
Sedgwick 2014 12 126    93102
Name: 12, dtype: int64
Sedgwick 2015 12 127    92067
Name: 12, dtype: int64
Sedgwick 2016 12 127    84228
Name: 12, dtype: int64
Sedgwick 2017 12 127    83818
Name: 12, dtype: int64
Sedgwick 2018 12 127    0
Name: 12, dtype: int64
Sedgwick 2019 12 126    82006
Name: 12, dtype: int64
Sheridan 2013 1 127    142732
Name: 1, dtype: int64
Sheridan 2014 1 127    140571
Name: 1, dtype: int64
Sheridan 2015 1 128    140700
Name: 1, dtype: int64
Sheridan 2016 1 128    144184
Name: 1, dtype: int64
Sheridan 2017 1 128    138367
Name: 1, dtype: int64
Sheridan 2018 1 128    125375
Name: 1, dtype: int64
Sheridan 2019 1 127    113423
Name: 1, dtype: int64
Sheridan 2013 2 127    134845
Name: 2, dtype: int64
Sheridan 2014 2 127    140727
Name: 2, dtype: int64
Sheridan 2015 2 128    134670
Name: 2, dtype: int64
Sheridan 2016 2 128    146223
Name: 2, dtype: int64
Sheridan 2017 2 128    132636
Name: 2, dtype: int64
Sheridan 2018 2 128    118804
Name: 2, dtype: int64
Sheridan 2019 2 127    115003
Name: 2, dtype: int64
Sheridan 2013 3 127    145326
Name: 3, dtype: int64
Sheridan 2014 3 127    156966
Name: 3, dtype: int64
Sheridan 2015 3 128    153134
Name: 3, dtype: int64
Sheridan 2016 3 128    157129
Name: 3, dtype: int64
Sheridan 2017 3 128    148710
Name: 3, dtype: int64
Sheridan 2018 3 128    133718
Name: 3, dtype: int64
Sheridan 2019 3 127    130379
Name: 3, dtype: int64
Sheridan 2013 4 127    148872
Name: 4, dtype: int64
Sheridan 2014 4 127    155409
Name: 4, dtype: int64
Sheridan 2015 4 128    151473
Name: 4, dtype: int64
Sheridan 2016 4 128    154595
Name: 4, dtype: int64
Sheridan 2017 4 128    141818
Name: 4, dtype: int64
Sheridan 2018 4 128    128089
Name: 4, dtype: int64
Sheridan 2019 4 127    124814
Name: 4, dtype: int64
Sheridan 2013 5 127    150103
Name: 5, dtype: int64
Sheridan 2014 5 127    157583
Name: 5, dtype: int64
Sheridan 2015 5 128    154521
Name: 5, dtype: int64
Sheridan 2016 5 128    157543
Name: 5, dtype: int64
Sheridan 2017 5 128    151459
Name: 5, dtype: int64
Sheridan 2018 5 128    138233
Name: 5, dtype: int64
Sheridan 2019 5 127    130874
Name: 5, dtype: int64
Sheridan 2013 6 127    152742
Name: 6, dtype: int64
Sheridan 2014 6 127    155505
Name: 6, dtype: int64
Sheridan 2015 6 128    165734
Name: 6, dtype: int64
Sheridan 2016 6 128    165173
Name: 6, dtype: int64
Sheridan 2017 6 128    159522
Name: 6, dtype: int64
Sheridan 2018 6 128    139454
Name: 6, dtype: int64
Sheridan 2019 6 127    135411
Name: 6, dtype: int64
Sheridan 2013 7 127    152973
Name: 7, dtype: int64
Sheridan 2014 7 127    152790
Name: 7, dtype: int64
Sheridan 2015 7 128    160613
Name: 7, dtype: int64
Sheridan 2016 7 128    156365
Name: 7, dtype: int64
Sheridan 2017 7 128    147068
Name: 7, dtype: int64
Sheridan 2018 7 128    131503
Name: 7, dtype: int64
Sheridan 2019 7 127    124307
Name: 7, dtype: int64
Sheridan 2013 8 127    157052
Name: 8, dtype: int64
Sheridan 2014 8 127    152289
Name: 8, dtype: int64
Sheridan 2015 8 128    156296
Name: 8, dtype: int64
Sheridan 2016 8 128    157241
Name: 8, dtype: int64
Sheridan 2017 8 128    153230
Name: 8, dtype: int64
Sheridan 2018 8 128    0
Name: 8, dtype: int64
Sheridan 2019 8 127    130909
Name: 8, dtype: int64
Sheridan 2013 9 127    157806
Name: 9, dtype: int64
Sheridan 2014 9 127    160262
Name: 9, dtype: int64
Sheridan 2015 9 128    165070
Name: 9, dtype: int64
Sheridan 2016 9 128    161206
Name: 9, dtype: int64
Sheridan 2017 9 128    150643
Name: 9, dtype: int64
Sheridan 2018 9 128    0
Name: 9, dtype: int64
Sheridan 2019 9 127    132216
Name: 9, dtype: int64
Sheridan 2013 10 127    171058
Name: 10, dtype: int64
Sheridan 2014 10 127    169974
Name: 10, dtype: int64
Sheridan 2015 10 128    175048
Name: 10, dtype: int64
Sheridan 2016 10 128    181544
Name: 10, dtype: int64
Sheridan 2017 10 128    156729
Name: 10, dtype: int64
Sheridan 2018 10 128    0
Name: 10, dtype: int64
Sheridan 2019 10 127    142046
Name: 10, dtype: int64
Sheridan 2013 11 127    150196
Name: 11, dtype: int64
Sheridan 2014 11 127    145115
Name: 11, dtype: int64
Sheridan 2015 11 128    150242
Name: 11, dtype: int64
Sheridan 2016 11 128    155162
Name: 11, dtype: int64
Sheridan 2017 11 128    131993
Name: 11, dtype: int64
Sheridan 2018 11 128    0
Name: 11, dtype: int64
Sheridan 2019 11 127    119028
Name: 11, dtype: int64
Sheridan 2013 12 127    132748
Name: 12, dtype: int64
Sheridan 2014 12 127    136232
Name: 12, dtype: int64
Sheridan 2015 12 128    139175
Name: 12, dtype: int64
Sheridan 2016 12 128    126115
Name: 12, dtype: int64
Sheridan 2017 12 128    114061
Name: 12, dtype: int64
Sheridan 2018 12 128    0
Name: 12, dtype: int64
Sheridan 2019 12 127    105454
Name: 12, dtype: int64

South Boulevard 2013 1 128    20183
Name: 1, dtype: int64
South Boulevard 2014 1 128    19801
Name: 1, dtype: int64
South Boulevard 2015 1 129    20196
Name: 1, dtype: int64
South Boulevard 2016 1 129    18900
Name: 1, dtype: int64
South Boulevard 2017 1 129    19445
Name: 1, dtype: int64
South Boulevard 2018 1 129    18530
Name: 1, dtype: int64
South Boulevard 2019 1 128    17196
Name: 1, dtype: int64
South Boulevard 2013 2 128    18985
Name: 2, dtype: int64
South Boulevard 2014 2 128    19757
Name: 2, dtype: int64
South Boulevard 2015 2 129    18948
Name: 2, dtype: int64
South Boulevard 2016 2 129    19027
Name: 2, dtype: int64
South Boulevard 2017 2 129    18124
Name: 2, dtype: int64
South Boulevard 2018 2 129    17948
Name: 2, dtype: int64
South Boulevard 2019 2 128    17325
Name: 2, dtype: int64
South Boulevard 2013 3 128    19429
Name: 3, dtype: int64
South Boulevard 2014 3 128    21892
Name: 3, dtype: int64
South Boulevard 2015 3 129    21468
Name: 3, dtype: int64
South Boulevard 2016 3 129    20984
Name: 3, dtype: int64
South Boulevard 2017 3 129    20132
Name: 3, dtype: int64
South Boulevard 2018 3 129    20099
Name: 3, dtype: int64
South Boulevard 2019 3 128    18564
Name: 3, dtype: int64
South Boulevard 2013 4 128    20999
Name: 4, dtype: int64
South Boulevard 2014 4 128    22667
Name: 4, dtype: int64
South Boulevard 2015 4 129    21647
Name: 4, dtype: int64
South Boulevard 2016 4 129    20327
Name: 4, dtype: int64
South Boulevard 2017 4 129    19071
Name: 4, dtype: int64
South Boulevard 2018 4 129    19378
Name: 4, dtype: int64
South Boulevard 2019 4 128    19589
Name: 4, dtype: int64
South Boulevard 2013 5 128    22053
Name: 5, dtype: int64
South Boulevard 2014 5 128    22609
Name: 5, dtype: int64
South Boulevard 2015 5 129    21210
Name: 5, dtype: int64
South Boulevard 2016 5 129    20827
Name: 5, dtype: int64
South Boulevard 2017 5 129    20681
Name: 5, dtype: int64
South Boulevard 2018 5 129    20073
Name: 5, dtype: int64
South Boulevard 2019 5 128    19886
Name: 5, dtype: int64
South Boulevard 2013 6 128    21753
Name: 6, dtype: int64
South Boulevard 2014 6 128    22657
Name: 6, dtype: int64
South Boulevard 2015 6 129    23122
Name: 6, dtype: int64
South Boulevard 2016 6 129    22069
Name: 6, dtype: int64
South Boulevard 2017 6 129    21172
Name: 6, dtype: int64
South Boulevard 2018 6 129    20611
Name: 6, dtype: int64
South Boulevard 2019 6 128    19554
Name: 6, dtype: int64
South Boulevard 2013 7 128    22227
Name: 7, dtype: int64
South Boulevard 2014 7 128    22584
Name: 7, dtype: int64
South Boulevard 2015 7 129    23732
Name: 7, dtype: int64
South Boulevard 2016 7 129    21348
Name: 7, dtype: int64
South Boulevard 2017 7 129    19771
Name: 7, dtype: int64
South Boulevard 2018 7 129    20535
Name: 7, dtype: int64
South Boulevard 2019 7 128    20917
Name: 7, dtype: int64
South Boulevard 2013 8 128    21409
Name: 8, dtype: int64
South Boulevard 2014 8 128    22066
Name: 8, dtype: int64
South Boulevard 2015 8 129    21872
Name: 8, dtype: int64
South Boulevard 2016 8 129    21391
Name: 8, dtype: int64
South Boulevard 2017 8 129    21141
Name: 8, dtype: int64
South Boulevard 2018 8 129    0
Name: 8, dtype: int64
South Boulevard 2019 8 128    21198
Name: 8, dtype: int64
South Boulevard 2013 9 128    20764
Name: 9, dtype: int64
South Boulevard 2014 9 128    21976
Name: 9, dtype: int64
South Boulevard 2015 9 129    21666
Name: 9, dtype: int64
South Boulevard 2016 9 129    21025
Name: 9, dtype: int64
South Boulevard 2017 9 129    19630
Name: 9, dtype: int64
South Boulevard 2018 9 129    0
Name: 9, dtype: int64
South Boulevard 2019 9 128    19993
Name: 9, dtype: int64
South Boulevard 2013 10 128    22983
Name: 10, dtype: int64
South Boulevard 2014 10 128    23138
Name: 10, dtype: int64
South Boulevard 2015 10 129    22560
Name: 10, dtype: int64
South Boulevard 2016 10 129    21435
Name: 10, dtype: int64
South Boulevard 2017 10 129    20792
Name: 10, dtype: int64
South Boulevard 2018 10 129    0
Name: 10, dtype: int64
South Boulevard 2019 10 128    21651
Name: 10, dtype: int64
South Boulevard 2013 11 128    20217
Name: 11, dtype: int64
South Boulevard 2014 11 128    19745
Name: 11, dtype: int64
South Boulevard 2015 11 129    19411
Name: 11, dtype: int64
South Boulevard 2016 11 129    20128
Name: 11, dtype: int64
South Boulevard 2017 11 129    18332
Name: 11, dtype: int64
South Boulevard 2018 11 129    0
Name: 11, dtype: int64
South Boulevard 2019 11 128    18832
Name: 11, dtype: int64
South Boulevard 2013 12 128    18884
Name: 12, dtype: int64
South Boulevard 2014 12 128    20497
Name: 12, dtype: int64
South Boulevard 2015 12 129    18786
Name: 12, dtype: int64
South Boulevard 2016 12 129    17468
Name: 12, dtype: int64
South Boulevard 2017 12 129    16754
Name: 12, dtype: int64
South Boulevard 2018 12 129    0
Name: 12, dtype: int64
South Boulevard 2019 12 128    18107
Name: 12, dtype: int64
Southport 2013 1 129    83129
Name: 1, dtype: int64
Southport 2014 1 129    83101
Name: 1, dtype: int64
Southport 2015 1 130    82887
Name: 1, dtype: int64
Southport 2016 1 130    84988
Name: 1, dtype: int64
Southport 2017 1 130    88934
Name: 1, dtype: int64
Southport 2018 1 130    91274
Name: 1, dtype: int64
Southport 2019 1 129    82007
Name: 1, dtype: int64
Southport 2013 2 129    79449
Name: 2, dtype: int64
Southport 2014 2 129    80662
Name: 2, dtype: int64
Southport 2015 2 130    79524
Name: 2, dtype: int64
Southport 2016 2 130    84145
Name: 2, dtype: int64
Southport 2017 2 130    83258
Name: 2, dtype: int64
Southport 2018 2 130    84097
Name: 2, dtype: int64
Southport 2019 2 129    80728
Name: 2, dtype: int64
Southport 2013 3 129    82160
Name: 3, dtype: int64
Southport 2014 3 129    91815
Name: 3, dtype: int64
Southport 2015 3 130    88743
Name: 3, dtype: int64
Southport 2016 3 130    93057
Name: 3, dtype: int64
Southport 2017 3 130    94334
Name: 3, dtype: int64
Southport 2018 3 130    95607
Name: 3, dtype: int64
Southport 2019 3 129    91958
Name: 3, dtype: int64
Southport 2013 4 129    84883
Name: 4, dtype: int64
Southport 2014 4 129    89254
Name: 4, dtype: int64
Southport 2015 4 130    85009
Name: 4, dtype: int64
Southport 2016 4 130    90103
Name: 4, dtype: int64
Southport 2017 4 130    91326
Name: 4, dtype: int64
Southport 2018 4 130    91487
Name: 4, dtype: int64
Southport 2019 4 129    91278
Name: 4, dtype: int64
Southport 2013 5 129    85545
Name: 5, dtype: int64
Southport 2014 5 129    89795
Name: 5, dtype: int64
Southport 2015 5 130    84061
Name: 5, dtype: int64
Southport 2016 5 130    92821
Name: 5, dtype: int64
Southport 2017 5 130    96403
Name: 5, dtype: int64
Southport 2018 5 130    98385
Name: 5, dtype: int64
Southport 2019 5 129    96144
Name: 5, dtype: int64
Southport 2013 6 129    91194
Name: 6, dtype: int64
Southport 2014 6 129    94011
Name: 6, dtype: int64
Southport 2015 6 130    89882
Name: 6, dtype: int64
Southport 2016 6 130    99131
Name: 6, dtype: int64
Southport 2017 6 130    102200
Name: 6, dtype: int64
Southport 2018 6 130    97630
Name: 6, dtype: int64
Southport 2019 6 129    96554
Name: 6, dtype: int64
Southport 2013 7 129    92540
Name: 7, dtype: int64
Southport 2014 7 129    94935
Name: 7, dtype: int64
Southport 2015 7 130    92906
Name: 7, dtype: int64
Southport 2016 7 130    96295
Name: 7, dtype: int64
Southport 2017 7 130    97351
Name: 7, dtype: int64
Southport 2018 7 130    0
Name: 7, dtype: int64
Southport 2019 7 129    94985
Name: 7, dtype: int64
Southport 2013 8 129    94187
Name: 8, dtype: int64
Southport 2014 8 129    90333
Name: 8, dtype: int64
Southport 2015 8 130    88805
Name: 8, dtype: int64
Southport 2016 8 130    97766
Name: 8, dtype: int64
Southport 2017 8 130    103311
Name: 8, dtype: int64
Southport 2018 8 130    0
Name: 8, dtype: int64
Southport 2019 8 129    97552
Name: 8, dtype: int64
Southport 2013 9 129    90537
Name: 9, dtype: int64
Southport 2014 9 129    93334
Name: 9, dtype: int64
Southport 2015 9 130    92517
Name: 9, dtype: int64
Southport 2016 9 130    100838
Name: 9, dtype: int64
Southport 2017 9 130    104591
Name: 9, dtype: int64
Southport 2018 9 130    0
Name: 9, dtype: int64
Southport 2019 9 129    94984
Name: 9, dtype: int64
Southport 2013 10 129    96952
Name: 10, dtype: int64
Southport 2014 10 129    95693
Name: 10, dtype: int64
Southport 2015 10 130    96967
Name: 10, dtype: int64
Southport 2016 10 130    109624
Name: 10, dtype: int64
Southport 2017 10 130    105203
Name: 10, dtype: int64
Southport 2018 10 130    0
Name: 10, dtype: int64
Southport 2019 10 129    99949
Name: 10, dtype: int64
Southport 2013 11 129    84706
Name: 11, dtype: int64
Southport 2014 11 129    78345
Name: 11, dtype: int64
Southport 2015 11 130    80899
Name: 11, dtype: int64
Southport 2016 11 130    96536
Name: 11, dtype: int64
Southport 2017 11 130    89470

Name: 11, dtype: int64
Southport 2018 11 130    0
Name: 11, dtype: int64
Southport 2019 11 129    82039
Name: 11, dtype: int64
Southport 2013 12 129    78575
Name: 12, dtype: int64
Southport 2014 12 129    79252
Name: 12, dtype: int64
Southport 2015 12 130    80520
Name: 12, dtype: int64
Southport 2016 12 130    80896
Name: 12, dtype: int64
Southport 2017 12 130    81461
Name: 12, dtype: int64
Southport 2018 12 130    0
Name: 12, dtype: int64
Southport 2019 12 129    76758
Name: 12, dtype: int64
Sox-35th-Dan Ryan 2013 1 130    108260
Name: 1, dtype: int64
Sox-35th-Dan Ryan 2014 1 130    94360
Name: 1, dtype: int64
Sox-35th-Dan Ryan 2015 1 131    113733
Name: 1, dtype: int64
Sox-35th-Dan Ryan 2016 1 131    113909
Name: 1, dtype: int64
Sox-35th-Dan Ryan 2017 1 131    103950
Name: 1, dtype: int64
Sox-35th-Dan Ryan 2018 1 131    97240
Name: 1, dtype: int64
Sox-35th-Dan Ryan 2019 1 130    83453
Name: 1, dtype: int64
Sox-35th-Dan Ryan 2013 2 130    102888
Name: 2, dtype: int64
Sox-35th-Dan Ryan 2014 2 130    105121
Name: 2, dtype: int64
Sox-35th-Dan Ryan 2015 2 131    107193
Name: 2, dtype: int64
Sox-35th-Dan Ryan 2016 2 131    118079
Name: 2, dtype: int64
Sox-35th-Dan Ryan 2017 2 131    104993
Name: 2, dtype: int64
Sox-35th-Dan Ryan 2018 2 131    94049
Name: 2, dtype: int64
Sox-35th-Dan Ryan 2019 2 130    89983
Name: 2, dtype: int64
Sox-35th-Dan Ryan 2013 3 130    114423
Name: 3, dtype: int64
Sox-35th-Dan Ryan 2014 3 130    124521
Name: 3, dtype: int64
Sox-35th-Dan Ryan 2015 3 131    129029
Name: 3, dtype: int64
Sox-35th-Dan Ryan 2016 3 131    128961
Name: 3, dtype: int64
Sox-35th-Dan Ryan 2017 3 131    118531
Name: 3, dtype: int64
Sox-35th-Dan Ryan 2018 3 131    105990
Name: 3, dtype: int64
Sox-35th-Dan Ryan 2019 3 130    98406
Name: 3, dtype: int64
Sox-35th-Dan Ryan 2013 4 130    144679
Name: 4, dtype: int64
Sox-35th-Dan Ryan 2014 4 130    149142
Name: 4, dtype: int64
Sox-35th-Dan Ryan 2015 4 131    148244
Name: 4, dtype: int64
Sox-35th-Dan Ryan 2016 4 131    141608
Name: 4, dtype: int64
Sox-35th-Dan Ryan 2017 4 131    134300
Name: 4, dtype: int64
Sox-35th-Dan Ryan 2018 4 131    121668
Name: 4, dtype: int64
Sox-35th-Dan Ryan 2019 4 130    117331
Name: 4, dtype: int64
Sox-35th-Dan Ryan 2013 5 130    76498
Name: 5, dtype: int64
Sox-35th-Dan Ryan 2014 5 130    161310
Name: 5, dtype: int64
Sox-35th-Dan Ryan 2015 5 131    155626
Name: 5, dtype: int64
Sox-35th-Dan Ryan 2016 5 131    164366
Name: 5, dtype: int64
Sox-35th-Dan Ryan 2017 5 131    144627
Name: 5, dtype: int64
Sox-35th-Dan Ryan 2018 5 131    132445
Name: 5, dtype: int64
Sox-35th-Dan Ryan 2019 5 130    136602
Name: 5, dtype: int64
Sox-35th-Dan Ryan 2013 6 130    0
Name: 6, dtype: int64
Sox-35th-Dan Ryan 2014 6 130    143981
Name: 6, dtype: int64
Sox-35th-Dan Ryan 2015 6 131    154259
Name: 6, dtype: int64
Sox-35th-Dan Ryan 2016 6 131    159730
Name: 6, dtype: int64
Sox-35th-Dan Ryan 2017 6 131    143136
Name: 6, dtype: int64
Sox-35th-Dan Ryan 2018 6 131    143895
Name: 6, dtype: int64
Sox-35th-Dan Ryan 2019 6 130    137121
Name: 6, dtype: int64
Sox-35th-Dan Ryan 2013 7 130    0
Name: 7, dtype: int64
Sox-35th-Dan Ryan 2014 7 130    150821
Name: 7, dtype: int64
Sox-35th-Dan Ryan 2015 7 131    175015
Name: 7, dtype: int64
Sox-35th-Dan Ryan 2016 7 131    163795
Name: 7, dtype: int64
Sox-35th-Dan Ryan 2017 7 131    157501
Name: 7, dtype: int64
Sox-35th-Dan Ryan 2018 7 131    133195
Name: 7, dtype: int64
Sox-35th-Dan Ryan 2019 7 130    146868
Name: 7, dtype: int64
Sox-35th-Dan Ryan 2013 8 130    0
Name: 8, dtype: int64
Sox-35th-Dan Ryan 2014 8 130    167846
Name: 8, dtype: int64
Sox-35th-Dan Ryan 2015 8 131    175988
Name: 8, dtype: int64
Sox-35th-Dan Ryan 2016 8 131    151925
Name: 8, dtype: int64
Sox-35th-Dan Ryan 2017 8 131    153198
Name: 8, dtype: int64
Sox-35th-Dan Ryan 2018 8 131    0
Name: 8, dtype: int64
Sox-35th-Dan Ryan 2019 8 130    141272
Name: 8, dtype: int64
Sox-35th-Dan Ryan 2013 9 130    42005
Name: 9, dtype: int64
Sox-35th-Dan Ryan 2014 9 130    160086
Name: 9, dtype: int64
Sox-35th-Dan Ryan 2015 9 131    157870
Name: 9, dtype: int64
Sox-35th-Dan Ryan 2016 9 131    159876
Name: 9, dtype: int64
Sox-35th-Dan Ryan 2017 9 131    150667
Name: 9, dtype: int64
Sox-35th-Dan Ryan 2018 9 131    0
Name: 9, dtype: int64
Sox-35th-Dan Ryan 2019 9 130    131538
Name: 9, dtype: int64
Sox-35th-Dan Ryan 2013 10 130    107171
Name: 10, dtype: int64
Sox-35th-Dan Ryan 2014 10 130    149835
Name: 10, dtype: int64
Sox-35th-Dan Ryan 2015 10 131    154986
Name: 10, dtype: int64
Sox-35th-Dan Ryan 2016 10 131    138598
Name: 10, dtype: int64
Sox-35th-Dan Ryan 2017 10 131    128256
Name: 10, dtype: int64
Sox-35th-Dan Ryan 2018 10 131    0
Name: 10, dtype: int64
Sox-35th-Dan Ryan 2019 10 130    117323
Name: 10, dtype: int64
Sox-35th-Dan Ryan 2013 11 130    93040
Name: 11, dtype: int64
Sox-35th-Dan Ryan 2014 11 130    122592
Name: 11, dtype: int64
Sox-35th-Dan Ryan 2015 11 131    125216
Name: 11, dtype: int64
Sox-35th-Dan Ryan 2016 11 131    121167
Name: 11, dtype: int64
Sox-35th-Dan Ryan 2017 11 131    109844
Name: 11, dtype: int64
Sox-35th-Dan Ryan 2018 11 131    0
Name: 11, dtype: int64
Sox-35th-Dan Ryan 2019 11 130    100860
Name: 11, dtype: int64
Sox-35th-Dan Ryan 2013 12 130    0
Name: 12, dtype: int64
Sox-35th-Dan Ryan 2014 12 130    116753
Name: 12, dtype: int64
Sox-35th-Dan Ryan 2015 12 131    115571
Name: 12, dtype: int64
Sox-35th-Dan Ryan 2016 12 131    99054
Name: 12, dtype: int64
Sox-35th-Dan Ryan 2017 12 131    95314
Name: 12, dtype: int64
Sox-35th-Dan Ryan 2018 12 131    0
Name: 12, dtype: int64
Sox-35th-Dan Ryan 2019 12 130    90362
Name: 12, dtype: int64
State/Lake 2013 1 131    228785
Name: 1, dtype: int64
State/Lake 2014 1 131    216467
Name: 1, dtype: int64
State/Lake 2015 1 132    224862
Name: 1, dtype: int64
State/Lake 2016 1 132    224840
Name: 1, dtype: int64
State/Lake 2017 1 132    225840
Name: 1, dtype: int64
State/Lake 2018 1 132    267004
Name: 1, dtype: int64
State/Lake 2019 1 131    252316
Name: 1, dtype: int64
State/Lake 2013 2 131    234884
Name: 2, dtype: int64
State/Lake 2014 2 131    225101
Name: 2, dtype: int64
State/Lake 2015 2 132    236221
Name: 2, dtype: int64
State/Lake 2016 2 132    236252
Name: 2, dtype: int64
State/Lake 2017 2 132    227435
Name: 2, dtype: int64
State/Lake 2018 2 132    261659
Name: 2, dtype: int64
State/Lake 2019 2 131    268052
Name: 2, dtype: int64
State/Lake 2013 3 131    219506
Name: 3, dtype: int64
State/Lake 2014 3 131    266014
Name: 3, dtype: int64
State/Lake 2015 3 132    263163
Name: 3, dtype: int64
State/Lake 2016 3 132    269581
Name: 3, dtype: int64
State/Lake 2017 3 132    256736
Name: 3, dtype: int64
State/Lake 2018 3 132    311266
Name: 3, dtype: int64
State/Lake 2019 3 131    311586
Name: 3, dtype: int64
State/Lake 2013 4 131    247717
Name: 4, dtype: int64
State/Lake 2014 4 131    263736
Name: 4, dtype: int64
State/Lake 2015 4 132    267694
Name: 4, dtype: int64
State/Lake 2016 4 132    260382
Name: 4, dtype: int64
State/Lake 2017 4 132    248542
Name: 4, dtype: int64
State/Lake 2018 4 132    300024
Name: 4, dtype: int64
State/Lake 2019 4 131    311301
Name: 4, dtype: int64
State/Lake 2013 5 131    233449
Name: 5, dtype: int64
State/Lake 2014 5 131    251990
Name: 5, dtype: int64
State/Lake 2015 5 132    259768
Name: 5, dtype: int64
State/Lake 2016 5 132    265108
Name: 5, dtype: int64
State/Lake 2017 5 132    262966
Name: 5, dtype: int64
State/Lake 2018 5 132    317500
Name: 5, dtype: int64
State/Lake 2019 5 131    326223
Name: 5, dtype: int64
State/Lake 2013 6 131    255114
Name: 6, dtype: int64
State/Lake 2014 6 131    264457
Name: 6, dtype: int64
State/Lake 2015 6 132    286456
Name: 6, dtype: int64
State/Lake 2016 6 132    253795
Name: 6, dtype: int64
State/Lake 2017 6 132    273411
Name: 6, dtype: int64
State/Lake 2018 6 132    327193
Name: 6, dtype: int64
State/Lake 2019 6 131    334540
Name: 6, dtype: int64
State/Lake 2013 7 131    279725
Name: 7, dtype: int64
State/Lake 2014 7 131    279712
Name: 7, dtype: int64
State/Lake 2015 7 132    313698
Name: 7, dtype: int64
State/Lake 2016 7 132    282749
Name: 7, dtype: int64
State/Lake 2017 7 132    278173
Name: 7, dtype: int64
State/Lake 2018 7 132    0
Name: 7, dtype: int64
State/Lake 2019 7 131    349822
Name: 7, dtype: int64
State/Lake 2013 8 131    278246
Name: 8, dtype: int64
State/Lake 2014 8 131    269567
Name: 8, dtype: int64
State/Lake 2015 8 132    297821
Name: 8, dtype: int64
State/Lake 2016 8 132    269054
Name: 8, dtype: int64
State/Lake 2017 8 132    277744
Name: 8, dtype: int64
State/Lake 2018 8 132    0
Name: 8, dtype: int64
State/Lake 2019 8 131    341992
Name: 8, dtype: int64
State/Lake 2013 9 131    279287
Name: 9, dtype: int64
State/Lake 2014 9 131    279292
Name: 9, dtype: int64
State/Lake 2015 9 132    314867
Name: 9, dtype: int64
State/Lake 2016 9 132    281477
Name: 9, dtype: int64
State/Lake 2017 9 132    326587
Name: 9, dtype: int64
State/Lake 2018 9 132    0
Name: 9, dtype: int64
State/Lake 2019 9 131    339470
Name: 9, dtype: int64
State/Lake 2013 10 131    304611
Name: 10, dtype: int64
State/Lake 2014 10 131    297857
Name: 10, dtype: int64
State/Lake 2015 10 132    315981
Name: 10, dtype: int64
State/Lake 2016 10 132    300459
Name: 10, dtype: int64
State/Lake 2017 10 132    342753
Name: 10, dtype: int64
State/Lake 2018 10 132    0
Name: 10, dtype: int64
State/Lake 2019 10 131    371217
Name: 10, dtype: int64
State/Lake 2013 11 131    257581
Name: 11, dtype: int64
State/Lake 2014 11 131    245923
Name: 11, dtype: int64
State/Lake 2015 11 132    268155
Name: 11, dtype: int64
State/Lake 2016 11 132    275210
Name: 11, dtype: int64
State/Lake 2017 11 132    326527
Name: 11, dtype: int64
State/Lake 2018 11 132    0
Name: 11, dtype: int64
State/Lake 2019 11 131    305288
Name: 11, dtype: int64
State/Lake 2013 12 131    224655
Name: 12, dtype: int64
State/Lake 2014 12 131    232090
Name: 12, dtype: int64
State/Lake 2015 12 132    247108
Name: 12, dtype: int64
State/Lake 2016 12 132    227894
Name: 12, dtype: int64
State/Lake 2017 12 132    259780
Name: 12, dtype: int64
State/Lake 2018 12 132    0
Name: 12, dtype: int64
State/Lake 2019 12 131    271380
Name: 12, dtype: int64
Thorndale 2013 1 132    72429
Name: 1, dtype: int64
Thorndale 2014 1 132    76715
Name: 1, dtype: int64
Thorndale 2015 1 133    80534
Name: 1, dtype: int64
Thorndale 2016 1 133    83397
Name: 1, dtype: int64
Thorndale 2017 1 133    80199
Name: 1, dtype: int64
Thorndale 2018 1 133    78018
Name: 1, dtype: int64
Thorndale 2019 1 132    71729
Name: 1, dtype: int64
Thorndale 2013 2 132    69208
Name: 2, dtype: int64
Thorndale 2014 2 132    79231
Name: 2, dtype: int64
Thorndale 2015 2 133    76957
Name: 2, dtype: int64
Thorndale 2016 2 133    84353
Name: 2, dtype: int64
Thorndale 2017 2 133    78477
Name: 2, dtype: int64
Thorndale 2018 2 133    76168
Name: 2, dtype: int64
Thorndale 2019 2 132    73011
Name: 2, dtype: int64
Thorndale 2013 3 132    75750
Name: 3, dtype: int64
Thorndale 2014 3 132    87483
Name: 3, dtype: int64
Thorndale 2015 3 133    86916
Name: 3, dtype: int64
Thorndale 2016 3 133    90812
Name: 3, dtype: int64
Thorndale 2017 3 133    90559
Name: 3, dtype: int64
Thorndale 2018 3 133    84400
Name: 3, dtype: int64
Thorndale 2019 3 132    79751
Name: 3, dtype: int64
Thorndale 2013 4 132    76980
Name: 4, dtype: int64
Thorndale 2014 4 132    82553
Name: 4, dtype: int64
Thorndale 2015 4 133    81809
Name: 4, dtype: int64
Thorndale 2016 4 133    84381
Name: 4, dtype: int64
Thorndale 2017 4 133    79271
Name: 4, dtype: int64
Thorndale 2018 4 133    81350
Name: 4, dtype: int64
Thorndale 2019 4 132    76337
Name: 4, dtype: int64
Thorndale 2013 5 132    78881
Name: 5, dtype: int64
Thorndale 2014 5 132    87198
Name: 5, dtype: int64
Thorndale 2015 5 133    87221
Name: 5, dtype: int64
Thorndale 2016 5 133    87945
Name: 5, dtype: int64
Thorndale 2017 5 133    87640
Name: 5, dtype: int64
Thorndale 2018 5 133    85844
Name: 5, dtype: int64
Thorndale 2019 5 132    81435
Name: 5, dtype: int64
Thorndale 2013 6 132    77113
Name: 6, dtype: int64
Thorndale 2014 6 132    80646
Name: 6, dtype: int64
Thorndale 2015 6 133    86271
Name: 6, dtype: int64
Thorndale 2016 6 133    86226
Name: 6, dtype: int64
Thorndale 2017 6 133    84775
Name: 6, dtype: int64
Thorndale 2018 6 133    81162
Name: 6, dtype: int64
Thorndale 2019 6 132    77671
Name: 6, dtype: int64
Thorndale 2013 7 132    76247
Name: 7, dtype: int64
Thorndale 2014 7 132    79557
Name: 7, dtype: int64
Thorndale 2015 7 133    83073
Name: 7, dtype: int64
Thorndale 2016 7 133    79965
Name: 7, dtype: int64
Thorndale 2017 7 133    75282
Name: 7, dtype: int64
Thorndale 2018 7 133    75722
Name: 7, dtype: int64
Thorndale 2019 7 132    81668
Name: 7, dtype: int64
Thorndale 2013 8 132    82271
Name: 8, dtype: int64
Thorndale 2014 8 132    79131
Name: 8, dtype: int64
Thorndale 2015 8 133    82195
Name: 8, dtype: int64
Thorndale 2016 8 133    80207
Name: 8, dtype: int64
Thorndale 2017 8 133    81272
Name: 8, dtype: int64
Thorndale 2018 8 133    0
Name: 8, dtype: int64
Thorndale 2019 8 132    79896
Name: 8, dtype: int64
Thorndale 2013 9 132    87385
Name: 9, dtype: int64
Thorndale 2014 9 132    88033
Name: 9, dtype: int64
Thorndale 2015 9 133    89534
Name: 9, dtype: int64
Thorndale 2016 9 133    88131
Name: 9, dtype: int64
Thorndale 2017 9 133    87204
Name: 9, dtype: int64
Thorndale 2018 9 133    0
Name: 9, dtype: int64
Thorndale 2019 9 132    85068
Name: 9, dtype: int64
Thorndale 2013 10 132    95380
Name: 10, dtype: int64
Thorndale 2014 10 132    94739
Name: 10, dtype: int64
Thorndale 2015 10 133    96366
Name: 10, dtype: int64
Thorndale 2016 10 133    93496
Name: 10, dtype: int64
Thorndale 2017 10 133    89869
Name: 10, dtype: int64
Thorndale 2018 10 133    0
Name: 10, dtype: int64
Thorndale 2019 10 132    81980
Name: 10, dtype: int64
Thorndale 2013 11 132    83635
Name: 11, dtype: int64
Thorndale 2014 11 132    80016
Name: 11, dtype: int64
Thorndale 2015 11 133    82274
Name: 11, dtype: int64
Thorndale 2016 11 133    85170
Name: 11, dtype: int64
Thorndale 2017 11 133    82388
Name: 11, dtype: int64
Thorndale 2018 11 133    0
Name: 11, dtype: int64
Thorndale 2019 11 132    74385
Name: 11, dtype: int64
Thorndale 2013 12 132    78291
Name: 12, dtype: int64
Thorndale 2014 12 132    79466
Name: 12, dtype: int64
Thorndale 2015 12 133    80717
Name: 12, dtype: int64
Thorndale 2016 12 133    77966
Name: 12, dtype: int64
Thorndale 2017 12 133    75206
Name: 12, dtype: int64
Thorndale 2018 12 133    0
Name: 12, dtype: int64
Thorndale 2019 12 132    67131
Name: 12, dtype: int64
UIC-Halsted 2013 1 133    133498
Name: 1, dtype: int64
UIC-Halsted 2014 1 133    131804
Name: 1, dtype: int64
UIC-Halsted 2015 1 134    129237
Name: 1, dtype: int64
UIC-Halsted 2016 1 134    138126
Name: 1, dtype: int64
UIC-Halsted 2017 1 134    145715
Name: 1, dtype: int64
UIC-Halsted 2018 1 134    127010
Name: 1, dtype: int64
UIC-Halsted 2019 1 133    120000
Name: 1, dtype: int64
UIC-Halsted 2013 2 133    160232
Name: 2, dtype: int64
UIC-Halsted 2014 2 133    159442
Name: 2, dtype: int64
UIC-Halsted 2015 2 134    148153
Name: 2, dtype: int64
UIC-Halsted 2016 2 134    170623
Name: 2, dtype: int64
UIC-Halsted 2017 2 134    159132
Name: 2, dtype: int64
UIC-Halsted 2018 2 134    154883
Name: 2, dtype: int64
UIC-Halsted 2019 2 133    163805
Name: 2, dtype: int64

UIC-Halsted 2013 3 133    150883
Name: 3, dtype: int64
UIC-Halsted 2014 3 133    156023
Name: 3, dtype: int64
UIC-Halsted 2015 3 134    147237
Name: 3, dtype: int64
UIC-Halsted 2016 3 134    164142
Name: 3, dtype: int64
UIC-Halsted 2017 3 134    157200
Name: 3, dtype: int64
UIC-Halsted 2018 3 134    152779
Name: 3, dtype: int64
UIC-Halsted 2019 3 133    148919
Name: 3, dtype: int64
UIC-Halsted 2013 4 133    171560
Name: 4, dtype: int64
UIC-Halsted 2014 4 133    173562
Name: 4, dtype: int64
UIC-Halsted 2015 4 134    159544
Name: 4, dtype: int64
UIC-Halsted 2016 4 134    169558
Name: 4, dtype: int64
UIC-Halsted 2017 4 134    157007
Name: 4, dtype: int64
UIC-Halsted 2018 4 134    161699
Name: 4, dtype: int64
UIC-Halsted 2019 4 133    170257
Name: 4, dtype: int64
UIC-Halsted 2013 5 133    114755
Name: 5, dtype: int64
UIC-Halsted 2014 5 133    110805
Name: 5, dtype: int64
UIC-Halsted 2015 5 134    96550
Name: 5, dtype: int64
UIC-Halsted 2016 5 134    96639
Name: 5, dtype: int64
UIC-Halsted 2017 5 134    98213
Name: 5, dtype: int64
UIC-Halsted 2018 5 134    111593
Name: 5, dtype: int64
UIC-Halsted 2019 5 133    111884
Name: 5, dtype: int64
UIC-Halsted 2013 6 133    95195
Name: 6, dtype: int64
UIC-Halsted 2014 6 133    93448
Name: 6, dtype: int64
UIC-Halsted 2015 6 134    92872
Name: 6, dtype: int64
UIC-Halsted 2016 6 134    94936
Name: 6, dtype: int64
UIC-Halsted 2017 6 134    94505
Name: 6, dtype: int64
UIC-Halsted 2018 6 134    88404
Name: 6, dtype: int64
UIC-Halsted 2019 6 133    89373
Name: 6, dtype: int64
UIC-Halsted 2013 7 133    108271
Name: 7, dtype: int64
UIC-Halsted 2014 7 133    102351
Name: 7, dtype: int64
UIC-Halsted 2015 7 134    97767
Name: 7, dtype: int64
UIC-Halsted 2016 7 134    92950
Name: 7, dtype: int64
UIC-Halsted 2017 7 134    90720
Name: 7, dtype: int64
UIC-Halsted 2018 7 134    91857
Name: 7, dtype: int64
UIC-Halsted 2019 7 133    96735
Name: 7, dtype: int64
UIC-Halsted 2013 8 133    121806
Name: 8, dtype: int64
UIC-Halsted 2014 8 133    118997
Name: 8, dtype: int64
UIC-Halsted 2015 8 134    120496
Name: 8, dtype: int64
UIC-Halsted 2016 8 134    133019
Name: 8, dtype: int64
UIC-Halsted 2017 8 134    114846
Name: 8, dtype: int64
UIC-Halsted 2018 8 134    0
Name: 8, dtype: int64
UIC-Halsted 2019 8 133    121219
Name: 8, dtype: int64
UIC-Halsted 2013 9 133    168815
Name: 9, dtype: int64
UIC-Halsted 2014 9 133    187470
Name: 9, dtype: int64
UIC-Halsted 2015 9 134    196646
Name: 9, dtype: int64
UIC-Halsted 2016 9 134    195648
Name: 9, dtype: int64
UIC-Halsted 2017 9 134    193684
Name: 9, dtype: int64
UIC-Halsted 2018 9 134    0
Name: 9, dtype: int64
UIC-Halsted 2019 9 133    200995
Name: 9, dtype: int64
UIC-Halsted 2013 10 133    211508
Name: 10, dtype: int64
UIC-Halsted 2014 10 133    202553
Name: 10, dtype: int64
UIC-Halsted 2015 10 134    210598
Name: 10, dtype: int64
UIC-Halsted 2016 10 134    200754
Name: 10, dtype: int64
UIC-Halsted 2017 10 134    206824
Name: 10, dtype: int64
UIC-Halsted 2018 10 134    0
Name: 10, dtype: int64
UIC-Halsted 2019 10 133    222190
Name: 10, dtype: int64
UIC-Halsted 2013 11 133    172468
Name: 11, dtype: int64
UIC-Halsted 2014 11 133    156045
Name: 11, dtype: int64
UIC-Halsted 2015 11 134    173267
Name: 11, dtype: int64
UIC-Halsted 2016 11 134    179153
Name: 11, dtype: int64
UIC-Halsted 2017 11 134    177054
Name: 11, dtype: int64
UIC-Halsted 2018 11 134    0
Name: 11, dtype: int64
UIC-Halsted 2019 11 133    177206
Name: 11, dtype: int64
UIC-Halsted 2013 12 133    106312
Name: 12, dtype: int64
UIC-Halsted 2014 12 133    102608
Name: 12, dtype: int64
UIC-Halsted 2015 12 134    104443
Name: 12, dtype: int64
UIC-Halsted 2016 12 134    90009
Name: 12, dtype: int64
UIC-Halsted 2017 12 134    108064
Name: 12, dtype: int64
UIC-Halsted 2018 12 134    0
Name: 12, dtype: int64
UIC-Halsted 2019 12 133    106456
Name: 12, dtype: int64
Washington/Dearborn 2013 1 134    219972
Name: 1, dtype: int64
Washington/Dearborn 2014 1 134    252944
Name: 1, dtype: int64
Washington/Dearborn 2015 1 135    257556
Name: 1, dtype: int64
Washington/Dearborn 2016 1 135    275435
Name: 1, dtype: int64
Washington/Dearborn 2017 1 135    293173
Name: 1, dtype: int64
Washington/Dearborn 2018 1 135    300772
Name: 1, dtype: int64
Washington/Dearborn 2019 1 134    300816
Name: 1, dtype: int64
Washington/Dearborn 2013 2 134    207478
Name: 2, dtype: int64
Washington/Dearborn 2014 2 134    256430
Name: 2, dtype: int64
Washington/Dearborn 2015 2 135    249049
Name: 2, dtype: int64
Washington/Dearborn 2016 2 135    286103
Name: 2, dtype: int64
Washington/Dearborn 2017 2 135    279944
Name: 2, dtype: int64
Washington/Dearborn 2018 2 135    282264
Name: 2, dtype: int64
Washington/Dearborn 2019 2 134    303071
Name: 2, dtype: int64
Washington/Dearborn 2013 3 134    234883
Name: 3, dtype: int64
Washington/Dearborn 2014 3 134    288782
Name: 3, dtype: int64
Washington/Dearborn 2015 3 135    299225
Name: 3, dtype: int64
Washington/Dearborn 2016 3 135    324653
Name: 3, dtype: int64
Washington/Dearborn 2017 3 135    331025
Name: 3, dtype: int64
Washington/Dearborn 2018 3 135    333086
Name: 3, dtype: int64
Washington/Dearborn 2019 3 134    344872
Name: 3, dtype: int64
Washington/Dearborn 2013 4 134    238357
Name: 4, dtype: int64
Washington/Dearborn 2014 4 134    278638
Name: 4, dtype: int64
Washington/Dearborn 2015 4 135    292025
Name: 4, dtype: int64
Washington/Dearborn 2016 4 135    303147
Name: 4, dtype: int64
Washington/Dearborn 2017 4 135    303479
Name: 4, dtype: int64
Washington/Dearborn 2018 4 135    314872
Name: 4, dtype: int64
Washington/Dearborn 2019 4 134    342058
Name: 4, dtype: int64
Washington/Dearborn 2013 5 134    247608
Name: 5, dtype: int64
Washington/Dearborn 2014 5 134    286495
Name: 5, dtype: int64
Washington/Dearborn 2015 5 135    296065
Name: 5, dtype: int64
Washington/Dearborn 2016 5 135    313541
Name: 5, dtype: int64
Washington/Dearborn 2017 5 135    331492
Name: 5, dtype: int64
Washington/Dearborn 2018 5 135    337697
Name: 5, dtype: int64
Washington/Dearborn 2019 5 134    358542
Name: 5, dtype: int64
Washington/Dearborn 2013 6 134    271634
Name: 6, dtype: int64
Washington/Dearborn 2014 6 134    293678
Name: 6, dtype: int64
Washington/Dearborn 2015 6 135    323356
Name: 6, dtype: int64
Washington/Dearborn 2016 6 135    339418
Name: 6, dtype: int64
Washington/Dearborn 2017 6 135    355223
Name: 6, dtype: int64
Washington/Dearborn 2018 6 135    348741
Name: 6, dtype: int64
Washington/Dearborn 2019 6 134    362993
Name: 6, dtype: int64
Washington/Dearborn 2013 7 134    296869
Name: 7, dtype: int64
Washington/Dearborn 2014 7 134    311158
Name: 7, dtype: int64
Washington/Dearborn 2015 7 135    340362
Name: 7, dtype: int64
Washington/Dearborn 2016 7 135    329617
Name: 7, dtype: int64
Washington/Dearborn 2017 7 135    338347
Name: 7, dtype: int64
Washington/Dearborn 2018 7 135    350474
Name: 7, dtype: int64
Washington/Dearborn 2019 7 134    375766
Name: 7, dtype: int64
Washington/Dearborn 2013 8 134    294865
Name: 8, dtype: int64
Washington/Dearborn 2014 8 134    295912
Name: 8, dtype: int64
Washington/Dearborn 2015 8 135    314693
Name: 8, dtype: int64
Washington/Dearborn 2016 8 135    335718
Name: 8, dtype: int64
Washington/Dearborn 2017 8 135    358084
Name: 8, dtype: int64
Washington/Dearborn 2018 8 135    0
Name: 8, dtype: int64
Washington/Dearborn 2019 8 134    371610
Name: 8, dtype: int64
Washington/Dearborn 2013 9 134    275025
Name: 9, dtype: int64
Washington/Dearborn 2014 9 134    286907
Name: 9, dtype: int64
Washington/Dearborn 2015 9 135    313378
Name: 9, dtype: int64
Washington/Dearborn 2016 9 135    317019
Name: 9, dtype: int64
Washington/Dearborn 2017 9 135    327611
Name: 9, dtype: int64
Washington/Dearborn 2018 9 135    0
Name: 9, dtype: int64
Washington/Dearborn 2019 9 134    345935
Name: 9, dtype: int64
Washington/Dearborn 2013 10 134    306273
Name: 10, dtype: int64
Washington/Dearborn 2014 10 134    309950
Name: 10, dtype: int64
Washington/Dearborn 2015 10 135    329559
Name: 10, dtype: int64
Washington/Dearborn 2016 10 135    335944
Name: 10, dtype: int64
Washington/Dearborn 2017 10 135    353740
Name: 10, dtype: int64
Washington/Dearborn 2018 10 135    0
Name: 10, dtype: int64
Washington/Dearborn 2019 10 134    390665
Name: 10, dtype: int64
Washington/Dearborn 2013 11 134    287455
Name: 11, dtype: int64
Washington/Dearborn 2014 11 134    273137
Name: 11, dtype: int64
Washington/Dearborn 2015 11 135    299714
Name: 11, dtype: int64
Washington/Dearborn 2016 11 135    330452
Name: 11, dtype: int64
Washington/Dearborn 2017 11 135    336327
Name: 11, dtype: int64
Washington/Dearborn 2018 11 135    0
Name: 11, dtype: int64
Washington/Dearborn 2019 11 134    346886
Name: 11, dtype: int64
Washington/Dearborn 2013 12 134    295484
Name: 12, dtype: int64
Washington/Dearborn 2014 12 134    297768
Name: 12, dtype: int64
Washington/Dearborn 2015 12 135    318676
Name: 12, dtype: int64
Washington/Dearborn 2016 12 135    313908
Name: 12, dtype: int64
Washington/Dearborn 2017 12 135    314314
Name: 12, dtype: int64
Washington/Dearborn 2018 12 135    0
Name: 12, dtype: int64
Washington/Dearborn 2019 12 134    333734
Name: 12, dtype: int64
Washington/Wabash 2013 1 Series([], Name: 1, dtype: int64)
Washington/Wabash 2014 1 Series([], Name: 1, dtype: int64)

Washington/Wabash 2015 1 Series([], Name: 1, dtype: int64)
Washington/Wabash 2016 1 Series([], Name: 1, dtype: int64)
Washington/Wabash 2017 1 136    242410
Name: 1, dtype: int64
Washington/Wabash 2018 1 136    225310
Name: 1, dtype: int64
Washington/Wabash 2019 1 135    215300
Name: 1, dtype: int64
Washington/Wabash 2013 2 Series([], Name: 2, dtype: int64)
Washington/Wabash 2014 2 Series([], Name: 2, dtype: int64)
Washington/Wabash 2015 2 Series([], Name: 2, dtype: int64)
Washington/Wabash 2016 2 Series([], Name: 2, dtype: int64)

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [2]:
years = [2013, 2014, 2015, 2016, 2017, 2018, 2019]

for station in riders2020['stationame']:
    for month in range(1,13):
        x = years
        y = []
        for year in years:
            riders[year][(riders[year]['stationame'] == station)][str(month)]
        ds = pd.DataFrame(list(zip(x,y)), columns = ['year','riders'])
        X = ds.iloc[:, 0].values.reshape(-1, 1)  # values converts it into a numpy array
        Y = ds.iloc[:, 1].values.reshape(-1, 1)  # -1 means that calculate the dimension of rows, but have 1 column
        regressor = LinearRegression()  # create object for the class
        regressor.fit(X, Y)  # perform linear regression
        Y_pred = regressor.predict(X)  # make predictions

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

In [2]:
years = [2013, 2014, 2015, 2016, 2017, 2018, 2019]

for station in riders2020['stationame']:
    for month in range(1,13):
        x = years
        y = []
        for year in years:
            riders[year][(riders[year]['stationame'] == station)][str(month)]
        ds = pd.DataFrame(list(zip(x,y)), columns = ['year','riders'])
        X = ds.iloc[:, 0].values.reshape(-1, 1)  # values converts it into a numpy array
        Y = ds.iloc[:, 1].values.reshape(-1, 1)  # -1 means that calculate the dimension of rows, but have 1 column
        regressor = LinearRegression()  # create object for the class
        regressor.fit(X, Y)  # perform linear regression
        Y_pred = regressor.predict(X)  # make predictions

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

In [12]:
for station in allrides['station_name']:
    for month in allrides['month']:
        ds = pd.DataFrame(list(zip(allrides['year'], allrides['riders'])),columns = ['indep','dep'])
        X = ds.iloc[:, 0].values.reshape(-1, 1)  # values converts it into a numpy array
        Y = ds.iloc[:, 1].values.reshape(-1, 1)  # -1 means that calculate the dimension of rows, but have 1 column
        regressor = LinearRegression()  # create object for the class
        regressor.fit(X, Y)  # perform linear regression
        Y_pred = regressor.predict(X)  # make predictions

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').